✅ actions:
  - changed-files:
    - any-glob-to-any-file: .github/**/*

↔️ migrations:
  - changed-files:
    - any-glob-to-any-file:
      - db/migrate/*
      - db/schema.rb

🌱 seeds:
  - changed-files:
    - any-glob-to-any-file:
      - db/seeds/*
      - db/seeds.rb

🐳 docker:
  - changed-files:
    - any-glob-to-any-file:
      - docker_files/*
      - docker-compose.yml

":spider_web: dependencies":
  - changed-files:
    - any-glob-to-any-file:
      - Gemfile
      - Gemfile.lock

💡 To Change Everything:
  - changed-files:
    - any-glob-to-any-file:
      - app/assets/stylesheets/tochangeeverything.scss
      - app/assets/stylesheets/to_change_everything/*
      - app/assets/stylesheets/to_change_everything/**/*
      - app/controllers/to_change_everything_controller.rb
      - app/helpers/to_change_everything_helper.rb
      - app/views/layouts/to_change_everything.html.erb
      - app/views/to_change_everything/*
      - config/locales/to_change_everything/*
      - docs/to-change-everything-guide.md
      - lib/generators/to_change_everything/*
      - public/tce/*
      - public/tce/**/*
