require:
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'db/schema.rb'

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/AbcSize:
  Max: 67

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
  Max: 100

Metrics/ClassLength:
  Max: 131

Metrics/CyclomaticComplexity:
  Max: 12

Layout/LineLength:
  Max: 186
  Exclude:
    - 'db/**/*'

Metrics/MethodLength:
  Max: 27
  Exclude:
    - 'db/migrate/*'

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 14

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/*'

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/system/*'

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5
  Exclude:
    - 'spec/system/*'

Security/Open:
  Exclude:
    - 'lib/tasks/db/import.rake'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/MixinUsage:
  Exclude:
    - 'script/*'
