inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/migrate/20230628052836_init_schema.rb
    - vendor/**/*

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Exclude:
    - db/**/*

# TODO: https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsenvironmentvariableaccess
#       Consider using `Rails.application.config.foo` instead of `ENV['FOO']`
Rails/EnvironmentVariableAccess:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/system/*

RSpec/ExampleLength:
  Max: 14
  Exclude:
    - spec/system/*

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5
  Exclude:
    - spec/system/*

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/MixinUsage:
  Exclude:
    - script/*

# Metrics rules to ignore
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case
