#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew update

  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies..."
    brew bundle
    brew services restart postgresql
  }
fi

if [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
  echo "==> Installing Ruby..."
  rbenv install --skip-existing
  which bundle >/dev/null 2>&1  || {
    gem install bundler
    rbenv rehash
  }
fi

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies..."
  bundle check  || {
    bundle install --quiet --without production
  }
fi

# DELETES all pg databases / software and starts from scratch
# brew services stop postgresql
# brew uninstall postgresql
# rm -rf /usr/local/var/postgres/
# brew install postgresql
# brew services start postgresql
