#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to run.

set -e

# used to check if certain commands are available to script
command_exists () {
  command -v $1 >/dev/null 2>&1 || { echo >&2 "==> I looked for $1, but couldn't find it. Trying something else."; return 1; }
}

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
    brew services restart postgresql
  }
fi

# read the ruby version from .ruby-version file
ruby_version=`cat .ruby-version`

echo "==> Installing Ruby: $ruby_version"
if command_exists rbenv; then
  echo '==> using rbenv for install'
  rbenv install -s $ruby_version
elif command_exists ruby-install; then
  echo '==> using ruby-install for install'
  ruby-install ruby $ruby_version --no-reinstall
  source /usr/local/opt/chruby/share/chruby/chruby.sh
  chruby $ruby_version
else
  echo '==> Did not find rbenv or ruby-install!'
  echo '==> Please install either tool to manage ruby'
  echo '==> rbenv: `brew install rbenv`'
  echo '==> ruby-install: `brew install ruby-install`'
  exit 1
fi

which bundle >/dev/null 2>&1  || {
  gem install bundler
}
