#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew update

  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies..."
    brew bundle
    brew services restart postgresql@9.6
  }
fi

if [ -f "Gemfile" ]; then
  echo "==> Installing Bundler..."
  gem install bundler --pre

  echo "==> Installing gem dependencies..."
  bundle install --quiet --without production
fi
