#!/usr/bin/env ruby

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root
APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)

def system!(*args)
  system(*args) || abort("\n==> Command #{args} failed")
end

chdir APP_ROOT do
  puts '==> Setting up DB...'
  system! 'bundle exec rails db:create'

  puts "==> Tests started at: #{Time.now.strftime("%H:%M:%S")}"

  system! 'bundle exec rspec'
  system! 'bundle exec rubocop'
end

