#!/usr/bin/env ruby

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root
APP_ROOT = Pathname.new File.expand_path('..', __dir__)

def system! *args
  system(*args) || abort("\n==> Command #{args} failed")
end

chdir APP_ROOT do
  puts '==> Setting up DB...'
  system! 'bundle exec rails db:create'

  puts "==> Tests started at: #{Time.now.strftime('%H:%M:%S')}"

  puts '==> Running isolated specs'
  system! 'bundle exec rspec --tag=~read_only_spec'

  puts '==> Running non-isolated, read-only specs'
  system! 'bundle exec rspec --tag=read_only_spec'

  system! 'bundle exec rubocop'
end
