#!/usr/bin/env ruby

# script/console: Launch a console for the application. Optionally allow an
#                 environment to be passed in to let the script handle the
#                 specific requirements for connecting to a console for that
#                 environment.

require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root.
APP_ROOT = Pathname.new File.expand_path('..', __dir__)

def system! *args
  system(*args) || abort("\n==> Command #{args} failed")
end

chdir APP_ROOT do
  if ARGV[0].nil?
    # No argument provided.
    # So run local console in the development environment.
    system! 'bundle exec rails console'
  else
    # Use first argument as an environment name.
    # Use this to decide how to connect to the appropriate console.
    case ARGV[0]
    when 'production'
      system! 'heroku run rails console --app the-crimethinc-production'
    when 'staging'
      system! 'heroku run rails console --app the-crimethinc-staging'
    else
      puts "Sorry, I don’t know how to connect to the #{ARGV[0]} environment."
      `exit 1`
    end
  end
end
