#!/usr/bin/env ruby

# script/seed: Drop the database, rebuild it, and fill it with seed data

require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root.
APP_ROOT = Pathname.new File.expand_path('..', __dir__)

def system! *args
  system(*args) || abort("\n==> Command #{args} failed")
end

chdir APP_ROOT do
  puts '==> Dropping DB…'
  system! 'bundle exec rails db:drop'

  puts '==> Creating DB…'
  system! 'bundle exec rails db:create'

  puts '==> Downloading DB dump from S3…'
  system! 'bundle exec rake db:dump:download'
  puts

  puts '==> Importing pg dump into local development DB…'
  system! 'bundle exec rake db:dump:import'
  puts

  puts '==> All done!'
end
