#!/usr/bin/env ruby

# script/seed: Drop the database, rebuild it, and fill it with seed data

require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root.
APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)

def system!(*args)
  system(*args) || abort("\n==> Command #{args} failed")
end

chdir APP_ROOT do
  system! 'script/bootstrap'

  puts '==> Dropping DB…'
  system! 'bin/rails db:drop'

  puts '==> Creating DB…'
  system! 'bin/rails db:create'

  puts '==> Migrating DB…'
  system! 'bin/rails db:migrate'

  puts '==> Seeding DB…'
  system! 'bin/rails db:seed'

  puts '==> DB is now ready to go!'
end
