#!/usr/bin/env ruby

# script/server: Launch the application and any extra required processes locally.

require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root.
APP_ROOT = Pathname.new File.expand_path('..', __dir__)

def system! *args
  system(*args) || abort("\n==> Command #{args} failed")
end

chdir APP_ROOT do
  # ensure everything in the app is up to date.
  system! 'script/update'

  puts '==> Opening site in browser'
  puts '==> README: Refresh your browser after server is started'
  system! 'open http://localhost:3000'

  puts '==> Starting Server'
  system! 'rails server -p 3000'
  puts
end
