#!/usr/bin/env ruby

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root.
APP_ROOT = Pathname.new File.expand_path('..', __dir__)

def system! *args
  system(*args) || abort("\n==> Command #{args} failed")
end

chdir APP_ROOT do
  system! 'script/bootstrap'

  puts '==> Installing dependencies'
  system! 'gem install bundler --conservative'
  system('bundle check') || system!('bundle install')

  puts '==> Starting postgresql'
  system! 'brew services start postgresql'

  puts '==> Preparing database'
  system! 'bundle exec rails db:create'
  system! 'bundle exec rails db:migrate'

  puts '==> Removing old logs and tempfiles'
  system! 'bundle exec rails log:clear tmp:clear'

  puts '==> App is now setup!'
  puts '==> Next step is:'
  puts '    ./script/server'
end
