#!/usr/bin/env ruby

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.

require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root
APP_ROOT = Pathname.new File.expand_path('..', __dir__)

def system! *args
  system(*args) || abort("\n==> Command #{args} failed")
end

chdir APP_ROOT do
  # ensure everything in the app is up to date
  system! 'script/update'

  # boot the app and any other necessary processes
  system! 'bundle exec guard'
end
