#!/bin/sh

# script/server: Launch the application and any extra required processes locally.

set -e

cd "$(dirname "$0")/.."

export RAILS_ENV="test" RACK_ENV="test"

# ensure everything in the app is up to date.
script/update

# ensure DB is reset to devs
bin/rake db:test:clone

# boot the app and any other necessary processes.
bundle exec guard
