#!/usr/bin/env ruby

# script/update: Update application to run for its current checkout.

require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root.
APP_ROOT = Pathname.new File.expand_path('..', __dir__)

def system! *args
  system(*args) || abort("\n==> Command #{args} failed")
end

chdir APP_ROOT do
  system! 'script/bootstrap'

  puts '==> Installing dependencies'
  system! 'gem install bundler'
  system('bundle check') || system!('bundle install')

  puts '==> Updating database'
  # TEMP: RUBYOPT is to silence warning between Ruby 2.7.0 and Rails 6.0.2.2
  system! "RUBYOPT='-W:no-deprecated -W:no-experimental' bundle exec rails db:create"
  system! "RUBYOPT='-W:no-deprecated -W:no-experimental' bundle exec rails db:migrate"
  system! "RUBYOPT='-W:no-deprecated -W:no-experimental' bundle exec rails db:migrate RAILS_ENV=test"

  puts '==> Removing old logs and tempfiles'
  system! 'bundle exec rails log:clear tmp:clear'
end
