<h1>Privilege, Identity, and Conflict at the 2009 CrimethInc. Convergence</h1>
<p>For a basic discussion of some of the issues around privilege, power dynamics, and identity, try <a href="/texts/atoz/underminingoppression.php">&ldquo;Undermining Oppression&rdquo;</a> in our online reading library.</p>
<p>Accounts from the disruption of the convergence are collected <a href="http://www.crimethinc.com/blog/2009/08/03/crimethinc-convergence-controversy/"><strong>here</strong></a> and <a href="http://www.crimethinc.com/blog/2009/08/08/more-convergence-accounts/"><strong>here</strong></a>.</p>
<p>Some have suggested that we should simply see the difficult events at the convergence as a reminder to address the issues of white supremacy and gentrification; meanwhile, all manner of uninformed parties who were not present at the convergence have been commenting about it. We humbly suggest that it might be more appropriate for those who were not at the convergence to focus on discussing gentrification, oppression, and abuse in their own experiences, while listening to those who were present at the convergence when it comes to questions pertaining to it.</p>
<h3>Summary of Events</h3>
<p>After seven years of rural convergences, the organizers of the 2009 convergence agreed it was time to experiment with a new format. In doing so, they set aside a time-honed but predictable template, opening up the possibility of making new discoveries and new errors.</p>
<p>The original plan was to purchase a building in Pittsburgh and transform it into a community center in the course of the convergence. One consistent criticism of the convergences had been that they contributed little to the local communities in which they occurred; with this new approach, the organizers hoped to channel the temporary energy of the convergence into creating something of permanent use to the community that hosted it.</p>
<p>But this proved complicated on many fronts. Purchasing a building is difficult enough in itself apart from the challenges of organizing a convergence. Attempts to assemble a coalition of local collectives to share the community center did not pan out. Finally, the announcement that the G20 summit would be happening in Pittsburgh indicated that the authorities would be especially eager to use any pretext to harass the convergence&mdash;which would be particularly problematic if it took place in a building that was not yet up to code. On top of this, some locals argued that the neighborhood in which the proposed community center would be located was an inappropriate space for a predominantly white gathering. In response to all these concerns, the local organizers shifted their plans, renting a building in the neighborhood where they themselves lived along with a great number of Pittsburgh anarchists. Some of the considerations around this decision were addressed in <a href="#appendix">a text</a> included in the orientation &rsquo;zine distributed at the beginning of the convergence.</p>
<p>Meanwhile, behind the scenes, the organizing group suffered a schism, further complicating matters and subtracting energy and resources from the organizing itself. In the end, it was impressive that the convergence came together at all. Hosting a week-long gathering of hundreds of people is not easy. Because the convergence is free of charge, organizers also had to come up with the resources to rent the building themselves, and to feed and provide for everyone.</p>
<p>The convergence site was a building on Penn Avenue, which forms the boundary between Bloomfield, Pittsburgh&rsquo;s Little Italy, and Garfield, a predominantly African-American neighborhood in the process of gentrification. Some controversy persisted in the month leading up to the event; local organizers felt they had made a real effort to open up dialogue, while an essay entitled &ldquo;Points of Consideration Before, During, and After the CrimethInc. Convergence&rdquo; appeared implying otherwise.</p>
<p>The first five days of the convergence were filled with workshops, games, and discussions. Topics ranged from police tactics and legal support work to permaculture and the challenges of organizing with ADHD; several different workshops dealt with race, gender, and cultural appropriation. A &rsquo;zine library distributed hundreds of &rsquo;zines and books; a free kitchen prepared delicious meals; a mediation team addressed conflicts and accountability processes; a free clinic served the medical needs not only of attendees but also of people from the neighborhood.</p>
<p>There were two lengthy workshops discussing gentrification: the first dealt with general issues, while the second addressed specifically how the convergence affected the neighborhood in which it took place. At the second, it was decided that a letter would be written to be distributed in the neighborhood explaining what the convergence was about, and a potluck open to the community would take place on the final day of the event, to open dialogue and extend resources to locals.</p>
<p>The building itself, it turned out, was simply not big enough to accommodate everyone who came. At previous convergences, the rural setting had offered ample space for participants to take space and time to themselves; but in this context, in the center of Pittsburgh, that was impossible. This exacerbated the challenges and frustrations common at events that include people of a wide range of backgrounds and levels of awareness. For instance, some attendees of color have described the pain of feeling marginalized and isolated, and have stated that other attendees&rsquo; oppressive behavior was not addressed; some queer and trans attendees have recounted people asking inappropriate questions about their gender expression, and interactions with people who otherwise disrespected their identities. Most of the frequently-cited examples of oppressive behavior reference a handful of individuals who had not attended previous convergences and were not representative of the majority of attendees; but the fact remains that both the people who attended the convergence and the policies and structures put in place by the organizers failed to offset this.</p>
<p>On the evening of July 25, approximately 200 anarchists and fellow travelers gathered upstairs in the largest room in the building for a participatory cabaret. At the end of the performances, while everyone was still gathered, a commotion erupted at the back of the room. A half dozen people of color were shouting at everyone else in the room:</p>
<p>&ldquo;Get out of this neighborhood! Get out of Pittsburgh! Do not return for the G20! GO BACK TO EUROPE!&rdquo;</p>
<p>&ldquo;We are NOT pacifists! This is NOT a safe space! Get out of here!&rdquo;</p>
<p>&ldquo;We have solidarity from hundreds of people all across the country!&rdquo;</p>
<p>&ldquo;All your squats, all your infoshops, all your collective houses are gentrifying neighborhoods of color! You think that just because people will nod to you on the street, they want you around? Get in your cars and leave!&rdquo;</p>
<p>(&ldquo;Some people here can&rsquo;t leave!&rdquo;)</p>
<p>&ldquo;Too fucking bad! Get in your car and leave!&rdquo;</p>
<p>The individuals, since described as &ldquo;the disrupters&rdquo; by people of color at the convergence who oppose their action, began to grab people&rsquo;s belongings and throw them out of the space. Others reacted with outrage, and a shouting match ensued; threats were exchanged, but no blows were intentionally struck. The atmosphere was extremely charged; many broke down in tears, and some suffered panic attacks. One person of color who opposed the disrupters&rsquo; actions was called a &ldquo;race traitor.&rdquo;</p>
<p>The disrupters included four participants in the convergence and three people who had just arrived from out of town; they were backed up by two white people who had come to the convergence with those who planned to disrupt it. The two disrupters who had not been &ldquo;in on&rdquo; the action before that day disappeared early on in the events that followed; one reappeared at the &ldquo;caucus&rdquo; at the end, while the other left Pittsburgh immediately and has since said that he regrets his participation.</p>
<p>At first, longtime organizers exchanged glances of confusion: however many convergences and conferences they had organized, however many riots they had participated in and fights they had broken up, no one had dealt with <em>this</em> before.</p>
<p>Many who were not there have been curious as to why no one defended themselves. One complicating factor was that some of the disrupters were participants in the convergence who had been there the whole week, and even the ones who had just appeared were known to attendees; people considered them comrades and wanted to take their concerns seriously. Some young white participants who were still developing their understanding of race and privilege may genuinely have thought that being a white ally meant doing whatever angry people of color told them to do. For others, it was immediately clear that the action was scripted to frame all white attendees as racist, and that almost any measures to resist it would play into this strategy. Some concluded that the conflict playing out in that room at that moment was less important than the one that would play out in discussions over the following months and years, and the first priority was to make sure that nothing happened that could obscure the underlying issues in those discussions.</p>
<p>All these factors made it extremely difficult for people to know how to react, and the disrupters exploited this to the fullest extent they could.</p>
<p>As people fleeing the upstairs gathered outside, the police showed up. Despite the volatility of the situation, they were successfully turned away, though they had been seeking an excuse to enter the space all week.</p>
<p>Eventually, without any formal decision-making, three basic responses crystallized. Some people gathered downstairs, attempting to coordinate housing and rides for the distraught people making their way away from the confrontation. Some remained upstairs, acting as intermediaries with the angriest and most emotional white people, urging them to withdraw from the space and making sure things did not escalate. A couple people of color, not constrained by the fear that their actions could be misconstrued, confronted the disrupters. This culminated in a physical altercation as several people of color opposing the disruption attempted to force the disrupters out of the room. The two &ldquo;white allies&rdquo; who were there to support the disruption engaged physically in this conflict, while white organizers made sure other white people stayed out of it.</p>
<p>Ultimately, although significantly more people of color opposed the disruption than participated in it, some were mired into inaction that night by complicated feelings of alienation both from the disrupters and from some of the other convergence participants. When all the white people had finally left the space, there was a brief attempt at discussion between the disrupters and the remaining people of color who opposed them. The disrupters only repeated their dogmatic rhetoric justifying their actions; both parties concluded that dialogue was impossible. The disrupters came downstairs and stood around outside for a while before all leaving in a group. Some convergence participants slept in the building that night, but many had already left the area to sleep in their vehicles, at locals&rsquo; houses, in the nearby graveyard, or in other spaces such as at the Pittsburgh airport. Some left Pittsburgh entirely.</p>
<p>On Saturday, people slowly regrouped at the building and then at the Really Really Free Market. It was decided that the plans for that evening would be canceled so people could return to the building to discuss the previous night&rsquo;s events. One concerned young white person worried that it would be disrespectful to return there after being told to leave, until he was reminded that the disrupters had demanded not only that white people leave the building but also that they go to Europe.</p>
<p>That night, the upstairs room was again filled with people. At the suggestion of some of those who had physically resisted the disrupters, the discussion focused on the ways white people had reacted to the disruption. A list was made of all the potentially oppressive or inappropriate things people had said or done in response, and the group went through them one by one, discussing the issues around each until everyone was satisfied. This arduous process lasted late into the evening. Unfortunately, some of the people who might have benefited most from this conversation had already left the convergence, or else were hanging out outside in reactionary disaffection. In this regard, though the disruption did not end the convergence, it fractured it, causing a minority of attendees to leave and another minority to disengage.<a name="analysis" id="analysis"></a></p>
<h3>CrimethInc. vs. CrimethInc., APOC vs. APOC</h3>
<p>Perhaps the first thing to emphasize about the events at the convergence is that it was not a rupture <em>between</em> CrimethInc. and Anarchist People of Color (APOC), but rather twin ruptures <em>within</em> both of them. CrimethInc. and APOC are not membership groups; it is impossible for any single action to represent either. Some of the most active participants in CrimethInc. projects are anarchist people of color, just as there are white people involved who need to do more to combat privilege and white supremacy. Also, although the disruption was calculated to create the appearance of polarization, more people of color opposed and resisted it than participated.</p>
<p>The false opposition of &ldquo;CrimethInc. vs. APOC&rdquo; serves quite a few questionable agendas. It&rsquo;s useful for critics who would love to discredit CrimethInc. by any means necessary and are willing to brush off the participation of people of color in order to do so. It&rsquo;s useful for white people who don&rsquo;t want to have to question their own privilege and internalized racism&mdash;associating APOC and all questions about white privilege with the controversial actions of a few is all too convenient. It&rsquo;s useful to all who, out of wrongheaded opposition to anarchist organizing and &ldquo;identity politics,&rdquo; would like to dismiss CrimethInc. and APOC alike. It&rsquo;s useful to those who, like at least some of the disrupters, appear to have given up on white anarchists ever being good comrades to people of color and are casting about for corroborating evidence.</p>
<p>Worst of all, this false opposition is useful to fascists and nationalists, not to mention other hostile parties. The &ldquo;Bay Area National Anarchists,&rdquo; for example&mdash;one of several fascist organizations attempting to appropriate anarchist rhetoric and aesthetics in order to seduce new recruits&mdash;enthusiastically posted the disruptors&rsquo; statement on their website, lauding the &ldquo;separatist&rdquo; action as proof that there are &ldquo;irreconcilable differences between tribal and racial groups.&rdquo; We can be sure that some of the discussion of the incident on anarchist websites has included posts from fascists or government agents intent on exacerbating the situation. Likewise, we know from the events of the past few years that infiltrators are present at anarchist events, and we cannot rule out that they might take advantage of conflicts like this&mdash;though it is counterproductive to speculate further without evidence.</p>
<p>The point is that conflicts in the anarchist community frequently include hostile voices from outside it, voices which may not be easy to identify. This makes it especially important to remain level-headed in the midst of them, acting according to our best judgment and refusing to let others persuade or provoke us into behavior that does not reflect our values. It is also crucial that we not assume that the words or actions of a few represent everyone we interpret as similar to them.</p>
<p>For the record, we believe the APOC network is invaluable to the anarchist movement. Everyone benefits from people of color having autonomous spaces to organize and strategize. We challenge all white anarchists to respect the autonomy of people of color and to do more to combat white supremacy in all its forms. We also respect the perspective of anarchists of color who have given up on white people ever being good comrades; this is a coherent position, though it can&rsquo;t usefully be <em>our</em> position, as people of a range of ethnicities participate in our networks and projects. Our only &ldquo;irreconcilable differences&rdquo; are with fascists&mdash;and all others who legitimize domination, <em>including those who defend the disruption. </em></p>
<h3>Not Drama but Resistance</h3>
<p>Fiascos like this can be extremely demoralizing for anarchists, especially newer anarchists who picture the struggle against hierarchy as an uncomplicated war against an external enemy. They can seem like pointless distractions; sometimes they drive people out of the anarchist movement entirely.</p>
<p>In some ways, this is equivalent to the attitude that conflicts in personal relationships are simply &ldquo;drama&rdquo; that outsiders should avoid getting embroiled in&mdash;even when they involve abuse and violations of consent. It may seem easier to stay out of things, but standing aside rather than addressing abusive and oppressive dynamics can also force people out of the anarchist movement.</p>
<p>For us, being anarchists means contesting hierarchy everywhere it appears: struggling against external oppressors, against oppression and domination within our communities, and against those forces inside ourselves. We must perpetually reevaluate how effective and appropriate various tactics are for these struggles. In those regards, the disruption at the convergence is as important as any protest or direct action, and there is at least as much to learn from it.</p>
<h3>The Challenges of Open Spaces</h3>
<p>CrimethInc. occupies an awkward position when it comes to debates about privilege and oppression. As a point of entry for many who are not previously familiar with anarchism, CrimethInc. brings together people with a wide range of critiques and levels of awareness. Since the turn of the century, CrimethInc. projects have increasingly engaged with the power dynamics associated with race and gender, although this has not necessarily carried over to those discovering anarchism through those projects. From one side, some reactionaries dismiss this engagement as mere &ldquo;identity politics,&rdquo; implying that it has nothing to do with revolutionary struggle. From the other side, critics who know little about CrimethInc. projects besides the cover of a book published in 2001 continue to attempt to conscript the collective to serve as a straw man representing everything wrong with anarchism. Being highly visible means that CrimethInc. projects are often associated with those who consume them more so than with those who produce them. It also means that many people use CrimethInc. as a projection screen on which to impose the images of whatever enemies they wish to contrast against themselves.</p>
<p>Over the past few years, CrimethInc. convergences have served as an introductory space for hundreds of people curious about anarchist struggle and ways of life. At best, they have offered an opportunity for aspiring radicals to challenge their conditioning and learn from each other. One inspiring example of this occurred at the 2008 convergence outside Milwaukee, when first-time attendees performed an ill-thought-out racist skit. Others approached them with constructive criticism, and the result was an important and beneficial learning experience. Documentation of this can be found in comments <a href="http://www.crimethinc.com/blog/2008/07/23/2008-convergence-reportback-teaser/">here</a> and <a href="http://www.crimethinc.com/blog/2009/08/03/crimethinc-convergence-controversy/#comment-17623">here</a>. While too many attempts at calling out such behavior end with defensiveness and communication breakdowns, this was a rare success story.</p>
<p>There is a lot to be said for creating mixed spaces in which people can be exposed to new ideas and develop their own capabilities. Such spaces are crucial for new participants to become involved in the anarchist movement. Unlike most other anarchist conferences and events, the convergences have been emphatically self-organized, offering room for all attendees to put on their own workshops and try out their own ideas. On the principle that people learn more from doing than from watching, this makes a great deal of sense; on the other hand, it means that the atmosphere and organization of the convergence are determined in part by the least experienced or self-aware participants.</p>
<p>Like many events in this sector of the anarchist milieu, the convergences have attracted a predominantly younger, whiter crowd. At worst, this means that more privileged participants can remain insulated within their comfort zones, creating&mdash;however unconsciously&mdash;an environment that is uncomfortable for those who do not share their privilege. The preceding paragraphs make a pretty good argument for why aspiring radicals from privileged demographics can benefit from others&rsquo; participation, but they don&rsquo;t explain why there would be any incentive for less privileged people to subject themselves to the same marginalization they already experience in much of society at large.</p>
<p>It may be quixotic to think that spaces in which the majority of people are white, male-bodied, or straight can ever be comfortable for everyone else&mdash;yet there must be ways to make them<em> less</em> alienating. Meanwhile, the participation of a wider variety of people in these spaces is vital not only for people with more social privilege who stand to learn from others&rsquo; perspectives, but also to the current participants with less social privilege who are already invested in them.</p>
<h3>Was There Racism at the Convergence?</h3>
<p>Of course there was. Racism is not confined to Klan rallies and prime-time television; it pervades our society. It&rsquo;s safe to say that every predominantly white space is bound to be affected by racist power dynamics; much racism is simply a matter of ignoring others&rsquo; needs and thoughtlessly utilizing privilege at others&rsquo; expense. This kind of behavior is default setting for most white people, and especially easy in mostly white spaces.</p>
<p>Was the convergence <em>more</em> racist than other predominantly white anarchist spaces or gatherings? We fear the answer is no, though this is no excuse. The challenges we grapple with pervade the entire milieu, and white anarchists should not delude themselves to the contrary. Even those who abhor CrimethInc. projects should be paying attention here. The responsibility to deal with this challenge extends beyond CrimethInc. to the anarchist community at large.</p>
<p>On one hand, it is something of an improvement on other anarchist events that the convergence operates outside the exchange economy, guaranteeing food, housing, and participation to all who attend regardless of their means (and without any humiliating &ldquo;scholarship&rdquo; applications). On the other hand, the discomfort of being crowded together with limited facilities and practically no privacy attracts a narrower crowd, subculturally speaking, which can make it even more alienating for people from outside that subculture.</p>
<p>The fact that even a single person of color chose to participate in the disruption out of personal frustration is a serious red flag. If we want to create environments in which people of various races, genders, classes, and walks of life can collaborate and learn from one another, we are responsible for trying to ensure that <em>everyone</em> can feel comfortable in them. Those with privilege have to take the initiative, as they are the ones best positioned to redress the power imbalance.</p>
<p>We can separate issues of white supremacy at the convergence into two basic categories. The first is structural, encompassing the organizing process, the site, and the relationship to the local community. The second is social, comprising the behavior of individuals in the course of the week. Up to this point, the second category has occasioned more internal criticism than the first, but the first is probably more important.</p>
<p>It&rsquo;s interesting to note how, at least for white attendees, incidents that seemed insignificant when they occurred assumed tremendous significance in the wake of the disruption. Suddenly every comment that had seemed trivial to white ears took on new dimensions. Perhaps this can convey the tiniest taste of what it is like never to be able to shrug off such comments. This should also be instructive to white anarchists who assume the CrimethInc. convergence was targeted because it was a more racist space than other predominantly white gatherings: rest assured that if this had happened at another event, other supposedly insignificant incidents would have been cast in stark relief.</p>
<p>One more note: when addressing racism and white supremacy, it&rsquo;s important not to judge others&rsquo; behavior according to classist criteria. When people visualize a racist, they often picture a poor Southern white, even though wealthy whites are much better positioned to inflict and benefit from racist injustice. Middle class people put a tremendous amount of focus on addressing issues of language and protocol, but addressing one&rsquo;s racist conditioning is more about communication than language, more about self-awareness than protocol, more about humility than expertise. A rural working class white person who never went to college to learn about &ldquo;intersectionality&rdquo; can still be a better comrade to people of color than a wealthy white, however many anti-oppression trainings the latter has attended&mdash;or taught.  </p>
<h3>How About Gentrification?</h3>
<p>It is arguable that the convergence contributed to the gentrification of the adjacent Garfield neighborhood. As discussed in <a href="#appendix">the appendix</a>, one tactic promoting gentrification is to maximize the visibility of white people, and the convergence certainly contributed to that.</p>
<p>It&rsquo;s worth pointing out, however, that the convergence was actively opposed by the Bloomfield Garfield Corporation (BGC), one of the primary forces behind gentrification in the area. Earlier on the day of the disruption, the BGC called in a false complaint to the Public Health Department; sympathetic sources at the Department reported that the BGC stated &ldquo;We don&rsquo;t want those people here&mdash;they don&rsquo;t fit in with our plans for the area.&rdquo;</p>
<p>Gentrification is a topic worthy of much more detailed discussion than space permits here. In brief, it seems that there are two basic approaches to combating it. One is for white people simply not to move into neighborhoods that are at risk for gentrification. This guideline is probably sufficient in some cases, but it does not take into account that often it is the poorest whites who are forced to move into such neighborhoods in order to find housing they can afford. It does not seem any more appropriate to blame these people than to blame those who are forced to take minimum-wage jobs at McDonald&rsquo;s. Another approach to fighting gentrification is for those who move into targeted neighborhoods to take responsibility for establishing ties with their neighbors and counterbalancing the negative effects of their presence, for example by taking effective action against gentrification. This can take many forms, including counter-development campaigns, anti-eviction organizing, and supporting local community infrastructure.</p>
<p>In this light, perhaps the issue to focus on was not so much that the convergence took place next to Garfield, but that it was not used more effectively to test and circulate strategies for fighting gentrifiers such as BGC. As a general rule, approaches founded on resistance rather than guilt are bound to be more effective.  </p>
<h3>Critique of the Convergence Organizing</h3>
<p>Midway through the week, one longtime attendee who had pushed hard for the 2009 convergence to experiment with a new model remarked that it was just like a rural convergence, only in a city. Indeed, though this convergence took place in a different setting, the model that had been developed over the preceding seven years was transposed whole into this new environment.</p>
<p>This was a tremendous missed opportunity. The model that had worked well enough in the countryside was not as suited for the city, and, more to the point, it offered few opportunities to engage with locals&mdash;which presumably would be the whole reason to have an urban convergence. There were exceptions to this, such as the open hours at the free clinic, but in general the convergence occurred in a bubble, separated from local communities rather than integrated into them or reaching out to them. This is not the model for radical organizing that most longtime convergence participants employ in our own hometowns, and it&rsquo;s unfortunate that we fell back into it here. Scarcity of resources such as food and space was repeatedly cited as one of the obstacles to opening up interactions with more locals; indeed, it&rsquo;s hard to demonstrate the advantages of the anarchist alternative with so little at our disposal. But there was also a failure of imagination.</p>
<p>Much of this can be traced to glitches in the organizing process. Because the original plan was to buy and repair a building, little thought was given to how else the event might interact with the local community. Less that two months before the event, local organizers were still scrambling to keep open the possibility of purchasing a building, while putting little energy into developing a plan B. The breakdown in the organizing group can only have made things worse. This is a reminder of how important group dynamic issues are, and how far-ranging the effects can be when conflicts are not worked out.</p>
<p>It&rsquo;s also true that other recent models for anarchist gatherings have provided precious few examples of how to engage with local communities. Conferences are frequently held on college campuses, which brings up as many issues around accessibility and class comfort as convergences in residential neighborhoods bring up about gentrification. Bookfairs cast locals as consumers, limiting their participation according to economic means and offering few other points of departure besides passively listening to speakers.</p>
<p>We anarchists, long used to being outsiders, must be careful not to marginalize ourselves. Future convergences that take place in cities should aim to interact with locals and interrupt the separations that characterize daily life under capitalism. It is sad that the Pittsburgh Really Really Free Market, which could have been an opportunity for this, ended up largely being a space to process the effects of the disruption.</p>
<p>Participants also brought up concerns about structural issues that could have contributed to this year&rsquo;s convergence being an uncomfortable space for attendees with less social privilege. Some suggested that the self-structuring nature of the convergence was a problem. A couple people asked whether it would be better for it to be invite-only, though this was hotly disputed. It was proposed that there could be a mandatory orientation workshop for first-time attendees. Other top-down solutions were advanced, involving more structure and protocol.</p>
<p>Instead of proposing more infrastructure, one might ask why the existing infrastructure&mdash;such as the mediation team and the exclusion policy&mdash;was not effective. One answer is that those who were most alienated by others&rsquo; behavior felt least entitled to ask organizers for help dealing with it. Another is that responsibility was not widely distributed enough&mdash;a six-person mediation team can&rsquo;t hope to keep up with every potential conflict or uncomfortable situation without others also taking initiative.<a class="footnote" href="javascript:void(0);" onclick="return overlib('Participants in the mediation team report that its effectiveness was limited by the lack of a culture of communication and mediation generally in the anarchist community.', CAPTION, '[1]');" onmouseout="nd();">[1]</a> Here again we return to the challenges of organizing events that include people who are at their first anarchist gathering.</p>
<p>Some of the aforementioned proposals focus more on how to curb the insensitive behavior of those who benefit from social privilege than on empowering those affected by it. One proposal that took the opposite approach suggested that race and gender caucuses should be scheduled at the beginning of the convergence, rather than near the end<a class="footnote" href="javascript:void(0);" onclick="return overlib('In fact, the APOC caucus was originally scheduled for the second day of this convergence. One of the people who planned and carried out the disruption asked that it be moved back to Friday, the day of the disruption.', CAPTION, '[2]');" onmouseout="nd();">[2]</a> (when they have occurred the last few years), offering participants of those demographics the chance to confer and present demands to other attendees. As privilege issues extend to an infinite range of facets beyond race, gender, and class, this would still be a limited solution, but it could at least be a starting point. It also takes advantage of the self-structuring aspect of the convergence, rather than attempting to suppress it.</p>
<p>In a spatial rather than temporal version of this proposal, spaces could be designated for the same purpose. This would have been particularly difficult in Pittsburgh, where there was so little space at our disposal, but we can at least put it in the toolbox for later.</p>
<p>One other factor at this convergence was that there were so few opportunities for individuals to address the entire convergence. At previous convergences, there had been circles in the morning and the evening; in Pittsburgh, due to space and time constraints, they only took place in the mornings, barely accommodating organizers and workshop presenters and offering no time at all for individuals to air concerns or frustrations.</p>
<h3>Being a &ldquo;White Ally&rdquo;</h3>
<p>In the discussions on Saturday night, one white person said something to the effect that he initially supported the disruption because, as an aspiring white ally, he unconsciously assumed that he should support whatever people of color seemed to be taking the most &ldquo;radical&rdquo; position. This is a telling indicator of how simplistic many white radicals&rsquo; conceptions still are of what it means to be a &ldquo;white ally.&rdquo;</p>
<p>Being a white ally&mdash;or, one might say less ostentatiously, a good comrade&mdash;to people of color is not a simple matter. In a specific personal relationship, such as with a friend or neighbor, it involves becoming aware of one&rsquo;s advantages, checking one&rsquo;s tendencies to utilize them, and above all being approachable and open to criticism. This is a lifelong project, but with healthy communication it is possible to measure one&rsquo;s success according to concrete feedback.</p>
<p>Aspiring to be a &ldquo;white ally&rdquo; beyond specific relationships is more complex and potentially problematic. One can aspire to contest systems of white supremacy in general, but &ldquo;white ally&rdquo; is not a role or identity that one can earn with any amount of effort. Endless questions open before any white person who sets out to be an ally to &ldquo;people of color&rdquo; in the abstract. Whose lead do you follow? In conflicts between people of color, how do you decide which side to take, or how to stand aside? Is it possible to make this decision without simply identifying with those who seem less threatening to your white privilege, or who offer more opportunity to appease your white guilt?</p>
<p>Too many white people approach the issue of white supremacy as if it is simply a bill they can pay and move on. It is not a matter of individual guilt that can be absolved, but of engaging honestly and critically with one&rsquo;s position in an unjust system. We are going to be struggling with power dynamics around race and gender for the rest of our lives, even if there is a capital-R Revolution. Rather than setting out to persuade themselves that they are doing enough, white people need to understand that nothing they can ever do will be &ldquo;enough,&rdquo; and yet that they have everything to gain by trying.  </p>
<h3>Identity and Legitimacy</h3>
<p>The disruptors imposed a framework for identity and legitimacy that has dominated dialogue about the events, even among many who oppose their politics as well as the action. At worst, this has resulted in people pitting various identities against each other in a contest for legitimacy: &ldquo;Queer and trans folks were forced out onto the street in the middle of the night!&rdquo; &ldquo;People of color have been displaced from land for hundreds of years!&rdquo;</p>
<p>It is important to avoid shallow critiques of identity politics that obscure the ways our various experiences of race, gender, class, and other factors shape our lives. But we can&rsquo;t simply use identities to confer automatic legitimacy on anyone&rsquo;s suffering, ideas, or actions. We have to create frameworks that acknowledge the uniqueness of everyone&rsquo;s experiences rather than presenting individuals as mere collections of identities, and emphasize what <em>everyone</em> has to gain in dismantling oppression along all axes.</p>
<p>This is especially relevant in reference to justifications of the disrupters&rsquo; behavior. We all agree that violence is legitimate in self-defense. Can this be extrapolated to mean that violence is always legitimate when a person lower in the social hierarchy attacks someone higher in it? If so, how do we establish exactly where people stand in relation to each other? Is race more determinant than class or gender? Are there complex equations by which we can work out who is entitled to evict whom from a space?</p>
<p>Or is this the wrong line of questioning altogether? As anarchists, we might instead posit that violence is only legitimate to the extent that it creates or defends horizontal power dynamics. Self-defense can be an instance of this, as can attacks on the repressive apparatus of the state.</p>
<p>It is not anarchist to prioritize any one form of oppression over others. White people can&rsquo;t understand or judge the experiences of people of color, but by this same principle no one can fully understand or judge another person&rsquo;s experience, and that increases exponentially according to all sorts of differences. The point is not to rank oppressions, but to offset their effects while fighting them. Forms of political shorthand such as &ldquo;all white people benefit from white privilege&rdquo; and &ldquo;there is no such thing as reverse racism&rdquo; are useful for this, but they cannot justify turning a blind eye when people of oppressed demographics victimize others on the basis of presumed privilege.  </p>
<h3>About the Disruption</h3>
<p>Feelings are always legitimate. It is a crushing tragedy that anyone felt excluded or silenced at the convergence.</p>
<p>When one feels excluded and silenced, there is something to be said for striking out, even when it is not in order to create the possibility of dialogue but simply to create space for oneself. Calls for dialogue are cheap coming from those whose comfort excludes and silences others. It&rsquo;s easy to be sympathetic to the person who accepted the last-minute invitation to participate in the disruption out of frustration with the atmosphere of the convergence.</p>
<p>All that said, not all <em>actions</em> are legitimate. Many who experienced the disruption have identified it as dominating, abusive behavior. The white people in the building were targeted on account of their identities rather than their actions, and everyone in the building was subjected to an extremely traumatic situation. This was justified on the grounds that people of color have been subjected to much worse&mdash;which is true but beside the point.</p>
<p>Let no one say the action was not violent. When the police evict a family from their home, they need not hit anyone for the eviction to be violent; the threat of violence is enough. Likewise, by screaming that they were not pacifists and physically seizing and damaging people&rsquo;s belongings (including, incidentally, the belongings of people of color), the disrupters made their intentions clear. Justifications after the fact about &ldquo;property damage&rdquo; not being violence are beside the point, not to mention a disingenuous misrepresentation of the anarchist case for anti-corporate vandalism.</p>
<p>Gentrification has been cited as one of the justifications for the disruption, along with the allegation that the organizers had not consulted the residents of the neighborhood where the convergence took place. Of course, some of the organizers and participants were residents of the neighborhood, while none of the disrupters were even from Pittsburgh. The disruption was supported by at least one local who was not present, but it&rsquo;s unlikely that the disrupters themselves consulted the residents of the neighborhood before acting supposedly in their interests. By forcing hundreds of people out onto the street in the middle of the night and attracting the police, the disruption posed great risk not only to convergence participants, but also potentially to local residents; if anything, it increased the negative effects of the convergence on the neighborhood.</p>
<p>In the statement the disrupters released several days after the convergence, they acknowledged, amid various fabrications,<a class="footnote" href="javascript:void(0);" onclick="return overlib('It would be a waste of time to address all of these, so we&rsquo;ll note only one example: &ldquo;Many knew full well that there were at least two perpetrators of sexual assault present at the convergence (which went against the convergence&rsquo;s own policy), yet nobody said or did anything.&rdquo; It is true that the mediation team spent quite a bit of time and energy following up on the accountability processes of two individuals at the convergence, in communication with the survivors in question. The policy stated that the wishes of survivors would be respected, and that policy was implemented to the fullest extent possible. The statement by the disrupters indicates one of two things: either they are maliciously misrepresenting that situation to their own gain&mdash;disrespecting the efforts of the mediation team (which included people of color), the wishes of the survivors, and the seriousness of the issues of sexual assault and accountability in general&mdash;or else <em>they</em> knew of the presence of two unaccountable perpetrators and did not say anything about them to the mediation team, an equally unconscionable action.', CAPTION, '[3]');" onmouseout="nd();">[3]</a> that the disruption had been discussed long before the convergence, when the organizers were still considering purchasing a building. Rather than a response to any specific grievance, it seems that the disruption was an opportunistic attack on a target calculated to create the maximum notoriety while occasioning the minimum risk. If this is so, it is particularly unscrupulous that those who planned it invited others to participate on the basis of their personal frustrations.</p>
<p>One might hope that an action like this might at least give rise to dialogue, and one person who joined in at the last minute has said that he did so hoping to achieve that goal; but the disruption itself seems intended to bring out the worst in people and make dialogue impossible. Forcing people out of the space, demanding that they not only leave the building but also Pittsburgh and North America, clearly created structural obstacles to any sort of collective processing of the event; it was only by defying the disrupters&rsquo; demands that attendees were able to address the inappropriate ways white people had responded. Some of the disrupters have made it clear that they do not regard white anarchists as comrades; it&rsquo;s not out of the question that they may have deliberately set out to create a situation intended to corroborate that perspective.</p>
<p>In any case, those who planned the disruption in advance have made it very difficult not to interpret their entire participation in the convergence as a malicious series of deeds carried out in bad faith.</p>
<p>In the subsequent statement, the disruption was called &ldquo;Smack a White Boy,&rdquo; but the only people who ended up in physical confrontations were people of color. This was not an accident, but a structural result of the disrupters&rsquo; approach. What did they expect other people of color in the space would do? The disrupters imposed a situation on everyone in the building in which any white people who defended themselves or their belongings would be framed as racists; the only ones who were immune to this setup were the other people of color, who were then forced to personally take on the disrupters, regardless of whether they were emotionally prepared for this.</p>
<p>As of this writing, most of those who knew about the disruption in advance have expressed regrets of one kind or another, but the core group of disrupters has continued to justify it in the strongest terms. In our view, they are perpetrators of abuse who cannot be considered comrades unless they are willing to be accountable for their actions.  </p>
<h3>Critique of the Response</h3>
<p>Whatever can be said against participants in the convergence, throughout the entire incident no one threw a punch or called the police. It would be very difficult to find another mixed space of hundreds of people who would react to such a provocation without resorting to violence, whether their own or via the authorities.</p>
<p>But was the organizers&rsquo; reaction appropriate? Under the circumstances, considering that there was no template for handling such situations, it may not have been the worst response; if nothing else, it prevented anything from complicating the discussions that have taken place since. But upon a great deal of reflection, we can&rsquo;t endorse the way people handled the disruption as an appropriate model for responding to similar events in the future.</p>
<p>By choosing to stay out of the conflict, white organizers essentially accepted the terms of the disrupters, collaborating in forcing them on everyone else and forcing the people of color who opposed the disruption to do so alone.</p>
<p>This is an example of how a muddle-headed desire to be an ally can sometimes cause people to countenance abusive behavior. White privilege is not the only kind of privilege, white-inflicted oppression is not the only kind of oppression; in standing aside, white organizers essentially joined the disrupters in prioritizing one form of oppression over others. This is neither responsible nor anarchist.</p>
<p>If this response sets the precedent for such situations, it will be impossible to defend anarchist events against disrupters of all stripes. Unfortunately, there are incentives for people of all walks of life to dominate and abuse others, and it&rsquo;s not out of the question that worse enemies than these particular disrupters might attempt to take advantage of what they see as a weakness among anarchists. If there is a next time, we urge people to draw on this example and take action to prevent people from coercing others and breaking up events.</p>
<p>This is not the first time that anarchists have clashed over issues of oppression, entitlement, and coercion. History has shown repeatedly that apparently minor disagreements often foreshadow major divisions&mdash;in 1917, for example. We must stick to our principles even when others call on us to suspend them; let us not forget what became of anarchists who suspended them in the past.</p>
<p>There is also much to critique about the response after Friday night. It&rsquo;s interesting to note that both the disruption Friday night and the discussion Saturday night targeted the attendees as a whole, diffusing responsibility, when most of the grievances in question could be traced to specific individuals. Anyone could have taken the initiative to approach the responsible parties personally, but few did. The discussion Saturday night was good for helping participants hone their understanding of oppression and white supremacy, but many of those who most needed to hear it were not in the room. At worst, this makes such discussions appear to be a sort of litany people recite to assure themselves of their good intentions, rather than a concrete way to change. Granted, people were exhausted&mdash;but most of the important growth in consciousness around these issues results from personal conversations, not open discussions.</p>
<p>A few people have dared to be honest and vulnerable, such as the white people in the discussion Saturday night who owned up to the oppressive things they had said Friday, and the people who participated in or were forewarned of the disruption who have come forward to express their regrets and explain why they did what they did. This humility sets a good example for everyone else.</p>
<p>Though many people have rejected the disrupters&rsquo; demands that white people &ldquo;Go back to Europe&rdquo; and so on as absurd, perhaps it is insulting not to engage with them. This is a coherent position&mdash;even if white people can&rsquo;t be forced to return to Europe, one could argue that the only way for people of color to maintain their dignity is to refuse to legitimize their presence in North America.<a class="footnote" href="javascript:void(0);" onclick="return overlib('Who knows what this says about the white &ldquo;allies&rdquo; who supported the disruption and physically resisted the people of color who opposed it. Perhaps if you assist the &ldquo;right&rdquo; people of color in their struggles against other people of color, you are welcome in North America after all?', CAPTION, '[4]');" onmouseout="nd();">[4]</a> Indeed, white radicals <em>consistently</em> give people of color reason to doubt that they can ever be good comrades. White anarchists who don&rsquo;t want to see more debacles like this in the future should make a real effort not to give people of color reason to give up on them.</p>
<p>Ultimately, though it is tempting for most white people to focus on the disruption, the roots of the issue and the power to address them lie within white anarchists. The disruption was not <em>only</em> a publicity stunt or a power grab within APOC; the fact that even a single person chose to participate in it out of personal frustration indicates that we all have a tremendous amount of work to do.  </p>
<h3>Not Conclusions, but Beginnings</h3>
<p>The various ways white people responded to the disruption show how far we have to go in developing a comprehensive anti-oppression politic that can protect against all forms of internal oppression and domination. The way the disruption itself played out, becoming a conflict between people of color as well as between people of color and white people, shows that issues of identity and privilege cannot be simplified into one-dimensional imperatives; we can&rsquo;t just draw lines between black and white or right and wrong and fight it out, knowing ourselves to be on the side of the angels.</p>
<p>Though this has been emotionally exhausting all around, it&rsquo;s only one learning experience in a lifelong process; we can&rsquo;t let it discourage us. We&rsquo;re in a long-term struggle; we&rsquo;ll be organizing events for many years yet, along with other forms of activity. This year, we&rsquo;ll discuss how to improve on the convergence models of the past, how to engage more with privilege and gentrification, and where to go from here. Here&rsquo;s hoping this text can prompt more constructive discussions around all these issues.</p>
<p>&nbsp;</p>
<p>&nbsp;<a name="appendix"></a></p>
<h3>Appendix 1: &ldquo;History and Neighborhood&rdquo;</h3>
<p><em>from the convergence orientation &rsquo;zine</em></p>
<p>This year's CrimethInc. convergence departs from past experiments through our decision to host it in an urban setting. Along with this choice of locations comes a host of new dynamics, relationships, and histories that are important for all of us to be aware of as we choose our actions for the week. Being in the city, this year's convergence space is also situated on the battlefield of a struggle raging in Pittsburgh and most other cities in the U.S. There are many different names to describe this conflict&mdash;gentrification, &quot;urban renewal,&quot; community development, etc.&mdash;but at the heart of it is essentially the struggle over who has power to make decisions about the composition of a neighborhood, and how that power is structured. Similarly, who benefits from decisions made about a community, and whose interests are being heard? And how do the actions of folks from different racial, class, and cultural backgrounds participating in those neighborhoods affect the outcome of these struggles?</p>
<p>This year's convergence is taking place at the intersection of four major neighborhoods in Pittsburgh: Bloomfield. Garfield, Friendship, and East Liberty. For us to understand our relationships to these communities and how other folks in this city might feel about our presence here, it is important for us to be aware of the history and character of these neighborhoods. Bloomfield is a traditionally white, working class neighborhood know as Pittsburgh's &quot;Little Italy.&quot; Garfield has traditionally been a working-class neighborhood, changing as new waves of immigrants arrived in Pittsburgh and currently inhabited mostly by African-Americans. East Liberty, following a disastrous redevelopment plan and white flight in the 1960s, has become a working-class, African-American neighborhood and home to refugees from the destruction of the Hill District to build the Civic Arena. Friendship was invented as a neighborhood in the early 1990s by white, self-described &quot;urban homesteaders&quot; who sought to disassociate themselves from the &ldquo;blighted&rdquo; neighborhoods of Garfield and East Liberty. At the moment, there is an attempt to further split part of East Liberty into a new neighborhood called &quot;East Side,&quot; the new home of a Whole Foods, Trader Joe's, Starbucks, a Trek bike shop, and other businesses appealing to the affluent.</p>
<p>In examining this history, what are the intentions behind terms such as blighted neighborhoods, urban renewal and urban homesteading. Who has the power to make these definitions, and for what purposes are these labels used?</p>
<p>* Urban blight is a term generally used to describe the neighborhoods of poor people, immigrants, and people of color in order to justify holding power over these neighborhoods and making decisions about their future. Urban blight says that no one should care about these places and they have no value.</p>
<p>* Urban renewal in Pittsburgh is a history of highways expansions, new stadiums, and other publicly funded development that displace marginalized communities for the benefit of the elite. This term was used as justification for demolishing the heart of Pittsburgh's Hill District in 1961, the center of the black community at the time, to make way for an opera house serving Pittsburgh's white elite.</p>
<p>* The term homesteading, meanwhile, is rooted in the time of westward expansion of white Amerika, when the government offered incentives for settlers to move out from the original colonies. This movement was directly tied to displacement of Native Americans from their land, to the great detriment of the environment and for the enrichment of corporations. Might the modern application of the word reflect a similar process of white migration into traditional communities of color?</p>
<p>In planning and carrying out the CrimethInc. convergence this year, we need to be aware of our relationship to these historical injustices and the current struggles over defining the communities in our city. Our initial hope in organizing an urban convergence was to use the strength in numbers of hosting this event to create permanent infrastructure that could empower radical activities in Pittsburgh. We planned to buy a building that would host the convergence, use the momentum of the convergence to renovate it, and then have the building remain as a long-term anarchist resource for Pittsburgh. This would have been a major departure from convergences of years past, which actually strive to leave nothing behind.</p>
<p>It sounds like synergy, but the size, logistical, and geographical needs of a convergence space and a long-term anarchist social center are actually pretty divergent. After months and months of looking, we weren't able to find something that would suit both projects perfectly. Rather than buy a building for a one week event or get a building that we could use long term but that would make this event impossible, we decided not to rush it and to make other plans for the convergence.</p>
<p>Our revised plan was to rent a building for the convergence space. In searching for a space to hold the convergence, we confronted the realities of being (mostly) white anarchists in a world shaped by the historical developments outlined above. Whether it was through the art-world, 'hip' politicians, absentee landlords, or any other avenue we knew of other folks getting space, we were thwarted. At the heart of it, hosting the CrimethInc. convergence (like most anarchist activities) is not in the self-interest of people who generally try to appeal to the world of corporate funding, &quot;community development&quot; grants, yuppie consumers, and the police. On the other hand, we were too poor for almost all of the property in the city available for a traditional rental agreement, regardless of the political leanings of the owners. The only neighborhoods where we could afford a space were either completely isolated from the local anarchist communities, or in neighborhoods targeted for gentrification.</p>
<p>In the end, we didn't make much of a choice at all: we are hosting the convergence in the *only* legal space we could afford. And it is situated (to varying degrees, like most of Pittsburgh at this moment) in a place where there is serious tension about competing visions for the future of a neighborhood.</p>
<p>One of the most difficult decisions we had to make this year was the decision to get a 'legal' space. While we dreamed of other plans, all of them carried with them the more immediate threat of arrest. We felt it would be irresponsible to thrust all of you into that situation without your consent, and we worried that not enough of us would be willing to face those risks for these wilder plans to reach fruition. On the other hand, we felt a responsibility to all of you to make the convergence happen, and our only other real option we could see was a complete cancellation. So, we're still trying the urban experiment, on what are the best terms we felt able to achieve, and we are still excited about what we can accomplish together. </p>
<p>The purpose of our analysis is not to feel guilt about the situation we are in, because we didn't create this system, but rather to figure out how we can fight against it better, how we can be smarter and resist and overcome the way this world is to the best of our abilities. This situation leads to a lot of difficult questions for all of us to think about: Can white people exist in neighborhoods such as this without being a gentrifying force in the community, and how do we go about it? Is there an alternative to being outsiders in communities of color for white anarchists with little money, and what does that alternative look like? And finally, what are the possibilities for radical communities to exist of mixed race &amp; class without becoming co-opted by the dominant trends of gentrification and capitalist development?</p>
<p>We are committed to exploring these questions and many more with all of you during the CrimethInc. convergence this year. In the meantime, as the local organizers, and with the input of other folks in our community, we ask you to please be aware of the following things to minimize our negative impact in this neighborhood.</p>
<p>* One of the main tactics of gentrification is to maximize the visibility of white people in a neighborhood (through art walks, special events, festivals, etc.), thereby monopolizing public space and marginalizing people of color. If you are white, please be aware of how much public space you and your friends are taking in the community, and try to hang out in places like Friendship Park versus Penn Avenue.</p>
<p>* The police are major agents of gentrification, befriending and &quot;protecting&quot; white people while harassing and terrorizing people of color. Do not befriend the police. It is best not to talk to any police officers, and if you see police doing fucked up things while you are here, do your best to hold them accountable while keeping your own safety in mind. Easy things to do are write down badge numbers, ask the folks being harassed if they need anything, and document the situation if possible.</p>
<p>* Please don't support the yuppie businesses in the area. Please do not go to the fancy coffee shops, art galleries, and hip clothing boutiques. Most of these business owners wouldn't have dared to walk the streets of this neighborhood five years ago. Don't reward them now that they're trying to cash in.</p>
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1] Participants in the mediation team report that its effectiveness was limited by the lack of a culture of communication and mediation generally in the anarchist community, most of which focus only on sexual assault and abuse.
</p>
<p>[2] In fact, the APOC caucus was originally scheduled for the second day of this convergence. One of the people who planned and carried out the disruption asked that it be moved back to Friday, the day of the disruption.</p>
<p>[3] It would be a waste of time to address all of these, so we&rsquo;ll note only one example: &ldquo;Many knew full well that there were at least two perpetrators of sexual assault present at the convergence (which went against the convergence&rsquo;s own policy), yet nobody said or did anything.&rdquo; It is true that the mediation team spent quite a bit of time and energy following up on the accountability processes of two individuals at the convergence, in communication with the survivors in question. The policy stated that the wishes of survivors would be respected, and that policy was implemented to the fullest extent possible. The statement by the disrupters indicates one of two things: either they are maliciously misrepresenting that situation to their own gain&mdash;disrespecting the efforts of the mediation team (which included people of color), the wishes of the survivors, and the seriousness of the issues of sexual assault and accountability in general&mdash;or else <em>they</em> knew of the presence of two unaccountable perpetrators and did not say anything about them to the mediation team, an equally unconscionable action.
</p>
<p>[4] Who knows what this says about the white &ldquo;allies&rdquo; who supported the disruption and physically resisted the people of color who opposed it. Perhaps if you assist the &ldquo;right&rdquo; people of color in their struggles against other people of color, you are welcome in North America after all?</p>
</div>