<h6>The following essay is the first of a two-part series regarding plans for a month of decentralized events and actions planned for August 2010. To skip from the past directly to the future, read part two, <a href="/texts/atoz/10pt2.php">AUGUST 2010: We Are Everywhere</a>.</h6>
<p>&nbsp;</p>
<h1>THE OBJECTIVES OF THE CRIMETHINC. CONVERGENCE</h1>
<h5>The plan was all over the place from the beginning!</h5>
<p>&nbsp;</p>
<p><em>It is early in the summer of </em>2010<em> and CrimethInc. agents have not yet revealed the location of the the summer gathering that has occurred annually for almost a decade; on the heels of a <a href="/texts/recentfeatures/09.php">controversial disruption</a>, and after reaching a plateau of opportunities and variations on the model itself, the </em> CrimethInc. Experimental Committee <em>is researching objectives for the model that would eventually become the events of </em>August 2010.<em> It is late evening and dusk has just turned to night. The air is humid and still. Clouds roll on the horizon.
</em></p>
<p>In a moment of stasis while researching and revising our plan for August 2010&mdash;surrounded by notes, maps, newspaper clippings, and antiquities from our archives&mdash;we acting members of the Experimental Committee looked up at each other in unison. It hadn&rsquo;t fully materialized in our work that <em>we hadn&rsquo;t been a part of this from the beginning.</em> It was true: the gatherings that we were studying <em>predated</em> our lives as anarchists. We were a new generation of anarchists and many of us could trace the lineage of our meaningful life experiences back to some profound moment at a CrimethInc. Convergence and one similar moment of realization: that <em>we could spend the rest of our lives fighting for our values.</em></p>
<p>Fully metabolizing this information was our big breakthrough; we knew that if we confined our deliberations to the narrow spectrum of possibilities capable of being realized by <em>organizers</em> we&rsquo;d be doomed to endlessly repairing models that may not be capable of achieving certain objectives in the first place. As inspired newcomers, the convergence <em>had never been done before</em> and even later when we first helped to make them work, those were new experiences too.
</p>
<p>Thus, any outreach project attempted on the scale of a CrimethInc. Convergence <em>must</em> be composed of new and adventurous experiences&mdash;for the fascinated newcomers, the autonomous groups who come together to organize the activities, and <em>the anarchist community as a whole.</em></p>
<p>It was from this hearth that the CrimethInc. Experimental Committee&mdash;entrusted with all of the reckless abandon and audacity that made us&mdash;struck the &ldquo;<a href="/blog/2010/06/03/august-2010-we-are-everywhere/">We Are Everywhere</a>&rdquo; campaign. However, if we are to try something new, we ought to first understand the objectives and intentions of the CrimethInc. Convergence so as to not lose more than we gain by replacing it.</p>
<h2>WHAT WAS THE POINT?</h2>
<h4><a href="#accessible">To maintain an accessible point-of-entry into the anarchist community</a>.</h4>
<h4><a href="#visibility">To demonstrate a sustainable way to organize on a national scale, <em>without</em> a summit</a>.</h4>
<h4><a href="#inspiration">To invigorate and inspire anarchist communities</a>.</h4>
<h4><a href="#values">To create a safe and experimental space to hone and practice our values</a>.</h4>
<h4><a href="#autonomy">To practice managing and organizing zones of autonomy</a>.</h4>
<h4><a href="#reunion">To reunite old comrades in new ways</a>.</h4>
<h4><a href="#uncontrollable">To be adventurous and uncontrollable</a>.</h4>
<p>&nbsp;</p>
<hr />
<h3><a name="accessible">To maintain an accessible point-of-entry into the anarchist community</a>.</h3>
<p><em>Geography</em> &ndash; Probably the single most obvious shortcoming of a national gathering is that it can happen only in one place, which limits its accessibility geographically immediately. A further complication is that most people for whom it is a financial option to travel cross-country cannot spend such time away from work<a class="footnote" href="javascript:void(0);" onclick="return overlib('Although clearly we mean to say that many people cannot spend two weeks away from their jobs, it also needs to be made clear that many anarchists are so involved in local organizing that they cannot leave those projects for long either.', CAPTION, '[1]');" onmouseout="nd();">[1]</a>&mdash;including involved and sympathetic anarchists&mdash;and consequently cannot travel the distance. This means that the population of anarcho-curious participants are predominantly unemployed or self-employed. Although this is often an observation leveled against CrimethInc. Convergences by skeptics, the fact that they are geographically inaccessible to many people is merely <em>a circumstance of the medium;</em> as any national gathering&rsquo;s accessibility&mdash;from bookfairs to social forums&mdash;is limited to locals, committed organizers, and the extra-regional participants privileged enough to attend.</p>
<p><em>Accommodations</em> &ndash; It should be considered a small victory alone that none of the participants over the years have ever had to pay for the reclaimed vegan meals or the outdoor camping at a CrimethInc. Convergence. However, an innumerable amount of would-be participants have forgone attendance because living arrangements <em>didn&rsquo;t accommodate for them.</em></p>
<p><em>Prioritization</em> &ndash; In traveling across the country with a prepared workshop, we <em>pass</em> through dozens of small towns and anarchist communities. In doing so, we miss these opportunities to share information and create new points-of-entry; this prioritization of &ldquo;doing everything in one place&rdquo; works against the logic of the swarm models that we&rsquo;ve carefully honed in street confrontations for years.</p>
<h3><a name="visibility">To demonstrate a visible and sustainable way to organize on a national scale <em>without</em> a summit</a>.</h3>
<p><em>Visibility</em> &ndash; Though recent protests coordinated by anarchists have <a href="/texts/recentfeatures/g202.php">proven new models</a> of success, we are visible in those historical moments because we are intervening in an arena where mainstream media is already waiting at the sidelines. Therefore, anarchists in the streets of Athens, OH, are far less visible&mdash;even to the Athenians&mdash;than the comparable number of anarchists on the streets of Denver during the DNC. No matter what we do with convergences, the national attention won&rsquo;t focus on them until there is more widespread anarchist activity.</p>
<p>It is therefore imperative that we not presume massive gatherings are separate but equal to mass mobilizations with respect to visibility&mdash;they are indeed <em>less</em> visible both to mainstream media and within our circles.</p>
<p><em>Sustainability</em> &ndash; Although it is fairly clear what it takes to organize a convergence if you&rsquo;ve ever been to one&mdash;and in that sense they are <em>self-reproducing</em>&mdash;the fact remains that few organizers step forward into subsequent organizing roles in the years following their first contributions. This tendency likely stretches deep into the heart of this analysis: that the goals and objectives held by new organizers are rarely met, and those who help year after year and insist upon convergences simply lack imagination.</p>
<p>Additionally, <em>convergences are disproportionately exhausting to organize.</em> As is expected for centralized work of this magnitude, almost all of the heavy lifting falls on a small group of locals. Occasionally, some workloads are taken on by nearby anarchist communities, but it is a limitation of the model that a few critical locals will be overworked, and the larger community too removed from the organizing to be helpful, even when they&rsquo;d be excited to help.</p>
<h3><a name="inspiration">To invigorate and inspire anarchist communities</a>.</h3>
<p><em>Infrastructure</em> &ndash; Even when convergence organizers are actively involved in the local projects they utilize while organizing, groups rarely benefit from the arrangement. Although it is easy to say that this is a problem with CrimethInc. Convergences exclusively, it is a likelihood that this stress and exhaustion occurs because anarchist infrastructural efforts <em>in general</em> have no contingency plan for benefiting from a surge of participation and demands. Success stories include things like cleaning up an illegal dumpsite for a host and repairing hundreds of bikes with various cooperatives, but the other side of the story is probably more common: that collectives and social spaces are stretched and warped by the convergence beyond repair. To make this less likely, we can make sure the projects we work on locally know how to benefit from the influx of volunteers and participants&mdash;that we don&rsquo;t already have measures to achieve this perhaps indicates that we <em>don&rsquo;t expect our ideas to be popular.</em> In the meantime, we should put less stress on local projects so that we can forge mutually-beneficial relationships.</p>
<p><em>Mutual Aid</em> &ndash; Of all the Really Really Free Market projects founded during CrimethInc. Convergences, none of them have ever stuck. A short piece published by some local organizers who stayed with it suggests that these &lsquo;Free Markets <em>can</em> <a href="/blog/2008/04/28/free-market-in-winona/">make a comeback</a> long after the convergence, but undoubtedly it would be best to spend months of work founding a mutual aid project <em>before</em> the influx of extra participants and energy, rather than after.</p>
<p><em>Pressure</em> &ndash; Because essential basic accommodations are so difficult to organize, the pressure to &ldquo;make it work somehow&rdquo; builds in the months leading up to each convergence. Often times, great things come from mandates like these, but when it regards questions like &ldquo;how can we make sure an imminent mass of 300 people can live together in the same space?&rdquo;, it puts such torque on interpersonal relationships that rarely any good comes of it. Moreover, this pressure has at times severed local affinities and ruined relationships. Where these pass-fail pressure paradigms exist, the inspiration and encouragement that might follow a successful experiment is lost, and thus the larger objective cannot be achieved for organizers on the ground.</p>
<h3><a name="values">To create a safe and experimental space to hone the practice of our values</a>.</h3>
<p><em>Anti-oppression</em> &ndash; To create a space where incoming participants can learn and practice sensitive communication and develop admiration for those who actively work against oppression within themselves should be a primary objective for any anarchist outreach project. Great care must be taken to ensure this learning and discovery can occur without jeopardizing our cumulative efforts as long-term community members. At times, open-invitation gatherings, regardless of the sensitivity and care invested beforehand, <em>cannot</em> be these spaces. As many of the queer, trans, female-bodied, and people of color who have been a part of organizing convergences in the past know, their role as organizers cannot preempt the institutionalizations that exist both in the social arenas from which many first-time convergence-goers hail, and from within our own communities. The question then, is, how can these spaces be organized and populated by non-white, transgendered, and/or female-bodied people exist without being vulnerable to the same sorts of oppressive and marginalizing behavior found elsewhere? Should gatherings be organized separately, as some of the disrupters of 2009 <a href="/texts/recentfeatures/09.php">have argued</a>? Should we adapt our policies and workshops retroactively, attempting to address specific issues as they unfold, as has been happening? All the caucuses and corresponding auxiliary discussions we can organize will not change the fact that eventually we must know how to work, love, and live together. And if we constantly prune a project, we will always be reacting to problems that could have been avoided. The most reasonable answer is that neither of these strategies will work, and that if we maintain focus on the original objective, we will have to find an overall strategy that allows different methods to be simultaneously tried and practiced according to the needs of the organizers and participants.</p>
<p><em>Surveillance &amp; Repression</em> &ndash; Though very few arrests have occurred during CrimethInc. Convergences, and those that did involved appropriate support structures, the gatherings themselves have been a hunting ground for FBI infiltrators. These despicable impostors&mdash;<em>sheep in wolves&rsquo; clothing</em>&mdash;have undoubtedly been among the attendees at each event since 2002, looking for inexperienced and impressionable young people to entrap and later defame. This is not to say that convergences are more vulnerable than other places. Avoiding gatherings wholly on the grounds that they attract infiltrators is naive; wherever we do important work, they will come. It is good form to practice assembling with new people and protect ourselves with <a href="/blog/2009/06/24/towards-a-collective-security-culture/">effective security culture</a>. However, if we aren&rsquo;t changing our models more often than repressive forces, we risk expediting their processes.</p>
<h3><a name="autonomy">To practice managing and organizing zones of autonomy</a>.</h3>
<p><em>Consensus Process</em> &ndash; It is worthwhile to note that during convergences, each day begins and ends with group-encompassing conversations during which participants are free to address each other. In this manner, tasks and roles are bottomlined, issues are raised, schedules are discussed, plans are announced, iffy plans are called out, and so on. Historically, however, convergences have been <em>bad</em> at assembling as spokescouncils and responding to immediate emergencies<a class="footnote" href="javascript:void(0);" onclick="return overlib('In 2004, after a group of convergence-goers were arrested for mischief, chaos ensued and people evacuated when the JTTF began harassing people on the streets. The same disarray occurred 5 years later when the convergence was disrupted in Pittsburgh. In these and many other emergency situations, convergences have had a very difficult time coming to consensus on contingency plans.', CAPTION, '[2]');" onmouseout="nd();">[2]</a>.</p>
<p><em>Conflict Resolution</em> &ndash; Spokescouncils work when the difficult and problematic power dynamics within small groups are prevented from affecting decision-making by dividing power by the number of participants. Autonomous groups that report to and share with a collective spokescouncil are able to focus on their own work in ways that convergence organizers cannot. If the organizing body of a convergence is having a difficult time balancing power, coming to consensus, or following through on commitments, <em>everyone loses.</em></p>
<p><em>Adjustments</em> &ndash; Convergences as they have been historically organized don&rsquo;t allow us to <em>hone</em> our ability to prepare autonomous zones, precisely because they are models of imitation. The lessons learned at each consecutive convergence are rarely successfully passed from one organizing group to the next, and therefore the model cannot refine into better versions of itself; the imitated formula&mdash;centralized location, autonomous workshops, free accommodations, group activities, and reunion-socializing&mdash;only allows <em>so much</em> variation. A more active research and development of effective convergence models would be a worthwhile endeavor, but in the meantime the anarchist convergence will continue to be both flawed and valuable in <em>predictable</em> ways.</p>
<p><em>Cooperation</em> &ndash; Most importantly: even though readers of CrimethInc. literature and other members of the anarchist community have infinitely diverse contexts, perspectives, and interests, CrimethInc. Convergences have a certain reputation, and therefore a limited attraction. It makes sense that we have always maintained a &ldquo;become part of the organizational effort, or plan a convergence according to your own needs&rdquo; stance when it comes to criticism, but that attitude only works in deflecting those eager naysayers who would sooner complain about the priorities of others than work on behalf of their own. When it comes to learning the greatest lesson of massive collective undertakings&mdash;working together for common objectives despite social grievances&mdash;anarchists of all stripes and affinities must be <em>encouraged by the model</em> to work side by side. If the convergence doesn&rsquo;t give us an opportunity to at least <em>try</em> to work together in this way, we should develop other models that do.</p>
<h3><a name="reunion">To reunite old comrades in new ways</a>.</h3>
<p><em>Distractions</em> &ndash; The convergences are treasured mostly because they offer an opportunity for old friends to meet, socialize, renew their networks, and have adventures together. However, convergences are actually <em>difficult</em> places to catch up with old friends because the constant schedule of activities demands attention and participation. Not to mention that anyone who has been to more than one convergence often ends up filling a de facto organizing position and then has more responsibilities than time to play and reminisce. It would be better to attempt to meet this objective separately from the others, than to force the rest of the objectives to become secondary priorities.</p>
<p><em>Subculture</em> &ndash; While we&rsquo;re at it, let&rsquo;s not forget the hundreds of people who went to one convergence and decided <em>never to go again.</em> The people on the sidelines during every convergence aren&rsquo;t interested in returning to reunite <em>precisely because</em> so much subcultural social networking and bonding occur during these open-invitation gatherings that newcomers outside the subculture rarely benefit from this objective.</p>
<h3><em><a name="uncontrollable">To be adventurous and uncontrollable</a>.</em></h3>
<p>We broke the convergence down into component parts and found that several mechanisms had been missing all along, and that far more had been bent out of true as a result of the torque and stress of the workload we hoped it could handle. As elements of the project, the objectives were both sound and optimistic, but when considered as parts of a whole they were lost in the mess of logistics. Untangling the objectives has meant looking at our mistakes closely and taught us in a new way to <em>learn from our experiments.</em></p>
<p>There are some who would try to relive their exhilarating first convergence moments, or experience them vicariously through new generations of participants, but ultimately feeling obligated to organize a convergence means that we have lost the initial spirit of them. But convergences dare us to <em>up the ante.</em> Sometimes that means moving beyond them, especially when they do not achieve our worthwhile objectives.</p>
<h5>In many ways the convergences have been successes beyond our wildest dreams. Friendships have been written in stone because of them. Conversations and debates have become book chapters and song verses. Workshops have changed lives.</h5>
<p>&nbsp;</p>
<p>Having achieved all of this means we can move beyond, to struggle for these objectives in different ways. We can challenge ourselves to greatness. It is in this spirit that we embark on the next great experiment: to <em>decentralize</em> the CrimethInc. Convergence. To announce to the world, to our comrades, to our comrades-to-be that <a href="/blog/2010/06/03/august-2010-we-are-everywhere/">WE ARE EVERYWHERE</a>.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h6>This has been the first of a two part series exploring the objectives of coordinated points-of-entry. To read part two, &ldquo;AUGUST 2010: We Are Everywhere,&rdquo; <a href="/texts/atoz/10pt2.php">click here</a>.</h6>
<p>&nbsp;</p>
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1] Although clearly we mean to say that many people cannot spend two weeks away from their jobs, it also needs to be made clear that many anarchists are so involved in local organizing that they cannot leave those projects for long either.</p>
<p>[2] In 2004, after a group of convergence-goers were arrested for mischief, chaos ensued and people evacuated when the JTTF began harassing people on the streets. The same disarray occurred 5 years later when the convergence was disrupted in Pittsburgh. In these and many other emergency situations, convergences have had a very difficult time coming to consensus on contingency plans.</p>
</div>