<h6>The following essay is the second in a two-part series regarding plans for a month of decentralized events and actions planned for August 2010. To skip from the future directly to the past, read part one, <a href="/texts/atoz/10pt1.php">The Objectives of the CrimethInc. Convergence</a>.</h6>
<p>&nbsp;</p>
<h1>AUGUST 2010: <br /> WE ARE EVERYWHERE</h1>
<h5>... and what it means to believe it.</h5>
<p>&nbsp;</p>
<p><em>It is early in the summer of</em> 2010 <em>and CrimethInc. agents have just <a href="/blog/2010/06/03/august-2010-we-are-everywhere/">announced plans</a> for a month of decentralized activities to help create visibility for anarchist projects and alternatives. After eight annual national gatherings, the</em> CrimethInc. Experimental Committee <em>has decentralized the  renowned</em> CrimethInc. Convergence. <em>The committee is tearing up their membership documents, and questioning the decision they&rsquo;ve just made. It is the first hours of morning, and the moon has just set behind the trees. The soil is fresh with rain. Rose blossoms open and wait for the bees.</em></p>
<p>This whole campaign began with these questions: can anarchists work together to achieve common objectives if only given a limited timeframe? Could we respond to a financial crisis or ecological disaster before we missed the opportunity? Could we mobilize solidarity for our allies if they asked for it? What if we could? What if we knew we could? If those remain hypothetical questions, will we be doomed to miss opportunities until &ldquo;the time is right&rdquo;, or is it that we simply lack a model?</p>
<p>That is why we have torn out our hair, debated through the night, collapsed in exhaustion: looking for a model to share with each other, looking for an answer to these questions. <strong>Our first experiment is this: a month of activities, with only two months to prepare.</strong> We&rsquo;ve organized a fire drill, a giant game of capture the flag using an atlas: everyone can participate, and we&rsquo;re all on the same side. Every person&rsquo;s contribution benefits every other participant equally.</p>
<p>&nbsp;</p>
<h5>At the end of the summer, we will all feel the results of this challenge. We can determine where we stand with respect to these questions. That is to say, we can determine how much we&rsquo;ve won. To make these determinations, we will outline the following objectives clearly ahead of time so that we can learn important lessons later, whatever the results.</h5>
<p>&nbsp;</p>
<h2>WHY ARE WE EVERYWHERE?</h2>
<h4> <a href="#accessible">To maintain an accessible point-of-entry into the anarchist community!</a> </h4>
<h4> <a href="#visibility">To demonstrate a sustainable way to organize on a national scale, <em>without</em> a summit!</a> </h4>
<h4> <a href="#inspiration">To invigorate and inspire anarchist communities!</a> </h4>
<h4> <a href="#values">To create a safe and experimental space to hone and practice our values!</a> </h4>
<h4> <a href="#autonomy">To practice managing and organizing zones of autonomy!</a> </h4>
<h4> <a href="#reunion">To reunite old comrades in new ways!</a> </h4>
<h4><em><a href="#uncontrollable">To be adventurous and uncontrollable!</a></em></h4>
<p>&nbsp;</p>
<hr />
<h3><a name="accessible">To maintain an accessible point-of-entry into the anarchist community!</a></h3>
<p><em>Tours</em> &ndash; By encouraging groups to tour the country with workshops, discussions, and presentations, we can spread information and initiative throughout our regional networks. We can bring communities together on terms determined by local anarchists. The concurrence of enthusiastic adventures with practical activities means that new spaces can open within seasoned arenas. Similar strategies have been <a href="http://news.infoshop.org/article.php?story=03/04/17/0399549" target="_blank">tried before</a>, but by existing as a part of a larger model, these will encourage accessibility, rather than limit it. </p>
<p><em>Localized Events</em> &ndash; Because locals are most likely to know what will be appropriate and effective, their organization of <a href="http://www.youtube.com/watch?v=-79pX1IOqPU" target="_blank">creative actions</a> can invite visibility in ways that national events are doomed to make mundane. Opening the scope of possibilities to include and benefit from small-scale autonomous activity will demonstrate and focus our resources, achieving our objectives in ways that reach beyond our communities and into our collective momentum. </em></p>
<h3><a name="visibility">To demonstrate a visible and sustainable way to organize on a national scale <em>without</em> a summit!</a></h3>
<p><em>Visibility</em> &ndash; In identifying common objectives and demands, we can create a <em>phenomenon</em> that maintains cohesive visibility in the <a href="http://www.youtube.com/watch?v=uoMo-66JADg" target="_blank">mainstream</a>, <a href="http://www.dailyillini.com/news/champaign-urbana/2010/04/14/local-anarchists-aim-to-share-power" target="_blank">independent</a>, and <a href="http://vimeo.com/4956175" target="_blank">social</a> medias. We can open ourselves to our neighbors, locate ourselves for our allies, and fortify our position against our enemies. We can insist that a group of touring legal workers protecting against repression can hail from the same imperative that inspires a collective of gardeners to distribute free produce&mdash;we can wave a black flag and announce that <em>none of us will ever surrender.</em></p>
<p><em>Movement</em> &ndash; Because it is possible to move together in the maelstrom of street confrontations, it is also possible to move together on a field the size of a continent. To practice doing so will illuminate the context of our daily work so that we might always move this way.</p>
<h3><a name="inspiration">To invigorate and inspire anarchist communities!</a></h3>
<p><em>Infrastructure</em> &ndash; Every day anarchists work to found and maintain projects and communities; our campaigns should both benefit from and contribute to these things so that they may never be separate or lost from our struggle for other worlds. We cannot continue to overwhelm them with stress, nor can we ever be afraid to work with them carefully to achieve broader goals: local infrastructures can <em>safely conduct electricity.</em></p>
<p><em>Pressure</em> &ndash; That we are organizing in decentralized ways means that we can focus on working through the problematic power dynamics in our relationships without jeopardizing the success of the larger campaign. We know that this work will never be completed&mdash;<em>nor will it ever be possible to postpone</em>&mdash;so we should not organize campaigns that don&rsquo;t enable that work to be done.</p>
<h3><a name="values">To create a safe and experimental space to hone the practice of our values!</a></h3>
<p><em>Affinity</em> &ndash; Working with people you trust means that you can resolve important issues and work on your projects at the same time, that you can safely confide in your companions, that you can trust them to have your interests in mind. Just as we can form tours or organizing groups that we feel safe in, we can organize events in the communities to which we belong: wherever the moments of <em>everywhere</em> occur, they will be part of everywhere and therefore stand not above or below, but beside. </p>
<p><em>Risk</em> &ndash; By traveling and being everywhere, we demand that agents of repression must also be everywhere, and thus maximize the expense of investigating our friendships, interfering with our personal lives, and preying on our young. We cannot be cornered, and we will not be undermined&mdash;whether or not we can be outnumbered has nothing to do with the number of anarchists who travel to summits, but how many more homes of resistance there are than police stations. By waving our flags now, we&rsquo;ve already won.</p>
<h3><a name="autonomy">To practice managing and organizing zones of autonomy!</a></h3>
<p><em>Autonomy</em> &ndash; Before we are ever capable of actualizing collective desires, we must first feel free to act on our own. By planning our own activities and taking responsibility for our contributions, we can exercise our abilities and demonstrate our intentions. In doing so, we will bounce through  everywhere, building a charge and attracting companions.</p>
<p><em>Community</em> &ndash; It is about time we table our obscure disputes and nay-saying! This model was prepared from scratch to preempt everyone who would refuse to participate on the grounds that their theoretical rivals were <em>also</em> participating. Working together without agreeing on every issue is what makes anarchism happen&mdash;the more we show that we are willing to stand beside our adversaries in theory, the more we will be able to coordinate against our adversaries in <em>real life.</em></p>
<h3><a name="reunion">To reunite old comrades in new ways!</a></h3>
<p><em>Intersections</em> &ndash; For all those socialites who long to reunite with old friends, you must from now on <em>work</em> for it. If you would travel across the country to catch up with your friends during a national gathering, you should be willing to make stops along the way, and foresee the points of intersection ahead of time.</p>
<p><em>Assembly</em> &ndash; There is no reason that regional gatherings cannot be organized in the span of two months. Go ahead and plan them, perhaps cleverly located on the <a href="http://www.cnn.com/2010/US/05/27/oil.spill.amount/" target="_blank">shores of Louisiana</a> or the <a href="http://www.youtube.com/watch?v=s1ZO8FSGPV4" target="_blank">mountains of Appalachia</a> or the <a href="http://afterthefallcommuniques.info/" target="_blank">classrooms of California</a> or in the <a href="http://www.youtube.com/watch?v=WHPxUwayNzA" target="_blank">foreclosed homes that belong to your friends</a>.</p>
<p>&nbsp;</p>
<h2><em><a name="uncontrollable">To be adventurous and uncontrollable!</a></em></h2>
<p>In setting the timeframe for the whole month of August, we took a daring risk: <em>what if nothing happens?</em> But that is a pointless question to ask <em>now.</em> What if we asked ourselves that <em>every day?</em> What if we had asked ourselves that five weeks ago when oil first started pumping into the Gulf of Mexico? What if we had asked ourselves that in the days following the recent credit crisis that sent stock markets plummeting and banks into ruin? What if anarchists had asked themselves that on September 12, 2001? Surely, the more appropriate question is &ldquo;what parts of August will bear our name?&rdquo; How much will we know about anarchist activity in North America on September 1, 2010? What will we feel capable of doing after we know this about ourselves? These are questions that <em>will</em> be answered. </p>
<p>We are proposing this broad strategy because we are tired of focusing on the differences. Each of us live our lives differently, it&rsquo;s true. Every anarchist has deeply personal perspectives on power, society, and the world around us, so there are bound to be disagreements. But let&rsquo;s see what it means to activate our own rebellions in concert. What it will mean to be <em>visible together.</em></p>
<p>&nbsp;</p>
<h5>Let&rsquo;s sound the fire drill! Do what moves you! If you already have plans for August, unfold them harder! If you&rsquo;ve got a black flag, that&rsquo;s all you&rsquo;ll need! Adorn it with whatever color you please! Let&rsquo;s get all over the place! Fight where you stand! Climb the nearest whatever and announce it! Let it echo from collective house to social center! From folk band to hip-hop crew! From garden plot to giveaway! From classroom to janitor closet!</h5>
<p>&nbsp;</p>
<p>This August 2010, do something. Get Everywhere. Do something thirty-one times in a row. Do something on your lunch break. Challenge yourself to play well with others. Observe all the principles that make for effective protests and potlucks. Sell shit to pay for gas or never leave the park bench. Wave the black flag or burn it, just let people know: <strong><a href="/blog/2010/06/03/august-2010-we-are-everywhere/">WE ARE EVERYWHERE</a></strong>.</p>
<p>&nbsp;</p>
<h6><em>The birds are singing,</em></h6>
<h4><strong>&ndash; The CrimethInc. Experimental Committee.</strong></h4>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h6>This has been the second in a two part series exploring the objectives of coordinated points-of-entry. To read part one, &ldquo;The Objectives of the CrimethInc. Convergence,&rdquo; <a href="/texts/atoz/10pt1.php">click here</a>.</h6>
