<h1>Accounting for Ourselves</h1>
<h2>Breaking the Impasse Around Assault<br />and Abuse in Anarchist Scenes</h2>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/justice/1b.jpg" rel="lightbox[justice]"><img src="https://cloudfront.crimethinc.com/images/justice/1c.jpg" width="500" height="499"/></a></p>
<p>Sexual assault and abuse continue to plague anarchist circles and spaces. In response, we&#8217;ve developed processes to hold each other accountable outside of the state. But why can&#8217;t we seem to get them right? This essay examines the context in which these community accountability models emerged and analyzes the pitfalls we&#8217;ve encountered in trying to apply them. To move beyond the impasse around sexual violence within our scenes, we need to challenge the idea of community itself and take our resistance in new directions.</p>
<h2>Introduction</h2>
<h5><em>“I don&#8217;t believe in accountability anymore…<br />my anger and hopelessness about the current model are proportional to how invested I&#8217;ve been in the past. Accountability feels like a bitter ex-lover to me… the past ten years I really tried to make the relationship work, but you know what?”</em><br />
-Angustia Celeste,<br /><a href="http://anarchalibrary.blogspot.com/2011/01/safety-is-illusion-reflections-on.html">“Safety is an Illusion: Reflections on Accountability”</a></h5>
<h3>Getting Started: Origins and Purpose</h3>
<p>Sexual assault and abuse tear us apart. They fracture our communities, ruin individual lives, sabotage projects and organizing, reveal nasty contradictions between our supposed ideals and our actual practices, and maintain a climate of fear and oppression, especially for women. Sexual assault is political; it is a function of patriarchy, not just an individual harm done by individual people (usually men) to others (most often women). Sexual assault and abuse, partner violence, child abuse, and sexual harassment are primary ways that men physically impose domination over women. Sexualized violence helps to maintain patriarchy, heterosexism, trans oppression, ageism and oppression of youth, racist colonialism, and genocide. The struggle against sexual assault and abuse is essential for revolutionary transformation. </p>
<p>The <em>accountability process</em> model has been one of the primary tools used by anarchists to address assault and abuse in recent years. This essay analyzes this model in hopes of provoking honest, self-critical discussion about how we respond to assault and abuse within anarchist scenes, and imagining directions to move forward.</p>
<p>This article is NOT intended to serve as an accessible introduction to community accountability processes; it assumes that you have some knowledge of what they are and how they work (or don&#8217;t work). It draws specifically on North American anarchist, punk, and radical activist subcultures and presumes that the reader understands their context and language. If you don’t, try reading some of <a href="appendix">the sources cited below</a> before this one. If you&#8217;re an anarchist and you&#8217;ve had some experience with efforts to respond to assault and abuse within your scene under the label of “accountability,” this is intended for you. </p>
<h3>Gender Frameworks</h3>
<p>Gender is complicated; some folks we might perceive as male or female don&#8217;t identify that way, and some don&#8217;t identify as either. In referring to “men” or “women,” we mean folks who identify that way, whether <a href="http://en.wikipedia.org/wiki/Cisgender">cisgender</a> or transgender. Throughout this essay, both survivors and people who&#8217;ve assaulted or abused others are referred to in general using “they” as a gender-neutral pronoun. Assault and abuse can be committed by anyone against anyone, across gender lines; sometimes cis women, trans men and women, and genderqueer folk assault, and often cis men are survivors as well. But this acknowledgment should not erase the fact that the vast majority of folks who abuse and assault are cis men, and the majority of folks they abuse and assault are women. </p>
<p>Sexual assault and abuse are neither gender-specific (i.e., they can only happen by or to people of a certain gender) nor gender-neutral (i.e., the gender of a person who assaults or is assaulted is irrelevant to the conversation). We must understand the gendered patterns of assault and abuse as an expression of patriarchal domination, without making invisible experiences that fall outside of that gendered framework.</p>
<h3>Restorative and Transformative Justice</h3>
<p>In speaking about accountability processes, we’re referring to collective efforts to address harm—in this case, sexual assault and abuse—that focus not on punishment or legal “justice” but on keeping people safe and challenging the underlying social patterns and power structures that support abusive behavior. In the loosest sense, this might simply mean a few friends sticking up for someone who&#8217;s been hurt: asking them what they need, and trying to negotiate for those needs with the person who hurt them and among the community they share. Some processes involve a group that mediates between an individual and the person calling them out, or separate groups supporting each person and facilitating communication between them. These processes usually involve setting out conditions or “demands” for the person who&#8217;s been called out as a means of restoring safety or trust and preventing the harm from happening again, and some method for following up to ensure that these demands are met. All of these different approaches share an intention to address the harm done directly without relying on the state.</p>
<p>Community accountability appeals to anarchists as a critical alternative to the <a href="http://en.wikipedia.org/wiki/Adversarial_system">adversarial framework</a> of the criminal “justice” system. According to this framework, two parties in conflict are assumed to have opposite interests; the state considers itself the aggrieved party and thus acts as mediator; and “justice” means deciding which person is correct and which person suffers consequences—which are determined by the state, and usually unrelated to the actual harm done or its root causes. In contrast, <a href="http://en.wikipedia.org/wiki/Restorative_justice"><em>restorative justice</em></a> focuses on the needs of the ones harmed and those who did harm, rather than the need to satisfy the abstract principles of law or to exact punishment. Folks who&#8217;ve been harmed play an active role in resolving a dispute, while those who harm are encouraged to take responsibility for their actions and repair the harm they&#8217;ve done. It is based on a theory of justice that sees “crime” and wrongdoing as an offense against individuals or communities rather than the state. Many of the current working models for restorative justice originated in Maori and North American indigenous communities. </p>
<p>Building on that framework, the <a href="http://generationfive.org/tj.php"><em>transformative justice</em></a> model links restorative justice&#8217;s focus on rectifying harm rather than strengthening state power with a critique of systematic oppression. According to <a href="http://www.generationfive.org">Generation Five</a>, an organization that grounds their work to end child sexual abuse in this model, the goals of transformative justice are:</p>
<ul>
<li>Safety, healing, and agency for survivors</li>
<li>Accountability and transformation for people who harm</li>
<li>Community action, healing, and accountability</li>
<li>Transformation of the social conditions that perpetuate violence—systems of oppression and exploitation, domination, and state violence</li>
</ul>
<p>The anarchist practice of community accountability rests in theory on these underlying principles, along with the DIY ethic and a focus on direct action. </p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/justice/2b.jpg" rel="lightbox[justice]"><img src="https://cloudfront.crimethinc.com/images/justice/2a.jpg" width="500" height="500"/></a></p>
<h2>Where We&#8217;re At</h2>
<h3>Anarchist Community Accountability: Recent History and the Current State of Things</h3>
<p>How did this set of practices around responding to sexual assault and abuse emerge? In the 1990s and early 2000s, women and other survivors responded to assault and abuse in a variety of ways, including making zines calling people out to distribute at shows, discussing their experiences amongst themselves, warning people in other communities about repeat assaulters, and in some cases <a href="http://www.zinelibrary.info/files/Men%20In%20The%20Feminist%20Struggle.pdf">physically confronting them</a>. The Hysteria Collective based in the Portland, OR area represented one of the early structural attempts to respond to sexual assault, producing and distributing literature, challenging the presence of abusive men in the punk scene, and organizing a conference. In other towns, folks formed girl gangs for self-defense and concerted confrontational action. However, more often than not, such efforts were isolated, belief in rape myths persisted amongst anarchists (especially men), and survivors who attempted to speak out were ignored, shunned, dismissed for distracting attention from more important issues, or blamed for COINTELPRO-style divisiveness.</p>
<p>In response, anarchist women and others worked to encourage anarchist scenes to take sexual assault and abuse seriously and promote a culture of consent. Much of this spread through zine culture, particularly Cindy Crabb&#8217;s <a href="http://www.dorisdorisdoris.com"><em>Doris</em></a> and <a href="http://www.phillyspissed.net/"><em>Support</em></a> zines; also, workshops began appearing at radical conferences discussing survivor support, consent, and positive sexuality. Men&#8217;s groups began to organize against sexual violence in some radical scenes, such as the <a href="http://zinelibrary.info/dealing-our-shit-six-years-mens-group-and-accountability-work">Dealing With Our Shit (DWOS) collective</a> founded in Minneapolis in 2002. A major turning point occurred at the 2004 Pointless Fest in Philadelphia, where concert organizers <a href="http://www.slugandlettuce.net/columns/guest-columnist-81-phillys-pissed-statement">publicly announced that three women had been raped</a> at the event and established collectives to support the survivors and figure out how to deal with the rapists. These collectives became <a href="www.phillyspissed.net">Philly&#8217;s Pissed</a> and <a href="http://www.phillystandsup.com">Philly Stands Up</a>, long-standing separate but collaborating collectives devoted respectively to survivor support and assaulter intervention.</p>
<p>Assault, accountability, and consent became topics at nearly all anarchist conferences and gatherings. Many distros began to carry zines on the subject, touring bands spoke from stage about it, and anarchists in many other cities formed support and accountability collectives. Organizers of mass mobilizations began to develop plans for response, culminating in a full-scale <a href="http://medic.wikia.com/wiki/Responding_to_Sexual_Assaults_as_Mass_Mobilizations">sexual assault response infrastructure at the anti-G20 convergence</a> in Pittsburgh in 2009.</p>
<p>So how do things stand today? Terms such as “consent,” being “called out,” “accountability process,” and “perpetrator” are in wide use, to the point of becoming the subject of jokes. A great many people have been called out for abusive behavior, and dozens of accountability processes are ongoing in various stages. An identity politics around the labels “survivor” and “perpetrator” has emerged, with scenes polarizing around them. In spite of <a href="http://news.infoshop.org/article.php?story=2008all-survivors">efforts to caution against this</a> and encourage all participants in accountability processes to remain self-critical, these labels have sometimes been used to leverage power, dispense or deny legitimacy, and erase differences in experience.</p>
<p>Philly Stands Up continues their work, getting paid by colleges to lead trainings on their model and functioning as a sort of semi-formal sexual assaulter surveillance organization, with folks from around the country contacting them for updates on different ongoing processes. They networked with other groups doing transformative justice work at the US Social Forum in Detroit and hosted a three-day training for community accountability organizers in January 2011. Numerous other similar collectives have been attempted among anarchists in other cities, though few have had the longevity or prominence of PSU. As more and more intra-scene communication moves onto the internet, a number of websites (most prominently <a href="http://www.youtube.com/watch?v=dQw4w9WgXcQ">anarchistnews.org</a>) have become major hubs for shit-talking around the politics of assault and accountability. Websites have also appeared giving information about specific individuals who have assaulted or abused others. </p>
<p>Most anarchist gatherings now issue guidelines about consent and sexual assault response, and often address the presence of people involved in accountability processes. Based on the policies developed by sexual assault response organizers at the 2009 Pittsburgh anti-G20 mobilization, organizers at the 2010 anti-IMF mobilizations in Washington DC posted an announcement stating <a href="http://news.infoshop.org/article.php?story=20100929155610284">“No Perpetrators Welcome.”</a> It explained that in an effort to make the demos safe for survivors, “people who have perpetrated in the past, people running away from accountability processes, and people who refuse to respect the IMF Resistance Network consent guidelines” were prohibited from all organizing spaces and events. More recently, organizers for the 2012 <a href="http://torontoanarchistbookfair.wordpress.com/sexual-assault-and-consent-policy/">Toronto Anarchist Book Fair</a> echoed this language banning all perpetrators, but added: </p>
<h6>We understand and respect that communities have engaged in their own processes around these incidents. If you have gone through an accountability process and the survivor, joined by the community, feels you have sufficiently dealt with your shit, this statement does not include you.</h6>
<p>Likewise, the organizers of the 2012 <a href="http://www.anarchistbookfair.net/saferspace">New York Anarchist Book Fair</a> banned:</p>
<h6>People who have perpetrated inter-personal violence, assault and/or harassment unless they are actively engaged in an accountability process and currently in compliance with all the terms and/or demands of that process (according to the facilitators, the survivor, and/or whomever&#8217;s been designated to monitor the agreements emerging from the process). </h6>
<p>A major source of controversy has been the pre-emptive banning of individuals who&#8217;ve been called out for sexual assault or abuse from anarchist gatherings. In recent years, survivors and their supporters have increasingly requested for particular individuals who have sexually assaulted others to be banned from upcoming events. Organizers have struggled to prioritize believing survivors without pre-emptively condemning people, and to balance transparency against privacy and avoiding retraumatization. An <a href="http://libcom.org/blog/safer-spaces-false-allegations-nyc-anarchist-bookfair-26042012">internet brouhaha</a> emerged when a person online posted an email they had received from organizers of the New York Anarchist Book Fair, asking them not to attend without specifying the reason. Some interpreted the email as a <a href="http://libcom.org/forums/news/kafka-sales-will-be-through-roof-nyc-anarchist-book-fair-10042012">Kafkaesque</a>, authoritarian presumption of guilt through anonymous rumor, while others defended it as an effort to remain neutral while attempting to secure a sense of safety for other attendees.</p>
<p>While controversies persist around our methods of response to sexual assault, norms around sexuality have shifted significantly within anarchist scenes in recent years. Discourses of consent have expanded, while information about assault, survivor support, and options for accountability has become increasingly available. This has noticeably changed how we conduct sexual relationships, relate to our own bodies, and respond to survivors. Compared to previous years, many anarchists have become more conscious of sexual power dynamics and increasingly empowered to communicate boundaries and desires.</p>
<p>However, sometimes abusers in anarchist communities “talk the talk” of consent and support while doing the same old shit. As the author of &#8220;<a href="http://anarchalibrary.blogspot.com/2010/10/is-anarchist-man-our-comrade-2010.html">Is the Anarchist Man Our Comrade?”</a> challenges:</p>
<h6>Accountability processes often do a lot of good but sometimes they just teach men how to appear unabusive when nothing&#8217;s changed but the words coming out of their mouth. Survivors and friends are left wondering if said male is no longer a threat. Eventually the issue recedes from peoples&#8217; minds because they don&#8217;t want to seem overly reactionary and don&#8217;t know what further steps to even take and the perpetrator is able to continue on in their life without much changing.</h6>
<p>How can we prevent these discourses from being appropriated by the sensitive anarcha-feminist sexual assaulter? It seems that the availability of community accountability processes hasn&#8217;t changed the patterns of behavior they were developed to address. What isn&#8217;t working here?</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/justice/3b.jpg" rel="lightbox[justice]"><img src="https://cloudfront.crimethinc.com/images/justice/3a.jpg" width="500" height="408"/></a></p>
<h3>Ten Pitfalls of Community Accountability Processes</h3>
<p>Two important qualifications: first, these are pitfalls of accountability processes <em>as they&#8217;re actually practiced,</em> as we&#8217;ve experienced them. Some of these pitfalls aren&#8217;t inherent to these processes, but are simply mistakes commonly made by people who undertake them. One might respond to many of these critiques by saying, “Well, if people actually applied the model as it&#8217;s intended, that wouldn&#8217;t happen.”</p>
<p>Fair enough; but for any such model to be widely relevant and applicable, it has to be robust enough to be able to succeed even when conditions aren&#8217;t optimal, or when folks don&#8217;t or can&#8217;t follow the model perfectly. So bear in mind that these pitfalls don&#8217;t imply that our accountability models are futile or doomed. On the contrary, <em>because</em> we&#8217;re invested in figuring out how to end assault and abuse, we have to be unflinchingly critical in examining efforts to do so.</p>
<p>Second, the things people frequently say to avoid responsibility should not be mistaken for problems with accountability processes. For example: “This stuff distracts us from the real revolutionary issues; it&#8217;s divisive and hurts the movement; holding people accountable is manipulative/coercive/overemphasized/a power grab,” and so forth. These are not pitfalls of accountability processes; these are problems of patriarchy and its supposedly anarchist apologists. </p>
<p>That said, here are some of the major difficulties we&#8217;ve encountered in the processes we&#8217;ve developed to hold each other accountable for sexual assault and abuse within anarchist scenes.</p>
<p>1) <strong>There is no clear sense of when it’s over, or what constitutes success or failure.</strong> When can we say definitively that a certain person has “worked on their shit”? What will allow a survivor and their supporters to feel comfortable with someone continuing to participate in a shared community? When expectations aren&#8217;t explicit, goals aren&#8217;t concrete, or the time-line and means of assessment aren&#8217;t clear, confusion and frustration can follow for everyone involved.</p>
<p>This often happens because we have so little experience with alternative modes of resolving conflict and addressing harm that we don&#8217;t know what to look for. For instance, even if a person has “been accountable,” the survivor may or may not necessarily <em>feel</em> better. Does this determine the success or failure of a process? If someone has done all the things asked of them, but others aren&#8217;t sure if the steps taken were effective, what <em>could</em> confirm that real change has taken place? It may or may not actually be possible to restore trust after harm has been done; if not, this may not be the right type of process to undertake.</p>
<p>Likewise, past what point can we agree that someone has NOT worked on their shit, and we shouldn&#8217;t bother wasting our time on it anymore? Some accountability processes drag on for months and years, diverting collective energy from other more fulfilling and useful ends. One stubborn sexist can sour an entire scene on making good faith efforts to hold folks accountable—which goes to show how important it is to know when to end an attempted process before it drags everyone down with it. If we&#8217;re going to invest so much time and energy in these processes, we need a way to assess if it&#8217;s worthwhile, and when to admit failure. And that requires determining what failure would mean: for instance, kicking someone out of a scene, trying other modes of response, or admitting to a survivor that we can&#8217;t enforce their demands.</p>
<p>2) <strong>Standards for success are unrealistic.</strong> For instance, the common demand that someone work on their proverbial shit is either too vague to be meaningful, or practically translates to a profound psychological transformation beyond the bounds of what we can achieve. As the article “<a href="http://www.anarchapistemology.net/archives/18">Thinking Through Perpetrator Accountability</a>” puts it:</p>
<h6>Perpetrator accountability is not an easy or short process… It takes a lifelong commitment to change behaviors that are so deeply ingrained; it requires consistent effort and support. When talking about follow-up, we should be making schedules for weeks, but also talking about checking in after months and years. It takes that kind of long-lasting support to make real transformation possible.</h6>
<p>Let&#8217;s be frank: if we expect people to remain involved in an accountability process for some scumbag they don&#8217;t even like for <em>years,</em> and we expect this as a norm for an increasing number of processes for different people, who may or may not be cooperative—we are not setting a realistic standard.</p>
<p>That&#8217;s not to say that the article is wrong; transformation of patriarchal and abusive behavior patterns is a lifelong process. But is it really a surprise that we fail to sustain these difficult, unrewarding processes stretching over such lengths of time, when few anarchists in our scene follow through on long-term commitments to even our most fervent passions? What can we <em>realistically</em> commit to doing?</p>
<p>3)<strong> We lack the collective ability to realize many demands.</strong> We can say we&#8217;re committed to meeting survivor demands, but that&#8217;s just empty rhetoric when that would require resources we don&#8217;t have. Do we know of suitably anti-authoritarian feminist counselors and therapy programs, and can we pay for them when the person called out can&#8217;t? Can we enforce our wishes on someone who isn’t cooperative—and as anarchists, should we? What consequences can we enact that actually matter? In a transient subculture, can we realistically commit to following up with someone for years into the future, and establishing structures of support and accountability that will last that long?</p>
<p>One phrase commonly used in survivor demands and support discourse is “safe space,” that ever-elusive place in which survivors will be able to feel comfortable and fully reintegrated into collective life. What does safety mean? Is it something that we can promise? From reading the policies of recent anarchist gatherings, it appears that the primary method of securing safe space involves excluding people who have harmed others. But safety means more than quarantining those who have ruptured it for particular people, since rape culture and patriarchy suffuse all of our lives—they’re not just the result of a few bad apples. While exclusion can shield survivors from the stress of sharing space with people who&#8217;ve harmed them, and help to protect folks in our community from repeatedly abusive people, exclusion falls painfully short of safety. In fact we may rely on banning others from spaces less because it keeps people safe than because it&#8217;s one of the only safety-related demands we can actually enforce.</p>
<p>In the essay “<a href="http://anarchalibrary.blogspot.com/2011/01/safety-is-illusion-reflections-on.html">Safety is an Illusion</a>,” Angustia Celeste condemns the “false promises of safe space”:</p>
<h6>We can&#8217;t provide survivors safe space; safe space in a general sense, outside of close friendships, some family and the occasional affinity, just doesn&#8217;t exist… there is no such thing as safe space under patriarchy or capitalism in light of all the sexist, hetero-normative, racist, classist (etc.) domination that we live under. The more we try and pretend safety can exist at a community level, the more disappointed and betrayed our friends and lovers will be when they experience violence and do not get supported.</h6>
<p>What would genuine safety for survivors and for all of us look like? Are there other strategies in that direction that we can enact beyond exclusion and ostracism?<a class="footnote" href="javascript:void(0);" onclick="return overlib('Challenging banning and exclusion as primary accountability tactics raises more thorny questions about how to evaluate survivor demands, not just in terms of our <em>ability</em> to enact them but our <em>willingness</em> to do so. Is our role as proponents of anarchist accountability simply to adhere to the demands set forth by a survivor, even if we disagree with them strategically or ethically? Being an ally can be defined as doing what the survivor wants, no matter what; but we believe that no liberation can result from suspending our autonomy and uncritically following demands, no matter whose. Yet when is it our place as supporters to criticize what a survivor claims they need to heal or feel safe?', CAPTION, '[1]');" onmouseout="nd();">[1]</a></p>
<p>4) <strong>We lack skills in counseling, mediation, and conflict resolution.</strong> Often survivor demands include finding a counselor or mediator. To be effective, this person should be willing to work for free or on a sliding scale; hold anti-authoritarian politics and a survivor-conscious feminist analysis; have the time and energy to take an active role in working with someone over a long period of time; and be close enough to the community to understand its norms, without being directly involved in the situation. How many of these people are there? How many of us even have basic active listening skills, let alone the ability to navigate complex dynamics of consent and assault, patriarchal conditioning, anti-authoritarian conflict resolution, and psychological transformation? And for those few who do fit the bill, or at least come close, how many aren&#8217;t already swamped and overwhelmed? </p>
<p>Perhaps this is everyone&#8217;s fault for not collectively prioritizing these skill sets. Fine, but what do we do right now? And how do we avoid creating a division of labor where folks with a certain set of skills or lingo become akin to authorities within anarchist versions of judicial processes?</p>
<p>5) <strong>This stuff depresses people and burns them out.</strong> It&#8217;s intense, emotionally draining work to engage in community accountability, often with little appreciation or compensation. It can be exhausting and unrewarding, particularly when the processes rarely succeed in keeping a community intact while satisfying all participants. The gravity of the work scares people off, and understandably so.</p>
<p>This isn&#8217;t to say that we should try to make community accountability for sexual assault and abuse fun and lighthearted. But we need to acknowledge that this is a barrier to people stepping up and staying committed for the long-term involvement we&#8217;re saying is necessary for success. And these problems are magnified when we rely on skills and experience that only a few people in our circles have.</p>
<p>6) <strong>Accountability processes suck up disproportionate time and energy.</strong> None of us signed up for anarchy because we love participating in exhausting, interminable processes to address the stupid ways people hurt each other within our subcultural bubbles. We became anarchists because we hate cops, because we love punk shows, because we want a freer world, and for a million other reasons. When we spend so much time and energy trying to resolve internal conflicts and convince intransigent sexists to take responsibility for changing their behavior, we risk cutting ourselves off from the passions that brought us together in the first place. </p>
<p>It&#8217;s easy to get demoralized about anarchist politics when we can&#8217;t even stop assaulting each other, let alone smash the state and abolish capitalism. It&#8217;s not that working to end sexual assault and patriarchy is not revolutionary—on the contrary! But if accountability processes⎯particularly frustrating and unsuccessful ones⎯come to occupy too much of our collective energy, we&#8217;re not likely to stay engaged and bring new folks into our struggles. </p>
<p>We can&#8217;t sweep assault and abuse under the rug and silence survivors in the name of false unity. This previous norm perpetuated oppression and made us less effective all around, prompting community accountability efforts to emerge in the first place. We have to find a way to deal with our abusive behavior that doesn&#8217;t swallow up all of our energy and demoralize us.</p>
<p>7) <strong>Subcultural bonds are weak enough that people just drop out.</strong> Bear in mind that many of the less coercive models of restorative justice on which community accountability frameworks are based originated in smaller-scale indigenous societies, with stronger social and cultural affinities than most any of us in the current United States can imagine. The notion that we should attempt to preserve the community and allow folks who&#8217;ve hurt others to remain integrated into it relies on the assumption that all parties are invested enough in this “community” to endure the scrutiny and difficult feelings that accompany going through an accountability process. The affinities that draw people into punk and anarchist scenes often aren&#8217;t strong enough to keep people rooted when they feel threatened by what they&#8217;re asked to do. Folks who&#8217;ve been called out often just pick up and leave town, sometimes even preemptively before they&#8217;re called to account for their shitty behavior. Short of communicating with similar social networks in the assaulter&#8217;s new destination (which happens increasingly often), there&#8217;s not much we can do to prevent that. When the primary consequences we can exact for noncompliance with accountability demands involve forms of ostracism and exclusion, people will avoid these by skipping town or dropping out.<a class="footnote" href="javascript:void(0);" onclick="return overlib('At times, people honestly trying to be accountable have left anarchist scenes entirely in order to give space to a survivor. While better than not cooperating, this subverts the transformative justice ideal of keeping folks part of a community.', CAPTION, '[2]');" onmouseout="nd();">[2]</a></p>
<p>8) <strong>Collective norms encourage and excuse unaccountable behavior.</strong> Our individual choices always occur in a social context, and some of the collective norms of anarchist scenes facilitate, if not directly justify, kinds of behavior that have often led to boundary-crossing and calling out. </p>
<p>For example, in many anarchist scenes, a culture of intoxication predominates and most social gatherings center around alcohol and drug use. Few safeguards exist when folks drink or use to excess, and few alternative spaces exist for those who want to stop or reduce their drinking or using without losing their social lives. Humor and conversation norms reinforce the notion that extreme drunkenness is normal and funny, and that people are less responsible for their actions while drunk then while sober. Weekend after weekend, we create highly sexualized spaces with strong pressure to get intoxicated, resulting in groups of people too drunk or high to give or receive solid consent.<a class="footnote" href="javascript:void(0);" onclick="return overlib('One common challenge occurs when someone doesn&#8217;t clearly remember what happened in an encounter for which they&#8217;ve been called out, or remembers the experience differently from how the person calling them out remembers it. A survivor may assume that this is simply a ploy to avoid responsibility, which is possible; but often, people&#8217;s memories simply don&#8217;t line up. If accountability processes are not pseudo-judicial attempts to determine “the truth” of what “really happened” as confirmed by some authority, how can we reconcile these differences? Do the memories of all parties have to match in order for demands to be legitimate? Can someone take responsibility for doing things they don&#8217;t remember?<br /><br />From our experience intervening with people who&#8217;ve been called out, acknowledging that someone may experience reality differently from them forms an important first step. For example, we can ask them to admit that something they experienced as consensual may not have been experienced that way by someone else. The sincere apology a survivor seeks may not be forthcoming if the person they&#8217;re calling out doesn&#8217;t remember an interaction in the same way. Still, accepting that the other(s) may have felt violated by something that they did can open someone towards examining and changing some of their behaviors, if not taking full responsibility.', CAPTION, '[3]');" onmouseout="nd();">[3]</a> Then in the aftermath of the harm caused in those situations, we expect individuals to deal with the consequences of their choices on their own, rather than all of us taking responsibility for the collective context that normalizes their behavior. </p>
<p>Of course, none of these dynamics excuse abuse. But sexual assault takes place in a social context, and communities can take or avoid responsibility for the kinds of behavior our social norms encourage. Alcohol and drug use is just one example of a group norm that excuses unaccountable behavior. Other entrenched dynamics that folks seeking accountability have cited as hindering their efforts include the idolization of scene celebrities (people in popular bands, renowned activists, etc.); the notion that sexual and romantic relationships are “private” and not the business of anyone outside of them; and the belief that groups who face systematic oppression (such as queers and people of color) shouldn&#8217;t “air the dirty laundry” of intra-community violence, since it could be used to further demonize them.</p>
<p>Are we willing to examine and challenge our group norms on a collective level, to see how they promote or discourage accountable behavior? Is it possible to hold entire scenes collectively accountable for what we condone or excuse? Attempting to hold a whole group of people accountable in some structured way would likely multiply all of the problems we experience with accountability processes oriented around a single person. Yet without acknowledging and challenging our collective responsibility, holding individuals accountable won&#8217;t be enough. </p>
<p>9) <strong>The residue of the adversarial justice system taints our application of community accountability models.</strong> Some of the most vitriolic backlash against accountability processes has been directed at their pseudo-judicial nature. On the one hand, folks who&#8217;ve harmed others rarely have experience being called to account for their behavior except via authoritarian systems; attempts to do so often prompt accusations of “witch-hunts,” “authoritarianism,” and cop/judge/lawyer/prison guard-like behavior. Previously anti-state militants often do miraculous turnarounds, suddenly becoming extremely interested in the US government&#8217;s guarantees of “justice”: <em>“Whatever happened to innocent until proven guilty, man? Don&#8217;t I get a fair trial? Can&#8217;t I defend myself? Listen to my character witnesses!”</em></p>
<p>On the other hand, folks pursuing accountability have received similar conditioning into adversarial conflict resolution, so it can be very easy to fall into that mode of framing the process—especially when faced with an infuriatingly stubborn anarcho-rapist. Some participants have used accountability processes as a way to threaten consequences or leverage power over others. While this may be an understandable response to the frustration and powerlessness often felt in the aftermath of abuse and assault, it can undermine attempts to pursue non-adversarial solutions. </p>
<p>A damning critique of the failure of anarchist accountability processes to escape the logic of the legal system comes in a <a href="http://occupyca.wordpress.com/2010/08/22/i-communique%CC%81/">communiqué</a> explaining why a group of women physically confronted a sexual assaulter:</p>
<h6>We did what had to be done out of sheer necessity. As radicals, we know the legal system is entrenched in bullshit—many laws and legal processes are racist, classist, heterosexist and misogynist. Alternative accountability processes, much like the traditional ones, often force the survivor to relive the trauma of the assault and force her to put her reputation—a problematic concept in itself—on the line as “proof” of her credibility. They end up being an ineffective recreation of the judicial process that leaves the perpetrator off the hook, while the survivor has to live through the memory of the assault for the rest of her life. The US legal system and the alternative community-based accountability processes are simply not good enough for survivors, and certainly not revolutionary.</h6>
<p>10) <strong>Sexual assault accountability language and methods are used in situations for which they were not intended.</strong> One example of this misapplication involves the widespread use of the principle of rape crisis survivor support specifying that supporters should “always believe the survivor.” This makes perfect sense in a rape crisis organization setting, solely focused on providing emotional support and services to an individual who&#8217;s experienced a form of trauma that is widely disbelieved, when being believed is instrumental to the healing process. But this doesn&#8217;t make sense as a basis for conflict resolution. In rape crisis counseling settings, or when someone discloses to you as a trusted friend seeking support, the focus should remain on the needs of the survivor. But transformative justice involves taking into account the needs and thus the experiences and perspectives of all parties involved, including the person who assaulted.</p>
<p>This does not mean that we have to figure out who&#8217;s telling the truth and who&#8217;s lying; that&#8217;s the residue of the adversarial system again. Nor does this mean that all perspectives are equally valid and no one is right or wrong. It does mean that to encourage someone to be accountable, we have to be willing to meet them where they&#8217;re at, which means accepting that one person&#8217;s experience can vary significantly from that of someone else. Being accountable requires being open to the possibility that one is wrong, or at minimum that someone else could experience the same event in a dramatically different, hurtful way. But having the survivor entirely define the operating reality may not lend itself to this mode of community accountability.</p>
<p>Another example of the overuse and misapplication of sexual assault accountability discourse comes when people call others into accountability processes for a wide range of behaviors that aren&#8217;t sexual assault. For instance, if someone feels angry and hurt after the breakup of a non-abusive relationship, it might be tempting to frame their grievances through the lens of calling someone out and demanding accountability. It could take the form of demanding that someone be banned from certain spaces, drawing on the gravity this exerts as a common accountability process demand. It&#8217;s understandable that folks who feel angry or hurt for any number of reasons might want the kind of instant validation of their feelings that can come (in some circles) from framing one&#8217;s hurt and anger as a call-out requiring “accountability”—whether or not that process and language makes sense for the situation.<a class="footnote" href="javascript:void(0);" onclick="return overlib('4 It&#8217;s difficult to acknowledge this without slipping into the kind of minimizing and denying language that&#8217;s so often used to silence survivors. We don&#8217;t want reactionaries to pick up on it and use it as another weapon in their arsenal of denial: “They&#8217;re just power-tripping on this &#8216;accountability&#8217; trend when that doesn&#8217;t even apply to this situation,” and so forth. Still, we need to be able to talk openly about this to learn how to respond more effectively to assault and abuse.', CAPTION, '[4]');" onmouseout="nd();">[4]</a> </p>
<p>This is dangerous not only because these terms and tactics were designed for certain types of conflicts and not others, but also because their overuse may trivialize them and lead others to treat dismissively the very serious situations of assault and abuse for which they were developed. It&#8217;s encouraging that issues of sexual assault and abuse have entered so widely into the discourses of radical communities. But we should be careful to avoid generalizing the methods developed for responding to one specific set of conflicts and oppressive behaviors to other situations for which they weren&#8217;t intended.</p>
<p>In some cases, folks frustrated by someone&#8217;s problematic behavior have even felt reluctant to call the person out on it for fear of that person being labeled a “perpetrator,” or of others presuming the hurtful but mild form of non-consensual behavior to have been sexual assault, and thus the person addressing it to be a “survivor.” When this overuse of sexual assault accountability language dovetails with the identity politics around survivor/perpetrator and policies such as the <a href="http://news.infoshop.org/article.php?story=20100929155610284">“no perps allowed”</a> statement, this effort to promote accountability could end up discouraging people from speaking out against other forms of crummy behavior, for fear of someone being permanently tarred with the “perp” brush rather than having a few conversations, apologizing, and reading a <a href="http://fruitiondesign.com/dealwithit/02wispy.php">zine</a>.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/justice/4b.jpg" rel="lightbox[justice]"><img src="https://cloudfront.crimethinc.com/images/justice/4a.jpg" width="500" height="302"/></a></p>
<h2>New Directions and Further Questions</h2>
<p>So where do we go from here? The widespread disillusionment with accountability processes suggests that we&#8217;ve reached an impasse. We&#8217;re proposing four possible paths to explore—not as solutions to these pitfalls so much as directions for experimenting to see if they can lead to something new. </p>
<h3>Direction 1: Survivor-Led Vigilantism</h3>
<p>“<em>I wanted revenge. I wanted to make him feel as out of control, scared and vulnerable as he had made me feel. There is no safety really after a sexual assault, but there can be consequences.</em>”
-Angustia Celeste, <a href="http://anarchalibrary.blogspot.com/2011/01/safety-is-illusion-reflections-on.html">“Safety is an Illusion: Reflections on Accountability”</a></p>
<p>Two situations in which prominent anarchist men were confronted and attacked by groups of women in New York and Santa Cruz made waves in anarchist circles in 2010. The debates that unfolded across our scenes in response to the actions revealed a widespread sense of frustration with existing methods of addressing sexual assault in anarchist scenes. Physical confrontation isn&#8217;t a new strategy; it was one of the ways survivors responded to their abusers before community accountability discourse became widespread in anarchist circles. As accountability strategies developed, many rejected physical confrontation because it hadn&#8217;t worked to stop rape or keep people safe. The trend of survivor-led vigilantism accompanied by <a href="http://occupyca.wordpress.com/2010/08/22/i-communique%CC%81/">communiqués</a> critiquing accountability process models reflects the powerlessness and desperation felt by survivors, who are searching for alternatives in the face of the futility of the other available options. </p>
<p>However, survivor-led vigilantism can be a valid response to sexual assault regardless of the existence of alternatives. One doesn&#8217;t need to feel powerless or sense the futility of other options to take decisive physical action against one&#8217;s abuser. This approach offers several advantages. For one, in stark contrast to many accountability processes, it sets realistic goals and succeeds at them. It can feel more empowering and fulfilling than a long, frequently triggering, overly abstract process. Women can use confrontations to build collective power towards other concerted anti-patriarchal action. Physical confrontation sends an unambiguous message that sexual assault is unacceptable. If sexual violence imprints patriarchy on the bodies of women, taking revenge embodies female resistance. Above all, it&#8217;s <em>unmediated</em>; as the author of the article <a href="http://news.infoshop.org/article.php?story=20100827153515576">&#8220;Notes on Survivor Autonomy and Violence&#8221;</a> wrote:</p>
<h6>A common criticism of accountability processes of all varieties is their tendency to mirror some sort of judicial system—structured mediation toward rehabilitation or punishment of one kind or another. While an outcome dictated by the survivor is certainly not akin to one dictated by the state, the process remains a <em>mediation</em>. Conversely, to move away from this judiciary is to reject mediation, a remnant of the idea that our interactions must be somehow guided by third parties, even third parties we choose ourselves. To that end, an attack on one’s rapist is unmediated and direct, precisely that which any judicial system forbids; the line between desire and action is erased.</h6>
<p>Of course, there are plenty of disadvantages to vigilantism, too. Choosing to escalate the situation brings serious risks, both legally and physically. Cops are more likely to bring charges for a group physical assault on a man than an “alleged” sexual assault. And, as advocates for battered women know, partner violence has a very real possibility to turn deadly; more women are killed by their partners than by any other type of attacker. Beyond the immediate risks, you can&#8217;t beat up a social relationship, as they say; throttling an individual scumbag doesn&#8217;t do much to make anyone safer or end systematic rape culture, however satisfying it may feel to a vindicated survivor. As mentioned above, the desire to address the roots of rape culture in responding to individual assaults helped give rise to community accountability efforts in the first place. </p>
<p>There&#8217;s also a legacy of non-survivor-accountable vigilantism, a type of male violence that has been widely identified by survivors and anarchist women as being more about masculine ego trips than promoting healing and safety. A critique of this phenomenon comes from <a href="http://www.phillyspissed.net/sites/default/files/survivor-support.pdf"><em>Supporting a Survivor of Sexual Assault</em></a>, a zine oriented towards male allies of survivors, in its discussion of the principle “No More Violence”:</p>
<h6>Is kicking a rapist’s ass going to make the rape not have happened? Will his pain make the survivor’s go away? Does the survivor need to be trying to chill out another out-of-control, violent man? Probably not. </h6>
<h6>Since non-trans men commit the overwhelming majority (some say over 99%) of sexual assaults, men who are supporting a survivor need to be especially conscious of the impact of male violence. It is male violence that causes rape, not what ends it. Your actions must be those of ending male violence. </h6>
<h6>We cannot speak for the responses that survivors, women in particular, may make to rape. If women, as a majority of survivors, decide to collectively respond in a way that involves violence or asking male supporters to participate in violence; that is something for women and survivors to work out for themselves. For men who are supporting a survivor, however, it is <strong>absolutely essential</strong> that you put aside your desires for masculine retribution and interrupt the cycle of male violence… It is not your responsibility, or right, to come in vigilante-style and take matters into your own hands.</h6>
<p>This critique influenced the decision of groups like DWOS in Minneapolis to adopt “non-violence” as a principle. Notice, however, that this critique intentionally does not apply to <em>survivor-led</em> vigilantism, but to unaccountable non-survivor responses. </p>
<p><a href="http://news.infoshop.org/article.php?story=2010091917451655">Apologists for anarchist men attacked by survivor-led groups</a> claim that vigilantism is authoritarian: “Accountability cannot be a one-way street or else it becomes a synonym for punitive and policing power.” But as the survivor communiqués make clear, vigilantism is not a form of “accountability,” at least not community accountability based on transformative justice as it&#8217;s generally conceived within anarchist circles; it&#8217;s an explicit rejection of it. It&#8217;s not a pseudo-judicial process; it declines both state-based and non-state methods of conflict resolution in favor of a direct, unmediated response to harm. Whether or not we think it&#8217;s appropriate, it shouldn&#8217;t be mistaken for a form of accountability gone wrong. On the contrary, it&#8217;s an intentional response to the perceived failure of accountability methods.</p>
<p>So long as our practices around accountability for sexual assault and abuse don&#8217;t successfully meet folks&#8217; needs, vigilantism will continue, challenging anarchist advocates of transformative justice to make their ideals a reality. Should we be trying to develop sufficiently effective accountability responses so that vigilantism isn&#8217;t necessary? Or should we be developing and extending our practices of survivor-led physical confrontation?</p>
<h3>Direction 2: Prevention Through Gender-Based Organizing</h3>
<p>It&#8217;s an obvious point, but worth making: instead of spending all this energy trying to figure out how to support people who&#8217;ve been assaulted and respond to those who assault, wouldn&#8217;t it make more sense to focus on preventing all this assaulting in the first place? Easier said than done, of course. But so far, we&#8217;ve only discussed reactive, after-the-fact responses to forms of harm that we&#8217;re assuming will continue, even as we figure out better ways to react. </p>
<p>To borrow the language of the nonprofit rape crisis center world, responding to assaults and working with assaulters through accountability processes falls under intervention, or tertiary prevention. Primary prevention entails preventing first-time assault and abuse through education and by shifting social, cultural, and institutional norms, while secondary prevention involves identifying risk factors associated with assault and abuse and intervening to prevent them from escalating. So we shouldn&#8217;t necessarily deem responses such as accountability processes failures if sexual assaults continue in anarchist communities. Instead, we should broaden the kinds of preventative work we&#8217;re doing alongside them. What might we be doing to stop all this from happening in the first place? </p>
<p>Outside of anarchist circles, prevention work around gender violence usually centers on education: for women, around self-defense and harm reduction; for men, around combating rape myths and taking responsibility for ending male violence; and for all, healthy communication and relationship skills. In anarchist circles, some women have mobilized around sharing self-defense skills, and a great deal of popular education (mostly led and conducted by women) has taken place around consent, communication with partners, and positive sexuality. As noted above, while this has noticeably shifted the sexual discourses used by anarchists, we need more extensive engagement with gender oppression to break entrenched patterns.</p>
<p>One pathway towards this deeper transformation has come through gender-based collectives, specifically men&#8217;s groups focusing on changing attitudes towards sexuality and consent among men. However, with a few exceptions such as <a href="http://zinelibrary.info/dealing-our-shit-six-years-mens-group-and-accountability-work">DWOS</a> in Minneapolis, the <a href="http://pioneerspress.com/catalog/zines/1791/">Philly Dudes Collective</a>, and the <a href="http://socialdetox.wordpress.com/tag/social-detox-1/">Social Detox</a> zine, there has not been much visible presence in recent years of anti-sexist men&#8217;s organizing among anarchists. Previously in certain scenes, anti-sexist men&#8217;s groups allied with autonomous women&#8217;s organizing. These formations are currently out of fashion for a number of reasons, including anti-feminist backlash, a certain understanding of trans and genderqueer politics that labels all gender-based organizing as essentialist and problematic, and the absorption of so many committed anti-patriarchy militants of many genders into sexual assault response and accountability work. Could forming anti-sexist men&#8217;s groups to do assault and abuse prevention work in tandem with autonomous women&#8217;s organizing prove fruitful as another direction in which to experiment?</p>
<p>This approach could offer several advantages. Creating structures to share skills for dismantling patriarchy and self-transformation might reduce problematic behaviors among participants while also providing an infrastructure for accountability responses when folks did harm others. Pre-existing men&#8217;s groups allow folks to take responsibility for self-education and action against patriarchy that doesn&#8217;t have to be contingent on a “perpetrator” label or “demands.” And folks could be referred to groups for a wide range of behaviors that might not raise eyebrows on their own but could be warning signs of underlying patriarchal patterns, so that others can intervene before those patterns manifest in more harmful ways (i.e., secondary prevention). For once, we&#8217;d have a place to offer folks who, whether by community compulsion or self-motivation, want to “work on their shit.”</p>
<p>But beyond just dealing with problematic behaviors, men&#8217;s groups provide space for deeper relationship building, learning, political clarification, emotional intimacy, even fun. This should provide incentive for folks to get involved and stay engaged, since it&#8217;s not centered solely on debilitatingly intense crisis-mode accountability work. The kinds of study, reflection, and relationship-building that take place in these groups can strengthen the other radical organizing folks are doing in anarchist scenes, leaving us with more options, skills, and people able to respond in crisis situations. And unlike many internally-focused community accountability strategies, men&#8217;s groups can interact with non-anarchist individuals and groups to spread anti-patriarchal messages and practices while learning from other feminist organizing, making our efforts relevant to broader social struggles against gender violence and patriarchy.</p>
<p>But wait… what about this whole gender thing? Amid the current gender politics of North American anarchist scenes, it&#8217;s common to view any gender-specific organizing as suspect. Isn&#8217;t this just a remnant of tired identity politics, vestiges of leftist guilt, outdated essentialism, and suspiciously authoritarian practices? Don&#8217;t we want to destroy the gender binary, the real root of patriarchy and gender oppression? And doesn&#8217;t organizing based on gender (or assigned gender or whatever) just reinforce the patriarchal and transphobic framework we&#8217;re trying to destroy?</p>
<p>Certainly there are difficult questions to address in determining who “counts” as a man, whether we base our understanding on self-identification or social recognition or birth assignation, where different genderqueer and trans folks fit, and figuring out who was “socialized” how. And ending hierarchy and alienation in all their forms will require strategies more liberating than identity politics. But let&#8217;s be realistic: distinct patterns of oppressive behavior and power still fall pretty predictably along gender lines. If gender-based organizing can help dislodge those patterns, perhaps we must embrace that contradiction and do our best to engage with it in all its messy complexity.</p>
<p>Beyond the question of gendered organizing in principle, there are other possible problems with this approach. Without subscribing to the notion that there are “good” anarchist men who&#8217;re not the sexual assaulters we need to worry about, we can acknowledge that the folks who might benefit most from examining their sexist behavior will likely be least inclined to participate. Also, participating in a formal men&#8217;s group could be a way for sexists to gain legitimacy, diverting attention from their crappy behavior by waving their feminist ally membership cards at people who call them out. And if the focus on gender-based organizing privileges men&#8217;s groups, even anti-sexist ones, over autonomous women&#8217;s and/or trans organizing, that could stabilize rather than challenge patriarchal power relations in a scene.</p>
<h3>Direction 3: Not Accountability, But Conflict Resolution</h3>
<p>Our struggles for accountability suffer because we have so few models, methods, or skills for resolving conflicts amongst ourselves. While it&#8217;s admirable that we&#8217;ve put so much energy into figuring out strategies for responding to assault and abuse, there are innumerable other kinds of conflict and problematic behaviors that we also need tools to address—and as we&#8217;ve seen, the sexual assault-specific accountability methodologies aren&#8217;t appropriate in dissimilar situations. What if we prioritized building our conflict resolution and mediation skills?</p>
<p>Of course, there are specific issues relevant to sexual assault and abuse, and these shouldn&#8217;t be eclipsed in a general focus on conflict resolution. But if there&#8217;s a precedent, language, and skill set for addressing a wide range of conflicts and harm, and being asked to participate in a conflict resolution process becomes common and less threatening, perhaps we&#8217;ll be able to respond less defensively when we learn that our actions have hurt others. Rather than extending the identity politics of survivor and perpetrator, we could create more nuanced language that neither idealizes nor demonizes people, but asks all of us to remain engaged in lifelong processes of self-transformation. This requires empathy towards folks who have done harm, to create space for them to own up to their behaviors and heal.<a class="footnote" href="javascript:void(0);" onclick="return overlib('5 As a self-described perpetrator explains in a comment on “Notes on Survivor Autonomy and Violence”: “I&#8217;m not saying that survivors have to feel empathy for people who did them violence. But if we&#8217;re going to build communities that can actually outsurvive patriarchy, instead of being atomized and pummeled to dust by it, I think somebody will need to have empathy for perpetrators. Speaking from my personal experience, I know that I never would have had the courage to actually own up to my shit and deal if I hadn&#8217;t found a couple folks that actually cared about me and found a way to show me empathy… And I don&#8217;t think empathy means making excuses for someone. In fact, in this context, I think it means not letting someone make excuses, not letting them escape their responsibility and their history, and making sure they own up to the consequences that come from the actions they&#8217;ve taken. It also means listening to them, sincerely, even while doing this, and seeking understanding. And I believe it means making sure that perpetrators do feel consequences for their actions, but not punishments. It also means finding resources so that the perpetrator can first learn and then practice a different pattern of habits and actions… I think what is required for accountability processes is empathy. Empathy and anger, at the same time.”', CAPTION, '[5]');" onmouseout="nd();">[5]</a></p>
<p>What are the advantages of framing sexual assault accountability processes within a broader emphasis on conflict resolution? There would be no need for a definitional hierarchy or litmus test to determine what “counts” as serious assault or abuse. By setting a precedent of collective engagement with less intense conflict, we would gain valuable experience to serve us in crisis situations. Framing conflict resolution as a collective responsibility could prevent the emergence of a specialized class of people who always facilitate these processes, and make it easier to find supporters with sufficient distance from a situation to be able to mediate neutrally.<a class="footnote" href="javascript:void(0);" onclick="return overlib('It&#8217;s worth asking whether or not “neutrality” is possible or desirable in conflict mediation. In many conflicts, one party wields greater power than the other, and if effort isn&#8217;t made to intervene in that power dynamic, neutrality can often amount to collusion with power. An alternative model of a mediator&#8217;s orientation towards parties in a conflict is “bipartiality” rather than neutrality. According to this framework, a mediator advocates for both parties, but also challenges them when they leverage their access to power within the conflict, asking them to consider the ways that their power blind them to the experiences of those lacking that power.', CAPTION, '[6]');" onmouseout="nd();">[6]</a></p>
<p>One cautionary point needs to be made very clearly: mediation is not appropriate for many cases of partner abuse. The article “Thinking Through Perpetrator Accountability” lays it out:</p>
<h6>Mediation should not be used as a substitution for an accountability process. Mediation is for two people having a conflict that needs to be resolved; abuse is not mutual. Abuse is not simply about two people needing to come to the table to work things out. Mediators may certainly be useful for helping to facilitate some of the concrete negotiations within an accountability process, but please do not suggest a session with a mediator as an option instead of a long-term commitment to an accountability process.</h6>
<p>Counselors for domestic violence survivors learn that “couples counseling” should not be undertaken in a clear situation of partner abuse, because abusers will usually manipulate the process, leaving the abusive and unequal dynamics underlying the relationship unaddressed. This is important to bear in mind so that a shift to a conflict resolution framework isn’t applied to situations of abusive relationships.</p>
<p>What about other disadvantages? Well, there&#8217;s still the problem of responding to existing problems by prescribing solutions that demand skills or resources we don&#8217;t have. What can we do in the meantime, while undertaking the long-term work of learning how to resolve our conflicts? Survivors might feel frustrated to see assault and abuse lumped in with less intense or politically significant conflicts, minimizing the harm they&#8217;ve experienced. Asking survivors to use less forceful language when addressing perpetrators could reinforce the survivor-blaming messages that they are overreacting, that sexual assault is not a significant issue worth naming strongly. Also, male “experts” in conflict resolution could hijack survivor support work and divert its feminist focus. We must acknowledge the specific context of sexual assault and abuse, honor the pain and rage of survivors, and account for oppressive power while broadening the range of conflicts we can address.</p>
<h3>Direction 4: Concentric Circles of Affinity</h3>
<p>“<em>There is no such thing as accountability within radical communities because there is no such thing as community—not when it comes to sexual assault and abuse. Take an honest survey sometime and you will find that we don&#8217;t agree. There is no consensus. Community in this context is a mythical, frequently invoked and much misused term. I don&#8217;t want to be invested in it anymore.</em>”<br />
-Angustia Celeste, <a href="http://anarchalibrary.blogspot.com/2011/01/safety-is-illusion-reflections-on.html">“Safety is an Illusion: Reflections on Accountability”</a></p>
<p>At the heart of all of these questions lies one unresolved problem: what is “community?” Are we in one together as anarchists? As punks? As people in a certain local scene? Because we&#8217;re at the same protest, show, or mass mobilization? Do we choose to be in it, or are we in it whether we like it or not, regardless of how we identify? And who decides all of this? </p>
<p>You can&#8217;t have community accountability without community. The entire transformative justice framework falls apart without some coherent sense of what community means. But unfortunately, no one seems to be able to answer this question for our milieu. And without an answer, we find ourselves banging our heads against the wall again and again, when a slimy assaulter just skips town or drops out of the scene after being called out, or when someone wields enough power in a scene to gerrymander the boundaries of community to exclude survivors and allies. This is not an abstract question: it&#8217;s fundamental to what we do and how power operates in our scenes.</p>
<p>Community becomes concrete through specific institutions, such as the websites, gatherings, social centers, and collective houses that comprise the North American anarchist scene. Although no one is taking attendance (except possibly the FBI), and many of us quarrel about who counts as a <em>real</em> anarchist, those of us who move through these spaces have a sense of being a part of something. We weave together this sense through shared practices that mark us as teammates: dress and body modification, quirks of diet and hygiene, conversation with specialized lingo and points of reference.</p>
<p>But is being a part of an anarchist “milieu” enough of a basis for the kind of community demanded by these accountability strategies? Can we realistically apply these models to our diffuse, fragmented, mostly unstructured associations of misfits? </p>
<p>As we move through our lives navigating connections with friends, neighbors, and comrades, we&#8217;re not just part of a single unitary community, or even a web of multiple communities. Rather, our relationships with others take the form of <em>concentric circles of affinity.</em> From these, we can trace a tentative model to imagine how to apply community accountability models to anarchist scenes. </p>
<p>One of the major flaws in our notion of anarchist community lies in its nature as implicit and assumed, rather than explicit and articulated. We don&#8217;t often directly state our commitments to and expectations of the other people with whom we share various kinds of “community,” except in specific projects or collectives; for instance, by living together, housemates agree to pay bills on time, wash the dishes, and respect each other&#8217;s space. What if we extended that degree of explicit intention to all of our relationships of affinity? Impossible: we&#8217;re supposed to sit down with every anarchist in North America—or even just in our town—and spell out explicit standards for how we relate and what we expect from each other?</p>
<p>No, of course not… and that&#8217;s exactly the point. We can&#8217;t do that, so we have to figure out how to collectively determine these things within the different webs of relationships in our lives. Rather than presuming a “community” and attempting to hold people accountable based on that fiction, we should define our expectations of and commitments to the others in our various circles of affinity, and use them as the basis for our responses to conflict and harm.</p>
<p>For example, let&#8217;s say that as my innermost concentric circle I have my affinity group. These are the folks I trust the most, with whom I take risks and for whom I&#8217;ll do whatever it takes. I&#8217;d be willing to give these people the benefit of the doubt in resolving conflict and addressing harm far more than any other people. Under this model, I would sit down with my affinity group and preemptively discuss how to address conflicts with each other when they come up, ranging from the most minor to the most serious disputes and forms of harm. Think of it as a sort of pre-nuptial agreement for friends and comrades, covering the bases in case things should go wrong. That way, I have a clear sense of how to respond when one of my crew does me wrong, and a shared basis of trust for working with them in a potentially long-term process of transformation. While I wouldn&#8217;t extend that trust to most people, within this group we share a deep and explicit affinity, so I&#8217;ll be open to criticism, calling out, and transformation with the trust that my comrades will be, too. Other examples of this innermost circle of affinity might be families (birth or chosen), houses and land projects, various types of collectives, or tight-knit groups of friends.</p>
<p>The next circle outwards might be a shared community space, such as an infoshop or social center. It&#8217;s a fairly consistent group of people, some of whom I&#8217;m closer with than others, but also an open space, so folks may come that I don&#8217;t know. Since it&#8217;s not a totally fixed group and not every single person can or would settle on direct agreements with one another, there can be collective agreements around respect, consent, anti-oppression, use of resources, and such. These don&#8217;t have to be authoritarian; they can be collectively determined, revised at any time by the consent of those most affected, and no one is compelled to abide by them; folks who can&#8217;t or won&#8217;t can choose not to participate in the space. As a result, I would be willing to go along with trying to hold someone accountable insofar as they wanted to continue to participate in the space. Since what defines our “community”—the terms of our affinity with each other—is our shared experience of participation in the space, then if one of us ceases to participate in it, we&#8217;re no longer in community with one another, thus shouldn&#8217;t expect to be held or hold others accountable through it. And accordingly, if someone violates or refuses to abide by the collective standards, there&#8217;s a procedure in place by which someone can held accountable for their actions; and if they refuse, others can exclude them from the space in good conscience. Other examples of this second circle of affinity could include specific events, larger organizing projects, and folks who hang out loosely in shared social spaces.</p>
<p>This framework of concentric circles of affinity helps us imagine where we can best apply the accountability practices with which we&#8217;ve been experimenting these past few years among anarchists. As the circles move outwards to mass mobilizations, “anarchists,” “punks,” and our broader radical “community,” it’s harder to imagine how we could concretely define community and navigate accountability within it. There&#8217;s no reason to expect anyone to be “accountable” to us based on whatever abstraction we claim to share with them. Without a concrete basis, our “community” has neither carrot nor stick; we can&#8217;t reward people for going along with our demands and we can&#8217;t coerce them into doing so. So if some random person who&#8217;s supposedly an anarchist sexually assaults someone, it might not be realistic to approach our response to the situation in terms of community accountability.</p>
<p>So then what do we do? Call the cops, beat them up, kick them out of all the institutions controlled by folks with whom we share affinity? And how do we deal with the recurrent problem of people who leave one scene only to resume abusive behavior in another? We don&#8217;t have any clear answers. But we have to start having discussions in every circle of affinity about our terms of engagement and how to address harm and resolve conflict, before we&#8217;re in crisis and forced to figure it out as we go. Until we&#8217;ve done that thoroughly in every collective, space, social group, and other anarchist formation, we can’t realistically aspire to formal community accountability as a strategy for dealing with our shit.</p>
<p>Forming affinity groups is a crucial part of anarchist organizing. It can be as simple as pulling together a crew of friends to do an action, or as formal and structured as you can imagine. Crucially, it preserves the basic principle of voluntary association at the heart of anarchy, the idea that we can do what we want with whomever we want without coercion or bureaucracy. This simple process has formed the core of our actions at demos and mobilizations, but perhaps we can use it to conceptualize our entire anarchist community and milieu. If we can create stronger ties with each other and understand our affinities more concretely, perhaps we’ll have the basis to make community accountability something more than a vague and contentious dream.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/justice/5b.jpg" rel="lightbox[justice]"><img src="https://cloudfront.crimethinc.com/images/justice/5a.jpg" width="500" height="528"/></a></p>
<p>We hope this essay will contribute to self-reflection among anarchists about where our affinities really are. Perhaps we can address many of the pitfalls of our experiments with accountability processes thus far by making our expectations of and commitments to one another as explicit as possible. We also can consider extending survivor-led vigilantism, pursuing anti-sexist men&#8217;s groups and gender-based organizing to undermine rape culture, or broadening our focus on conflict resolution and mediation. Whatever paths we choose, anarchists must continue trying whatever we can to break this impasse around abuse and assault in our scenes. Our liberation depends on it.</p>
<a name="appendix" id="appendix"></a>
<h2>Appendix</h2>
<h3>Works Cited</h3>
<p>“An Internal Action of the Vaginal Liberation Front”, in <a href="http://www.zinelibrary.info/files/Men%20In%20The%20Feminist%20Struggle.pdf"><em>Men in the Feminist Struggle</em></a></p>
<p><a href="http://news.infoshop.org/article.php?story=2010091917451655">“Don&#8217;t Believe the Hype”</a></p>
<p><a href="http://zinelibrary.info/dealing-our-shit-six-years-mens-group-and-accountability-work"><em>Fight Rape! Six Years of Men&#8217;s Group and Accountability Work</em></a> by Dealing With Our Shit</p>
<p><a href="http://news.infoshop.org/article.php?story=20100929155610284">“IMF Resistance Network Consent Guidelines: No Perpetrators Welcome”</a></p>
<p><a href="http://occupyca.wordpress.com/2010/08/22/i-communique%CC%81/">&#8220;i. communique&#8221;</a> by Radical Women&#8217;s Kitchen</p>
<p><a href="http://anarchalibrary.blogspot.com/2010/10/is-anarchist-man-our-comrade-2010.html">&#8220;Is the Anarchist Man Our Comrade?&#8221;</a></p>
<p><a href="http://libcom.org/forums/news/kafka-sales-will-be-through-roof-nyc-anarchist-book-fair-10042012">&#8220;Kafka sales will be through the roof at the NYC Anarchist Book Fair&#8221;</a></p>
<p><a href="http://news.infoshop.org/article.php?story=20100827153515576">“Notes on Survivor Autonomy and Violence”</a></p>
<p>&#8220;<a href="http://www.anarchistbookfair.net/saferspace">Safer Space Policy</a>,&#8221; by NYC Anarchist Book Fair Collective</p>
<p><a href="http://libcom.org/blog/safer-spaces-false-allegations-nyc-anarchist-bookfair-26042012">&#8220;Safer spaces, false allegations, and the NYC Anarchist Book Fair&#8221;</a></p>
<p>&#8220;Safety is an Illusion: Reflections on Accountability&#8221; by Angustia Celeste, in <a href="http://anarchalibrary.blogspot.com/2012/02/its-down-to-this-stories-critiques-and.html"><em>It&#8217;s Down To This: Reflections, Stories, Critiques, Experiences, and Ideas on Community and Collective Response to Sexual Violence, Abuse and Accountability</em></a></p>
<p><a href="http://torontoanarchistbookfair.wordpress.com/sexual-assault-and-consent-policy/">&#8220;Sexual Assault and Consent Policy&#8221;</a> by Toronto Anarchist Book Fair Collective</p>
<p><a href="http://www.phillyspissed.net/sites/default/files/survivor-support.pdf"><em>Supporting a Survivor of Sexual Assault</em></a> by Men Against Rape Culture.</p>
<p>“<a href="http://anarchalibrary.blogspot.com/2012/04/thinking-through-perpetrator.html">Thinking Through Perpetrator Accountability</a>,” in <em><a href="http://www.crimethinc.com/rt/">Rolling Thunder #8</a></em></p>
<p>“<a href="http://news.infoshop.org/article.php?story=2008all-survivors">We Are All Survivors, We Are All Perpetrators</a>,&quot; in <em><a href="http://www.crimethinc.com/rt/">Rolling Thunder #1</a></em></p>
<h3>Resource List</h3>
<p><strong>Groups and Organizations</strong></p>
<ul>
<li><a href="http://www.generationfive.org/">Generation Five</a> (Oakland, CA)</li>
<li><a href="http://www.phillystandsup.com/">Philly Stands Up</a> (Philadelphia, PA)</li>
<li><a href="http://creative-interventions.org">Creative Interventions</a> (San Francisco, CA)</li>
<li><a href="http://incite-national.org">INCITE! Women of Color Against Violence</a> (national)</li>
<li><a href="http://alp.org/community/sos">Audre Lorde Project – Safe OUTside the System</a> (Brooklyn, NY)</li>
<li><a href="http://www.criticalresistance.org">Critical Resistance</a> (national)</li>
<li><a href="http://www.supportny.org/">Support New York</a> (New York City)</li>
</ul>
<p><strong>Books</strong></p>
<ul>
<li><a href="http://www.incite-national.org/index.php?s=88"><em>The Color of Violence: The INCITE! Anthology</em></a>, by INCITE! Women of Color Against Violence</li>
<li><a href="http://www.incite-national.org/media/docs/0985_revolution-starts-at-home.pdf"><em>The Revolution Starts at Home: Confronting Partner Abuse in Activist Communities</em></a>, edited by Ching-In Chen, Jai Dulani, Leah Lakshmi Piepzna-Samarasinha and Andrea Smith</li>
<li><a href="http://www.prisonpolicy.org/scans/instead_of_prisons/index.shtml"><em>Instead of Prisons: A Handbook For Abolitionists</em></a>, by Prison Research Education Action</li>
<li><a href="http://www.livingjusticepress.org/index.asp?Type=B_BASIC&amp;SEC={B16C526F-6660-4D06-B514-72D2F2A4C167}"><em>Peacemaking Circles: From Crime to Community</em></a>, by Kay Pranis</li>
</ul>
<p><strong>Zines</strong></p>
<ul>
<li><a href="http://anarchalibrary.blogspot.com/2012/02/its-down-to-this-stories-critiques-and.html">It&#8217;s Down to This: Stories, Critiques and Ideas on Community and Collective Response to Sexual Violence and Accountability</a></li>
<li><a href="http://www.phillyspissed.net/node/27">What Do We Do When #2</a> and <a href="http://www.phillyspissed.net/node/26">#3</a></li>
<li><a href="http://www.phillyspissed.net/node/21">An Activist Approach to Domestic Violence</a></li>
<li><a href="http://www.phillyspissed.net/node/10">Thoughts About Community Support Around Intimate Violence</a></li>
<li><a href="http://www.dorisdorisdoris.com/zines3.html">See No, Speak No, Hear No</a></li>
<li><a href="http://cobp.resist.ca/sites/cobp.resist.ca/files/alternatives-to-police-web.pdf">Alternatives to Police</a> by Rose City Copwatch</li>
<li><a href="http://zinelibrary.info/files/learning%20good%20consent2.pdf">Learning Good Consent</a></li>
<li><a href="http://www.phillyspissed.net/node/18">Support</a></li>
<li><a href="http://zinelibrary.info/files/world+without+paper+2.pdf">World Without Sexual Assault</a></li>
<li><a href="http://www.phillyspissed.net/node/15">Let&#8217;s Talk About Consent, Baby</a></li>
<li><a href="http://anarchalibrary.blogspot.com/2010/09/our-own-response-early-2000s.html">Our Own Response</a></li>
<li><a href="http://www.phillystandsup.com">A Stand-Up Start Up: Confronting Sexual Assault with Transformative Justice</a></li>
<li><a href="http://www.blackandpink.org/wp-content/upLoads/Beautiful-Difficult-Powerful.pdf">Beautiful, Difficult, Powerful: Ending Sexual Assault Through Transformative Justice</a></li>
<li><a href="http://zinelibrary.info/files/conflict.pdf">Conflict Resolution Circles</a></li>
<li><a href="http://zinelibrary.info/if-they-were-human-different-take-perpetrator-accountability">As If They Were Human: A Different Take on Perpetrator Accountability</a></li>
<li><a href="http://zinelibrary.info/files/anti-authoritarian%20conflict%20mediation.pdf">Revolution in Conflict: Anti-Authoritarian Approaches to Resolving and Transforming Conflict and Harm</a></li>
<li><a href="http://zinelibrary.info/files/for_a_safer_world.pdf">For a Safer World</a></li>
</ul>
<p><strong>Other Resources</strong></p>
<ul>
<li><a href="http://www.creative-interventions.org/tools/toolkit/">Creative Interventions Toolkit</a></li>
<li><a href="http://generationfive.org/downloads/G5_Toward_Transformative_Justice.pdf">Toward Transformative Justice</a>, by Generation Five </li>
<li><a href="http://www.incite-national.org/index.php?s=93">Community Accountability Principles/Concerns/Strategies/Models</a></li>
<li><a href="http://www.incite-national.org/index.php?s=94">Community Accountability Within People of Color Progressive Movements</a></li>
<li><a href="http://www.onf-nfb.gc.ca/eng/collection/film/?id=50027">Hollow Water</a> (documentary film), by Bonnie Dickie</li>
<li><a href="https://communityaccountability.wordpress.com">Ideas, Actions, Art, &amp; Resources for Communities Responding to &amp; Transforming Violence</a></li>
<li><a href="http://www.crinfo.org">Conflict Resolution Information</a></li>
<li><a href="http://www.restorativejustice.org">Restorative Justice Information Clearinghouse</a></li>
<li><a href="http://www.realjustice.org">International Institute for Restorative Practices</a></li>
<li style="list-style: none;"><em>Policies for Mass Mobilizations around Sexual Assault and Consent:</em></li>
<li> - <a href="http://medic.wikia.com/wiki/Sexual_Assault_Disclosure">Sexual Assault Disclosure</a></li>
<li> - <a href="http://medic.wikia.com/wiki/Responding_to_Sexual_Assaults_as_Mass_Mobilizations">Responding to Sexual Assaults at Mass Mobilizations</a></li>
<li> - <a href="http://medic.wikia.com/wiki/Example_Consent_Policies">Example Consent Policies</a></li>
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1] Challenging banning and exclusion as primary accountability tactics raises more thorny questions about how to evaluate survivor demands, not just in terms of our <em>ability</em> to enact them but our <em>willingness</em> to do so. Is our role as proponents of anarchist accountability simply to adhere to the demands set forth by a survivor, even if we disagree with them strategically or ethically? Being an ally can be defined as doing what the survivor wants, no matter what; but we believe that no liberation can result from suspending our autonomy and uncritically following demands, no matter whose. Yet when is it our place as supporters to criticize what a survivor claims they need to heal or feel safe?</p>
<p>[2] At times, people honestly trying to be accountable have left anarchist scenes entirely in order to give space to a survivor. While better than not cooperating, this subverts the transformative justice ideal of keeping folks part of a community.</p>
<p>[3] One common challenge occurs when someone doesn&#8217;t clearly remember what happened in an encounter for which they&#8217;ve been called out, or remembers the experience differently from how the person calling them out remembers it. A survivor may assume that this is simply a ploy to avoid responsibility, which is possible; but often, people&#8217;s memories simply don&#8217;t line up. If accountability processes are not pseudo-judicial attempts to determine “the truth” of what “really happened” as confirmed by some authority, how can we reconcile these differences? Do the memories of all parties have to match in order for demands to be legitimate? Can someone take responsibility for doing things they don&#8217;t remember?</p>
<p>From our experience intervening with people who&#8217;ve been called out, acknowledging that someone may experience reality differently from them forms an important first step. For example, we can ask them to admit that something they experienced as consensual may not have been experienced that way by someone else. The sincere apology a survivor seeks may not be forthcoming if the person they&#8217;re calling out doesn&#8217;t remember an interaction in the same way. Still, accepting that the other(s) may have felt violated by something that they did can open someone towards examining and changing some of their behaviors, if not taking full responsibility.</p>
<p>[4] It&#8217;s difficult to acknowledge this without slipping into the kind of minimizing and denying language that&#8217;s so often used to silence survivors. We don&#8217;t want reactionaries to pick up on it and use it as another weapon in their arsenal of denial: “They&#8217;re just power-tripping on this &#8216;accountability&#8217; trend when that doesn&#8217;t even apply to this situation,” and so forth. Still, we need to be able to talk openly about this to learn how to respond more effectively to assault and abuse.</p>
<p>[5] As a self-described perpetrator explains in <a href="http://news.infoshop.org/comment.php?mode=view&amp;cid=1073791902">a comment on “Notes on Survivor Autonomy and Violence”</a>: “I&#8217;m not saying that survivors have to feel empathy for people who did them violence. But if we&#8217;re going to build communities that can actually outsurvive patriarchy, instead of being atomized and pummeled to dust by it, I think somebody will need to have empathy for perpetrators. Speaking from my personal experience, I know that I never would have had the courage to actually own up to my shit and deal if I hadn&#8217;t found a couple folks that actually cared about me and found a way to show me empathy… And I don&#8217;t think empathy means making excuses for someone. In fact, in this context, I think it means not letting someone make excuses, not letting them escape their responsibility and their history, and making sure they own up to the consequences that come from the actions they&#8217;ve taken. It also means listening to them, sincerely, even while doing this, and seeking understanding. And I believe it means making sure that perpetrators do feel consequences for their actions, but not punishments. It also means finding resources so that the perpetrator can first learn and then practice a different pattern of habits and actions… I think what is required for accountability processes is empathy. Empathy and anger, at the same time.”</p>
<p>[6] It&#8217;s worth asking whether or not “neutrality” is possible or desirable in conflict mediation. In many conflicts, one party wields greater power than the other, and if effort isn&#8217;t made to intervene in that power dynamic, neutrality can often amount to collusion with power. An alternative model of a mediator&#8217;s orientation towards parties in a conflict is “bipartiality” rather than neutrality. According to this framework, a mediator advocates for both parties, but also challenges them when they leverage their access to power within the conflict, asking them to consider the ways that their power blind them to the experiences of those lacking that power. </p>
</div>