<h1>Antinationalist Nationalism</h1>
<h5>The Anti-German Critique <br />
and Its All-Too-German Adherents</h5>
<p><dl>&ldquo;The idea that an understanding of genocide, that a memory of holocausts can only lead people to want to dismantle the system is erroneous. The continuing appeal of nationalism suggests that the opposite is true: that an understanding of genocide has led people to mobilize genocidal armies, that the memory of holocausts has led people to perpetuate holocausts. The sensitive poets who remembered the loss, the researchers who documented it, have been like the pure scientists who discovered the structure of the atom. Applied scientists used the discovery to split the atom&rsquo;s nucleus, to produce weapons which can split every atom&rsquo;s nucleus; nationalists use the poetry to split and fuse human populations, to mobilize genocidal armies, to perpetrate new holocausts.&rdquo;<br /><br />
<strong>-Fredy Perlman,</strong> <em>The Continuing Appeal of Nationalism</em></dl></p>
<p>&nbsp; </p>
<p>Back in the 1990s, answering mail for the &rsquo;zine I used to publish, I noticed that Germans&mdash;even German anarchists&mdash;responded strangely whenever the conflict between Israel and Palestine came up. Every time anything related to the issue appeared in my &rsquo;zine, I got a lengthy letter from an irate German accusing me of Palestinian nationalism or even borderline anti-Semitism. I never once received such a letter from citizens of any other nation, even though the &rsquo;zine was distributed as far as Israel, nor did I ever receive one from a Jewish reader of any nationality. From my perspective, the positions in the &rsquo;zine on that issue were not particularly controversial: like most others in the anarchist community, I deplored the violence and racism of the Israeli military and the Zionist settler movement, while remaining suspicious of those seeking to capitalize on what I considered understandable Palestinian desperation. At the time, I interpreted these letters as nothing more than an overzealous effort on the part of some Germans to be sensitive about issues affecting Jewish people.</p>
<p> I returned to Europe last fall for the first time in some years. In the course of my travels, I discovered that what had seemed like a minor blind spot in the German radical milieu had evolved into what I regard as a really problematic strain of thought: the &ldquo;Anti-German Critique,&rdquo; a reactionary nationalism that masquerades as radical anti-nationalism. For adherents of this ideology, the important thing is not to oppose capitalism, racism, and hierarchy everywhere, but to oppose Germany and anti-Semitism specifically, even to the extent of supporting other capitalist nations and other forms of racism.<a class="footnote" href="javascript:void(0);" onclick="return overlib('The word racism is used in this text to call attention to the double standards so many white people bring to their considerations of the Palestine/Israel conflict. One must be a racist to compare the living conditions of average Palestinian and Israeli families today and not see injustice, however things stand in the gang war. It&rsquo;s also impossible to describe the policies of the Israeli government, which disenfranchise, dominate, and humiliate Palestinians the same way apartheid did native Africans in South Africa, as anything less than racist. Some Palestinians might also be described as having racist ideas, but they are hardly in a position to subject Israelis en masse to such dehumanizing treatment.', CAPTION, '[1]');" onmouseout="nd();">[1]</a> Revolutions being unforthcoming, Anti-German antifascists settle for supporting the current government of Israel, all the injustices it perpetrates notwithstanding, on account of the injustices perpetrated by its opponents.</p>
<p> At first, I only came across hints of this. Climbing the immense stairwell of the EKH, Vienna&rsquo;s longstanding squatted social center, I came upon a little exhortation scrawled on the wall: &ldquo;Support Zionism.&rdquo; That&rsquo;s strange, I thought to myself: here, in an anarchist stronghold, graffiti urging people to rally to a cause already receiving more support from the United States than any other government in the world, and responsible for the displacement and repression of an entire population of people of color. In the ageless tradition of marker-bearing squatters, I added a little message of my own: &ldquo;down with all isms&mdash;support people, not nations.&rdquo;</p>
<p> The following week found me staying at a social center in Dresden. Among the other occupants of the space were two Israelis, who&mdash;like many young Israelis I had met upon earlier visits to Europe<a class="footnote" href="javascript:void(0);" onclick="return overlib('Among others, I had spent time with members of the band Dir Yassin, an anarchist and anti-Zionist band from Israel. They were interviewed in the anarcho-punk magazine <em>Profane Existence</em> in 1998, and with luck you can still find the interview.', CAPTION, '[2]');" onmouseout="nd();">[2]</a>&mdash;were traveling the continent in order to avoid the draft that compels Israelis to serve in the military. I fell to talking politics with one of them. He declined to take a position on the Israel-Palestine conflict&mdash;an admirable enough stance for a person coming from such a complicated situation, who had accepted exile rather than risk killing or dying for a cause in which he did not believe.</p>
<p> Others in Germany had not respected his decision, however. He recounted to me his experience traveling for a few days with a German band; when it came out that he was avoiding military service, another person on the tour&mdash;a German gentile, otherwise committed to revolutionary politics&mdash;was outraged: &ldquo;You mean you wouldn&rsquo;t serve to protect your people? You coward!&rdquo;</p>
<p> Scarcely two days later, during an antifascist action in Leipzig, I had my first brush with Anti-Germans. I&rsquo;ll spare you the details of my participation in the event&mdash;suffice it to say my friends and I spent hours wandering around peering at photocopied maps, followed by a few exhilarating minutes being pursued by riot police through cordoned-off streets and over spiked fences, and in the end the scheduled fascist march was thwarted. After traveling throughout southern and eastern Europe, where fascism is gaining more and more power, it was a real relief to see it being held at bay somewhere. It was not so encouraging, however, to see US, Israeli, and British flags being unloaded at the departure point of an antifascist march.</p>
<p> I went immediately over to the young men unloading them. My German friend had urged me not to waste my time, but whether or not they would listen to me I was curious what they had to say for themselves.</p>
<p> &ldquo;What are you doing with that flag?&rdquo; I gestured at the stars and stripes one young fellow was pulling from the truck.</p>
<p> &ldquo;We are going to march with it.&rdquo;</p>
<p> &ldquo;I&rsquo;m from the United States,&rdquo; I began, &ldquo;and I can&rsquo;t fucking believe you would march with a US flag at this rally. Don&rsquo;t you know what this flag means?&rdquo;</p>
<p> &ldquo;But it is different here! Here, this flag is a symbol of the antifascist struggle.&rdquo;</p>
<p> &ldquo;Listen, everywhere in the world that flag represents the same things: Hollywood, Coca-Cola, the absolute power of the capitalist market. What does that have to do with freedom?&rdquo;</p>
<p> His answer was almost plaintive. &ldquo;But Britain and the United States beat the German government! They were the only ones who could do it. We carry their flags to remember this.&rdquo;</p>
<p> &ldquo;They fought that war with their armies segregated into black and white divisions, and Japanese citizens in internment camps! They weren&rsquo;t fighting for freedom, but for their own national power&mdash;just like in the genocidal wars against the Native Americans! That flag is stained with the blood of millions!&rdquo;</p>
<p> &ldquo;But they were the only ones who could stop the Nazis here,&rdquo; he repeated, almost sheepishly. I hadn&rsquo;t caught myself a particularly fierce Anti-German.</p>
<p> &ldquo;That war only happened because people were willing to march under flags in the first place, and we could have won it without flags if people like you didn&rsquo;t insist on them. If you&rsquo;re going to march with that flag, count me out, and every antifascist like me in the US would do the same.&rdquo; I left to find my own route to block the fascists&mdash;hence the crazy chase scene involving the spiked fence.</p>
<p> That night, sporting a limp that lasted for weeks, I stayed at a squat in Erfurt. Here, someone had gone around to every poster that had read &ldquo;Antifascist&rdquo; and blacked out &ldquo;fascist&rdquo; to replace it with &ldquo;Deutsch.&rdquo; What kind of people thought it was more important to take at stand against Deutschland than against fascism?</p>
<p> It wasn&rsquo;t until Hamburg, my last stop in Germany, that I got to have the discussion I&rsquo;d wanted with a real live Anti-German. It was someone I knew: back in the &rsquo;90s, he had booked my old punk rock band at a social center in Germany. He was thinner now, with a more haughty, intellectual air about him and a pencil-thin moustache.</p>
<p> &ldquo;Yes,&rdquo; he was saying, &ldquo;but your new band is&hellip; not so good, yes?&rdquo; He nodded to me, eyebrows raised.</p>
<p> &ldquo;We&rsquo;re a new band,&rdquo; I replied, gamely. &ldquo;We&rsquo;ve just learned new instruments. Over time, I hope we&rsquo;ll improve. But yes, right now, perhaps we are not so good.&rdquo;</p>
<p> &ldquo;Your last band&rdquo;&mdash;he paused for dramatic effect&mdash;&ldquo;did not improve with time, I think. I saw you at the beginning of your last tour, and then at the end. Do you remember?&rdquo;<br />
&ldquo;Yes, of course. I agree.&rdquo; Humility is the better part of celebrity, if you want to last an hour in punk circles.</p>
<p> &ldquo;You know,&rdquo; he said, leaning his head back and looking into the middle distance, &ldquo;I think when I first started to lose interest, it was when the record came out with the song about Intifada.<a class="footnote" href="javascript:void(0);" onclick="return overlib('The offending song, named &ldquo;Called Terrorists by Terrorists,&rdquo; was explained thus in the liner notes:<br /><br />&ldquo;The title of this song refers to the well-known murder of United Nations mediator Count Folke Bernadotte, who was killed on orders from future Israeli politician Yitzhak Shamir. Bernadotte was appointed in 1948 to negotiate between the Palestinian natives and the Zionists who were attempting to establish an Israeli state in their homeland; he was the former head of the Swedish Red Cross, and had risked his life to save thousands of Jews from concentration camps during the second world war. After months of studying the situation, Bernadotte concluded that in the interests of human decency if the Zionists were to eventually be given sovereignty over a part of Palestine, Palestinian refugees who had been driven out by Zionist violence should be given two options: they should be allowed to return to their stolen lands, or else receive compensation from the new nation of Israel for what had been taken from them. The day after he made his proposal, he was killed by Zionist terrorists carrying out Shamir&rsquo;s instructions. Years later, supported by a media blackout on the past and the fact that history is always written by the victors, Shamir was able to join other world leaders in referring to the Palestinians who still resisted the racist repression of his regime as &lsquo;terrorists&lsquo; without anyone bringing up his own blood-soaked past.&rdquo;', CAPTION, '[3]');" onmouseout="nd();">[3]</a>&rdquo;</p>
<p> &ldquo;Aha!&rdquo; I exclaimed, practically pounding my fist upon the ubiquitous foosball table&mdash;the game is known as &ldquo;kicker&rdquo; in Germany, and heaven help any foreigner who takes on even the drunkest of native players. &ldquo;An Anti-German! I&rsquo;ve been waiting for this! Let&rsquo;s get down to business.&rdquo;</p>
<p> &ldquo;Yes, I think there is a lot where we do not agree! But maybe there is no reason even to talk about it.&rdquo; He darted me a sidelong glance. &ldquo;For example, you said you live in the woods&mdash;you are against technology and civilization, yes? But for us, you know, we think that technology is just something that works. It spreads, because it works.&rdquo;<br />
He had my complete attention now. &ldquo;And other peoples who are less, shall we say, advanced&hellip;?&rdquo;</p>
<p> &ldquo;Ah, I see what you suggest. Yes, some might say that this is a Western-centered view. But people around the world are taking up this lifestyle as fast as they can.&rdquo;</p>
<p> &ldquo;But you really can&rsquo;t argue that everything that spreads is a good thing. You know, a plague also spreads. A plague spreads because it works! And anyway, I am not against all technology&mdash;just technologies that promote hierarchy or water down our experience of life. Besides, if everyone lived the way people in Germany and the US live, the planet would be wrecked in one generation.&rdquo;</p>
<p> &ldquo;A plague spreads because it works,&rdquo; he repeated, nodding in slit-eyed appreciation of my clever rejoinder.</p>
<p> I learned later, in my research into Anti-German thought, that indeed, some Anti-German writers conceive of world history in terms of the progress of civilization (i.e., Western civilization), with the implication that other cultures are primitive. This is an old-fashioned Marxist analysis, in which capitalist technocracy is a stage of human evolution that must be passed through on the way to communist utopia; this was the excuse the Bolsheviks and Maoists gave for forcing millions to give up their traditional lifestyles in order to join the machinery of industrial communism. &ldquo;There is something worse than capitalism and bourgeois society: its barbarous abolition,&rdquo; writes one Anti-German, and he goes on to make it explicit that he is referring to Arabic nationalism as well as German fascism. Thinking this way makes it easy enough to pose Israel and the United States as the flagships of culture and progress, and those dirty Arabs as the savages to whom the torch of Nazi irrationality and brutality has been passed.</p>
<p> But let&rsquo;s return to the conversation in Hamburg. &ldquo;But what are the US flags for in the demonstrations?&rdquo; I demanded.</p>
<p> &ldquo;Ah, they are a joke, to wind people up,&rdquo; he explained. &ldquo;There are certain people it is important to piss off with these flags. You know, in Germany, the right wing exploits the whole anti-American thing for its own purposes.&rdquo;</p>
<p> &ldquo;But isn&rsquo;t it totally reactionary to carry them just because they bother your enemies? Does that mean you have to embrace the flag of such a destructive, oppressive nation?&rdquo;</p>
<p> As I discovered later in my studies, if he had been a true hard-line Anti-German he would have explained to me that, because the US provides Israel with the money and guns to hold the entire Middle East at bay and do to the Palestinians as they please, it is not a destructive nation at all, but the foremost protector of peace. Instead, he opted for a more conciliatory approach: &ldquo;This is a German thing, special to our German context. Here, where the holocaust took place, our most important job is to fight German power, and for this the flags are good.&rdquo;</p>
<p> I reflected a minute. &ldquo;Isn&rsquo;t it very German to claim that in the German context, you have a special privileged perspective that justifies actions that don&rsquo;t make sense anywhere else?&rdquo;</p>
<p> As their name implies, Anti-Germans put quite a bit of energy into establishing the special status of the German nation-state as an evil more terrible than any other. Accordingly, my companion launched into an explanation of why the Holocaust happened in Germany, why it could only happen in Germany, and why it was worse than any other atrocity in history. To hear him tell it, the status of the German state as perpetrator of the most terrible of all crimes grants certain special rights and powers of observation to its citizens: knowing anti-Semitism better than anyone else, they can see  more clearly than others how it is still the most serious danger facing the world.</p>
<p> I wasn&rsquo;t able to follow his argument this far, though, as I was still getting over my shock at his dismissal of others&rsquo; racist oppression and slaughter. &ldquo;Wait, what about the extermination of the Native Americans?&rdquo;</p>
<p> &ldquo;That was different: that was simply a conflict over land and resources, and it was concluded when the last of the Indians surrendered. The Jews were law-abiding German citizens, and were singled out for purely racist, ideological reasons. You&rsquo;ll probably say that there were people in the death camps besides the Jews; but the Jews were the real targets of the Shoah<a class="footnote" href="javascript:void(0);" onclick="return overlib('&ldquo;Shoah&rdquo; is a Hebrew word for the Holocaust.', CAPTION, '[4]');" onmouseout="nd();">[4]</a>.&rdquo;</p>
<p> &ldquo;Of course, Jewish people now have the means to talk about their experiences in the death camps, whereas the Romani people, who are still oppressed and dispossessed everywhere, are unable to get a hearing.&rdquo;</p>
<p> &ldquo;Don&rsquo;t you think that sort of rhetoric is a little anti-Semitic, like saying there is a worldwide Jewish conspiracy?&rdquo;</p>
<p> &ldquo;It&rsquo;s very convenient for a gentile like you to call everyone who disagrees anti-Semitic! You&rsquo;ll recall that the last time I was here with a band that talked about Israel and Palestine, half of us were Jewish. Anyway, what about my earlier question? Isn&rsquo;t it nationalist to consider Deutsch culture a context unto itself apart from the international context? What ever happened to &lsquo;no borders, no nations&rsquo;?&rdquo;</p>
<p> He answered me with a phrase that summarized everything for me: &ldquo;But that does not take into account our special situation. Here we say, &lsquo;destroy all nations, but Israel last.&rsquo;&rdquo;</p>
<p> In this formulation, we arrive at the central fallacy of the pro-Zionist position: the idea that nations protect their citizens. This is a fundamental misunderstanding of the way state power works. Each government argues to its citizens that it exists to protect them from other governments; but when nations fight, it is not governors that die, but their citizens. Thousands upon thousands upon thousands of Israelis have died since the formation of Israel in 1948. Former terrorists such as Shamir and Sharon have risen to power upon waves of fear, assuring their constituents that if anyone is to suffer, it will be Arabs&mdash;but their policies have continued to result in the loss of Israeli lives, while they die of old age.<a class="footnote" href="javascript:void(0);" onclick="return overlib('With the exception, of course, of Israeli prime minister Yitzhak Rabin, who was assassinated by a Zionist Jew for fear he might make progress towards a peaceful and just solution to the conflict. One would think this, if anything, would have turned the Israeli public against militant Zionism&mdash;but no, he was succeeded in power by a right wing hardliner.', CAPTION, '[5]');" onmouseout="nd();">[5]</a></p>
<p>Compared to the aforementioned Romani people, who are still persecuted across the whole of Europe, one might even say the Israelis have it worse: thanks to billions and billions of dollars from the United States, they are able to maintain an artificially high standard of living, but at any moment a suicide bomber may kill them or their loved ones. One must wonder if, given the opportunity, most Romani people would opt for power and luxury beneath the sword of Damocles over their current circumstances. Had they somehow been chosen by destiny to force a people out of their homeland and carry on a US-financed war against their neighbors for the past half-century, the results would surely be similar.</p>
<p> Neither fate, of course, is desirable. If Jews today were in the same situation as the Romani, that would also be a terrible tragedy. But let us not imagine that those are the only two possibilities for survivors of the Holocaust. Such a lack of imagination, that reduces all questions to a matter of picking the lesser of two evils, is at the heart of all the impasses that face us across the world today. It is the same lack of imagination that led people to mobilize around Kerry against Bush, rather than opposing the US government itself; it is the same lack of imagination that induces the Anti-Germans to side with the state of Israel against its enemies, rather than with us against nationalism and enmity themselves.</p>
<p> To be sure, the Jews who have been murdered worldwide over the past six decades have been killed by anti-Semites. Anti-Semitism has flourished among Arabs; much is made of this by the Anti-Germans, who trace Arabic nationalism back to early connections between certain Arabs and German Nazis. But these few connections would have been meaningless if Arabic anti-Semites had not had been able to make use of Israeli atrocities in the years that followed to recruit converts. The violence in the Middle East today is not the direct successor to the Nazi Holocaust; rather, it is the result of the violence committed by survivors of that Holocaust, who became abusers in their turn&mdash;as survivors all too often do.</p>
<p> Until now, we have barely touched upon the number of Palestinians and other Arabs who have suffered at the hands of the Israeli state. If one is making an argument for nations as protectors of human beings, one must take all human beings into account, not only the citizens of certain nations&mdash;unless one believes the others to be subhuman. Here we can see that the cost of the establishment and perpetuation of the state of Israel has been colossal in terms of the suffering and death of both Israelis and Palestinians.</p>
<p> As anarchists, we can find the explanation for this not in the innate bloodthirstiness and anti-Semitism of Arabs (nor the imperialistic machinations of Jews, for that matter), but in the way nationalists and nation-states pit human beings against one another. For us, the answer is clear: we must struggle against the governments of Israel and Palestine, as well as those of the US, Germany, and all other nations. So long as one intolerant, violent, self-interested government is able to carry on unchallenged, it will be all too easy for rival governments to muster frightened adherents to commit murderous acts as well. So-called pragmatists who insist that we must support one or another of these gangs would have us perpetuate the whole mess into eternity. We can find our solidarity with all Palestinians and Israelis who struggle against their own rulers on the basis of a recognition of each other&rsquo;s humanity.<a class="footnote" href="javascript:void(0);" onclick="return overlib('In that spirit, I&rsquo;d like to conclude this text with a poem by leading Israeli author Aharon Shabtai:<em> I, too, have declared war: / You&rsquo;ll need to divert part of the force / deployed to wipe out the Arabs&mdash; / to drive them out of their homes / and expropriate their land&mdash; / and set it against me. / You&rsquo;ve got tanks and places, / and soldiers by the battalion; / you&rsquo;ve got the rams&rsquo; horns in your hands / with which to rouse the masses; / you&rsquo;ve got men to interrogate and torture; / you&rsquo;ve got cells for detention. / I have only this heart / with which I give shelter / to an Arab child. / Aim your weapons at it: / even if you blow it apart / it will always, / always mock you.</em>', CAPTION, '[6]');" onmouseout="nd();">[6]</a>
</p>
<p> Before we conclude, let&rsquo;s revisit the origins and mentality of the Anti-German ideology, as it exemplifies many of the potential pitfalls for radicals in today&rsquo;s global context. Long before the Nazis came to power in Germany, opposition to capitalism and the rich was often directed against caricatures of &ldquo;the International Jew.&rdquo; Many German nationalists considered the proletariat to be composed of non-Jewish Germans, who were supposedly preyed upon by Jewish money lenders; the implication was that by getting rid of the Jews, the capitalist system could be symbolically cleansed of its parasites. Anti-Semitism was taken for granted in many revolutionary circles: Bakunin, one of the most famous early anarchist thinkers, made anti-Semitic remarks, and Mussolini himself started out with an interest in anarchism. Revolutionary working class activism was co-opted by national socialism such as that of Mussolini&rsquo;s blackshirts no less than by nationalist socialism such as that of the Bolsheviks. This checkered heritage makes it easy for the Anti-Germans to read anti-Semitism in the radicalism of their contemporaries, whether it&rsquo;s there or not.</p>
<p> Today, fascists in Germany and other nations have similarly muddied issues by adopting environmentalist and anti-globalization stances. It would be nice to stop at the conclusion that the Anti-Germans have simply been provoked by their enemies into thoughtlessly adopting contradictory positions, but the fact that they have crossed into nationalism and borderline racism suggests something more insidious: that in setting out to resist fascism, they have been infected by it, perhaps as a result of the same German predispositions they aim to oppose. In studying their example, we can recognize the importance of developing a nuanced critique of power relations, but we are also reminded of Nietzsche&rsquo;s dictum that those who do battle with monsters must take care lest they become monsters themselves.</p>
<p> Every holocaust justifies itself on the pretext of protecting innocents. In the US, during the extermination of Native Americans (and, later, during the segregation era), white women were said to be threatened by colored savages; in Nazi Germany, citizens of pure &ldquo;Aryan blood&rdquo; were fetishized as victims of a worldwide conspiracy of degenerates. In coming to see the Jewish people as a category&mdash;&ldquo;the&rdquo; endangered, &ldquo;the&rdquo; victims of oppression&mdash;rather than committing to a struggle against injustice everywhere and in all forms, the Anti-Germans set the stage for themselves to end as abettors of racist, nationalist war. It is easy to see how German radicals, eager to distance themselves from their nation&rsquo;s anti-Semitic history and desperate to oppose a resurgent fascist movement, might prioritize Jewish concerns over others. But this is sometimes how new atrocities occur: the survivors of persecution become persecutors, and others, anxious to atone for condoning their former persecution, turn a blind eye.</p>
<p> Anti-German partisanship for Israel, once set in motion, did not lack justification and encouragement: there is an entire propaganda industry given over to rationalizing Israeli policy, just as there is another given to taking advantage of it to mobilize Arabic resistance groups. Zionist Israelis are indeed victims in the Israel-Palestine conflict, as are Palestinian suicide bombers; the problem is that both fight not to end the conflict but to win it. The Anti-German phenomenon should remind anarchists not to hurry to pick sides in national and ethnic strife; we must, rather, side with whatever parts of those struggling resonate with our desires to supercede the terms of such conflicts, however buried those parts may be. We can intercede in the manner demonstrated by Rachel Corrie, the US activist killed by a bulldozer of the Israeli Defense Force while fighting to protect Palestinian homes: not so that one side may triumph, but to help human beings survive an inhuman conflict.</p>
<p> All this is complicated, for sure. In a world in which seemingly everybody is lined up on one side or another of such conflicts, it seems those who would take sides with everyone against conflict itself find themselves apart from everyone else, even at odds with them. But again, let us learn from the Anti-Germans: those who resign themselves to the failure of revolutionary prospects turn, defensively, into the very monsters they so recently opposed.</p>
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1] The word racism is used in this text to call attention to the double standards so many white people bring to their considerations of the Palestine/Israel conflict. One must be a racist to compare the living conditions of average Palestinian and Israeli families today and not see injustice, however things stand in the gang war. It&rsquo;s also impossible to describe the policies of the Israeli government, which disenfranchise, dominate, and humiliate Palestinians the same way apartheid did native Africans in South Africa, as anything less than racist. Some Palestinians might also be described as having racist ideas, but they are hardly in a position to subject Israelis en masse to such dehumanizing treatment.
</p>
<p>[2] Among others, I had spent time with members of the band Dir Yassin, an anarchist and anti-Zionist band from Israel. They were interviewed in the anarcho-punk magazine <em>Profane Existence</em> in 1998, and with luck you can still find the interview.</p>
<p>[3] The offending song, named &ldquo;Called Terrorists by Terrorists,&rdquo; was explained thus in the liner notes: &ldquo;The title of this song refers to the well-known murder of United Nations mediator Count Folke Bernadotte, who was killed on orders from future Israeli politician Yitzhak Shamir. Bernadotte was appointed in 1948 to negotiate between the Palestinian natives and the Zionists who were attempting to establish an Israeli state in their homeland; he was the former head of the Swedish Red Cross, and had risked his life to save thousands of Jews from concentration camps during the second world war. After months of studying the situation, Bernadotte concluded that in the interests of human decency if the Zionists were to eventually be given sovereignty over a part of Palestine, Palestinian refugees who had been driven out by Zionist violence should be given two options: they should be allowed to return to their stolen lands, or else receive compensation from the new nation of Israel for what had been taken from them. The day after he made his proposal, he was killed by Zionist terrorists carrying out Shamir’s instructions. Years later, supported by a media blackout on the past and the fact that history is always written by the victors, Shamir was able to join other world leaders in referring to the Palestinians who still resisted the racist repression of his regime as &lsquo;terrorists&lsquo; without anyone bringing up his own blood-soaked past.&rdquo;
</p>
<p>[4] &ldquo;Shoah&rdquo; is a Hebrew word for the Holocaust.</p>
<p>[5] With the exception, of course, of Israeli prime minister Yitzhak Rabin, who was assassinated by a Zionist Jew for fear he might make progress towards a peaceful and just solution to the conflict. One would think this, if anything, would have turned the Israeli public against militant Zionism&mdash;but no, he was succeeded in power by a right wing hardliner.</p>
<p>[6] In that spirit, I&rsquo;d like to conclude this text with a poem by leading Israeli author Aharon Shabtai:<br /><br /><em>
I, too, have declared war:<br />
You&rsquo;ll need to divert part of the force<br />
deployed to wipe out the Arabs&mdash;<br />
to drive them out of their homes<br />
and expropriate their land&mdash;<br />
and set it against me.<br />
You&rsquo;ve got tanks and places,<br />
and soldiers by the battalion;<br />
you&rsquo;ve got the rams&rsquo; horns in your hands<br />
with which to rouse the masses;<br />
you&rsquo;ve got men to interrogate and torture;<br />
you&rsquo;ve got cells for detention.<br />
I have only this heart<br />
with which I give shelter<br />
to an Arab child.<br />
Aim your weapons at it:<br />
even if you blow it apart<br />
it will always,<br />
always mock you.</em></p>
</div>