<p align="center"><a href="http://cloudfront.crimethinc.com/images/atc/atc-dust-1b.jpg" rel="lightbox[justice]"><img src="http://cloudfront.crimethinc.com/images/atc/atc-dust-1a.jpg" width="500" height="534" title="After the Crest, part I: What to Do while the Dust Is Settling" alt="After the Crest, part I: What to Do while the Dust Is Settling"/></a></p>
<p style="color: #ab0000; margin: 20px">At the high point, it seems like it will go on forever. You feel invincible, unstoppable. Then the crash comes: court cases, disintegration, depression.</p>
<p style="color: #ab0000; margin: 20px">Once you go through this several times, the rhythm becomes familiar. It becomes possible to recognize these upheavals as the heartbeat of something greater than any single movement.</p></span>
<p>Over the past six years, cities around the world have seen peaks of struggle: <a href="http://www.crimethinc.com/blog/2008/12/25/how-to-organize-an-insurrection/">Athens</a>, <a href="http://www.crimethinc.com/blog/2011/01/26/the-uk-student-movement/">London</a>, <a href="http://www.crimethinc.com/texts/recentfeatures/rosefire.php">Barcelona</a>, <a href="http://www.crimethinc.com/blog/2011/02/02/egypt-today-tomorrow-the-world/">Cairo</a>, <a href="http://www.bayofrage.com/featured-articles/occupy-oakland-is-dead/">Oakland</a>, <a href="http://www.crimethinc.com/texts/recentfeatures/montreal1.php">Montréal</a>, <a href="http://www.salon.com/2013/06/14/%E2%80%9Ci%E2%80%99ve_gone_to_resist_i%E2%80%99ll_be_right_back%E2%80%9D/">Istanbul</a>. A decade ago, anarchists would converge from around the world to participate in a single <a href="http://www.crimethinc.com/texts/pastfeatures/demonstrating.php">summit protest.</a> Now many have participated in months-long upheavals in their own cities, and more surely loom ahead.</p>
<p>But what do we do after the crest? If a single upheaval won’t bring down capitalism, we have to ask what matters about these high points—what we hope to get out of them, how they figure in our long-term vision, and how to make the most of the waning period that follows them. This is especially pressing today, when we can be sure that there are more upheavals on the way.</p>
<p>To this end, we have organized a dialogue with anarchists in some of the cities that have seen these climaxes of conflict, including Oakland, Barcelona, and Montréal. This is the first in a series of reflections drawn from those discussions.</p>
<p>Practically all of the participants in these discussions independently reported that it was really hard for them to formulate their thoughts: “I don’t know why, but whenever I sit down to work on it, I get depressed.” This suggests a broader problem. Many anarchists depend on a triumphalist narrative, in which we have to go from victory to victory to have anything to talk about. But movements, too, have natural life cycles. They inevitably peak and die down. If our strategies are premised on endless growth, we are setting ourselves up for inevitable failure. That goes double for the narratives that determine our morale.</p>
<p style="color: #ab0000; margin: 20px"><a href="http://www.crimethinc.com/books/contra/defs/movement.html"><em>Movement</em></a> – A mysterious social phenomenon that aspires to growth yet, when observed, always appears to be in decline.</p>
<p style="color: #ab0000; margin: 20px">When social change is gathering momentum, it is protean and thus invisible; only when it stabilizes as a fixed quantity is it possible to affix a label to it, and from that moment on it can only decompose. This explains why movements burst like comets into the public consciousness at the high point of their innovation, followed by a long tail of diminishing returns. A sharper eye can see the social ferment behind these explosions, perennial and boundless, alternately drawing in new participants and emitting new waves of activity, as if in successive breaths.</p>
<p>In Occupy Oakland, a three-week occupation gave way to a six-month decline. This bears repeating: <em>movements spend most of their time in decline.</em> That makes it all the more important to consider how to make the most of the waning phase.</p>
<p>As all movements inevitably reach limits, it is pointless to bewail their passing—as if they would go on growing indefinitely if only the participants were <em>strategic enough.</em> If we presume the goal of any tactic is always to maintain the momentum of a particular movement, we will never be able to do more than react quixotically against the inexorable passing of time. Rather than struggling to stave off dissolution, we should act with an eye to the future.</p>
<p>This could mean consolidating the connections that have developed during the movement, or being sure to go out with a <a href="https://robertgraham.wordpress.com/2012/09/09/bakunin-the-paris-commune-1871/">bang</a> to inspire future movements, or revealing the internal contradictions that the movement never solved. Perhaps, once a movement has reached its limits, the most important thing to do in the waning phase is to point to what a future movement would have to do to transcend those limits. </p>
<p style="color: #ab0000; margin: 20px">We had <a href="http://www.crimethinc.com/texts/recentfeatures/breaking.php">occupied the building</a> for almost 24 hours, and we were starting to imagine that we could somehow hold onto it. I was about to go out for supplies to fortify the place when something caught my eye. There in the dust of the abandoned garage was a hood ornament from a car that hadn’t been manufactured in 40 years. I reached down to pick it up, then hesitated: I could always look at it later. On impulse, I took it anyway. A half hour later, a SWAT squad surrounded the building for blocks in every direction. We never recovered any of the things we built or brought there. Over a hundred of us met, danced, and slept in that building, outside the bounds of anything we’d previously been able to imagine in our little town, and that little hood ornament is all I have to show it happened.</p>
<p style="color: #ab0000; margin: 20px">When I visited my friends in the Bay Area the following week, they were in the same state of elation I had been when I left the building: “We walk around and people see us and call out OCC-U-PY! Things are just going to grow and keep on growing!”</p>
<h3>Keep perspective.</h3>
<p>During a crescendo of social struggle, it can be difficult to maintain perspective; some things seem central yet prove transitory, while other things fall by the wayside that afterwards turn out to have been pivotal. Often, we miss opportunities to foster long-term connections, taking each other for granted in the urgency of responding to immediate events. Afterwards, when the moment has passed, we don’t know how to find each other—or we have no reason to, having burned our bridges in high-stress situations. What is really important, the tactical success of a particular action, or the strength of the relationships that come out of it?</p>
<p>Likewise, it is rarely easy to tell where you are in the trajectory of events. At the beginning, when the window of possibility is wide open, it is unclear how far things can go; often, anarchists wait to get involved until others have already determined the character of the movement. Later, at the high point, it can seem that the participants are at the threshold of tremendous new potential—when in fact that window of possibility has already begun to close. This confusion makes it difficult to know when it is the right time to shift gears to a new strategy.</p>
<p style="color: #ab0000; margin: 20px">We were outside at a café in downtown Oakland a couple months later. I was asking what my friends thought the prospects were for the future. “Things will pick up again when spring arrives,” they assured me.</p>
<p style="color: #ab0000; margin: 20px">At first I believed them. Wasn’t everyone saying the same thing all around the country? Then it hit me: we were sitting there in the sunshine, wearing t-shirts, in the city that had seen the most intense action of the whole Occupy movement. If there wasn’t another occupation there already, it wasn’t coming back.</p>
<h3>Keep the window of possibility open while you can; if you have to split, split on your own terms.</h3>
<p>Movements usually begin with an explosion of uncertainty and potential. So long as the limits are unclear, a wide range of participants have cause to get involved, while the authorities must hold back, unsure of the consequences of repression. How do we keep this window of possibility open as long as possible without sidestepping real disagreements? (Think of Occupy Wall Street when it first got off the ground and all manner of radical and <a href="http://larouchepac.com/node/19779">reactionary</a> tendencies mingled within it.) Is it better to postpone clashes over ideological issues—such as nonviolence versus diversity of tactics—or to precipitate them? (Think of the controversial black bloc in Occupy Oakland on <a href="http://www.bayofrage.com/from-the-bay/the-anti-capitalist-march-and-the-black-bloc/">November 2, 2011</a>.)</p>
<p>One way to approach this challenge is to try to clarify the issues at stake without drawing fixed lines of political identity in the process. As soon as a tactical or ideological disagreement is understood a conflict between distinct social bodies, the horizon begins to close. The moment of potential depends on the fluidity of the movement, the circulation of ideas outside their usual domains, the emergence of new social configurations, and the openness of individual participants to personal transformation. The entrenchment of fixed camps undermines all of these.</p>
<p>This problem is further complicated by the fact that the top priority of the authorities is always to divide movements—often along the same lines that the participants themselves wish to divide. It may be best to try not to precipitate any permanent breaks until the horizon of possibility has closed, then make sure that the lines are drawn on your own terms, not the terms of the authorities or their <a href="http://www.truthdig.com/report/item/the_cancer_of_occupy_20120206/">unwitting liberal stooges</a>.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/atc/atc-dust-2b.gif" rel="lightbox[justice]"><img src="http://cloudfront.crimethinc.com/images/atc/atc-dust-2a.gif" width="500" height="272"/></a></p>
<h3>Push the envelope.</h3>
<p>What is still possible once the horizon has been circumscribed? In a dying movement, one can still <a href="http://www.crimethinc.com/blog/2012/09/17/post-debate-debrief-video-and-libretto/"><em>push the envelope,</em></a> setting new precedents for the future so subsequent struggles will be able to imagine going further. This is a good reason not to avoid ideological clashes indefinitely; in order to legitimize the tactics that will be needed in the future, one often has to begin by acting outside the prevailing consensus.</p>
<p>For example, at the conclusion of November 2, 2011, Occupy Oakland participants controversially attempted <a href="http://www.indybay.org/newsitems/2011/11/03/18697018.php">to take over a building</a>. This provoked a great deal of backlash, but it set a precedent for a series of building occupations that enabled Occupy to begin to challenge the sanctity of private property during its long waning phase—giving Occupy a much more radical legacy than it would otherwise have had.</p>
<h3>One year’s breakthroughs are the next year’s limitations.<a class="footnote" href="javascript:void(0);" onclick="return overlib('For example, the emphasis on tactical nonviolence that enabled a large body to converge around Occupy Wall Street became an obstacle to keeping the streets when repression escalated. Often, in places where a movement crosses a new threshold, it subsequently remains suspended at that point of development, limited by the same structures that enabled it to advance. After the occupation of the capitol in Madison in spring 2011, activity in Wisconsin never caught up to what followed in New York, just as Occupy Wall Street never matched the intensity of Occupy Oakland. In February 2012, after Occupy Oakland had died down, the student strike in Montréal set the high-water mark for contemporary struggle in North America—and anarchists in Montréal are still paying the price of this high point, facing intense police repression.', CAPTION, '[1]');" onmouseout="nd();">[1]</a></h3>
<p>During the burgeoning stage of a movement, participants often become fixated on certain tactics. There is a tendency to try to repeat one’s most recent successes; in the long run, this can only produce conservatism and diminishing returns. Diminishing returns are still returns, of course, and a tactic that is no longer effective in its original context may offer a great deal of potential in another setting—witness the occupation of <a href="http://www.crimethinc.com/blog/2013/06/19/postcards-from-the-turkish-uprising/">Taksim Square</a> in June 2013, when no one in the US could imagine occupying anything ever again. But tactics and rhetoric eventually become used up. Once no one expects anything new from them, the same slogans and strategies that generated so much momentum become obstacles.</p>
<p>As soon as Occupy is in the news, anyone who had an occupation in mind had better hurry to carry it out before the window of opportunity has closed and nobody wants to occupy anything at all. In a comic example of this tendency to fixate on certain tactics, after Occupy Oakland was evicted, Occupy Wall Street mailed a large number of tents across the country as a gesture of support. These tents merely took up storage space over the following months as the struggle in Oakland reached its conclusion on other terrain.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/atc/atc-dust-3b.gif" rel="lightbox[justice]"><img src="http://cloudfront.crimethinc.com/images/atc/atc-dust-3a.gif" width="500" height="639"/></a></p>
<h3>Don’t regress to outmoded strategies.</h3>
<p>Sometimes, after a new strategy that is attuned to the present context has created new momentum, there is a tendency to revert to previous approaches that have long ceased working. When people with little prior experience converge in a movement, they sometimes demand guidance from those who have a longer history of involvement; more often, it is the veterans themselves who demand to provide this guidance. Unfortunately, longtime activists frequently bring in old tactics and strategies, using the new opportunity to resume the defeated projects of the past.</p>
<p>For example, fourteen years ago, worldwide summit-hopping offered a way to exert transnational leverage against capitalist globalization, offering a model to replace the local and national labor organizing that had been outflanked by the international mobility of corporations. Yet when labor activists got involved, they criticized summit-hoppers for running around the world rather than organizing locally the old-fashioned way. Likewise, Occupy got off the ground because it offered a new model for an <a href="http://www.crimethinc.com/texts/recentfeatures/nightmares.php">increasingly precarious population</a> to stand up for itself without stable economic positions from which to mobilize. But again, old-fashioned labor activists saw this new movement only as a potential pool of bodies to support union struggles, and channeled its momentum into <a href="http://www.bayofrage.com/further-reading/wall-street-of-the-waterfront/">easily coopted dead ends</a>.</p>
<p>In the wake of every movement, we should study what its successes and failures show about our current context, while recognizing that by the time we can make use of those lessons the situation will have changed once more.</p>
<h3>Beware of rising expectations.</h3>
<p>When a movement is at its high point, it becomes possible to act on a scale previously unimaginable. This can be debilitating afterwards, when the range of possibility contracts again and the participants are no longer inspired by the tactics they engaged in before the crest. One way to preserve momentum past the end of a movement is to go on setting attainable intermediate goals and affirming even the humblest efforts toward them.</p>
<p>The trajectory of <a href="http://www.crimethinc.com/texts/recentfeatures/greenscared.php">green anarchist struggles</a> in Oregon at the turn of the last century offers a dramatic example of this kind of inflation. At the beginning, the goals were small and concrete: protect a specific tree or a <a href="http://crimethinc.com/movies/pickaxe.html">specific stretch of forest</a>. After the <a href="http://www.crimethinc.com/blog/2006/11/30/seattle-seven-years-later/">World Trade Organization protests</a> in Seattle, the goals of green anarchists in the region <a href="http://greenanarchy.anarchyplanet.org/">hypertrophied</a> until they reached a tactical impasse. When your immediate objective is to “take down industrial civilization,” just about anything you can do is going to feel pointless.</p>
<p>Indeed, during a declining phase, it may be important to resist the tendency to escalate. When the <a href="http://www.crimethinc.com/texts/recentfeatures/shac.php">SHAC campaign</a> ran aground, <a href="http://www.rootforce.org/2008/02/10/a-revised-strategy/">Root Force</a> set out to apply the same strategy against a much bigger target—scaling up from a single animal testing corporation to the major infrastructural projects underlying transnational capitalism. A SHAC-style campaign targeting a <em>smaller</em> corporation might have succeeded, empowering a new generation to go on applying the strategy, but Root Force never even got off the ground.</p>
<h3>Quit while you’re ahead.</h3>
<p>The declining phase of a movement can be a dangerous time. Often, popular support has died down and the forces of repression have regained their footing, but the participants still have high hopes and feel a sense of urgency. Sometimes it’s best to shift focus before something really debilitating occurs.</p>
<p>Yet quitting while you’re ahead is complicated. If the connections that have been made are premised on collective action, it can be difficult to retain these without staying in the streets together.</p>
<p>Months after Occupy Oakland was definitively over, police <a href="http://www.youtube.com/watch?v=fmA2jjNVr2g">brutally attacked</a> an <a href="http://www.bayofrage.com/from-the-bay/all-our-ancestors-killed-colonists/">anarchist march</a> against Columbus Day, making several arrests and pressing felony charges. It is an open question whether this showed that anarchists had overextended themselves, but after a payback action the following night in Oakland, street activity in the Bay Area died down for almost a year. On the other hand, after the UK student movement died down, an explosion of <a href="http://www.crimethinc.com/texts/recentfeatures/nightmares.php">riots</a> in August 2011 suggested that many of the underclass participants felt abandoned by the withdrawal of their former activist allies from street action. It is possible that, had the movement continued in some form, the riots might have turned out differently—as a point of departure for another wave of collective struggle, rather than the desperate act of a marginalized population rising ruinously against society itself.</p>
<h3>Be prepared for burnout and depression.</h3>
<p>After the crest, when the euphoria is over, many participants will experience depression. Since the events that regularly brought them together have ceased, they are isolated and more vulnerable. Others may veer into addiction: substance use can be a way to maintain intimacy with each other and with danger itself when there is no more fire in the streets. The simple pleasures with which people celebrated their victories can expand to fill the space left by the receding tide of events, becoming self-destructive. This is another reason to establish new venues to maintain camaraderie and connection when the window of possibility is closing.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/atc/atc-dust-4b.gif" rel="lightbox[justice]"><img src="http://cloudfront.crimethinc.com/images/atc/atc-dust-4a.gif" width="500" height="621"/></a></p>
<h3>Save energy for the fallout.</h3>
<p>All of these problems are often intensified by the explosion of discord that usually follows a movement’s demise. Once it is clear that a movement is definitively over, all the conflicts that the participants have been putting off come to the fore, for there is no longer any incentive to keep them under the rug. Suppressed resentments and ideological differences surface, along with serious allegations about abuse of power and violations of consent. Learning from these conflicts is an essential part of the process that prepares the way for future movements: for example, contemporary anarchism is descended in part from the feminist backlash that followed the New Left movements of the 1960s. But participants rarely think to save energy for this phase, and it can feel like thankless work, since the “action” is ostensibly over.</p>
<p style="color: #ab0000; margin: 20px">It was a few nights before the eviction of the Occupy Philly encampment, and we were holding a General Assembly to decide what to do. Tensions were running high between the residents of the camp, who were primarily homeless, and those who participated chiefly in meetings and working groups. That night, a homeless man interrupted the GA to accuse several of those in leadership positions of being in league with the police, being racist, and planning to sell out the homeless. The facilitator tried to ignore the disruption, but the angry man drowned him out and eventually riled up a few more people who began shouting too. In this moment of chaos and heightened emotion, we had a unique opportunity. We could have shifted our focus from the threat that the government wanted us to react to, instead using that GA to finally address the tensions in our own group in hopes of building a force that could survive into the next phase of struggle. Instead, the facilitator tried to restore order by directing us to &#8220;break into small groups and discuss what &#8216;respect&#8217; means.&#8221; My heart sank. Our shared energy was explosive; we needed to channel it, not suppress it.</p>
<p style="color: #ab0000; margin: 20px">That was the last time I saw many of the comrades I’d befriended over the preceding months. The eviction wasn’t the greatest threat we faced after all.</p>
<h3>Repression hits hardest at the end.</h3>
<p>Government repression usually does not hit in full force until after a movement has died down. It is most convenient for the state to attack people when their support networks have collapsed and their attention is elsewhere. <a href="http://www.crimethinc.com/texts/recentfeatures/greenscared.php">Operation Backfire</a> struck years after the high point of Earth Liberation Front momentum, when many of the participants had moved on and the communities that had supported them had disintegrated. Similarly, the authorities waited until May 2012 to strike back at Occupy with a series of <a href="http://www.crimethinc.com/blog/2012/05/29/inside-the-fbi-entrapment-strategy/">entrapment cases</a>.</p>
<p>The chief goal of repression is to open the fault lines within the targeted social body, isolating it and forcing it into a reactive position. Ideally, we should respond to repression in ways that establish new connections and position us for new offensives. </p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/atc/atc-dust-5b.gif" rel="lightbox[justice]"><img src="http://cloudfront.crimethinc.com/images/atc/atc-dust-5a.gif" width="500" height="284"/></a></p>
<h3>Hold your ground.</h3>
<p>How do we transition into other forms of connection when the exceptional circumstances that drew us together are over? The networks that coalesce effortlessly during the high point of momentum rarely survive. While new events were unfolding, there was an obvious reward for setting differences aside and interrupting routines to converge. Afterwards, the large groups that formed <a href="http://www.crimethinc.com/blog/2011/12/06/three-years-since-the-greek-insurrection/">slowly break down into smaller ones</a>, while smaller groups often vanish altogether. The reshuffling of allegiances that takes place during this period is vital, but it’s equally vital not to lose each other in the shuffle.</p>
<p>During the crest of a movement, participants often take for granted that it will leave them at a higher plateau when it is over. But this is hardly guaranteed. This may be the most important question facing us as we approach the next wave of struggles: how do we gain and hold ground? Political parties can measure their effectiveness according to how many new recruits they retain, but anarchists must conceive of success differently.</p>
<p>In the end, it isn’t just organizations with contact lists that will remain after the crest, but above all new questions, new practices, new points of reference for how people can stand up for themselves. Passing these memories along to the next generation is one of the most important things we can do.</p>
<h3>Further Reading</h3>
<p><a href="http://www.crimethinc.com/blog/2011/12/06/three-years-since-the-greek-insurrection/">Three Years since the Greek Insurrection</a>, our interview with comrades in Athens about the months following the <a href="http://www.crimethinc.com/blog/2008/12/25/how-to-organize-an-insurrection/">uprising of December 2008</a></p>
<p><a href="http://www.bayofrage.com/featured-articles/occupy-oakland-is-dead/">Occupy Oakland Is Dead; Long Live the Oakland Commune</a></p>
<p><em>Cracking under Pressure: Narrating the Decline of the Amsterdam Squatters&#8217; Movement</em>, by Lynn Owens</p>
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1] For example, the emphasis on tactical nonviolence that enabled a large body to converge around Occupy Wall Street became an obstacle to keeping the streets when repression escalated. Often, in places where a movement crosses a new threshold, it subsequently remains suspended at that point of development, limited by the same structures that enabled it to advance. After the occupation of the capitol in Madison in spring 2011, activity in Wisconsin never caught up to what followed in New York, just as Occupy Wall Street never matched the intensity of Occupy Oakland. In February 2012, after Occupy Oakland had died down, the student strike in Montréal set the high-water mark for contemporary struggle in North America—and anarchists in Montréal are still paying the price of this high point, facing intense police repression.</p>    
</div>