<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/1b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/1a.jpg" alt="Fire Extinguishers and Fire Starters: Anarchist Interventions in the #Spanish Revolution, an account from Barcelona" width="500" height="432"></a></p>
<p align-"right" style="margin-right: 0px">&nbsp;</p>
<h2 name="a" id="a">Barcelona, Spring 2011: <br />
Chronology of An Unexpected Event</h2>
<h3>Buildup:</h3>
<p><strong>September 29, 2010:</strong> The major labor unions, CCOO and UGT, along with the anticapitalist CGT, the anarcho-syndicalist CNT (which has multiple splits), and other small unions, hold a general strike to protest the bank bailouts and proposed austerity measures included in the Labor Reform. In many city centers and industrial zones, participation in the strike is massive. In Barcelona, the streets erupt in heavy, day-long rioting. CCOO and UGT pickets, on the contrary, tend to be symbolic and spectacular. Both organizations subsequently sign on to the Labor Reform. Before or shortly after the strike, half a dozen neighborhoods in Barcelona form neighborhood &ldquo;social assemblies.&rdquo;</p>
<p><strong>November 28, 2010:</strong> Elections in Catalunya replace the governing Socialist Party with the rightwing Convergencia i Uni&oacute;, which adopts a hardline, pro-police rhetoric.</p>
<p><strong>January 27, 2011:</strong> Acting apart from the major unions, the CGT, CNTs, and COS (a left Catalan coordination of syndicates) hold a general strike in Catalunya, which is also called for in Euskadi and other parts of the Spanish state. The strike coincides with the approval of the Labor Reform, supported by the major unions and the Socialist Party (which has led the government in Madrid since 2004).  In certain cities, the strike receives substantial support in the transport and manufacturing sectors, but generally achieves little participation. In Barcelona, burning barricades, sabotages, pickets, and contentious protests win a combative visibility for the strike.</p>
<p><strong>May 1, 2011:</strong> In Barcelona, the <a href="http://anarchistnews.org/?q=node/14546">anticapitalist Mayday protest</a>, supported by the CNTs, CGT, COS, socialist <em>indepes</em> (Catalan independence activists), and informal or &ldquo;black bloc&rdquo; anarchists, leads thousands of people into the emblematic rich neighborhood, Sarri&agrave;, where protestors burn dumpsters and luxury cars, smash up approximately a hundred banks, fashion stores, and car dealerships, cover the walls in spray-painted slogans, and throw bottles and paint bombs at police before being dispersed in a heavy charge. The mood is exultant. The weeks before and after are marked by especially high quantities of sabotage and attacks.</p>
<h3>#Revolution Breaks Out:</h3>
<p><strong>Sunday, May 15:</strong> A recently formed platform centered in Madrid, <em>Democracia Real Ya</em> or &ldquo;Real Democracy Now&rdquo; (DRY), holds simultaneous protests in dozens of cities throughout the Spanish state, convened via Facebook, Twitter, Indymedia and various activist listservs. That night, the idea is spread via Twitter to camp out in Puerta del Sol, a central Madrid plaza, modeling on the Tahrir Square occupation in Egypt. In other cities, occupations also begin in central plazas that night or the next night. </p>
<p><strong>Monday, May 16:</strong> In the evening, eighty to a hundred people begin an encampment in Pla&ccedil;a Catalunya, the symbolic center of Barcelona, which in the last decade has become almost exclusively a tourist zone. As in other cities, the occupation organizes itself with a general assembly. A small number of anarchists are participating. In the meeting, they argue down the proposal to sign on to the Real Democracy Now manifesto from Madrid. Many other people also express the need for the Barcelona encampment to develop independently. It is decided the encampment will release no unitary manifestos that attempt to speak for all participants. Notwithstanding, principles of unity already authored by the DRY activists&mdash;non-party assembly decision-making, nonviolence, and unity among <em>los indignados,</em> &ldquo;the indignant&rdquo;&mdash;are successfully imposed.</p>
<p><strong>Tuesday, May 17:</strong> Early in the morning, the police attack the occupation in Madrid, beating and harassing the 250 people camped out there and arresting 19. However, comrades gather outside the jail, and the square is subsequently reoccupied by an even larger and more energetic crowd. The Barcelona encampment grows to over a thousand. As in other cities, the central assembly begins to create commissions to work out various infrastructural and ideological needs; these include &ldquo;extension,&rdquo; &ldquo;communication,&rdquo; &ldquo;content,&rdquo; &ldquo;assembly preparation,&rdquo; &ldquo;financial,&rdquo; &ldquo;legal,&rdquo; and &ldquo;kitchen.&rdquo; During the day, DRY activists carry out nonviolent sit-ins in various banks. Hundreds of people are sleeping in the plaza overnight.</p>
<p><strong>Wednesday, May 18:</strong> The encampment makes the front page of Barcelona's various free newspapers, which are more trend- and controversy-sensitive than the traditional newspapers. Up until now, the latter had been silencing the events, but once the cat is out of the bag they take the lead in sculpting public opinion on the so-called 15 May or 15M movement. At the nightly <em>cassolada</em> (pots and pans noise demo) and assembly, the crowds in Pla&ccedil;a Catalunya reach 5-10,000. Many anarchists who had previously abstained from the pro-democracy protest, either out of disdain or because other protests were happening the same weekend, spontaneously converge in the crowd. Several bring whatever anarchist flyers and pamphlets they had laying around, and these are quickly snatched up by the crowd. Anarchists make plans to hold a debate on democracy the next day, without getting approval from the central assembly.</p>
<p><strong>Thursday, May 19:</strong> Twenty thousand people take part in the cassolada and assembly, and during the day thousands more people pass through, or hang out to make music and art. In the evening, some anarcho-punks have set up a distribution, which serves as a convergence point for various anarchists. The first original anarchist critiques of the situation are printed and distributed (see <a href="#c">appendix</a>), while timely texts on democracy and nonviolence that have recently been published in the Catalan anarchist journal, <em><a href="http://terracremada.pimienta.org" target="_blank">Terra Cremada</a></em>, are reformatted as flyers and distributed.  In the late afternoon, we start the debate with a critique of democracy. Fifty people of all sorts crowd in to participate, with great interest. We use an old megaphone lent by the CNT, but many speakers prefer not to use it; thus a small upward limit is placed on participation on the debate, as no more than the fifty people closest to the center can hear over the background noise of the plaza.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/2b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/2a.jpg" width="500" height="750" style="margin-bottom: 2px"></a><br /><em>Night of May 19 in the plaza</em></p>
<p><strong>Friday, May 20</strong>: Anarchists set up a tent in the morning, with a table for distributing flyers, posters, and other literature. More critiques written by participants in the occupation are printed. A self-appointed representative of one of the commissions attempts to kick out the anarchist tent and another tent set up by members of a performance-oriented squatted social center, on the justification that space in the plaza is reserved for the commissions. The evening meeting is largely dominated by Trotskyists and small-scale, left-wing Catalan independence politicians. The crowds have swelled beyond the limits of the plaza, and can no longer be counted. Even though a high quality sound system has been set up, the half of the multitude that rings the margins of the plaza cannot hear the assembly. The number of commissions has reached, by some counts, 17, along with multiple sub-commissions. Meaningful participation in the official structure becomes increasingly impossible.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/3b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/3a.jpg" width="500" height="333" style="margin-bottom: 2px"></a><br /><em>Food distribution</em></p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/4b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/4a.jpg" width="500" height="333" style="margin-bottom: 2px"></a><br /><em>Consensus in the plaza?</em></p>
<p><strong>Saturday, May 21:</strong> The &ldquo;Day of Reflection,&rdquo; a constitutionally mandated holiday before Election Sunday. Protests of any kind are firmly prohibited this day. If the occupation previously constituted an illegal gathering, as of Saturday it is a flagrant violation of the Spanish Constitution. In general, people are defiant and contemptuous of the law. There had been much talk of police evictions, but with the massive crowds, President Zapatero and the Supreme Court have decided to be tolerant. Notwithstanding, DRY activists in many cities use the threat of police eviction as an excuse to remove anti-election banners. In Barcelona they are unsuccessful. Hundreds of thousands of people pass through Pla&ccedil;a Catalunya to witness the &ldquo;revolution.&rdquo; Everyone in the city is talking about it. Out of the Content Commission, which had previously been trying to impose a reformist statement of minimum demands, a &ldquo;Self-Organization and Direct Democracy&rdquo; sub-commission is formed, with heavy anarchist participation.</p>
<p><strong>Sunday, May 22:</strong> Countrywide elections take place for city governments and deputies. The Socialist Party loses its majority; by next year they will have to be replaced in Madrid by the conservative Popular Party. However, both of these two major parties lose a huge portion of their traditional votes. Extreme right and fascist parties pick up a large number of votes, although they remain relatively small. In Catalunya, left-wing independence parties and other fringe left parties greatly increase their proportion of the votes and enter into power in some cities. In Euskadi, the recently legalized Basque independence party Bildu wins major victories and becomes the second largest party in the region. The greatest winner is abstention, which is the preferred option for one-third to one-half of the electorate, depending on the region. Additionally, blank or null votes double or even triple, to reach around 5%. <a href="http://en.wikipedia.org/wiki/Lionel_Messi">Messi</a>, <a href="http://en.wikipedia.org/wiki/Shakira">Shakira</a>, and &ldquo;mi puta madre&rdquo; gain record numbers of votes. In Pla&ccedil;a Catalunya, the crowds remain unbelievably massive, but contrary to all previous days, the atmosphere is more like a county fair, as many people come from the polling stations to check out the curiosity.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/5b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/5a.jpg" width="500" height="684" style="margin-bottom: 2px"></a></p>
<p><br /><strong>Monday, May 23:</strong> The occupations around Spain continue, although they begin to diminish. In Barcelona, the cassolada is shortened from an hour and a half to half an hour. The general assembly involves 5-10,000 people, roughly the same amount as the first Wednesday. A proposal consensed on by the Self-Organization sub-commission to decentralize the assembly and respect autonomous decision-making processes is voted on and receives overwhelming support. However, thirty people, mostly Trotskyists, vote for &ldquo;more debate&rdquo; and the proposal is sent back to the commission, as debate is impossible in the massive general assembly.</p>
<p><strong>Tuesday, May 24:</strong> During the day, the encampment in Pla&ccedil;a Catalunya is very small, but all the physical structures (computer lab, sound system, kitchen, garden, tents) guarantee its continued presence. The central assembly is only half as large as the previous day. By this point, anarchists have printed and distributed at least 20,000 flyers, pamphlets, and posters, all paid for by donations collected at the anarchist tent.</p>
<p><strong>Wednesday, May 25:</strong> The numbers remain the same as the previous day. Some activists begin to build houses in the trees of Pla&ccedil;a Catalunya to make an eviction more difficult. In the neighborhood of Clot, the Social Assembly of the neighborhood holds an open meeting in the market square. 150 people, young and old, come to participate. After engaging conversations, debates, and brainstorms, the meeting ends with a cassolada. Other neighborhoods begin to do the same, sometimes joining up with the weekly pickets held by local hospital or education workers protesting cutbacks.</p>
<p><object width="500" height="375"><param name="movie" value="http://www.youtube-nocookie.com/v/PtaNg8c8OtU?version=3&amp;hl=en_US&amp;rel=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube-nocookie.com/v/PtaNg8c8OtU?version=3&amp;hl=en_US&amp;rel=0" type="application/x-shockwave-flash" width="500" height="375" allowscriptaccess="always" allowfullscreen="true"></embed></object><br />
<em>Police attack the plaza on May 27</em></p>
<p><strong>Friday, May 27:</strong> At 6:30 a.m., approximately 300 riot police move into Pla&ccedil;a Catalunya in order to &ldquo;clean up&rdquo; the plaza for &ldquo;hygienic reasons&rdquo; and to remove potentially dangerous clutter ahead of tomorrow's European football championship between Bar&ccedil;a and Manchester, which is to be televized in the plaza. About two hundred people are sleeping in the plaza at the time. A meeting is called; this is the same tactic certain activists used to centralize and pacify 500 people in a major occupation in Barcelona before the January general strike, enabling the police to detain and evict the lot of them with ease. Thinking they have come to evict the plaza, tens of thousands of people surge towards the center and surround the police. Sanitation workers are loading all the materials in the plaza into trucks. Thirty-five trucks are filled with tents, tables, chairs, sleeping bags, computers, kitchen equipment, literature, the sound system, and more. Protestors unsuccessfully attempt to prevent the trucks from leaving the plaza, provoking police charges. Dogmatic pacifists attempt to force everyone to sit down and hold signs saying &ldquo;nonviolent resistance.&rdquo; They physically force some people to sit down, and accuse those who do not of being infiltrators. Hundreds of people are beaten by police while sitting down. Over time, more and more people take to their feet, either as a rejection of the extreme degree of pacifism or simply to allow themselves to be more mobile in confronting the police. As the police are repeatedly swarmed and surrounded, they fire rubber bullets into the crowd at close range. People begin to throw plastic bottles, trash, water, and juice at the cops, and in a few cases rocks are thrown. Pacifists form a human chain to protect the police lines, but the crowds eventually push past them and swarm the police, forcing them out of the plaza and cutting off the surrounding streets. Perhaps fifty thousand people or more have converged on the center, and the atmosphere is triumphant. 121 people have been injured, many with broken bones. One person is reported to have lost an eye and another person to have lost hearing in one ear. One person&rsquo;s lungs and spleen have been punctured by a rubber bullet fired from less than two meters away. He is sent to the hospital in critical condition; no reliable information can be found about him afterwards. A rumor circulates that a Portuguese protestor in Barcelona has died.</p>
<p><strong>Saturday, May 28:</strong> Football fans gather for the European championship. Normally, a giant TV screen is installed in Pla&ccedil;a Catalunya, but due to the continuing occupation, the screen is placed at another point in the city center. The media worry about clashes between protestors and football hooligans, and rumors circulate that Nazis are planning to infiltrate and attack the plaza. Pacifists form cordons to block off all the entrances to the plaza. No football fans are allowed entry. The pacifists watch as fans fight with police, and cheer as they are arrested. Even youths are denied sanctuary in the plaza. The pacifists attempt to silence anarchists shouting at the police. After this day, many anarchists stop participating in the occupation, or shift to the neighborhoods.</p>
<h3>Winding Down:</h3>
<p><strong>Sunday, May 29:</strong> In other major cities, including Sevilla and Valencia, the occupations have continued, but they have been monopolized by DRY activists; there is little open debate and low participation. In the nightly meeting in Sevilla, only about two hundred people participate, while during the day scarcely fifty people are present.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/6b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/6a.jpg" width="500" height="341" style="margin-bottom: 2px"></a><br /><em>May 29: People remain in the plaza in Barcelona</em></p>
<p><strong>Wednesday, June 1: </strong>The general assembly in Pla&ccedil;a Catalunya has shrunk to a stable thousand people participating every night. The tents, kitchen, garden, and sound system stolen by police have been replaced. During the day, a few hundred people hang out. In the neighborhoods, open meetings and cassoladas continue to gain steam. Some neighborhoods begin to block streets, a proposal that was always too controversial for the general assembly. DRY activists in some neighborhoods insist that the neighborhood assemblies must be auxiliaries of the central assembly in Pla&ccedil;a Catalunya, but they do not seem to be successful. In some cases, exclusive nonviolence is abandoned as a principle of unity. In Clot, participation in the neighborhood open assembly grows to two or three hundred, and new plaques are installed to change the name of the square to &ldquo;Pla&ccedil;a de l'Assemblea.&rdquo; Open assemblies and cassoladas are carried out in perhaps ten other neighborhoods.</p>
<p><strong>Thursday, June 2:</strong> A fringe left political party sets up a table in Pla&ccedil;a Catalunya, but anarchists physically eject them, provoking a confrontation with pacifists. Pacifists, meanwhile, continue to eject Pakistani street vendors from the plaza, while refusing to apply the same policy to the generally white citizens who buy beer from them. Anarchists begin several arguments with these pacifists. Two days later, the first text in a non-European language to be distributed inside the square appears. It is a flyer in Urdu, asking the vendors not to sell beer in the plaza, because it hurts the image of the occupation.</p>
<p><strong>Sunday, June 5:</strong> Comrades in Madrid report that the occupation there has largely degraded. Many junkies are shooting up in the plaza, possibly encouraged to go there by police or simply taking advantage of the autonomous zone, while Nazis have attempted to join the assembly and the protest marches on multiple occasions. The rumor circulates that DRY founders in Madrid are talking about turning their platform into a political party before the federal level elections scheduled for the fall. In Barcelona, anarchists organize a talk criticizing the imposition of nonviolence in Pla&ccedil;a Catalunya. That evening, the general assembly decides to dismantle the encampment but keep the information tables and commission tents open during the day. Plans are prepared for a blockade of the Catalan parliament on June 15, and for a major protest on June 19. Lead organizers propose to have a security cordon within the march in case certain people start chanting violent slogans.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/7b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/7a.jpg" width="500" height="674" style="margin-bottom: 2px"></a><br /><em>Poster about the May 27 attacks: <br />
&ldquo;All you need to know about the police is this, and nothing more&rdquo;</em></p>
<p align="center">&nbsp;</p>
<h2 id="b" name="b">The Characteristics of the Occupation</h2>
<p>The first day I set foot in the plaza, I knew I was experiencing something unique. No one here had ever seen anything like this. Thousands of people, friends and strangers, crowding together, announcing their indignation, defying the law, calling for revolution. I had hardly ever spent time before in Pla&ccedil;a Catalunya. It was just a place for tourists and pigeons. Now I could pass hours here and have conversations with all sorts of people. A Pakistani man asks me to help translate what's going on. A young student comments on a flyer I&rsquo;m handing out. Two grandparents argue about democracy and the best way to go about the struggle. </p>
<p>Once people saw that I was handing out flyers, they lined up to take them and soon I was all out. During the first week, everyone was excited, everyone was desperate for new ideas and perspectives. In a matter of days we distributed thousands of flyers, many of them new texts written just for this situation. On the other side of the city and in the metro, I often saw people reading our texts&mdash;not just glancing at them, but poring over them. That first week, I could go into any bakery or copy shop in town and request free bread or cheap copies &ldquo;for the plaza&rdquo; and receive at least a sympathetic response, and often a lot of free materials.</p>
<p>What we have experienced in Barcelona is a rupture&mdash;not so much in State control, in view of the democratic forms chosen by the occupation movement, but most definitely in people&rsquo;s affective reality. Society left its isolation cells and physically manifested itself in the middle of the plaza, and many people were feeling its presence for the very first time. They were recognizing how isolated they had been until now, in the plaza, where they encountered a force, a collective power, waiting to be reborn. In these unprecedented circumstances, people could begin to believe in the possibility of situations that were entirely new.</p>
<p>Before, when you handed someone an anarchist flyer, they might think about it for a while, it might improve their understanding of you, it might annoy them, but in any case they would only digest it at the level of opinions&mdash;because you were talking about something hypothetical, something unreal. But in the plaza, hearing our conversations or reading the literature we had on our table, people would really begin to debate: &ldquo;But if we get rid of all the politicians, new ones will just come replace them.&rdquo; &ldquo;No, these kids are right! We need to get rid of all of them. If we're able to get rid of the first batch, we can get rid of the next ones too!&rdquo;</p>
<p>People's aesthetics no longer marked their political niche. The most important thing was their bravery and sincerity. Many times I saw grandparents berating young punks for being too passive, or people dressed for work taking a more radical position than activist hippies. And everyone was talking about real possibilities. For at least the first week, these people meant it when they chanted &ldquo;Aqu&iacute; comen&ccedil;a la revoluci&oacute;!&rdquo; &ldquo;The revolution begins here!&rdquo;</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/8b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/8a.jpg" width="500" height="333" style="margin-bottom: 2px"></a></p>
<h3>So where did the so-called Spanish Revolution end up?</h3>
<p>I remember yelling to a friend, high on the mass excitement of those first days, &ldquo;This is our revolution! No barricades, nothing romantic like that, but what do we expect? It's a piece of shit, but we already knew this is the world we live in. We have a lot of work to do!&rdquo;</p>
<p>Within the complexity of the Spanish Revolution, one could find plenty to denounce. For a critical anarchist, it would be easier to reject the whole thing than embrace it. Fortunately, on the whole Barcelona anarchists refused to take the easy road. </p>
<p>Most noteworthy in its long list of faults were its disappointed pretensions of being revolutionary. The Democracia Real Ya activists did their best to place the whole movement in an ideological straightjacket from the beginning. In Barcelona in particular, these activists were joined by a legion of minor league politicians, particularly Catalan indepes, as well as Trotskyists and dogmatic pacifists, all trying to get a piece of the pie. These in turn were aided by a great mass of well-meaning people who were simply reproducing the values of democracy and nonviolence taught to them by the system, and no small number of highly skilled and no less well-meaning activists of the anti-globalization or student variety&mdash;including some anarchists&mdash;who cherished the processes of consensus and direct democracy.</p>
<p>This complex agglomeration of people formed a powerful <a href="http://en.wikipedia.org/wiki/Recuperation_(politics)">recuperation machine</a> that could not be neutralized with any simple approach. But I'm getting ahead of myself. </p>
<p>The preamble of the <a href="http://roarmag.org/2011/05/manifesto-spanish-revolution-puerta-del-sol-protests/">DRY manifesto</a> gives a good impression of their political brand: </p>
<p><em>&ldquo;We are ordinary people. We are like you: people, who get up every morning to study, work or find a job, people who have family and friends. People, who work hard every day to provide a better future for those around us. Some of us consider ourselves progressive, others conservative. Some of us are believers, some not. Some of us have clearly defined ideologies, others are apolitical, but we are all concerned and angry about the political, economic, and social outlook which we see around us: corruption among politicians, businessmen, bankers, leaving us helpless, without a voice.&rdquo;</em></p>
<p>Democracia Real Ya did an excellent job of formulating a mediocre politics defined by its populism, victimism, reformism, and moralism. By using common, value-laden terms such as &ldquo;democracy&rdquo; (good) and &ldquo;corruption&rdquo; (bad), they created a discursive trap that garnered overwhelming support for all their proposals while deflecting or falsely including proposals that went further. Their stated minimums included revolutionary language and the highly popular sentiment that &ldquo;we're going to change everything,&rdquo; while offering a ladder of demands that basically signaled the prices, from cheap to expensive, at which they would sell out. It started with reform of the electoral law, passed through laws for increased oversight of the bankers, and reached, at it's most radical extreme, a refusal to pay back the bailout loans. Everything was structured around demands communicated to the existing government, but prettied up in populist language. Thus, the popular, anarchist slogan <em>Ning&uacute; ens representa</em>, &ldquo;No one represents us,&rdquo; was distorted within their program to mean, &ldquo;None of the politicians currently in power represent us: we want better ones who will.&rdquo;</p>
<p>However, to carry out this balancing act, they did have to adopt vaguely antiauthoritarian organizing principles inherited from the antiglobalization movement, such as open assemblies, no spokespersons, and no political parties.</p>
<p>Proposals centered on direct action or sentiments containing a rejection of government and capitalism were easily neutralized within this ideological framework. The former would be paternalistically tolerated as cute little side projects eclipsed by the major projects of reformist demands, and the latter would be applauded, linked back to the popular rhetoric already in use, and corrupted to mean an opposition to current politicians or specific bankers. </p>
<p>The only way to challenge this co-optation of popular rage was to focus critique on democracy itself. We quickly discovered that the idea of direct democracy was the major theoretical barrier that protected the existing representative democracy, and direct democracy activists, including anarchists, were the critical bridge between the parasitic grassroots politicians and their social host body. </p>
<p>By the fourth or fifth day of the occupation in Barcelona, it became apparent in practice what we had already argued in theory: that direct democracy recreates representative democracy; that it is not the features that can be reformed (campaign finance, term limits, popular referendums), but the most central ideals of democracy that are inherently authoritarian. The beautiful thing about the encampment in the plaza was that it had multiple centers for creation and initiative-taking. The central assembly functioned to suppress this; had it succeeded, the occupation would have died much sooner. It did not succeed, thanks in part to anarchist intervention. </p>
<p>The central assembly did not give birth to one single initiative. What it did, rather, was to grant legitimacy to initiatives worked out in the commissions; but this process must not be portrayed in positive terms. This granting of legitimacy was in fact a robbing of the legitimacy of all the decisions made in the multiple spaces throughout the plaza not incorporated into an official commission. Multiple times, self-appointed representatives of this or that commission tried to suppress spontaneous initiatives that did not bear their stamp of legitimacy. At other times, commissions, moderators, and internal politicians specifically contravened decisions made in the central assembly, when doing so would favor further centralization. This is not a question of corruption or bad form; <em>democracy always subverts its own mechanisms in the interests of power.</em></p>
<p>Again and again in the plaza, we saw a correlation between democracy and the paranoia of control: the need for all decisions and initiatives to pass through a central point, the need to make the chaotic activity of a multitudinous occupation legible from a single vantage point&mdash;the control room, as it were. This is a statist impulse. The need to impose legibility on a social situation&mdash;and social situations are always chaotic&mdash;is shared by the democracy activist, who wishes to impose a brilliant new organizational structure; the tax collector, who needs all economic activity to be visible so it can be reappropriated; and the policeman, who desires a panopticon in order to control and punish. I also found that numerous anarchists of various ideological stripes were unable to see the crucial theoretical difference between the oppositions <em>representational democracy vs. direct democracy/consensus</em> and <em>centralization vs. decentralization</em>, because the first and second terms of both pairs have been turned into synonyms through misuse. For this reason, I have decided to rehabilitate the term &ldquo;chaos&rdquo; in my personal usage, as it is a frightening term no populist in the current context would use and abuse, and it relates directly to mathematical theories that directly express the kind of shifting, conflictual, constantly regenerating, <a href="http://en.wikipedia.org/wiki/Acephalous_society">acephalous</a> organization anarchists are calling for. </p>
<p>After visiting another city where the encampment had basically killed itself through boredom, I realized that these antiauthoritarian consensus activists had also partially saved the day in Barcelona. Because radical anarchists are so extreme in our critique, we often lack social intuition; we have a hard time viewing the world from the perspective of &ldquo;normalized&rdquo; citizens. And while the <a href="http://twitter.com/#!/search/%23spanish%20revolution">#Spanish Revolution</a> took everyone by surprise, it especially took us by surprise. Only a few of us had arrived by Wednesday, the third day of the occupation, and most did not come until Thursday or Friday. However, the consensus activists tended to be at the heart of it from early on. Many of them were experienced moderators, thanks to their participation in the great mobilizations of the antiglobalization movement, so they were often the ones facilitating the central assembly. And because they functioned as a bridge between the parasitic grassroots politicians and the masses, they also functioned as a shield for anarchist ideals, because they were actors in their own right who had their own goals, quite distinct from the goals of the DRY activists or the Trotskyists.</p>
<p>In cities where this activist core did not exist, DRY activists or Trotskyists quickly homogenized the encampments and vigorously suppressed radical ideas. These encampments soon shrunk like a desiccated corpse, with more parasite than host body. In Barcelona, on the other hand, anarchists enjoyed legitimacy and presence from the get-go, and the grassroots politicians generally had to pay lip service to anarchist organizational ideals, giving radical anarchists more room to work in. </p>
<p>One of the most repugnant features of the occupation, which ultimately caused many anarchists to stop participating, was the imposition of nonviolence. Nonviolence was one of the original principles of the DRY platform, and in Barcelona the first antiauthoritarian participants either did not try to or were not able to reject it. Nonviolence was never debated, but always included in every action proposal, so the choice before the central assembly was always nonviolence or nothing. In the beginning, activists carried out a few peaceful sit-ins. For May 30, DRY announced an action to be carried out throughout the entire Spanish state: that day, everyone should withdraw 155 euros from their bank accounts (155 = 15-5, or 15 May), &ldquo;a peaceful and subtle act, but sufficiently contentious and attention-grabbing to clearly demonstrate the indignation we feel, and also our strength and commitment to take this through to the end,&rdquo; in their words.</p>
<p>But generally, their action plan was to do nothing, to stay in the plazas, to prevent people from seizing or blocking the surrounding streets, and to talk about another protest on the fifteenth day of the following month. When anarchists in Barcelona distributed flyers on the third day of the occupation, they quickly released a statement, not approved by any assembly, saying that the occupation was strictly pacifist, and that the police were trying to infiltrate and encourage violence; therefore all the good citizens should bring their cameras and take pictures of everybody and everything.</p>
<p>I believe it was the first Wednesday or Thursday when a group of activists dropped a huge banner from a major building alongside the plaza, reading &ldquo;Politicians, Bosses, Bankers, CCOO UGT [the major trade unions] Fuck Off.&rdquo; The crowds cheered exultantly. Two days later, another group blocked a street and cut open a section of the giant billboard covering another building, to reveal a large spray-painted slogan beneath; if I remember correctly, it said &ldquo;No one represents us!&rdquo; On this second occasion, some people cheered, but self-appointed leaders tried to stop the action and denounced it as violent.</p>
<p>When police carried out their hygienic operation on Friday, May 26, pacifists verbally or physically obliged everyone to sit down and to hold signs with the words &ldquo;nonviolent resistance.&rdquo; The police beat the protestors with glee, opening heads and breaking arms. On a few occasions when people attempted to snatch away police batons, pacifists ran towards them to bring their message of peace. As thousands more people arrived to liberate the plaza, they overwhelmed police lines and surged towards the cops in the middle, shouting and starting to throw things. Pacifists formed a human chain to protect them. Police were eventually pushed back, not without completing their cleaning operation and allowing the sanitation trucks to depart with all the materials they had stolen. Even though the crowds generally pushed past the limits set forward by the pacifists&mdash;and they certainly didn't do it sitting down waiting for the legal team, as the pacifists had advised&mdash;the ideologues of nonviolence still claimed it as a victory. They also falsely stated that the police attempted to evict the plaza and were defeated. All this should come as no surprise, as pacifists have done the same thing with the Arab revolts&mdash;emboldening statists like Obama to do the same.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/9b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/9a.jpg" width="500" height="333" ></a></p>
<p>The following Saturday was the worst day, when the pacifists formed human chains to keep football fans out of the plaza and cheered police as they arrested hooligans.  When there were still comrades in critical condition in the hospital, injured from rubber bullets shot by police officers, these same pacifists proposed going to support a rally the police were holding to protest their upcoming wage cuts.</p>
<p>There were other problems as well. Senegalese immigrants selling sunglasses and Pakistani immigrants selling beer and sandwiches moved into the autonomous zone we had created in the plaza. Selling things on the street, if you're not rich enough to have your own store or kiosk, is illegal in Barcelona, and the cops often amuse themselves chasing immigrant street vendors. Enter the <em>Convivencia</em> (coexistence, living-together) Commission. The CC formed with the explicit objective of not allowing <em>antisistema</em> to come and take over the plaza. Antisistema is a media term originally used to refer to anarchists in a depoliticized and delegitimizing way; it has since been extended to squatters and anyone else who falls outside the range of acceptable democratic opinion. In popular usage it is almost a synonym for hoodlum or hooligan. Consequently, the proposal to form the CC won popular approval in the assembly before any debate could be had, and despite the fact that many non-anarchist participants in the plaza had signs criticizing the media use of the term &ldquo;antisistema.&rdquo;</p>
<p>The CC police set themselves the task of kicking out the Pakistani <em>lateros</em> (beer vendors). Their justification was that &ldquo;they bothered people&rdquo; by offering beers for sale every few minutes, and that they &ldquo;created a bad image&rdquo; for the encampment (in the media). Multiple times, anarchists confronted CC members, who often went around with name-tags and walkie-talkies, but to no avail. Despite accusations of hypocrisy and racism, they specifically refused to talk to the people who had the money to buy the beer, and only focused on pushing out the people whose livelihood was based on selling it.</p>
<p>There was a heavy dose of legalism as well among the leading organizers. They attempted to get us to take down our signs against voting, claiming it could be used as a justification for a police eviction, even though the whole occupation was blatantly illegal. At another point they raised a stink when some people started an urban garden in the plaza; they complained that replacing the mulch beds around the fountain with plants was &ldquo;uncivic.&rdquo; For context, the <em>civisme</em> laws in Barcelona have been an aggressive tool to kill street culture and make things more comfortable for tourists. Anarchists in the plaza often had to argue against legalist mentalities; it helped that the occupation in itself sprang from illegality. On this front, we gained some ground; the garden, for example, was not suppressed.</p>
<p>There were also problems with certain junkies and drunkards who had taken up residence in the plaza and constantly harassed or even assaulted women. Pacifist organizers and the Convivencia Commission tried to prevent the feminist assembly in the plaza from organizing self-defense classes and taking care of the problem on their own, instead paternalistically offering to protect them. Anarchists had a hard time dealing with the junkies and drunkards who were being jerks. On the one hand, we were glad they were taking advantage of the autonomous zone to live without police harassment for a few weeks. On the other hand, some of them acted in ways we wouldn't tolerate from anybody; in another context, only residual liberal guilt would have kept us from knocking them on their asses. Unfortunately, the situation was extremely complicated: any use of violence could have provoked a major confrontation with the pacifists, with totally unforeseen consequences. Worse still, it could have a conservative backlash that would have vindicated and demanded more of the CC's policing activities. </p>
<p>On the whole, however, there was much in the plaza to value. It was an extensive, chaotic space of self-organization where people met their logistical needs&mdash;sometimes going through the official channels, sometimes not. There was a library, a garden, an international translation center, a kitchen with big stoves and solar cookers, and at any time there were a couple concerts, workshops, debates, and massage parlors taking place, along with innumerable smaller conversations and encounters.</p>
<p>And it was amazing to encounter a wider anarchist community there, to find that most comrades had the same idea to come down to the plaza even though the most visible discourses emanating therefrom were staunchly social-democratic. The comrades we met there were not always members of our pre-existing affinity groups, but also libertarians we had never worked with before. On the whole, comrades demonstrated an impressive commitment, agility of action, and a nuanced and incisive critique. It became clear again that the old stereotype of the anarchist ghetto is at best only partially true. At the first chance to join a collectivity and communicate with others, most of us were there, even though it was often an uncomfortable or even hostile environment. The very fact that we can speak of an &ldquo;anarchist ghetto&rdquo; indicates that we are less isolated than most people. This communality that we carry with us makes us stand out; the &ldquo;ghetto&rdquo; is formed less by attitudes on the interior and more by the imposition of a general social isolation on everybody else. In Barcelona, this has become truer in the last few years, now that many anarchists have distanced themselves from the tradition of squatting for the sake of squatting.</p>
<p>Not exactly on the turn of a dime, but within the space of a couple days, many dozens of us dropped our routines and threw ourselves wholeheartedly into the occupation&mdash;staffing the literature table, writing or finding texts and photocopying them, having conversations and arguments, joining the commissions, and organizing debates, talks, and concerts. It was an incredible feeling to find so many accomplices in the middle of a social singularity, to spend the night conversing, arguing, and analyzing the day's events, to spend the following morning writing the next round of announcements and critiques, to pass the siesta printing, and then to go back down to the anarchist tent for an afternoon and evening of distribution, meetings, and the assembly.</p>
<p>Inevitably, we exhausted ourselves. Talking with comrades who took part in the December 2008 insurrection in Greece, it sounded like people reached their physical limits in three weeks. Evidently, debates and meetings are more taxing than riots and tear gas: most of us started to burn out after a week or two. Many of those who were most active in the first week were gradually replaced by a sort of second shift of those who had taken longer to be convinced of the need to participate.<br />
</p>
<h3>A Note on Technology</h3>
<p>A reader might notice that from the vantage point of the internet, it seems like the "#Spanish Revolution" was based almost entirely around Twitter and Facebook, virtual communication that doesn't feature at all in my account. In reality, except for the occasional tech geek wandering by suggesting that we could solve all the world's problems with virtual simultaneous internet democracy, that part of the revolution simply didn't exist for me.</p>
<p>Perhaps this is not surprising, in that I don't have a cellphone and don't use Facebook. In the end, these are just tools for spreading the word, and while they do change the terrain, from a certain point of view they are superfluous. I found it easy to be in the center of important happenings and to stay informed. Toting a cellphone around would have just wasted my time and left logs of all my movements and communications for the police to browse at their leisure. For the past millennia, there have been occasions in which people gather together spontaneously in surprising numbers. As social isolation increases, networking technology helps overcome the growing distances, but it also plays a role in creating them in the first place.</p>
<p>I recall a talk in a Barcelona anarchist social center, in which we called an Egyptian anarchist in Tahrir Square via Skype. She laughed about the whole Twitter and Facebook obsession, explaining that those tools were useful but that their importance had been exaggerated by Western media.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/10b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/10a.jpg" width="500" height="333" style="margin-bottom: 2px"></a><br /><em>Mediatized democracy</em></p>
<h3>Anarchist Strategies</h3>
<p>After debating the matter with comrades nearly every day for weeks, I think those of us who chose to participate in the occupation with an anarchist critique made the right strategic choices. Our only errors come down to a question of finding the right balance between the various forms of activity.</p>
<p>The few anarchists who were there at the beginning were instrumental in blocking the signing of the Democracia Real Ya manifesto and in approving the decision not to produce any unitary manifestos. This allowed the Barcelona occupation to take on an independent character and develop according to its own needs, which endowed it with more vivacity. In Sevilla, by contrast, the occupation in Las Setas signed on to the Madrid platform from the beginning, never developed as much diversity or strength, and quickly lost what it had. And in Madrid, the assembly passed a law early on to allow no ideological symbols or ideological groups in the occupation, which was a decisive factor in preventing the anarchists there from ever setting up their own table to distribute propaganda. Accordingly, they had far less visibility, though they made a major effort to participate in the various commissions. We owe what we achieved in Barcelona in part to the fact that some anarchists went to the protest and occupation at the very beginning, despite the odious democratic rhetoric that predominated; and that they did not only go as warm bodies, but as fighters or activists with their own specific critique.</p>
<h5>&nbsp;</h5>
<h5>   We owe what we achieved in Barcelona in part to the fact that some anarchists went to the protest and occupation at the very beginning, despite the odious democratic rhetoric that predominated; and that they did not only go as warm bodies, but as fighters or activists with their own specific critique.</h5>
<p>&nbsp;</p>
<p>After more anarchists arrived on Wednesday and Thursday, there was a debate that ended in an impasse: <em>do we participate in the assembly and the commissions, or do we stay at the margins?</em> A couple of us argued that the place of the anarchists is always in the margins, and our role is to subvert the center and make sure the margins are more alive, more creative, and more interesting than the center. Fortunately, we did not win that debate, although subsequent events vindicated our position. In the end, most &ldquo;radical&rdquo; anarchists<a class="footnote" href="javascript:void(0);" onclick="return overlib('I use this term simply to separate us from those of the consensus/moderation crowd and those whose participation was not openly anarchist.', CAPTION, '[1]');" onmouseout="nd();">[1]</a> participated in various commissions, especially Content, where minimum demands and political programs were formulated. Anarchist participation basically made this commission explode, as the Trotskyists and social-democrats who previously dominated it found it impossible to get approval for their populist programs with us involved. Subsequently, the commission broke up into about a dozen sub-commissions: these included labor, ecological, and other themed ones, and also &ldquo;Self-Organization and Direct Democracy.&rdquo; This did not prevent the Trots from subsequently speaking in the name of Content and trying to delegitimize the decisions of the sub-commissions. </p>
<p>Those favoring self-organization (anarchists and autonomists) and those favoring direct democracy (radical liberals) were lumped in the same sub-commission; the latter found this appropriate, while the former considered the two terms to be diametrically opposed. Of course, the former were right, but it was a good thing the two groups were lumped together because this allowed the two camps to debate, spreading a critique of direct democracy beyond anarchist circles and giving anarchists good practice in communicating. Not to sound arrogant, but the partisans of self-organization tended to win the debates, as the democrats had superficial ideas and generally less experience in any kind of struggle.</p>
<p>By participating in the commissions, anarchists achieved multiple victories. In a few instances, we changed the form of the occupation; in many instances, we held effective debates, crystallized our analysis, and gained contact with a broader antiauthoritarian community. We also blocked several attempts to pacify or neutralize the most beautiful aspects of the occupation. </p>
<p>However, within a couple weeks most of us realized that we had made a mistake by putting so much energy into the commissions. We had effectively sequestered anarchist ideas in a few useful but relatively small spaces; we had exhausted ourselves with daily meetings; and we had allowed ourselves to be seduced by the official organizational structures, which generally proved themselves impervious to decentralization from the inside. Meanwhile, we had only realized a tiny fraction of the occupation&rsquo;s potential for self-organization. This is ironic, in that most of us were busy talking about self-organization in the appropriate commissions.</p>
<p>On a few occasions, we defied the central assembly and the commissions by organizing things on our own, starting projects in small affinity groups and working out conflicts with other projects on a case-by-case basis. We set up the literature tent, organized two or three talks, two or three debates, helped organize a concert, and helped organize an <a href="http://en.wikipedia.org/wiki/Escrache">&ldquo;escrache&rdquo;</a> protest at a nearby workplace that had just fired a worker for being pregnant. If we had only put half as much energy into the commissions, those valuable debates still would have happened, but we could have organized ten times as many informal events in the plaza, making it a reality that the margins were stronger than the center.</p>
<p>As it happened, within a week the anarchist tent had become a place where people rested between meetings&mdash;this meant that we weren't having as many spontaneous conversations with random passersby. The margins, I should clarify, were not a lifeless place waiting for anarchist leadership. There was already a great deal of activity there, much organized by hippies, but little of it had any explicit political content; thus it was less contentious, and more easily delegitimized within a dichotomy of work/leisure or culture/politics.</p>
<p>On the first Friday of the occupation, the day we set up the anarchist tent with the literature table, a vital strategic decision had to be made unexpectedly. Someone from some commission came up to tell us that the plaza was reserved for commission tents, so we had to move to the edge, basically a sidewalk area outside the entrances to the inner plaza. The guy was very clever, and used a convincing argument: if we stayed there, then the Trotskyists and Stalinists and all these other parties could also set up their tents, and we didn't want to be responsible for that, did we?</p>
<p>At the time, there were only about six of us there. I don't want to make myself too much of a protagonist; everyone telling the story from their own perspective will remember analogous episodes, because we have all made heroic efforts in these days. But the fact of the matter is, I soon found there were only two of us who opposed moving the tent, and the other one was willing to accept the majority position. I argued forcibly: who cares if all the little Marxist-Leninist parties in the world move in? The commissions and the official structures are far more dangerous. Furthermore, we were fully legitimate in setting up this tent, because we were not a pre-existing political party but a spontaneous initiative that arose from the plaza itself. Most of the people in the tent at that point had never worked together on any project before, and a couple of us had met for the first time in the plaza. <em>Not only was it our responsibility as anarchists to defy the commissions and open up the plaza for all sorts of initiatives, but it was a good thing if they subsequently tried to kick us out in the general assembly. As anarchists, we want to make existing conflicts visible, not avoid them.</em> Let them try to kick us out, and then see where this democratic revolution goes. </p>
<p>We argued face to face with various commissiocrats, sometimes being nice, sometimes being outraged, until they were convinced or exhausted. We also built some common ground with another tent they were trying to kick out, one that had been set up by some performance kids from a circus squat. If we had not won that little battle and realized the need to seek conflict <em>not only with the State but also in the social movements, which also contain the State,</em> we would have been at a severe disadvantage in everything that followed.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/11b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/11a.jpg" width="500" height="392" style="margin-bottom: 2px"></a><br /><em>Repression comes in many forms</em></p>
<p>Other strategic decisions were easier. We all agreed it was important to confront the keepers of order, such as the people from the Convivencia Commission. We started arguments where necessary, but remained willing to reconcile and be friendly if they stopped acting like cops or politicians; this actually happened on a couple occasions.</p>
<p>Our propaganda efforts also didn't need any discussion, and they were modestly Herculean. It's impossible to say how many flyers we handed out, but it may well have exceeded 30,000, plus hundreds of pamphlets and posters. Surprisingly, it was all self-financed via a donation jar at our table. Especially in the first week, passersby tossed in huge quantities of coins and even bills so we could keep printing our supposedly extremist and alienating propaganda.</p>
<p>The final strategic conflict I'll detail involved criticizing allies who were involved in the centralization of the meetings. Our criticisms were harsh at times, and they strained more than a few friendships, but I think it was absolutely necessary. By widely posting the accusation that the assembly was being manipulated by Trotskyists and left Catalan politicians, we put these people on the defensive and limited their activity. The same approach was harder with the DRY activists, unfortunately, because they were previously unknown and they were in the middle of the whole thing from the beginning.</p>
<p>Meanwhile, by strongly criticizing the consensus activists for facilitating this manipulation and recreating the State, we made visible an absolutely vital line of conflict, deflating the various excuses that hid authoritarianism within questions of process and inefficiency. This latter group, the consensus activists, mostly had good intentions, and some were in fact comrades, so they were genuinely sensitive to criticism. The results of our attempts to criticize them will surface in the coming months as they evaluate their own intervention in this phenomenon and we continue criticizing them. It is necessary that as soon as possible, everyone who honestly desires freedom recognize that democracy must be destroyed in all its forms. </p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/13b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/13a.jpg" width="500" height="377" style="margin-bottom: 2px"></a></p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/14b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/14a.jpg" width="500" height="333" style="margin-bottom: 2px"></a></p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/15b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/15a.jpg" width="500" height="332" style="margin-bottom: 2px"></a><br /><em>This is what democracy looks like: Friday, May 27, Pla&ccedil;a Catalunya</em></p>
<h3>What We Learned</h3>
<p>We can derive a number of lessons from this experience, many of which are still being digested.</p>
<p>For me, the first is this: <em>there can be no more excuses for mass assemblies</em> moderated by consensus specialists. It is important for collectivities to come together; when this happens, it is important. But the only mass organizational form that can exist without being imposed is that of an <em>encuentro</em>, an encounter, where people speak their minds or share ideas or ask for help on initiatives that they are starting without needing anyone's permission. Within this encounter, there can be individuals and affinity groups, people involved in formal (nonparty) organizations or informal federations, or whatever. The whole question of formality or informality is a distraction&mdash;it doesn't matter, it only comes down to personal taste. From an anarchist viewpoint, the only necessity is that there be no decision-making body that has more legitimacy than all the others. A social movement is essentially an attempt by society to be reborn out of the void of capitalist alienation. We should not have to adhere to any single organizational form in order to fully participate in the social movement, because every single one will exclude certain kinds of people.</p>
<p>In the past, the CNT played this role. To participate in the struggle in Barcelona, you practically had to work within the CNT, and they screwed it up something awful. It would be a similar mistake to grant legitimacy to a mass assembly, regardless of whether it uses consensus or voting, because depending on the time and location of the meetings, how long they last, whether there are chairs to sit in or whether the space can be accessed by handicapped people, some people will be excluded. Even if you could design the perfect meeting form and rewind capitalist development to recreate a proletariat that all went to work and went to bed at the same time, there would still be exclusion, because some people just don't do meetings, while others have large crowds and speechmaking in their blood. The only answer to this is to recognize a web of decision-making structures and organizing forms with equal legitimacy, destroying once and for all the divide between public and private.</p>
<p>Secondly, we learned again what makes a good intervention: <em>presence plus critique.</em> Presence means being there, but it also means participating, becoming a material and integral part of what is going on. Critique means not leaving your brain at home because you think you're going to scare people off with your anarchist ideas; it means expressing yourself, and also listening, and evaluating your own behavior.</p>
<p>I had a chance to compare our experiences with a failed anarchist intervention in another city that confirms this point. Some comrades went to the encampment there just as warm bodies, without criticism. Others went provocatively, snubbing everything and everyone and leaving when they got a bad reaction, deciding not to come back because it wasn't a comfortable space for them. It strikes me that these two opposite approaches are complementary. Both are based on avoiding personal discomfort.</p>
<h3>Some further lessons:</h3>
<p><em>People are situational, not sovereign.</em> This same idea seemed to be confirmed by the Greek experience. With the possible exception of a few Nietzschean superbeings, people are not sovereign individuals who live according to their opinions. Rather, people respond to their situations. Accordingly, the same person who has little time for an anarchist text on a normal day of the week will stop and read it and fantasize with you about overthrowing the State if you happen to meet them in the unexpected terrain of a spontaneous collectivity. The next question to explore is to what extent we can plant seeds, in the boring moments, that will stay with people and have the chance to sprout when those people enter the unpredictable terrain of a rupture.</p>
<p><em>Collaboration between the various sects of libertarians was vital. </em> Perhaps affinity groups are overrated: in the end it did not matter so much whether a fellow anarchist agreed with you on the question of the existence or nonexistence of the proletariat; it mattered more whether we could get along and communicate. It was a great advantage to have many different perspectives mixing, different strategies being developed, and different people being drawn to participate in different ways. The anarcho-syndicalists made a great effort to be present in many of the commissions, and it was funny and instructive seeing them participating in the same popular debates with nihilist and insurrectionary anarchists. They also brought with them the important tradition of the CNT, which granted legitimacy to anarchist participation on the whole.</p>
<p><em>Decentralization is not the same as dispersal. </em> A mass gathering point such as Pla&ccedil;a Catalunya can give us a sense of collective strength, which dispersal would dissipate. Decentralization means not utilizing a unitary organizational structure with central nodes. It is a question of mode, not scale. Many people, including some anarchists, misunderstood the anarchist proposal for decentralization as a proposal to shift activity to the neighborhoods. While this was in fact part of what most anarchists were proposing, it is equally possible to transplant centralized structures at a smaller scale to all the neighborhood assemblies. Fortunately, the Barcelona neighborhood assemblies, which formed around the September general strike, had already defeated an attempt to centralize them within the umbrella organizing structure that arose around the strike. They preferred their autonomy. As such, they were a favorable terrain for anarchists, especially where we had already been participating in our neighborhood assembly. It was harder for grassroots politicians to take them over, and harder to impose an ideological unity, because we already had a point of unity: we lived in the neighborhood together, and we had no pretensions of all thinking the same way. </p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/16b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/16a.jpg" width="500" height="375" style="margin-bottom: 2px"></a><br /><em>An open meeting in a Barcelona neighborhood, May 25</em></p>
<p><em>When we express anarchist ideas honestly, humbly, and passionately, it can reveal that many of those who remain silent are already partially on our side. </em> Inertia and common values work against us and favor the populists and democrats, but anarchist ideas almost always win a debate because they speak to an inalienable impulse towards freedom that exists in everyone who still has a heart. The important thing, then, is to participate in the debate, as long as that debate does not legitimize official political channels but takes place between ordinary people. It is no coincidence that the dogmatic pacifists boycotted the debate we organized about nonviolence. They're not interested in a debate, but in imposing their practice.</p>
<p><em>Nonviolence is not a cultural peculiarity, but a real danger everywhere democracy exists. </em> I thought that with its Mediterranean culture and its long, living history of forceful struggles, Spain would never have a problem with nonviolence. But in a period of a few years, it has appeared with a strength that could rival the pacifism in the UK or US. And these pacifists do not generally emerge from a trajectory of the historical nonviolent struggles in Spain, such as the antimilitarist movement. Rather, they have been created out of whole cloth by the democratic context itself; the ground was prepared, in my mind, by the tolerance of leftist, democratic, rights-based discourses in the antagonistic social movements of the last couple decades. People who identify as peaceful should be heartily encouraged to make themselves at home within our struggles. Nonviolence, on the other hand, must be treated with contempt until it is made synonymous with cowardice and snitching, and decent pacifists abandon ship to never again be confused with cop-lovers. By continuing to use the dichotomy of nonviolence and violence, and arguing whether or not our actions qualify as violent, we are only empowering them. Violence does not exist: it is a vague and moralistic category. Only nonviolence exists, and it means selling out, running away, and censoring other people's struggles.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/17b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/17a.jpg" width="500" height="333" style="margin-bottom: 2px"></a><br /><em>Barcelona, May 27</em></p>
<p><em>Direct democracy is just representative democracy on a smaller scale. </em> It inevitably recreates the specialists, centralization, and exclusion we associate with existing democracies. Within four days, once the crowds exceeded 5,000, the experiment in direct democracy was already rife with false and manipulated consensus, silenced minorities, increasing abstention from voting, and domination by specialists and internal politicians.</p>
<p>In a story worthy of Kafka, we were trying to schedule a debate and we wanted to let those at the Activity Commission know. The kid at the table looked down at his form, a crappy little piece of paper written up in ballpoint pen, and told us we couldn't have our event in the spot where we wanted. &ldquo;Why?&rdquo; I asked, getting ready to go ballistic. The response was far more pathetic than I had expected. &ldquo;Because our forms are divided into different columns, see, one column for each space in the plaza, but that space over by the staircase, well that's not an official space.&rdquo; &ldquo;That's okay, we don't mind, just write it down.&rdquo; &ldquo;But, but, I can't. There isn't a column for it.&rdquo; &ldquo;Well, make a column.&rdquo; &ldquo;Um, I can't.&rdquo; &ldquo;Oh Christ, look, which one's open&mdash;look, here, 'Pink Space,' just write our event down for the 'Pink Space' and when the time comes we'll just move it.&rdquo; Within two weeks, without any prior training, the Spanish Revolution had created perfect bureaucrats!</p>
<p>Some radical anarchists put too much trust in the commissions. They were only useful as spaces for debate and as spaces to subvert. For example, in the beginning, the assembly decided not to release unitary manifestos speaking for everyone. Subsequently, in the commissions, anarchists had to fight proposals for minimum demands and manifestos every single night. Finally, there was a commission meeting with no anarchists present, and the minimums were passed through the commission and subsequently ratified by the general assembly, which ratified nearly every proposal passed before it. On the other hand, the anarchist proposal to decentralize the assembly was voted on twice, and each time achieved overwhelming support, but curiously was defeated on technicalities both times. This action demonstrated that we were right, we had lots of support, and the assembly was a sham&mdash;that, in itself, was a victory. But direct democracy cannot be reformed from within. It has to be destroyed.</p>
<p>In another example of the unsuitability of these organizational forms, the attempt to organize a simple debate about nonviolence almost failed because the Self-Organization and Direct Democracy Sub-Commission needed days to debate and consense on exactly how they wanted to do it. In the end, two people decided to ignore the commission, and joining with another anarchist who was not participating in Self-Organization, the three of them organized a successful talk and debate in just a day, accomplishing what a group of fifty people had failed at over the course of a week.</p>
<p>Finally, we learned our own limits. After two weeks of meetings, debates, and grassroots bureaucracy, some of us were ready to shoot ourselves. We were exhausted, and we had made the grave error of dropping all our other projects and actions. This demonstrated a necessary flexibility, but it also meant that during these most critical moments, radical anarchist actions weren't happening in the streets. It always felt vital to be in the meetings, in case something should go wrong, but we could have moderated our participation and devoted some energy elsewhere.</p>
<p>In this respect, it became obvious that we lack people who are comfortable with public speaking. This is a vital skill we need to develop collectively. Often, people with antiauthoritarian critiques made up a large proportion of a meeting, but we just sat through it all and listened to bullshit because none of us wanted to take the microphone. In the second open assembly in the Clot neighborhood, I started to get depressed because it was exhibiting none of the antiauthoritarian sentiment as the first one. Populist inertia was steamrolling us. Finally, I took the mike and launched into a ten-minute speech urging a focus on long-term revolutionary goals and self-organization, and slamming reformism, pacifism, and attempts at a homogenous unity. A huge part of the crowd cheered, and afterwards more people were motivated to get up and express similar sentiments, shifting the direction of the whole meeting. At the end, half a dozen people, from grandmothers to students, thanked me for my contribution, while others came over to start arguments that ended with them either convinced of or at least respecting the anarchist position. I didn't enjoy speaking or receiving compliments&mdash;it made me feel nervous and self-conscious&mdash;but I wonder: if I hadn't, would the meeting have run its course with the uninterrupted illusion of a reformist majority?</p>
<p>Now that the Pla&ccedil;a Catalunya occupation is disappearing, the struggle will continue in the neighborhoods, in the radical unions, in preexisting affinity groups, and in the new relationships that have been formed during these days. Time will tell, but I suspect we have made a great leap forward by participating in the neighborhood assemblies, meeting new accomplices, and winning ourselves a great social visibility in spite of a hostile democratic environment. The real revolution is a long time in coming, but its sputtering attempts to come to life are plainly visible in these surprising, pathetic, exhausting, beautiful moments, as long as we have the fortitude to be there.<br />
</p>
<h3>Further Reading</h3>
<p><strong>Two of the &ldquo;official&rdquo; sites:</strong><br />
<a href="http://www.spanishrevolution.es" target="_blank">www.spanishrevolution.es</a><br />
<a href="http://acampadabcn.wordpress.com/" target="_blank">acampadabcn.wordpress.com/</a></p>
<p><strong>Pages with some anarchist perspectives:<br />
</strong><a href="http://www.alasbarricadas.org/noticias/?q=node/17815" target="_blank">www.alasbarricadas.org/noticias/?q=node/17815<br />
</a><a href="http://barcelona.indymedia.org" target="_blank">barcelona.indymedia.org</a><br />
<a href="http://terracremada.pimienta.org/" target="_blank">terracremada.pimienta.org/</a><br />
</p>
<p>&nbsp;</p>
<h2 id="c" name="c">Appendix: <br />
Translations from Original Texts <br />
in Catalan and Spanish </h2>
<p>&nbsp;</p>
<h3>&ldquo;Why We Don't Lay Claim to Democracy&rdquo;</h3>
<p><em>Possibly the first anarchist text to come out of the occupation, this was published alongside &ldquo;And after Sunday, what then?&rdquo;</em></p>
<p>We participate in the struggles against home repossessions, against evictions, against the cutbacks and all the abuses we suffer daily. We create social centers, libraries, newspapers with counterinformation and analysis, community gardens, and specific events. We practice direct action, attacking the symbols of our oppressors such as the police, the politicians, and the banks. <strong>For all these reasons, we do not lay claim to democracy.</strong></p>
<p>We believe that it is only necessary to lay claim to freedom, without establishing limits to our desires. Frequently it is thought that &ldquo;freedom&rdquo; and &ldquo;democracy&rdquo; are synonyms, but democracy always leads to an even stronger social control&mdash;it is dictatorship with other weapons, it is the State that tricks us into participating in our own domination. <strong>There is no single democracy in the entire world where the people are free, and this is not a question of corruption but rather of the normal functioning of democracies.</strong></p>
<p>Like all kinds of states, democracy is based on centralization and the monopolization of decision-making. It doesn't matter if we all participate in these decisions, because massive assemblies are easy to manipulate. The person with the microphone, the people who want to lead, will always be within the majority and the minority will always be silenced. <strong>In Pla&ccedil;a Catalunya we are creating a real democracy and this is our great mistake.</strong> We are reproducing the same roles that exist in parliament, we are creating the progressive politicians of tomorrow. </p>
<p><strong>We imagine a Pla&ccedil;a Catalunya with a diversity of assemblies, where everyone can start initiatives without passing through a centralized and cumbersome assembly,</strong> thus giving everyone the experience of participating in a process of autogestion instead of being spectators. We can organize millions of initiatives with greater fluidity without having to pass through the commissions, which are easily dominated by specialists. We don't need others to tell us what we can do.</p>
<p>We are not satisfied with the single voice of the centralized assembly, because it's hardly any better than the daily silence of capitalism. We want a plaza full of voices, of assemblies, of conversations. We're truly interested in creating links between all of us, but we'd like to do it in another way: through solidarity between the struggles and not through the homogenization of our ideas. </p>
<p><strong>Let's destroy democracy and spread freedom!</strong></p>
<p>&nbsp;</p>
<h3>&ldquo;And After Sunday, What Then?&rdquo;</h3>
<p>In Tahrir Square, after bringing down the dictatorship, people realized that it was only the beginning. Even though none of it appeared in the media, afterwards there was a whole series of strikes and occupations in factories and other places. Bringing down the dictatorship was just one step forward for opening the struggle and keeping the State from shooting them all down. </p>
<p>In Pla&ccedil;a Catalunya, if we bring down the monopoly of the political parties and the electoral farce, what will we have accomplished? Nothing more than to open new possibilities to struggle and achieve what we really want: the autogestion of our lives and the end of exploitation and social hierarchies. </p>
<p>We want to collectivize the social wealth, as our grandparents did in the revolution of 1936, and in the insurrections of Figols, Casas Viejas, Asturias, and the Hospitalet Commune in the years before. The dictatorship destroyed these struggles, but not our desire for freedom. Later, the democracy has maintained and intensified the social and economic changes made by the dictatorship.</p>
<p>If we end this circus of politicians, we will have the opportunity to realize our dream of self-organization and collectivization. Without a doubt, these implies a hard struggle with much determination, responsibility, and perseverance if we really want to solve the problems we suffer. They will call us violent, they will repress us, they will try to assign us leaders and new politicians. </p>
<p>Therefore it is indispensable:<br />
<em>-never to pact with the rich and powerful</em><br />
<em>-to support the prisoners created by the repression</em><br />
<em>-to respect diverse paths of struggle</em><br />
<em>-to seize the streets, and the responsibility to sustain ourselves through mutual aid</em></p>
<p><strong>It is not easy, but it is possible. The path is long and as long as our dream of liberty remains alive, we will be more alive than ever.</strong></p>
<p>&nbsp;</p>
<h3>&ldquo;Grave Errors of the Protagonists of the Central Assembly&rdquo; </h3>
<p><em>This flyer appeared on the first Friday of the occupation.</em></p>
<p><em>&ldquo;Patience, patience &ndash; this isn't easy.&rdquo;</em> [Words often spoken by the meeting moderators] The forms and structures taken by the central assembly are not something natural, but rather a specific choice towards centralized instead of decentralized structures. Even though many of the organizers are surely reproducing what they already know in good faith, the effect and the purpose of centralization is to create a structure in which the majority cannot participate, they can only watch and vote. </p>
<p><em>&ldquo;We are creating a space for expressing ourselves.&rdquo;</em> Lies. With a central assembly, they are silencing 9,999 spaces for expressing ourselves, replacing them with one single space. Didn't they notice that in the hours before the Central Assembly there was a multitude of meetings, conversations, assemblies, and initiatives not controlled by anyone?</p>
<p><em>&ldquo;Everyone agree? Good, consensus.&rdquo;</em> It is evident that in the majority of votes in the General Assembly, it is the abstaining vote that wins. Only four days of real democracy and we've already reproduced everyday democracy and massive apathy. They are killing the revolution with boredom.</p>
<p><em>&ldquo;There's no time to debate here, this has to pass through the commissions.&rdquo;</em> But when there are thousands of people in the plaza, when in the meetings only the people closest to the speaker can hear, when some commissions last until five in the morning, there is no possibility to debate in the commissions either. A structure has been created in which delegation is necessary. The democracy with which we are all fed up has been reproduced.</p>
<p align="center"><strong>How to Manipulate an Assembly</strong></p>
<p>For he who has the microphone and announces the proposal, it is extremely easy to generate the desired consensus.</p>
<p>--Always propose the desired option in the first position. E.g. &ldquo;The proposal is to do a silent march to Pla&ccedil;a Sant Jaume. Everyone in favor?&rdquo; No one wants to be in the minority, so those who aren't in favor will abstain from voting, so there will be the appearance of consensus.</p>
<p>--Avoid debate on your ideological foundations. E.g. &ldquo;The proposal is to carry out a nonviolent actoin against the banks.&rdquo; Nonviolence is never debated, but imposed, by making exclusively pacifist proposals so that the options will always be doing nothing, or doing something nonviolent. You can't be a future politician if you don't know how to control the rage of your flock. This is what democracy is all about.</p>
<p>--When you monopolize the microphone to make speeches and sway the masses, it's best if you don't use the exact same gestures as Lenin did, so as not to reveal your true intentions.</p>
<p>--Never, under any circumstances, allow decentralization or spontaneity to flourish, because then your loyal masses would be replaced with a multitude of self-organized, creative, and liberated people.</p>
<p align="center"><strong>Concrete Proposals for a Self-Organized Plaza</strong></p>
<p>--Replace the monopoly of the commissions with a multiplication of organizing groups. Multiple kitchens, multiple communication and extension groups, with more autonomy, more fluidity, more possibility to develop diverse forms for diverse tastes, more space for everyone's participation without creating silenced minorities. These groups would communicate among themselves, collaborating when they consider it opportune. </p>
<p>--Convert the Central Assembly into a general encounter for exchanging information and resources, and generating a collective environment and consciousness. Here one could make proposals in order to seek support and allies, but without obliging everyone to sign on. If we don't have spokespeople, we don't need unified texts either. If we don't have leaders, we don't need homogenized actions. What unites us is the fact that we are here and we are self-organizing our resistance. </p>
<p><strong>Down with centralization! Up with self-organization!</strong></p>
<p>&nbsp;</p>
<h3>&ldquo;The Greatest Violence Would Be Returning to Normality&rdquo;</h3>
<p><em>This flyer appeared about a week into the occupation.</em></p>
<p>In Pla&ccedil;a Catalunya we are already thousands. We have taken the center of the city. We have made it ours, and with our determination we have opened a fault line of indignation in the wall of consent and social resignation. </p>
<p>Now we only have two options: allow this crack to close up, losing a unique opportunity for a veritable social change, or open it as much as we can, widening it until it reaches the very foundations of our misery and exploitation.</p>
<p>If we want to get somewhere, if we want everything that we denounce and disdain to disappear, we must exceed the limits of the plaza. We must exceed the limits of the very legality which yesterday told us we could not occupy it, and today tells us we cannot leave it, that we cannot touch the normality that surrounds it.</p>
<p>We must disobey the voice of Power when it tells us that blocking a street is violent while it blocks human lives with layoffs and exploitation, when it tells us that confronting the police is violent while they torture immigrants and and dissidents in their jails, when it tells us that attacking a bank is violent while it leaves whole families on the street for not paying the mortgage. </p>
<p>We must disobey, because no revolution has ever been carried out while respecting the laws of the powerful. We must disobey, because the greatest violence would not be to continue to act illegally, but rather to pass up the opportunity to end once and for all the abuses and all the massive violence this society produces. </p>
<p>We must take the streets, we must extend the revolt to all the neighborhoods and every field of life.</p>
<p>We don't want just a plaza, we want the whole city. </p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/barc/18b.jpg" rel="lightbox[barc]"><img src="https://cloudfront.crimethinc.com/images/barc/18a.jpg" width="500" height="707" style="margin-bottom: 2px"></a></p>
<p>&nbsp;</p>
<h3>&ldquo;Assemblies, Democracy, and Capitalism&rdquo;</h3>
<p><em>This text appeared on a poster produced about a week into the occupation.</em></p>
<p>The democratic form is the most perfected political system that Capital has encountered for its development and universal implantation. <strong>There is no practical criticism of democracy without a criticism of capitalism.</strong> To accept or attempt to reform capitalism implies accepting or trying to reform its most appropriate political form. Democracy separates political decisions from the rest of social life. It foments the illusion that we are equals before the law and the institutions, while obscuring the fact that while it offers these possibilities they will only be a reality for those who can employ them. This separation avoids class antagonism or gender differences, reducing conflicts to an apparently neutral sphere in which it will be possible to achieve equality via discussion and consensus among the affected parties. And it is this mechanism that brings with it a generalized demobilization, in which any movement that is oppositional in the beginning can be integrated through dialogue between representatives.</p>
<p>Nonetheless, the criticism of democracy cannot be reduced to the manner in which decisions are made. Democracy, whether direct or representative, is the supremacy of means over ends, and the dissolution of potentialities into that which is purely formal. If a movement advances and confronts Power, it is not democratic. But if the conflict or the movement can be compatible with arbitration and conciliation, then it is normal that form and procedure should be the most important considerations. Organizing an assembly according to the proper norms becomes more important than what the assembly decides. <strong>Those who privilege procedures of administration are condemned to creating an administrative apparatus, instead of resituating discussion within the content of our experience, our words and our actions.</strong> Reality is inverted, and it is forgotten that revolution is not only a question of form. It is the nature of this change we must insist upon. To create a world without money, without the exchange of commodities, without the buying and selling of labor, without companies as competing poles of value accumulation, without work being separated from the rest of our activities, without the State, without a political sphere that is specialized and isolated from our social relations. </p>
<p>&nbsp;</p>
<h3>&ldquo;Important Information Regarding <br />
a Possible Eviction of the Plaza&rdquo; </h3>
<p><em>This was the official text put on the encampment website on May 20 and handed out among participants.</em></p>
<p>1) Regarding political and electoral posters: removal of posters that urge voting for any political optoin [including blank or null votes] will now begin [in order to comply with Spanish law regarding the &ldquo;Day of Reflection&rdquo; before Election Sunday].</p>
<p>2) In the case of police intervention, we will all sit down in the plaza. It is our duty to show our ID and our right to politely ask for the badge number of the police officer. IMPORTANT: Once seated on the ground in the plaza, make use of the LEGAL TEAM, identified by their reflective jackets, to act as mediators between the plaza and the police. (The LEGAL TEAM is a defense commission belonging to the Bar Association).</p>
<p>3) We define ourselves as a gathering [to attempt to dodge the law prohibiting protests in the days before the election].</p>
<p>4) In the case of arrest NEVER make a statement in the police station. We are providing all of you with the phone number of the LEGAL TEAM so they can give you legal aid.</p>
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1] I use this term simply to separate us from those of the consensus/moderation crowd and those whose participation was not openly anarchist.
</p>
</div>