<h6 align="right" style="margin-right: 0px"><em>This story accompanies <a href="/texts/recentfeatures/border.php">Designed to Kill: Border Policy and How to Change It</a>,<br />
an analysis exploring how the actual effects and objectives of<br />
US border control policy differ from its ostensible purpose.</em></h6>
<h1>Four Stories from the Border</h1>
<p>&nbsp;</p>
<p>We were walking up a small canyon. One of my companions was doing very loud and rather florid call outs: &ldquo;!COMPANERAS! &iexcl;COMPANEROS! &iexcl;NO TENGAN MIEDO! &iexcl;TENEMOS AGUA, COMIDA, Y MEDICAMIENTOS! &iexcl;SOMOS AMIGOS! &iexcl;NO SOMOS LA MIGRA! &iexcl;ESTAMOS AQUI PARA AYUDARLES! &iexcl;SI NECESITAN CUALQUIER COSA: GRITENOS!&rdquo; The great majority of the time no one is there to hear these call outs.</p>
<p>We turned a corner in the canyon, and there were about thirty five people: men, women, children, and teenagers, dressed in all blacks, browns, and desert tans, dead silent and taking up a very small amount of space. &ldquo;Holy shit, um, did you hear us coming?&rdquo;</p>
<p>&ldquo;Yes, we heard you coming.&rdquo; It was very hot. We gave them lots of water, food, socks, and treated a number of blisters and sprained ankles. They were all from Guatemala. They said they had been together every step of the way. As we prepared to part ways, one of them handed us a large sack of money&mdash;pesos and dollars.</p>
<p>&ldquo;Um, no, you don't understand, you don't have to give us any money, this is why we are here.&rdquo;</p>
<p>&ldquo;No, you don&rsquo;t understand,&rdquo; he said. &ldquo;We found this money at a shrine in the desert. We decided that it was not doing anybody any good there, so we took it. If the migra catches us they will take it from us, and it will never do anybody any good. We want you to take this money, and to use it to help other migrants.&rdquo; We carried out their wishes.</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/border/7b.jpg" rel="lightbox[border]"><img src="http://thecloud.crimethinc.com/images/border/7a.jpg" width="500" height="375"></a></p>
<p>We got a call from the Mexican consulate. A man's family had contacted them. He had been missing for nine days. The last time anybody had seen him he was somewhere near a small body of water with a fractured rib. They thought that he was in our area somewhere. For about a week we searched and searched, but we never found him. His brother had papers. He came up, with a horse. He combed the desert on horseback for another week, and eventually found his brother's body.</p>
<p>Two weeks later a man came walking into camp. He was carrying an almost empty gallon jug of water with our markings on it in one hand, and a white shirt tied to a long stick in the other. He stuck the jug under my nose: &ldquo;This water saved my life! I was praying to Jesus for water! I was sure I was going to die, and I found this water in the desert! I think Border Patrol leaves it on the trails for people!&rdquo;</p>
<p>&ldquo;No, man,&rdquo; I said, &ldquo;Border Patrol couldn't give a shit if people live or die. We left that water.&rdquo;</p>
<p>&ldquo;Those bastards,&rdquo; he said. &ldquo;I&rsquo;ve been waving this flag at their helicopters for three days. They just fly on. When you want them they're nowhere to be seen, and when you don't&mdash;there they are.&rdquo; I checked the markings on the bottle. It had been dropped two weeks earlier, at an unusual location we had only gone to because we were looking for the man who died.</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/border/8b.jpg" rel="lightbox[border]"><img src="http://thecloud.crimethinc.com/images/border/8a.jpg" width="500" height="752"></a></p>
<p>One day my colleague and I drove way out into the middle of nowhere to drop water in the desert. Four days later it was time to check on it. On our way out to the spot we saw a man sitting by the side of the little dirt road. He had a ripped up piece of blanket tied around one knee. &ldquo;How are you doing?&rdquo; I asked him.</p>
<p>&ldquo;Badly,&rdquo; he answered. &ldquo;Look at this.&rdquo; He pulled up his pant leg to reveal a black, swollen, thoroughly broken ankle.</p>
<p>&ldquo;That&rsquo;s bad,&rdquo; I said. &ldquo;You need to go to the hospital.&rdquo;</p>
<p>&ldquo;Yes,&rdquo; he said. &ldquo;Look at this.&rdquo; He pulled his shirt aside.</p>
<p>&ldquo;OH SHIT!&rdquo; my colleague and I shouted in unison. He had a large open chest wound, bloody, half scabbed over and oozing pus. &ldquo;You need to go to the hospital right NOW! What happened?&rdquo;</p>
<p>&ldquo;Four nights ago I was walking with three other men through those mountains over there. I took a blind fall, ten or twelve feet over a cliff. I broke my ankle and sliced my chest open on a rock. They carried me down from there all through the night. In the morning we saw you drive by, but we were still too high, we couldn't get to the road in time. When we got here they left and said they were going to find help. I haven't seen them or anybody else since then.&rdquo;</p>
<p>&ldquo;You've been here four days?&rdquo; It had been well over a hundred degrees every day. &ldquo;Have you had any food or water?&rdquo;</p>
<p>&ldquo;Food, no. A couple times a day I crawled over to that pond. I didn't want to get very far from the road in case someone drove by.&rdquo;</p>
<p>A hundred yards from the road there was a dried up cattle pond, at best an inch deep, mostly manure and sludge. There were about a dozen sets of drag marks where he had crawled between the pond and the road. We drove him to the ambulance. He was remarkably stoic about everything. I asked him if the bumpy road was hurting his ankle. &ldquo;No.&rdquo;</p>
<p>&ldquo;Your chest?&rdquo;</p>
<p>&ldquo;No.&rdquo;</p>
<p>&ldquo;You didn't get sick from the bad water?&rdquo; I was sure that he would have died if he had.</p>
<p>&ldquo;No.&rdquo; The ambulance took him to the hospital and I never heard from him again.</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/border/9b.jpg" rel="lightbox[border]"><img src="http://thecloud.crimethinc.com/images/border/9a.jpg" width="500" height="375"></a></p>
<p>We got a call from our neighbors. A man had crawled up to their door. He was in terrible shape. He could barely stand or talk. He had not eaten or drunk water for three days, and he hadn't urinated for a day and a half. It had been deadly hot. We tried to give him fluids, but he would vomit immediately every time.</p>
<p>&ldquo;This is really bad,&rdquo; I told him. &ldquo;You need an IV. We don't have one here. You may have kidney damage. We can't treat that. You need to go to the hospital. They will deport you after they treat you, but if you don't I am really afraid that you might die.&rdquo;</p>
<p>&ldquo;No,&rdquo; he said. &ldquo;Don't call them.&rdquo;</p>
<p>&ldquo;Please, I understand, but&mdash;&rdquo;</p>
<p>&ldquo;No. Don't call them.&rdquo;</p>
<p>&ldquo;But&mdash;&rdquo;</p>
<p>&ldquo;No.&rdquo; We laid him down. After several hours he managed to keep down a tiny amount of water. We nursed him through the night as best we could, giving him water every hour or so. By the morning he was able to hold it down without vomiting, and he finally urinated a little bit. He could barely sit up, but he was able to talk again.</p>
<p>&ldquo;I&rsquo;ve never seen anyone so sick refuse to go to the hospital,&rdquo; I said. &ldquo;What happened to you?&rdquo;</p>
<p>&ldquo;I&rsquo;ve lived in the states for eighteen years,&rdquo; he told us. &ldquo;I&rsquo;ve never been in any trouble. I've never even gotten a parking ticket. My wife and I finally paid off our house. All my children are here. So are my grandchildren. For work I take care of elderly people. Six months ago I had an accident and I broke my back. I was in bed for nearly four months. I was working again, and I got pulled over. The policeman said that I didn't use my turn signal. I've been here eighteen years and I never got pulled over once. I&rsquo;ve always been very careful. They sent me to a detention facility. They kept me there for fifteen days, with chains on my hands and feet. They fed us peanut butter and crackers three times a day. I was shackled the whole time. They dropped me off across the border with nothing. I had nowhere to go. I hadn&rsquo;t been there in so long. I left with a group that night. They drove us way out into the desert. We walked for three days. I couldn&rsquo;t keep up any longer. I&rsquo;m not a young man any more. They left me out there with no food or water. I was by myself for three more days. I had no idea where I was. I drank dirty water from a cattle pond, and it made me even sicker. I was hearing voices and seeing things. When I saw that house up there I didn't know if it was real or not. I kept walking towards it. I thought that I might have already died. I can&rsquo;t do this again. My whole life is here. There is nothing for me in this world if I can't make it back. If I die I&nbsp;die. This is my only chance. I have to keep trying.&rdquo;</p>
<p>He recovered slowly. He called us a week after he left, from his house. A month later he and his wife sent down a huge package of shoes and food and clothing to give to other migrants. &ldquo;I almost always stay inside,&rdquo; he said. &ldquo;I can&rsquo;t afford to risk being sent back again. I suffered so much out there. I'm still healing. I know that&nbsp;I could never&nbsp;make it another time.&rdquo;</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/border/10b.jpg" rel="lightbox[border]"><img src="http://thecloud.crimethinc.com/images/border/10a.jpg" width="500" height="667"></a></p>
<p>&nbsp;</p>