<p align="center"><a href="http://thecloud.crimethinc.com/images/brazilpt1/1b.jpg" rel="lightbox[breakwith]"><img style="margin-bottom: 5px" src="http://thecloud.crimethinc.com/images/brazilpt1/1a.jpg" width="500" height="454" title="The June 2013 Uprisings in Brazil, Part I"/></a></p>
<h6 align="right" style="margin-right: 0px"><em>The opinions, analysis, gossip, conspiracy, and witchcraft expressed herein do not purport to represent all the groups and positions in the uprisings that occurred throughout Brazil in June 2013. We do not want to erase the power of difference, the capillary plurality and molecular diversity of experiences, tactics, and political perspectives. We do not want to impose a final analysis on the uprisings. These analyses reflect only the critical perspective of an anonymous, rhizomatic grupelho (faction) active in the uprisings of Goiânia, Pôrto Alegre, Belo Horizonte, São Paulo, and Rio de Janeiro. We hope to describe what occurred from a radical, anti-hegemonic, and subaltern point of view. We also aspire to convey a bit of the magic from the streets, barricades, favelas, and prisons of Bra$il, to fuel the ongoing struggles in Turkey, Egypt, Chile, Greece, Spain, Italy, the USA, and elsewhere in the Globalitarian Empire.</em></h6>
<h2>Timeline of Events</h2>
<p>In São Paulo, the first demonstration of this new wave of revolt against the transit fare increase took place on June 6, 2013. The fare had been increased by 20 cents. This meant that a single transit cost a third of the Brazilian minimum wage, forcing some workers to skip lunch to afford it. The MPL (Movimento pelo Passe Livre: Free Pass Movement) had called the June 6 demonstration far in advance to protest the fare increase; a relatively wide coalition backed it, including left-wing and center-left parties, social movements, and the student movement. The most radical groups anticipated it with fear and excitement: fear that the parties might get traction in the movement, and excitement about the participation of the popular classes1 and more radical groups. The demonstration in São Paulo occurred in the wake of street clashes with police a few weeks earlier in Pôrto Alegre and Goiânia, in weekly mass demonstrations, bringing not only more radical sectors but also popular and poor strata to the streets.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/2b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/2a.jpg" width="500" height="363"/></a>
<em>Demonstrations against the increase in Goiânia in late May: “We will not Pay” painted on a burning bus.</em></p>
<p>The first demonstration in São Paulo fulfilled expectations. About 5000 people took to the streets. Leaving from the Viaduto do Chá across from the city hall of São Paulo, the march passed by the most important avenues of the city. From the first moment, graffiti appeared all over the walls; dumpsters were dragged into the street and burned, disrupting and distracting the military police. Within an hour, a confrontation with police erupted that lasted until the end of the demonstration. The police attacked with tear gas, pepper spray, and stun grenades. The demonstrators retaliated with projectiles and erected burning barricades of trash and subway turnstiles. After this battle, the demonstration proceeded to Paulista Avenue (one of the city’s busiest and most important streets), closing it in both directions. Again, garbage burned in the streets. Shops, corporate franchises, banks, and subway stations were transformed by means of paint and projectiles. The losses inflicted to the São Paulo subway were estimated at US $40,000 that day. </p>
<iframe width="500" height="281" src="//www.youtube-nocookie.com/embed/BlHjNnZjNyw?rel=0" frameborder="0" allowfullscreen></iframe><br/><br/>
<p>São Paulo had not seen such fierce demonstrations since the protests against the Free Trade Area of the Americas negotiations over a decade before. Another demonstration was scheduled for the next day.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/3b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/3a.jpg" width="500" height="309"/></a>
<em>Demonstration in São Paulo: “If the fare do not goes down, the city will stop it!”</em></p>
<p>The same spirit marked this demonstration: graffiti on the walls, destruction of the symbols of global capitalism. Once again, the police attacked; once more, the protesters responded. A <a href="http://mais.uol.com.br/view/s70pk4i6az2h/protesto-contra-aumento-de-tarifas-tem-confronto-na-marginal-04024E1B3266E0A14326?types=A&amp;">new street battle began</a> with the police employing tear gas, bombs, and batons, and protesters defending themselves with stones, barricades, and homemade bombs. A third protest in the same mold was scheduled for the following day.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/4b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/4a.jpg" width="500" height="308"/></a>
<em>Another big demonstration in São Paulo.</em></p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/5b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/5a.jpg" width="500" height="303"/></a>
<em>Police search at the subway before a demonstration. Police arresting people with vinegar for treating the effects of tear gas and pepper spray.</em></p>
<p>The protesters of São Paulo had a few days of rest after this three-day marathon; another demonstration was scheduled for June 13. This one started around 6 pm in the square Ramos de Azevedo, in the center of the city. Protesters gathered there from 5 pm on. The group went to the square of the Republic, then walked along Ipiranga Avenue to the street of Consolação, at the corner of Roosevelt Square.</p>
<p>Now it was a whole new ball game. The previous week’s demonstrations had attracted more people, and this demo was attended by more than 10,000. Police appeared at the outskirts of Paulista Avenue, trying to block the demonstration to defend the interests of big business, who feared new reprisals from the enraged population. Riot police made a cordon and began to bombard the demonstration. Again, the manifestation retaliated with stones, built barricades, and destroyed targets associated with global capitalism.</p>
<iframe width="500" height="281" src="//www.youtube-nocookie.com/embed/UGOL2hy2J-4?rel=0" frameborder="0" allowfullscreen></iframe><br/><br/>
<p>This time, the police were stopping and searching people on the subway; even before the beginning of the demonstration, they detained more than 40 people. By the end of the evening, almost 250 had been arrested. This was clearly an attempt to criminalize and intimidate the movement by means of conspiracy charges and absurd bail costs (R$20,000).</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/6b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/6a.jpg" width="500" height="308"/></a>
<em>Demonstration in São Paulo.</em></p>
<p>Another new aspect of this demonstration was the molecularization of the revolt. As riot police increased repression, the demonstration began to dissolve naturally into small groups of 300 to 1000. These initiated new demonstrations and points of conflict all around the city center. Guerrilla battles broke out everywhere as protesters retreating from bomb-throwing police built barricades.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/7b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/7a.jpg" width="500" height="244"/></a>
<em>Protesters trying to invade the Palácio dos Bandeirantes, the headquarters of the state government of São Paulo.</em></p>
<p>The anticipation building up to the fifth major demonstration was intense. It was called for June 17. The media was buzzing. GLobo—the biggest TV company of Brazil and one of the world’s biggest—interrupted their programming to disseminate news about the demonstrations. Initially, the corporate media depicted the movement as a bunch of criminals; then, when it gained momentum, they began to make a distinction between peaceful protesters and vandals in an attempt to marginalize the more radical sectors.</p>
<p>Yet once again, the demonstration assumed a radical character. Large banks, chain stores, and department stores were beautified with graffiti; protesters nearly overran the headquarters of the state government of São Paulo, the Palácio dos Bandeirantes; busses were vandalized…
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/8b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/8a.jpg" width="500" height="376"/></a>
<em>100,000 protesters at a demonstration in Rio.</em></p>
<p>We had known that the commotion about the Military Police beating photographers, reporters, and protesters would attract a large mass—and that came true. About 50,000 people attended this demonstration. Now what we had feared was finally happening: the demonstration included the middle class, the opportunist parties, a few nationalist groups, and the extreme right wing. The middle class had bought the hetero-bourgeois media discourse: they called for pacifism, marching with Brazilian flags and singing the national anthem. The right wing was trying to take over the movement, bringing their own agenda: protesting “corruption” and calling for President Dilma to be impeached. This was the first demonstration in which there were reports of pacifist protesters attacking radical groups. Anarchists who were spray painting in a bank were attacked by nationalists and pacifists and forced to withdraw. Chants of &#8220;no violence&#8221; directed at the police turned into chants of &#8220;without vandalism&#8221; directed at the protesters. The game had changed again.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/9b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/9a.jpg" width="500" height="296"/></a>
<em>A protester throws a Molotov cocktail at police in front of the ALERJ.</em></p>
<p>Meanwhile, in Rio de Janeiro, thousands of people took to the streets the same day. Drawing on the momentum from São Paulo, a demonstration that would otherwise have drawn only a few thousand people drew over 100,000—making it the largest street demonstration in Brazil for 20 years. The starting point was on the square of the Candelária. The mass occupied the Rio Branco Avenue and marched toward the square of the Municipal Theater.</p>
<p>Knowing that the parties wanted to end the demonstration in Candelária, a group of anarchists, insurrectionists, anarcha-feminists, and Maoists were able to pull the manifestation to ALERJ, the parliament of Rio de Janeiro. The scene was already chaotic when the crowd arrived there. A small group of military police had attempted to guard a barricade in front of the building; surrounded and attacked, they fled into the ALERJ. Some protesters tried to invade the ALERJ; others spray painted its walls and broke its windows; still others began to burn cars. Several groups fanned out into the surrounding area to attack banks and multinational stores; other groups started looting, distributing the goods and playing with them in the streets. For over three hours, the center of Rio de Janeiro was filled with protesters.</p>
<iframe width="500" height="281" src="//www.youtube-nocookie.com/embed/oHyfFeUT1-s?rel=0" frameborder="0" allowfullscreen></iframe><br/><br/>
<p>From that day on, the demonstrations spread throughout the country. Pôrto Alegre returned to star in street clashes. Belo Horizonte and Rio de Janeiro staged new mass protests; during the Confederations Cup, protesters torched several car dealerships in Belo Horizonte and protesters from Rio de Janeiro came within 500 meters of the Maracanã during the final game, advancing more than two kilometers past the perimeter established by FIFA. Rio de Janeiro witnessed the greatest demonstration in the history of Brazil, over 3 million people, including an hours-long pitched battle in which protesters clashed with the BOPE (Assault Troop of Rio de Janeiro Military Police) and chased away the Caveirão—“BigSkull,” BOPE´s tank for going into the slums to kill poor and black people.</p>
<iframe width="500" height="281" src="//www.youtube-nocookie.com/embed/-NJiMD9DQ6Q?rel=0" frameborder="0" allowfullscreen></iframe><br/><br/>
<p>The people of Vitória also fought major battles, occupying the Terceira Ponte—the most important bridge of the city. In Salvador, the demonstrations became a great deal more radical, drawing broad participation especially from the poorest sectors of society. There were demonstrations in the cities around São Paulo: Campinas, Santos, Praia Grande, Sorocaba—and around Rio de Janeiro: Barra Mansa, Macaé, Campos—and in other large cities such as Curitiba, Florianopolis, Natal, Maceio, and Aracaju. At the end of June, there were days when there were protests in more than 100 cities at once, and cities like São Paulo, Pôrto Alegre, Belo Horizonte, and Rio de Janeiro had protests every day of the week. Not to mention the international solidarity protests that took place in Berlin, Barcelona, and London.</p>
<p>On June 19, thanks to all the burned busses, smashed banks, and destroyed shop fronts, the governments of Rio and São Paulo jointly announced the reduction of the transit fare. This was a transparent ploy to preserve what little popularity they had left, meeting the movement’s demands before things got further out of control. This had a domino effect: soon after, several major cities also announced fare reductions, making this a historic victory. Yet more demonstrations still ensued. These focused on additional issues such as private mafia control of transportation. Belo Horizonte, Pôrto Alegre, and Vitória joined in, with protesters occupying the Legislative Chamber. In Rio de Janeiro and São Paulo, protesters continued to fill the streets. Several public university offices in São Paulo and Belo Horizonte are occupied as of this writing, and we just been informed that Paulínia, in the state of São Paulo, is the first city to adopt Rate Zero after the protests: free passage on public transportation.</p>
<blockquote>
<p><strong>The movement against rising transportation costs is not new—it has been around for some years. Three years ago, it seemed to be one of the only urban movements involving mass conflict with the state. Why was that movement so lively when others seemed lifeless? And what was its role in setting off these recent larger struggles?</strong></p>
</blockquote>
<p>The Movimento pelo Passe Livre (Free Pass Movement) has existed since 2005. The movement arose out of major uprisings against the fare increases that had occurred in Florianópolis and Salvador. The MPL gained a disproportionate role due to stupidity of the bourgeois media, which searches for leaders and martyrs for any social struggle, embracing whatever is simplest and most marketable. The MPL is usually just another group that participates in combative forums against rising rates in the cities that have more militant struggles over transportation issues.</p>
<p>These movements against rising rates have never been mass movements. In general, they are composed from the militant student movement, former students who are public school teachers, and high school students: mostly white, middle-class, heterosexual cis-men, in their overwhelming majority belonging to parties of the center-left social Democrats and Trotskyists, but also including a current of anarchists and autonomists. From the founding of the MPL until today, the protests that took place against the fare increases involved 3000 participants at the very maximum. Also, the movement did not have a radical character. Even with the participation of anarchists, the movement never managed to defend itself from police attacks, let alone begin an offensive against capitalism and the state. Its demonstrations were often marches carrying banners and drumming; when repression came, these were immediately dispersed, with rare exceptions.</p>
<p>In addition, there were other radical urban movements. One of the few breaths of life in recent years was the organization of the homeless and the movement of urban occupations—squats involving poor, black, and queer people. They established important social occupations across the country and bravely resisted the attacks of the state. The campaign against the Belo Monte hydroelectric dam also gained nationwide support, drawing thousands of people to the streets and inspiring urban militants to join indigenous peoples in the Amazon in committing acts of resistance and sabotage against Belo Monte.</p>
<blockquote>
<p><strong>Explain how the uprising spread from a few specific single issues and particular groups to the participation of many parts of the general population with a broader outlook.</strong></p>
</blockquote>
<p>Insurrectionary situations always exceed teleological interpretation; any attempt to explain them that does not take this into account is limited to a cis-masculinist rationality and Eurocentric totalitarian reason. That said, a variety of factors have contributed to this political cauldron.</p>
<p>The brave popular resistance in pitched battles around the country and the brutal police violence against demonstrators generated a social upheaval, bringing a large contingent of people to the streets. The arrival of these new protesters with little political background changed the situation. While the existing the movement radicalized in response to police repression, pacifists and nationalists attracted many of the newcomers, altering the character of the protests. In this context, extreme right-wing groups saw an opportunity to gain visibility.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/10b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/10a.jpg" width="500" height="299"/></a>
<em>“The favela never slept!”</em></p>
<p>The crisis of the state in Brazil has discredited all political and social representation, including professional politicians and left-wing parties. Much of the population attended demonstrations expressing this disillusionment. The right wing would channel this into campaigns against corruption, calls for the impeachment of president, and appeals in defense of the family.</p>
<p>The political context of Brazil is extremely turbulent; movements offer a strategic link to the strengthening of the collective interests of groups in resistance. The negative impact of the World Cup in Brazil is already visible, and in mass demonstrations during the Confederations Cup, the voices of those who are being affected by these developments echoed in the streets, especially in cities that hosted those events. The evictions of urban occupations and policies targeting favelas are also proceeding at full speed, which also contributed momentum. The movements of black people and people of color and grassroots organizations from the favelas brought a focus on police violence and state terrorism against black youth and slum dwellers. There is also a cis-heterosexist and masculinist assault in Brazil, with religious politicians trying to implement a law criminalizing women who have abortions, and another calling for psychologists to “heal” people guilty of anti-heteronormal gender disobedience. So the voices of all kinds of feminists, women, gays, trans-people, and queer-folks also echoed in the streets across the country.</p>
<p>One of the slogans of the uprising was “The giant woke up.” The participation of marginalized sectors including black people, favela dwellers, and trans-folks showed that the police who were violent downtown, with rubber bullets against rich and heterosexual protesters, were the same ones who kill poor, black, and non-heterosexual people in the slums every day. Slogans began to appear like &#8220;The Favela never slept,&#8221; &#8220;Feminists and trans-peoples never slept,&#8221; putting the movement in historical context rather than catering to the privilege of a disoriented middle class that always assumes itself to be the protagonist.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/28b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/28a.jpg" width="500" height="306"/></a>
<em>Demonstration in Rio: “The police that repress in the streets are the same ones that kill in the favelas!”</em></p>
<p>For more context, we can highlight the killing of eleven residents of Favela da Maré in Rio. In a demonstration of Maré residents, the police charged some people with robbery. Soon after, the police carried out a military operation in the Favela da Maré, killing eleven villagers. This produced a national uproar, strengthening the struggle of residents and politicized further demonstrations in Rio. Here is our solidarity with the families and residents of Maré and all those who live with violence every day, where direct action, radicalism, and fury in the streets reflect the realities of life on the margins of hetero-capitalism and the need to resort to such tactics as a survival strategy.</p>
<blockquote>
<p><strong>How did the politics shift as the uprising became more popular?</strong></p>
</blockquote>
<p>Already, before the events in São Paulo and Rio, the very first protests in Pôrto Alegre and Goiânia were fierce. The news was that protesters were closing streets with burning tires and barricades, that they were burning busses, that the government was scared and retreating and that the police were violent, trapping many people and giving rise to lawsuits. Balaclavas, Molotov cocktails, gas masks, vinegar, voluntary medical staff, gasoline, and all types of handmade bombs were deployed in almost all the demonstrations around the country, and not only by traditionally radical and insurrectionary groups. Tactics such as occupying government offices, blocking the doors of city hall, blockading roads, clashing with police, and looting became commonplace. The way the police reacted with violence and then retreated in fear only radicalized the demonstrators, creating a spirit of solidarity with arrested or injured protesters and revealing the power of horizontal grassroots organization.</p>
<p>On the other hand, the victory of the fare reduction, the end of the Confederations Cup, and the appearance of middle-class, nationalist, and pacifist sectors in the movement generated a period of decline in some cities. In São Paulo, in late June, black bloc’ers and other radical protesters were repeatedly beaten up by pacifists and handed over to police. Although the protests in Rio remained quite radical, anarchists and other protesters suffered aggression from Marxist and workerist parties.</p>
<p>Overall, the victories won by insurrectionary tactics offered a breath of hope to the vast majority that took to the streets. The fare increase was repealed, the aforementioned law of &#8220;gay healing&#8221; was tabled, a bill offering impunity to parliamentarians was vetoed. In cities where there was a pacifist breakthrough, it is necessary to revise the tactics and reorganize the fight, but the feeling in the air is that militant tactics fit into a context that has passed the point of no return. From now on, Molotov cocktails, barricades, and street fighting will be part of the tradition of street demonstrations in Brazil.</p>
<blockquote>
<p><strong>Twelve years ago, Brazil had a powerful anti-capitalist movement. Describe how Lula&#8217;s presidency and the electoral victories of the PT changed the political landscape and contributed to the eclipse of that movement.</strong></p>
</blockquote>
<p>The entry of the PT—the Workers Party, the party of Lula and the current president, Dilma—into the presidency transformed the political landscape. However, to explain the transformation of the political context only in terms of representational politics not only obscures contingencies, micropolitics, and molecular resistance, but reproduces the modern-colonial attempts to see politics within the privileged sphere of cis-hetero-white-eurocentric-masculinist rationality.</p>
<p>When the Lula government came to power, the sections of the left and social movements that benefitted from PT support stopped engaging in anti-government confrontations in return for money and privileges. This caused many movements to decline, including the Landless Workers’ Movement (MST), the student movement and unions, and even some sectors of the homeless movement and urban occupations, traditionally radical and nonpartisan.</p>
<p>This contributed to the decline of the anti-globalization movement, but it was not the only factor. The failure to cope with the advancement of pacifist ideology, the failure to create strategies and languages to break out of the boring traditions of the hegemonic left, and the inability to connect with other struggles also contributed to the decline of that movement. Beyond the external factors of macro and electoral geopolitics, the movement declined because it could not cope with the new context by renewing itself and creating new dynamics—<a href="http://en.wikipedia.org/wiki/Minority_(philosophy)">“minor”</a> dynamics, in the language of Deleuze and Guattari, “terrible” dynamics, in the language of Tiqqun.</p>
<p>The social assistance programs of the Lula government have also shifted the context. On the one hand, new income redistribution and credit policies raised much of the population above the poverty line, enabling a new mass to participate in spectacular capitalism, consuming the gadgets and lethargic subjectivity of middle class identity. This created widespread political apathy. On the other hand, the credit policy has generated a huge mass of people who are no longer poor, but rather indebted. Combined with the mass entry of slum dwellers and poor people of color into universities via government programs, this politicized many sectors that traditionally were on the margins of hetero-capitalist society, producing a new indebted class with access to a discourse previously restricted to the privileged.</p>
<blockquote>
<p><strong>The uprisings around the world that began with Greece in December 2008 and culminated with the Arab Spring in 2011 were all described as protests against austerity. What does it mean to see uprisings in countries like Brazil and Turkey where the economy is supposed to be &#8220;improving&#8221;?</strong></p>
</blockquote>
<p>It is important to understand that Brazil’s economic growth came the hard way. It arose via a process of accumulation by dispossession—both in the countryside, where a massive influx of agro-industrial capital expanded monoculture and livestock exportation, and in the city, through urban commodification policies including the removal of slums and building occupations and the <a href="http://en.wikipedia.org/wiki/Pacifying_Police_Unit">militarization of the city</a>. But it is also important to remember that by June 2013, economic growth had already plateaued, with some evidence of decline: inflation has been relatively high this year, and the rising prices of basic commodities such as tomatoes only confirm this. Once more, the entry of a large part of the population into the arena of consumer capitalism occurred only via their going into debt.</p>
<iframe width="500" height="281" src="//www.youtube-nocookie.com/embed/ZApBgNQgKPU?rel=0" frameborder="0" allowfullscreen></iframe>
<p align="center"><em>Though essentially reformist, this video offers a good overview of the situation around the World Cup.</em></p>
<p>This created a tense situation. Part of the population was directly hit by the negative consequences of this economic growth: construction of dams, killings and expulsions from the countryside, evictions and removals related to World Cup and international investments, military occupations of neighborhoods. Another part of the population is suffering from the halt of economic growth, and yet another part suffers from debt as a consequence of its supposed social ascent.</p>
<p>The management of Brazilian capitalism seems to have entered a time of crisis: most of its institutions are discredited, and the mechanisms that produce capitalist subjectivity seem to be breaking down. The hatred of party flags in the street demonstrations, the cries of &#8220;No more Dilma,&#8221; the disillusionment with politicians and corruption—rather than indicating that the population has been taken in by the speech of fascist and right-wing groups, these show that people are losing confidence in the most fundamental institutions of capitalism and the state. Moreover, it appears that the entry of a new population into consumer society has been a disappointment. The utopia depicted in electronics advertisements has turned out to be boring and unfulfilling.</p>
<blockquote>
<p><strong>What has been the influence of the revolts in Greece and Spain, the Arab Spring, and the Occupy movement upon the popular imagination in Brazil? Did participants in the June uprising see themselves as connected to the people fighting in Turkey and Egypt at the same time?</strong></p>
</blockquote>
<p>The Greek anarchist movement has long inspired the insurrectionary anarchist imagination in Brazil. However, until recently, we thought that the Greek anarchists could do such things because the Greek police are not militarized, whereas such revolts could never occur under Brazil’s military police. So, aside from inspiring a desire for more radical protests, Greek anarchists were not very influential. But we should also point out that the hetero-masculinist performance of some parts of the Greek anarchist movement has provoked critique from anarcha-feminist, radical feminist, and insurrectionary and anarchist queer sectors here.</p>
<p>The Occupy movement also had some influence here. The occupations of squares occurring at the end of 2011 in Pôrto Alegre, Rio, São Paulo, and other cities in the country took a new generation and a new social demographic into the streets—and some of those sectors remained active, taking a role in the uprisings. This was not always for the best: part of the pacifist and nationalist wave that raged in mid-June occurred thanks to the holders of the Guy Fawkes masks, Anonymous activists and some members of Occupy.</p>
<p>The <a href="http://www.crimethinc.com/blog/2013/07/04/interview-anarchists-in-the-turkish-uprising/">Turkish resistance movement</a> exerted a vivid influence on uprisings in Brazil. First, because like Brazil, Turkey is a country where one rarely sees violent street demonstrations, despite the abject living conditions of much of the population. Chants like &#8220;It&#8217;s over love, so here will turn Turkey&#8221; echoed in Pôrto Alegre, Rio de Janeiro, São Paulo, and other cities. Demonstrators adopted tactics of urban confrontation from the Turkish resistance: barricades of burning garbage, gallons of water in which to submerge tear gas canisters.</p>
<p>Meanwhile, <a href="http://roarmag.org/2013/06/from-tahrir-and-rio-to-taksim-the-smell-of-teargas/">a letter from the Egyptian movement in solidarity with the Brazilian uprising</a> was received with a lot of emotion by protesters. </p>
<blockquote>
<p><strong>What was the role of anarchists in initiating the uprising, and in pushing it further? In what ways were anarchist interventions in the events successful? In what ways did they fail?</strong></p>
</blockquote>
<p>On one hand, it is important to highlight the role of anarchists in the events. Many of the clashes with police were led by anarchists or involved a great number of anarchists. Older anarchist militants helped maintain calm and share tactics during the tensest moments; this probably preserved momentum and also ensured the safety of the participants. Black blocs also had a role in the resistance; in cities like Rio de Janeiro, Belo Horizonte, and São Paulo, they become a target of pacifist and communist parties, who felt that anarchists threatened their power. Black bloc tactics, initiated by anarchists, also spread throughout the demonstrations, especially in Belo Horizonte and Rio.</p>
<p>On the other hand, thankfully, anarchists were not as important as some would think. Much of the fighting and resistance was initiated by marginalized sectors of society: the unemployed, informal workers, poor workers, homeless people, street children, unemployed teenagers, and favela dwellers. In some moments of resistance—for example, when protesters drove the Caveirão off the streets, or in Belo Horizonte when protesters burned several car dealerships—you could see only a few anarchists. This shows that the radical tactics and spirit had spread throughout the multitude, or that the anarchists had dissolved themselves into the multitude. This is important: if the imperial capture apparatus cannot identify and isolate the source of revolt, the insurrection can spread.</p>
<p>It is still too early to make a balance sheet of anarchist participation in the revolt. However, it is clear that the most militant tactics, driven by young anarchists, radical feminists, anarcha-feminists, insurrectionary queers, and animal liberationists—sectors largely marginalized by social anarchism—were precisely the most effective tactics and the ones that spread the most in the demonstrations, playing a central role in the victory of the uprising.</p>
<blockquote>
<p><strong>Have there been debates about violence versus non-violence? How have other people reacted to those who take more militant action?</strong></p>
</blockquote>
<p>In the anti-globalization era, we sidestepped the debate about violence, non-violence, and diversity of tactics. But this debate has erupted in the current demonstrations with material consequences; it seems that now we&#8217;re experiencing what the insurrectionary anarchists experienced <a href="http://www.crimethinc.com/blog/2006/11/30/seattle-seven-years-later/">in Seattle in 1999</a>. Pacifists attacking radicalized protesters and anarchists; people giving flowers to policemen and inviting them to join the protest; demonstrators kneeling before the riot police advancing toward them with weapons; pacifists asking demonstrators to bend down so the police can identify protesters who are spray painting walls or destroying shops behind them; peaceful demonstrators denouncing protesters and delivering videos of radical actions to the police; communist parties making pamphlets criminalizing anarchists and black bloc’ers, or even physically attacking them.</p>
<p>Despite all this, most people feel that those victories were only possible because of the riots. This gives confidence and credibility to anarchists and insurrectionists; it also caused those tactics to spread. In cities like Rio, some center-left, social anarchist, and student sectors have sympathized with anarchists and insurrectionists and started a campaign against the criminalization of more militant actions.</p>
<blockquote>
<p><strong>What was the role of social media in the revolt? How successful has the government been in using it to strike back at participants?</strong></p>
</blockquote>
<p>The media has played an important role. The first major demonstrations against the increase were all announced through Facebook, and that has continued to this day. Videos of police brutality and popular resistance have been shared through social networks, offering a powerful counterpoint to the corporate media.</p>
<p>But we know that the internet is not an emancipatory space, but rather a hetero-capitalist capture apparatus. Facebook (called Fachobuk by some Brazilians—a play on the word “facho,” slang for fascist) itself was strangely slow, and some news sites could not be accessed or shared. We knew that the US government was watching Facebook and the ABIN (Brazilian Intelligence Agency) was also monitoring online profiles and email accounts. We knew that the police made fake profiles in order to search for information, and phones are being tapped, along with all the old-fashioned imperial practices of spying and infiltration.</p>
<blockquote>
<p><strong>What internal and external limits did the revolt reach? What forms of repression failed or backfired against it? Which forms were successful, and why?</strong></p>
</blockquote>
<p>Currently there are some difficulties in attempts to rearticulate the protests in some cities. The first obstacle is the challenge of dealing with the nationalist and pacifist middle-class demonstrators who have joined the protests. This difficulty is related to a larger impasse: the question of what strategies could hinder the adhesion of this and other reformist agendas to our struggles. There is also the challenge of linking the fare protest movement with other struggles: can we connect those who are showing up to these demonstrations now to the movement of urban occupations, or the fight against evictions, or the struggles against transphobia, heterosexism, and sexism? The reproduction of hierarchical power relations within the movement has also been a problem. Posters have appeared calling President Dilma a dyke, among other transphobic, misogynistic, and heterosexist acts.</p>
<p>As for repression, at first the state of São Paulo used a strategy of ordering the police not to initiate conflict, in an attempt to stifle the movement. Then they overcorrected this first strategy by intensifying repression, which clearly failed. The arrests, bail costs, and police intelligence investigations are also a strategy of intimidation. Despite some effect, this strategy has been fought back, thanks to the growing number of volunteer lawyers who have joined the struggles and the police brutality videos that are published on the internet every day.</p>
<blockquote>
<p><strong>Speak more about the place of nationalism inside the movement, and in the backlash against it.</strong></p>
</blockquote>
<p>It’s true, the middle class and nationalists entered into the demonstrations. Their agendas are usually shallow and empty: against corruption and violence, for education… Its political impact occurred in the momentary disruption of radical sectors that were attacked by nationalists who claimed to oppose violence. Moreover, for a certain period, many people feared that extreme right-wings groups would get traction in the middle class.</p>
<p>This appearance of nationalists and the middle class functioned chiefly as a warning to groups focused on creating insurrectionary situations, rather than as a demonstration that these groups have political relevance. Moreover, we know that fascism is molecular: we saw this in the communists beating radical demonstrators and pacifists repeating homophobic chants.</p>
<blockquote>
<p><strong>What do you expect to happen in Brazil next year, alongside the World Cup? How will this revolt change the shape of future struggles in Brazil? And what are the obstacles facing those who want to see these struggles go further?</strong></p>
</blockquote>
<p>It is hard to imagine how things will be from now on. We know the risks of these attempts: Marxist futurology has made enough errors and missed quite a few lessons. However, we have some evidence in the current political ferment from which to build a political imagination about the coming year.</p>
<p>We know that for the police and the forces of empire, these protests and the Confederations Cup serve as a laboratory for the further development of biopolitical capitalism. In recent demonstrations, the police have used new weapons such as sound cannons, water cannons, and various types of pepper sprays and Tasers. We also know that the government is taking steps towards the suspension of laws and installation of the <a href="http://en.wikipedia.org/wiki/State_of_exception">State of Exception</a>. Senators are already revisiting the concept of “terrorism” in order to place political street demonstrations within this framework. The <a href="http://www.v-brazil.com/world-cup/law/">World Cup general law</a> also uses this framework, giving power to the State, vetoing the right to demonstrate in the streets with violators subject to trial in international courts.</p>
<p>We also know the prospects of demonstrations to stop the World Cup. The slogans &#8220;You will not have Cup&#8221; and &#8220;I give up the World Cup, I want money for health and education&#8221; were chanted all over the country since the first demonstrations. We believe that the outlook is generally radicalized. In this sense, the expectation is of even bigger confrontations for the coming year, more people on the streets, more radicalization, but also more arrests, detentions, political repression, media manipulation, and conflict with nationalists, communists, and pacifists.</p>
<p>So we face many challenges. First, we have to ensure that these mobilizations remain radical and connected to other movements and struggles, to ensure the construction of a strong supportive network that can last into 2014. Another challenge is to find strategies to maintain militant struggle while avoiding security problems that would lead to investigations, arrests, and prosecutions. An intense debate about anonymity, opacity, and social and public activism is being waged within radical organizations.</p>
<p>Of course, we never imagined that we would live to see street fighting in the era of “economic growth.” But it shows us the cracks in the empire´s great wall. Now we have to achieve a breakthrough for insurrectionary and anti-hegemonic social struggles in the country, so they cannot be captured or pacified. Those who have realized that they are expendable from the perspective of global capitalism must cease to understand themselves as a reconcilable opposition and enter a final antagonism with the empire. We have to go beyond the point of no return.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/11b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/11a.jpg" width="500" height="287"/></a>
<em>A demonstration in São Paulo, June 8: “Turkey is here. United!”</em></p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/12b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/12a.jpg" width="500" height="310"/></a>
<em>A demonstration in São Paulo, June 17: Subway destroyed by protesters.</em></p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/13b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/13a.jpg" width="500" height="259"/></a>
<em>A burnt bus at a demonstration in Pôrto Alegre, June 17.</em></p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/14b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/14a.jpg" width="500" height="289"/></a>
<em>Real bullets from a police gun found by a protester at a demonstration in Rio on June 17.</em></p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/15b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/15a.jpg" width="500" height="334"/></a>
<em>A car burning in Rio on June 17.</em></p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/16b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/16a.jpg" width="500" height="350"/></a>
<em>Police brutality in Rio on June 17.</em></p>
￼
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/17b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/17a.jpg" width="500" height="343"/></a>
<em>Car dealerships burning at a protest in Belo Horizonte on the day of the Confederations Cup game.</em></p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/18b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/18a.jpg" width="500" height="261"/></a>
<em>Car dealerships destroyed at protest in Belo Horizonte: “This car dealership supports the protests. But no violence!” An appeal in vain.</em></p>
￼<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/19b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/19a.jpg" width="500" height="334"/></a>
<em>Occupation of the Chamber of Councilors at Pôrto Alegre.</em></p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/20b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/20a.jpg" width="500" height="373"/></a>
<em>“Burn the rich!” painted in front of GLobo headquarters during a demonstration against corporate media in São Paulo in early July.</em></p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/21b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/21a.jpg" width="500" height="408"/></a>
<em>Riot police enter a hospital to arrest suspected protesters after a demonstration in Rio in early July.</em></p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/22b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/22a.jpg" width="500" height="261"/></a>
<em>Non-hetero protester provoking police at a demonstration in Rio.</em></p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/23b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/23a.jpg" width="500" height="309"/></a>
<em>Looting during a protest in Rio on June 17. A child taking only toys in a big department store downtown.</em></p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/24b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/24a.jpg" width="500" height="334"/></a>
<em>Pacifists and nationalists at a demonstration in São Paulo: “Our rotting politicians are the cancer of our nation”—“The vandals do not represent us.”</em></p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/25b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/25a.jpg" width="500" height="376"/></a>
<em>Road toll burned during a demonstration against the fare increase at Cosmópolis in the state of São Paulo.</em></p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/26b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/26a.jpg" width="500" height="348"/></a>
<em>São Paulo City Hall surrounded by angry protesters at a demonstration in mid-June.</em></p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/brazilpt1/27b.jpg" rel="lightbox[standing]"><img style="margin-bottom: 5px" src="http://cloudfront.crimethinc.com/images/brazilpt1/27a.jpg" width="500" height="271"/></a>
<em>Barricades at a demonstration in Salvador in late June.</em></p>
