<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/1b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/1a.jpg" alt="Breaking and Entering a New World: Pioneering the Future of the Occupy Movement" width="500" height="469"/></a></p>
<p>This is the story of the occupation of a derelict building in Chapel Hill, North Carolina on November 12-13, 2011, told in the voices of a wide range of participants. While <a href="http://trianarchy.wordpress.com/2011/11/13/this-building-is-ours-chapel-hill-anarchists-occupy-downtown-building/">anarchists</a> and <a href="http://www.newsobserver.com/2011/11/13/1641362/activists-take-over-vacant-franklin.html">corporate media</a> have circulated news of this action far and wide, the experiences shared inside the building have remained a sort of <a href="http://en.wikipedia.org/wiki/Black_box">black box</a>. This report opens up that box, just as the occupiers opened up the building, to reveal a world of possibility.</p>
<p>Some of the narratives below are excerpted from longer accounts, which can be read in their entirety <a href="/texts/recentfeatures/breakingaccounts.php">here</a>.</p>
<p>&nbsp;</p>
<iframe src="//player.vimeo.com/video/32600177?portrait=0&amp;color=ffffff" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
<center><p><em>Slideshow courtesy of Underground Reverie</em></p></center>
<p>In contrast to the occupation movement in some parts of the US, anarchists were involved in <a href="http://occupychapelhill.org/">Occupy Chapel Hill</a> from the very beginning, sending out the initial call and facilitating the first meetings. The points of unity consensed upon at the first gathering were based on the <a href="http://pittsburghendthewar.org/PittsburghPrinciples.html">Pittsburgh Principles</a>, and the group never adopted a nonviolence agreement.</p>
<h6>At the second assembly, we debated whether to set up an encampment. Some argued against it, claiming that the police would evict us and insisting we should apply for a permit first. In nearby Raleigh, occupiers had applied for a permit but were only granted one lasting a few hours; everyone who remained after it expired was arrested. A few of us thought it better to go forward without permission than to embolden the authorities to believe we would comply with whatever was convenient for them.</h6>
<h6>A different facilitator would have let the debate remain abstract indefinitely, effectively quashing the possibility of an occupation, but ours cut right to the chase: &ldquo;Raise your hand if you want to camp out here <em>tonight.&rdquo;</em> A few hands went hesitantly up. &ldquo;Looks like five&hellip; six, seven&hellip; OK, let&rsquo;s split into two groups: those who want to occupy, and everyone else. We&rsquo;ll reconvene in ten minutes.&rdquo;</h6>
<h6>At first there were only a half dozen of us, but once we took that first step, others started drifting over. Ten minutes later there were twenty-four occupiers&mdash;more than we believed the local police were prepared to arrest&mdash;and that night fully three dozen people camped out in Peace and Justice Plaza. I stayed awake all night waiting for a raid, but it never came. We&rsquo;d won the first round, expanding the zone of the possible.</h6>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/2b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/2a.jpg" /></a></p>
<p>On November 2, participants in the <a href="http://www.crimethinc.com/blog/2011/11/06/oakland-general-strike-footage/">general strike in Oakland</a> attempted to <a href="http://www.bayofrage.com/from-the-bay/statement-on-the-occupation-of-the-former-travelers-aid-society-at-520-16th-street/">occupy an empty building</a> that had previously provided services to the homeless. This controversial action ended in dramatic confrontations with riot police, but opened up a new horizon as winter crept up on the occupation movement.</p>
<p>Saturday, November 12, following the second annual <a href="carrboroanarchistbookfair.wordpress.com">Carrboro anarchist book fair</a>, upwards of fifty people gathered for a march in solidarity with the occupation movement.</p>
<h6>We couldn't tell if we were parading yet. The crowd had begun to move, but it was still finding its rhythm and cohesion. But we two found our cue: there was a little boy, maybe five years old, carrying a black flag on the end of a six-foot bamboo pole. It tottered, sometimes bumping other paraders, as he struggled proudly and joyously to keep it aloft. We were with him.</h6>
<p>Undercover officers were already following participants, peppering them with inappropriate questions.</p>
<h6>This middle-aged white guy in a puffy red winter vest shuffled to catch up with us. Curious and clueless, he was in from &quot;out of town,&quot; he knew nothing about Anarchy or Occupy, and he was hoping we would explain things to him. Did we want to &quot;smash capitalism?&quot; Did we know what the plan was for tonight? Sometimes we couldn't resist saying hilarious nonsense to him, but mostly we told him about how much we loved detective movies.</h6>
<p>The march proceeded to the 10,000-square-foot commercial building at 419 West Franklin&nbsp;Street, a former Chrysler-Plymouth dealership empty since 2003. The absentee owner, <a href="http://www.highbeam.com/doc/1G1-133443137.html">Joe Riddle</a>, was among the town&rsquo;s most widely loathed <a href="http://www.riddlecommercial.com/">property holders</a>. He had no plans for the building; as it was sitting on property valued at close to a million dollars, only a powerful corporation could possibly purchase it.</p>
<h6>When we left the book fair, I had no idea what to expect, other than that we would be heading towards the plaza occupation. I was caught off guard by the large number of people and full of excitement as we made our way through a parking lot to the street. When we arrived, I was surprised to see the group move in the opposite direction. By the time we&rsquo;d crossed the street to the building, I was so caught up in chanting and looking around at the crowd that I hadn't taken stock of where I was. At this point, I looked toward the front of the march and saw that the windows of a building had been decorated with two large banners.</h6>
<h6>The march veered up the driveway in front of the building. As the crowd approached the vertical-sliding door, it glided up and two or three pairs of eyes stared out from under hats and over bandannas. As we streamed in, I saw people conversing and looking around the huge main room,&nbsp;silhouetted&nbsp;by the electric lights that had been rigged up and placed in the center. Someone handed me a folded sheet of paper that presented one of the most truly exciting ideas I had ever seen: the proposal that, amidst this global economic and political collapse, a community could form around this long-abandoned and maliciously wasted property and make something of benefit to the town at large. As I walked around the premises, I couldn't believe that this was happening before my eyes. While I was caught entirely off-guard, I was eager to see where it would go.</h6>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/3b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/3a.jpg" /></a></p>
<p>Participants distributed <a href="http://www.indyweek.com/pdf/111611/OccupyEverythingFlyer.pdf">leaflets</a> proposing that the space could be turned into a social center serving the community, including a meticulously designed blueprint showing some of &ldquo;the countless uses such a building could be put to once freed from the stranglehold of rent.&rdquo; Over the course of the evening, these handouts were warmly received by hundreds of passersby.</p>
<h6>    I stepped out to get some air. A couple approached me: &ldquo;What&rsquo;s going on here?&rdquo;</h6>
<h6>I handed them the pamphlet and explained, &ldquo;We&rsquo;re turning this building into a community center.&rdquo;</h6>
<h6>The man&rsquo;s face lit up. &ldquo;That&rsquo;s great! I worked as a chef next door&nbsp;for years and this place just rots here!&rdquo;</h6>
<h6>I nodded and added matter-of-factly, &ldquo;It&rsquo;s an illegal occupation.&rdquo;</h6>
<h6>&ldquo;Even better!&rdquo; he said enthusiastically.</h6>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/4b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/4a.jpg" /></a></p>
<p>The leaflet spelled out an anticapitalist rationale for occupying the building, framing it in reference to the local context:</p>
<h6>Across the US, tens of thousands of commercial and residential buildings sit empty while people sleep in the streets or descend into poverty paying ever-rising rent. Chapel Hill is no different. This building has been empty for a full decade, gathering dust and equity for a faraway landlord while rent skyrockets beyond our ability to pay. A brand new &ldquo;green&rdquo; development remains empty right up the street, gentrifying the neighborhood so longtime locals have to move to Durham. This is what happens when our town is shaped by profit rather than human need.</h6>
<p>A handful of police officers positioned themselves across the street, a threatening but hesitant presence.</p>
<h6>We had a police liaison ready and waiting, but they never initiated contact with us. When the police crossed the street towards the building, about fifty of us gathered in front of it, chanting &ldquo;A&mdash;Anti&mdash;Anticapitalista!&rdquo; The officers hesitated&mdash;what was this strange incantation?&mdash;and withdrew. That chant cast an enchantment, magically protecting the occupation.</h6>
<p>Two people from the Chapel Hill Downtown Partnership also arrived; after the building had remained untouched for so many years, they had coincidentally just arranged for an artist to make a display in the front window. Occupiers engaged personably with them, exchanging contact information to open negotiations about the space. Later this was intentionally omitted from the authorities&rsquo; account of events, so as not to disrupt their narrative about <em>dangerous and unapproachable anarchists</em>.</p>
<p>Meanwhile, more and more people were arriving, passing through the open garage door to explore the building.</p>
<h6>    Vastness. Pure vastness. How can a building be so enormous? A single orange extension cord snaked across the vast concrete floor to a jury-rigged contraption of silver flood lamps. The warm grey yellow light flooded up and outwards to a massive ceiling of latticed wooden beams, casting crisscrossed shadows to the eaves of the roof beyond. The cinderblock walls seemed to extend out endlessly, an impossible distance, to a back door that had to be a football field away.</h6>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/5b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/5a.jpg" /></a></p>
<p>Some people began cleaning the interior; others set up a kitchen, a reading library, and sleeping areas. Trucks and cars were pulling up in the driveway one after another to unload supplies. A show originally scheduled in a local basement as an after-party for the book fair was moved to the occupation.</p>
<h6>S&mdash; performed her set a cappella, kneeling on a blanket in that immense darkness with all of us pressed around her, a spark sailing up into the night. She&rsquo;s always an amazing singer, but this was something else. When she opened her mouth, the whole world poured out: childbirth and tear gas, clear streams and mountaintop removal, rage and exaltation and tragedy.</h6>
<h6>Occupying a building means investing yourself in a space that may be taken from you any minute, in a time you know is short; it forces you to be present in a way we rarely are, to confront your own mortality. Death accompanies us at every step, devouring us instant after instant, but we only awaken to this when we stumble into unrepeatable moments. Without that awareness to give it urgency, music is only music; that night, it was existence itself, running through our fingers like sand.</h6>
<h6>R&mdash; joined her with his berimbau for the last song. When he hit the first note and paused, it echoed through the building and throughout our lives. Death and the police&mdash;the great erasers&mdash;were close at our heels, but for that moment we were immortal together, viscerally alive.</h6>
<p>A joyous dance party ensued in the front room, as several dozen people cavorted with increasing abandon to live DJs while looped <a href="http://www.crimethinc.com/blog/2011/11/06/oakland-general-strike-footage/">footage from the Oakland general strike</a> was projected larger than life across the wall behind them. Over one hundred people from many different walks of life passed through the building in the course of the evening; locals who had only seen each other around town introduced themselves and conferred giddily. Many of these were younger anarchists, students, and hipsters employed in the service industry, but others were long-established residents old enough to recount stories from the days before the automobile dealership closed. There were even a few attendees who possessed positions of influence at the university or in local politics; later, of course, it never came up that they had participated exuberantly in an illegal occupation.</p>
<h6>The most exciting thing for me about occupying this building was the looks on my friends&rsquo; faces. Surprise. Accomplishment. Possibility. Unbridled joy.</h6>
<h6>None of us thought we could hold this building, but several hours in we were still dancing, still chatting with passersby, still dreaming about what would come next. What if this building could actually be ours? What if we could be powerful enough together to build the beautiful things we deserve? I had so many conversations with strangers about what we can make and be for each other outside the constraints of capitalism, so many daydreams about living in a world where everyone has enough&mdash;and on each of these new friends&rsquo; faces, I found the resolve to make something worth taking risks for.</h6>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/6b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/6a.jpg" /></a></p>
<p>As the festivities finally died down, about two dozen people settled in to sleep in the building overnight, securing the doors and unrolling sleeping bags on cardboard and wooden pallets. Others stood watch&mdash;some inside, some outside&mdash;waiting to sound the alarm in case of a police raid.</p>
<h6>Occupy Chapel Hill had encamped in the only public space in Chapel Hill, a concrete plaza outside the building that serves as post office and courthouse, located at the edge of a long stretch of bars. At 2 a.m. every night, patrons stumble from the bars, tearing down signs, kicking tents, and shouting obscenities at occupiers. No wonder so many occupiers fled to Occupy Chrysler for the cavernous safety of the abandoned car dealership at the other end of the street. While four or five members of OCH waged the stressful nightly battle to deescalate intoxicant-fueled anger at the plaza, I settled with one companion on the stoop in front of the Chrysler building to stay awake and watch while weary occupiers got some well-deserved rest.</h6>
<h6>Traffic dwindled, leaving only a cold quiet street of brick buildings and gold-leafed trees, a few stars, and the just-waning moon. In those quiet hours before dawn, anything seemed possible in the town where we both had lived most of our lives. If the landlord antagonistic to the town let us stay, if the town antagonistic to the landlord let us stay, if a nonprofit arts organization with tentative access to the building partnered with us, if any of those things happened we had the skills among us to winter off the grid easily. At three times the size of the public plaza, the hulking building behind us not only offered room for Occupy&rsquo;s general assemblies, teach-ins, and sleeping, but ample space to become whatever a community envisioned: a kitchen, a clinic, a classroom, a library, a movement and arts space. It seemed all we had to do was wait for morning and begin.</h6>
<p>Police officers dropped by in the morning, unsuccessfully seeking to gather intelligence from those on watch duty. This visit was also omitted from their later narrative of events. The artist who had been invited by the Downtown Partnership to decorate the storefront showed up shortly thereafter; a friend of participants in Occupy Chapel Hill, she expressed support for the occupiers. This didn&rsquo;t prevent enemies of the occupation from later using her as an excuse to justify the raid.</p>
<p>An assembly discussing anarchist strategies against the prison-industrial complex had been planned for the book fair venue at noon. It was moved to the front room of the occupation; dozens of people participated, sticking around afterwards for lunch catered by a supportive local restaurant. Others, several of whom were carpenters or construction workers by trade, were busy fixing up the building: sweeping the floors, unboarding the windows, and building structures to supplement the furniture dropped off by enthusiastic locals.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/7b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/7a.jpg" /></a></p>
<h6>After lunch, a rumor circulated that the police were preparing to raid the space. A few dozen of us gathered for an impromptu meeting. It struck me how different this was from the general assemblies of Occupy Chapel Hill. Those were often bureaucratic nightmares, breeding boredom and aggravation as people deadlocked over minutia and droned on just to hear themselves speak.</h6>
<h6>Here, there was nothing abstract about the issues at hand, nothing that promoted pointless arguing or ego trips. We were putting our bodies on the line just by being present; these were real choices that would have immediate consequences for all of us. For once, we didn&rsquo;t need a facilitator to listen to each other or stay on topic. With our freedom at stake, we had every reason to work well together. Maybe the problem at the plaza had been that we weren&rsquo;t risking enough.</h6>
<h6>We decided that if the police came and it was clear we couldn&rsquo;t keep the building, we would all leave in a group, taking our belongings with us and being sure not to leave anyone in their hands. They must have had that meeting infiltrated or else they wouldn&rsquo;t have known to swoop in right after it; later, they claimed they were afraid we were dangerous, but their real fear must have been that we would bring the occupation to a close on our own terms, without any losses.</h6>
<p>Many people hurried home from this meeting to get more supplies and return to the building prepared to hold it for the long haul. The police took this opportunity to carry out a fully militarized raid.</p>
<h6>I was sitting on the brick edge of the flowerbed, drinking coffee and sharing a chocolate bar with friends, alternately watching Franklin Street&rsquo;s pedestrians and glancing at the yoga class beginning inside our building. The conversation was lighthearted; we were all dizzy with the excitement of taking a stand against the wastefulness of the property owner. We feared our joy might be short-lived&mdash;we anticipated being quickly evicted, and had committed to a plan to leave peacefully when the police arrived&mdash;but nevertheless, we were reveling in our future plans for the community center we hoped to establish.</h6>
<h6>I was suddenly distracted by the headlights of a white SUV, growing larger and larger in the back door of the building. I heard someone inside yell &ldquo;POLICE!&rdquo; I pictured a few officers arriving to tell those inside the building that it was private property, that they had to vacate or be arrested. I sighed and began to collect my belongings.</h6>
<h6>But as I rounded the corner of the building, I was met by a group of police officers and Special Emergency Response Team members&mdash;my brain automatically labeled them &ldquo;soldiers.&rdquo; Some were wearing familiar black Chapel Hill Police Department uniforms; others green fatigues and tactical vests. All were carrying loaded weapons&mdash;automatic rifles and handguns. Many had belts loaded with extra cartridges, ammunition, and plastic zip-tie handcuffs. They were running towards me, pointing their guns and screaming &ldquo;ON THE GROUND! EVERYBODY ON THE GROUND! FACES ON THE PAVEMENT!&rdquo;</h6>
<h6>I paused. <em>Surely they don&rsquo;t mean me,</em> I thought. <em>Surely they aren&rsquo;t carrying those guns because they&rsquo;re scared of me.</em> Knowing that I was outside, and that my bag only contained notebooks, pamphlets, and a coffee thermos, it seemed impossible that these police officers were really running towards, really screaming at, really aiming their weapons at <em>me.</em> I took a moment to set my half-empty cup of coffee on the edge of the flowerbed. But as the barrels of their rifles drew closer, I realized <em>yes, they are running at me.</em> I threw myself to the concrete, face down.</h6>
<h6>I listened to my own ragged, heavy breathing and the sounds of boots. I was torn between the visceral need to <em>see</em> the friends I had been sitting with and a fear that made me squeeze my eyes tightly shut. I focused on my breathing&mdash;in, out, in, out. What would have happened if I&rsquo;d hesitated any longer before falling to the pavement? Would they have fired? If I&rsquo;d reached into my pocket to protect my phone, would they have killed me?</h6>
<h6>I heard a man&rsquo;s gruff voice above me: &ldquo;Please place your hands at the small of your back.&rdquo; A second passed before I realized he was addressing me. I took my hands from beneath my face and placed them behind me. I felt him take my hands and pull one through each loop of the plastic handcuffs. I heard the tk-tk-tk-tk ratcheting of the cuffs being tightened. I remained face down on the sidewalk. I counted seventy-two of my own deep breaths.</h6>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/8b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/8a.jpg" /></a></p>
<p>An operation coordinated between multiple police departments shut down several blocks of Franklin Street, Chapel Hill's primary artery, for over an hour while officers waving assault rifles stormed the building. They arrested eight people and detained many more, including journalists and legal observers. Ironically, the city bus requisitioned by police to hold arrestees bore an advertisement for Wells Fargo on the side. <a href="http://www.dailytarheel.com/index.php/multimedia/8270">A large crowd immediately gathered across the street</a> chanting &quot;Shame!&quot; and &quot;Police, Police, the Army of the Rich!&quot; and explaining the circumstances of the raid to curious passersby.</p>
<p>That evening, less than six hours later, a spirited solidarity march of nearly a hundred people took the streets of downtown Chapel Hill, marching around the main thoroughfares chanting &quot;Occupy Everything&quot; and &quot;We'll Be Back.&quot; Some carried black flags; others bore banners reading &quot;Under Capitalism We're All Under Gunpoint&quot; and &quot;Fight Back.&quot; The majority of the participants marched as a <a href="http://www.crimethinc.com/blog/2008/10/11/fashion-tips-for-the-brave/">black bloc</a>, sending a clear message that they were not intimidated; many supporters and curious passers-by followed behind.</p>
<h6>I'm not the kind of person who gets up in front of people to tell them what I think&mdash;I'm usually too nervous to address even a small crowd. But that night I felt like my voice was the voice of all the women in the march; my voice was as strong as one hundred people's voices, screaming, &quot;Cops, Pigs, Murderers!&quot; at the top of my lungs. Afterwards, I told my friend that I felt like I needed to yell for all the ladies, because I wanted to be sure everyone would hear us, too. I yelled as loudly as I could. It was hard to imagine a reason to be anywhere but there, surrounded by the most awesome human beings I know, in that beautiful moment.</h6>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/9b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/9a.jpg" /></a></p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/10b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/10a.jpg" /></a></p>
<p>The march was followed by a benefit show packed with well over a hundred people. Locals and visitors from around the state expressed solidarity with the arrestees, the building occupation, and the anticapitalist movement. The owners of the venue had openly approved of the black bloc assembling there and returning after the march; this marked a watershed gain in public support for anarchists in Chapel Hill.</p>
<h6>Everyone was there, even the Women&rsquo;s Studies professor I&rsquo;d dated&mdash;my housemate loaned her his scarf for the black bloc. Our band somehow ended up playing, too, even though we weren&rsquo;t on the bill and hadn&rsquo;t practiced in half a year; people were waving black flags in the air as they danced. The whole weekend was like an anarchist cartoon, with all the clich&eacute;s crowded in back to back: the book fair, the workshop, the squat, the assembly, the raid, the march, the show. I hadn&rsquo;t slept in something like 72 hours; things were starting to feel surreal. Had those blonde students with black sweatshirts over their UNC gear been real? Were they really shouting &ldquo;Fuck the Police!&rdquo; with us?</h6>
<p>Monday afternoon, dozens of protesters disrupted the <a href="http://abclocal.go.com/wtvd/video?id=8431411&amp;rss=rss-wtvd-video-8431411">press conference</a> at which the mayor and police chief attempted justify the raid. This swift response prevented the authorities from spinning a narrative of public support and likely contributed to later public willingness to express disapproval. Media attention continued to focus on outrage against the police rather than the violation of property rights.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/11b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/11a.jpg" /></a></p>
<p>That evening, Occupy Chapel Hill gathered for a contentious general assembly at the original encampment. There were more people in attendance, and more energy, than there had been at any general assembly since its inception; whether or not one approved of the building occupation, it had undeniably breathed life into the local movement as well as garnering it national attention. The discussion revealed that the differences within Occupy Chapel Hill were hardly fatal. In subsequent general assemblies it became clear that the building occupation had radicalized many if not most participants, further expanding their notion of the possible. </p>
<p>Over the following week, people inspired by the efforts in Oakland and Chapel Hill occupied buildings in <a href="http://antistatestl.wordpress.com/2011/11/18/report-from-one-participant-n17-march-against-austerity-a-joyful-and-unruly-crowd-takes-a-building/">Saint Louis</a>, <a href="http://occupywallst.org/article/occupy-vacant-buildings-99/">Washington, DC</a>, and <a href="http://pugetsoundanarchists.org/node/1109">Seattle</a>. This new wave of actions pushed the Occupy movement from symbolic protests towards directly challenging the sanctity of property.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/12b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/12a.jpg" /></a>
<em>photo by Nancy Munoz</em></p>
<p>On Thursday, over one hundred people marched up Franklin Street expressing solidarity with occupiers worldwide and reaffirming their opposition to the raid; many of them were taking the street for the first time. The following Monday, two hundred people from a wide range of demographics assembled at the police station, marched without a permit down a major boulevard to the town hall, and continued to block traffic and raise a ruckus for hours while some of them entered the city council meeting to speak out or disrupt it. Local government was in disarray, the police were powerless to do anything with public disapproval at an all-time high, and a diverse social movement was coming together around anarchist-initiated efforts. A solidarity march the same night <a href="http://atlanta.indymedia.org/local/atl-anti-police-march-nov21">in Atlanta</a> underscored how widely the ripples from the building occupation had spread.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/13b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/13a.jpg" /></a></p>
<p>This story demonstrates how swiftly a social movement can take off when a few individuals seize the right opportunity to push the envelope. By creating an open, irresistible space that transformed all who passed through it, the occupiers shifted the political landscape in a single night. The authorities were confronted with a no-win situation: they had to choose between ceding territory and discrediting themselves in the public eye. Swift follow-up enabled anarchists to turn subsequent attempts at repression into additional opportunities to forge connections and spread the virus of resistance.</p>
<p>As the economy worsens and social conflict intensifies, the conditions will be increasingly ripe for contesting the physical territory of capitalism. But this can only succeed and spread when it is viewed above all as a way to fight for <em>social</em> territory. The relationships we build in the process of fighting are the territory we win, even more than the plazas and buildings we seize.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/14b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/14a.jpg" /></a></p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/15b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/15a.jpg" /></a></p>
<p>&nbsp;</p>
<h5>    I do not feel that we lost, even when I walk down Franklin Street and read the &quot;condemned&quot; sign now posted out front. The sense of possibility remains; there is a new intensity when we mask up for a black bloc downtown, an aliveness that pulls on those around us. My only regret is that we never got to name our space. Its memory persists, but incommunicable, faceless. If I fight now, it is not only to honor that memory, but also to give it form for all those who can only imagine it in the abstract. We will be back. Next time we'll be ready.</h5>
<p>&nbsp;</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/16b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/16a.jpg" /></a></p>
<p>&nbsp;</p>