<h6 align="right" style="margin-right: 0px"><em><em>These narratives accompany <a href="/texts/recentfeatures/breaking.php">Breaking and Entering a New World</a>, the story of the occupation of a derelict building in Chapel Hill, North Carolina on November 12-13, 2011</em>.</em></h6>
<h1>Personal Accounts from a  Building Occupation Movement</h1>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/17b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/17a.jpg" /></a></p>
<h2>I.</h2>
<p>You've been passing the empty warehouse almost daily over the nine years you've lived in this town. Giant windows comprise the whole front fa&ccedil;ade of the building, displaying the dusty remains of some long-abandoned showroom, and to the right a short driveway buts into a flaking silver garage door. You've peered in those grimy windows, squinting to see what lies through the empty doorway in the wall of the front room visible to passersby like yourself. Biking home on warm summer nights you've wondered how a prominent spot on the main street in town could sit abandoned and rotting for over a decade. You've heard grumbles about the wealthy absentee landlord who sits on it from half a state a way, content to let it rot. You've mused in fleeting moments on the crazy things that could be possible in such an enormous space. You've noticed the snowballing amount of graffiti inside, lighting up the walls of that front room and&mdash;you can only imagine&mdash;the uncharted expanse that must lie beyond it. And as your bike rolls past it to work in the mornings, and then again on the way home, day after day, your curiosity ossifies into just another dull throb at the irrationality and injustice of life in this town. After all, what could you do?</p>
<p>Then all of a sudden, something has changed. Just a little way up the street, folks have been occupying the plaza in front of the post office with tents and tables and banners, just as people around the world have been occupying spaces in their cities. A rumbling current of outrage against the wealthy who exploit us with impunity has begun to reverberate, even in this recession-proof affluent college town. In blog posts and whispers, we hear of creative actions, conflicts with the police, illicit dreams. Something <em>is</em> changing&mdash;could it be our sense of what's possible?</p>
<p>And then, an evening at first like any other: biking up Franklin Street after a day spent partly at work, partly perusing the anarchist book fair where folks swap books, 'zines, strategies, and stories about the kinds of resistance they've seen or can imagine. Instead of heading home, you pull your bike over on a brick walkway, and there you see a surge of people, banners, a few drums, flowing out along the sidewalk then spilling across the street. There's a tight sense of anticipation, something crackling through the rowdy crowd, and you're drawn into it. You scan the street&mdash;where are the police?&mdash;and then you notice something you've never seen before; that same empty warehouse, but this time, with elegant banners spanning those grimy windows.</p>
<p>But wait&mdash;those banners are <em>inside</em> the building! And then you see the crowd of which you're now a part swelling on the sidewalk in front, and streams of people heading through a now-open silver garage door, and a dim golden glow emanating from the long-empty space. As you step onto the sidewalk and then the short driveway, you see shapes of people, friends and strangers, milling about beyond the banners in the front room. Someone to your right hands you a pamphlet, while on your left a bullhorn crackles to life. Across the street Friday night pedestrians are stopping to chat with the red-shirted valet parking attendants, who shrug their shoulders and fold their arms with intrigued smiles. You turn back around to the open door, just a few steps ahead. Through the gloom you can see shapes, outlines of a vast expanse, a canvas of possibility. Do you dare? You approach the doorway, your breath caught in your chest. And then, heart pounding, you step inside.</p>
<p>Vastness. Pure vastness. How can a building be so enormous? A single orange extension cord snakes across a vast concrete floor to a gerry-rigged contraption of silver flood lamps. The warm grey yellow light floods up and outwards to a massive ceiling of latticed wooden beams, casting criss-crossed shadows to the eaves of the roof beyond. The cinder block walls seem to extend out endlessly, an impossible distance, to a back door that must be a football field away. A few graffiti pieces dot the walls, but are swallowed up by the boundless expanse of gray walls and peeling dull green paint. A massive flaking metal marquee sign, splayed across the floor along a side wall, reads &ldquo;Carolina&rdquo; in an elegant cursive. Two revelers exchange gleeful shouts, then hoist the twelve-foot long rusty word up and shuffle past you to haul it out front, where a swelling crowd listens to a clean-cut speaker describing various possible futures for a building like this. But this isn't just a building anymore. This is an experiment. This is an adventure. This is a challenge.</p>
<p>Around you, people wander, suffused with wonder, pointing and exclaiming. Behind you in the front showroom music reverberates and the flicker of a projector has begun to dance across the walls. As you tentatively step forward, you recognize some people from the book fair earlier or from the occupation up the street, but also random folks walking by, hipsters you've seen a parties here and there, and others you don't recognize at all. Some stride out into the massive open space, gesturing animatedly, while others haul speakers into the front room or wooden pallets against the wall.</p>
<p>A decade's dust coats the floor, and you stifle a cough. But already a cluster of people to your right are chatting about who's headed out to get a push broom, where they can find a mop, who's got a can to line with the trash bags someone just dropped off.</p>
<p>Back across to your left in the front room, dozens of people are settling into a semicircle around a performer, whose enchanting voice begins to echo through the rafters, bringing goose bumps to your arms. And in front of you, some fifty yards off into the opposite corner of this massive space, you see a woman whose name you can't recall, though you know you've seen her on the bus before. She is alone, dressed in a burgundy sweater over blue jeans with a billowy white scarf, and she is whirling, dervish-like, to her own rhythm. As you stand watching, bewildered but with growing joy and awe, she twirls and spins, ducking and flowing with liquid grace, while the golden flood lamp light crosses the flickering of the projector against her elegantly moving silhouette to cast dazzling shadows across the empty wall. The voice from the front room rises, electrifyingly powerful, to a hair-raising crescendo, and still the white-scarfed woman crouches and whirls, her back to you, facing her reflection on the dirty gray wall, playing with the delicate motions of her shadow amidst the crisscrossing light.</p>
<p>Your head stretches back and you look up to the dark brown lattice of wooden beams along the massive ceiling, and as whistles and enthusiastic applause waft through the vastness, you feel a sense of vastness inside yourself, an expanding oceanic awe and excitement&mdash;a sense of possibility.</p>
<p>And then you realize that the question you resignedly asked yourself biking by this warehouse each day has irrevocably changed. Now you wonder: what could we do? And the possible answers seem to stretch out limitless before you, like dancing shadows dappling the cinder block walls.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/18b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/18a.jpg" /></a></p>
<h2>II.</h2>
<p>I am an anarchist. I have been in assemblies, street marches, and squatted buildings enough times to satisfy my curiosity and wear out my enthusiasm. I have also been in countless failures, countless hare-brained adventures rationalized by the conviction that &quot;something must be done.&quot; On Saturday night, I expected to take part in yet another.</p>
<p>I joined the march knowing little about people's plans. The idea of occupying a building was in the air, and I had a hunch that someone might go for it, but that didn't answer any of my questions. What was the goal? Would this be another publicity stunt, or did somebody actually think we could hold a space long enough to do something? When the police came, would the march continue, or would we stand our ground and wait to get arrested? I hoped someone had an exit strategy for whatever mess we got ourselves into. As for me, I figured I would tag along and try to be useful if things got hot.</p>
<p>My first glimpse of the building didn't exactly make me hopeful. A few people who had filtered inside were attempting to dance to techno music coming through some tinny laptop speakers, but other than that it looked like the abandoned, gutted warehouse that it was, not the future community center the leaflets described. A few banners taped to the front windows made me think with embarrassment of an SDS protest, with trite slogans and poorly drawn icons of &quot;radicalism.&quot; My friends and I milled around out front making up nonsense chants to mitigate the boredom. Some kid started preaching through a bullhorn to no one in particular. At least he was doing something. It seemed that exit strategies were too advanced for this plan; so far there was very little worth exiting.</p>
<p>Soon police started to arrive. A squad car parked in the middle of Franklin Street while two others circled the block, trying to figure out what was going on. A couple particularly brawny officers posted up across the street to help keep an eye on things. They looked bored too.</p>
<p>Someone suggested we bring in some furniture to make the space a little cozier. First up was a discarded magazine rack he had seen earlier that day; I helped retrieve it and marched it proudly through a throng of college kids outside the McDonald's. When we set it down, somebody else materialized with a box of zines and flyers, and began arranging them on the shelves. So, we had a library. That's a start.</p>
<p>By now, the police had gotten their orders and were moving in. Three of them crossed the street and made their way towards the entrance, flashlights in hand. A crowd of about fifty people, who had been dispersed throughout the space and on the sidewalks outside, quickly gathered between the cops and the gate, unsure what came next. Now the chants came in handy. Police are social animals; they get nervous when they can't hear their leaders' voices through the walkie-talkie. &quot;A-! Anti-! Anticapitalista!&quot; we shouted&mdash;a standby among anarchists, who always want to sound like they're from some other country, but evidently intimidating to the Chapel Hill PD, who must have thought we were reciting some ancient curse in Latin. Whatever it was, they backed off. We learned much later that the confrontation had indeed persuaded them not to evict that night, which they had originally planned to do.</p>
<p>For the moment, we had free rein to transform the space as the police abandoned their posts and contented themselves with occasionally cruising by. A generator and PA were brought in and the dance party began in earnest, followed by a show originally booked at a distant acquaintance's basement. I joined a crew gathering discarded pallets and cardboard from elsewhere in town, so that those who stayed the night would have something more comfortable to sleep on than a cement floor. Occupations are one thing when they exist only for the news cameras; they are quite another when they materially benefit the occupants. Behind the library we set up a table, which was soon laden with soup, bread, and three pans of delicious curries.</p>
<p>The next morning, there was plenty of coffee and grits with greens. Years of work with the Really Really Free Market had taught anarchists how to provide for a crowd. Overnight, more lumber and tools had been brought in, along with a washbasin and a propane stove and heater. A carpenter I hadn't seen in years was already building custom tables for the appliances. Some kind of meeting was being held in the front room, but I felt that meetings could wait for later. There was work to do.</p>
<p>In Europe, where the squatting movement has been a force for decades, the people who help establish a squat often have no intention of living there. Experience has shown that it is vitally important to build up the space as much as possible in the first forty-eight hours. In some cases, this means fortifications against police attack, but the most important effect is social. A dramatic transformation of a derelict building gives outsiders a reason to support the project, and it gives participants a tangible sense that they have something worth fighting for. If we did get evicted, I wanted to leave with a memory of what could have been. They could take away a building, but they couldn&rsquo;t destroy a shared determination to fight.</p>
<p>I took it upon myself to let in a little light. The western and southern walls of our squat were filled with eight-foot windows, all of which had been boarded up for years. The only glass left uncovered was the display room on the north side facing the street. The property owner had probably been worried about kids throwing rocks through the panes facing the alley, but I expected we would face less hostility from strangers than this multimillionaire.</p>
<p>The plywood itself presented some problems, though. It was held on by self-tapping bolts that could only be removed with a hex bit, and the wood had swollen around them so that each one had to be dug out with a chisel before the socket would fit on. If I'd been getting paid, I would have cursed my boss for every stripped screw and awkward angle. This was for me, though. A couple friends joined in, and another crew started taping clear plastic sheeting over the handful of panes that were already broken. </p>
<p>Soon, we could see the results with each sheet of plywood we brought inside, destined to be a table or a bathroom wall. The light was pouring in, illuminating surfaces that had not seen the sun in a decade and dust still hanging in the air from the morning's monumental sweeping campaign. For me, this was a profound moment. When the building was just a number in a ledger-book, it had no need for light. The physical change signified something deeper: what mattered here, for the first time, was life&mdash;not real estate, but human needs. I fantasized with my workmates about murals and gardens as we took down the final boards and brought them in, carefully gathering the screws for future use. The space was ours.</p>
<p>Everybody who has felt the injustice of this world dreams of revenge from time to time. I myself find it hard to trust those who only talk about building a new world, about peace and community, and never about destroying the world we know. I wonder if their reality has been different than mine, or if their positive attitude serves some other agenda. My skepticism when I arrived at our future community center was, among other things, a doubt that a group of people clearly unprepared for militant confrontation could pose any threat to the powers enforcing daily misery in this inhospitable world. In the twenty-one hours that we held the space, that skepticism turned to joy, a sense of imagination and possibility that I seldom associate with political action. We were living in a world where nothing was scripted, and it seemed like it might last.</p>
<p>When the raid came, I was across town gathering resources for the space. I rushed back, but it was too late: our squat looked like a conquered city, and my comrades were lying on the ground at gunpoint. I stood across the street shouting and jeering until my voice gave out, until the last arrestees had been carted off in the brand new eco-friendly bus that Chapel Hill had sent for them. The banners that had embarrassed me the night before came down as we watched, powerless&mdash;except for two hanging overhead, too high for the cops to tear at them, that proclaimed, with a mix of tragic pride and irony, &quot;OCCUPY. EVERYTHING.&quot;</p>
<p>In a press conference held the next day to justify the use of force, the police chief explained that anarchists had blocked the front windows with banners so that officers could not see what dangers might await them inside. Their assault rifles held off a fear of the unknown. I winced a little, but couldn't help laughing too. We didn't block the windows, we opened them! It was not obscurity they feared, but unpredictability&mdash;the unpredictability of freedom, the same unpredictability that made them retreat before a chanting crowd that first night. They overreacted because they knew nothing else to do; all their training revolves around one nonnegotiable tenet, that someone must be in control.</p>
<p>I do not feel that we lost, even when I walk down Franklin Street and read the &quot;condemned&quot; sign now posted out front. The sense of possibility remains; there is a new intensity when we mask up for a black bloc downtown, an aliveness that pulls on those around us. My only regret is that we never got to name our space. Its memory persists, but incommunicable, faceless. If I fight now, it is not only to honor that memory, but also to give it form for all those who can only imagine it in the abstract. We will be back. Next time we'll be ready.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/19b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/19a.jpg" /></a></p>
<h2>III.</h2>
<p>At twice a day for three years, I may have walked by the abandoned car dealership on the main strip in my small town literally two thousand times. Having one foot in the local graffiti community I&rsquo;d also been inside a few times. It was eerie and quiet, dark and dead inside. The inside was dark but the entire front was giant windows so one had to move slowly and keep a bit low while exploring the 10,000 square foot art gallery.</p>
<p>Six months later, we left the anarchist book fair with banners and drums and 75 excited people in tow. As the march approached the dealership I could already see our friends with black masks on, putting up giant banners in the front windows: &ldquo;Capitalism left this building for dead (Giant circle A) We brought it back to life&rdquo;&mdash;&ldquo;Stop taking orders, Start taking over&rdquo;&mdash;and, of course, &ldquo;Occupy Everything.&rdquo; By the time we actually got to the building, there was a projector casting footage of the Oakland general strike on the main wall visible through the windows, while techno music was bumping from the now open garage door. We marched in and the crowd followed us with sounds of surprise, delight, and excitement as they saw the massive space illuminated by clip lights affixed to a ladder in the center of the room. Pamphlets were distributed offering a floor plan for all the amazing things this space could be and a manifesto about reclaiming the public space capitalism has stolen from us.</p>
<p>After the movie, folks gathered back outside. The police had arrived and people seemed confused and perhaps a bit nervous. Somebody gave a rousing speech and the crowd started chanting at the police, who quickly backed off and did not return for the evening. Once the boys in blue had retreated, the mood lightened and people flooded back into the front room where a DJ was spinning popular dance music; the protest footage had been put on loop in the background.</p>
<p>This was what we had needed. The tent city occupation down the street was a constant battle: cold, wet, under siege by drunks&hellip; conflicting beliefs and personalities had been threatening to tear us apart, and as the conditions got worse and the general assemblies became a chore numbers had dwindled, further killing morale. But tonight we danced! Differences aside, we smiled and discussed the possibilities of moving the tent city into the building for the winter; a yoga instructor scheduled a class for 4 p.m. the following day, the first event at our new community center.</p>
<p>I stepped out to get some air. A couple approached me and asked &ldquo;What&rsquo;s going on here?&rdquo;</p>
<p>I handed them the pamphlet and explained, &ldquo;We&rsquo;re turning this building into a community center.&rdquo;</p>
<p>The man&rsquo;s face lit up. &ldquo;That&rsquo;s great! I worked as a chef next door&nbsp;for years and this place just rots here!&rdquo;</p>
<p>I nodded and added matter-of-factly, &ldquo;It&rsquo;s an illegal occupation.&rdquo;</p>
<p>&ldquo;Even better!&rdquo; he said enthusiastically.</p>
<p>People started returning from around town with desks, couches, pallets, and cardboard to sleep on since it seemed we&rsquo;d be staying the night. Folks I&rsquo;d seen from all over town were coming by to check things out after a tweet and some text messages went out; the music and dancing continued until well after the bars had let out.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/20b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/20a.jpg" /></a></p>
<h2>IV.</h2>
<p>After the more diplomatic and physically imposing among us successfully encouraged the two semi-hostile drunks to stagger on their way, we shut the garage door and battened down the hatches for the night. The dozen or so of us who were still awake gathered for one last little council to plan how to handle the night. I scanned the warehouse; suddenly the massive space seemed more imposing, a bit creepy, with just two lamps casting a dim light through the enormous cavern. Surveying the scene, it seemed that in addition to the handful of us chatting quietly that several others had already bedded down for the night. A trio of oogles were squished in a corner, their dog still wandering around sniffing things. A lone crust punk from out west was asleep against the wall, half sitting up on a bare pallet, arms folded. Does anyone have a spare blanket for that guy? Two sleeping bags jutting out from the wall near the front room remained inert, occupied by a mysterious pair who had presumably slept through the performances and three-hour dance party; maybe they just had really effective earplugs?</p>
<p>As we discussed night watches for security (two folks out front, one out back, one inside), where to pee and poop (in a bucket in the far corner), how to alert each other in case of a raid or other emergency (whistles), and other crucial details, I tried to keep up and contribute, but I was fading fast. I'd been sick for a week already, and the combination of a long day tabling at the anarchist book fair, the insane adrenaline rush of the march and occupation, euphoric dance party overexertion, general stress and uncertainty about police response and random drunks, and overall overwhelmingness had taken their toll. As soon as we broke up, I headed wearily over to the two pallets I'd laid out against the far right wall.</p>
<p>Now that it was 3 a.m., a deep November chill had set in, and I knew it would be a challenge to stay warm. Fortunately my sleeping bag, borrowed from the outdoor occupation up the street, proved up to the task, reinforced by the thin blanket I draped over it. I snuggled in&mdash;hey, these pallets aren't that uncomfortable after all!&mdash;and wrapped a thin undershirt over my nose and mouth as an improvised dust mask.</p>
<p>A deep quiet settled in, periodically ruptured by inexplicable squeaks and groans from the walls or slurred laughter from drunken pedestrians outside. Some twenty or twenty-five feet overhead, I could see the wooden beams of the ceiling faintly in the dim light of the remaining lamps. The sound of my friend on night watch pacing slowly from front door to back provided a bit of reassurance. Still, I couldn't sleep amid the excitement, the anxiety, the odd noises and the unfamiliar setting. When was the last time someone slept in this building, I wondered? Graffiti writers had been in here, as the walls testified, but there weren't any signs of overnight or longer-term visitors before we entered. Was I among the first of a new generation? Who would sleep here tomorrow night, the night after? How would we keep each other safe, ensure consent and respect, have somewhere more private and comfortable to shit than a plastic bucket in a dark corner? Would the police really let us hold the space? Would the owner care? Would they use inspections officers and fire codes to shut us down, strangle us in red tape? How will the media report on it? What kinds of events could we have here? What would &quot;we&quot; answer all of these questions? Should I find someone to sublet my room and move in here? Will I get asthma or brown lung disease or something from all this dust?</p>
<p>These and ten thousand other questions ricocheted through my skull as the night hours slowly peeled away. And it wasn't until I noticed the daylight seeping in through the front windows and heard the murmurs of the night watch folks chatting with the people who'd arrived to relieve them that I realized I had fallen asleep at all. Somehow we'd made it through the night, I pondered sleepily. What the hell would the day hold?</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/21b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/21a.jpg" /></a></p>
<h2>V.</h2>
<p>Shortly before the raid, I got a call informing me that police had been seen congregating not far from the occupation. I began to walk around the building, spreading this news. As I finished telling people out back, two white, unmarked SUVs pulled up to the back of the building. As soon as I saw them moving towards the building, before they announced themselves as &quot;police,&quot; I raced to the front of the building, repeatedly yelling &quot;Cops!&quot; Not many people had been inside; I saw some people move outside, while others who had already been outside looked around in alarm.</p>
<p>When I reached the front of the building, I took a few steps down the driveway and suddenly saw assault-rifle-wielding paramilitary troops flying around the corner of a neighboring building. They were shouting for us to get down&mdash;&quot;Face down on the pavement&quot;&mdash;as they cycled the barrels of their rifles from me to those around me. I hit the deck almost instantly. The entire event was so surreal that it didn't even feel like it was happening to me. As I lay with my face in the pavement, I heard someone to my side ask in a somewhat strained voice if the cop standing over him was going to shoot him; I later learned the cop was shoving a gun into the man&rsquo;s back as he lay on the pavement. I couldn't see what was going on and figured it was best to lie still. I dimly registered being given instructions about my hands and the subsequent tightening of handcuffs; I attempted to get my sleeves between the plastic zip-ties and my skin, as nerve damage is&nbsp;frighteningly&nbsp;common with zip-ties.</p>
<p>I was finally rolled onto my back and seated on a low wall. At this point, I looked around and realized that none of the cops had any sort of crowd-dispersal equipment. Whereas I had seen batons, riot shields, and &quot;non-lethal&quot; weapons like tear-gas, mace, and rubber bullets at the evictions of numerous other occupations, here I saw only tactical vests, extra magazines, and assault rifles. At least one of the officers did have a taser; however, it was holstered and appeared to be incredibly awkward to access, especially compared to the live-ammunition firearm in his hand. As arrestees were loaded onto the&nbsp;public transit&nbsp;bus with a large Wells Fargo ad on the side, to be transported to the Hillsboro jail, I couldn't help but reflect on the violence displayed towards people who had given no indication of possessing weapons. The fact that the CHPD had willfully defended a decrepit building's vacancy by threatening my life and the lives of other non-violent protesters struck me, and strikes me, as abhorrent.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/22b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/22a.jpg" /></a></p>
<h2>VI.</h2>
<p>When I saw the occupying of the old Chrysler building, it opened a part of myself which had been closed off and boarded up, much like the building itself. I saw people with smiles helping each other clean and build things. There were so many different people with the desire to come together&mdash;it was beautiful, and has been carved into my mind ever since. It made me want to see more positive things for my community, things that would somehow ricochet throughout it. I desired hope, which I once believed to be a weak sentiment. I desired to feel helpful instead of helpless. I desired to believe people would come together for a change, for something other than a sports game. Now I feel like that is more possible. So many people caught a glimpse of potential in that building. If our lives could be shifted away from money and more towards needs, things like a community center could happen.</p>
<p>But instead of a community center being set up, I returned to a police raid. Machine guns were the only weapons visible&mdash;no tear gas, no rubber bullets, just loaded machine guns with plenty of extra magazines handy. It was chilling to witness a variety of people being pushed with guns, handcuffed, and illegally searched. A large group of people formed to support the occupiers and &ldquo;Shame!&rdquo; the police.</p>
<p>A whole new level had been shown to me. They are afraid of us getting together on our own terms and will attempt to divide us at all costs. This is our movement&mdash;a movement for the people, by the people. This is not a protest, this is <em>progress.</em></p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/23b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/23a.jpg" /></a></p>
<h2>VII.</h2>
<p>We gathered after the general assembly for the solidarity march with all the occupations around the country facing eviction and police brutality. But unlike our solidarity marches of years past, tonight we marched for ourselves too. Since the raid, it hadn&rsquo;t been uncommon to turn on the news and hear people referring to &ldquo;New York, Oakland, Chicago, and Chapel Hill.&rdquo; Our quiet little town had become a spectacle; the incident had made the front page of every local paper for days in a row, and it seemed like everyone I passed on the street was talking about it.</p>
<p>An anti-police march a few nights previous had brought 100 people into the street blocking traffic, wearing masks&mdash;itself a crime in our state, for which our friends at Occupy Asheville were facing charges&mdash;and antagonizing the police, who were terrified of winding up on the national news again for attacking protesters already protesting police brutality. Now our numbers swelled to over a hundred and twenty and we took the street without masks. While the occupation at Peace and Justice Plaza and the occupation of the abandoned car dealership had been clearly defined as separate events, it was obvious that each benefitted from the other&rsquo;s existence. The month-long, harmless encampment had established us as &ldquo;friendly neighborhood protesters,&rdquo; while the squatted social center had (literally) overnight brought publicity and a sensation that powerful action was possible, letting the country know that Occupy Chapel Hill was a big deal.</p>
<p>The police cars flanked us as we marched back to the sight of the raid and then down to the new high-rise apartments which members of our community had caught felony riot charges for protesting just a few months earlier. The cops were on the defensive and we knew it. We dared them to fuck with us, all parties involved fully aware that the whole nation would hear about any police misconduct. Finally, we returned to the occupation where rousing speeches were made and flyers were distributed for the next march, only a few days later.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/occupych/24b.jpg" rel="lightbox[occupych]"><img src="https://cloudfront.crimethinc.com/images/occupych/24a.jpg" /></a></p>
<p>&nbsp;</p>