<p align="center"><a href="https://cloudfront.crimethinc.com/images/conspiracy/1b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/conspiracy/1a.jpg" width="500" height="365"></a></p>
<h1 style="margin-bottom: 0px">The Age of Conspiracy Charges</h1>
<p>&nbsp;</p>
<p>Looking back over the past decade, it appears that North American law enforcement agencies are increasingly utilizing conspiracy charges to target anarchists and others involved in radical communities. We&rsquo;ve composed <a href="#a">a review of recent conspiracy cases</a> in hopes of analyzing this.</p>
<p>If conspiracy charges are becoming central to the state's strategy against anarchists, it is imperative that we develop a strategy of our own to respond to this and seize the initiative rather than simply reacting over and over to individual cases. This text is a humble effort in that direction, in hopes of inspiring more thoughtful reflections from our comrades.</p>
<p>Conspiracy charges are convenient for police and federal agents in that they do not require authorities to prove that any actual illegal activity took place, only shared intent. In that regard, they are an ideal weapon to wield against ideologically-based communities; they also lend themselves to <a href="http://www.crimethinc.com/blog/2009/06/24/towards-a-collective-security-culture/">government agents&rsquo; efforts to entrap na&iuml;ve activists</a>.</p>
<p><a href="http://friendsoftortuga.wordpress.com/2010/01/27/a-new-year-a-new-tortuga-house-update/" target="_blank">There are also signs</a> that the authorities may be attempting to fabricate evidence for larger conspiracy cases on a national scale. It&rsquo;s impossible to know whether these will ever pan out, but it&rsquo;s certainly better to be prepared.</p>
<p>What can we do to respond to this strategy of repression? Here are some basic starting places:</p>
<h3>1. Don&rsquo;t let the state intimidate us out of confrontational public organizing.</h3>
<p>The state targets public organizers like the <a href="http://shac7.com/" target="_blank">SHAC 7</a>
or the <a href="rnc8.org" target="_blank">RNC 8</a> because they are effective. Public organizing groups  have been essential in creating the necessary conditions for anarchists to determine the character of recent mobilizations such as those against the <a href="http://www.crimethinc.com/texts/atoz/rncdnc.php" target="_blank">2008 Republican National Convention</a> and the G20 summits of <a href="http://www.crimethinc.com/texts/atoz/g202.php" target="_blank">2009</a> and <a href="http://www.crimethinc.com/texts/recentfeatures/toronto2.php" target="_blank">2010</a>. The same goes for local and ongoing campaigns.</p>
<p>Even when it is framed as a strategic choice, retreating from public organizing can only play into the hands of the authorities. Repression is intended to cause militants to back away from engaging with the public, losing connection with a broader social base and deepening the false dichotomy between passive &ldquo;community organizing&rdquo; and clandestine direct action. This is not to say everyone must organize publicly&mdash;on the contrary, one function of public organizing is to prepare a favorable ground for more generalized and anonymous actions&mdash;but that it is a necessary aspect of anarchist struggle.<br />
</p>
<h3>2. Minimize our vulnerability to conspiracy charges.</h3>
<p>There are many ways we can do this. Perhaps the most obvious is to <a href="http://crimethinc.com/texts/recentfeatures/security.php" target="_blank">practice appropriate security culture</a>, sharing sensitive information on a need-to-know basis and doing our best to keep informants out of our circles. Security culture is not only for those who may be party to illegal activity; it is important for everyone connected to networks that the state is interested in mapping or disrupting. Some hypothesize that one of the reasons the authorities didn&rsquo;t bring conspiracy charges against organizers of the <a href="http://crimethinc.com/texts/recentfeatures/g202.php">Pittsburgh G20 protests</a> was that, in contrast to the RNC Welcoming Committee, individuals suspected of being police agents were not permitted into the coordinating group. The closer informants are to us, the easier it is for them to prepare cases of some kind, however fabricated.</p>
<p>Likewise, it&rsquo;s important to keep an eye out for <a href="http://www.crimethinc.com/blog/2009/06/24/towards-a-collective-security-culture/">federal bounty hunters preying on na&iuml;ve young activists</a>. Often they prefer to target the least experienced or connected individuals in a social milieu instead of tangling with longtime militants. We can also inoculate ourselves against disruption by sorting out internal conflicts before they offer infiltrators or prosecutors opportunities to divide us against each other.</p>
<p>After so many conspiracy cases have been brought against anarchists, we should no longer be surprised by new ones. We need to be thinking in advance about how to respond to them; that means preparing legal support structures and bail funds even when we don&rsquo;t have reason to believe we&rsquo;re about to be targeted. It also means being intentional about how we conduct ourselves so we don&rsquo;t make it easier for prosecutors to demonize us. In the words of grand jury resister <a href="http://davenportgrandjury.wordpress.com/" target="_blank">Carrie Feldman</a>,</p>
<h6>Does whatever value I gained from wearing an <a href="http://en.wikipedia.org/wiki/Animal_Liberation_Front" target="_blank">ALF</a> shirt in high school outweigh the fact that it was later used to smear me in court and justify holding me in jail for four months? Mostly I just want to say, yeah, fuck&rsquo;em. Bring it on. But I think the important thing is to always be weighing that, be aware of it. Be ready to own everything you say and do. Don&rsquo;t just front or talk a militant line to sound cool. When you&rsquo;re reading about it in your FBI file you&rsquo;ll want to have said things worth standing by. </h6>
<p>Whenever someone is targeted with a politically motivated conspiracy case, it&rsquo;s important that we mobilize the very best legal defense we can. This means hiring good lawyers, not just accepting lazy and often outright backstabbing court-appointed defenders. Every conspiracy case against radicals sets a precedent for more of the same; defending one of us is literally defending all of us. Good lawyers serve two functions. First, they intimidate the state, which will be more likely to bargain or drop charges if it knows pressing them will be expensive and risky. Second, they can win cases or get them thrown out, as recently occurred in the case of the <a href="http://www.greenisthenewred.com/blog/aeta-4-case-thrown-out-dismissed/3015/" target="_blank">AETA 4</a>. Raising the money to defend one person effectively can save a lot more money and heartache in the long run.</p>
<p>Public support campaigns are equally important. On one side, this means going public when you are targeted&mdash;both so you can receive support and so that repression will be brought into the spotlight. On the other, it means organizing long-term support for defendants, so they will feel invested in answering to the community and so the authorities will have to factor in public relations challenges when they consider whether to target us. Support campaigns can target the most vulnerable individuals in the power structure; the supporters of the <a href="rnc8.org" target="_blank">RNC 8</a> did this by concentrating on county attorney Susan Gaertner, who was eventually forced to    <a href="http://rnc8.org/2009/04/terrorism-dropped-conspiracy-remains/" target="_blank">drop the terrorism charges</a> against the defendants.</p>
<p>Finally, though this should go without saying, we can protect ourselves from conspiracy charges simply by not cooperating with the authorities. Of the cases detailed below, many of them would never have gotten off the ground if people had not been intimidated into making statements against their former comrades. Nobody talks, everybody walks&mdash;that goes for our whole community as well as specific groups of defendants.</p>
<p>Defendants who cooperate with the government never come out ahead. As detailed below and elsewhere, not only do they lose friends and community support, they rarely get significantly shorter sentences&mdash;and doing prison time is much harder as an informant.<br />
</p>
<h3>3. Craft an effective narrative discrediting the state's use of conspiracy charges and circulate it to the general public.</h3>
<p>If the authorities come to rely on pressing conspiracy charges against anarchists as a central strategy of repression, we must take advantage of the ways this makes them vulnerable. Many in our society&mdash;and not just radicals&mdash;are uncomfortable with the idea of people being persecuted for thought crime. We need to find ways to address people outside our social and political circles about the prevalence of conspiracy charges, so as to utilize this opportunity to discredit the state and delegitimize conspiracy-based cases. The broader the range of people who disapprove of this tactic, the more the hands of the authorities will be tied.</p>
<p>Most of this work has yet to be done. If you are concerned about government repression, consider the ways you can approach others outside radical communities about this issue.</p>
<p>When we talk about conspiracy charges and witch hunts, it&rsquo;s important to emphasize that we&rsquo;re talking about the state, which <em>exists</em> to carry out violent repression. As long as there are inequalities and injustices, there will be resistance, and those in power will attempt to repress it. If we take ourselves seriously as a revolutionary movement, we need to see ourselves in the larger context and histories of resistance movements and the repression they have faced; we would do well to learn both from the successes and the failures of the past. It&rsquo;s also important to remember that repression is a daily fact of life for countless people in communities on the wrong end of power and privilege; anarchists are far from exceptional in this regard.<br />
</p>
<p><p align="center"><a name="a" id="a"></a><a href="https://cloudfront.crimethinc.com/images/conspiracy/2b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/conspiracy/2a.jpg" width="500" height="663"></a></p>
<h2>Appendix: An Incomplete Review of Recent Conspiracy Cases</h2>
<p>This is hardly a comprehensive survey of conspiracy charges pressed against anarchists and other radicals in recent history. However, it does cover some of the landmark cases that created the current context, as well as ongoing cases that will set important precedents.</p>
<p>Altogether, this review encompasses charges pressed against nearly a hundred individuals. The cases themselves vary from fairly conventional uses of conspiracy charges to outright entrapment and examples that stretch the legal definition of conspiracy even by prosecutors&rsquo; standards.<br />
</p>
<h5>2004</h5>
<h3><a href="http://shac7.com/" target="_blank">The SHAC 7</a></h3>
<p>In the early days of the 21st century, although several hearings before Congress had brought governmental pressure to bear against the animal liberation movement, efforts to quash direct action organizing by capturing and prosecuting participants proved fruitless. Finally, a New Jersey federal grand jury indicted seven individuals and the organization <a href="http://www.crimethinc.com/texts/atoz/shac.php" target="_blank">Stop Huntingdon Animal Cruelty USA</a> on charges of animal enterprise terrorism under the <a href="http://abolishtheaeta.org/web/" target="_blank">Animal Enterprise Protection Act</a> on May 26, 2004. Charges of interstate stalking and conspiracy to use a telecommunications device to harass others were also included in the indictment. It has been said that the defendants were essentially targeted for running a website advocating direct action.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/conspiracy/3b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/conspiracy/3a.jpg" width="500" height="331" style="margin-bottom: 2px"></a><em><br />
The SHAC 7</em></p>
<p>The SHAC 7 were convicted on March 2, 2006 under the AETA. Their conviction probably emboldened law enforcement agencies to utilize conspiracy charges to target radicals nationwide, especially in cases in which simple criminal charges could not be pressed convincingly or did not appear to offer enough of a deterrent.<br />
</p>
<h3><a href="http://en.wikipedia.org/wiki/Rod_Coronado" target="_blank">Rod Coronado</a></h3>
<p>On December 2, 2004, federal prosecutors indicted Rod Coronado on conspiracy charges related to a local environmental group interfering with mountain lion hunting in Sabino Canyon in March 2003. The indictment came just seven days before Coronado was to stand trial for three lesser misdemeanor charges filed after his arrest in Sabino Canyon on March 26. The new charge carried a maximum penalty of six years in prison.</p>
<p>Coronado faced this among many other charges in a concerted campaign of harassment across several years. On December 13, 2005, he and codefendant Matthew Crozier were found guilty of felony conspiracy to interfere with or injure a government official, misdemeanor interference with or injury to a&nbsp;forest&nbsp;officer, and misdemeanor depredation of government property.&nbsp;Coronado was sentenced on August 6, 2006 to eight months in prison, three years supervised probation, and fined $100. Crozier was sentenced to 100 hours community service, three years probation, and a $1000 fine.<br />
</p>
<h5>2005</h5>
<h3><a href="http://www.crimethinc.com/texts/atoz/greenscared.php" target="_blank">Operation Backfire</a></h3>
<p>In December 2005 and January 2006, with assistance from the Bureau of Alcohol, Tobacco, Firearms, and Explosives (ATF), the FBI indicted six women and seven men on a total of 65 charges, including arson, conspiracy, use of destructive devices, and destruction of an energy facility. The defendants were named as Joseph Dibee (still at large), Chelsea Dawn Gerlach, Sarah Kendall Harvey (n&eacute;e Kendall Tankersley), <a href="http://www.supportdaniel.org/" target="_blank">Daniel McGowan</a>, Stanislas Meyerhoff, Josephine Overaker (still at large), <a href="http://www.supportjonathan.org/" target="_blank">Jonathan Paul</a>, Rebecca Rubin (still at large), Suzanne Savoie, Justin Solondz (currently <a href="http://www.nytimes.com/2009/11/28/world/asia/28china.html?_r=2&amp;hpw" target="_blank">in custody in China</a>), <a href="http://www.crimethinc.com/blog/2007/12/22/on-darren-thurston&rsquo;s-statement-&ldquo;fired-back&rdquo;/" target="_blank">Darren Thurston</a>, Kevin Tubbs, and <a href="http://www.supportbriana.org/" target="_blank">Briana Waters</a> (not charged with conspiracy). A number of other unindicted co-conspirators were also named, including Jacob Ferguson, Jen Kolar, and Lacey Philabaum, all of whom joined Meyerhoff, Gerlach, Harvey, Savoie, Tubbs, and Thurston in accepting plea deals in return for informing to the government. Another alleged co-conspirator, William Rodgers, committed suicide while in police custody. Nathan Block and Joyanna Zacher were added in a superseding indictment in June 2006.<br />
</p>
<h5>2006</h5>
<h3><a href="http://supporteric.org/" target="_blank">Eric McDavid</a></h3>
<p>In January 2006, as a result of a separate investigation but widely reported as an extension of Operation Backfire, three more individuals&mdash;Eric McDavid, Zachary Jenson, and Lauren Weiner&mdash;were arrested in Auburn, California for conspiring to damage facilities &ldquo;by explosive or fire.&rdquo; Jenson and Weiner took cooperating plea bargains, selling out McDavid, who was convicted on all counts September 27, 2007 and was sentenced in May 2008 to nearly 20 years in prison.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/conspiracy/4b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/conspiracy/4a.jpg" width="500" height="318" style="margin-bottom: 2px"></a><em><br />
Eric McDavid</em></p>
<p>The McDavid case is notable because of the role of a paid informant, &ldquo;Anna,&rdquo; who essentially entrapped the defendants by utilizing money and flirtation to lure them into discussions about illegal activity. It subsequently received <a href="http://www.crimethinc.com/blog/2008/04/22/elle-magazine-retraction-or-hoax/" target="_blank">coverage in Elle magazine</a> among other venues.<br />
</p>
<h3><a href="http://portland.indymedia.org/en/2007/06/360368.shtml" target="_blank">Sadie and Exile</a></h3>
<p>Nathan Fraser Block, aka &ldquo;Exile,&rdquo; and Joyanna Lynn Zacher, aka &ldquo;Sadie,&rdquo; were arrested in February 2006 in Olympia, Washington in connection to the Jefferson Poplar Farm fire which occurred in 2001 in Clatskanie, Oregon. </p>
<p>In November 2006, Joyanna Zacher and Nathan Block each pled to one count of conspiracy, attempted arson, plus multiple arson charges from actions at the Joe Romania Chevrolet car dealership in Eugene and the Jefferson Poplar tree farm, as part of a global resolution agreement with prosecutors in the Operation Backfire case. Daniel McGowan and Jonathan Paul entered plea deals in the same hearing, resolving all the outstanding Operation Backfire cases. All four defendants refused to assist in government investigations of other activists. It is worth noting that, compared to the cooperating defendants in the Backfire case (see chart, as a <a href="http://crimethinc.com/texts/images/green_scare_chart.gif" target="_blank">GIF</a> or <a href="http://crimethinc.com/texts/images/green_scare_chart.pdf" target="_blank">PDF</a>), the non-cooperating defendants received proportionately shorter sentences.<br />
</p>
<h5>2007</h5>
<h3><a href="http://www.freethesf8.org/" target="_blank">The San Francisco 8</a></h3>
<p>Eight Black community activists, including former Black Panthers, were arrested January 23, 2007 on charges related to the 1971 killing of a San Francisco police officer. Similar charges were thrown out after it was revealed that police had used torture to extract confessions when some of the same men were arrested in New Orleans in 1973.</p>
<p>Richard Brown, Richard O'Neal, Ray Boudreaux, and Hank Jones were arrested in California. Francisco Torres was arrested in Queens, New York. Harold Taylor was arrested in Florida. Herman Bell and Jalil Muntaqim&mdash;had already been held as political prisoners for over 30 years in New York State prisons. The men were charged with the murder of Sgt. John Young and conspiracy encompassing numerous acts between 1968 and 1973. Bail amounts were originally set between three and five million dollars each.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/conspiracy/5b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/conspiracy/5a.jpg" width="500" height="375" style="margin-bottom: 2px"></a><em><br />
San Francisco 8 members Francisco Torres, Ray Boudreaux, Richard Brown, Harold Taylor, and Hank Jones with supporters</em><br />
</p>
<p>Herman Bell and Jalil Muntaqim were sentenced to probation and time served, after Bell agreed to plead to voluntary manslaughter and Muntaqim to conspiracy to voluntary manslaughter. All charges were then dropped against Brown, Jones, Taylor, and Boudreaux, with the prosecution admitting it had &ldquo;insufficient evidence&rdquo; against them. Charges had already been dropped against O'Neal in 2008.</p>
<p>Francisco Torres is the last one still facing charges; he maintains his innocence and will appear in court on August 10.<br />
</p>
<h5>2008</h5>
<h3><a href="http://supportmariemason.org/" target="_blank">Marie Mason</a></h3>
<p>In March 2008, Marie Mason, Frank Ambrose, Aren Burthwick, and Stephanie Lynne Fultz
were <a href="http://www.foxnews.com/story/0,2933,336931,00.html" target="_blank">arrested and charged with conspiracy to commit arson</a>; Mason and Ambrose faced additional charges related to acts of property destruction that occurred in 1999 and 2000. It came out that Ambrose, Mason&rsquo;s ex-husband, had been assisting the FBI extensively in investigating environmental organizing since 2007; despite this, his plea bargain resulted in a <a href="http://news.infoshop.org/article.php?story=20081021200843765" target="_blank">nine year sentence</a>, two years more than the prosecutor had requested. Burthwick and Fultz also negotiated cooperating deals with the Justice Department, agreeing to help in the investigation of Mason. Mason was threatened with a&nbsp;life sentence before <a href="http://news.infoshop.org/article.php?story=20080914205631210" target="_blank">accepting a&nbsp;plea bargain in September 2008</a>, in which she also admitted involvement in 12 other acts totaling more than $2.5 million of property damage.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/conspiracy/6b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/conspiracy/6a.jpg" width="500" height="355" style="margin-bottom: 2px"></a><em><br />
Marie Mason</em><br />
</p>
<p>Mason was&nbsp; sentenced on February 5, 2009 in federal court in Lansing, Michigan. She received almost 22 years, the longest sentence of any <a href="http://www.greenisthenewred.com/blog/green-scare/" target="_blank">Green Scare</a> prisoner. The sentence is currently being appealed.<br />
</p>
<h3><a href="http://www.sfreporter.com/santafe/article-4488-forest-for-the-trees.html" target="_blank">Rhinelander</a></h3>
<p>Bryan Rivera, aka Bryan Lefey, was arrested July 2008 on charges relating to a July 2000 Earth Liberation Front action at the U.S. Forest Service Facility in Rhinelander, WI, where genetic research was being conducted on trees.</p>
<p>Katherine Christianson was originally named as a co-conspirator. Government informant <a href="http://snitchwire.blogspot.com/2009/03/snitch-ian-wallace-sentenced-to-three.html" target="_blank">Ian Wallace</a>, who was cooperating in investigations into other ELF actions, got involved and named Aaron Ellringer and Daniel McGowan as additional co-conspirators. Christianson and Ellringer eventually became government informants. All were convicted; Ellringer received four days, Christianson 2 years, Lefey 3 years, Wallace 3 years for this and related actions.</p>
<p>Green Scare prisoner <a href="http://www.supportdaniel.org/" target="_blank">Daniel McGowan</a>, already serving a 7 year sentence, had also been involved in the Rhinelander action, but was not prosecuted federally for it as stipulated in his 2006 non-cooperating plea agreement. McGowan steadfastly refused to cooperate in the Rhinelander investigation, and in summer 2008 his federal sentence was suspended for a brief time while he was held in civil contempt for refusing to testify before a grand jury about the action.<br />
</p>
<h3><a href="http://rnc8.org/" target="_blank">The RNC 8</a></h3>
<p>In what was the first&nbsp;use of criminal charges under the 2002 Minnesota version of the Federal Patriot Act, Ramsey County prosecutors charged eight alleged organizers of protests against the <a href="http://www.crimethinc.com/texts/atoz/rncdnc.php" target="_blank">2008 Republican National Convention</a> with Conspiracy to Riot in Furtherance of Terrorism. The 8 faced up to seven and a half years in prison under the terrorism enhancement associated with the charge, which allows for a 50% increase in the maximum penalty. They later received more charges&mdash;conspiracy to commit property damage, conspiracy to commit property damage in furtherance of terrorism, conspiracy to riot, and the original charge.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/conspiracy/7b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/conspiracy/7a.jpg" width="500" height="319" style="margin-bottom: 2px"></a><em><br />
The RNC 8</em><br />
</p>
<p>In early April 2009, <a href="http://rnc8.org/2009/04/terrorism-dropped-conspiracy-remains/" target="_blank">county attorney Susan Gaertner dropped the charges</a> of Conspiracy to Commit Riot in Furtherance of Terrorism and Conspiracy to Commit Criminal Damage to Property in Furtherance of Terrorism. This occurred shortly after one of the defendants appeared on MSNBC and petitions to drop all the charges were delivered to Gaertner&rsquo;s office, including a resolution from the 17,000-member Duluth Central Labor Body in support of the RNC 8.</p>
<p>The terrorism charges were dropped as a direct result of a political pressure campaign against Gaertner, who had pressed the charges and was running for governor at the time. After protests at all of her campaign events and various other disruptions, Gaertner&rsquo;s name became synonymous with the RNC 8 to such an extent that eventually she had to adopt &ldquo;<em>The courage to do the right thing even when it is politically unpopular</em>&rdquo; as a campaign slogan. When Gaertner dropped the terrorism charges, she explained to a local paper that the terrorism charges would be &ldquo;distracting&rdquo; and &ldquo;a disaster at trial.&rdquo; This was not enough to save her campaign; she later dropped out of the governor&rsquo;s race entirely.</p>
<p>Significantly, no conspiracy charges were filed against organizers of protests against the <a href="http://www.crimethinc.com/texts/atoz/g202.php" target="_blank">2009 G20 summit in Pittsburgh</a>, Pennsylvania. This seems to indicate that the support campaign for the RNC 8 was successful enough to discourage the state from attempting the same strategy, although it was surely caused by factors in Pittsburgh as well. The latter may include the willingness of the organizing group to exclude suspicious individuals and hesitance on the part of local officials to go after well-connected activists.</p>
<p>The other two conspiracy charges remain pending against the RNC 8. The trial will begin on October 25, 2010.<br />
</p>
<h5>2009</h5>
<h3><a href="http://www.greenisthenewred.com/blog/aeta-arrests/1070/" target="_blank">AETA 4</a></h3>
<p>On February 19 and 20, 2009, the Joint Terrorism Task Force of the FBI arrested <a href="http://aeta4.org/" target="_blank">Joseph Buddenberg, Maryam Khajavi, Nathan Pope, and Adriana Stump</a>; they were charged with conspiracy to violate the Animal Enterprise Terrorism Act for protest activity relating to home demonstrations in which they wrote on a sidewalk with chalk, among other things.</p>
<p>A judge dismissed the case &ldquo;without prejudice&rdquo; in July 2010 on the grounds that the government didn&rsquo;t give enough specifics on the alleged criminal activity:</p>
<h6>In order for an indictment to fulfill its constitutional purposes, it must allege facts that sufficiently inform each defendant of what it is that he or she is alleged to have done that constitutes a crime. This is particularly important where the species of behavior in question spans a wide spectrum from criminal conduct to constitutionally protected political protest. While &lsquo;true threats&rsquo; enjoy no First Amendment protection, picketing and political protest are at the very core of what is protected by the First Amendment.</h6>
<p>Because the case was dismissed without prejudice, the government can re-indict the defendants; it is unclear whether this will occur.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/conspiracy/8b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/conspiracy/8a.jpg" width="500" height="397" style="margin-bottom: 2px"></a><em><br />
The AETA 4</em><br />
</p>
<p>
<br />
</p>
<h3><a href="http://www.mostlyeverything.net/" target="_blank">Hugh and Tiga</a></h3>
<p>Gina &ldquo;Tiga&rdquo; Wertz and Hugh Farrell were arrested on April 24, 2009 by Indiana state authorities and charged with multiple counts of intimidation, conversion, and corrupt business influence, a felony racketeering charge, for their involvement in protests against I-69. The felony racketeering charge was later dismissed. Both pled July 2010 to misdemeanor charges and received 15 months probation.<br />
</p>
<h3><a href="http://www.supportkevin.org" target="_blank">Kevin Olliff</a></h3>
<p>Kevin Olliff was arrested in April 2009 on state charges for protest-related activity against UCLA vivisectors three years earlier; he faced 10 felony charges including multiple counts of stalking, conspiracy, conspiracy to stalk, and threatening of a public servant. Olliff did not make bail and stayed in jail for almost a year before he pled to six of the ten felony counts against him in March 2010 in a non-cooperating plea agreement.<br />
</p>
<h3><a href="http://davenportgrandjury.wordpress.com/" target="_blank">Carrie Feldman and Scott DeMuth</a></h3>
<p>Carrie Feldman was subpoenaed to a federal grand jury in Davenport, Iowa in October 2009. She read a statement of non-cooperation and pled the 5th Amendment, and was re-subpoenaed for November. Scott DeMuth was subpoenaed to appear with her, and the two were both jailed for civil contempt on account of refusing to answer questions.</p>
<p>Scott DeMuth was indicted for conspiracy to violate the AETA days later, and was released pending trial; Feldman was jailed for four months, during which time her case received public attention. She was eventually released because &ldquo;her testimony is no longer needed.&rdquo; DeMuth&rsquo;s trial is scheduled to begin September 13, 2010.<br />
</p>
<h5>2010</h5>
<h3><a href="http://asheville11defense.com/" target="_blank">The Asheville 11</a></h3>
<p>Eleven people were arrested on May 1, 2010 in Asheville, NC, accused of doing $20,000 worth of damage to downtown businesses. Each was charged with 3 felonies (felony riot, felony conspiracy to riot, felony damage to property) and 10 misdemeanors (one was charged with 11). Initially set at $10,000, bail was ratcheted up to $65,000 apiece as the authorities implemented anti-anarchist scare tactics in the media and court system. Their trial dates have yet to be set.<br />
</p>
<h3><a href="http://www.counterpunch.org/gelderloos07072010.html" target="_blank">Toronto G20</a></h3>
<p>Sixteen people were arrested and charged with conspiracy on account of the protests against the <a href="http://www.crimethinc.com/texts/recentfeatures/toronto2.php" target="_blank">G20 summit in Toronto, Canada</a>. Although this is occurring in Canada, the Canadian government is clearly hoping to utilize the conspiracy model pioneered in the SHAC 7 and RNC 8 cases to terrorize dissidents involved in laying the framework for the most intense protests Ontario has seen thus far this century. As of now, little information is available about the Toronto G20 charges; the government is not releasing any information, and lawyers appear to be advising the defendants to proceed extremely carefully.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/conspiracy/9b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/conspiracy/9a.jpg" width="500" height="815" style="margin-bottom: 2px"></a><em><br />
If you&rsquo;re going to fuck security culture, please use protection</em><br />
</p>
<p>&nbsp;</p>