<h1>&nbsp;</h1>
<h1>Despair</h1>
<p>&nbsp;</p>
<h3>&ldquo;I wish all the people who&rsquo;ve killed themselves were still alive&mdash; and all the people who are alive would <em>kill themselves!&rdquo;</em></h3>
<p><a href="/texts/images/despair/1b.gif" rel="lightbox"><img src="/texts/images/despair/1a.gif" width="200" height="443" style="float:left; margin-bottom: 0px"></a>If there is a social stratum below the exploited underclass, a demographic that suffers most from the absurdities of our society, it is the suicides. The suicidal class&mdash;every minute, a few more hit the pavement. Who is more dispossessed than them? They are only recognized when they absent themselves; only their blood speaks on their behalf. They know better than anyone else what must change about this world, and yet in despair of ever changing it they avenge themselves upon the only victims in easy reach&mdash;giving a new meaning to the saying that those who make half a revolution dig their own graves.</p>
<p>Imagine a person feeling that his life is out of his control to such an extent that he can only regain possession of it by murdering himself! Can a society really be free and healthy if people will go to such lengths to escape?</p>
<p>So like theft and adultery, suicide is forbidden, an unspeakable abomination. Self-satisfied den mothers who have never grappled with debilitating depression feel entitled to sneer at the cowardice of those who make the difficult decision to end their lives. Even the terminally ill are not to choose for themselves when and how they pass away&mdash;there are laws against it, as if the living could legislate for those crossing over into death! What does it say of a civilization that it not only forbids its denizens to kill themselves but does not even permit the <em>question</em> of whether life is worth living?</p>
<p>Yet we commit a little suicide every moment we deny ourselves the lives we wish to live. Wholesale suicide is off-limits, but most settle willingly enough for death on the installment plan, whittling their lives away hour by hour. No matter how unfulfilling life is, they dare not back out, for God is waiting on the other side to punish them for shirking their earthly duties&mdash;God, that is, or else Public Opinion, which He has deputized in His absence.</p>
<p>Meanwhile, if a young man joins the military and mindlessly obeys orders that lead to his senseless death, his conduct is courageous and praiseworthy. Suicide, like Disaster, is perfectly acceptable so long as it occurs on the terms of the powers that be; you can die in their hands, but not of your own. The ones who shoot or hang themselves are daring heretics, like the upstart mystics who claim to receive divine guidance that bypasses the Pope: if self-destruction is the order of the day, they&rsquo;re determined to have a firsthand relationship with it, whatever anyone else says. In rejecting both living death and the sovereignty of the authorities over their lives, they are only one step away from rejecting death and domination altogether: <em>Neither death nor taxes!</em></p>
<p>But again, like theft, adultery, and other pressure valves, suicide is isolating&mdash;indeed, it is the most isolating act bar none. While it returns an instant of autonomy to an individual, it can only prevent people from establishing collective ownership of their lives. Those who dig their own graves make only half a revolution. If no one could steal, if no one could cheat, if no one could end his life, yet all the tensions that run through our society today remained&mdash;picture the massive upheavals that would ensue!</p>
<p>If all those who have killed themselves could compare notes at some grand convention center in the hereafter, what would they be able to tell us? Perhaps they would be capable of succoring one another where no one else could; perhaps they would regret that, rather than destroying themselves, they didn&rsquo;t launch a revolutionary organization comprised of those who have nothing to lose; perhaps it would seem strange to them that it had felt so much easier to do violence to themselves than to respond to the violence done to them.</p>
<p> It&rsquo;s too late, of course&mdash;their lives are fixed in eternity, set apart like flies trapped in amber. But there is still time to find those who are currently contemplating suicide, to encourage them to speak freely about their feelings and do our best to make a world no one will wish to leave.</p>
<p align="center"><a href="/texts/images/despair/2b.gif" rel="lightbox"><img src="/texts/images/despair/2a.gif" width="500" height="345"></a></p>
<h3>&ldquo;Put me out of my misery or take me out of it!&rdquo;</h3>
<p>Life is not simply a trap, a sentence. This occurs to everyone at least once. We have an option that makes us freer than the gods, just as every employee is freer than every boss: we can quit. One can savor this idea in every extremity; it provides consolation when nothing else can. Nothing obligates us to live&mdash;therefore, if we have the courage for it, at every moment life can become a tabula rasa, a space in which anything is possible and everything can be risked.</p>
<p>With such freedom, we can only be slaves if we choose to be. Slavery is for those who still believe that their masters control the domain of death as well as life&mdash;not for us. For us, there is only the unknown. It may be awful, it may be salvation, it may be nothingness, but it is unknowable, in life as well as death. Frontiers to be crossed, new worlds to explore, abysses to be risked&mdash;yes, the possibility of joy, of the realization of your most cherished desires, and risk, risk too. The risk of finally confronting fear, daring the unknown, looking the ugliness of life in the face&mdash;of, one way or another, <em>quitting the job of existing.</em></p>
<p>For most of our contemporaries, life itself is a job, a desperate struggle to juggle a thousand obligations&mdash;including the saddest imperative of all, enjoying oneself. These unfortunates forget the lightness of life, the weightlessness of every moment, every situation, in the face of nonexistence.</p>
<p><em>We can choose not to live.</em> So there is no reason not to open oneself to, to risk everything for, a life of joy. There is always the option of putting an end to things&mdash;one may as well play for high stakes if one chooses to exist. After all, the worst that could happen is already assured.</p>
<p>There is no reason to get up in the morning, then, but to <em>live.</em> No boss, no law, no god can take from you the possibility of saying No.</p>
<p>All this is useless, and not news, to the suicide, who has already disconnected from life and wills death simply to finalize the arrangement, to put an end to the inconvenience of feeling one thing and living another. Once you&rsquo;re that exhausted and demoralized, no mere mental exercise can change your mind; suicide bombers, contrary to idle speculation, must act from a tremendous investment in this world to be capable of going to such lengths to die at others&rsquo; expense. Your average suicidal person can barely vacuum her apartment, let alone carry out an elaborate mission.</p>
<p>But imagine if people lived as though they might die at any moment, so every day it was as if they were born again! Imagine if no one let life become a job for himself or anyone else in the first place! Then how many people would kill themselves? People commit suicide when it is harder for them to picture breaking off their commitments than ceasing to exist&mdash;here again are our customs and investments, become cancerous and inorganic, riding us to early graves.</p>
<h3>Life&mdash;Consider the Alternative</h3>
<p>If we were brave or reckless enough for it, our despair could afford us supernatural powers. Imagine being able to act without fear of the repercussions, to choose the unknown over the intolerably familiar, to withdraw from unhealthy obligations and relationships the moment you recognize them for what they are. It takes a ruthless mercy to discard sentimentality and remember all the things that never happened and <em>still might never happen,</em> all the dreams that never came true&mdash;to acknowledge that we can&rsquo;t wait forever, there&rsquo;s not enough time for that.</p>
<p><em>Let the past go.</em> All the old battles you&rsquo;re still fighting, all your denial and defense mechanisms, all the addictions and inertia you&rsquo;ve accumulated and all the fears that bind you to them. This is going to be the hardest thing you ever live through&mdash;but let them go, let them die, have courage through the silent moments in the void as you wait, trembling, for your new life to be born. It will be.</p>
<p>Despair. It&rsquo;s our only hope.</p>
<p>&nbsp;</p>