<p align="center"><a href="http://cloudfront.crimethinc.com/images/empire/1c.jpg" rel="lightbox[nightmares]"><img src="http://cloudfront.crimethinc.com/images/empire/1b.jpg" alt="2012: The Empire Has No Clothes" width="500" height="329"/></a></p>
<p>The new year breaks on a turbulent world. Increasingly superfluous, we pour into the <a href="http://en.wikipedia.org/wiki/Tertiary_sector_of_the_economy" target="_blank">service industry</a>&mdash;greasing the wheels for consumption rather than producing anything of lasting value&mdash;or scavenge at the margins. Forced to be ever more flexible and mobile, competing against ever-broadening swaths of the population for ever more precarious jobs, we aren&rsquo;t just <em>atomized,</em> we&rsquo;ve become <a href="http://en.wikipedia.org/wiki/Plasma_(physics)" target="_blank">plasma</a>&mdash;a shapeless, reactive mass in which even the most elementary bonds have been broken.</p>
<p>This doesn&rsquo;t signify the triumph of capitalism, but a new phase of uncertainty for the system as well as its subjects. Today, even liberals acknowledge that 99% of the population has little stake in perpetuating the status quo. Yet only the most doctrinaire Marxists still believe history will deliver us to utopia: maquiladoras on the moon seem equally likely. The current turmoil simply affords us a window of opportunity, a window with no guarantees. If we fail to seize it, the system will stabilize once more, as it has in every previous crisis: and this time we can be sure the stabilizing mechanism will not be the <a href="http://en.wikipedia.org/wiki/Fordism" target="_blank">carrot</a>, but the stick.</p>
<p>To summarize <a href="http://www.crimethinc.com/texts/recentfeatures/nightmares.php">an earlier analysis</a>: when it&rsquo;s easier to <a href="http://en.wikipedia.org/wiki/Tunisian_revolution" target="_blank">overthrow governments</a> than to reform them, we shouldn&rsquo;t base our strategies on incremental victories, but popularize ways of fighting that create new social bodies. As people lose their previous positions in society, traditional struggles will collapse, but the disenfranchised will pour into every struggle that creates new commons. Yet these commons can only survive as long as they spread: we can only defend ourselves <em>offensively.</em></p>
<p>These hypotheses were borne out throughout 2011, from the so-called <a href="http://www.crimethinc.com/blog/2011/02/02/egypt-today-tomorrow-the-world/">Arab Spring</a> to the <a href="http://www.usnews.com/news/articles/2011/11/21/occupy-oakland-evicted-police-use-of-pepper-spray-under-scrutiny" target="_blank">fall of the occupations</a>. Here are some of the factors we expect to shape the context of struggle in 2012.<br />
</p>
<h3>Not the Carrot, but the Stick</h3>
<p>In the economic crisis, policing and private security are one of the only remaining growth industries. The fierce and apparently <a href="http://www.thiscantbehappening.net/node/900" target="_blank">coordinated</a> police repression of occupations should come as no surprise in a nation where nearly two and a half million are incarcerated and police kill hundreds every year. <em>That violence is only going to intensify.</em> There&rsquo;s no other way to keep the superfluous population under control, especially as we get unruly.</p>
<p>We should brace ourselves for increasing levels of force&mdash;perhaps beyond anything we can imagine&mdash;and countering these in the streets will be essential to the next phase of resistance. But the strategy of the stick means more than tear gas and SWAT team raids. The authorities can&rsquo;t utilize force without provoking greater unrest unless they delegitimize the targets and break up all social configurations that could fight back. Demonizing insurgents in the media, driving wedges between and within social bodies, and buying off potential allies are all essential steps in this strategy. In this context, implicit offers of immunity to cooperative elements in popular movements are functionally identical to police violence, as they prepare the ground for it. Protesters who seek to distinguish themselves from the irrational and unruly are accepting complicity in everything that is done to the latter.<a class="footnote" href="javascript:void(0);" onclick="return overlib('This process is particularly insidious in that those who are offered immunity often experience this as a victory for the movement&mdash;inclusion in the political process, for example, or at least unprecedented dialogue with the powerful. The complicit may not even know they&rsquo;re part of a peace treaty that renders others more vulnerable. A great part of complicity is ignorance&mdash;if you don&rsquo;t notice people suffering, you&rsquo;ve probably already been bought.', CAPTION, '[1]');" onmouseout="nd();">[1]</a></p>
<p>We can already see how this has played out in various parts of the world over the past year. In Egypt, a widespread popular revolt obtained its original object, but fragmented afterwards as some continued fighting for liberation while others abandoned them to the bullets of the military. In the UK, the disconnection between protest movements and the suffering underclass meant that the <a href="http://london.indymedia.org/articles/9969">inevitable revolt</a> of the latter took an antisocial form, limiting its scope. On the other hand, <a href="http://occupyoakland.org/">Occupy Oakland</a> has been able to continue escalating precisely because anarchists and other angry poor people were never successfully marginalized.</p>
<p>&nbsp;</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/empire/2b.jpg" rel="lightbox[nightmares]"><img src="http://cloudfront.crimethinc.com/images/empire/2b.jpg" width="500" height="295"/></a></p>
<h3>The Cycle of False Hope</h3>
<p>Four years ago, savvy young people eager to change the world lined up behind a politician&rsquo;s promise of &ldquo;Hope.&rdquo; In 2011, many of the same people took to the street; the Occupy Movement was a logical next step for the Obama Generation once electoral politics failed them. We can expect this cycle of hope and disillusionment to continue now that the occupiers&rsquo; attempt at autonomous direct democracy has been crushed by force. Faith in leaders was the first to go; faith in <a href="https://www.commondreams.org/view/2011/11/14-8" target="_blank">nonviolence</a> might be next.</p>
<p>In a time of widespread anxiety and discontent, it&rsquo;s tempting to throw one&rsquo;s weight behind anyone who offers to fix the economy and the social ills that supposedly caused its decline. When one promise inevitably fails, the next round of proposals tends to be more extreme. In the coming years, there will be more militancy across the political spectrum and more willingness to act outside the established institutions.</p>
<p>Unfortunately, direct action does not always serve liberating ends. The crucial battle right now is not between illegalism and law and order, but between competing visions of upheaval&mdash;and our most dangerous enemies may not be bureaucrats or executives. One of our tasks as anarchists is to unmask would-be leaders and their false promises&mdash;the pied pipers of <a href="http://www.crimethinc.com/texts/recentfeatures/nightmares.php">pipe dreams</a>. This is not for the faint of heart: anarchists who <a href="http://anarchistnews.org/?q=node/5537" target="_blank">lacked the mettle to take an unpopular stand</a> when Obama was elected will be hard-pressed to take on apparently horizontal social movements that ultimately function to stabilize capitalism.</p>
<p>Anarchist principles are catching on throughout society, well beyond the plaza occupations. From the right we hear that <a href="http://www.time.com/time/politics/article/0,8599,2005371,00.html" target="_blank">&ldquo;every tea partier is a tea party leader,&rdquo;</a> and at least some people take this rhetoric seriously. For now, this trend seems simply to be fostering an extra-parliamentary version of two-party politics, with little serious opposition to capitalism on either side. But every moment of disillusionment can also be a moment of transformation. We may find strange bedfellows in 2012.</p><p align="center"><a href="http://cloudfront.crimethinc.com/images/empire/3b.jpg" rel="lightbox[nightmares]"><img src="http://cloudfront.crimethinc.com/images/empire/3b.jpg" width="500" height="315"/></a><em>Higher levels of conflict are going to become increasingly routine . . .</em></p>
<h3>The Taming of the Technological Frontier?</h3>
<p>&ldquo;Not the carrot, but the stick&rdquo;: we picture security guards with actual nightsticks, but this clampdown will also occur on the newest terrain of struggle, digital communication. The same technology that helped capitalists outflank the resistance of the 1960s has produced new forms of revolt, from file-sharing to viral riots. Without the advance endorsement of <a href="http://en.wikipedia.org/wiki/Anonymous_(group)" target="_blank">Anonymous</a>, for example, Occupy Wall Street might never have gotten off the ground. We can expect to see a worldwide authoritarian backlash against the internet-spread and twitter-savvy revolts of 2011.</p>
<p>Much of this clampdown will take the form of direct surveillance and censorship. We take for granted that those are chiefly employed in places like Syria and Tunisia; in fact, most of the censorship technology those governments use comes from Silicon Valley&mdash;and was first applied right here in the US.<a class="footnote" href="javascript:void(0);" onclick="return overlib('Much of this technology was originally developed to maximize white-collar productivity at US corporations; the third world dictatorship market didn&rsquo;t really open up until the initial development costs had been covered. Just as it was easier for China to industrialize after Europe had, once censorship technology is developed it becomes more and more affordable&mdash;this is another aspect of how policing is one of today&rsquo;s growth industries. Rhetoric about freedom aside, the US government would never inconvenience the censorship industry; the latter is intrinsic to US national security, in that through these companies the US has a backdoor into the security practices and information flow&nbsp;of every country employing them worldwide. That is to say&mdash;to maintain its imperial position, the US has to remain at the forefront of free market solutions for repression. This is an interesting example of how economic practices are inextricable from the political forms that vouchsafe them, and vice versa.', CAPTION, '[2]');" onmouseout="nd();">[2]</a> Since even the slightest internet censorship presupposes effective and exhaustive surveillance, it is a small step from regulation to lockdown. </p>
<p>Yet not all digital repression is as heavy-handed as the firewall around China. Think instead of the <a href="http://www.londonnet.co.uk/news/2011/dec/met-raids-100-homes-suspected-rioters-live-bullets-option-future-trouble.html" target="_blank">digital forensics</a> utilized by police in the UK to follow up on last summer's riots. Alongside this kind of surgical targeting, we can expect yet subtler efforts to delegitimize resistance and guide discourse away from anything that could prove disruptive. The attention economy of Facebook and Youtube is ideal for both approaches.</p>
<p>The current struggles over digital privacy and &ldquo;free speech&rdquo; are not just a matter of civil liberties; they will have significant consequences for the next phase of struggle in the streets. The more difficult it becomes to speak freely and safely online, the more specialized the role of circulating information will be, and the more difficult it will become to coordinate revolt spontaneously. The resulting power imbalances may figure strongly in the cooption and neutralization of struggles: in some plaza occupations, the disproportionate power of the media working group has already been a recurring problem. If the clampdown succeeds, this will only get worse.<br />
</p>
<h3>Keeping up the Fight</h3>
<p>Of course, our best defense against the authorities utilizing all the intelligence they gather is not proper computer security, but thriving social movements. When people are used to acting together and discontent is simmering, the powerful are afraid to provoke a storm they can&rsquo;t control. Again, the best defense is a good offense.</p>
<p>As different groups compete for ownership of the struggle, we should be especially suspicious of every attempt to <em>manage</em> the forms revolt takes. The do-it-yourself ethic that seemed revolutionary in the 1990s ultimately helped solve the crisis of the previous form of capitalism, preparing atomized individuals to <a href="http://richmond.craigslist.org/jjj/" target="_blank">self-manage</a> our integration into the economy; <em>self-managing</em> the taming of our own rebellions may well be the next phase of this program. The non-profit post-industrial complex is a familiar example of this: it is essentially a return to feudalism, in which the powerful dole out just enough resources to the well-meaning to keep the population quiet. We expect to see some new examples as social conflict continues. Some of the best managers might be impressively militant.</p>
<p>Today the question isn&rsquo;t <em>whether</em> there will be resistance&mdash;we no longer need to buy plane tickets overseas to get a taste of it&mdash;but what social forms will characterize it, what precedents it will set. We&rsquo;ll probably see heterogeneous zones like Occupy Wall Street open up repeatedly over the coming years, each time drawing in new sectors of the population with diverse perspectives and agendas. These spaces will inevitably rupture as the elements that constituted them form new configurations and new fault lines emerge. Our goal should not be to preserve these for their own sake, then, but rather to make sure the <em>right</em> ruptures occur.</p>
<p>Alongside attempting to intensify explicitly political movements such as the plaza occupations, we should also figure out what role to play in the violent clashes we can expect to see more frequently. Even after a remarkable wave of anti-austerity protests, anarchists in London seemed unprepared for last August&rsquo;s Tottenham riots. We need to be able to act swiftly and decisively in such moments. We probably won&rsquo;t succeed in imposing our own political agenda on them; even if we could, it might put us in the ranks of the managers and protest marshals. What we can do is demonstrate in practice how different forms of revolt are relevant to each other, and help to link them together. Looters need hackers, and hackers need looters too.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/empire/5b.jpg" rel="lightbox[nightmares]"><img src="http://cloudfront.crimethinc.com/images/empire/5b.jpg" width="500" height="288"/></a></p>
<h3>A Crisis of Legitimacy</h3>
<p>Whatever their results, presidential elections are a ritual for reinforcing the legitimacy of the government and its political process. In 2012, this legitimacy is in question to an unusual extent. The popular rhetoric of autonomy and participation is the flipside of a growing skepticism towards our rulers.</p>
<p>Right now this skepticism is mostly expressed in the language of corruption and mismanagement; people doubt the legitimacy of <em>this</em> government, but perhaps not of government itself. For the ruling class, holding that line will be the top priority this year. Our priority will be the opposite.</p>
<p>At the same time, we&rsquo;ll be facing our own crises. Would-be leaders have always used discourses of legitimacy to isolate their foes&mdash;violence versus nonviolence, locals versus outside agitators, goal-oriented discipline versus unproductive chaos. As the false promises become more extreme, so will the recriminations. Pandering to their discourse reinforces their advantage, but declaring ourselves on the side of the illegitimate is not enough to undermine the force of legitimacy itself. How we navigate this complex problem will determine our ability to link different social bodies in revolt.</p>
<p>No matter what, we cannot sit back and let the cycle of hope and disillusionment run its course, however costly those who profit off of false hope make it to intervene. Nothing we say is credible if we fail to provide examples of action to those who are ready to act. An escalating cycle of conflict produces a growing apparatus of control. If we wait until every solution except anarchy has been tried, it will be too late.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/empire/4b.jpg" rel="lightbox[nightmares]"><img src="http://cloudfront.crimethinc.com/images/empire/4b.jpg" width="500" height="350"/></a><em>. . . and the stakes keep going up.</em></p>
<p>&nbsp;</p>
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1] This process is particularly insidious in that those who are offered immunity often experience this as a victory for the movement&mdash;inclusion in the political process, for example, or at least unprecedented dialogue with the powerful. The complicit may not even know they&rsquo;re part of a peace treaty that renders others more vulnerable. A great part of complicity is ignorance&mdash;if you don&rsquo;t notice people suffering, you&rsquo;ve probably already been bought.</p>
<p>[2] Much of this technology was originally developed to maximize white-collar productivity at US corporations; the third world dictatorship market didn&rsquo;t really open up until the initial development costs had been covered. Just as it was easier for China to industrialize after Europe had, once censorship technology is developed it becomes more and more affordable&mdash;this is another aspect of how policing is one of today&rsquo;s growth industries. Rhetoric about freedom aside, the US government would never inconvenience the censorship industry; the latter is intrinsic to US national security, in that through these companies the US has a backdoor into the security practices and information flow&nbsp;of every country employing them worldwide. That is to say&mdash;to maintain its imperial position, the US has to remain at the forefront of free market solutions for repression. This is an interesting example of how economic practices are inextricable from the political forms that vouchsafe them, and vice versa.</p>
</div>