<p align="center"><a href="https://cloudfront.crimethinc.com/images/vortext/1b.jpg" rel="lightbox[border]"><img src="https://cloudfront.crimethinc.com/images/vortext/1a.jpg" alt="Beware/Join the Experimentation Committee" width="500" height="270"></a></p>
<h6 align="right" style="margin-right: 0px"><em>This manifesto appeared in <a href="http://www.crimethinc.com/blog/2012/04/08/outliers-to-the-front-presenting-vortext/"><strong>VORTEXT</strong></a>, organ of the Experimentation Committee.<br /> It is available in PDF form <a href="/blog/2012/07/04/new-feature-and-vortext-now-online/">here</a>.</em></h6>
<h5>&ldquo;You need to know how to experience freedom in order to be free. You need to free yourself in order to experience freedom. Within the present social order, time and space prevent the <strong>experimentation of freedom</strong> because they suffocate the freedom to experiment. Only by upsetting the imperatives of time and social space will it be possible to imagine new relations and surroundings. The old philosopher said one can only desire on the basis of what one knows. Desires can only change if one changes the life that produces them.&rdquo;<br />
&ndash;Anonymous, <em>At Daggers Drawn</em></h5>
<p><em>If it works, it&rsquo;s obsolete.</em> Real innovation rarely comes from the successful&mdash;those who have something to lose can&rsquo;t afford to stumble about at random. On the contrary, it comes from the ones who have their hands free: lunatics, ne&rsquo;er-do-wells, outsiders, <em>MAXIMUM ULTRAISTS.</em></p><p>
In sleepy backwaters far from academia&rsquo;s ivory towers, teenagers improvise munitions and Wright brothers invent airplanes. Most never achieve fame, not even of the fifteen-minute variety. They don&rsquo;t contribute to the sort of progress recorded by historians&mdash;incremental, linear, triumphalist. They aren&rsquo;t part of an <em>avant-garde</em>: that presupposes a direction, when it is precisely the refusal of direction that enables them to make their discoveries.
</p><p>Some call this play. Others call it folk science. We call it <em>the Experimentation Committee.</em>
The Experimentation Committee doesn&rsquo;t hold yearly conventions or award laurels. For the most part, it is comprised of people who never meet each other. It is not a membership organization but a secret society of the elect, which one may join only by departing from all that is familiar. It is a tunnel of darkness, a cocoon in which one becomes <em>another.</em>
</p><p>Joining the Experimentation Committee is not only a matter of experimenting in <em>means,</em> but also in <em>ends</em>: not just acting according to values&mdash;however &ldquo;radical&rdquo;&mdash;but, as Nietzsche put it, <em>revaluating</em> them.<a class="footnote" href="javascript:void(0);" onclick="return overlib('When economists revalue a currency, they do so in relation to other currencies; thus one may simply understand Nietzsche as proposing that we reevaluate traditional values relative to <em>other</em> values. But we can also imagine him to be arguing for a way of thinking and living that <em>produces new values.</em> As he says, one must have chaos within oneself to give birth to a dancing star.', CAPTION, '[1]');" onmouseout="nd();">[1]</a> This kind of behavior is no walk in the park. Those who have chosen a project or direction can at least evaluate their success according to an external measure; without this convenience, there is no staving off self-doubt and existential crises. The Experimentation Committee is not for the faint of heart.
</p><p>When you understand something, you <em>know</em> less, for you no longer see the field of possibilities. People are only likely to break new ground when they don&rsquo;t understand how something works, when they <strong><em>imitate without mastery or comprehension.</em></strong> In this regard, the internet may actually be a barrier to innovation&mdash;it tends spread identical copies, not unique imitations.</p>
<h5><em>If you aren&rsquo;t sure what we mean, hurry&mdash;cease reading this instant and compose your own text expressing whatever you can imagine we might mean. Only thus will you have any hope of generating something new.</em></h5>
<p>Abstract theoretical considerations about what is needed rarely bear fruit; more often, people discover innovations by trying things at random until one works, albeit to achieve a previously unsought end. Only then do the theoreticians catch up, explaining why it works and why its results are desirable. This suggests that innovators should prioritize wide-ranging experimentation, even at random, over carefully-crafted hypotheses. <strong><em>New strategies arise from new tactics,</em></strong> not vice versa.
</p><p>To participate in the Experimentation Committee, one must go beyond merely insisting that &ldquo;another world is possible,&rdquo; unless perhaps it is the other world depicted by Jean Ignace Isidore Gerard (as &ldquo;<a href="http://www.flickr.com/photos/bjacques/sets/72157622452294268/" target="_blank">J.J. Grandville</a>&rdquo;). Rather, one must &ldquo;remain impossible as long as those who are now possible remain possible,&rdquo; as Bakunin put it: the point is not to legitimize even the outlandish as realistic, but to abolish reality as we know it.
</p><p>All of us have been part of the Experimentation Committee at some point in our lives&mdash;at least long enough to become anarchists, antinomians, or whatever it is you are that explains why you&rsquo;re reading this. Yet like the reference points for anarchist revolution, our examples of bona fide participation in the Committee are largely mythological.
</p><p>Let&rsquo;s start with the Situationists in their younger days, <em><a href="http://www.bopsecrets.org/SI/2.derive.htm" target="_blank">drifting</a></em> around Europe, investing their <em>chance encounters</em> with meaning, before they became so fucking ideological. From their <em>d&eacute;rives</em> we derive the principle that the Experimentation Committee must <em>wander</em> rather than seek.<a class="footnote" href="javascript:void(0);" onclick="return overlib('&ldquo;Aimless is my song. Yes, aimless<br />As is love and life,<br />And creator and creation.&rdquo;<br /><em>&ndash;Heinrich Heine</em>', CAPTION, '[2]');" onmouseout="nd();">[2]</a>
</p><p>Every cup that runneth over, everyone who exceeds his role&mdash;who <em><a href="http://theanarchistlibrary.org/library/alfredo-m-bonanno-i-know-who-killed-chief-superintendent-luigi-calabresi" target="_blank">goes beyond</a></em>&mdash;qualifies for membership. We count Subcommandante Marcos of the EZLN among the Experimentation Committee not because he participated in a revolutionary uprising but because he found time in the midst of it to write <a href="http://books.google.com/books?id=p_1oiln1U4oC&amp;printsec=frontcover#v=onepage&amp;q&amp;f=false" target="_blank">children&rsquo;s stories</a> about a talking beetle. This ski-masked Scheherazade, desperately sending out tales of Durito from his muddy camp in hopes of maintaining enough liberal attention to escape massacre for another week, cannot fail to touch our hearts even when his politics do not.
</p><p>If the French gang <a href="http://www.revoltagainstplenty.com/index.php/archive/16-archive-global/58-os-cangaceiros" target="_blank">Os Cangaceiros</a> really did squat a top-dollar condominium&mdash;rather than the usual abandoned warehouse&mdash;solely in order to provoke a police attack, that also qualifies as the requisite <em>excess.</em>
<a href="http://www.spoonfed.co.uk/spooners/tom-699/lecture-violence-to-endurance-extreme-curating-at-the-ica-495/" target="_blank">Alexander Brener and Barbara Schurz</a> are first-round draft picks. Playing free jazz isn&rsquo;t enough, but Sun Ra qualifies. Punk bands like <a href="http://www.youtube.com/watch?v=W_xlTB9aUlo" target="_blank">Contropotere</a> and Gism almost make the cut, but Creation Is Crucifixion enlisted when they started <a href="http://en.wikipedia.org/wiki/Creation_Is_Crucifixion" target="_blank">reprogramming video games</a> in addition to playing hardcore. <a href="http://en.free-voina.org/about" target="_blank">Voina</a> seems inspiring, though our Russian comrades report&mdash;not surprisingly&mdash;that they&rsquo;re assholes. Neither Marinetti nor any other marionette of state or capital has a damn thing to do with the Committee.
</p><p>It is rarely easy to mobilize support for Experimentation Committee <a href="http://asheville11defense.com/" target="_blank">arrestees.</a> All the more reason to burn the prisons.
</p><p>The Experimentation Committee <strong>claims the death rattles of sacred cows as its national anthem</strong>. The Experimentation Committee <strong>strikes fear into the hearts of all who earnestly wish to succeed</strong>. The Experimentation Committee is an unquenchable fountain of youth, ceaselessly replenishing the world despite all our efforts to seal it up. Compose your last will and testament&mdash;double or nothing&mdash;and join up.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/vortext/2b.jpg" rel="lightbox[border]"><img src="https://cloudfront.crimethinc.com/images/vortext/2a.jpg" alt="Comrades&mdash;urely It Is Too Late, but We Need You for the Experimentation Committee!" width="500" height="461"></a></p>
<p><em>To apply, mail one of the following to:</em></p>
<p><em>V&Ouml;&Ouml;&Ouml;RTEXT</em> vortex[at]crimethinc.com
<em>P.O. Box 494, </em>
<em>Chapel Hill NC 27514, </em>
<em>USA</em></p>
<p>&bull; A homemade Was-passiert-dann-Maschine</p>
<p>&bull; A book report (approx. 1000 words) on one of these works: Max Ernst, <em>La Femme 100 T&ecirc;tes</em>; M&aacute;rio de Andrade, <em>Macuna&iacute;ma</em>; Oswald de Andrade [no relation], <em>Cannibal Manifesto</em>; Luigi Serafini, <em>Codex Seraphinianus</em>; the five books of Rabelais; the so-called Voynich Manuscript</p>
<p>&bull; A performance piece or work of art with one of these titles:</p>
<p style="margin-left: 25px"><em>God Punishes the NYPD<br />Nihilist Rube Goldberg Machine<br />
Judith Butler Does Battle with the Hydra of Gender<br />
The Suicide of Barack Obama<br />
Dead Letter from the 1980s<br />
Red Herring<br />
Cat with Moth Wings<br />
Crime or Miracle: A Complete Human Being<br />
Lucifer Abandons Cain to His Fate<br />
Satan&rsquo;s Daughter Liberty Invokes His Assistance in Storming the Bastille<br />
No Artist&mdash;No Title<br />
The City Was a Hunchback, Sinister at Dusk<br />
Weapons for Children<br />
La Belle Dame Sans Merci<br />
The Sound of Tiny Hatchets<br />
Unload the Drum Machine!<br />
Bid for Popularity<br />
Trojan Horse</em></p>
<p>&bull; An oneiric history of the Occupy movement, i.e., a chronicle consisting entirely of selections recounted from the participants&rsquo; dreams and nightmares</p>
<p>&bull; An ethnography comparing the role narcotics trafficking has surreptitiously played in Denmark&rsquo;s Christiania to its function in maintaining zones in US ghettos that are antagonistic to policing and gentrification&mdash;OR&mdash;a historical study explaining why the punk rock subculture put down roots in Malaysia, Indonesia, and the Philippines but not in India or Bangladesh, and how this shaped the worldwide resurgence of anarchist ideas at the turn of the century</p>
<p>&bull; We demand that Diamanda Gal&aacute;s prepare her own translation of Guy Debord&rsquo;s <em>Society of the Spectacle</em>! We demand that Alejandro Jodorowsky learn lithography in order to illustrate it! We demand that Evergreen State College award an honorary degree&mdash;in absentia, if necessary&mdash;to the miscreants who <a href="http://news.infoshop.org/article.php?story=2009trotsky-cookies" target="_blank">stole Leon Trotsky&rsquo;s ashes and baked them into cookies!</a></p>
<p>&bull; The Federal Aviation Administration believes it is possible for an unarmed individual of any age or stature to hijack an airplane using a single bottle of tap water or tube of toothpaste. This seems to be very valuable information indeed. Figure out how this is done and report to us.</p>
<p>Those who fulfill demands made in the name of the Experimentation Committee earn the right to make such demands of others. <strong><em>Expand the Committee!</em></strong></p>
<p>&nbsp;</p>
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1] When economists revalue a currency, they do so in relation to other currencies; thus one may simply understand Nietzsche as proposing that we reevaluate traditional values relative to <em>other</em> values. But we can also imagine him to be arguing for a way of thinking and living that <em>produces new values.</em> As he says, one must have chaos within oneself to give birth to a dancing star.</p>
<p>[2] &ldquo;Aimless is my song. Yes, aimless<br />As is love and life,<br />And creator and creation.&rdquo;<br /><em>&ndash;Heinrich Heine</em></p>
</div>