<h1>The Fine Art of Criticism</h1>
<h5>A How-To Guide for Aspiring Journalists</h5>
<p align="center"><img src="../images/reviewsimage.jpg" width="500" height="290"></p>
<p> Those who can, write; those who can&rsquo;t, write reviews. Writing reviews is the surest shortcut to a sensation of power for those who lack the dedication necessary to create something of actual worth. In passing judgment on others&rsquo; work, the reviewer experiences a fleeting high of self-importance cheaper than any other.</p>
<p> Fortunately for the next generation of hacks, after squandering the best years of our writing careers composing purple prose for the throwaway tabloids of yellow journalism, we&rsquo;ve finally perfected this most elusive of literary forms. Deceptively simple and mundane, reviews are often assumed to be easy to pen; in fact, it&rsquo;s almost impossible to compose one worth reading. To save you the trouble of suffering through this learning process yourself (and your potential readers the risk of suffering along with you), we present here a surefire failsafe handy guide to the most rightly unappreciated literary form of the twentieth century. Mix yourself a stiff metaphor, cultivate an air of supercilious indifference&mdash;a prerequisite for any reviewer worth the salt he hopes to pour in others&rsquo; wounds&mdash;and read on.</p>
<h3>The Comparison</h3>
<p> This is the most common convention in the reviewer&rsquo;s repertoire, and the most swiftly, thoughtlessly trotted out. It comes in three basic varieties:</p>
<p>A is like B: &ldquo;<em>Orwell&rsquo;s</em> 1984 <em>is basically a rewrite of Zamyatin&rsquo;s</em> We, <em>right down to the use of punctuation marks.&rdquo; &ldquo;Like any other band with guitars, bass, and drums, Cannibal Corpse owes everything to Chuck Berry.&rdquo;</em></p>
<p>A is like B + C: &ldquo;<em>The sequel to</em> The Matrix<em> is the bastard child of Nintendo video games and MTV&rsquo;s &lsquo;The Daily Grind.&rsquo;&rdquo; &ldquo;Dragonforce sounds like Richard Marx with double bass.&rdquo;</em></p>
<p>A is like B (perhaps + C) under extenuating conditions: these can include, for example, drugs&mdash;&ldquo;<em>Jackson Pollock is like, uh, Matisse on serious methamphetamines&rdquo;</em>&mdash;violence&mdash;<em>&ldquo;Baudrillard offers the sort of insights Foucault would have hit upon if he&rsquo;d suffered severe head trauma at an early age&rdquo;</em>&mdash;evocative locations&mdash;<em>&ldquo;Imagine Tolstoy&rsquo;s War and Peace if it was set in a Soviet gulag across only three days; there you have it, Solzhenitsyn&rsquo;s </em>The First Circle&rdquo;&mdash;or, for maximum clich&eacute; action, all three: <em>&ldquo;Muppet Burger&rsquo;s new album &ldquo;Fuzzy Massacre&rdquo; sounds like Sun Ra and Sinead O&rsquo;Conner, cranked out of their minds on cough syrup and banana peel blunts, beating the stuffing out of Morrissey in a dark alley while humming La Marseilles to themselves.&rdquo;</em></p>
<h3>The Fawning Accolade</h3>
<p> A critic should not tender a positive review unless he believes he stands to gain in some way. Sometimes demonstrating one&rsquo;s superiority by exhibiting prescient taste can be as gratifying as the more direct approach of simply declaring something inferior. Of course, the power dynamics shift as soon as the spotlighted upstart gains a certain amount of attention: then, glorification accrues to the artist rather than the reviewer, so one must return to scorn and ridicule.</p>
<p> Things are not usually even this complex: a guest list and bar tab beckon, a senior editor threatens, advertising dollars await, Public Opinion counsels that this is going to be a Hot Item this year and those who fail to get on board do so at their own peril. One must give positive reviews to something, after all, and it never hurts to kill two birds with one stone.</p>
<p> Sometimes it does occur that a neophyte, carried away by actual passion unbecoming of the serious journalist, expresses honest appreciation. Please, resist this temptation. We&rsquo;ve all got mouths to feed in this business, and a certain professional standard of restraint and objectivity is only common sense.</p>
<h3>The Interpretation</h3>
<p> The critic does well to cast himself as the artist&rsquo;s interpreter, a modern-day successor of the priests who explicated the drugged ravings of the Oracle of Delphi. This relationship places the critic in the more essential role: any damn fool can get hooked on heroin and put a few chords together, but it takes a Greil Marcus to construct meaning out of the resulting cacophony and go on to trace its lineage to the Anabaptists. Artists are idiot savants who achieve greatness by unhinging themselves, as Rimbaud himself insisted&mdash;that&rsquo;s why the best of them die young; does it make sense to allow such people to speak for themselves? Besides, as a dancer, asked by a journalist to speak about her newest work, once rejoined, &ldquo;If I could tell you about it, I wouldn&rsquo;t have to dance it.&rdquo;</p>
<p> For best results, select the most incoherent and opaque artwork, rewarding artists and movements that produce this with positive coverage. Ideally, the public, knowing themselves unqualified to do, feel, or think anything on their own, should bypass the artwork completely, coming directly to the critics. It goes without saying that any creative person who makes concrete statements&mdash;the musician who speaks between songs, the poet who dares write about a current war&mdash;should be decisively ignored, or at least dismissed as superficial. This policy worked fabulously for art critics throughout the twentieth century, and indeed may explain the evolutionary trajectory of Western art across that era&mdash;not to mention recent developments in the punk rock scene.</p>
<h3>The Personal Anecdote</h3>
<p> When a reviewer feels the itch to hold forth about his own extensive experience as a widely traveled citizen of the world, he need not stick to the matter at hand. Many a frustrated travel writer, philosopher, religious mystic, and misanthrope has found a lasting career as a reviewer&mdash;not least because it is one of the few writing jobs in which it is not important that anyone actually read your work.</p>
<h3>Hearsay and Speculation</h3>
<p> Reviewers have to worry about their facts being checked about as much as federal agents at a bail hearing. Any old thing you heard or might have heard is fair game. It&rsquo;s your job to keep things interesting, so don&rsquo;t hesitate to spice up your review with a little scandalous gossip: <em>I used to be a card-carrying member of The Anarchist Movement, until I heard Bakunin was actually a paid agent of the Czar.</em></p>
<h3>The Stream of Invective</h3>
<p> This can range from a simple insult (regarding Jack Kerouac&rsquo;s claim that he wrote On the Road in a matter of days, Truman Capote quipped, <em>&ldquo;That&rsquo;s not writing, that&rsquo;s typing&rdquo;</em>) to a veritable torrent of abuse&mdash;which, in some cases, may be well deserved:</p>
<p style="padding-left: 20px"> Imagine Def Leppard if Wesley Willis was the principle songwriter and their vocalist sounded like a character from The Flintstones. Now imagine whatever you just imagined, only worse. There you have it, the debut from Andrew WK, &ldquo;I Get Wet.&rdquo; This makes the stuff they play over the public address systems at professional football games seem bookish and highbrow. The lyrics are pathologically tautological (&ldquo;you can&rsquo;t stop what you can&rsquo;t end&rdquo;), the riffs sound like cheap radio advertising jingles with some of the notes played wrong, the end of every song sounds like a television being switched off. For that matter, the beginning of every song sounds like a television being switched on! My friend Gabe says this makes him feel like he&rsquo;s at a keg party at a frat house, but there are no women there, just drunk, belligerent jocks and brain-damaged football players wrestling the furniture and shouting each other down about the stock market. Myself, I can&rsquo;t help but imagine this blaring over the speakers in the personnel bay of an army helicopter as GIs are airlifted into an Iraqi village to slaughter mothers and children&mdash;and as if in anticipation of this, Andrew has recorded a track in which he sings over and over &ldquo;You better get ready to kill, get ready to die.&rdquo; Even if you didn&rsquo;t have serious doubts about the future of Western civilization before you heard this release, one listen will make you a revolutionary in the tradition of the Dadaists and Situationists who set out to put an end to art itself&mdash;that is, if it doesn&rsquo;t reduce you to utter nihilism.</p>
<h3>Absurd Allegations</h3>
<p> When it&rsquo;s not possible to unleash a well-founded Stream of Invective, but the reviewer still desires to maintain the readers&rsquo; attention, he must fall back upon what philosophers call the straw man argument: he must concoct the most ridiculous make-believe version of the subject of the review he possibly can, and display his great strength and prowess by painstakingly tearing it apart.</p>
<p> In ideological circles&mdash;including certain anarchist camps, strange to tell, where so much talk of solidarity would lead one to expect constructive criticism to be the order of the day&mdash;this approach is even more common than the Comparison. Those who believe&mdash;often correctly&mdash;that their ideas can only be of interest if all other ideas are entirely bankrupt must remain ever vigilant, ready to pounce upon and discredit other thinkers by any means necessary.</p>
<h3>The Irrelevant Digression</h3>
<p> The digression comes in two forms. In the more common form, it is a sort of verbal smoking break in which the writer gets up from his desk, takes a breath, and stretches his legs, all without ceasing to address the reader. Reviewers who wish to curry favor with discriminating readers should throw in as many of these as possible: the less attention they pay to the subject of the review, the more bearable their writing is bound to be.</p>
<p> Alternately, the digression can be an underhanded way to slip in Absurd Allegations, when there is no more straightforward pretext for introducing them. For example, in the midst of a review of the thoroughly utilitarian <em>Recipes for Disaster: An Anarchist Cookbook</em>, which is simply a collection of direct action tactics, the <em>Anarchy Magazine</em> reviewer can, as if remaining on topic, stray into such ramblings as:</p>
<p style="padding-left: 20px">&ldquo;Their interpretation of social change seems to be that &lsquo;good people&rsquo; can, and should, be agents of social change. The material conditions of that change, the horrible consequences of &lsquo;bad people,&rsquo; and the history of social change that doesn&rsquo;t conform to the &lsquo;good people&rsquo; model are all outside the scope of CrimethInc.&rsquo;s approach. It is as if they have made a good and right choice and aren&rsquo;t going to let reality interfere with it.&rdquo; </p>
<h3>Sample Exercise</h3>
<p> Dash off a review of this How-To Guide and submit it to www.libcom.org. Whether you compose a Stream of Invective, an Absurd Allegation, or an Irrelevant Digression, and regardless of whether you have ever undertaken to write a single word before in the English language (or have read any of this text beyond than this sentence), your review is bound to be more balanced and informative than anything that would appear on that site otherwise<a class="footnote" href="javascript:void(0);" onclick="return overlib('The original version of this Guide included a dig at <em>Clamor</em> magazine, which had just uncritically published an authoritarian Marxist&rsquo;s atent&aacute;t on<em>Recipes for Disaster</em>. (With little reference to the content of the book or anything else, he utilized the majority of the review to slam CrimethInc. for not being authoritarian Marxists, ending with a quotation from Mao.) To our great dismay, <em>Clamor</em> ceased publication the following week, and several other small publishers to whom they had owed money perished with them. It is with great trepidation, then, that we train our poison pen on a new target.', CAPTION, '[1]');" onmouseout="nd();">[1]</a>.</p>
<h3>Appendix: Constructive Criticism</h3>
<p><em>From The Do-It-Yourself COINTELPRO Handbook:</em></p>
<p>In the end, our most dangerous enemies are not the subversive operatives themselves, who can be isolated and exterminated if it becomes necessary; they are, rather, those who offer constructive criticism of their efforts, for constructive criticism strengthens revolutionary endeavors and sharpens insurgent tactics. Fortunately, such criticism can be buried beneath an avalanche of hostility and impertinence.</p>
<p> Make every discussion into a debate with two opposed sides, pro- and anti-. This distracts attention from the ideas and subjects in question; it also compels all parties to entrench themselves in rigid positions. Always refer to your opponent&rsquo;s ideas as if they constitute a fixed, disembodied ideology; always address your opponent as if he is an automaton serving this ideology, not a complex being with a life history behind him.</p>
<p> Never approach involved persons with questions; always take your criticisms directly to the public. Do not offer any strategy other than your own the benefit of the doubt. Focus on the very simplest, stupidest, weakest points in any material; emphasize these. Disregard subtleties. Pick a simple accusation and stick with it, repeating it over and over until everyone is so fed up that they leave the entire arena of discussion to escape your negativity.</p>
<p> Make your objections simpler than your target text or tactic; it must be easier to be against it than it is to understand and interpret it. Unblushingly judge books by their covers. People should be able to take a stand with you without having to learn anything about the subject. Make it a style to dismiss as a style; make it a trend to accuse of being a trend.</p>
<p> Attack egos, exhaust patience, be as incoherent as possible. Make it impossible for anyone to derive anything positive from your tirades, despite their best intentions and efforts to get past your aggressive tone. When speaking of aspects of their work which make you feel alienated, for example, be as alienating as possible yourself. Defensiveness is what you want to provoke, above all&mdash;it discredits like nothing else. </p>
<p> Whatever demographics your opponent is reaching successfully, demonize. Utilize hot potato terms such as &ldquo;sexist&rdquo; and &ldquo;classist&rdquo;&mdash;use them over and over, with as little specific reference as possible, until it is impossible to have constructive discussions about the important issues these accusations raise. Assume you can represent the views of individuals from backgrounds other than your own&mdash;especially demographics that &ldquo;need&rdquo; representing, as if they cannot do it themselves. Refer to bona fide representatives of these demographics, when they appear in positions you didn&rsquo;t expect, as &ldquo;token.&rdquo;</p>
<p> Lower the level of discussion with pointless personal attacks, sarcasm, and self-righteousness. No depth is too low to stoop. Become obsessed with your crusade; calculate your blows to hurt feelings and offend bystanders. Everyone who has grown up in this vicious world has built up a certain amount of frustration and resentment; utilize this, learn how to trigger it in others. In every discussion, set negative energy in motion and make sure it wins out over constructive thought and respectful dialogue. Even if no one is persuaded by your arguments, this creates an environment that frightens off all outsiders.</p>
<p> Above all, be afraid. Be afraid of your own well-hidden doubts and vulnerabilities, and of others&rsquo; reputed superiority&mdash;and spread that fear, that shame, that guilt and resentment like a plague. Paralyze yourself and everyone else with blame for supposed imperfections. Hate yourself so much that you can only find respite in attacking others.</p>
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1]  The original version of this Guide included a dig at <em>Clamor</em> magazine, which had just uncritically published an authoritarian Marxist&rsquo;s atent&aacute;t on<em>Recipes for Disaster</em>. (With little reference to the content of the book or anything else, he utilized the majority of the review to slam CrimethInc. for not being authoritarian Marxists, ending with a quotation from Mao.) To our great dismay, <em>Clamor</em> ceased publication the following week, and several other small publishers to whom they had owed money perished with them. It is with great trepidation, then, that we train our poison pen on a new target.</p>
</div>