<h6 align="right" style="margin-right: 0px"><em>&raquo; Detailed maps of the events of September 24, 2009 are available <a href="https://cloudfront.crimethinc.com/images/rt9/rt9_maps.pdf">here.</a><br />An expanded version of this coverage appears in <a href="/rt">Rolling Thunder #9</a>. &raquo;</em></a></h6>
<h1>G20 Mobilization:  Preliminary Assessment</h1>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/g202/noborders_b.jpg" rel="lightbox[g202]"><img src="https://cloudfront.crimethinc.com/images/g202/noborders_a.jpg" width="500" height="333"></a></p>
<p>The reports are coming in, and many participants are describing the G20 protests in Pittsburgh as a success. This is exciting news; the US anarchist movement hasn&rsquo;t pulled off an unequivocally successful nationwide mobilization in half a decade or more. At the same time, success entails risks of its own: we may overlook the things we didn&rsquo;t do well, take credit for things outside our actual influence, or fixate on attempting to repeat ourselves. Meanwhile <a href="http://www.youtube.com/watch?v=dm1kSMSDJBw&amp;NR=1" target="_blank">the authorities</a>, who often exaggerate our effectiveness to justify repressing us, appear to be understating the extent of anarchist damage and disruption in Pittsburgh, perhaps to downplay the possibility of militant anticapitalism regaining momentum.</p>
<p>This appraisal explores the triumphs and shortcomings of the G20 mobilization, in hopes that these lessons can be applied soon on a variety of other battlefields.</p>
<p><strong>For a description of the context of the G20 and an account of the events of Thursday, September 24, read <a href="http://www.crimethinc.com/texts/recentfeatures/g20.php">this</a>. For a discussion of policing at the G20 and a report on the events of Friday evening, read <a href="http://www.crimethinc.com/blog/2009/09/30/state-repression-at-the-g20-protests/">this</a>.</strong></p>
<p>&nbsp;</p>
<h2>What Went Right in Pittsburgh</h2>
<p>Whenever a mass mobilization goes well&mdash;that is, about once a decade&mdash;every established organization and ideological faction hastens to explain how this confirms their pet theories or tactical preferences. It should not be surprising, then, that as big-tent anarchists&mdash;&ldquo;anarchists without adjectives&rdquo;&mdash;our take is that the Pittsburgh G20 protests succeeded because the efforts, strategies, and strengths of a wide range of participants were integrated into a complementary whole. Things would not have gone nearly as well had any of the elements been missing.</p>
<p>This time, everyone got what they wanted. The fundamental success in Pittsburgh was that everybody from strident pacifists to dogmatic nihilists managed to contribute to something larger than themselves; everything else followed from this.</p>
<p>Community organizers won public support and turned out far more than the usual suspects; this made the streets safer for everyone and helped expand dialogue beyond the radical ghetto. Those who wanted to confront the summit itself marched toward it on Thursday and demonstrated in front of it Friday afternoon; this provided a political narrative for the mobilization. Black bloc anarchists who wanted to avoid the authorities in order to attack everyday manifestations of capital got their wish, doing well over <a href="http://www.pennlive.com/midstate/index.ssf/2009/09/83_arrested_at_g-20_in_pittsbu.html" target="_blank">$50,000 of property damage</a> to corporations, <a href="https://cloudfront.crimethinc.com/images/g202/smash_b.jpg" rel="lightbox[g202]">police</a>, and university <a href="http://pittaav.blogspot.com/2009/09/newsletter-16-9282009.html" target="_blank">animal testing facilities</a>. Those who wished to cast themselves as legitimate protesters whose voices were being suppressed by a police state had adequate opportunity to do so, and were joined by hundreds of unwitting University of Pittsburgh students in a spectacle that could only erode the credibility of the authorities.</p>
<p>Meanwhile, anarchists gained credibility both by taking the initiative in organizing and by cooperating successfully with other groups. Thursday&rsquo;s anarchist-organized unpermitted march was the main action of the first day of the G20, drawing participants from all sorts of political perspectives and social backgrounds; on Friday, a raucous anarchist contingent swelled the permitted march organized by the <a href="http://pittsburghendthewar.org/" target="_blank">Anti-War Committee</a> (AWC). Though some had initially feared that the <a href="http://resistg20.org/principles" target="_blank">Pittsburgh Principles</a> were a watered-down version of the <a href="http://rnc08report.org/archive/224.shtml" target="_blank">St. Paul Principles</a> established in the <a href="http://www.crimethinc.com/texts/recentfeatures/rncdnc.php" target="_blank">mobilization against the 2008 RNC</a>, they succeeded in enabling anarchists and others to coordinate actions and maintain solidarity.</p>
<p>In this regard, we can see the G20 mobilization as building on the precedents set by the 2008 RNC mobilization to establish the legitimacy of anarchist organizing in the public eye. In the anti-war era, anarchist organizing was successfully marginalized by liberal groups; anarchists organized breakaway marches and other peripheral actions but repeatedly failed to take the initiative to determine the fundamental character of mass protests. In hopes of breaking this pattern, anarchists got started well over a year before the 2008 RNC, emerging as one of the major players in the organizing.</p>
<p>The first day of the RNC, anarchists participated in decentralized marches and blockades, while anti-war activists sponsored a permitted march. This was based partly on the reasoning that the most successful direct-action-oriented protests of the preceding decade had been coordinated to coincide with other events, spreading the police thin. In Pittsburgh, <a href="http://resistg20.org/" target="_blank">the Pittsburgh G20 Resistance Project</a> (PGRP) went further, organizing an unpermitted march as the only event for the first day&mdash;an ambitious gamble.</p>
<p>The Anti-War Committee had discussed scheduling its permitted march for Thursday as well, but the PGRP had already announced the unpermitted march for that day. This meant that the AWC had the option of repeating the format of the 2008 RNC; however, some prominent participants stated that they were convinced that the story of the day on Thursday was bound to be the PGRP march. The AWC chose instead to hold the permitted march on Friday.</p>
<p>So it happened that the main event opening the G20 protests was organized primarily by anarchists and according to anarchist principles. This made other aspects of the mobilization easier: for example, liberals who might otherwise have attempted to discredit the PGRP were hesitant to do so, knowing that many members of their groups were participating in the Thursday march. At the same time, it raised the stakes: if anarchists and their allies were solely responsible for the first day of the protests, they could hardly afford to &ldquo;<a href="http://www.crimethinc.com/texts/atoz/rncdnc.php" target="_blank">go it alone</a>,&rdquo; failing to bring out other demographics.</p>
<p>Accordingly, the PGRP organized a local outreach operation improving on the door-to-door efforts the RNC Welcoming Committee had carried out in the Twin Cities; this reached a majority of the houses in Greenfield, Bloomfield, and Lawrenceville, among other neighborhoods. For $400, the PGRP printed 10,000 copies of a four-page newspaper in plain language that connected the G20 to local issues such as transit, war, and healthcare.</p>
<p>The RNC Welcoming Committee had over <a href="http://news.infoshop.org/article.php?story=20070211225811580" target="_blank">a year and a half</a> to prepare for the 2008 RNC; Pittsburgh anarchists had barely <a href="http://news.infoshop.org/article.php?story=20090531213049472" target="_blank">four months</a> to prepare for the G20. Estimates of anarchist participation in the RNC protests vary, but most peak around 1000; at the spokescouncil the day before the action, something like 500 people were represented. At the spokescouncil the night before the G20 protests, perhaps 300 people were represented, provoking some distress; but the following day over 1000 people gathered at Arsenal Park for the unpermitted march.</p>
<p>A few hundred of these were militant anarchists from around the US, but a great number of them were Pittsburgh locals. Some of the latter were liberals and radicals who had developed relationships with anarchists in the <a href="http://www.organizepittsburgh.org/" target="_blank">Pittsburgh Organizing Group</a> (POG) in its seven years of activity preceding the formation of the PGRP; some were students, out in greater numbers than expected because the school district cancelled classes during the summit; others were simply people who had stumbled upon the PGRP call to action against the G20. They came out despite the efforts of the government and corporate media to intimidate them and discredit anarchist organizers. Many of them stayed in the streets despite the waves of repression that ensued.</p>
<p><a href="https://cloudfront.crimethinc.com/images/g202/killfarmers_b.jpg" rel="lightbox[g202]"><img src="https://cloudfront.crimethinc.com/images/g202/killfarmers_a.jpg" width="500" height="332"></a></p>
<p>Even those who only wish to fight police and destroy corporate property must acknowledge the importance of the outreach that involved all these people in the mobilization. Without this social body, it would have been easy for the police to focus on repressing isolated anarchists, and successful direct action would have occurred in a vacuum rather than in a social context in which it could be inspiring and infectious.</p>
<p>In positioning themselves to lay the groundwork for such outreach and coordination, long-running organizations like POG serve an essential role in the infrastructure of the anarchist movement. This goes for the more recently established Greater Pittsburgh Anarchist Collective, as well, which also contributed to PGRP organizing. If we want to see large-scale mobilizations, there have to be groups with the capacity and credibility to organize them: groups everyone can trust to come through on their commitments, so people know they are not taking a great risk by showing up from out of town. This is not to say that every anarchist must organize in such a group, or that this is the most important form of anarchist organizing&mdash;but without at least a few of these, anarchists will be doomed to the periphery of protest movements, and may find it difficult to coordinate other large-scale forms of resistance as well.</p>
<p>All this said, had the PGRP turned out 1000 participants for a march that simply ended up being dispersed or mass-arrested in the empty industrial zone southwest of Arsenal Park, it would not have been nearly as empowering as what happened. Autonomous anarchists making decisions outside the PGRP framework played an essential role in the success of the G20 protests.</p>
<p>Anarchists focused on conflict and property destruction have long fantasized about &ldquo;<a href="http://anti-politics.net/downloads/Politics_is_not_a_banana_Online/banana_pages.pdf" target="_blank">Plan B [PDF, 14.8 MB]</a>&rdquo;&mdash;the idea that, rather than attacking heavily defended symbolic manifestations of state and capital such as summit meetings, would-be rioters should appear where they are least expected in order to do more damage with impunity. This model notoriously failed at the 2007 anti-G8 mobilization in Germany, among other places. In theoretical terms, Plan B is an attempt to free direct action from the baggage of activism, to channel dissent into resistance rather than performing it reactively and symbolically. It could be said that, at worst, the reasoning behind &ldquo;Plan B&rdquo; fails to take into account the social and psychological foundations of the successful street actions of the past decade, approaching rioting in purely military terms. The social body behind the anarchist riots of recent memory has been bound together as much by the feeling of entitlement that comes of fighting an obvious external foe as by the clandestine networks and illicit desires championed by partisans of Plan B.</p>
<p>In Pittsburgh, however, as out-of-town anarchists arrived and familiarized themselves with the terrain, some concluded it would be disastrous to march towards the summit and directly into a police trap; this included some who had not previously been enthusiastic about Plan B. With thousands of police waiting for it, no one believed the march had any chance of reaching the convention center; if the point was simply to stage a confrontational protest, the empty corridor between Arsenal Park and the convention center was hardly the most opportune setting.</p>
<p>At the same time, as so many locals had been brought into the mobilization on the grounds that they were going to march on the G20, it was impossible to change plans without losing the social body of the march. PGRP organizers argued this at the spokescouncil, and this was further underscored when the body of the march refused to follow the black bloc at the front when it turned east away from the convention center on its way out of Arsenal Park. Everyone else continued toward the summit, and the bloc that had headed east turned back and rejoined the mass. The choice not to split the march proved pivotal: because of this, when it later proved impossible to make any headway toward the convention center, a great many more people headed east than had initially attempted to.</p>
<p>Had the entire march continued east at the outset rather than heading toward the convention center as promised, there would surely have been intense controversy afterwards, which might have seriously undermined Pittsburgh anarchists&rsquo; credibility in the eyes of their community. Fortunately, the way things played out, everyone got to do what they wanted, and to do it <em>together.</em></p>
<p>Only a few blocks west of Arsenal Park, the march came up against a line of police excited to show off the sonic weaponry of their new <a href="http://en.wikipedia.org/wiki/Long_Range_Acoustic_Device" target="_blank">LRAD vehicle</a>. The LRAD <a href="http://gothamist.com/2009/09/29/eardrum-blasting_sound_cannon_comin.php" target="_blank">was not particularly effective against anarchists</a>, many of whom have willingly subjected themselves to similarly unpleasant noises at comparable volumes as a result of their <a href="http://www.youtube.com/watch?v=kIBBerDiDXY&amp;feature=player_embedded" target="_blank">musical tastes</a>. But the march wisely chose not to make a serious attempt to breach the police lines, knowing there must be more police waiting ahead to block and likely surround them.</p>
<p><a href="http://twincities.indymedia.org/2009/sep/photos-thursdays-anti-g20-peoples-uprising" target="_blank">Indymedia photographs</a> have since confirmed this, showing a much larger police contingent waiting a couple blocks past the first police blockade:</p>
<p><a href="https://cloudfront.crimethinc.com/images/g202/pano_b.jpg" rel="lightbox[g202]"><img src="https://cloudfront.crimethinc.com/images/g202/pano_a.jpg" width="500" height="143"></a></p>
<p>In the end, by blocking the route to the convention center, the police were the ones who forced marchers to turn around and head east. They can be held responsible for everything that happened next&mdash;the property destruction, the pepper-gassing of civilians, the disruption of business and traffic. However, the shift of the action eastward probably would not have occurred so decisively had autonomous anarchists not already been discussing the potential of setting out in that direction.</p>
<p>Once the rest of the city was added to the terrain of struggle, it was a whole new ball game. Protesters were not simply chanting in isolation, but transforming the urban landscape according to a new logic. The police were not simply staffing a militarized zone far from the public eye, but interrupting the flows of business as usual. This was no longer protest as private grudge match, but a public event that affected everyone whether or not they had previously taken a side.</p>
<p>Everything that occurred in Oakland&mdash;the mass standoff with the police, <a href="http://www.youtube.com/watch?v=Rc1IGqlekvs" target="_blank">the black bloc that decimated the business district</a>, the police riot the following night&mdash;came as a surprise to practically everyone. On Wednesday, everybody from local organizers to out-of-town maniacs had agreed that Oakland would be impassable on account of the G20 leaders&rsquo; visit to neighboring Schenley Park. The extension of the demonstration into the city at large opened up possibilities that had been unimaginable.</p>
<p>If protest is essentially theater, anarchists were <a href="http://en.wikipedia.org/wiki/Fourth_wall" target="_blank">breaking the fourth wall</a>, involving the audience in the play. There is a great deal of talk about this in anarchist circles, but it rarely occurs on the transformative level everyone desires. It is perhaps ironic that the actions of black bloc anarchists were instrumental in bringing this about. The local organizers had kept the social body of protesters together by insisting on heading towards the convention center, but it was the autonomous anarchists&rsquo; movement away from the convention center that involved the rest of the city in the action.</p>
<span class="readinggallery"><a href="https://cloudfront.crimethinc.com/images/g202/gal1_b.jpg" rel="lightbox[g202]" >
<img src="https://cloudfront.crimethinc.com/images/g202/gal1_a.jpg" width="156" height="104"></a>
<a href="https://cloudfront.crimethinc.com/images/g202/gal2_b.jpg" rel="lightbox[g202]" >
<img src="https://cloudfront.crimethinc.com/images/g202/gal2_a.jpg" width="156" height="104"></a>
<a href="https://cloudfront.crimethinc.com/images/g202/gal3_b.jpg" rel="lightbox[g202]" >
<img src="https://cloudfront.crimethinc.com/images/g202/gal3_a.jpg" width="156" height="104"></a>
<a href="https://cloudfront.crimethinc.com/images/g202/gal4_b.jpg" rel="lightbox[g202]" >
<img src="https://cloudfront.crimethinc.com/images/g202/gal4_a.jpg" width="156" height="104" style="margin-bottom: 15px"></a>
<a href="https://cloudfront.crimethinc.com/images/g202/gal5_b.jpg" rel="lightbox[g202]" >
<img src="https://cloudfront.crimethinc.com/images/g202/gal5_a.jpg" width="156" height="104" style="margin-bottom: 15px"></a>
<a href="https://cloudfront.crimethinc.com/images/g202/gal6_b.jpg" rel="lightbox[g202]" >
<img src="https://cloudfront.crimethinc.com/images/g202/gal6_a.jpg" width="156" height="104" style="margin-bottom: 15px"></a></span>
<p>The fierceness of Thursday&rsquo;s black blocs bears special comment. There were only a few hundred police in Seattle, and they more than had their hands full dealing with other demonstrators. The black bloc in Pittsburgh, on the other hand, was menaced by ten times that number of police, but still wreaked considerable havoc. On Thursday night, when a couple hundred anarchists rampaged through downtown Oakland, there were hundreds of militarized police mere blocks away; police vehicles showed up at the very outset of the march, but the participants were utterly unfazed. Though the events in Pittsburgh hardly compare to the actions of some black blocs overseas, they are impressive in the US context.</p>
<p>It has been said that the demonstrations of the past decade have functioned as a sort of inoculation for the police state: without ever seriously threatening it, they have provoked it to develop a much more powerful immune system. Yet it may be that this police state has also bred a tougher breed of anarchist, too, the way that new strains of virus evolve that are immune to existing vaccines. The state has not succeeded in suppressing the desires that motivate anarchist resistance. In Pittsburgh, whenever an opening appeared, anarchists poured eagerly into it&mdash;smashing windows by the dozen, hailing projectiles onto police lines, and largely escaping unscathed.</p>
<p>It was significant that the actions of the black bloc were integrated into the rest of the protest, occurring together with and as an expression of the whole. Had the Plan B fantasy led instead to some entirely clandestine action distant from the rest of the protesters, it might  have set a dangerous precedent for that faction of the US anarchist movement, signifying a slide towards the logic of closed circles and armed struggle. Instead, militant confrontation was collective and infectious. The most militant elements established a symbiotic relationship with the larger social body in the streets on Thursday: despite the wide range of participants, there were few cases of serious conflict over tactics.</p>
<p>By choosing to participate in an unpermitted march, everyone present had taken a stand in favor of disruption; tactics that might have been controversial elsewhere, such as rolling dumpsters at police or smashing corporate windows, were interpreted as expressions of the collective desire to hold ground or as legitimate retaliation for indiscriminate police violence. Together, the black bloc and the rest of the protesters made mass arrests very difficult: the sheer numbers made wholesale encirclement impractical and politically costly, while the speed, mobility, and ferocity of the militant minority stretched police attention over a wide area and prevented the police from controlling the crowd. For example, at the end of Thursday afternoon when the police attempted to prevent the crowd from entering Oakland by blocking them off at the intersection of Liberty and Baum, not only did the black bloc get through their lines, but the challenges of holding back the rest of the crowd kept the police busy while the bloc barricaded the street, smashed the windows of Boston Market and other establishments, and penetrated deep into Oakland. This forced the police to occupy the entire neighborhood with a military force, precipitating the events of that evening and the following day.</p>
<p><a href="https://cloudfront.crimethinc.com/images/g202/dumpster_b.jpg" rel="lightbox[g202]" title="Photo by Foo, http://www.iwasaround.com"><img src="https://cloudfront.crimethinc.com/images/g202/dumpster_a.jpg" width="500" height="332"></a></p>
<p>So much attention has focused on Thursday that it&rsquo;s easy to forget about the <a href="http://resistg20.org/friday" target="_blank">actions called for Friday morning</a>. As in the calls for autonomous actions at the 2004 Democratic and Republican National Conventions, which <a href="http://www.crimethinc.com/texts/pastfeatures/demonstrating.php" target="_blank">were not subsequently deemed particularly successful</a>, a  <a href="http://maps.google.com/maps/ms?ie=UTF8&amp;hl=en&amp;msa=0&amp;msid=107721976781220532219.0004707c58f14ffc66b77&amp;z=14&amp;iwloc=000470cd047d3f45ad29e" target="_blank">list</a> was circulated of local targets embodying everything objectionable about global capitalism. Some local organizers who were pessimistic about the potential of mass mobilizations saw the Friday call to action as a way to connect the G20 protests to local issues; for others, it was a fallback plan in case Thursday was a washout, and a way to draw attention to the targets through advance media coverage. It had an unintended effect, however: by Wednesday, a great number of the establishments on the list had boarded up their shop fronts and announced that they were closed for the week. This forced organizers to rethink the strategy for the day, as it made less sense to call for actions at closed, boarded up targets. Some actions still occurred&mdash;including an Iraq Veterans Against the War march and actions outside a recruiting station and a Whole Foods&mdash;but it would have taken a great deal of street activity to have interrupted business as usual to the extent that the call to action did on its own.</p>
<p>Downtown Pittsburgh was similarly affected. <a href="http://www.post-gazette.com/pg/09270/1001172-482.stm" target="_blank">According to some reports</a>, barely 20% of the people who normally work in or travel through downtown did so during the summit. Surely this is more due to alarmist rhetoric and overzealous policing than to anarchist organizing; we could hardly overthrow capitalism simply by subjecting it to such inconveniences, anyway. But it does give a sense of the context of repression and control in which anarchists were nonetheless able to act.</p>
<p>Shortly before the demonstrations, the authorities in Pittsburgh were attempting to backpedal on their original scare-tactic story about anarchists coming to destroy the city. Apparently the spin had gotten out of control, and the city government was eager to reassure businessmen and consumers that the anarchists did not pose such a dramatic threat after all.</p>
<p>This brings us to the final successful aspect of the mobilization&mdash;media liaison work. Advance media coverage is the space in which police lay the groundwork to justify raids and violent repression; to the extent to which activists can counteract these smear campaigns, they can tie the hands of police, although corporate media is hardly a neutral playing field.</p>
<p>One person from the PGRP gave dozens of on-camera interviews, repeating talking points consensed on by the media working group; a pseudonym was used by various members of the group to reply to telephone and email interviews. While refuting police fabrications, representatives of the PGRP never shied away from the politics or intentions of the group; this may have helped legitimize Thursday&rsquo;s unpermitted march in some eyes, drawing more participants. It&rsquo;s also possible that such a forthright media policy discouraged police from raiding spaces before the G20, although there are several other possible explanations for this.</p>
<p>Immediately after the demonstrations, the <a href="http://www.post-gazette.com/pg/09269/1000990-482.stm" target="_blank">Pittsburgh Post-Gazette</a> actually admitted in the first sentence of a front-page article that anarchists &ldquo;weren't stockpiling human waste to throw at police.&rdquo; This kind of honesty is almost unheard of in the world of corporate journalism. Other stories were comparably favorable, at least compared to the usual flood of mendacity.</p>
<p>It&rsquo;s possible that obtaining fairer coverage was easier this time around because, for once, anarchists were part of <a href="http://www.usatoday.com/money/world/2009-09-24-g20-jobs_N.htm" target="_blank">a story the media wanted to tell</a>. Corporate reporters generally have a story ready in advance to feed to interviewees, in order to make their own job as simple as possible; perhaps, in this case, anarchists happened to be useful for the spin journalists planned to put on the summit, with the recession on and discontent simmering. In any event, we can&rsquo;t count on being fairly represented by the corporate media in the future, even if others emulate the work of the PGRP media working group.</p>
<p><br />
</p>
<h2>Repression: Police Tactics and Strategy</h2>
<h5>&ldquo;We&rsquo;re trying to thin out the innocent.&rdquo;</h5>
<p align="right" style="margin-top: -10px"><em>&ndash;Pittsburgh University Police Chief Tim Delaney, <br />
<a href="http://post-gazette.com/pg/09277/1002977-482.stm" target="_blank">quoted</a> by corporate media reporter Rich Lord <br />
(we can&rsquo;t make this stuff up!)</em></p>
<p><a href="https://cloudfront.crimethinc.com/images/g202/kid_b.jpg" rel="lightbox[g202]"><img src="https://cloudfront.crimethinc.com/images/g202/kid_a.jpg" width="500" height="337"></a></p>
<p>Up until 2 p.m. Thursday, many doubted the unpermitted march would even make it out of Arsenal Park. Organizers and anarchists of all stripes dramatically misread the plans of the police. Things turned out better than expected, but it is bad news, not good news, when we fail to predict our foes&rsquo; behavior accurately.</p>
<p>Let&rsquo;s look again at the context shaping the police strategy. The weeks before the G20 saw a pitched struggle in the media and the city government. The liberal community was pushing civil liberties issues, with the ACLU <a href="http://www.aclupa.org/legal/legaldocket/g20case.htm" target="_blank">winning a lawsuit</a> over the right to demonstrate; the City Council was divided, having <a href="http://www.pittsburghlive.com/x/pittsburghtrib/news/breaking/s_643260.html" target="_blank">struck down</a> a mask ordinance despite pressure from police and presumably the federal government. One City Council member went so far as to <a href="http://www.pittsburghcitypaper.ws/gyrobase/Content?oid=oid:69194" target="_blank">attend the beginning of Thursday&rsquo;s unpermitted march</a>; he had also showed up at the <a href="http://resistg20.org/tuesday" target="_blank">picnic at Friendship Park on Tuesday</a>, and it may not have been coincidental that the police massing nearby disappeared immediately afterwards.</p>
<p>The police had already <a href="http://www.pittsburghcitypaper.ws/gyrobase/Content?oid=oid%3A66453" target="_blank">embarrassed themselves</a> with heavy-handed scare tactics weeks before the summit. The local police force was far too small to handle the G20 alone, but bringing in additional forces increased the challenges of coordination and the likelihood that outside officers might behave in ways that could be costly for the city. The city government was extremely short on funds, and could hardly afford the processing costs of mass arrests, let alone consequent lawsuits.</p>
<p>Police intelligence&mdash;oxymorons aside&mdash;seemed to be at an all-time low. The police attempted to recruit spies from adjacent social milieus, offering money for them to report on protest organizing; but as the PGRP came together largely out of long-existing relationships, most of the working groups were composed of people who had a lot of context for each other. There were internal conflicts about the exclusion of suspicious individuals, but&mdash;unlike the RNC Welcoming Committee&mdash;those who were suspected of being police agents were not permitted to participate in sensitive organizing. With only a few months warning that the G20 was to occur in Pittsburgh, the authorities had considerably less time to infiltrate activist circles. They had already been tracking many PGRP organizers for years, and they continued physically tracking them up to and during the summit; but it may be that a lack of informants directly within organizing circles prevented the state from manufacturing incriminating statements that could offer pretexts for raids or conspiracy charges. The FBI did not repeat the despicable tactic of <a href="http://www.crimethinc.com/blog/2009/06/24/towards-a-collective-security-culture/" target="_blank">entrapping impressionable young activists</a> that it had employed at the RNC, either.</p>
<p>There are indications that the conspiracy charges brought against the organizers known as the <a href="http://rnc8.org/" target="_blank">RNC 8</a> were not ordered by the federal government, but rather by overzealous Ramsey County authorities; the case has not gone well for the state thus far, which has already been compelled to drop the terrorism charges against them. This is another possible explanation of why no similar charges have been brought against PGRP organizers, whether or not the internal security practices of the PGRP were more effective than those of the RNC 8. Either way, it appears that the RNC 8 charges do not set an inexorable precedent for the future. Those who organize anarchist frameworks for mass mobilizations won&rsquo;t automatically be charged with felony conspiracy, though this is not to say that it will never happen again. Much may still hinge on the outcome of the RNC 8 trial.</p>
<p>Without actionable intelligence on anarchist organizing, rank-and-file police focused on harassing <a href="http://www.examiner.com/x-10661-Pittsburgh-Grassroots-Examiner~y2009m9d21-G20-Green-City-sends-40-cops-to-Landslide-Community-Farm-again" target="_blank">subcultural spaces</a> in the weeks before the summit. They did seem prepared to carry out raids&mdash;they hassled several collective houses as well as Seeds of Peace, they threatened the convergence space and the <a href="http://community.post-gazette.com/blogs/bigstory/archive/2009/09/25/police-check-out-makeshift-medical-facility.aspx" target="_blank">Wellness Center</a>, they located and raided the alleged comms space even though it was twenty miles outside of town&mdash;but they didn&rsquo;t seriously go after organizers&rsquo; or protesters&rsquo; housing.</p>
<p>This may have been the result of a cost-benefit analysis. The city was attempting to downplay the negative impact of the G20 summit and the repressive policing surrounding it, and raids would have had the opposite effect. Meanwhile, protesters were not gathered in or especially dependent on any one space. Although the lack of centralized housing for out-of-town protesters was inconvenient, it meant that no single police raid could have significantly disrupted the mobilization. We will certainly see more police raids in the future, and the authorities must have been prepared to carry them out in Pittsburgh, but it seems they concluded at the end that there was nothing to gain from doing so.</p>
<p><a href="https://cloudfront.crimethinc.com/images/g202/bus_b.jpg" rel="lightbox[g202]"><img src="https://cloudfront.crimethinc.com/images/g202/bus_a.jpg" width="500" height="307"></a></p>
<p>This brings us back to the afternoon of September 24. In response not only to protester hype but also to the usual counterinsurgency paranoia, thousands of police and National Guard had been brought into Pittsburgh at a cost of millions and millions of dollars. The local government wasn&rsquo;t particularly eager to set them loose on demonstrators, but the PGRP march left them no choice.</p>
<p>Police were out in force around Arsenal Park, with the rest of their numbers almost all positioned west of it. They had an initial line ready to intercept the unpermitted march at <a href="http://www.youtube.com/watch?v=ia0wVU3RHkI" target="_blank">37th and Penn Avenue</a>, and a considerably stronger body of troops a couple blocks behind that. They planned to confront the crowd in this comparatively isolated area, pepper-gassing the working-class inhabitants of the neighborhood as well as the protesters. It is possible they were prepared to make mass arrests&mdash;they did so the following night, when it didn&rsquo;t make any sense at all&mdash;but they didn&rsquo;t attempt to make them immediately. Instead, the police strategy rested on crowd control and dispersal; they planned to break up the crowd from a distance, rather than engaging in hand-to-hand combat. The vision of 1000 people being beaten and arrested on the evening news was simply too much for local politicians to stomach.</p>
<p>The police don&rsquo;t seem to have placed many undercovers in the march. This must have been dictated by their strategy. Relying on distance weapons that affect everyone indiscriminately&mdash;pepper gas, the LRAD, beanbag rounds&mdash;they could hardly fill the march with agents who would be endangered by these. In most of the snatch arrests that transpired Thursday afternoon, a car pulled up and officers leaped out to grab the victim. This indicates fears for the safety of officers in the vicinity of protesters, and police representatives have said as much in subsequent interviews about the snatch arrests.</p>
<p>A police strategy of crowd control and dispersal is convenient for anarchists in a variety of ways. Fewer arrests means higher morale coming out of the mobilization and less legal support work afterwards; crowd control agents and &ldquo;less lethal munitions&rdquo; dramatize the oppressive nature of the police state, creating an atmosphere of social conflict. In North America, we rarely see the police respond to anarchist demonstrations with this strategy; the Quebec City anti-FTAA protests of April 2001 are one of the only other examples of this occurring on a large scale. Presumably the authorities only adopt this approach when they are convinced that they are going to be dealing with a great number of protesters, at least some of whom are capable of defending themselves.</p>
<p>It was a tremendous victory in advance that the police adopted this strategy. Again, a great part of the credit for this goes to the PGRP, whose organizing work made it clear ahead of time that Thursday&rsquo;s march would not be safe to trifle with. Beyond this, it seems to have been the result of external limitations. Anarchists should not congratulate themselves too much on the results of this fortuitous development; it would be more useful to focus on learning how to predict and produce similar police strategies in the future. If we manage to pose a serious threat, the state will surely mobilize every force at its disposal against us; but there is a lot to be gained from analyzing the factors that determine how the state can apply that force.</p>
<p>As has been seen at other mobilizations, the police were hesitant to confront those who were capable of defending themselves; consequently, the latter suffered a great deal less state violence than peaceful protesters and hapless bystanders. As counterintuitive as it sounds, it is often safer at the front of the black bloc than at the back of a crowd of confused spectators.</p>
<p>Subsequent <a href="http://post-gazette.com/pg/09277/1002977-482.stm" target="_blank">newspaper reports</a> have shed some light on the failure of police to respond to the Bash Back! march that devastated the university district Thursday night. If these are to be believed, emergency response officers were powerless to respond because they had been assigned to guard the area around nearby Phipps Conservatory, where the G20 leaders were dining. It was extremely audacious to attack the shopping district only a couple blocks away, but coupled with speed and the element of surprise, audacity can pay off, especially in a terrain that lends itself to swift movement and dispersal. It&rsquo;s still surprising that police did not surround the march from the very beginning. Perhaps they were overextended policing the rest of Oakland and keeping up with the disturbances around the corner by Schenley Plaza; or perhaps they believed the statement at the previous night&rsquo;s spokescouncil that the Bash Back! march would be a &ldquo;nonviolent&rdquo; event.</p>
<p>The <a href="http://post-gazette.com/pg/09277/1002977-482.stm" target="_blank">same sources</a> indicate that the authorities were crippled by the challenges of integrating officers from so many different departments into one command structure. This made it impossible to encrypt radio communications completely; police saw their on-air orders appear moments later in Twitter reports, prompting them to shift to cell phone communication, which cannot have improved matters. If the actions of the black bloc at the RNC in St. Paul did not completely dispel the myth of the all-powerful police state, the G20 protests should finish the job.</p>
<p><a href="https://cloudfront.crimethinc.com/images/g202/cordon_b.jpg" rel="lightbox[g202]"><img src="https://cloudfront.crimethinc.com/images/g202/cordon_a.jpg" width="500" height="335"></a></p>
<p>Massive marches like Thursday&rsquo;s can be an appropriate space for defensive materials such as reinforced banners; these limit speed and mobility, but can shield against police attacks. The laws passed in advance to forbid defensive equipment do not seem to have been a factor in police actions or charges brought against demonstrators, but they may have helped discourage anarchists from bringing such materials. There were surprisingly few banners of any kind, with most anarchists opting to travel light so as to move swiftly and adapt to circumstances. Because anarchists spent much of Thursday avoiding, outrunning, and outsmarting police forces, this was probably for the best, but it could have been a more serious problem had it been necessary to break through police lines more often. During a confrontation at 38th and Mintwood, riot police attempted to block two dozen people in an alley; the protesters forced their way out in a shoving match that left the banners in enemy hands.</p>
<p>Instead of targeting organizers with conspiracy charges, the authorities <a href="http://www.pittsburghlive.com/x/pittsburghtrib/news/pittsburgh/s_646374.html" target="_blank">brought felony charges</a> against two alleged participants in the communications structure. In the absence of leaders, comms is something the state can understand as a nerve center; the comms office was raided at the RNC as well, though the state released arrestees without charges. The communications system in Pittsburgh continued functioning after the raid and arrests; it is absurd to charge two people with masterminding the protests when hundreds and hundreds of people were acting, communicating, and making decisions independently on the ground.</p>
<p>Just as the RNC 8 trial will set an important precedent for organizing in the US, this case will be instrumental in determining how communications technologies can be used in the 21st century. The FBI has since <a href="http://news.infoshop.org/article.php?story=20091004231103793" target="_blank">brutally raided one defendant&rsquo;s house</a>, underscoring how important this is to our oppressors. It should also be important to anyone who feels strongly about free speech, regardless of their political views. We strongly urge everyone to circulate information about this case and support the defendants by any means.</p>
<p>As of this writing, the story has just reached <a href="http://www.npr.org/templates/story/story.php?storyId=113513780" target="_blank">National Public Radio</a>, and one of the defendants has <a href="http://www.democracynow.org/2009/10/6/twitter_crackdown_nyc_activist_arrested_for" target="_blank">appeared</a> on <a href="http://www.democracynow.org/" target="_blank">Democracy Now!</a> The search warrant for the raid, an inventory of seized items, and the original criminal complaint can be seen <a href="http://www.eff.org/deeplinks/2009/10/man-arrested-twittering-goes-court-eff-has-documen" target="_blank">here.</a></p>
<p><br />
</p>
<h2>Room for Improvement</h2>
<h5><br />
Perhaps the most important question is whether we can consolidate the progress we&rsquo;ve made through the RNC and the G20 towards determining the format and character of protest in the United States.</h5>
<p><a href="https://cloudfront.crimethinc.com/images/g202/mega_b.jpg" rel="lightbox[g202]"><img src="https://cloudfront.crimethinc.com/images/g202/mega_a.jpg" width="500" height="375"></a></p>
<p>Many anarchists sat out the G20 protests, not expecting them to be successful or important. The few hundred who did come from out of town were able to accomplish a great deal, thanks largely to local participation; but the anarchist movement should be able to mobilize greater numbers for events like this. It needn&rsquo;t interrupt ongoing local organizing to take a few days off once a year for a mobilization. In another setting, a black bloc of three hundred would simply not have been enough.</p>
<p>Many participants vastly overestimated the repressive power of the authorities in advance, perhaps in part because it has been so long since a successful mobilization on this scale. In some ways, the events of Thursday were a pleasant surprise, but it&rsquo;s never advantageous to misjudge the plans of the police. For example, at the spokescouncil the night before, several dozen protesters agreed to do jail solidarity on the assumption that enough of them would be arrested that they would constitute a force with some leverage. As it turned out, only a very small number of them were arrested, leaving the few individuals who refused to give their names in jail high and dry.</p>
<p>It is impossible to predict police strategy with any certainty, but being able to do so more accurately would help anarchists plan better. Many people are probably kicking themselves now for not going to Pittsburgh. In many ways, the anarchist movement is still haunted by the ghosts of the Miami FTAA and the St. Paul RNC, even though we have entered a new era. If anarchists maintain confrontational organizing in the wake of the G20, we can expect the state to increase the force it employs against us, but this cannot render us powerless&mdash;only our own fear and disorganization can do that. The battles that took place in Pittsburgh offer instructive examples of how outnumbered and outgunned protesters can nevertheless strike effective blows in the street.</p>
<p>As in practically every other sphere of anarchist organizing, attrition remains one of our most serious problems. Very few of the participants in the G20 mobilization were involved in mobilizations around the turn of the century; if we don&rsquo;t retain more participants from this generation, we will have to relearn the same lessons and build up the same skillsets all over again in another decade or less.</p>
<p>Perhaps the most important question is whether we can consolidate the progress we&rsquo;ve made through the RNC and the G20 towards determining the format and character of protest in the United States. It&rsquo;s not clear whether other anarchist communities will be able to replicate the achievements of their comrades in Minneapolis and Pittsburgh. In struggling to present alternatives to the docile and defeatist forms of protest currently viewed as legitimate, we are going against the grain of political discourse in the US; if we can succeed at this, it will change the shape of resistance movements in this country. Let&rsquo;s hope Pittsburgh was not an anomaly, but a step towards this.</p>
<p>The same day the unpermitted march gathered at Arsenal Park in Pittsburgh, students and workers <a href="http://news.infoshop.org/article.php?story=20090930042235427" target="_blank">occupied the Graduate Student Commons</a> at the University of California at Santa Cruz, while students at the New School in New York City <a href="http://www.newschoolinexile.com/News/article/sid=67.html" target="_blank">shut down a talk by former Secretary of Homeland Security Tom Ridge</a>. These actions are at least as important and instructive as the G20 protests; we can stage a mass mobilization once a year, but we win or lose ground in the struggle against hierarchy in ongoing local engagements.</p>
<p>In that regard, the strategic lessons of Pittsburgh are no more important than the feeling of empowerment that participants took home with them. Hundreds of people now feel in their bodies that, should circumstances require, they can don masks and sweatshirts and become an unstoppable force of defiance.</p>
<p><a href="https://cloudfront.crimethinc.com/images/g202/goodtimes_b.jpg" rel="lightbox[g202]"><img src="https://cloudfront.crimethinc.com/images/g202/goodtimes_a.jpg" width="500" height="333"></a></p>
<p>All this may still miss the mark. In the midst of an economic crisis, when a great part of the population is struggling just to make ends meet, neither nationwide mobilizations nor local occupations will put food directly on the table. We need to popularize anarchist alternatives that can provide for daily-life survival needs; this is the field in which successful models could be most contagious and transformative. Our success in this sphere will determine what we are capable of in every other context. Perhaps our next mobilization should be decentralized, taking place in every neighborhood around the country, offering people the opportunity to fight for their own lives in an immediate sense.</p>
<p>This is not to say we should hang up our black sweatshirts. They may be useful in that fight as well.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><em>[Dumpster Photo by <a href="http://www.iwasaround.com">Foo</a>.]</em></p>