<p align="center"><a href="https://cloudfront.crimethinc.com/images/ideology/2b.gif" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/ideology/2a.gif" width="500" height="737"></a></p>
<h1 style="margin-bottom: 0px">Do You Have Ideas, <br />
or Do Ideas Have You?</h1>
<p>&nbsp;</p>
<p align="right">&ldquo;The ideologist is a man who falls for the fraud perpetrated on him by his own intellect: that an idea, i.e. the symbol of a momentarily perceived reality,<br />
can possess absolute reality.&rdquo;<br />
&ndash;<em>Socrates, refuting Plato&rsquo;s interpretation of his ideas</em></p>
<p align="right">&ldquo;The world eludes us because it becomes itself again.&rdquo;<br /> 
<em>&ndash;Lewis Carroll</em></p>
<p><em>Editor&rsquo;s introduction: Possibly the best text any of us have written on the subject of ideology is a letter Nadia once sent to a friend in response to an article he had written with her help (her original title for the piece had been &ldquo;The Political Struggle is the Struggle Against the Political,&rdquo; which he changed to &ldquo;Against the Shallowness of the Political&rdquo;)... so here is her letter, reprinted from his private collection. Remember, <strong>whatever you believe imprisons you.</strong></em></p>
<p>&nbsp;</p>
<p align="right"> June 2<br />
Amsterdam (at Chlo&euml;&rsquo;s, with <br />
Phoebe and Heloise)</p>
<p>Dearest E---,</p>
<p> No, you haven&rsquo;t understood what I&rsquo;m talking about at <em>all</em>. In your hurry to purchase for yourself the image of &ldquo;political activist&rdquo; (or, worse, theorist)&mdash;whatever that is&mdash;you&rsquo;ve concluded that <em>everything</em> must be &ldquo;political&rdquo;&mdash;whatever <em>that</em> is! For the farther you expand the meaning of any word, the blurrier it becomes, and the more useless. Once <em>everything</em> is political, then &ldquo;political&rdquo; means nothing all over again, and we have to start from scratch.</p>
<p> So, assuming &ldquo;political&rdquo; isn&rsquo;t just a meaningless all-purpose word... Of course there are &ldquo;political&rdquo; ways to look at every issue, including one&rsquo;s own mortality&mdash;I wasn&rsquo;t trying to deny<em> that</em>. That, in fact, is exactly my point: once you begin to think of yourself as &ldquo;political,&rdquo; once you start to think in terms of analysis and critique&mdash;worse yet to think of yourself as <em>having</em> a critique&mdash;you come to approach <em>everything</em> on those terms, you try to fit<em> everything</em> into your analysis. Being &ldquo;political&rdquo; becomes a cancer that slowly spreads to every corner of your being, until you can&rsquo;t think about anything except in terms of class struggle or gender or whatever.</p>
<p> And there is no analysis, no ideology (because that&rsquo;s what we&rsquo;re talking about here, with your insistence on the politics of living and the theory of politics) broad enough to capture everything that life is. An ideology, just like an image, is always something you have to purchase&mdash;that is, you must give up a part of yourself in return for it. That part of yourself is every aspect of the world, every deliciously complex experience, every irreducible detail that won&rsquo;t fit into the framework you&rsquo;ve so proudly constructed. </p>
<p> Sure, you can look at oral sex and sunsets and love songs and really good Chinese food in terms of political issues, or even approach them in a way that is political in a far less superficial sense&mdash;but the fact is that when you&rsquo;re there in those moments there are things that escape any kind of comprehension, let alone expression, let alone analysis. Living and feeling are simply too complicated to be captured completely by any language, or any combination of languages. Just like that fucking halfwit Plato, the casualty of ideology (which I&rsquo;m begging you not to be) comes to doubt the reality of anything he can&rsquo;t symbolize with language (political or otherwise), because he&rsquo;s forgotten that his symbols are only convenient generalizations to stand in place of the innumerable unique moments that make up the universe.</p>
<p> I can anticipate your response: my critique of the political is itself a political evaluation, a part of my ideology. And so it is. I write to you so vehemently about this because it&rsquo;s an issue I&rsquo;m really struggling with now. I find myself turning <em>everything</em> into a political tract or critique, possessed by (what my ideology describes as!) a capitalistic compulsion to transform all my feelings and experiences into <em>objects</em>&mdash;that is, into theories I can carry around with me. My values have come to revolve around these theories, which I show off as proof of my intelligence and importance, the same way a bourgeois man shows off his car as proof of his worth: my life isn&rsquo;t about my actual experience anymore, it&rsquo;s about &ldquo;the struggle&rdquo;&mdash;when I&rsquo;d wanted that struggle to be about centering my life on my experiences, not some new substitute! I&rsquo;d like to say this letter is my last stand against the all-consuming demands of the political... but that was probably long ago, the last time I was able to reflect on something without the political ramifications even occurring to me. Careful what you wish for, E---, when you say everything is political.</p>
<p> I think part of this pathological need to systematize everything comes from living in cities, incidentally. Every single thing around us here has been made by human beings, and has specific human meanings attached to it&mdash;so when you look around, instead of seeing the actual objects that are around you, you see a forest of symbols. When I was staying in the mountains, it was different. I would go walking and I wouldn&rsquo;t see &ldquo;don&rsquo;t walk&rdquo; signs, I would see trees and flowers, things that have an existence beyond any framework of human meanings and values. Standing under a starry sky, there, gazing at the silent horizon, the world felt so immense and profound that I could only stand before it mute and trembling. No politics could ever provide a vessel deep enough to hold those moments. Not to say there&rsquo;s no reason for us to conceptualize things, E---, because of course that&rsquo;s useful sometimes&hellip; but it&rsquo;s a means, and not the only means, to a much greater end. That&rsquo;s all.</p>
<p> I&rsquo;ll leave you with this, my own poor translation of a line from the farewell letter Mao Tse-tung&rsquo;s mistress wrote him shortly after the so-called success of the Chinese so-called Communist Revolution:</p>
<p><em>&ldquo;It&rsquo;s sadly predictable that the only way you can come up with to celebrate the liberation you feel at leaving the old system behind is by coming up with a &ldquo;system of liberation,&rdquo; as if such a thing could exist&mdash;but that&rsquo;s what we can expect from those who have never known anything other than systems and systematizing, I guess.&rdquo;</em></p>
<p>Yours with love,<br />
Nadia</p>
<h3>&nbsp;</h3>