<p align="center"><a href="http://thecloud.crimethinc.com/images/ideology/1b.jpg" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/ideology/1a.jpg" width="500" height="391"></a></p>
<h1 style="margin-bottom: 0px">Against Ideology?</h1>
<p></p>
<h6 align="right" style="margin-right: 0px"><em>From notes for a panel discussion at the 2010 <a href="http://bfest.gr" target="_blank" >Babylonia festival</a> in Athens, Greece, at which a CrimethInc. agent was invited to speak about &ldquo;The End of Ideology and the Future Events&rdquo;</em></h6>
<p>While religious fundamentalism is still a powerful force, ideology seems to be on the wane as a motor of secular revolutionary activity. The days are long past when groups like the Communist Party could command millions of adherents worldwide. Should anarchists celebrate this decline, positioning ourselves atop the crashing wave of history? Is <em>ideology itself</em> the problem?</p>
<p>But what would it mean to be <em>against</em> ideology? To get to the bottom of this, we have to understand precisely what we mean by the term.</p>
<p>These waters have been muddied by countless Marxists before us. Marx insisted that ideology is determined by who controls the means of production, and functions to blind the proletariat to their own exploitation. But isn&rsquo;t Marxism the ideology par excellence, that has blinded untold millions? And how could class-based relations of production suffice to explain its proliferation throughout the 20th century? If some of Marx&rsquo;s disciples have attempted to update his analyses to keep up with a world that has never borne out his predictions, we should be as suspicious of them as we are of all <em>ideologues</em>.</p>
<p>It&rsquo;s easy to see the pitfalls of ideology when we examine the dogmatism of our enemies. But unless ideology is simply what we call the ideas of those with whom we disagree, we should be able to critique it in ourselves as well.</p>
<h3>But What Is Ideology, Anyway?</h3>
<p>The nature of ideology remains an enigma for contemporary anarchists: we know we&rsquo;re against it, but we can&rsquo;t pin down what it is.</p>
<p>Our own collective has struggled with this for a decade and a half. Early on, in <a href="http://www.crimethinc.com/books/days.html"><em>Days of War, Nights of Love</em></a>, our critique was summarized in slogans such as &ldquo;Do you have ideas, or do ideas have you?&rdquo; In retrospect, that formulation presumed a distinction between oneself and one&rsquo;s ideas, as if there were an essential self that precedes ideological construction. Later, in <a href="http://www.crimethinc.com/books/er.html"><em>Expect Resistance</em></a>, we tried another approach: &ldquo;When we want to rebel against the limits a culture imposes, we call it &lsquo;ideology&rsquo; &hellip;but we cannot escape culture itself&mdash;we carry it with us as we flee.&rdquo; This is more circumspect, but it doesn&rsquo;t indicate how we might resist those limits.</p>
<p>Our colleagues fare little better. Interviewed by <a href="http://voidnetwork.blogspot.com/2010/05/exclusive-interview-of-david-graeber-by.html" target="_blank">Void Network</a> for the newspaper <a href="http://www.babylonia.gr" target="_blank">Babylonia</a>, David Graeber offhandedly defines ideology as &ldquo;the idea that one needs to establish a global analysis before taking action (which inevitably leads to the assumption that an intellectual vanguard must necessarily play a leadership role in any popular political movement).&rdquo; This strikes us as too specific. On the other hand, in his <a href="http://library.nothingness.org/articles/SI/en/display/29" target="_blank"><em>Trait&eacute; de Savoir-Vivre &agrave; l'Usage
des Jeunes G&eacute;n&eacute;rations</em></a>, Raoul Vaneigem numbers &ldquo;individualism, alcoholism, collectivism, activism&rdquo; among the range of possible ideologies. Any definition that encompasses all these is surely too broad.</p>
<p>Resorting to the dictionary, we find that ideology is <em>&ldquo;A system of ideas and ideals, especially one that forms the basis of economic or political theory and policy</em>.&rdquo; By that definition, it appears difficult to outline an anarchist opposition to ideology: if we declare ourselves against systems of ideas and ideals, how can we maintain a critique of hierarchy and oppression? Worse yet, on what ground could we oppose such systems, without subscribing to such a system ourselves?</p>
<p>So let us approach the subject from another direction, broaching possibilities rather than charting territory, in hopes of making progress without devising an<em> ideological</em> blueprint for resisting ideology.</p>
<h3>What Could It Mean to Oppose Ideology?</h3>
<p>If the hallmark of ideology is that it begins from an answer or a conceptual framework and attempts to work backward from there, then one way to resist ideology is to start from questions rather than answers. That is to say&mdash;when we intervene in social conflicts, doing so in order to assert <em>questions</em> rather than conclusions.</p>
<p>What is it that brings together and defines a movement, if not questions? Answers can alienate or stupefy, but questions<em> seduce</em>. Once enamored of a question, people will fight their whole lives to answer it. Questions precede answers and outlast them: every answer only perpetuates the question that begot it.</p>
<p>The term anarchism is itself useful not because it is an answer, but because it is a question&mdash;because it is more effective than other terms (freedom, community, communism) at raising <em>the questions we wish to ask</em>. What does it mean to live without hierarchy, or to struggle against it? This single word offers endless points of departure, endless mysteries.</p>
<p>Perhaps the anarchist struggle is an attempt to enact a concrete program, to reach a forechosen destination&mdash;this is the<em> ideological </em>way of conceiving our project. But perhaps this utopia is<em> unreachable</em>, and its real significance is as a motivating force to enable us to live differently today. If this is the true value of utopian programs, then the less attainable they are the better.</p>
<p>But what else could it mean to resist ideology? Perhaps it means rejecting the Platonic conception of knowledge, in which it refers to some &ldquo;true reality&rdquo; more essential than lived experience. Those who spend a great deal of time studying and constructing theory often mistake their abstractions for real-world phenomena, when in fact they are only generalizations derived from individual experiences. Valuing the irreducible infinity of our own lives over the inert prescriptions of the dead, and knowing better than to believe ourselves infallible, we should frame our ideas as <em>hypotheses</em> rather than universal principles. Hypotheses can be tested, refined, and tested again, on an ongoing basis.</p>
<p>In this light, anarchism itself is only a broad generalization, a hypothesis that life is more fulfilling without hierarchy.</p>
<p>Perhaps resisting ideology means ceasing to regard our ideas as possessing meaning apart from the ways we are able to put them into practice. During peaks of struggle, people tend to focus on practical questions, and theory takes flesh in day-to-day actions; during plateaus of defeat, theory tends to become separate from activity, a specialized sphere unto itself. In a vacuum, the elaboration of theory can become a surrogate activity, compensating for all one is not<em> doing</em>, accustoming one to thinking <em>rather than </em>doing&mdash;as if the two could be disconnected! Thus ideologies become extensions of the egos of those who subscribe to them, who pit them against each other like rivals at a dogfight.</p>
<p>Perhaps resisting ideology means attempting to do without binary distinctions and assessments. Rather than taking positions for or against broad categories&mdash;&ldquo;student organizing,&rdquo; &ldquo;reformism,&rdquo; &ldquo;violence,&rdquo; even &ldquo;ideology&rdquo;&mdash;we could see each of these as composed of conflicting currents and tendencies. In this view, the role of theory is not to endorse or condemn, but to study this nuanced interplay of forces in order to inform strategic action.</p>
<p>Can we imagine resisting ideology in more concrete terms&mdash;for example, when it comes to organizing and outreach? Perhaps it means not positioning ourselves in an ideologically defined camp, but focusing on destabilizing the existing social terrain: creating new connections and circulating subversive energy rather than to attempting to hold territory. Anarchists who take this approach direct their attention out of the anarchist community, approaching people in other communities rather than debating details with those who share a common theoretical language. We certainly can&rsquo;t expect others to leave their comfort zones if we will not leave ours.</p>
<p>A corollary of this is that those in the midst of transformation are the real experts on social change, not career radicals who came to rest in one position decades ago. If this is so, the latter should follow their lead, not the other way around.</p>
<p>And obviously, resisting ideology means reconsidering habitual strategies and tactics, constantly challenging ourselves and our conceptions, not being too enchanted with the sound of our own voices.</p>
<h3>And Instead of Ideology?</h3>
<p>Of course, a complete disavowal of ideology is untenable&mdash;the very idea presupposes some sort of &ldquo;system of ideas and ideals.&rdquo; Ideology is not something we can escape or banish; at best, we can maintain a healthy suspicion of our own.</p>
<p>Pretensions of being completely against or outside ideology can be dangerous, first because they create the illusion that one has no need for such suspicion. Insisting that everyone else is a deluded ideologue is a good indication that you are one yourself, whether you&rsquo;re a hard-line Marxist or a self-proclaimed apolitical nihilist.</p>
<p>Those who profess to reject ideology entirely often end up glorifying certain <em>activities</em> in place of political commitments&mdash;for example, vandalism and violence against authority figures. But divorced from any political program, there is no guarantee that these will have liberating consequences; only those who grew up far from Kosovo and Palestine could conflate all such activity with resistance to hierarchy. Most of those who affect this posture are invested in some kind of political values, whether or not they admit it.</p>
<p>Grandiose rhetoric about the unknown (or &ldquo;destroying the world&rdquo;) notwithstanding, we can only ground resistance to the existent in what we know. If the unknown alone (or pure destruction) were our only objective, how would we know where to start? It is better to admit to the ideas and ideals that shape our decisions.</p>
<p>Ideologies&mdash;or should we say, ideas, ideals, values, meanings&mdash;are socially produced. From the moment of our birth, they construct us and we construct and reconstruct them. This is the inescapable fabric of our existence as social beings. Anarchism proposes that we could participate in this process <em>intentionally</em>, collectively producing value and meaning and thus ourselves. The essence of self-determination is not simply the ability to make choices for oneself, but to <em>make oneself</em> in the process. Winning this power is a much greater undertaking than any single battle that could be fought in the street. </p>
<p>Capitalism appears to perpetuate itself without ideology: it gives the impression that it does not need people to believe in it so long as they have to participate in it to survive. Yet let us not forget that millions of people in the so-called New World and elsewhere chose to fight and die rather than survive on its terms, regardless of the conveniences Western Civilization offered. The &ldquo;material needs&rdquo; that drive this system are still socially produced: one has to have internalized a certain amount of materialism in the capitalist sense to buy into materialism in the Marxist sense.</p>
<p>So perhaps we can frame our project in terms of <em>values</em> rather than ideology. We are not trying to propagate a particular system of ideas so much as to foster anti-authoritarian <em>desires</em>. By starting from what we want rather than what we believe, we can avoid the pitfalls of dogmatism and find common cause with others that transcends theory.</p>
<p>&nbsp;</p>
<h5>&ldquo;I protest against the charge of dogmatism, because, though I am unflinching and definite as to what I <strong>want</strong>, <br />
I am always doubtful about what I know.&rdquo; <br />
&ndash;Errico Malatesta</h5>
<h3>Earlier Reading</h3>
<p><a href="/texts/atoz/ideas.php"><strong>Do You Have Ideas, or Do Ideas Have You?</strong></a><strong><br />
<a href="/texts/atoz/onedimensional.php">One Dimensional Man in the Three Dimensional World</a></strong><a href="http://www.crimethinc.com/texts/atoz/onedimensional.php"></a></p>
<p><br />
</p>
<p align="center"><img src="http://thecloud.crimethinc.com/images/ideology/3a.jpg" width="500" height="375"></a></p>
