<p><a href="https://cloudfront.crimethinc.com/images/insurrect/insur1_b.gif" rel="lightbox[insurrect]"><img src="https://cloudfront.crimethinc.com/images/insurrect/insur1_a.gif" width="500" height="375"></a></p>
<h3>So do we&mdash;a total break with domination and hierarchy in all their forms, involving an armed uprising if need be. Until that&rsquo;s possible, we&rsquo;ll settle for recurring clashes in which to develop our skills, find comrades, and emphasize the gulf between ourselves and our oppressors.<br />
<br />But how do we bring about these confrontations? How do we ensure that they strengthen us more than our enemies? What pitfalls await us on this road? And what <em>else</em> do we have to do to make our efforts effective?</h3>
<p>&nbsp;</p>
<p>
Over the past few years, a <a href="http://en.wikipedia.org/wiki/Insurrectionist_anarchism" target="_blank">small current</a> has gained visibility in US anarchist circles prioritizing the themes of insurrection and social conflict. Like any ideological milieu, it&rsquo;s a lot more diverse than it appears from a distance. Some strains emphasize confrontation for its own sake, rather than as a means of achieving reforms; others frame revolt as a means of building the power of the oppressed outside static organizations. The common thread is that all are critical of formal institutions and focus on attack as their central theme.</p><p>
How effective are these strategies at achieving their professed goals? To answer this question, we can&rsquo;t simply study insurrectionist theory in a vacuum; we have to look at the activities associated with it in the US context. In practice, it&rsquo;s not always easy to tell where strategic considerations leave off and matters of emotional and psychological temperament begin; in this case, both are relevant. Much of what we will discuss below is not so much a matter of what insurrectionists say but of what they do.</p><p>
This subject is of particular interest to us because we are insurrectionists of a sort, whether or not we use that adjective. For well over a decade, we&rsquo;ve focused on confrontational struggle based in individual initiative, informal networks, and ad hoc organization. Starting with <a href="http://www.crimethinc.com/texts/atoz/shoplifting.php" target="_blank">shoplifting</a> and vandalism and working up to <a href="http://www.crimethinc.com/texts/recentfeatures/g20.php" target="_blank">streetfighting</a> and clandestine direct action, we&rsquo;ve learned the advantages and disadvantages of this approach on our own skin. One is always most critical of what is closest to one&rsquo;s heart: most eager to see it succeed, and most concerned about potential errors.</p><p>
In some ways, this is a very old line of thinking&mdash;perhaps older than some of its adherents realize. One genealogy traces its origins to the dispute between <a href="http://en.wikipedia.org/wiki/Marx" target="_blank">Marx</a> and <a href="http://en.wikipedia.org/wiki/Bakunin" target="_blank">Bakunin</a> over the organizational forms of the <a href="http://en.wikipedia.org/wiki/Paris_Commune" target="_blank">Paris Commune</a>. Some insurrectionists see precedents in the <a href="http://en.wikipedia.org/wiki/Propaganda_of_the_deed" target="_blank">propaganda of the deed</a> carried out by Nineteenth-century <a href="http://en.wikipedia.org/wiki/Propaganda_of_the_deed#List_of_assassinated_important_figures_and_other_propaganda_by_the_deed_acts" target="_blank">assassins</a> and the <a href="http://en.wikipedia.org/wiki/Illegalism" target="_blank">illegalism</a> associated with <a href="http://en.wikipedia.org/wiki/Jules_Bonnot" target="_blank">Jules Bonnot</a> and his fellow bank robbers. We can trace the lineage of current insurrectionist theory from <a href="http://en.wikipedia.org/wiki/Errico_Malatesta" target="_blank">Errico Malatesta</a> and <a href="http://en.wikipedia.org/wiki/Luigi_Galleani" target="_blank">Luigi Galleani</a> through the works of <a href="http://www.theanarchistlibrary.org/texts-sorted-author#BonannoAlfredoM" target="_blank">Alfredo Bonanno</a>, <a href="http://www.librarything.com/author/weirjean" target="_blank">Jean Weir</a>, and others who attempted to distill lessons from the social struggles of the 1960s and &rsquo;70s.</p><p>
At the same time, the latest wave of insurrectionist ideas is something of a new phenomenon in the US, where the high turnover rate in most anarchist communities often dooms them to relearn the same lessons over and over. One can hardly blame the new generations for this&mdash;if anything, the older generations are to blame for dropping out or refusing to communicate. Seasoned anarchists have to be especially cautious not to be dismissive and hostile about the enthusiasms of their young comrades. Ten years ago, we were the upstarts whose new energy and muddled ideas provoked all the testy veterans; we were able to learn from some of their criticisms, no thanks to them, but their disdain contributed to our defensiveness and their marginalization. If we accept roles on the opposite side of this dynamic now, we may doom those who come after us to repeat the same pattern.</p><p>
In that spirit, let&rsquo;s start with the advantages of insurrection as a point of departure.</p><p>
</p>
<h3>Starting from Revolt&hellip;</h3>
<p align="right">&ldquo;Attack is the refusal of mediation, pacification, sacrifice, accommodation, and compromise in struggle. It is through acting and learning to act, not propaganda, that we will open the path to insurrection, although analysis and discussion have a role in clarifying how to act. Waiting only teaches waiting; in acting one learns to act.&rdquo;<br />
<em>-<a href="http://www.eco-action.org/dod/no10/anarchy.htm" target="_blank">&ldquo;Insurrectionary Anarchy: Organizing for Attack,&rdquo;</a> in <a href="http://www.eco-action.org/dod/no10/" target="_blank">Do or Die #10</a></em><a href="http://www.eco-action.org/dod/no10/" target="_blank"></a></p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/insurrect/insur2_b.jpg" rel="lightbox[insurrect]"><img src="https://cloudfront.crimethinc.com/images/insurrect/insur2_a.jpg" width="500" height="375" style="margin-bottom: 2px"></a><em><br />The answer is always no.</em></p>
<p>Many organizations and movements, including some that are explicitly anarchist, promise to challenge the powers that be as soon as the groundwork has been prepared; but the world is always changing, and one may lay a foundation only to discover that the terrain has shifted. Once one gets used to waiting, even if it is only a matter of needing to prepare a little more, it is always easier to go on waiting. Revolution, like parenthood and everything else momentous in life, is something one can never be adequately prepared for.</p><p>
Often, this preparation is framed in terms of the need to do more outreach and education. But until there is a clash, until the lines are drawn, there is nothing to talk about. Most people tend to remain aloof from theoretical discussions, but when something is <em>happening</em>, when the stakes are high and they can see concrete differences between opposing sides, they will take a stand. In forcing such ruptures, one can compel those who hide authoritarian and capitalist allegiances to show their true colors, while offering everyone else the opportunity to form <em>other</em> allegiances.</p><p>
Sometimes one has to aim beyond the target in order to strike it. Perhaps in the pacified US, some have to decry all compromise and deliberation to resist co-optation and paralysis. By interrupting the apparent consensus and social peace, confrontations make injustice visible and legitimize the rage others feel as well. When the fog of apparently universal submission is dispelled, those who wish to fight can finally find each other&mdash;and readiness to fight is a better basis for allegiance than merely <em>ideological</em> agreement.</p><p>
The form of one&rsquo;s immediate actions should match one&rsquo;s long-term goals. Theoretical elaborations give rise to more of the same. Focusing on winning reforms tends to contribute to the development of reformist logic. If you want to destroy all forms of domination, it&rsquo;s best to confront them all from the outset.</p>
<h3>&hellip; and Spreading to Resistance</h3>
<p align="right">&ldquo;Insurrectionary anarchism, therefore, places particular importance on the circulation and spread of action, not managed revolt, for no army or police force is able to control the generalised circulation of such autonomous activity . . .<br />What the system is afraid of is not just these acts of sabotage themselves,<br />but also them spreading socially.&rdquo;<br />
<em>-<a href="http://www.eco-action.org/dod/no10/anarchy.htm" target="_blank">ibid.</a></em><a href="http://www.eco-action.org/dod/no10/anarchy.htm" target="_blank"></a></p>
<p align="center" style="line-height: 15px; margin-bottom: 25px"><a href="https://cloudfront.crimethinc.com/images/insurrect/insur3_b.jpg" rel="lightbox[insurrect]"><img src="https://cloudfront.crimethinc.com/images/insurrect/insur3_a.jpg" width="500" height="288" style="margin-bottom: 2px"></a><em><br />Every action that dispels the illusions of order and resignation <br />
is a spell cast for more of the same.</em></p>
<p>Almost all strains of insurrectionist thought emphasize the importance of revolt spreading. This is one of the best standards, then, by which to evaluate insurrectionist efforts.</p><p>
If both postponement and action tend to give rise to more of the same, then in acting oneself, one extends an invitation to others. This is an argument for carrying out actions that others can easily emulate, in hopes that they will catch on.</p><p>
That&rsquo;s the idea, anyway. Sometimes, of course, anarchists carry out an action others could easily emulate, but no one does. What <em>other</em> factors enable an action to inspire more actions?</p>
<h3>Even if the Time Is Not Ripe</h3>
<p align="right">&ldquo;We are insurrectionalist anarchists&hellip; because rather than wait, <br />
we have decided to proceed to action, even if the time is not ripe.&rdquo;<br />
<em>-Alfredo Bonanno, <a href="http://theanarchistlibrary.org/insurrectional-project" target="_blank">The Insurrectional Project</a></em><a href="http://theanarchistlibrary.org/insurrectional-project" target="_blank"></a></p>
<p>It is an article of faith among most insurrectionists that one should not wait for the appropriate material conditions, but should attack immediately. As a defense against the sort of postponement described above, this makes perfect sense; as a moral obligation or an axiom to govern every decision, it can be dangerously counterproductive.</p><p>
Insurrectionist theory allows for this, but in practice insurrectionists do not always make the wisest choices. This is one of the cases in which it can be difficult to differentiate between insurrectionism as a program with concrete goals and insurrectionism as a matter of disposition. To react immediately against oppression without thought for the consequences is beautiful, and perhaps a way to recover one&rsquo;s humanity in a desensitizing world&mdash;but it is not always strategic.</p><p>
This does not stop some from posing it as strategic. People who grew up in a society founded on <a href="/texts/days/nogods.php">Christian notions of moral law</a> often argue for their own preferences as universally valid prescriptions. It&rsquo;s surprising how judgmental people who claim to reject morality can be!</p><p>
So is insurrectionism a religion, or a strategy? If it is a religion, its precepts are timeless and unconditional: categorical imperatives. If, on the other hand, it is a strategy, developed under specific conditions, we should think hard about how those conditions might be different from ours, and how we should adjust it accordingly.</p><p>
When Bonanno originally formulated his analysis in the 1970s, Italy was in the midst of an <a href="http://en.wikipedia.org/wiki/Years_of_lead_(Italy)" target="_blank">upheaval</a> that threatened the entire social order; authoritarian and anti-authoritarian currents intermingled and contended in the course of struggling against the government. He was not making an argument for precipitating clashes where there were none so much as proposing an organizational strategy to ensure that ongoing clashes would promote liberty and autonomy. Contemporary US anarchists reading texts such as <a href="http://theanarchistlibrary.org/armed-joy" target="_blank">Armed Joy</a> do not always understand this, interpreting them instead as a challenge to escalate tactics on a personal basis.</p><p>
Of course, in a society based on competition and exploitation, there are always clashes, however subtle. One doesn&rsquo;t have to precipitate new ones; it is enough to fight where one stands. Unfortunately, the insurrectionist imagination is often limited by the most well-known models for attack. Imagine an insurrectionist who goes to work or school during the week but smashes bank windows on the weekends&mdash;hesitating to create a rupture in the fabric of her own daily life while willingly risking felonies to destroy things outside it. If such a lifestyle could make sense, it is an admission that one must still choose carefully when and how to &ldquo;proceed to action.&rdquo; We&rsquo;re not convinced it does make sense, but that doesn&rsquo;t mean the insurrectionist in question would be better off immediately smashing the windows in her own workplace.</p><p>
If &ldquo;proceeding to action even if the time is not ripe&rdquo; doesn&rsquo;t mean picking up the closest heavy object and attacking the nearest person in a uniform, what does it mean? How do we decide what kinds of action are most worthwhile?</p>
<p>&nbsp;</p>
<p align="right" style="color: #600">On Mayday, several dozen masked hoodlums rampage through an upscale shopping district in downtown San Francisco, smashing windows and setting off fireworks. Afterwards <a href="http://www.indybay.org/newsitems/2009/05/03/18592657.php" target="_blank">an anonymous statement on Indymedia</a> reads, in part:</p>
<p align="right" style="color: #600; margin-right: 30px; margin-left:30px">&ldquo;De Beers, Prada, Coach, Tumi, Wells Fargo, Longchamp, Macy's, Armani, Crate and Barrel, Montblanc, Urban Outfitters and Guess were all targeted for all kinds of boring ass political shit, but primarily because fuck them. Exploitation is the norm of economic activity, not the exception. We see no need to reveal our laundry list of grievances and solidarity.&rdquo;</p>
<p align="right" style="color: #600; margin-left: 15px">Much has changed since <a href="http://theanarchistlibrary.org/n30-black-bloc-communiqu&eacute;" target="_blank">the communiqu&eacute; from the ACME collective</a> following the <a href="http://www.crimethinc.com/texts/pastfeatures/blocs.php" target="_blank">black bloc</a> at the <a href="http://www.crimethinc.com/blog/2006/11/30/seattle-seven-years-later/" target="_blank">WTO protests in Seattle</a>. In 1999, the ACME statement was widely read and debated, influencing the politics of a new generation that saw more sense in opposing corporate power with crowbars than with signs or lockboxes. A decade later, black-clad anarchists are miraculously still finding ways to smash windows, despite ever-increasing surveillance and repression&mdash;but the communiqu&eacute;, if not the action itself, seems to be directed only to those who understand and approve of the tactic.</p>
<p>
</p>
<p>&nbsp;</p>
<h3>Against Subculture</h3>
<p align="right">&ldquo;Particularly to be avoided are the cultural and activist circles&hellip; <br />
All milieus are counter-revolutionary because they are only <br />
concerned with the preservation of their sad comfort.&rdquo;<br />
<em>-<a href="http://tarnac9.wordpress.com/texts/the-coming-insurrection/" target="_blank">The Coming Insurrection</a></em><a href="http://tarnac9.wordpress.com/texts/the-coming-insurrection/" target="_blank"></a></p>
<p>Historically, insurrectionist anarchism has centered around a rejection of static organizational structures. In the US, where long-standing anarchist organizations are not particularly common or powerful, it has recently come to be framed more as a reaction against <em>cultural</em> factors. Some insurrectionists conceptualize their position as a break with what they consider to be hopelessly passive and assimilated anarchist subcultures&mdash;bicycling as an end in itself, potlucks that never end in streetfighting, and so on. Some take this further, dismissing the very idea that subculture could have any radical potential.</p><p>
What does it mean to dismiss subculture? Culture is as ubiquitous among human beings as language; you can challenge it, you can even destroy it, but you generate new culture in the process. In general, this dismissal does not seem to proceed from some mystical doctrine that we could escape culture per se, the way that <a href="http://en.wikipedia.org/wiki/John_Zerzan" target="_blank">John Zerzan</a> preached a primitivist utopia without language, but rather from a reaction to the subcultural identifications of the preceding generation of anarchists. As explored in <a href="/rt/">Rolling Thunder #8</a>, by the time today&rsquo;s young anarchists came of age, the punk scene that sired so many of their predecessors had come to be dominated by reactionary elements. Faced with this, rejecting <em>one</em> subculture was not enough&mdash;why not reject subculture<em> itself?</em></p><p>
Young insurrectionists are not the first to attempt this: one can find similar rhetoric in books like <a href="/books/days.html"><em>Days of War, Nights of Love</em></a>. Before an idea wins many proponents, it&rsquo;s easy to declare that it transcends subculture, as it is not incarnated in any particular social context. Once it gains adherents, however, things get more complicated. In all likelihood, the proponents will share subcultural reference points&mdash;how else would they have encountered the idea?&mdash;and failing this, they are bound to create common points of reference in the course of attempting to put the idea into practice. Culture is simply a matter of points of reference, and the more obscure they are, the more &ldquo;subcultural&rdquo;&mdash;in this regard, ideological insurrectionism is a significantly <em>more</em> subcultural current than, say, the <a href="http://en.wikipedia.org/wiki/Straight_edge" target="_blank">vegan straightedge</a> scene.</p><p>
Actual insurrections can transcend subcultural boundaries in ways that theories do not, of course; likewise, cross-cultural spaces can sometimes create fertile ground for uprisings. There&rsquo;s a lot to be said for <a href="http://news.infoshop.org/article.php?story=20060610134717980" target="_blank">forging bonds between different communities in struggle</a>, demonstrating that resistance is not the sole province of any one demographic. Were it not for the homogeneity of most insurrectionist circles, it would be possible to read this criticism of subculture as an argument for cross-cultural spaces, rather than as an underhanded way to promote yet another new subculture. There is no such thing as a zone free of cultural identifiers&mdash;efforts to stay free of cultural limitations must begin by integrating multiple cultural contexts rather than pretending to be outside all of them.</p><p>
Perhaps, like the authors of the aforementioned <em>Days of War</em>, some people have to espouse a grandiose opposition to culture itself just to feel entitled to get something new off the ground. But eventually, when that new something has gotten going and become subculturally identified, they will need a critique that acknowledges this&mdash;otherwise, they are bound to be quarantined and neutralized like their predecessors. Those who think they can discount culture entirely are trying to throw out the baby with the bathwater&mdash;an especially difficult project when<em> you&rsquo;re</em> the baby.</p><p>
This dispute about culture parallels the much older dispute between insurrectionists and anarchists who believe in building long-term institutions. <a href="http://www.anarkismo.net/article/3430" target="_blank">The latter argue</a> that insurrectionist criticism of institutions is founded on the notion that formal structures are inescapably hierarchical, but counter that this analysis provides insurrectionists with no tools to challenge the subtle hierarchies that develop in informal networks. Decrying authoritarian tendencies and cultural complacency in competing ideological milieus is no proof against falling prey to them oneself.</p><p>
So, are all subcultures &ldquo;only concerned with the preservation of their sad comfort&rdquo;? Perhaps this is simply a matter of semantics, of calling social circles that are only concerned with preserving their comfort &ldquo;milieus.&rdquo; Is there a positive role that subculture could play in fomenting insurrections?</p><p>
Let&rsquo;s return to the question of how action proliferates. As pointed out above, simply doing things that &ldquo;anyone else can do&rdquo; is not itself enough to spread resistance. The premise of this approach is that others who share similar frustrations will see the actions and understand the strategy embodied in them, and that this alone will move them to action. But this takes for granted that the actions will be visible and the strategy comprehensible across cultural lines; it also disregards the ways that desire is determined by culture as well as class.</p><p>
Many of the assassins who killed presidents and tsars over a century ago passionately believed that these actions would inspire the oppressed to rise up. Clandestine &ldquo;armed struggle&rdquo; groups have sometimes used the same logic. One common insurrectionist critique of these groups is that their actions are too specialized; but this does not explain why more easily reproducible tactics often fail to catch on. Another critique of armed groups is that <a href="http://www.revoltagainstplenty.com/index.php/archive/16-archive-global/58-os-cangaceiros" target="_blank">they separate themselves from others so energy and ideas cease to flow</a>; this seems more to the point. One could argue that the circulation of insurgent desires and values&mdash;essentially a cultural phenomenon&mdash;is as indispensable for the proliferation of revolt as gasoline is to a Molotov cocktail.</p><p>
For example, over the past few years, North American anarchists have carried out clandestine attacks on ATMs, bank windows, and other targets; this is currently one of the best-known templates for insurrectionist activity. Such nighttime attacks don&rsquo;t seem to have spread widely outside the anarchist subculture in most of the cities in which they have occurred, but they <em>have</em> given rise to copycat actions in other <em>anarchist </em>communities. This indicates the importance of a common cultural context&mdash;shared values, points of reference, and venues for communication. Acting sincerely can be contagious, but our actions are always modeled on the examples we know and driven by the values fostered by our communities.</p><p>
People seem to be most likely to join revolts when doing so can help them meet their needs. But needs themselves are socially produced: nobody needed cell phones to maintain contact with their friends until a decade ago, for example, and countless indigenous communities chose resistance over all sorts of amenities until their lifeways were destroyed. The existing power structure is generally at least as capable as radicals are of offering opportunities to meet the needs it produces, whether through individual competition or institutional reforms. A real counterculture fosters needs that capitalism and democracy can never accommodate, such as the desire for human dignity.</p><p>
Efforts to spread resistance must take this into account. Over the past half century, insurrectionists overseas have frequently been subculturally identified&mdash;for example, the Italian insurrectionist milieu of the 1980s and &rsquo;90s was based in a network of autonomous social centers. In criticizing long-term infrastructural projects and countercultural milieus, some US insurrectionists reveal that they are unaware of the context behind the overseas rioting that inspires them.</p><p>
In response to the extravagant notion that we should jettison culture as a site for mobilizing resistance, we counterpose the project of building a <em>culture of resistance</em>, a space in which people of multiple cultural backgrounds can develop common reference points in order to attack hierarchy in all its forms.</p>
<h3>Against Anarchist Identity</h3>
<p>A variant on the rejection of subculture is the rejection of anarchism as an identity. This calls to mind another old question: should we organize specifically as anarchists, or are other approaches more likely to produce anarchy?</p><p>
There is a lot to be said for resisting quarantine in closed circuits of the converted. Picture a molecule that bonds with other molecules by sharing electrons with them. If it has loose electrons, it is prone to creating new connections or disruptions; on the other hand, if all of its electrons are in stable bonds, it is unlikely to introduce new dynamics to the molecules around it. Similarly, anarchists who seclude themselves in the company of committed ideologues tend to become static and predictable, while those who limit their participation in explicitly anarchist circles to stay open to other relationships can sometimes catalyze waves of transformation.</p><p>
At the same time, organizing on the basis of a social rather than ideological position&mdash;for example, as queer youth, as a neighborhood, or as working class people who like to break things&mdash;can be extremely challenging. Anyone who has worked in coalitions knows how hard it can be to accomplish anything in the face of massive internal differences in goals and values. This is true even without centralized decision-making&mdash;think of the instances when <a href="http://news.infoshop.org/article.php?story=20090604211215180" target="_blank">presumed comrades have pulled newspaper boxes back onto the sidewalk</a> during street confrontations. Perhaps the best approach is to organize at some intersection of social position and ideology: for example, a gang who grew up together discovers anticapitalist resistance, and sets out to introduce the possibility to other gangs.</p><p>
Often the ones at the forefront of clashes with the authorities are not self-identifying anarchists at all, while anarchists with carefully articulated political positions avoid conflict or even sabotage resistance. People adopt political stances for all sorts of reasons, and these stances frequently have nothing to do with how they actually conduct themselves. This phenomenon corroborates insurrectionist skepticism about the importance of ideological positions, but it also means that those who identify as insurrectionists are no more likely to practice what they preach than anyone else.</p><p>
Despite the fact that avowed anarchism does not always correlate with active resistance, there&rsquo;s no reason to believe struggles that are not identified as anarchist are any <em>more</em> likely to produce anarchic situations or relationships. If you&rsquo;re opposed to all forms of oppression, you may as well say so from the outset, lest you leave an opening for authoritarians to hijack your efforts.</p>
<h3>Not Just Insurrection, but <em>Anarchist</em> Insurrection</h3>
<p align="right">&ldquo;&lsquo;Armed struggle&rsquo; is a strategy that could be put at the service of <em>any</em> project.&rdquo;<br />
<em>-<a href="http://www.theanarchistlibrary.org/daggers-drawn-existent-its-defenders-and-its-false-critics" target="_blank">At Daggers Drawn</a></em><a href="http://www.theanarchistlibrary.org/daggers-drawn-existent-its-defenders-and-its-false-critics" target="_blank"></a></p>
<p align="center" style="line-height: 15px; margin-bottom: 25px"><a href="https://cloudfront.crimethinc.com/images/insurrect/insur4_b.jpg" rel="lightbox[insurrect]"><img src="https://cloudfront.crimethinc.com/images/insurrect/insur4_a.jpg" width="500" height="244" style="margin-bottom: 2px"></a><em><br />Fans of the LA Lakers celebrate a sports victory.</em></p>
<p>In the US, where militant political conflict is rare, it&rsquo;s tempting to assume that clashes with authority are inherently antiauthoritarian. Insurrectionist websites and magazines appropriate images from a wide variety of contexts; <a href="http://socialrupture.blogspot.com/" target="_blank">some</a> hail all sorts of antisocial crime as manifestations of social war, without knowing the motivations of the protagonists.<a class="footnote" href="javascript:void(0);" onclick="return overlib('Assuming common cause with others of unknown political commitments on the basis of their apparently subversive actions is risky on multiple levels. The Situationists used the Watts riots to argue that their ideas were &ldquo;already in everyone&rsquo;s heads&rdquo; at best, that was a stretch, and at worst a way to claim the right to speak for those who could only speak on their own behalf through action. We can celebrate rebellious actions from outside our communities, but meaningful alliances demand actual relationships.', CAPTION, '[1]');" onmouseout="nd();">[1]</a></p><p>
But rebellion and street violence are not necessarily anarchist. Resistance to oppressors is praiseworthy in itself, but much resistance takes place in support of other authoritarian powers. This is all too familiar in other parts of the world, where illegal violence on the part of fascists, paramilitaries, gangs, drug cartels, mafias, and authoritarian revolutionary movements is an essential aspect of domination. Aspiring authoritarians often take the lead in attacking reigning authorities precisely in order to absorb and co-opt popular unrest. Rioting per se is not always liberating&mdash;<a href="http://en.wikipedia.org/wiki/Kristallnacht" target="_blank">Kristallnacht</a> was a riot too. Even if some participants have the purest intentions, insurrections can go any number of directions: remember what happened to the Russians following the insurrection of 1917, or the Iranians following the insurrection of <a href="http://en.wikipedia.org/wiki/Iranian_Revolution" target="_blank">1978-79</a>.</p><p>
So anarchists must not only provoke confrontations, but also ensure that they contribute to a more horizontal and decentralized distribution of power. In this regard, glorifications of the superficial details of militant confrontation&mdash;black masks, Molotov cocktails, and so on&mdash;are largely beside the point, if not actively distracting. The flow of initiative among the rebels, the ways decisions are made and skills are shared, the bonds that develop between comrades: these are much more important. Likewise, one must strategize as to how social uprisings will contribute to long-term revolutionary momentum rather than simply enabling reactionary forces to consolidate power.</p>
<h3>Against Activism</h3>
<p>A great deal has been said <a href="http://theanarchistlibrary.org/give-activism" target="_blank">against activism</a>: it is a specialized role that frames social change as the domain of experts; it is predicated on dialogue with the powers that be; it promotes inauthenticity and limits the scope of change. A lot of this is mere semantics&mdash;many people who do not deserve such accusations see themselves as activists. Some of it is projected class resentment: those who have time to mess around in everyone else&rsquo;s business, &ldquo;changing the world&rdquo; rather than solving the problems of individualized survival, must have privileged access to resources, as the right wing has always alleged.</p><p>
It&rsquo;s not easy to distill the kernel of truth in this flood of vitriol, but one thing is certain: activism that does not explicitly challenge hierarchy fortifies it. Reformist struggles can win adjustments in the details of oppression, but they ultimately help the state maintain its legitimacy in the public eye&mdash;not only by giving it the chance to redress grievances, but by reinforcing the notion that the power to effect meaningful change lies in the hands of the authorities. It is better to struggle in such a way that people develop an awareness of their own capabilities outside all petitioning and bureaucracy. Reformist activism also tends to build up internal hierarchies: as if by chance, the best negotiators and media liaisons often turn out to be college-educated white people with good skin and conciliatory tones. Of course, certain insurrectionist practices may simply build up hierarchies according to different criteria.</p>
<h3>Sustaining Confrontations</h3>
<h5>Unless it provides for the practical needs <br />
of the participants, insurrectionism is just <br />
an expensive hobby: activism with felony <br />
charges and a smaller base of support.</h5>
<p>The other lesson we can derive from a close study of activism is the importance of not overextending. Some activities produce more energy and resources than they consume; others cost more than they produce. Many activist projects ultimately founder because they fail to recoup the resources invested in them: one cannot carry on an exhausting undertaking indefinitely without deriving the wherewithal for it from somewhere. Of course, these resources can take a wide variety of forms: a <a href="http://www.booksthroughbars.org/pbp/" target="_blank">Books to Prisoners</a> group may consume a great deal of labor hours, but persist so long as the social connections it provides are rewarding; traveling around the country to participate in riots may be expensive in terms of gas and bail money, but if it is exciting and empowering enough, the participants will come up with the cash somehow. On the other hand, if a million dollars must be raised for court costs following every demonstration, this may prove prohibitive, unless each demonstration wins new allies with deep pockets.</p><p>
Activities that cost more resources than they produce are not necessarily bad, but you have to strategize accordingly if you wish to participate in them. Ironically, despite insurrectionist hostility to activism, strategies that focus on confrontation are often at least as costly in this regard as traditional activist organizing. In dismissing goal-oriented struggles in favor of confrontation for its own sake, some US insurrectionists set themselves up for burnout. Symbolic clashes can help develop the capacity to fight for more concrete objectives, but not if they are so costly that they drain their social base out of existence. Breaking windows is a dead end unless it helps to generate a widespread social movement<a class="footnote" href="javascript:void(0);" onclick="return overlib('&ldquo;It is better to loot than to shoplift, to ambush than to snipe, to walk out than to phone in a bomb threat, to strike than to call in sick, to riot than to vandalize . . . Increasingly collective and coordinated acts against this world of coercion and isolation aren&rsquo;t solely a matter of effectivity, but equally a matter of sociality&mdash;of community and fun.&rdquo; -<em>War on Misery #3</em>', CAPTION, '[2]');" onmouseout="nd();">[2]</a>&mdash;or at least provides access to enough of the commodities behind the windows to fund the vandals&rsquo; eventual court cases.</p><p>
The most sustainable forms of confrontation seize resources which can then be employed in further struggle. The classic example of this is the <a href="http://en.wikipedia.org/wiki/Squatting#Europe" target="_blank">European squatting movement</a> of thirty years ago, in which the occupied buildings were used as staging areas for further social struggles. This approach supersedes both self-defeating reformist activism and self-destructive insurrectionist dogma. Unless it provides for the practical needs of the participants, insurrectionism is just an expensive hobby: activism with felony charges and a smaller base of support. Insurrectionists of other eras have recognized this and robbed banks rather than simply smashing their windows.</p><p>
Revenge is itself a need, but it is hardly the <em>only</em> need. People who face enough challenges just getting by will not be much more attracted to gratuitous vandalism than they are to activism that has nothing to do with their daily lives; on the other hand, tactics that enable them to sustain themselves may be more appealing. Insurrectionists who are frustrated with the lifestyle-oriented anarchism of those they perceive as &ldquo;subcultural&rdquo; actually stand to learn a lot from them. The latter remain involved in their version of anarchist community not because of moral or ideological imperatives, but because it sustains them. For insurrection to spread, it must do the same.</p>
<h3>Making a Virtue of Repression</h3>
<p>In the US, militant struggle means taking on the most powerful state in the history of the world. It demands a strategy that takes into account the repression, legal support, and prison sentences that will inevitably result, and somehow turns them to our advantage. The absence of such a strategy is perhaps the most significant structural flaw in insurrectionist projects today. We have to engage with the issue of repression beyond the usual security culture, limited prisoner support, occasional solidarity actions, and wishful thinking. &ldquo;Don&rsquo;t get caught&rdquo; isn&rsquo;t a plan, it&rsquo;s a prayer.</p><p>
It&rsquo;s embarrassing to acknowledge, but the activists who practiced non-violent civil disobedience in the US during the 1980s and &rsquo;90s were miles ahead in this regard, integrating their arrests, court cases, and prison sentences into their campaigns as strategic moves. Their approach was predicated on privilege and glorified victimhood in the most noxious ways, but perhaps we can still learn something from them in order to make the most of repression and ongoing prisoner support in our own struggle.</p><p>
The current case of the <a href="http://rnc8.org/" target="_blank">RNC 8</a>, in which anarchists have been targeted with conspiracy charges for organizing actions against the <a href="/texts/recentfeatures/rncdnc.php">2008 Republican National Convention</a>, may offer one starting point. The defendants have used their case to delegitimize the government and win allies in other communities; as of this writing, they seem to have the prosecutors on the defensive, as the terrorism charges against them have just been dropped and the case is widely acknowledged to be an embarrassment. If they had simply been anonymous vandals, rather than highly visible organizers, this might not have been possible.</p>
<h3>Is It Safer in the Shadows, or in the Spotlight?</h3>
<p align="right">&ldquo;No leaders to round up, no hierarchical organisation to wield power over us in our name, no membership lists to investigate, no manifestos to denounce, no mediators to meet (and then join) the power-holding elite. No public claims are made, no symbolic lines are drawn, no press statements to be deliberately misconstrued and trivialised by journalists. No platforms or programmes which the intellectuals can hijack as their exclusive property, no flag or banner to which to pledge a crass and sectarian allegiance.&rdquo;<br />
<em>-<a href="http://www.eco-action.org/dod/no10/anarchy.htm" target="_blank">&ldquo;Insurrectionary Anarchy: Organizing for Attack&rdquo;</a></em><a href="http://www.eco-action.org/dod/no10/anarchy.htm" target="_blank"></a></p>
<p>No membership, no statements, no public face. This might make it harder for the state to single out enemies, but it also sounds a little like the invisibility and isolation that make it so hard for comrades to find each other and get started.</p><p>
In the current atmosphere of repression, the insurrectionist approach is often framed as a question of security: with infiltrators everywhere and the legal repercussions of resistance intensifying, it is simply too dangerous to engage in visible organizing. However, it&rsquo;s far from certain that less visibility is any more likely to make anarchists safer or more effective.</p><p>
It often happens that in attempting to correct old errors, people commit new ones; forsaking problematic strategies, they learn the hard way what advantages led their predecessors to adopt them in the first place. So it is that anarchists, who only came into the public eye a decade ago, are now fantasizing about returning to the shadows.</p><p>
The government would like nothing better than for anarchists to retreat to private scenes and cliques, leaving few opportunities for unconnected individuals to get involved. It is to the authorities&rsquo; advantage for small numbers of radicals to escalate to more militant tactics while losing connection to a broader social base; this makes direct action less likely to spread, while rendering it easier to justify repression. It might be harder to track down clandestine groups at first, but recent FBI investigations, such as <a href="http://www.crimethinc.com/texts/recentfeatures/greenscared.php" target="_blank">Operation Backfire</a>,<a class="footnote" href="javascript:void(0);" onclick="return overlib('It&rsquo;s worth noting that the only Operation Backfire defendants who conducted themselves honorably were the ones who were still involved in activist organizing or subcultural communities.', CAPTION, '[3]');" onmouseout="nd();">[3]</a> show that closed, high-security structures are not impenetrable. One can also look at the case of the <a href="http://tarnac9.wordpress.com/" target="_blank">Tarnac Nine</a>, French radicals who are currently being charged with terrorist conspiracy; they are also alleged to be involved in authoring the book <a href="http://tarnac9.wordpress.com/texts/the-coming-insurrection/" target="_blank"><em>The Coming Insurrection</em></a>, which champions &ldquo;zones of opacity&rdquo; impenetrable to the authorities. In fact, such zones do not result only from proper control of information, but also from the appearance of so many insurgent groups that the authorities cannot keep up with all of them at once.</p><p>
If this is true, the most pressing task for anarchists is not to carry out secretive military strikes but to spread skills and practices. There is no substitute for participatory activities that offer points of entry for new people and opportunities for existing groups to connect. Likewise, refusing to interact with the public effectively means leaving it to the corporate media to tell one&rsquo;s story&mdash;or else suppress it. Just as insurrectionists must tie the escalation of conflict to the pace at which it spreads so as not to overextend themselves, they must also balance the practical advantages of secrecy against the necessity of circulating new formats and rebellious energy.</p><p>
This also has a bearing on whether it is safer and more strategic for anarchists to act alone with the element of surprise, outside any conventional &ldquo;political&rdquo; framework, or to participate in broader campaigns and mobilizations. In the latter context, the state is often more prepared and vigilant, rendering successful attacks more difficult from a purely military point of view; on the other hand, arrestees are more likely to receive support from outside the immediate anarchist community, and their actions may be more visible and comprehensible to others.</p><p>
All this is not to say that anarchist organizing should be visible in the same way conventional political campaigns are. The point is to ensure that anarchist<em> models</em> of resistance are accessible to everyone, not to promote the popularity of a platform or spokesperson or party. The chief dangers of visibility are not posed by the police, after all, but by the possibility of being absorbed into the spectacle, performing for the cameras until one comes to mistake representations for reality.</p>
<p align="center" style="line-height: 15px; margin-bottom: 25px"><a href="https://cloudfront.crimethinc.com/images/insurrect/insur5_b.jpg" rel="lightbox[insurrect]"><img src="https://cloudfront.crimethinc.com/images/insurrect/insur5_a.jpg" width="500" height="332" style="margin-bottom: 2px"></a><em><br />No less dangerous than the police is the tendency to internalize <br />
the logic of spectacle, performing for the cameras <br />
until one comes to mistake representations for reality.</em></p>
<p>
</p>
<p align="right" style="color: #600">The economy has just crashed, and the anarchists who have spent the preceding half decade building up various anticapitalist infrastructures are eager to assert themselves and their alternative in the public eye. Some friends have been tossing around the idea of a street party, and two dozen people meet to discuss it. The street party becomes A Funeral for Capitalism, intended to initiate a public dialogue on how to mobilize a grass-roots response to the crisis. Handbills and stickers appear everywhere; in planning meetings, the organizers picture themselves at the helm of a crowd of hundreds, tying together public merriment and resource distribution in a two-pronged assault.</p>
<p align="right" style="color: #600"> But the night of the street party is unseasonably cold, and only fifty diehards show up, finding themselves nearly the only pedestrians on the street. They barely make it one block before a lone police officer pulls over and charges into the crowd, seizing someone at random in hopes of setting an example to scare the others onto the sidewalk. To his surprise, he meets a rain of blows. These are not the hesitant activists of the previous generation, but a fiercer new breed.</p>
<p align="right" style="color: #600"> His intended victim escapes; he snatches another, but the same struggle ensues. Backup has arrived by now, and eventually the police manage to capture a single partygoer.</p>
<p align="right" style="color: #600">The rest regroup at a nearby caf&eacute;. Almost everyone who was in the street is present; there is a new sense of common cause. Within a couple hours, they have raised enough money to bond the arrestee out of jail; a couple weeks later, a benefit show featuring a puppet show and a bake sale draws more participants than the street party did and raises all the funds necessary for legal fees.</p>
<p align="right" style="color: #600"> Eventually the defendant negotiates a favorable plea bargain. Just as the bond money comes back, a comrade in another community is arrested on conspiracy charges, and the idea arises to donate the money to his support fund: so in coming into conflict with the authorities, the community has actually become more capable of extending solidarity to other communities.</p>
<p align="right" style="color: #600">Yet amidst all the hubbub, everyone has forgotten about engaging with the public at large, as the issue shifted imperceptibly from the economic crisis to the injustice of police repression. Bonds are tighter among the radicals, thanks to puppetry and baking no less than street bravado, but no tighter with the rest of the city.</p><p>
</p>
<h3>The Force of Insurrection</h3>
<p align="right">&ldquo;The force of an insurrection is social, not military. Generalised rebellion<br />is not measured by the armed clash but by the extent to which the economy<br />is paralysed, the places of production and distribution taken over,<br />the free giving that burns all calculation . . .&rdquo;<br />
<em>    -<a href="http://www.theanarchistlibrary.org/daggers-drawn-existent-its-defenders-and-its-false-critics" target="_blank">At Daggers Drawn</a></em></p>
<p>The force of an insurrection is social, not military. The power of<em> anarchist</em> insurrection is determined not by military confrontations, but by how pervasive resistance is, how widely distributed tactics and resources are, how durable and extensive and genuinely liberating the relationships are that underpin the whole endeavor. If our goal is not simply to persuade others&mdash;or, let&rsquo;s be honest, <em>ourselves</em>&mdash;of our defiance, then we have to prioritize forms of resistance that are either highly contagious or at least sustainable. Who is the social body that is to rise up? Whence is it to come?</p><p>
The force of insurrection is social, not military. This has long been an established tenet of insurrectionists, but in practice it is one of the most frequently forgotten. In focusing on attack, it is difficult not to end up unconsciously adopting the military logic of one&rsquo;s enemies, gauging effectiveness by the numbers of targets struck or the number of dollars&rsquo; worth of damage. Perhaps this is an inevitable risk of conceptualizing attack not as a means but an end&mdash;if <em>attack</em> is valuable in itself, then isn&rsquo;t a &ldquo;bigger&rdquo; attack better? This tendency is particularly dangerous for those who didn&rsquo;t grow up with an example in their communities of what it looks like to wage &ldquo;social war,&rdquo; who must invent their models for it from scratch.</p><p>
The force of insurrection is social, not military. That means it depends on the strength, solidarity, and relationships of an entire social body&mdash;not just an affinity group or crew. Those who bake cupcakes for fundraisers are at least as important as the arrested rioters; the effectiveness of the fundraisers determines how much force insurgents can continue to wield in the streets. One can break a window with a single brick and the muscles of one&rsquo;s arm, but one can only participate in a long-running <em>social</em> conflict as part of a community. Social force is absolutely a matter of culture, values, allegiances, priorities; social war takes place on this terrain, which is influenced by but distinct from the physical terrain of actual confrontations. How many people will support you in a conflict? How many will join in themselves? If you go to prison, will your grandmother support you? Will her community?</p><p>
The state often isolates rebels by means of <a href="http://theanarchistlibrary.org/insurrection-vs-organization" target="_blank">a classic martial arts move</a>: it pushes them in the direction they were already headed, provoking them into a showdown before they have built up the social force they need to survive it. It is essential to set the pace of escalation oneself, avoiding unfavorable engagements and resisting the temptation to focus on revenge. The ultimate target of insurrectionist attack is not just the state, but also the passivity of one&rsquo;s peers.</p><p>
To return to our starting point, none of this is a reason<em> not</em> to act, or to wait for the proper moment to assume hostilities. Social war, like class war, is always taking place: like it or not, we are born into it, and decide at every moment how we fight. The point is to act strategically, so as not to fight alone.</p><p>
This is especially complicated in today&rsquo;s context of surveillance and repression. One must engage in a certain degree of clandestinity to be capable of meaningful resistance at all. But if the most important aspect of resistance is the relationships that result, it is a mistake to choose forms of struggle that tend to produce smaller and smaller social bodies. Historically, except when resistance is spreading like wildfire, resistance movements tend to break down into smaller and smaller elements once they come into open conflict with the state: think of the transition from <a href="http://en.wikipedia.org/wiki/Students_for_a_Democratic_Society_(1960_organization)" target="_blank">Students for a Democratic Society</a> in the 1960s to the <a href="http://en.wikipedia.org/wiki/Weather_underground" target="_blank">Weather Underground</a> in the 1970s, or the trajectory of the <a href="http://thing.desk.nl/bilwet/Cracking/contents.html" target="_blank">Dutch squatting movement</a> over the course of the 1980s. If our social forms may become smaller as conflict intensifies, it might be more sensible to maintain low-intensity warfare that does not provoke the full wrath of the state, or else to start with the crowd as the unit of resistance rather than the crew or affinity group. This is not to say that we should not be organized in affinity groups, but that affinity group action should be a means of catalyzing crowd activity rather than an end in itself.</p><p>
The authorities understand themselves to be engaged in social war, perhaps more clearly than most insurrectionists do. They do not simply attack our bodies with batons, pepper spray, and imprisonment; they also set out to attack our relationships and social connections. It is significantly more cost-effective for them to intimidate, isolate, or discredit radicals than to imprison or kill them. In confrontations, we should recognize this intimidation and isolation as their top priority, and defend our relationships and our connections to others accordingly. They can beat or jail us as individuals without winning the social conflict&mdash;the question is whether our values and tactics take hold.</p>
<p>&nbsp;</p>
<h5>The authorities understand themselves to be <br />
engaged in social war, perhaps more clearly <br />
than most insurrectionists do. They do not <br />
simply attack our bodies with batons,<br />
pepper spray, and imprisonment; <br />
they also set out to attack our<br />
relationships and social connections.</h5>
<p>
</p>
<h3>Social War Requires Social Skills</h3>
<p align="right">&ldquo;Property destruction is not merely macho rabble-rousing or<br />
testosterone-laden angst release. Nor is it displaced and reactionary anger.<br />
It is strategically and specifically targeted direct action.&rdquo;<br />
<em>-<a href="http://theanarchistlibrary.org/n30-black-bloc-communiqu&eacute;" target="_blank">ACME Collective, N30 Black Bloc Communiqu&eacute;</a></em><a href="http://theanarchistlibrary.org/n30-black-bloc-communiqu&eacute;" target="_blank"></a></p><p>
</p><p>
Considering that insurrection depends on relationships, one would think that insurrectionists would be the most personable anarchists, the most eager to make friends and resolve conflicts. Ideally, insurrectionists would offer a welcome contrast to strident pacifists and domineering reformists. It should always be clear that militant action is not a macho performance but a well-reasoned strategic decision, or at least an honest emotional expression.</p><p>
It requires tremendous patience and social skills to lay the preconditions for insurrection. Unfortunately, some who gravitate to insurrectionist ideas have a predisposition for impatience and hostility. &ldquo;Starting from attack&rdquo; can be attractive to those who don&rsquo;t want to have to talk through disagreements or be accountable. In glorifying their preferred tactics over those of their potential allies, such hotheads spread false dichotomies that cut them off from the resources and support they need to make their attacks effective, sustainable, and contagious.</p><p>
One could view this tendency as an overreaction to <a href="http://www.crimethinc.com/texts/recentfeatures/whattoexpect.php#historical" target="_blank">the ponderous coalitions of the antiwar movement</a>. There is nothing good about enforced unity that paralyzes the participants and discourages autonomous action. But a knee-jerk rejection of everything that has made resistance movements possible in the past has little to recommend it, either.</p>
<p>&nbsp;</p>
<p style="margin-left: 25px"><strong>Social Skills for Social War:  </strong>
<ul>
<li>decision-making structures and cultural conventions that encourage horizontal power dynamics
<li>accountability processes to address internal domination
<li>conflict resolution, both internally and with potential allies
<li>the ability to provide for material, social, and emotional needs
<li>the capability to reproduce the social forms of resistance faster than they are destroyed
<li>the means to communicate beyond a single subculture
<li>the flexibility to adjust according to context, rather than remaining caught in ritual</ul>
</p>
<p>&nbsp;</p>
<p align="right" style="color: #600">It is April 21, 2001, and a black bloc is methodically knocking out all the windows of a multinational bank in downtown Quebec City during the <a href="http://en.wikipedia.org/wiki/Quebec_City_protest" target="_blank">Free Trade Area of the Americas summit</a>. Street confrontations have been going on for 24 hours straight; much of the city is awash in tear gas, and increasing numbers of protesters are responding with Molotov cocktails and other projectiles.</p><p align="right" style="color: #600">
A crowd of local toughs watches the black bloc from a distance. They have looked on sympathetically as the foreigners scuffled with riot police; the locals have no great love for the police, and as Qu&eacute;b&eacute;cois they resent that much of the occupying army has been brought in from English-speaking provinces halfway across the continent. On the other hand, the activists are invaders too, and now they&rsquo;re smashing up the city.</p><p align="right" style="color: #600">
As the bloc sets out in search of another bank, the locals follow them, picking up blunt objects and threatening them in limited English: &ldquo;Fookers!&rdquo; A bearded older liberal sees this unfolding and falls in stride with the toughs for a moment, pedantically explaining, &ldquo;No, they&rsquo;re not fuckers, it&rsquo;s just a<em> bad tactic</em>.&rdquo; Appropriating what they understand to be a term of biting abuse, the locals continue following the bloc, shouting &ldquo;Bad tak-teek! Bad tak-teek!&rdquo;</p><p align="right" style="color: #600">
One idealistic young anarchist falls back to reason with the pursuers. &ldquo;We&rsquo;re not against you&mdash;we&rsquo;re here to fight the same institutions that dominate you, the multinational corporations and the neoliberal governments that&mdash;&rdquo; He is answered with a punch in the face that drops him to the ground.</p><p align="right" style="color: #600">
This is the critical moment, in which the meaning of the whole mobilization is at stake. If the locals and the black bloc come to blows, the narrative of the weekend will shift from a showdown between People and Authority to pointless fighting between Marginalized Radicals and Everybody Else. The black bloc has a reputation for machismo; many other activists doubt their maturity, if not their sincerity. Having grown up bullied and baited, having become a militant anarchist in hopes of getting revenge, the young man must feel the temptation to fight back. If he does, his comrades will leap to his assistance. But he simply stands up and walks back to them, unsteady but deliberate.</p><p align="right" style="color: #600">
Two blocks further, the police loom into view: row after row of armored storm troopers firing concussion grenades and rubber bullets at the narrow lines of human beings before them. Both groups hesitate. The context has shifted.</p><p align="right" style="color: #600">
The locals eye the anarchists warily. &ldquo;You are here to thrash our cit&eacute;y?&rdquo; one calls out.</p><p align="right" style="color: #600">
&ldquo;No!&rdquo; shouts back a man in a ski mask. &ldquo;To FIGHT THE POLICE!&rdquo;</p><p align="right" style="color: #600">
&ldquo;To fight the police?&rdquo;</p><p align="right" style="color: #600">
&ldquo;To fight them, not you!&rdquo;</p><p align="right" style="color: #600">
&ldquo;Fook the police!&rdquo; shouts back another local, auspiciously.</p><p align="right" style="color: #600">
Representatives of the two groups approach each other with guarded gaits. Flash-bang grenades explode in the background as they hammer out a hasty truce and shake hands. As the sun sets over Quebec City, locals with shirts across their faces crouch alongside slingshot-wielding radicals in goggles and bandannas, peppering the police with chunks of broken concrete.</p><p>
</p>
<h3>Confronting All Forms of Oppression</h3>
<p align="center" style="line-height: 15px; margin-bottom: 25px"><a href="https://cloudfront.crimethinc.com/images/insurrect/insur6_b.jpg" rel="lightbox[insurrect]"><img src="https://cloudfront.crimethinc.com/images/insurrect/insur6_a.jpg" width="500" height="298" style="margin-bottom: 2px"></a><em><br />Insurrectionists coming from positions of comparative privilege <br />
cannot shrug these off simply by donning a mask.</em></p>
<p>Resistance movements have collapsed again and again amidst conflict over accountability, privilege, and internal oppression&mdash;for example, in the US at the beginning of the 1970s, and in Italy at the end of that decade. This occurred on a smaller scale during the disintegration of the US anti-globalization movement after the turn of the century; the consequences of this in Eugene, Oregon are explored in <a href="http://www.crimethinc.com/texts/recentfeatures/greenscared.php" target="_blank">&ldquo;Green Scared&rdquo;</a> elsewhere on this website.</p><p>
In some circles, insurrectionists have a reputation for failing to focus on these issues. This is extremely problematic&mdash;the point of anarchist activity is to attack <em>all </em>forms of hierarchy, not just the targets that make for exciting riot porn. Accountability and awareness of privilege strengthen the relationships that make meaningful struggle possible; without these, an affinity group can fall apart in the same way a movement can. Nurturing healthy relationships is not an additional task anarchists must take on alongside the project of resisting domination&mdash;it is the <em>basis</em> of that project, and a way to safeguard it.</p><p>
Even if the aforementioned bad reputation were only slander based on circumstantial evidence, it would still pose challenges to insurrectionists, for it enables their adversaries to paint them as irresponsible hypocrites.<a class="footnote" href="javascript:void(0);" onclick="return overlib('Some critics challenge the right of a predominantly white or male demographic to initiate confrontations in the first place; but people of all walks of life are entitled to fight for liberation on their own behalf, so long as they don&rsquo;t do so in a way that compromises others. The details of initiating confrontations without compromising others are complicated enough that it would demand an analysis even longer than this one to explore them.', CAPTION, '[4]');" onmouseout="nd();">[4]</a> Whenever anarchists fail to take the initiative to address patriarchy, white supremacy, and other manifestations of hierarchy, they leave themselves vulnerable to the machinations of liberals and others eager to discredit militant resistance. Insurrectionists should take the lead to develop tools for understanding and undermining privilege, so it is clear to everyone that there is no dichotomy between confronting the powers that be and addressing more subtle forms of hierarchical power.</p><p>
Confrontational approaches are bound to encounter opposition at some point, but if the opposition is coming from potential comrades, it&rsquo;s a warning sign that one is on the wrong path. Unfortunately, defensive insurrectionists sometimes react to this by isolating themselves further from constructive criticism, wrongheadedly telling themselves that they don&rsquo;t need allies on the path they have chosen.</p>
<h3>Languages of Exclusion</h3>
<p>By all means, explode with rage. Refuse to reduce your raw anger to demands or suspend your emotional responses to the tragedies around you. Turn your years of pent-up anguish into a fearsome instrument of revenge. Don&rsquo;t translate your grievances into the language of your oppressors&mdash;let them remain burning embers to be hurled from catapults. Attack, negate, destroy.</p><p>
But if it&rsquo;s <em>rage</em> you&rsquo;re feeling, why quote <a href="http://en.wikipedia.org/wiki/Agamben" target="_blank">philosophy professors</a>?</p>
<p>If some strands of contemporary US insurrectionism seem to have given up in advance on the possibility of connecting with comrades outside their immediate cliques, this is especially apparent in their esoteric language and points of reference. Talk about &ldquo;zones of opacity&rdquo;&mdash;and the dangers of becoming trapped in a milieu!</p><p>
Perhaps this is because so much insurrectionist theory has arrived from overseas in poor translation. Domestic insurrectionists emulate the obtuse style of their favorite texts, and the resulting gibberish highlights the absurdity of attempting to transpose an approach from its original context without reconsidering it. We&rsquo;re not qualified to critique insurrectionist writing from France or Italy, where presumably every dishwasher enjoys <a href="http://en.wikipedia.org/wiki/Michel_Foucault" target="_blank">Foucault</a> and <a href="http://en.wikipedia.org/wiki/Antonio_Negri" target="_blank">Negri</a>&mdash;but in the US, words like &ldquo;projectuality&rdquo; make a lot of people stop listening.</p><p>
Another source of this tendency can be found in the influence of academia. In the ivory tower, which is predicated on exclusion, academics are rewarded for developing abstruse language and theory. For some insurrectionists, appropriating such language must seem the same as appropriating other status symbols, such as the hip American Apparel&reg; outfits ubiquitous in certain scenes. But &ldquo;every tool has a world connected to it at the handle,&rdquo; and the exclusivity of academia comes with the terminology.</p><p>
Of course, some people are attracted to exclusive language&mdash;especially people who desire to see themselves as part of an elect in-group. A milieu that attracts a lot of this kind of energy is not likely to make a welcoming space for a broad range of participants; it also might not have a lot of staying power. Capitalist consumerism depends on new trends every season, and that goes for ideas as well as fashion: what is hip one year is guaranteed to be pass&eacute; the next.</p><p>
The alternative to this, amply demonstrated by other US insurrectionists, is not to communicate in dumbed-down prose like some communist splinter group, nor to affect the slang of imagined class allies, but simply to express oneself in a straightforward manner and not take common context for granted. Recovering obscurantists could try writing in the language they use when they talk with their neighbors or relatives. You can&rsquo;t expect others to step outside their comfort zones unless you are willing to do the same yourself.</p>
<p align="center" style="line-height: 15px; margin-bottom: 25px"><a href="https://cloudfront.crimethinc.com/images/insurrect/insur11_b.gif" rel="lightbox[insurrect]"><img src="https://cloudfront.crimethinc.com/images/insurrect/insur11_a.gif" width="500" height="353" style="margin-bottom: 2px"></a></p>
<h3>Striking Poses vs. Decolonizing Violence</h3>
<p align="right">&ldquo;We can become our own riot porn production machine, but this is less important than &lsquo;creating the conditions where an offensive can sustain itself without fading, of establishing the material solidarities that allow us to hold on.&rsquo;&rdquo;<br />
<em>  -<a href="http://zinelibrary.info/files/TD3imp.pdf" target="_blank">Total Destroy #3 [PDF, 2.3 MB]</a></em></p>
<p align="center" style="line-height: 15px; margin-bottom: 25px"><a href="https://cloudfront.crimethinc.com/images/insurrect/insur7_b.jpg" rel="lightbox[insurrect]"><img src="https://cloudfront.crimethinc.com/images/insurrect/insur7_a.jpg" width="500" height="309" style="margin-bottom: 2px"></a><em><br />By and large, radicals in the US have an especially mediated relationship to violence. Small wonder if they find themselves acting out programmed roles <br />
when they attempt to integrate violence into their resistance.</em></p>
<p>By and large, people in the US&mdash;particularly white people<a class="footnote" href="javascript:void(0);" onclick="return overlib('Not all insurrectionists fit this demographic, of course&mdash;but there might be a few who do.', CAPTION, '[5]');" onmouseout="nd();">[5]</a>&mdash;have an especially mediated relationship to violence. This is not to say that we are never exposed to violence, but that proportionately, we witness representations of it more often than we experience it directly. The land beneath our feet was bought with the extermination of its former inhabitants, the commodities that sustain our lifestyles flow in on a sea of blood, but when we think of violence we generally picture stylized images on television and movie screens. Small wonder if radicals who attempt to integrate violence into their resistance find themselves acting out programmed roles.</p>
<p>
&ldquo;Riot porn,&rdquo; the depictions of anti-authoritarian violence that abound in insurrectionist media, is only a subset of the representations of sex and violence surrounding us in this society. Pornography doesn&rsquo;t just cater to desire&mdash;it also shapes and directs it; in the case of riot porn, it glorifies the moment of physical conflict, while removing the social context that gives it meaning. Pornography can promote roles that have little to do with the actual needs of the participants; those who have been influenced by corporate pornography sometimes make disappointing sexual partners. Likewise, a cynical observer might caricature some current manifestations of insurrectionism as a misguided attempt to distill a strategy from the aesthetic of riot porn: no difficult negotiations with allies, no intermediate or long-term goals, only the moment of attack, isolated in a vacuum.</p><p>
Actual sex and violence can be reclaimed from patriarchal society, but in some ways it is more challenging to reclaim <em>representations</em> of sex and violence.<a class="footnote" href="javascript:void(0);" onclick="return overlib('Speaking of representation, white anarchists must be careful not to exoticize and eroticize violence in poor communities of color. This already occurs in hip hop consumerism, where racist capitalists kill two birds with one stone by profiting off representations of black people as violent and oversexed. Suburban insurrectionists pining for comrades may unconsciously picture stereotypical characters from hip hop videos as their class allies in the social war.', CAPTION, '[6]');" onmouseout="nd();">[6]</a> Anybody can shoot a motherfucker, but in this society the image of the gun is almost inextricably associated with notions of male power and domination. Anti-authoritarians who think spectacular representations of violence can be turned against their masters are playing with fire in more ways than they think.</p><p>
On the other hand, in a society in which so much privilege rests on violence that occurs outside our immediate experience, it is commendable that insurrectionists set out to establish a firsthand relationship to it. Perhaps insurrectionist activity should be evaluated according to how effectively it serves this project of deprogramming, no less than how much it costs the enemy or inspires potential comrades. To what extent does a given action enable the participants to achieve an unmediated and intentional relationship to violence? To what extent is it simply a reprise of all-too-familiar scripts? Just as we might judge erotic play or material by the extent to which it &ldquo;queers&rdquo; sex rather than reinforcing conventional roles and power dynamics, we might assess insurrectionist practice according to the extent to which it <em>queers violence</em>. This could mean anything from <a href="http://bashbacknews.wordpress.com/2009/09/26/queer-anarchists-makes-total-destroy-at-the-g20-summit/" target="_blank">empowering demographics who do not normally have the opportunity to wield violence against their oppressors</a>, to dispelling the influence of media representations of violence by replacing them with a familiarity based in lived experience, to making violence serve forbidden roles no one has yet imagined.</p>
<p>&nbsp;</p>
<p align="right" style="color: #600">The afternoon of the action, one older anarchist who hasn&rsquo;t participated in the organizing expresses his usual irritation: &ldquo;So the idea is to get the fucking cops called, wait till they show up, and then try to march around? These idiots have finally come up with a way to lose the element of surprise, which is practically the only advantage of the tactic!&rdquo;</p><p align="right" style="color: #600">
But surprisingly or not, everything goes exactly according to plan. People gather in the park for food and games, then at the appointed time depart in small groups for the secret location. It turns out to be a spacious abandoned building in the heart of downtown, with a great banner hanging from the roof: &ldquo;Reclaiming space to reclaim our lives: OCCUPY EVERYTHING.&rdquo; Party favors are distributed at the door&mdash;condoms, masks, a precious little manifesto: &ldquo;You see, here&rsquo;s the deal. We&rsquo;ve recently started to realize that we exist&hellip;&rdquo; Inside, a dance party is in progress; the derelict post-industrial decor has been beautified with streamers and another banner, this one reading &ldquo;PARTY LIKE IT&rsquo;S 1886.&rdquo; A couple gender dissidents have taken off all their clothes. Others are exploring the margins of the reclaimed building in ones and twos. Unlike the <a href="http://en.wikipedia.org/wiki/Reclaim_the_Streets" target="_blank">Reclaim the Streets</a> actions that swept the state a decade earlier, this is a private party, but it has the same atmosphere of wonder.</p><p align="right" style="color: #600">
After longer than expected, the news spreads from ear to ear: the police are inside! The sound system cuts out and someone pulls it out the back door just as an officer comes into sight, probing the crowd with his flashlight. Everyone trickles out the front door in a single-file line; this feels somewhat demoralizing, and the older anarchist grumbles that if they really want to have a march they should be exiting in one determined block. Instead, a hesitant crowd congeals on the sidewalk, dawdling as the outnumbered police struggle to figure out what&rsquo;s going on.</p><p align="right" style="color: #600">
The sound system reappears and people rally around it. Just as the crowd begins to move down the street, a policeman rushes over and seizes it. Everyone else continues; turning the corner, they miraculously find themselves occupying the street in a world seemingly empty of authorities. There is no precise cause or rallying cry for the evening, so the participants&mdash;unable to dispense with activist traditions, despite some rhetoric to the contrary&mdash;find themselves chanting the first catchphrases that come to mind: &ldquo;Swine flu!&rdquo; &ldquo;Wu Tang Clan ain&rsquo;t nothin&rsquo; ta fuck with!&rdquo; Two young men out on the town join in, clearly not interpreting this as an anarchist street party.</p><p align="right" style="color: #600">
A block later hoods go up, masks come down, and the sound of grating metal rings out as newspaper boxes are dragged into the street. Everyone else around the country is abandoning corporate print media, but anarchists are still passionately invested in their conviction that the boxes prevent pursuit by police vehicles. The caf&eacute; district is around the next turn, and chairs are sent flying against plate glass windows, only to bounce off and fall to earth. There is an element of playacting in the demeanor of even the wildest participants: they are striking poses, acting out their favorite scenes without the grim determination to <em>do damage</em> that characterized the famous black blocs of the anti-globalization era.</p><p align="right" style="color: #600">
The legal risks, of course, are still very real&mdash;but the police are mercifully far behind, and the crowd disperses before they can catch up. Some participants are pleased with themselves; others are nonplussed. A young hippy tries to initiate a conversation with a stern-faced fellow tucking a sweatshirt under his arm: &ldquo;Did you see those people throwing chairs at windows? That&rsquo;s fucked, huh?&rdquo; The one with the sweatshirt picks up his pace and does not answer.</p><p align="right" style="color: #600">
Afterwards, all the discussions from five years earlier begin again. Was it irresponsible for some people to escalate to property destruction when others didn&rsquo;t know it was coming? On the other hand, how are people supposed to initiate participatory vandalism? You can&rsquo;t exactly put up fliers announcing it. Did anyone aside from the participants understand the point&mdash;and does that even matter? Is it pathetic that the would-be rioters couldn&rsquo;t break the caf&eacute; windows? Or is it fortunate, as that might have provoked a more serious follow-up inquiry without achieving any meaningful objective? Few recognize these old questions&mdash;five years earlier, most people were living elsewhere or involved in totally different things.</p><p align="right" style="color: #600">
The grumpy older anarchist reminisces about the days when surprise marches like this used to take place in his own community. The first one involved hundreds of people, the majority of whom had never imagined themselves parading without a permit; to his mortification, they chanted &ldquo;What do we want? PEACE!&rdquo; when he would have preferred to raze the whole city to the ground. Over the following years, each march became a little more aggressive than the last; a small nucleus of committed clandestine organizers emerged, while conflicts deepened within the broader social base that made the format possible. The final action ended up on the national news, with tens of thousands of dollars of damage done to a high-profile target and several people standing trial for felonies. After that, everything dissolved in a mix of angry recriminations, exhausting legal support, and prohibitive security culture.</p><p align="right" style="color: #600">
His friend asks if it was worth it. &ldquo;Maybe,&rdquo; he allows. &ldquo;Like, everyone blames the Spanish anarchists for losing the <a href="http://flag.blackened.net/revolt/spaindx.html" target="_blank">Spanish Civil War</a>, as if a few kids in their twenties today could know the context better than they did&mdash;but perhaps they knew they were doomed from the start, and were holding it together as best they could in hopes of going out with a bang so they could inspire people like us. If the movement we were part of wasn&rsquo;t going to last forever, maybe it&rsquo;s for the best it ended the way it did, too. But should you cut right to smashing shit when you&rsquo;re trying to get something started? I don&rsquo;t know.&rdquo;</p><p>
</p>
<h3>Pretensions of Destroying Everything</h3>
<p>Some contemporary insurrectionism affects a nihilist posture, proposing in an offhand manner that everything that exists must be destroyed. To indigenous or environmentalist ears, this project of universal destruction can sound suspiciously like the program industrial capitalism is already carrying out.</p><p>
As with the disavowal of subculture, it may make pretty rhetoric to say one is against &ldquo;everything,&rdquo; but it doesn&rsquo;t make a lot of sense. Even opposing everything is still a position adopted in this world, shaped by and proceeding from the existing context. If we are against <em>everything</em>, how do we navigate? Where do we start, and how can we be sure that the results of our efforts won&rsquo;t be even worse? Can we make any stipulations about which direction to set out in at all?</p><p>
It makes more sense, and is more honest, to say that we side with some existing beings and currents against others, and hope by doing so to effect a total transformation of the world. Not only does this approach offer concrete starting points, it also lends itself better to studying the intricate ways hierarchical and horizontal dynamics intermingle in both the enemy&rsquo;s camp and our own.<a class="footnote" href="javascript:void(0);" onclick="return overlib('Contrast this with the facile opposition to &ldquo;civilization,&rdquo; case closed, adopted by hard-line primitivists.', CAPTION, '[7]');" onmouseout="nd();">[7]</a> If you can&rsquo;t see any good in your adversary, you probably won&rsquo;t be able to recognize anything bad in yourself. By the same token, the idea that everything has to be destroyed anyway can make it easy to excuse oneself from criticism.</p>
<h3>Dynamiting the Fault Lines</h3>
<p align="center" style="line-height: 15px; margin-bottom: 25px"><a href="https://cloudfront.crimethinc.com/images/insurrect/insur8_b.jpg" rel="lightbox[insurrect]"><img src="https://cloudfront.crimethinc.com/images/insurrect/insur8_a.jpg" width="500" height="283" style="margin-bottom: 2px"></a><em><br />Clashes do not occur between groups so much as within societies. <br />
Every society is made up of conflicting currents, which compete not only <br />
within society as a whole but also within the individuals who constitute it.</em></p>
<p>Let&rsquo;s return once more to the context surrounding large-scale insurrections such as the one that took place in <a href="/blog/2008/12/20/greece-and-the-insurrections-to-come/">Greece in December 2008</a>. Militant resistance is sustainable in such situations not only because of the initiative of the immediate participants, but also because of the efforts of non-anarchists who oppose military intervention, organize against legal repression, and otherwise limit the options of the state. Many of these people may also oppose the insurrection, even while playing essential roles in making it possible. If social war were simply a matter of force meeting force, the Greek government could have bombed all the squats and occupied universities from which the revolt was organized; it could not do so because its hands were tied by liberals, and for fear of turning liberals into radicals.</p><p>
This is not to diminish the courage of those who meet the state in open conflict, but to emphasize that clashes do not occur <em>between groups</em> so much as <em>within societies</em>. Every society is made up of conflicting currents, which compete not only within society as a whole but also within the individuals who constitute it; the moments of rupture that take place within individuals are no less important than those that take place between classes. The most effective insurrectionist actions not only open up the fault lines that run through society, they also compel the undecided to take sides&mdash;and to do so according to their own interests, rather than those of their masters.</p><p>
The outcome of revolutionary struggle is not decided by revolutionaries or autocrats so much as by those who sit on the fence between them. The balance of power is determined according to which side of the fence they come down on when they are forced to choose. Revolutionaries ignore this at their peril.</p>
<h3>Infrastructure <s>versus</s> Equals Confrontation</h3>
<h5>It is neither persuasion to abstract ideas nor class position alone that makes people invest themselves in the struggle against hierarchy. It is the experience of anarchist solutions to the problems of life, <br />
the development and fulfillment of anarchic desires. <br />
The need to revolt, to destroy, to get revenge is only one of many such desires.</h5>
<p>Liberals and others who oppose revolutionary struggle often pose a false dichotomy between connecting with the community and engaging in militant confrontation. Some insurrectionists have accepted this dichotomy at face value, arguing for the latter in place of&mdash;perhaps in despair of&mdash;the former. Ten years ago, militant anarchists argued against the conceptual framework of violence &ldquo;versus&rdquo; non-violence; now the pendulum has swung to the opposite extreme, and it is insurrectionists who insist that <em>attack</em> is distinct from community organizing.</p><p>
On the contrary, &ldquo;community organizing&rdquo; and taking the offensive are at their most effective when they are identical. Permanent conflict, decentralized organization, and all the other insurrectionist precepts can serve quite well in <a href="http://www.omnipresence.mahost.org/comiso.htm" target="_blank">local, community-based struggles</a>.<a class="footnote" href="javascript:void(0);" onclick="return overlib('For example, one of the classic cases of insurrectionist practice referenced by Alfredo Bonanno was a campaign to prevent the construction of a US missile base in Comiso, Italy. Anarchists helped form autonomous groups in the community, which were not ideologically identified but functioned according to insurrectionist principles, on the basis of a commitment to stop the construction by any means necessary.', CAPTION, '[8]');" onmouseout="nd();">[8]</a> Combining infrastructural and confrontational approaches does not mean volunteering at an infoshop during the day and smashing bank windows at night, but rather synthesizing the two into a single project. This is not complicated&mdash;as the whole world has been taken from us, we need only seize back any one of the things that should be ours and we enter into conflict with the state. If anarchists do not undertake this more often, perhaps it is because it is always most frightening to attempt what one wants most, what one knows one should have been doing all along.</p><p>
Is there an empty lot that should be a community garden? Turn it into one, and mobilize enough social force that the owner finds it most convenient to leave you be. Is a coworker being harassed or laid off? Bring the full power of your community to bear against her employer. Are there resources at the grocery store or the university that would be better off in your neighborhood? Figure out whom you can trust and how to distribute them, and<em> <a href="http://news.infoshop.org/article.php?story=20060508223435549" target="_blank">take them</a></em>. To win these engagements, you&rsquo;ll have to spend a lot more time building up relationships and credibility than running around with masks on&mdash;but there are no shortcuts in social war.</p><p>
This is nothing less than the project of <em>beginning our lives</em>, eternally deferred with all manner of half-hearted excuses and tortuous theoretical justifications. In our<em> real</em> lives, we are warriors who fight for ourselves and each other, who seize back the territory of our day-to-day existence or else die trying. Nothing less is worthy of us.</p><p>
It is neither persuasion to abstract ideas nor class position alone that makes people invest themselves in the struggle against hierarchy. It is the <em>experience </em>of anarchist solutions to the problems of life, the development and fulfillment of anarchic desires. The need to revolt, to destroy, to get revenge is one such need; if insurrectionist approaches can fulfill it, so much the better. But we deserve a resistance that fulfills <em>all</em> our needs, and all our dreams besides.
</p>
<p align="center" style="line-height: 15px; margin-bottom: 25px"><a href="https://cloudfront.crimethinc.com/images/insurrect/insur9_b.gif" rel="lightbox[insurrect]"><img src="https://cloudfront.crimethinc.com/images/insurrect/insur9_a.gif" width="500" height="789" style="margin-bottom: 2px"></a></p><p>
</p>
<p align="right" style="color: #600">Returning from the riots in <a href="http://en.wikipedia.org/wiki/Protests_during_the_EU_summit_in_Gothenburg_2001" target="_blank">Gothenburg during the 2001 summit of the European Union</a>, activists in Stockholm begin casting around for ways to initiate struggles closer to home. At first, the prospect is overwhelming: when you&rsquo;re trying to confront the system in its entirety, where do you start?</p><p align="right" style="color: #600">
Meanwhile, the rates in the Stockholm subway increase from 450 kronor to 500. One day, perhaps en route to a meeting, a young activist narrowly escapes being ticketed for fare evasion. Like most of her friends, she simply can&rsquo;t afford the new rates, and has to risk her luck leaping the turnstile every time she goes out. Most of the time she gets away with it&mdash;but if they catch her next time, it will cost 1200 kronor.</p><p align="right" style="color: #600">
She reflects on how many others must share her plight, each waging an individual guerrilla war against the transportation authorities. There&rsquo;s a union for everything in Sweden, it seems&mdash;but when it comes to the day-to-day tactics by which people actually survive, they still have to go it alone.</p><p align="right" style="color: #600">
There&rsquo;s an idea. A <a href="http://news.infoshop.org/article.php?story=2008sweden-fare-dodging" target="_blank">fare-dodgers union</a>.</p><p align="right" style="color: #600">
Hundreds of people join up. The dues are 100 kronor a month, a savings of 80% on the government rate for transportation, and if you get busted the union pays your fine. More importantly, fare dodging is no longer an isolated activity, but a collective revolt. Fare-dodgers see themselves as a social force, taking pride in their actions and inviting others to join in; the union also warns commuters of the movements of ticket enforcers, giving them added incentives to skip the fares even if they don&rsquo;t become dues-paying members. Rather than trying to persuade others to join in their activism, the founders of the union have found a way to bring people together on the basis of the resistance they were already engaged in: now every fare-dodger is a potential revolutionary, and <em>sees herself as one</em>.</p><p align="right" style="color: #600">
After a few months have passed and a few members have been busted for evasion, it turns out that the union is operating at a profit. With the extra funds, the organizers produce glossy propaganda urging the public to join them in an all-out war on public transportation fees, and begin brainstorming about their next step. What other fault lines run through Swedish society? How can other individual revolts be transformed into collective power&mdash;not in order to bargain with the authorities, but to defy them?</p>
<p align="right" style="color: #600"><em>[For more on the fare-dodgers&rsquo; union, see <a href="http://www.planka.nu" target="_blank">www.planka.nu</a>.]</em></p>
<h3>Anarchism without Adjectives</h3>
<p align="right">&ldquo;There are no such things as superior forms of struggle. <br />
Revolt needs everything: papers and books, arms and explosives&hellip;<br />
The only interesting question is <em>how to combine them</em>.&rdquo;<br />
<em>-<a href="http://www.theanarchistlibrary.org/daggers-drawn-existent-its-defenders-and-its-false-critics" target="_blank">At Daggers Drawn</a></em><a href="http://www.theanarchistlibrary.org/daggers-drawn-existent-its-defenders-and-its-false-critics" target="_blank"></a></p>
<p>If we have never called ourselves insurrectionists, it is not because we do not wish for insurrection, but because our own temperament predisposes us to an <a href="http://en.wikipedia.org/wiki/Anarchism_without_adjectives" target="_blank"><em>anarchism without adjectives</em></a>. The important thing is to fight for freedom and against hierarchy; we imagine that this will demand different approaches in different situations, and that these approaches may need one another to succeed. We are <a href="http://en.wikipedia.org/wiki/Anarcho-syndicalism" target="_blank">anarcho-syndicalists</a> on the shop floor, <a href="http://en.wikipedia.org/wiki/Green_anarchism" target="_blank">green anarchists</a> in the woods, <a href="http://en.wikipedia.org/wiki/Social_anarchism" target="_blank">social anarchists</a> in our communities, <a href="http://en.wikipedia.org/wiki/Individualist_anarchism" target="_blank">individualists</a> when you catch us alone, <a href="http://en.wikipedia.org/wiki/Anarchist_communism" target="_blank">anarcho-communists</a> when there&rsquo;s something to share, <a href="http://en.wikipedia.org/wiki/Insurrectionary_anarchism" target="_blank">insurrectionists</a> when we strike a blow.</p><p>
Anarchism without adjectives not only refuses to prioritize one approach over the others, but emphasizes the importance of each aspect of anarchism to its supposed opposites. The riot needs the bake sale to be repeatable; the arson needs the public campaign to be intelligible; the supermarket heist needs the neighborhood grocery distribution to pass on the goods.</p><p>
All dichotomies are false dichotomies to some extent, masking not only the common threads between the terms but also the <em>other</em> dichotomies one might experiment with instead. On close inspection, successful insurrectionism seems to depend so much on &ldquo;community building&rdquo; and even &ldquo;<a href="http://en.wikipedia.org/wiki/Lifestyle_anarchism" target="_blank">lifestyle anarchism</a>&rdquo; as to be virtually indistinguishable in practice. If we retired this particular distinction, what other distinctions might arise in its place? What other questions might we ask?</p><p>
All this is not to say that individual anarchists can&rsquo;t focus on their particular skills and preferred strategies&mdash;simply that it is an error to frame anyone&rsquo;s personal preferences as universals. In the end, as always, it comes down to a question of which problems you want to wrestle with, which shortcomings you feel most equipped to overcome. Do you prefer to struggle against invisible hierarchies in informal networks, or brave the stultifying inertia of formal organizations? Would you rather risk acting rashly, or not acting at all? Which is more important to you, security or visibility&mdash;and which do you think will keep you safer in the long run?</p><p>
We can&rsquo;t tell anyone which problems to choose. We can only do our best to outline them. Best of luck in your insurrections&mdash;may they intersect with ours.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/insurrect/insur10_b.gif" rel="lightbox[insurrect]"><img src="https://cloudfront.crimethinc.com/images/insurrect/insur10_a.gif" width="500" height="313" style="margin-bottom: 2px"></a><em><br />[<a href="/tools/downloads/#fight">Available as a PDF poster here</a>.]</em></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>
</p>
<h4>Further Reading</h4>
<p><a href="http://www.anarkismo.net/article/3430" target="_blank">&ldquo;Anarchism, Insurrections, and Insurrectionalism&rdquo;</a> by <a href="http://en.wikipedia.org/wiki/Platformism" target="_blank">Platformist</a> Joe Black</p>
<p><a href="http://theanarchistlibrary.org/insurrection-vs-organization" target="_blank">Insurrection vs. Organization: Reflections from Greece on a Pointless Schism</a> by Peter Gelderloos</p>
<p>&nbsp;</p>
<div id="footnoteprint">
<p>
</p><p>
</p>
<p>[1] Assuming common cause with others of unknown political commitments on the basis of their apparently subversive actions is risky on multiple levels. The Situationists used the Watts riots to argue that their ideas were &ldquo;already in everyone&rsquo;s heads&rdquo; at best, that was a stretch, and at worst a way to claim the right to speak for those who could only speak on their own behalf through action. We can celebrate rebellious actions from outside our communities, but meaningful alliances demand actual relationships.
</p>
<p>[2] &ldquo;It is better to loot than to shoplift, to ambush than to snipe, to walk out than to phone in a bomb threat, to strike than to call in sick, to riot than to vandalize . . . Increasingly collective and coordinated acts against this world of coercion and isolation aren&rsquo;t solely a matter of effectivity, but equally a matter of sociality&mdash;of community and fun.&rdquo; -<em>War on Misery #3</em>
</p>
<p>[3] It&rsquo;s worth noting that the only Operation Backfire defendants who conducted themselves honorably were the ones who were still involved in activist organizing or subcultural communities.</p>
<p>[4] Some critics challenge the right of a predominantly white or male demographic to initiate confrontations in the first place; but people of all walks of life are entitled to fight for liberation on their own behalf, so long as they don&rsquo;t do so in a way that compromises others. The details of initiating confrontations without compromising others are complicated enough that it would demand an analysis even longer than this one to explore them.</p>
<p>[5] Not all insurrectionists fit this demographic, of course&mdash;but there might be a few who do.</p>
<p>[6] Speaking of representation, white anarchists must be careful not to exoticize and eroticize violence in poor communities of color. This already occurs in hip hop consumerism, where racist capitalists kill two birds with one stone by profiting off representations of black people as violent and oversexed. Suburban insurrectionists pining for comrades may unconsciously picture stereotypical characters from hip hop videos as their class allies in the social war.</p>
<p>[7] Contrast this with the facile opposition to &ldquo;civilization,&rdquo; case closed, adopted by hard-line primitivists.</p>
<p>[8] For example, one of the classic cases of insurrectionist practice referenced by Alfredo Bonanno was a campaign to prevent the construction of a US missile base in Comiso, Italy. Anarchists helped form autonomous groups in the community, which were not ideologically identified but functioned according to insurrectionist principles, on the basis of a commitment to stop the construction by any means necessary.</p></div>