<p align="center"><a href="https://cloudfront.crimethinc.com/images/language/1b.jpg" rel="lightbox[breakwith]"><img src="https://cloudfront.crimethinc.com/images/language/1a.jpg" width="500" height="300" title="Anarchism and the English Language, English and the Anarchists’ Language"/></a></p>
<h6 align="right" style="margin-right: 0px"><em>This text is also available as a <a href="http://www.crimethinc.com/blog/2013/05/23/anarchism-and-the-english-language/">printable zine</a>.</em></h6>
<p><em>An exchange between Kristian Williams and the CrimethInc. Writers’ Bloc</em></p>
<h1>Anarchism and the<br />English Language</h1>
<p><em>Kristian Williams</em></p>
<p>George Orwell, in his classic essay, <a href="https://www.mtholyoke.edu/acad/intrel/orwell46.htm">“Politics and the English Language,”</a> makes the case that “the English language… becomes ugly and inaccurate because our thoughts are foolish, but the slovenliness of our language makes it easier for us to have foolish thoughts.”</p>
<p>The vices Orwell catalogued—vague phrases, dying metaphors, jargon, and general pseudoscientific pretentiousness—all help to sustain our boring prose. But worse, they also produce a stagnant and stifling mental atmosphere in which <em>thought</em> is commonly replaced with the automatic recitation of certain prescribed words or phrases “tacked together,” as Orwell memorably put it, “like the sections of a prefabricated hen-house.”</p>
<p>The effect on readers is certainly bad enough, but the implications for writers are more serious still. Sometimes, of course, vague and shoddy prose—and the readiness with which such is accepted—makes it possible for a writer to deliberately pass off one thing as another, or to hide bad reasoning in a rhetorical fog. More often, however, a well-meaning writer just accepts the standard currently in use and out of witless habit uses language that alters, obscures, or nullifies his own meaning. In such cases, the writer, too, is the victim: he means to say one thing, and says another; or, he means to say something, but says nothing instead. </p>
<p>This dynamic poses special problems for anarchism, as a mode of thought that shuns orthodoxy on principle and should be above defrauding an audience in the fashion typical of politicians and their parties. Anarchists face the further problem that, through clumsiness and inattention, our ideas become unintelligible. This destruction of meaning occurs at many levels simultaneously: It is impossible to convince people of an idea if one cannot explain it; it is equally impossible to explain an idea if you do not understand it yourself; and it is impossible to adequately understand an idea if its only means of expression frustrate any efforts to define or analyze it. Through this process ideas are transformed into something like the Latin mass: we in the congregation may not understand the priest&#8217;s ritual mumblings, but we believe that the words will save us.</p>
<p>Consider, for example, a sentence like “To be allies, cisgendered people need to check their privilege.”</p>
<p>Such a sentence is, by contemporary anarchist standards, utterly unremarkable and may even be regarded as a truism. And it contains several features that make it representative of the type of writing I am discussing. The first thing one ought to notice is the unattractive and the peculiarly un-persuasive quality of the language. Simply reading the words, it is very difficult to accept that only a single century separates this writing from the prose of Edward Carpenter or Peter Kropotkin.</p>
<p>Even apart from its plain ugliness, the writing is indecipherable to the uninitiated. It is dense with vague jargon terms, and offers not a single original turn of phrase, nor an image of any kind. Of its brief ten words, one—<em>cisgendered</em>—only exists in certain marginal academic departments and in a very narrow sliver of the political spectrum. Three others—<em>allies</em>, <em>check</em>, and <em>privilege</em>—are everyday English words that here take on specialized meanings. And one of these is so ambiguous as to render the sentence practically meaningless: Does <em>check</em> mean to examine, or to verify? Does it mean to physically block (as in hockey), or threaten (as in chess), or to decline a bet (as in poker)? Does one check one&#8217;s privilege the way one checks one&#8217;s coat at the theater, to be retrieved again after the show? Like a lot of moralistic language, this phrase manages to be prescriptive without actually being instructive: it offers us a command, but it lacks the necessary specificity to actually tell anyone what they should do in any real-world circumstance.</p>
<p>I&#8217;m not complaining here that the language is difficult—on the whole it is not—but that it is unsalvageably vague. It is, or should be, a problem if your idiom makes it impossible for other people to grasp your ideas; but how much worse is it if your language helps you to hide your meaning even from yourself? To a very large degree, the language here is standing in for thought. People who write this sort of thing may have some general idea of what they are trying to say—but they needn&#8217;t have. They&#8217;ve absorbed the correct words, the way a child memorizes the Pledge of Allegiance, without much concern as to whether the words correspond to anything in particular, either in the real world or even in one&#8217;s imagination.</p>
<p>My above example is drawn from queer politics, but one could easily multiply the cases if one so chose. (For instance: “The black bloc became a mere facet of the totalizing spectacle.”) All branches of anarchism—primitivists, syndicalists, insurrectionists, CrimethInc.—are similarly guilty, though the required code words and the preferred rhythm of the language may vary somewhat from one clique to the next. One need only pick up any issue of any anarchist publication—no matter what faction it represents—to find at least one example of similar writing.</p>
<p>Many of the words that occur most commonly in anarchist writing are used, I suspect, with no precise meaning in mind—or at times, with a meaning quite different from the typical usage. “Accountability,” “community,” “solidarity,” and “freedom” are used, in the overwhelming number of cases, simply as markers to signify things we like or favor. When we read, for instance, that “organizers should be accountable to the community,” we are each left to wonder who this relationship is supposed to involve, and are much less certain about what it is supposed to look like. Likewise, when we read that some group wants to “hold sex offenders accountable,” it is a fair and obvious question what they propose to actually <em>do.</em> Do they want them to make a public statement of apology? Do they plan to beat them up? Or do they mean, by circular logic, that they will hold them accountable by calling for them to be held accountable? It is striking how seldom such questions are ever answered—but it is more striking still how seldom they are actually <em>asked.</em> In both cases, the key word—<em>accountability</em>—has been invoked, and that is thought somehow to be sufficient.</p>
<p>Too often, the point of writing this way is not so much to communicate a specific idea to some real or potential readership. The words serve instead to indicate a kind of group loyalty, an ideological border between our side and the other side: we believe <em>this,</em> and they don&#8217;t. Or rather: we talk in <em>this</em> way and say <em>this</em> sort of thing; <em>they</em> talk in some other way, and say some other sort of thing.</p>
<p>Adopting the proper style allows one to demonstrate how radical one is. And it is a symptom of one&#8217;s writing being shaped by concerns, often suppressed concerns, about orthodoxy. It becomes important, not only to think the right thoughts, but also—sometimes even more so—to use the right words, as though one needs to punch in the correct code, but doesn&#8217;t need to remember why that particular series of letters was selected in the first place.</p>
<p>Underneath this practice of mental mimicry is the sense that words are imbued with a kind of mystical essence—some being good, others bad—irrespective of context or the use to which they are being put. The policing of language is one result, usually in the form of self-censorship but sometimes under public pressure. (I was recently chastised, for example, for using the word <em>riot</em>; the more vague <em>uprising</em> or <em>rebellion</em> being preferable.) Once euphemism begins to creep in, it is a short distance to travel between political politeness and pure dishonesty. At the same time, and following from the same impulse, much of our rhetoric takes on a ridiculously inflated quality. Protests become uprisings, on the one hand, while a drunken fight is described as “acting out” (unless, for other reasons, we label it “abuse”). In either case, the tendency is to write according to what <em>should have happened</em> under the terms of one&#8217;s own favorite theory, rather than struggling to discover and describe events as they actually occurred.</p>
<p>The tendency toward rhetorical inflation is driven, I believe, by a desire to make ourselves seem bigger, better, or more important than we are—even if the only people we fool are ourselves. “Actions” sound tougher than “protests” or “rallies,” even if all we do at these “actions” is walk about with signs. And it is rather embarrassing in a political context to say “me and my friends,” so instead we say “community” when we really mean “scene,” and “scene” when we really mean “clique.” But, isn&#8217;t there the nagging suspicion that something has gone awry when we begin using the word “community” in a way that excludes our neighbors, the mail carrier, and members of our immediate family?</p>
<p>Once this pattern sets in, all sense of proportion washes out of our language. Descriptions of events shrink or swell, not according to any observable feature of anything that has happened, but according to an <em>a priori</em> formula. One need only glance at the statements issued by competing sides in some recent anarchist controversy—the latest instantiation of the perennial debates over violence and nonviolence, or militant action versus base-building, will do—to recognize that, the two sides do not just <em>disagree</em> about this or that specific incident, but where questions of fact arise, each side takes an attitude of almost perfect indifference.</p>
<p>The linguistic drift is dangerous because it makes honest discussion impossible. And, maybe more worrisome, people are surprisingly willing to fall for their own propagandistic tricks. A political movement cannot expect to succeed, or even survive, if it cannot face reality. But moreover, if its members in very large numbers <em>do</em> lose touch with the world beyond their own press releases and manifestos, the movement probably will not even <em>deserve</em> to survive.</p>
<p>Anarchists, of course, are not the only people to write as though the words don&#8217;t matter. Much current writing is straightforward nonsense—not only political writing, but also advertising copy, academic prose, legal decisions, religious sermons, and love songs. But aside from the slipshod quality of contemporary English, and beyond even the special vices of political propaganda, anarchism has acquired several faults that are, more or less, distinctive.</p>
<p>For instance, we seem to have acquired the dubious habit of adopting an everyday word, narrowing its meaning, and turning it into a kind of jargon. The above-mentioned “allies,” “privilege,” “accountability,” and “actions” are all examples—as are “process” (as a verb), “facilitate,” “recuperate,” “lifestyle” (as an adjective), “bottom-line” (verb), “spectacle,” “safe space,” “spoke” (noun), “care” (noun), and “harm.”</p>
<p>Similarly, we sometimes take words that are necessarily relative and use them as though they were absolute. “Accessible” (or “inaccessible”) and “alternative” are the chief examples. Nothing <em>just is</em> accessible. It must be accessible <em>to someone.</em> Likewise, something can only be an alternative <em>to something else.</em> Saying that it&#8217;s an alternative to “the mainstream” is just question-begging.</p>
<p>More embarrassing still, many of our jargon terms are not even our own, but have been appropriated, or misappropriated, from other traditions—Marxist, Foucauldian, post-modern, feminist, or Queer Theory. There&#8217;s nothing wrong with that on its own, and I personally admire a willingness to take good ideas regardless of the source. But we&#8217;ve started writing like undergraduates imitating their professors. We say “hegemony” when we really just mean “influence,” and “contradiction” when we&#8217;re talking about conflict, “performativity” instead of “behavior,” and so on. The results of this imitative habit are sometimes pretty odd: because of Foucault, it is now common in political writing to refer to <em>people</em> as <em>bodies.</em> Thanks to Hardt and Negri, we talk about Empire rather than imperialism. And, in a related development, we commonly talk about Capital rather than capitalism, and do so in a way that makes it sound like an ill-tempered deity rather than an economic system.</p>
<p>Too often, too, we present simple ideas with complex language because we think it makes us look smarter, edgier, or more radical. We pepper our language with technical terms just to show that we&#8217;ve done our homework. There seems to be an agreement on the left that it is better to write in the style of badly-translated Hegel than to write like John Steinbeck. It is even easier, provided you don&#8217;t care to be understood.</p>
<p>The problem of course is not with the words themselves. The problem isn&#8217;t even with abstraction. Any effort to apply the lessons from one case to another necessarily involves some form of abstraction. The problem is the avoidance of clarity in meaning. The solution, then, is not to simply to abstain from using certain words, or to substitute new jargon for old, but to do what we can to make our writing as clear as possible. We do that through the use of fresh imagery, of concrete detail, and by taking care to spell out precisely who and what we mean whenever we&#8217;re tempted to invoke old spooks like “the people” or mystical processes like “struggle.”</p>
<p>The point here is not simply to describe the present state of anarchist writing, but to reverse the trends that have brought us here. And while many of the examples in “Politics and the English Language” are now very much out of date, Orwell&#8217;s advice remains sound. He offers one general principle, six rules, and six questions. </p>
<p>The principle is: “Let the meaning choose the word, and not the other way about.”</p>
<p>The rules are:</p>
<ol>
<li>Never use a metaphor, simile or other figure of speech which you are used to seeing in print.</li>
<li>Never use a long word where a short one will do.</li>
<li>If it is possible to cut out a word, always cut it out.</li>
<li>Never use the passive where you can use the active.</li>
<li>Never use a foreign phrase, a scientific word or a jargon word if you can think of an everyday English equivalent.</li>
<li>Break any of these rules sooner than say anything outright barbarous.</li>
</ol>
<p>It is worth noting that, were there a contemporary anarchist style guide, nearly all of these rules would be reversed: <em>Only</em> use figures of speech that you are used to seeing in print; <em>Never</em> use a short word if a long word is available; If it is possible to add a word, <em>always</em> add it in; <em>Never</em> use the active voice where you might use the passive; <em>Always</em> use a foreign phrase or jargon word if the everyday English word can be avoided; And <em>write barbarously</em> rather than violate any of these rules.</p>
<p>No one has formalized such commandments, and no one has had to. The slow drift of the language, and the overall cloudiness of our thought, allows us to adopt such practices without trying, and often, without consciously recognizing it. To break such habits, however, requires a conscious effort.</p>
<p>Orwell&#8217;s advice, put as succinctly as possible, might be summarized: Think before you write. </p>
<p>A scrupulous writer, in every sentence that he writes, will ask himself at least four questions, thus: What am I trying to say? What word will express it? What image or idiom will make is clearer? Is this image fresh enough to have an effect? And he will probably ask himself two more: Could I put it more shortly? Have I said anything that is avoidably ugly?</p>
<p>This approach assumes, of course, that the writer has some definite idea that he means to convey to the reader, that it is not his purpose to simply cycle through the fashionable platitudes in order to represent the right “line” or to rehearse stock phrases for some imaginary debate.</p>
<p>The purpose of anarchist writing, I believe, is—or should be—not to demonstrate how radical we are, or to dazzle our friends with our erudition, but to improve the quality of anarchist thought, to give our ideas a broader circulation, and to use those ideas to help reshape the world. But the present state of our writing, taken as a whole, seems ill-suited to every one of these aims. It produces, instead, hazy thinking, political and intellectual insularity, and, ultimately, irrelevance.</p>
<p>I don&#8217;t mean to suggest that the only thing standing in the way of revolution is bad prose. But it is possible that a great deal of the nonsense could be shaken out of anarchism if we commit ourselves to the clear expression of our ideas, and if we demand the same from the publications that we read. It is very difficult to write clearly unless one is also thinking clearly. And if a sentence cannot be translated from anarcho-english into plain English, there is a very good chance that it is meaningless.</p>
<h3>Kristian Williams is the author of <em>Our Enemies in Blue: Police and Power in America</em>, <em>American Methods: Torture and the Logic of Domination</em>, and <em>Hurt: Notes on Torture in a Modern Democracy</em>. He is presently at work on a book about Oscar Wilde and anarchism.</h3>
<p>&nbsp;</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/language/2b.jpg" rel="lightbox[breakwith]"><img src="https://cloudfront.crimethinc.com/images/language/2a.jpg" width="500" height="300" title="English and the Anarchists’ Language, Anarchism and the English Language"/></a></p>
<h1>English and the<br />Anarchists’ Language</h1>
<p><em>CrimethInc. Writers’ Bloc</em></p>
<p>“The alchemists have a saying: <em>‘Tertium non data’</em>: the third is not given. That is, the transformation from one element to another, from waste matter into best gold, is a process that cannot be documented. It is fully mysterious.  No one really knows what effects change.” –Jeanette Winterson</p>
<p>Kristian’s essay says much of what we would like to say to other anarchist writers. It is cowardly to conceal slipshod reasoning behind a smokescreen of gibberish—and dangerous, too, if you still encourage people to act on your arguments. Down with pseudo-academic posturing! Death to all who affix suffixes to project, potential, and position! <em>And hyperbole to the guillotine!</em></p>
<p>Yet seeing this spelled out as a program, our hearts rebel. Orwell’s advice, as Kristian presents it, might improve bad writing, but it says nothing about the alchemy that sets good writing apart from the merely serviceable. Nor does it engage with what could make writing <em>anarchist.</em> Does one write well as an anarchist the same way one writes well as a social democrat or an advertising agent? Or is anarchist writing another project entirely, which must be evaluated according to other criteria? Kristian is either making a big assumption or a fatal omission. It’s important to address this, lest his prescriptions be used against those who strike off in the right direction.</p>
<p>So given the choice between incoherent, insular jargon and the clear transmission of rational arguments, let us add another dimension to the discussion. We hypothesize a third pole—the mysterious third, the factor that effects change.</p>
<p>For the purposes of his argument, Kristian takes for granted that our language can adequately represent our ideas if we use it properly. But like any technology, language is not neutral; it incarnates the power relations of the society that produced it. It is generally easier to use contemporary English to convey the capitalist worldview than to express ideas or experiences outside it. There are submerged currents of resistance within English, as there are within every aspect of our society, but it tends to impose the values of the dominant social order.</p>
<p>When “legitimate” is inseparable from “authority” and drastically differing activities are defined as “violent” depending on who engages in them, an anarchist cannot trust words to represent her ideas the same way they represent those of politicians and pundits. This is not just a question of misuse, as if the words would <em>tell the truth</em> if they were used correctly. On the contrary, the language of politicians and pundits often appears more accessible than ours because the playing field is slanted in their favor. When we try to be more accessible, we sometimes end up making their points rather than our own.</p>
<p>In the face of such challenges, an anarchist has to bring the subterranean currents of resistance within the language to the surface in the course of making her case, or else she may not be able to make it at all. Moreover, as an anarchist, she must not establish new norms, but open up spaces of free play and uncertainty. Semantics is not just “the science of evading the point,” as a comrade once quipped, but one of the most important battlefields on which the balance of power is determined.</p>
<p>So if we begin with Orwell’s demand to “Let the meaning choose the word, and not the other way about,” we must end by using words in a manner that shakes them loose of their old meanings. When we speak, we shouldn’t focus only on properly <em>designating</em> our ideas via language, but on <em>destabilizing</em> the language itself—showing how it is enemy territory and opening new points of departure.</p>
<p>Let’s perform an example of this. Kristian urges us not to <em>write barbarously.</em> This sounds straightforward enough. Yet this loaded word, <em>barbarous,</em> comes to us from the ancient Greek onomatopoeia, βάρβαρος—it was a mockery of the foreigners whose incomprehensible speech (“bar bar bar”) marked them as inferior to Greek citizens. Similarly, in the essay Kristian cites, Orwell called on his countrymen “to drive out foreign phrases” for the sake of “the defense of the English language.” Orwell meant only to denounce jargon and abstraction, but in both cases we see how swiftly one could pass from demanding intelligibility to something more sinister. If our language is not neutral, it may be most dangerous when it is <em>most</em> intelligible. If that is so, our task as anarchists is to make language unfamiliar in a way that renders the ensuing confusion irresistible rather than off-putting.</p>
<p>Certainly, as Kristian points out, neologisms like “cisgendered” are not familiar to everyone. But if we stay within the bounds of language that is widely used in this society, we will only be able to reproduce consensus reality, not challenge it. How could we possibly challenge gender normativity in the same terms that maintain it? We have to invent new words, styles, and discourses that enable us to say new things while seducing others into the conversation. This calls for a dynamic rather than static understanding of the transmission of meaning—not to mention a little Dadaism. It calls for poetry rather than prose: <em>the third that is not given.</em></p>
<p>When we approach writing thus, mere accuracy ceases to be our principle virtue. This explains some of the examples of powerful writing that fall outside Kristian’s parameters.</p>
<p>A strict focus on accuracy alone would never produce a Lewis Carroll or a Kathy Acker—two authors whose work hints at the kind of anarchic style we are postulating. What is Orwell himself remembered for today—his essays, or his novels? His logic, or his neologisms? His politics, or his thoughtcrime? If not for the vitality of his imagination, his realism would never have reached us. He invented Newspeak to portray how language can be used to limit thought, but paradoxically he needed <em>new language</em> to convey this idea.</p>
<p>And then there is the problem of bad writing that is <em>better</em> than good writing. We remember the famous Audre Lorde quote—“The master’s tools will never dismantle the master’s house”—precisely because, on the face of it, it is patently false. It sticks in our minds; it is an enigma, a knot we can’t stop trying to untie. The same goes for the mixed metaphors of Peter Gelderloos; we may be “defenestrating the stranglehold” long after we have forgotten David Graeber’s methodical formulations. The cheerful excesses of youth will always outshine more prudent prose, to the despair of editors and other pedants. Anarchists should make the most of this, not fight it.</p>
<p>Good writers are generally intelligent, but some truly great writers are idiots savants. As one reviewer wrote of AC/DC, “One brain cell less and it wouldn’t have worked; one brain cell more and it wouldn’t have happened.” The slogans punk rock bequeathed to anarchism, which have borne its resurgence as far as Indonesia, function precisely because of their mystical banality. “Two clichés make us laugh,” wrote a certain Italian, “but a hundred clichés move us, because we sense dimly that the clichés are talking among themselves, celebrating a reunion.”</p>
<p>Then there is the problem of non-representational expression. A humorless reactionary might charge that the best page of <em>Days of War, Nights of Love</em> is the one ripped out of every copy; but the true aesthete <em>knows</em> it is the best page because, more effectively than any other, it conveys a sense of limitless possibility. If the anarchist author’s task is not to put up fencing but to pull up surveyor’s stakes, it is beside the point whether every reader derives the same sense from a sentence; the more widely diverging their responses, the better. Some Rorschach tests are worth more than expressions that convey the same information to everyone—and nothing else.</p>
<p>Besides, those who are convinced that <em>they</em> speak precisely—yet see imprecision virtually everywhere they look—rarely communicate well with others. That’s not how communication works. It is a mutual undertaking, for which rulebooks are no more useful than they are for any other kind of voluntary relationship. When it comes to communication, the proof of the pudding is in the eating, as the saying goes. Which anarchists are most widely read outside the anarchist milieu?</p>
<p>Here we have returned to a centuries-old debate. Do we side with the lucid prose of William Godwin, or the incandescent poetry of Percy Shelley? The sober Murray Bookchin, or the intoxicating Hakim Bey? Apollonian argumentation that frames anarchism as the culmination of the Enlightenment, or the Dionysian romance of an assault on Western civilization?</p>
<p>But who remembers William Godwin? A conservative minority within the anarchist movement has always held that we should be even more serious and scientific than our foes. But anarchists should concentrate on our strengths. Most people are drawn to the anarchist project by the desire for the wild and mysterious, for something ineffable. This is the same philosopher’s stone that distinguishes great art from scrupulous writing—that makes it <em>worth</em> violating the rules—that makes it worth writing at all. No amount of obfuscation can make up for its absence, but neither could any degree of accuracy.</p>
<p>Therefore, in defiance of Orwell and our own better judgment, we are compelled to conclude: <em>Write barbarously!</em> Build your arguments on the slopes of Vesuvius! Send your prose into uncharted seas! Break with common sense and convention in such a way that <em>everyone else joins in!</em></p>
<p>When in Rome, do as the Vandals do: <em>sack it.</em> Axe clichés and replace them with a coinage of your own mint. Topple the Tower of Babel, the imperial project of imposing a unitary logic on language and thought.</p>
<p>Forget about writing properly! <em>Barbarians to the barbarricades!</em> WRITE BARBAROUSLY!</p>
<h3><a href="http://www.crimethinc.com">CrimethInc.</a> is a maelstrom, a collective hallucination, a practice of subversion that probably doesn’t exist at all.</h3>
