<h1>March 4: Anarchists in  the Student Movement</h1>
<p align="center"><a href="http://thecloud.crimethinc.com/images/march4/m41_d.jpg" rel="lightbox[m4]"><img src="http://thecloud.crimethinc.com/images/march4/m41_c.jpg" width="500" height="375"></a></p>
<p>Anarchists in the US have been slow to respond to the economic crisis, missing many of the opportunities it has offered. One of the exceptions is the recent participation of anarchists in the student movement protesting budget cuts and <a href="http://keepcaliforniaspromise.org/383/they-pledged-your-tuition" target="_blank">austerity measures</a>. This came into the national consciousness in December 2008 when students occupied a building at the New School in New York City. NYU followed suit in February, and the following fall students in California began occupying schools up and down the coast.</p>
<p>The most recent phase of the student movement came to a head on March 4, when protests took place <a href="http://news.infoshop.org/article.php?story=2010march6" target="_blank">all around the US</a>. The Bay Area was perhaps the epicenter of this day of action, seeing thousands of people on the streets&mdash;but at this epicenter, the tensions and contradictions around anarchist participation in the student movement came to the fore. Here, we present an <a href="#bayarea">eyewitness report</a> on March 4 actions in the Bay, and complement it with a set of <a href="#bayarea">discussion questions</a> we hope will help anarchists and others in the student movement hone their strategies. We&rsquo;re seeking responses to these questions&mdash;email answers to <a href="mailto:rollingthunder@crimethinc.com" target="_blank">rollingthunder@crimethinc.com</a> or post them in the comments section <a href="/blog/2010/03/09/march-4-anarchists-in-the-student-movement/">here</a>.</p>
<p><a href="#bayarea"><strong>Report from the Bay Area, March 4</strong></a><strong><br />
<a href="#questions">Anarchists in the March 4 Protests: Discussion Questions</a></strong><a href="#questions"></a><br />
</p>
<p><a name="bayarea"></a>&nbsp;</p>
<h2>Report from the Bay Area, March 4</h2>
<p align="center"><a href="http://thecloud.crimethinc.com/images/march4/m42_b.jpg" rel="lightbox[m4]"><img src="http://thecloud.crimethinc.com/images/march4/m42_a.jpg" width="500" height="375" style="margin-bottom: 2px"></a><em><br />Banner at UC Riverside, March 3.</em></p>
<h3>Background</h3>
<p>From their inception, California's university systems&mdash;the University of California and California State University&mdash;were designed to allow access and social mobility for California's underclasses. The UC system was built as a premier research institution. For generations it has trained scientists, architects, and intellectuals. The CSU system was built on a populist model; less academically exclusive, it was to train the state&rsquo;s teachers, engineers, social workers, and the like. Both institutions evolved into world-class university systems, and both offered free enrollment to residents. </p>
<p>This remained the case for almost a hundred years, until in the early 1970s governor Ronald Reagan drastically increased &ldquo;student use fees&rdquo; to about $600&mdash;effectively introducing the first tuition for students. The CSU system eventually followed suit. At the time, opponents of Reagan's plan argued that implementing tuition would make fee hikes part of the normal budgetary process: that politicians would be unable or unwilling to avoid raising tuition when the opportunity presented itself. This is exactly what happened. Tuition at UC campuses exceeded $6000 by 2006. Even taking inflation into account, this represents an increase of over 200%.</p>
<p>That was before the economic crisis. When the markets collapsed in summer 2008, California's economy was hit particularly hard. The state experienced record budget deficiencies and faced insolvency. As part of his program to address the situation, Governor Schwarzenegger <a href="http://www.sacbee.com/2009/12/24/2418279/governors-deficit-cure-layoffs.html" target="_blank">imposed record cuts</a> on California's public education system. To make up for the decrease in state funding, the administrators of the state school systems proposed tuition hikes of up to 32% and mandatory furloughs for education workers equivalent to a 10% pay cut. The administration portrayed these pay cuts and fee hikes as the only option available, when in fact students and faculty thought that the problem would be much better addressed by shifting funds from different parts of the school budget. Funds could have been diverted, for example, from the University's multi-billion dollar construction budget.</p>
<p>Students and educators rebelled. A walkout was organized for September 24, 2009, the first day of the fall quarter at most UC campuses. <a href="http://studentactivism.net/2009/09/25/uc-walkout/" target="_blank">Thousands of students poured out of their classrooms</a> to protest the handling of the economic crisis. Students at UC Santa Cruz famously initiated <a href="http://occupyca.wordpress.com/2009/09/26/httpwww-mercurynews-comcentralcoastci_13419688/" target="_blank">an occupation of the Graduate Student Commons</a> that lasted for a full week. At a <a href="http://takeastand4publiced.org/2009/11/03/report-on-the-decisions-of-the-1024-mobilizing-conference-to-save-public-education/" target="_blank">massive organizing conference</a> on October 24, participants called for a state-wide day of action on <a href="http://www.defendeducation.org/" target="_blank">March 4, 2010</a>. Many were not content to wait this long, however. A call out went out for a student, staff, and faculty strike beginning on November 18, the day the UC Regents were voting to formalize the tuition increases. Over the next few days, demonstrations took place on campuses across the state and occupations occurred or were attempted at UCLA, UC Berkeley, <a href="https://sites.google.com/site/7daywkndproject/files/7dw01__02_08_10_read.pdf" target="_blank">UC Santa Cruz</a>, and UC Davis. <a href="http://occupyca.wordpress.com/" target="_blank">Occupation</a> became the rallying cry of the movement. These actions continued through the rest of the fall semester.</p>
<p>The winter break seemed to take some of the momentum out of the student movement, but behind the scenes students were preparing for March 4. As a buildup action ahead of the main protest, a group called for a dance party on UC Berkeley campus at 10 p.m. February 25. Hundreds of students attended. During the dance, one group conducted a short term occupation of Durant Hall&mdash;an appropriate target, as it is currently being remodeled with funds guaranteed by tuition increases. Around 2 a.m., the party left the campus and started out down Telegraph Avenue. The windows of a Subway outlet were destroyed; the group&rsquo;s numbers surged as intoxicated young people joined the street party from surrounding bars. Dumpsters and trash cans were set on fire.</p>
<p>Eventually police tried to push through the protesters, ostensibly to extinguish the trash fires. Demonstrators fought back with rocks and bottles, and the confrontation evolved into <a href="http://occupyca.wordpress.com/2010/02/26/the-durant-riot-initial-brief/" target="_blank">a small-scale riot</a>. The conflagration lasted about two hours, during which participants danced, fought with police, and <a href="http://www.youtube.com/watch?v=2GZbaXdK8Js" target="_blank">ghost rode the whip</a>. In the end, there were only two arrests.</p>
<p><object width="500" height="303"><param name="movie" value="http://www.youtube-nocookie.com/v/7h_9O7P-QXg&hl=en_US&fs=1&rel=0&color1=0x3a3a3a&color2=0x999999"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube-nocookie.com/v/7h_9O7P-QXg&hl=en_US&fs=1&rel=0&color1=0x3a3a3a&color2=0x999999" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="500" height="303"></embed></object></p><br />
<p>The blowback didn't come from the police, however&mdash;it came in <a href="http://www.dailycal.org/article/108460/community_evaluates_riot_s_impact_on_advocacy_effo" target="_blank">the media</a>, and in the meetings that followed. Well before the riot there had been serious disagreements and polarization within the movement regarding militant actions. This friction has flared up at several times over the last six months, accompanying confrontational attention-grabbing actions such as building occupations. The riot was no different; it was portrayed as having been perpetrated by outside agitators, or by <a href="http://deluche.blogspot.com/2010/02/open-letter-to-white-student-movement.html" target="_blank">privileged white radicals</a>. Subsequent meetings were contentious. Leftists openly and vociferously accused those they believed to be &ldquo;radicals&rdquo; or &ldquo;militants&rdquo; of being &ldquo;adventurist,&rdquo; &ldquo;vanguardist,&rdquo; &ldquo;provocateurs,&rdquo; or worse. The conflicts were draining for organizers with the strike mere days away.<br />
</p>
<h3>March 4</h3>
<p align="center" style="line-height: 15px; margin-bottom: 25px"><a href="http://thecloud.crimethinc.com/images/march4/m43_b.jpg" rel="lightbox[m4]"><img src="http://thecloud.crimethinc.com/images/march4/m43_a.jpg" width="500" height="375" style="margin-bottom: 2px"></a><em><br />A reinforced banner carried by anarchists in the <br />
March 4 protests in Berkeley and Oakland.</em></p>
<p>The actions that took place on <a href="http://occupyca.wordpress.com/2010/03/04/march-4/" target="_blank">March 4</a> were almost too numerous to count. There were pickets, walkouts, marches, and rallies across the state, at all grade levels, in affluent suburbs and poor cities, and elsewhere around the US. Grade schools across the state held &ldquo;disaster drills&rdquo; in protest of the &ldquo;budget disaster.&rdquo; Tens of thousands rallied in San Francisco. In Davis, UC students took over a freeway on-ramp and were attacked by police with batons, rubber bullets, and pepper balls. In Santa Cruz, students blockaded all the main entrances to the campus, effectively shutting it down. In spite of several confrontations and run-ins with speeding vehicles that left some injured, students were able to maintain the blockade of UCSC for the entire day, and ended by marching on downtown Santa Cruz.</p>
<p>Dawn broke on a beautiful clear day in Berkeley. As the sun rose, faculty associations set up pickets at school entrances. Several hundred students set up a human blockade at Sather Gate, a central choke point at the university. The crowd was energetic and boisterous, chanting and hanging banners. This blockade gradually grew in numbers as students arrived on campus. By late morning, a splinter group left for a &ldquo;roving&rdquo; picket of campus; this group ducked into classrooms around the school and encouraged students to walk out and support the protest. By about noon, the crowd at Sather Gate had more than doubled in size.</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/march4/m44_b.jpg" rel="lightbox[m4]"><img src="http://thecloud.crimethinc.com/images/march4/m44_a.jpg" width="500" height="375" style="margin-bottom: 2px"></a><em><br />The picket at Sather Gate outside UC Berkeley, late morning March 4.</em></p>
<p>Shortly after noon, the picket marched south from campus and occupied the intersection of Telegraph and Bancroft. A mobile sound system was playing music. All of this was eerily reminiscent of the late-night riot less than a week before. The crowd was relatively passive at this time, however; instead of setting fires, people listened to speeches over the PA system. This went on for about an hour, while the group gradually grew to at least several thousand people. Once everyone had had enough of the speakers, the gathering set out on a march down Telegraph Avenue and into Oakland. The route was an arduous 4.5 mile hike on a day that had become relatively warm. Although announced in advance, this march had reportedly been granted a permit by the government of Oakland but denied one in Berkeley; thus, at least at its outset, it was an unpermitted event.</p>
<p>After a quarter of a mile, Telegraph opened into a four-lane thoroughfare; the march occupied all four lanes for at least a city block. Several sound systems played loud music; the crowd chanted energetically; there were huge signs, puppets, and the like. People seemed to be generally in good spirits and enjoying a break from the rainy spring weather.</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/march4/m45_b.jpg" rel="lightbox[m4]"><img src="http://thecloud.crimethinc.com/images/march4/m45_a.jpg" width="500" height="375" style="margin-bottom: 2px"></a><em><br />The march proceeds down Telegraph Avenue.</em></p>
<p>Several blocks on the march came to a halt at a double-length bus which had jack-knifed across all four lanes of traffic. It is unclear whether the bus was positioned by police as a blockade, or if it had simply gotten stuck attempting to execute a U-turn to avoid the march. In any case, after a short stall, the march continued around the bus.</p>
<p align="center" style="line-height: 15px; margin-bottom: 25px"><a href="http://thecloud.crimethinc.com/images/march4/m46_b.jpg" rel="lightbox[m4]"><img src="http://thecloud.crimethinc.com/images/march4/m46_a.jpg" width="500" height="375" style="margin-bottom: 2px"></a><em><br />For reasons that remain unclear, a bus jackknifed across the street, <br />
temporarily stopping the march.</em></p>
<p>As the march progressed into Oakland, it repeatedly stopped for several minutes at a time before proceeding again. Such pauses are common in marches that are becoming elongated, as they enable stragglers to catch up. But this seemed like something different, as it occurred with great frequency. Eventually, black-clad &ldquo;militants&rdquo; made their way to the front of the march. Shortly thereafter, the mass of marchers formed a line of banners and came to a stop again. Those in front realized this and came to a stop fifty yards ahead. It seemed as if the two factions were staring each other down.</p>
<p>It was unclear exactly what was going on, but some have asserted that certain organizing groups were unhappy with the presentation at the front of the march: they wanted a cohesive, unified front line displaying all their banners in a row, and they were willing to split the march in order to maintain this. We have no proof that this was indeed the case, but it would explain the apparent tension in the air. In any case, after several minutes, the group proceeded as it had before, although with a little more jockeying for the lead.</p>
<p align="center" style="line-height: 15px; margin-bottom: 25px"><a href="http://thecloud.crimethinc.com/images/march4/m47_b.jpg" rel="lightbox[m4]"><img src="http://thecloud.crimethinc.com/images/march4/m47_a.jpg" width="500" height="375" style="margin-bottom: 2px"></a><em><br />This photo depicts a standoff in which many student groups stopped <br />
in an apparent attempt to separate themselves from the anti-authoritarian <br />
contingents at the front, behind the camera&rsquo;s field of vision.</em></p>
<p>As the procession crossed into downtown Oakland a group of brave young people climbed atop a billboard at least 100 feet high and unfurled a huge banner reading, &ldquo;FIGHT BACK. Today. Mayday. Every Day.&rdquo; The banner-droppers danced atop the billboard, and the crowd cheered as they passed by. </p>
<p align="center" style="line-height: 15px; margin-bottom: 25px"><a href="http://thecloud.crimethinc.com/images/march4/m48_b.jpg" rel="lightbox[m4]"><img src="http://thecloud.crimethinc.com/images/march4/m48_a.jpg" width="500" height="263" style="margin-bottom: 2px"></a><em><br />Young people exuberantly hang a huge banner from <br />
a billboard along the march route.</em></p>
<p>Shortly before the march reached its destination, fliers were distributed calling for an unpermitted &ldquo;dance party&rdquo; following the rally: &ldquo;Look for the flags.&rdquo;</p>
<p>The march proceeded into the heart of downtown Oakland. There were bands of riot police all over. This may have been in response to public criticism that the police response to the Berkeley &ldquo;riot&rdquo; was slow and ineffectual. Finally, the procession entered Frank Ogawa Plaza, where it met teachers and students from K-12 schools and other institutions of public education throughout the bay; who had held their own pickets, rallies and marches. </p>
<p>A group of anarchists and radicals gathered near the edge of the rally as the usual speakers took turns at the podium. Energy seemed low; people were tired from the long march and seemed discouraged by the atmosphere of polarization and the heavy police presence. Things worsened when a speaker took the stage and strongly discouraged protesters from attending &ldquo;any other marches that may leave from here.&rdquo; The speaker stated that any such marches would be unpermitted and dangerous&mdash;especially for young students.</p>
<p>The rally eventually wrapped up and participants gradually filed out of downtown Oakland. Anarchists hesitated. A breakaway dance party and snake march had been planned, but it was unclear if the energy or opportunity remained to carry out that plan. Eventually, a sound system was deployed at 14th and Broadway. This occurred after the great majority of participants had already left; all the same, the dance party quickly drew 200 to 300 people, and the group left the plaza to march in Oakland. Police moved in almost immediately and boxed the march in on three sides. Within minutes, the protest almost ended. People weren't sure what to do, and this seemed like it might be the nail in the coffin. The collective pessimism caused the group to react slowly. But finally it did react.</p>
<p>The snake march turned around and headed North on Broadway. It was somehow able to outmaneuver the police, cutting East one block and heading back south against traffic on Franklin. Within a few blocks the group came to the UC Office of the President, which appeared to have been the target of choice. But a small contingent of police had already positioned themselves in front of the building, and the march lacked the confidence to confront them. This was even more demoralizing. After a few minutes staring down the police line, the snake march moved on. It marched West on 11th back across Broadway and toward the Federal Building. Police had blocked off the street leading there, so the crowd continued West into a residential neighborhood. A few blocks in, word circulated: &ldquo;we're going to the freeway.&rdquo; The pace quickened. People jogged, then ran. The police attempted to outmaneuver the march, but the participants were quicker. After a quick left and then a right, the group came out at 10th and Castro: there it was, a clear shot right onto the freeway, with the cops at least a block away.</p>
<p>It must be said that for Bay Area radicals&mdash;and perhaps radicals everywhere&mdash;the freeway is something of a holy grail. Marches, Critical Masses, and all sorts of protests are always trying to get on the freeway, but are almost never successful. The times they do become almost legendary. A certain status is conferred on those who &ldquo;took the freeway,&rdquo; and everyone seems to remember when it happened. Perhaps this was in the backs of many protesters&rsquo; minds as they gleefully and recklessly ran headlong into rush hour traffic on the I-980 interchange. </p>
<p>Over a hundred protesters joined the group on the freeway. They moved south against traffic as a line of police pursued them. They daringly made their way up the interchange and onto I-880. Daringly, because the interchange quickly becomes elevated, and remains so. There are few exits, and one of the nearest ones lets off directly in front of a major police station. To either side is a thirty foot drop, and even if you could get down that way you'd be in the police impound lot.</p>
<p>The group marched toward the Jackson Street exit about half a mile away. About halfway to the off ramp, dozens of police vehicles in a convoy sped onto the opposite side of the freeway. Scores of riot police poured out and rushed at the marchers, coming in swinging. At least one protester is reported to have escaped by climbing down a tree next to the freeway. Another protester, a teenager, was not so lucky. As police closed in, 15-year-old student Francois Zimany either fell while trying to climb down a tree or was pushed over the side by police. He suffered serious head injuries and was unconscious for at least 10 minutes. He was rushed to the hospital in critical condition, but was released back to his family two days later.</p>
<p>One hundred and sixty were arrested on the freeway. The police action kept I-880 and I-980 closed in all directions for over an hour during the evening commute as they waited for Sheriff's Department buses to load the arrestees. The action made headlines everywhere. As of this writing, most if not all arrestees have been released with misdemeanors and felonies.</p>
<p><object type="application/x-shockwave-flash" width="500" height="310" data="http://www.indybay.org/js/flowplayer/FlowPlayer.swf"> <param name="movie" value="http://www.indybay.org/js/flowplayer/FlowPlayer.swf" /> <param name="quality" value="high" /><param name="bgcolor" value="#000000" /><param name="allowFullScreen" value="true" /> <param name="flashvars" value="config={videoFile:'http://www.indybay.org/uploads/2010/03/07/880policebrutality.mov_preview_.flv',splashImageFile:'http://www.indybay.org/im/play-button-328x240.jpg',loop:false,autoPlay:false,autoBuffering:false,bufferLength:5,initialScale:'fit'}" /> <p>Your browser is not able to display this multimedia content.</p></object></p>
<p><object width="500" height="401"><param name="movie" value="http://www.youtube-nocookie.com/v/C7JBx4PDBjw&hl=en_US&fs=1&rel=0&color1=0x3a3a3a&color2=0x999999"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube-nocookie.com/v/C7JBx4PDBjw&hl=en_US&fs=1&rel=0&color1=0x3a3a3a&color2=0x999999" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="500" height="401"></embed></object></p><br />
<h3>Conclusions?</h3>
<p>Some in the Bay Area are claiming March 4 as a victory for radicals. An ambitious militant action succeeded in interrupting the daily routine, spreading a message about student struggles and the lengths to which some people are willing to go to confront the state. But if it was a success, it was certainly not without cost. There were about 160 arrests, and although the charges were mostly minor, processing them all will consume valuable resources. More significantly, one young man nearly died&mdash;proving right the speaker who warned protesters against joining anarchist-organized actions.</p>
<p>Whether or not this particular action was a success, the most important thing is to evaluate the strategic thinking behind it. Were anarchists successful in rendering revolt infectious on March 4, or were reformists and authoritarians able to marginalize it? What exactly are anarchists attempting to accomplish in the student movement? If we have concrete goals, are we making progress towards them?</p>
<p>In hopes of promoting further dialogue and reflection, we have composed the following discussion questions. We welcome responses&mdash;email answers to <a href="mailto:rollingthunder@crimethinc.com" target="_blank">rollingthunder@crimethinc.com</a> or post them in the comments section <a href="/blog/2010/03/09/march-4-anarchists-in-the-student-movement/">here</a>. We expect answers will vary from one community and vantage point to the next; the more, the better.</p>
<p>&nbsp;</p>
<p><a name="questions"></a>&nbsp;</p>
<h2>Anarchists in the Student Movement: Discussion Questions</h2>
<h3>I. Local Contexts</h3>
<p>-How much of the movement that led up to March 4 was anarchist-organized? What were the strengths and weaknesses of anarchist participation and initiatives?</p>
<p>-What were the dynamics between anarchists and authoritarians ahead of March 4? How did the two camps attempt to outflank each other to determine the tone of the actions?</p>
<p>-Which tactics have anarchists had the most success with&mdash;occupations vs. protests, spontaneous versus announced actions? What does this tell us about what anarchists are best equipped to do in this context? In what ways was March 4 conducive or not conducive to these approaches?</p>
<p>-How will the events of March 4 influence the development of the student movement? How is this fortuitous or problematic for anarchists?<br />
</p>
<h3>II. International Influences</h3>
<p>-How influential have overseas student occupation movements&mdash;the anti-CPE movement in France, university occupations in Chile and Greece and Austria, and so on&mdash;been in anarchist participation in the student movement?</p>
<p>-&quot;Public education&quot; is much different in the US than in any of the aforementioned countries: it&rsquo;s more expensive, and student bodies are thus very different in class composition. How does this affect US student movements?</p>
<p>-Likewise, although there was a powerful North American student movement in the 1960s, there is less continuity in student activism in the US than there is overseas&mdash;radicals have to reinvent the wheel every generation. Similarly, university grounds don't have legal &quot;autonomy&quot; the way they do in Greece, Chile, and Colombia; and unlike Chile and Greece, we're not coming out of a recent era of dictatorship, so non-students don&rsquo;t readily interpret student revolt as a struggle for everyone's freedom as they do in those nations. How can US anarchists inspired by overseas student movements go about offsetting these differences?</p>
<p>-What shortcomings do European/Latin American student movements have that US anarchists risk importing along with the models themselves? What have the limits of anarchist action in those contexts been?<br />
</p>
<h3>III. Strategy</h3>
<h5>So long as people assume that &quot;progress&quot; around the question of education can only come from the state, anarchists can either settle for being militant cannon fodder for a reformist movement, or risk enabling authoritarians to isolate them when it comes out that they are not interested in reform after all.</h5>
<p>-Anarchists have to find some &quot;ground&quot; to act from in a society in which there is practically no space in which anarchist values are legitimized or even understood. This creates paradoxical situations: for example, taking part in a student struggle &quot;for education,&quot; in a country in which the very concept of education has always been tied to the state. In what ways does participating in a student movement legitimize social structures, roles, and privileges that anarchists would otherwise set out to undermine? How can anarchists undermine these while finding common cause with those who&mdash;at least initially&mdash;desire to reform them?</p>
<p>-What are the goals of anarchists in participating in the student movement? To win the respect of others in the movement? To seduce them into anarchism, or into militant confrontations? To win actual concessions from the government? To have exciting adventures? To create unpredictable situations and/or autonomous zones?</p>
<p>-Let us hypothesize that the student movement is a strategic and opportune terrain for anarchists right now, in that students are suddenly facing significantly worse prospects than before: as a downwardly mobile class, students are likely to reassess their interests and consider new allegiances. In this context, is it more important to prioritize the circulation of anarchist <em>messaging</em>, or of militant <em>tactics</em>? Focusing on militant actions can reduce one&rsquo;s notion of success to getting to use one&rsquo;s preferred tactics, regardless of whether or not this helps foster long-term connections or critiques. Militancy itself can serve multiple masters: in other times and places, authoritarians have achieved their own ends by means of the same tactics US anarchists currently celebrate&mdash;so anarchists should not assume that others are on the same page with them just because they join in for confrontations. At the same time, without a clash, opposition to authority is mere empty rhetoric, and people are always more open to ideas and values that they have seen work. Is it possible to transcend this dichotomy between messaging and tactics?</p>
<p>-Let us further hypothesize that in the US, a movement about &quot;education&quot; is likely to play into the hands of statists, thanks to the common conception of education as something organized by the government or corporate entities. Using militant tactics to address the funding crisis (or that appear to address it, regardless of the participants' intentions) can win anarchists the attention of a broad range of people concerned about &quot;education.&quot; But so long as most people assume that &quot;progress&quot; around the question of education can only come from state action, anarchists can either settle for being militant cannon fodder for a reformist movement, or risk enabling authoritarians to isolate them when it comes out that they are not interested in reform after all. Is there a way out of this double bind?</p>
<p>-Let us hypothesize yet further that the actions that go well for anarchists are likely to be the ones initiated by anarchists, or else in conjunction with others who respect anarchists&rsquo; goals and autonomy. In such cases, anarchists more likely to succeed in determining the character of events, preparing a context conducive to autonomy and confrontation. This may explain why some of the occupations and more apparently &ldquo;spontaneous&rdquo; actions have given more space and opportunity to decentralized forms of resistance than large-scale events such as the permitted marches of March 4. Authoritarian and lowest-common-denominator organizations can more easily dominate the latter, both by literally laying the groundwork of what is to happen and by monopolizing legitimacy in the public eye by presenting themselves as &ldquo;the&rdquo; representatives of student protest. So long as anarchists remain on the margins of liberal and authoritarian organizing, organizing breakaway marches and the like, will lack of initiative and &ldquo;legitimacy&rdquo; in the public eye always impose structural limits on their efforts? Should anarchists seek more influence and legitimacy in the coalitions that organize major protests such as those of March 4? Or is it wiser to focus on developing a counter-power outside the coalitions, general assemblies, and mass actions?</p>
<p>-Anarchist critiques of the university tend towards calling for the <a href="http://news.infoshop.org/article.php?story=2009bricks-to-schools" target="_blank">&quot;self-abolition&quot; of the student</a>; this makes sense, insofar as the role of student, like every role in this society, maintains the reign of capitalism and hierarchy. At the same time, as students put this into practice (either by dropping out, or ceasing to organize as students in favor of organizing as anarchists), this abolishes the ground from which anarchists and others could act in the student movement in the first place. Does this mean that anarchist participation in student organizing tends to abolish itself before it can abolish anything else? What strategies could make the best of this internal contradiction?</p>
<p>-<a href="http://deluche.blogspot.com/2010/02/open-letter-to-white-student-movement.html" target="_blank">Controversy</a> after <a href="http://oaklandlocal.com/blogs/2010/07/why-did-march-980-freeway-happen-community-voices" target="_blank">controvery</a> has focused on anarchists&rsquo; alleged whiteness and maleness, alongside <a href="http://takethecity.wordpress.com/2010/03/08/a-response-to-the-lies-of-march-4th/" target="_blank">accusations that anarchists are outsiders and agents provocateurs</a>. The former allegation exerts disproportionate demands on queer anarchists of color, who often shoulder the burden of credibly <a href="http://occupyca.wordpress.com/2010/03/03/response-to-a-critic-of-the-&ldquo;white&rdquo;-student-movement/" target="_blank">responding</a>; the latter creates a narrative in which anarchists are always <a href="http://occupyca.wordpress.com/2010/03/07/raider-nation-collective-statement-on-the-m4-highway-takeover/" target="_blank">defending themselves</a> against accusations and responding with charges that authoritarians are attempting to undermine their organizing, a narrative that can itself serve to frame anarchists as distant from everyone else. The fact that liberals and authoritarians find it necessary to attempt to discredit anarchists at least indicates that they view anarchists as a potential threat; but these smear campaigns can cripple anarchists by separating them from the social base they need. Are there aspects of current anarchist rhetoric, organizing, or tactics that render anarchists particularly vulnerable to these charges? Are there ways in which outside anarchists actually are acting as provocateurs, seeing others&rsquo; struggles as a field in which to organize militant confrontations for their own sake without reference to the needs of those they claim to support? What can anarchists do to propagate a discourse that engages with oppression without lending itself to efforts to discredit resistance?</p>
<p>-What might a genuinely non-hierarchical approach to learning look like, entirely outside statist models for education? Why has there been so little concrete discussion of this question in reference to the student movement, even in anarchist circles?</p>
<p>&nbsp;</p>