<p align="center"><a href="http://thecloud.crimethinc.com/images/montreal/title2b.jpg" rel="lightbox[montreal]"><img src="http://thecloud.crimethinc.com/images/montreal/title2a.jpg" alt="While the Iron Is Hot: Anarchist Analysis of the Revolt in Québec" width="500" height="333"></a></p>
<h6 align="right" style="margin-right: 0px"><em>This is the second of a two-part series; for a chronological account of the events analyzed herein, read
<a href="/texts/recentfeatures/montreal1.php"><strong>While the Iron Is Hot: Student Strike &amp; Social Revolt in Québec, Spring 2012</strong></a></em></h6>
<p>To fill out our <a href="/texts/recentfeatures/montreal1.php">chronology</a> of the unrest in Québec, we posed the following questions to our Montréal correspondent, who answered them with the assistance of other participants in the <a href="http://www.quebecprotest.com/" target="_blank">Printemps érable</a>. The interview concludes with an epilogue bringing the action up to the minute, when a <a href="http://bloquonslarentree.com/" target="_blank">convergence</a> to block the resumption of the semester is about to begin.</p>
<p>It’s important to acknowledge that, while the strike has had effects throughout the province of Québec, our coverage focuses almost entirely upon events in Montréal. The strike has played out differently in this city, a multilingual and sprawling metropolis with dozens of overlapping anarchist scenes and a rich history of anti-capitalist resistance, than it has in the rest of the province. A large number of anarchists and other radicals inhabit a limited number of neighborhoods in a ring around downtown Montréal, making it an important flashpoint for struggle.</p>
<h2>How did militant street tactics develop and proliferate in the course of the strike? What can anarchists elsewhere in North America learn from this?</h2>
<p>Discussing the tactics that militants have employed in the streets of Montréal and elsewhere in Québec, and discussing how those tactics have changed, it is often said that tactics <em>escalated</em> over time, and whenever things were <em>pacified,</em> the implication is that the tactics were <em>de-escalated.</em> Entire demonstrations, some of which were extremely large, are described as <em>confrontational</em> or <em>non-confrontational.</em> This kind of language is woefully imprecise. These terms can communicate nothing more than a feeling, an ambience of the moment, leaving the specific mechanics of what was going on obscure.</p>
<p>This is not to argue that tactics can never be ranked in some kind of loose conceptual hierarchy, from those that are less effective at inflicting damage to property or those who defend it—and thus entail less risk—to those that are more effective and riskier. For example, from lesser to greater intensity:</p>
<p><strong>1)</strong> giving riot police the middle finger,<br />
<strong>2)</strong> throwing rocks at them,<br />
<strong>3)</strong> throwing Molotov cocktails at them.</p>
<p>That categorization is arbitrary and its variable, <em>intensity,</em> isn&#8217;t rigorously defined, but it can be useful to think about tactics in this way.</p>
<p>Compared to most North American cities, in Montréal, the use of certain tactics by street fighters—including anarchists, Maoists, and hooligans whose politics are less precisely defined—is more normalized, and less contested. This was true long before the student strike began in February. Black bloc attire and masks, constructing barricades or simply tossing traffic cones into the street, throwing rocks and other projectiles, breaking windows and looting stores… if a Montréal local hears that a hockey riot took place, she can make an educated guess as to which of these tactics might have been used before she gets the details. The same applies to days like March 15 and May 1, to reformist demos that anarchists deem worth intervening in, and to the spontaneous demos that have occurred after the police have murdered someone.</p>
<p>It is accurate to say that, over the course of the strike, a significant number of participants from diverse political backgrounds have escalated their street tactics to about the same level as those employed by the aforementioned anarchists, Maoists, and hooligans. Throughout February and March, as well as earlier demonstrations like the one on November 10, 2011, anarchists employing black bloc tactics or wearing masks were often the only ones physically confronting the police and destroying the property of capitalists, putting them at odds with many of the other people in the street and leaving them isolated. Later on, though the tension between pacifists and street fighters didn&#8217;t disappear, the street fighters were a lot more numerous and some of them were running around with giant fleur-de-lysé flags—a sure sign that others besides “the usual suspects” were taking the fight to the police.</p>
<p>On the other hand, it would be <em>inaccurate</em> to say that anarchists on the whole have escalated their practice of street fighting. Since the strike began, anarchists have been doing the same thing they always do, the difference being that they are doing it <em>more often.</em> Every year in Montréal there are reformist demos at which anarchists challenge the organizer-imposed code of conduct, anti-capitalist demos at which the only ones trying to impose limits on the actions of anarchist street fighters are the police, and spontaneous manifestations of rage when the police do something particularly heinous. The strike has caused all three types of events to happen with a much greater frequency than would otherwise occur, but the anarchist approach to each has been essentially the same.</p>
<p>As to being <em>confrontational,</em> it&#8217;s also inaccurate to say that the movement became more confrontational over time, because whether or not they were successful, there were attempt to blockade bridges and highways even in February and early March. What happened is that, in March, the congress of CLASSE made the decision to adopt a more confrontational strategy as an organization—after some of its constituent members had already been pursuing such a strategy for weeks. But this simply meant that there were more resources for those organizing confrontational actions, which is what led to a greater frequency and diversity of targets: the port, the government-owned alcohol distribution corporation&#8217;s depot, and eventually downtown skyscrapers and events like the Salon Plan Nord. On campuses, the intention of classroom and campus blockades was, from the very beginning in many places, <em>to let no one in for any reason whatsoever,</em> and people used whatever tactics were necessary for that purpose.</p>
<p>It’s possible to argue that, gradually over the course of weeks, militants selected targets and carried out plans more intelligently. But as to whether they were <em>trying to be more confrontational,</em> things were simply different at different times and varied between people. The truce between the CLASSE exec and the government, the loss of Francis Grenier&#8217;s eye, the experience of seeing police run in fear… all of these, in complex ways, affected the courage and rage of different participants in the movement and, at certain times, contributed to a more confrontational attitude.</p>
<p>All that said, there have been some <em>innovations</em> on the streets. For one, rather than always seeking out rocks and other projectiles, more street fighters have started to bring tools—hammers in particular—with which to make the projectiles out of Montréal&#8217;s crumbling streets. For another, street fighters have started counting down aloud in order to coordinate their efforts, whether before attempting to break out of a kettle—as succeeded on May 20—or hailing rocks upon police.</p>
<p>Another innovation has been shields, which hadn&#8217;t been seen much at demonstrations for at least several years before November 10, 2011. The most conventional shield format is to drill together a combination of plexiglass sheets, foam, cardboard, and chloroplast—the stuff from which election signs are made. The idea of painting them to look like the covers of politically solid books, from <em>L&#8217;insurrection qui vient</em> to <em>Nineteen Eighty-Four</em>, came to Montréal from Rome, where student demonstrators used the tactic during the anti-austerity demonstrations in late 2010. Although shields hold promise, especially if they could be made of sturdy, light materials like the shields of the insurgent strikers in northwestern Spain, their actual use has been hit-or-miss and it’s questionable how useful they would be in fast-moving demos on the streets of Montréal. They were useful on the open fields of Victo, and <em>would have been</em> useful on April 20 if anyone had brought them; on both those days, both sides were holding fixed positions, and there was less hand-to-hand combat and more use of rubber and plastic bullets. In a situation like May Day, on the other hand, it&#8217;s unclear how shields—which are not usually carried by the most muscular people—could have been useful against unrelenting waves of riot cops. Thus far, shields have been used primarily for symbolic purposes: they are most common at passive demos like the one on March 22, perhaps in an effort to add an air of militancy to the carnival of fleur-de-lysé flags and papier-mâché puppets.</p>
<p>There have also been interesting <em>developments</em> in how things tend to play out in the streets. Particularly after the passing of the Special Law, people in black bloc attire—and what the media has <em>presented</em> as black bloc attire, i.e., anyone wearing a mask and looking vaguely “anarchist”—have frequently been approached by others in the streets and offered praise: “You’re so brave to be doing that kind of thing.” There is now a much greater degree of solidarity between people who are dressed to fight and those who aren&#8217;t, with several instances of unmasked people putting themselves at risk in order to pull their street fighter comrades out of the clutches of the police. There is even a sports-fan-style chant—<em>ALLEZ LES NOIRS!</em>—which literally (and atrociously) translates into English as “go blacks!” Crowds of hundreds have chanted these words at the tops of their lungs.</p>
<p>It is now widely understood that it is a good idea to build barricades in almost any situation. This has occasionally resulted in <em>very good</em> barricades consisting of huge amounts of debris, construction material, loose furniture from nearby cafés, and—more and more frequently—fire. However, more often, people simply drag an item or two into the street and no one else joins in. Sometimes, people dump garbage into the streets not even to find projectiles, but seemingly because they believe this will magically obstruct police vehicles. Not taking the time to build effective barricades, or not being able to get others to help you do this, is one thing. Doing something that has no effect on the police while making the streets more disgusting for the people who live there, unnecessarily annoying them in the process—that’s another thing entirely!</p>
<p>Riot police are able to mount their interventions because they can move freely through side streets, but a more widespread practice of erecting strong barricades in a march&#8217;s wake would not only interfere with the normal functioning of capitalism—it would make successful police interventions much harder to pull off, especially as the demonstration&#8217;s speed increases. Montréal would be a good place to import tactics used by street fighters in many major European cities: flipped dumpsters and luxury cars pulled or pushed into the street could obstruct police far more effectively than a few traffic cones.</p>
<p>There has also been an increased use of Molotov cocktails, nearly unheard of in street confrontations in North America for a long time. Their use has been sporadic, and it&#8217;s unclear what conclusions can be drawn here. It’s worth noting, in any case, that <em>some</em> people are now willing to take things to that level.</p>
<p>At first, very few people wore masks or goggles in the streets, but the experience of police brutality and CLASSE&#8217;s explicit call for direct action and economic disruption changed that very quickly. What had always been a small minority became the majority of the participants in many demos. All it took was a critical mass of people in March and April, augmented by efforts to vocalize support for normalizing the practice, whether via the distribution of texts or in CLASSE&#8217;s explicit endorsement of March 29&#8217;s Grande Masquerade.</p>
<p>In addition to the explosion in the use of masks and goggles, there has also been a significant increase in the use of black bloc attire by other militants at a time when many more experienced street fighters have begun opting for “light bloc” instead. “Light bloc” means wearing different clothes than one normally would and concealing one’s face and other identifying features, but not attempting to achieve a uniform look, in hopes that individual criminal acts won’t be attributed to anyone who is caught if arrests take place before the crowd de-blocks. The reasoning is that light bloc enables street fighters to disappear into a diverse crowd more effectively than black clothing, keeps street fighters from appearing as outsiders, and doesn&#8217;t attract preemptive police attention. A lesson that many local anarchists drew from March 12, 2011—when individuals in black bloc attire were targeted and arrested pre-emptively—is that one should be skeptical of overusing or fetishizing the black bloc tactic. Many had been skeptical before that, but afterwards, black blocs practically disappeared until February 2012, whereas they had previously been a regular feature at anti-capitalist demos.<a class="footnote" href="javascript:void(0);" onclick="return overlib('The only notable exception was the night of June 7, 2011, when a spontaneous anti-police demonstration took place in response to the shooting of two people in downtown Montréal the previous night.', CAPTION, '[1]');" onmouseout="nd();">[1]</a></p>
<p>Some experienced street fighters in the anarchist milieu have been critical of the recent propensity to habitually wear black in the streets, echoing <a href="anarchistnews.org/node/16910" target="_blank">constructive criticisms</a> that followed the attempt at a general strike in Oakland on November 2, 2011. This habit distinguishes street fighters from those around them—arguably inhibiting confrontational behavior from spreading—without significantly improving anyone’s ability to confront the police, since there is ample evidence that people can break the law and get away with it whether or not they wear black. Because street fighters in this city are frequently terrible at keeping tight, it is not uncommon for isolated individuals wearing black to be dispersed throughout the crowd, creating an unnecessarily dangerous situation.</p>
<p>Finally, there still isn&#8217;t a lot of communication between fighters in the street. People stick to their own crews for the most part; different crews rarely stay tight for very long in a moving demo, and it&#8217;s possible that many fighters don&#8217;t know what to say to others they see in the streets or else they don&#8217;t know how to say it. Even though it is clear that spreading information is important, it is almost certainly unclear what information needs to be spread at any moment, and the reality of social awkwardness is undeniable. As in a bar or at a party, people tend to stick to their friends rather than venturing out to meet new people.</p>
<p>This is all improving, albeit too slowly. One shift is that now, when fighters throw rocks at windows when people are on the other side of the glass, others more often approach them to suggest they use a hammer or metal garbage bin instead. When some throw from the back, others make a point of explaining that it&#8217;s better to go to the front to ensure that only the intended damage is done.</p>
<p>There is also increasing debate as to whether the small economic damage caused by petty property destruction is worth it. Ultimately, of course, individuals will decide for themselves. This debate echoes the allegation that some anarchists tend to measure the success of an action <em>only</em> by counting how many windows were broken, how many police vehicles were torched, and so on. In any case, by such a standard, the strike has been an unqualified success. Rather than critique those who might think this way—or the ones who construct this straw man caricature—we could just accept that there are valid reasons to applaud damage to the property of capitalists, and acknowledge that wider and more frequent use of the tactics that can accomplish this—as seen in Montréal since February—is a laudable objective.</p>
<p>So now that we&#8217;re deep into abstract hypothesizing, how might anarchists see the kind of mayhem that has recently swept Montréal in their own cities?</p>
<p>There is no easy answer. In Montréal, certain anarchists have been pushing for years to make sure that demonstrations transgress the limits imposed by the state—chiefly by the police—and sometimes also by organizers, movement politicians, and peace police. It is important to understand this as an <em>infrastructural</em> project. It involves procuring and constructing materials, gathering and disseminating information, laying plans and developing strategic acumen. All this organizing creates and replicates a tradition: confrontation with the police is now <em>normalized</em> in Montréal, more so than in most North American cities. But as much effort, energy, and passion as this has required, the reality is that Montréal&#8217;s political culture, which differs from any neighboring city, has made this process easier. This culture could not exist if not for Québec&#8217;s unique history over the last fifty years; it cannot simply be replicated elsewhere.</p>
<p>Wherever a militant political culture comes from, however it is cultivated, it is important for anarchists to reach out to those who show themselves willing to fight. In Québec, that includes the students, specifically the students who have engaged in some way in CLASSE&#8217;s campaign against the government. In many other parts of North America, it seems that—however <em>politicized</em> they might be—university students on the whole are rarely willing to translate their politics into any kind of action that might adversely affect their career prospects or weekend plans. If anarchists elsewhere—many of whom are students themselves—want to see their own towns erupt like Montréal has, perhaps they should start making connections with folks whom it might be a little harder to relate to, at least initially.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/montreal/72b.jpg" rel="lightbox[montreal]"><img src="http://cloudfront.crimethinc.com/images/montreal/72a.jpg" width="500" height="345" style="margin-bottom: 5px"/></a></p>
<h2>What forms has state repression assumed, and how have participants countered it?</h2>
<p>The natural response of the state to resistance is repression. In Québec, there has been resistance at many different levels, and accordingly repression has taken a variety of forms.</p>
<p>We can designate three categories of repression here: the tactics school administrators have used to dissuade students from doing anything inappropriate; the physical violence the SPVM and the SQ have employed against people in the streets; and the conditions that Québec&#8217;s judiciary, in collaboration with the police and the government, has used to prevent people from taking action again in the future.</p>
<p>The politics of the administrators vary from school to school. While many schools—especially the anglophone institutions—are governed by decided neoliberals, it is possible that some administrations are more <em>left</em> in some sense of the word. Regardless, on the whole the administrators have chosen to do their job: to control and suppress any tendency towards direct action among their students. Some have done this job less enthusiastically and less effectively, but they are not our allies—far from it.</p>
<p>Many schools have threatened students with a variety of academic consequences and other punitive measures, ranging from expulsion to a certain amount of community service. These measures include failing kids, expelling them, firing them from university-paid jobs, temporarily banning them from campus, and fining them—in short, pushing them out, or else pressuring them to drop out of their own accord. As one of the goals of the austerity measures is to shrink the postsecondary education systems that are exerting a net drain on capitalist economies worldwide, any drop in student enrollment is welcome. The university can inflict less pain than the courts, but administrators—whose role is comparable to the role of the police, in that it involves maintaining the normal functioning of capitalism—have frequently collaborated with police investigators to bring criminal charges against militants. Their actions impact people&#8217;s family lives, their pocketbooks, and in some cases their legal status in Canada. Even bearing in mind our critique of schools and the soulless middle-class lives that academics lead, it should be clear that it is unacceptable for people to be denied control of their destinies by these petty authority figures.</p>
<p>Several schools, in particular Concordia and McGill, spent hundreds of thousands of dollars on extra security to protect their campuses. On the topic of private security, there was often rhetoric to the effect that private security are not our enemies the way police are, that a lot of them are hard-working immigrants just doing their jobs, and picking fights with them isn&#8217;t a good idea. This is ridiculous. Private security goons have been instrumental in gathering intelligence for administrations and for the police—and like the police, they frequently hurt people and get away with it.</p>
<p>Now let’s discuss the repressive tactics of the police.</p>
<h5>“We are not for the establishment of a police state; we know that it is necessary to work with the population and create links. But there are groups for that. <strong><a href="http://zeroanthropology.net/2009/03/18/our-job-is-repressionthe-police-is-a-paramilitary-organization" target="_blank">Our job, as police officers, is repression.</a></strong> We do not need a social worker as a director, we need a general. In the end, <strong>the [SPVM] is a paramilitary organization</strong>—let&#8217;s not forget it.”</h5>
<p>These are the words of Yves Francoeur, the director of Montréal&#8217;s police union, <a href="http://fr.canoe.ca/infos/chroniques/richardmartineau/archives/2008/08/20080821-052600.html" target="_blank">spoken in 2008</a> during <a href="http://fr.wikipedia.org/wiki/%C3%89meute_de_Montr%C3%A9al-Nord" target="_blank">a rebellion in Montréal-Nord</a>. Considering that worker-employer relations couldn&#8217;t be better at the SPVM, one can imagine that this statement reflects the entire leadership&#8217;s understanding of their role. From the very beginning, and even before the strike began, Montréal&#8217;s police force has approached the student movement with a counterinsurgency strategy.</p>
<p>According to the conceptual hierarchy of British imperialist <a href="http://libcom.org/library/low-intensity-operations-subversion-insurgency-peacekeeping" target="_blank">Sir Frank Kitson</a>, an insurgency has three stages. In the first stage, it poses no real threat and is only potentially insurgent; in the second stage, it disrupts the economy but is not genuinely threatening; only in the third stage can it actually threaten the government. The proper approach for a counterinsurgent force is to comprehensively surveil the movement while it is in the first stage, and its security practices are not very developed, in order to prevent it from reaching the second stage, then destroy it ruthlessly if does reach the second stage, in the hopes of preventing it from ever threatening the security of the state.</p>
<p>In 2012, the movement advanced from the first stage of Kitson&#8217;s hierarchy to the second stage. The response of the SPVM has been somewhat more constrained than Kitson deemed appropriate for British subjects in India, Ireland, and Malaya. This is likely because, unlike colonial police forces, the police in Montréal often need to get people in elected office and the judiciary to support their plans—and the latter are often less strategically astute. Still, from the very beginning, the objective of the police has been to destroy the power of the movement. Two of the sources of the movement&#8217;s power are, first, the numbers of people willing to take the streets and, second, the willingness of many of those people to transgress the limits imposed on protest. The approach of the police has been to dissuade people from doing certain things and, knowing the importance of picking battles, to dissuade people from <em>attending</em> demonstrations where those things happen, while permitting people to attend more passive demos.</p>
<p>Perhaps, early in the strike, the police were <em>a little bit</em> restrained when it came to dealing with the students. It’s pointless to make assumptions about the collective psychology of the SPVM, but they may have genuinely believed that most students were good citizens and the unrest was only anarchist infiltrators instigating things. This changed quickly. The student movement, rather than collaborating with the police, chose to accommodate troublemakers; very soon, anyone wearing the red square could be appropriately treated as a troublemaker.</p>
<p>Physical violence, whether tactical or just the kind of generalized asshole behavior exemplified <a href="http://www.youtube.com/watch?v=ukHSEMptUaU&amp;feature=plcp" target="_blank">in this video</a>, is one way to get people off the streets. Police made heavy use of pepper spray and baton attacks throughout the strike. Flashbangs were an early addition that quickly came to characterize almost every demo; plastic and rubber bullets have been used more sparingly. Over time, the authorities shifted from trying to contain demos towards actively attacking them via police charges. Relentless offensives, like the one seen on May Day, have been rarer.</p>
<p>There have been multiple reports of male police molesting female arrestees. They routinely subjected arrestees to as much pain as possible; when searching people&#8217;s bags, they would open bottles of lemon juice or water and pour them over the other contents of the bag. Much of this sort of thing has been caught on tape, but the SPVM has a good PR position and a cozy relationship with the mainstream media. The fact that videos exist on YouTube doesn&#8217;t mean that anyone is going to see them, and it seems that only those who already hate the police seek them out. In any case, there is strong support from a certain portion of the population for “giving CLASSE-holes what they deserve,” and if the police get a reputation for being brutal and unpredictable, all the better for them.</p>
<p>In comparison to the rhetoric coming from Toronto&#8217;s police after the G20 summit or the Vancouver police after 2011&#8217;s hockey riot, the SPVM&#8217;s spokespeople have rarely said anything to the effect of “we will catch everyone.” They know that would be an impossible task. Instead, they imply that they will <em>punish</em> everyone. Everyone who takes to the streets will suffer for it, one way or another.</p>
<p>In addition, a few people have been specifically targeted for attack, with the full cooperation of the Crown (the government prosecutors) and the media.</p>
<p>Emma Strople, who was initially arrested and charged during the Grande Masquerade on March 29, was specifically targeted during on the nights of April 24 and April 25, the first two night demos. As the police arrested her, far from the demo which she had left before it had been declared an illegal assembly, they explained that they had it out for her and they were going to make her life hell.</p>
<p>Police raided the homes of Roxanne Bélisle and François-Vivier Gagnon—two of the four people who turned themselves in to police custody soon after their faces were published by the media, described by the police as wanted in connection to the May 10 smoke-bombing incident. Yalda Machouf-Khadir&#8217;s house was also raided. The police conducted a search for black clothing and items that could link her to the attack on Line Beauchamp&#8217;s office on April 13 or the events at the Université de Montréal the day before; they ended up mostly confiscating anarchist literature and anti-police flyers.</p>
<p>On June 11, one militant who had been dealing with problems unrelated to politics—he had been the first to discover the lifeless body of his sister after she had committed suicide—was arrested while driving from Montréal with his family to attend his sister&#8217;s funeral in the Saguenay. It is widely understood that the SQ, who pulled over the car on the highway about a half-hour&#8217;s drive from the island, knew his situation and pulled him over at the worst possible moment in order to get him to cooperate, promising that he might still be able to attend the funeral if he did so.</p>
<p>These are isolated and particularly egregious incidents. More common behaviors include surveillance of “prominent activists”—although there are far too many of those for it to be an easy task—the application of non-association conditions or conditions that restrict a person&#8217;s ability to participate in demonstrations, and a condition that has so far been applied only to Emma Strople and two others: exile. These three people are banned from the judicial district of Montréal—corresponding mostly with the Island of Montréal—for any purpose other than going to court. All three are people who have lived here for years. And even before they could get release conditions, however oppressive, many people have been denied bail and held in jail for periods of up to a few weeks.</p>
<p>On the streets, the police have deployed undercovers, sometimes in very large numbers, to facilitate the arrests of troublemakers—and possibly to gain control of the front of demonstrations to lead them in a direction that is favorable to police strategy, although this is difficult to confirm and may just be paranoia on the part of some militants. There will typically be more than one group of undercovers in any given demo, with at least one group trying to gather intelligence on those who are causing trouble and keep track of their location. A different group will follow them out of the demo, and often a third group will make the arrests. There is evidently a growing concern on the part of the SPVM, however, that their undercovers may be recognizable and could risk serious physical harm in the streets.</p>
<p>Anarchists have responded to all this in a number of ways, if inadequately. One thing anarchists have done well is to continue the tradition of prison solidarity noise demos, facilitating many more people participating in them. On March 29, there was a manif-action that disrupted the normal proceedings at the Palais de justice (yes, <em>the Palace of Justice</em>) in solidarity with those facing charges related to the occupation at Cégep du Vieux. On April 28, there was a solidarity demonstration of about 75 people at Tanguay Prison for Women, where Emma Strople was being held at the time; this was probably one of the bigger noise demos that had happened in Montréal up to that point. On May 16, there was a larger demonstration, consisting of over 100 people, expressing solidarity with three of the four people being held there in relation to the May 10 smoke-bombing—Geneviève Vaillancourt, Vanessa l&#8217;Écuyer, and Roxanne Bélisle—as well as every other victim of police and judicial repression over the course of the strike.</p>
<p>Despite these efforts, the response by anarchists—and by the movement overall—has been severely lacking. There has been no consistent campaign to disseminate information about the ones who currently face the harshest consequences of anyone in the movement. There has been no message to the effect that, if the authorities can get away with persecuting these people, that will empower them to do the same to everyone else. In addition, there has been very little in the way of response to those parasites upon the movement who denounce the ones who take greater risks or who, in positions of power, fail to take any action in their defense. The only thing that has happened is that, on a few isolated occasions, some brave people have endeavored to avenge wounds inflicted on their comrades—as on the night of March 7, when militants took to the streets to avenge Francis Grenier&#8217;s eye in the first night demo of the strike—and there have been demonstrations at the courthouse and prison in solidarity with comrades entangled in the criminal justice system. Both of these are good. Passion is important. But we need a strategy that can actually support these people, building a movement around them that will threaten our enemies and dissuade them from trying to do the same thing to anyone else.</p>
<h2>How were decisions made throughout the strike? How did anarchists engage with these processes or intervene in them? What has been <em>anarchist</em> in decision-making throughout the unrest?</h2>
<p>Whether they are manifested as the direct democracy of general assemblies, the representative democracy of certain states, or something else, <a href="http://www.crimethinc.com/blog/2012/04/29/poster-series-what-does-democracy-mean/">democratic ideals</a> are inherently authoritarian and contrary to projects of liberation. This has been argued effectively <a href="http://www.crimethinc.com/texts/atoz/barc.php">elsewhere</a>. One has to understand this principle to understand anarchist participation in the strike.</p>
<p>There is a powerful tradition of direct democracy on francophone campuses. Directly democratic decision-making processes were a key component of the leftist social movements that challenged the state in the 1960s and, among other things, forced the creation of the cégep system and the Université du Québec. In the years after the so-called <a href="http://www.thecanadianencyclopedia.com/articles/quiet-revolution" target="_blank">Quiet Revolution</a>, the new Québécois welfare state&#8217;s political class successfully bureaucratized labor unions and community-initiated health clinics; the people in power distrusted the population&#8217;s ability to make decisions for itself. Such bureaucratization was much less successful in the schools, though, as professors continued to engage in radical politics and students developed autonomous and militant political cultures. This was particularly true of schools in and around Montréal.</p>
<p>It is broadly agreed among students that a widely publicized general assembly is the highest authority regarding what students should do in a strike, including what can legitimately be done to school buildings. If a general assembly votes for a strike, every student is obliged to go on strike. If there is a vote that a building should be occupied, many consider it indisputable that this should happen. Student associations and highly partisan professor faculties, as institutions, have reinforced these ideas with their propaganda and the lessons they teach in classrooms.</p>
<p>But there is opposition to these ideas from within the student milieu, most visibly from students who support Charest&#8217;s tuition hikes—some of whom wear a green felt square in protest of the strike. They are roughly equivalent to Young Conservatives or Young Republicans in other parts of North America, the sort of people who would argue that “most students are leftists by default” and that the <em>truly</em> radical position to take on campus would be to support—wait for it!—<em>fiscal responsibility.</em> Echoing the Liberal Party leadership, they usually rail against general assemblies for two reasons: first, because they don&#8217;t conduct secret votes, so anti-strike students are made to feel intimidated for expressing their unpopular opinions; and second, because GAs have deemed themselves unaccountable to the rule of law.</p>
<p>Anarchist critiques of general assemblies are currently less visible—and, frankly, less coherent. Generally speaking, we have been arguing since at least the beginning of Occupy Montréal, in October 2011, that general assemblies should be spaces for communication and logistical coordination, not sources of legitimate authority. Some anarchists, however, often justified their actions during the strike as being consistent with the democratic decisions of certain student associations’ GAs. This is particularly common during hard pickets and other disruptive actions at schools, when anti-strike students and faculty and pro-strike students and their supporters (including anarchists) have often found themselves talking or yelling at each other.</p>
<p>Perhaps some anarchists don&#8217;t see the contradiction here, or perhaps they are using words cynically to achieve an objective, such as trouncing the green squares in an argument. Either way, this much is clear: these situations aren&#8217;t the easiest venue in which to introduce a more nuanced anarchist perspective, especially when that perspective is that those who identify with different interests in the social war are irreconcilable enemies. But if we are anarchists, and that is what we really think, then we should say it!</p>
<p>Anarchists who happen to be students have been the ones who engaged most earnestly in general assemblies, sometimes going so far as to “rock the vote”—spending precious hours of their lives convincing people to show up to the GA to vote in a particular way. This might seem an even more glaring contradiction, but there is a qualitative difference between this kind of activity and, say, campaigning for a nominally more left-wing political candidate. Even if anarchists reject everything that makes them significant, successful strike votes have a <em>social effect</em> that creates a space where student anarchists can engage in the struggle—by going to demos, distributing literature, sabotaging public transportation systems, and so on—rather than worrying about their studies.</p>
<p>This, at least, was the theory. Yet successful strike votes have not protected students from collective punishment in the form of a forced return to class or the threat of losing their semester—something that is <em>expensive,</em> if nothing else.</p>
<p>Initial anarchist attempts to organize their own GAs, starting in the few weeks before the strike began, did not work out as intended. The idea was to bring anarchists from Montréal&#8217;s myriad scenes together, to determine what different people were doing so as to coordinate <em>action</em> in a strategic way. These were not <em>open</em> assemblies; as a result, they were poorly attended, few people showed up consistently, and they weren&#8217;t very productive. Most anarchists found that it was more rewarding to spend their time and energy outside of these assemblies, and it’s hard to blame them.</p>
<p>It is easy enough to say that if only anarchists had dedicated more energy to this process of getting to know each other and figuring out how to cooperate, they could have had a more sustained and measurable effect on the strike. But the simple fact is that people weren&#8217;t ready to come together at that time, and they still aren&#8217;t. Montréal&#8217;s street fighters are segregated into a variety of cliques; putting an end to this segregation will be a slow process, if it is possible at all.</p>
<p>More recently, since the beginning of the summer, CLAC has attempted to organize anti-capitalist assemblies as spaces of communication. This is a good effort; so far it has produced some good results, including more anti-capitalist contingents at “national” demonstrations and more anarchist outreach such as the campaign against the elections.</p>
<p>Anarchist intervention in neighborhood assemblies—many of which were initiated by anarchists—holds the most promise. Every neighborhood assembly is different, but many of them—including Mile End, Saint-Henri, Pointe-Saint-Charles, Mile End, Hochelaga, and Villeray—have significant numbers of anarchists participating. They point to a different type of organizing, rooted in the immediate and pragmatic aspects of struggle rather than presumed ideological common ground.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/montreal/74b.jpg" rel="lightbox[rosefire]"><img src="http://cloudfront.crimethinc.com/images/montreal/74a.jpg" width="500" height="333"/></a></p>
<h2>Epilogue: Preparing for the Next Round</h2>
<p>The strike is not over, so this report can have no tidy conclusion. Starting after the Grand Prix weekend, when we began writing, the movement&#8217;s street presence has died down apart from a few events, but there have been developments on other fronts. Militants have traveled far and wide to spread news of the struggle in Québec to other parts of the continent. CLASSE has organized strategic consultas in just about every significantly populated place in Québec, as well as several cities in Ontario. The premier has called an election. Autonomous anti-capitalists have made their own call: from August 13 to August 17, they want people to come to Montréal and help to sabotage the start of the special semester stipulated in the Special Law—as many as ten weeks&#8217; worth of classes crammed into five, and the last chance that the government is offering to students at striking schools to make up the semester that was first extended into May because of the strike and then canceled altogether by decree.</p>
<p>Although it is the official policy of CLASSE to defy the Special Law—which has yet to be applied to militants as of this writing, despite being on the books for over two months—it seems that the organization is keeping back from organizing, demonstrations, or other actions to block the <em>rentrée,</em> the return to classes. This is sensible for their part, and probably useful to anyone who will need legal support. CLASSE has a lot of money, but its access to that money is precarious, and it’s all too likely that violations of the law would be punished by an asset freeze or fines imposed by automatic withdrawal. This is not to say CLASSE is shying away from opposing certain provisions of the new law. It will continue to organize disruptive demonstrations that do not collaborate with the police, though it&#8217;s likely that these demonstrations will target institutions other than schools.</p>
<p>Over the summer, CLASSE has focused on bringing its message to the people of Québec and the students of Ontario. From an anarchist perspective, this message can be charitably described as inadequate. The coalition&#8217;s new manifesto, <a href="http://www.stopthehike.ca/2012/07/share-our-future-the-classe-manifesto/" target="_blank">“Share Our Future”</a>—the English translation of which makes the scrappiest Montréal anarchist translation job look pretty damn good—includes some tokenistic references to marginalized elements in our society and other issues that anarchists in particular pushed to include, but that&#8217;s it. Worse, instead of sounding passionate, it sounds like precisely what it is: the product of a consensus process among people whose politics and strategic approach vary widely. Consequently, it is a litany of lowest common denominators, not an inspiring call to arms.</p>
<p>In the meantime, the election is on, and Pauline Marois, leader of the <a href="http://en.wikipedia.org/wiki/Parti_Qu%C3%A9b%C3%A9cois" target="_blank">Parti Québécois</a>, is doing her best to divert the power of the strike movement into her election campaign. She and her star candidate Léo Bureau-Blouin, who was president of FÉCQ until June, have kindly asked the student movement not to cause trouble during the campaign, arguing that disruption will play into the Liberals&#8217; re-election strategy. And it probably will, but that <em>doesn&#8217;t matter.</em> If the strike movement does not effectively sabotage the special semester, those who refuse to go to class will suffer the consequences and the movement&#8217;s <em>rapport de force</em> with whichever government comes to power on September 4 will be significantly diminished. A large segment of the movement thinks the most important thing is to drive Charest from power—when, in fact, the most important thing is for the movement to become confident of <em>its own power.</em></p>
<p>Student associations at a few schools have already voted to comply with the rentrée. Others, like the one at Cégep du Vieux Montréal—which, in the spring, voted to remain on strike until free education is realized in Québec—are going to fight it out.</p>
<p>For its part, CLAC has launched an anti-electoral propaganda campaign and disseminated a call for three demonstrations: one for the day that the election is announced; one for the leaders’ debate, although apparently there will be several; and one for the day of the election itself.</p>
<p>It is unclear what the plan is for the first week of the <em>rentrée,</em> but a <a href="http://bloquonslarentree.com/en" target="_blank">multilingual website</a> has been set up to inform people of the plan as it is determined. There are three cégeps opening up on August 13 and fourteen in total for the week, but whether or not the student associations at each of those schools will have decided to renew their strike mandates on August 10 is unclear. <a href="http://backtostrikemtl.com/" target="_blank">Another website</a> has been set up to arrange housing and transportation.</p>
<p>There have been two “national” demonstrations since the Grand Prix, one on June 22—a small and passive event of less than 100,000 people—and another on July 22, which was a little bit bigger and a little more exciting. An anti-capitalist contingent broke off from the main march in defiance of bylaw P&#8211;6 and the Special Law, although the militants involved did nothing more than disrupt traffic.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/montreal/75b.jpg" rel="lightbox[montreal]"><img src="http://cloudfront.crimethinc.com/images/montreal/75a.jpg" width="500" height="138" style="margin-bottom: 5px"/></a>
<em>July 22 demonstration in Montreal: quiet, but with lovely banners. The one on the left reads: “To vote is to abdicate. To abstain is to struggle.”</em></p>
<p>On the morning of August 1, Jean Charest announced the 40th Québécois general election. Incidentally, this was also the night of the 100th consecutive night demonstration, and both the student federations and the neighborhood assemblies had planned to give the demonstration more life than it had possessed in some time. Assemblies based in the neighborhoods to the north and the east of Berri Square organized marches that gathered more people as they passed through each neighborhood until they reached the square.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/montreal/76b.jpg" rel="lightbox[montreal]"><img src="http://cloudfront.crimethinc.com/images/montreal/76a.jpg" width="500" height="333" style="margin-bottom: 5px"/></a>
<em>On the 100th night of night demos: “<a href="http://en.wikipedia.org/wiki/Villeray,_Montreal" target="_blank">Villeray</a> disobeys.”</em></p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/montreal/77b.jpg" rel="lightbox[montreal]"><img src="http://cloudfront.crimethinc.com/images/montreal/77a.jpg" width="500" height="333" style="margin-bottom: 5px"/></a>
<em>The neighborhood contingents approaching Berri Square on August 1.</em></p>
<p align="center"><iframe src="http://player.vimeo.com/video/47366428?byline=0&amp;portrait=0&amp;color=898900" width="500" height="369" frameborder="0" style="margin-bottom: 5px" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
<em>After a passive summer, things are heating up again.</em></p>
<p>There were clashes with police. Bank windows were smashed out and dumpsters dragged into the streets. The police deployed their usual weapons: batons, pepper spray, flashbang grenades. A total of 15 people were arrested. The struggle continues.</p>
<h2>Further Reading</h2>
<p><a href="http://grevemontreal.noblogs.org/" target="_blank">Grève Montréal</a><br />
<a href="http://mtlcounter-info.org/" target="_blank">Montréal Contre-information</a></p> 
<p>&nbsp;</p>
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1] The only notable exception was the night of June 7, 2011, when a spontaneous anti-police demonstration took place in response to the shooting of two people in downtown Montréal the previous night.</p>
</div>