<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/1d.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/1a.jpg" width="500" height="372"/></a></p>
<p>The crisis continues. This isn&rsquo;t just a hiccup in the market, but a structural breakdown. A system driven by competition for ever-increasing profit can&rsquo;t run indefinitely; sooner or later everything that can be commodified has been drawn into the market, all the capital accumulates in a few hands, and the profits dry up.</p>
<p>Today the factories of every industry produce commodities more and more efficiently via automation that renders workers increasingly redundant. The only way to profit on these commodities is to cut costs: to eliminate workers or pay them next to nothing. But without work or wages, people can&rsquo;t play their part as consumers. The only job openings are with the police, who wage a never-ending war on the population to control the poor and unemployed. This is why our world is overflowing with cheap shit, with human life cheapest of all.</p>
<p>As commodities get cheaper and consumers get poorer, how can capitalists continue making a profit? Credit was invented as a way for consumers to go on shopping even when they weren&rsquo;t paid living wages. When the sale of real goods can no longer produce profit, profits must be made on expected future returns&mdash;in other words, on speculation.</p>
<p>But like any house of cards, debt can&rsquo;t be built up forever&mdash;eventually someone calls it in. The house of cards collapsed under its own weight in 2008 when it became clear that the expected future returns could never materialize. Rather than reconsidering their faith in capitalism, the authorities are now gutting the last vestiges of the support structures established to pacify the old labor movement, feeding every last stick into the fire.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/2b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/2a.jpg" width="500" height="767"/></a></p>
<p>The financial crisis signals a deeper metaphysical crisis: this system, which perpetuated itself by creating unfulfillable emotional needs, cannot provide for the global population&rsquo;s material needs either. The high rates of unemployment from Egypt to the US are not simply caused by the corruption of despots like Mubarak, nor the greed of specific capitalists; they are evidence that a system that never worked for us is on the verge of ceasing to work at all.</p>
<p>In response, some hope to resurrect social democracy. But wasn&rsquo;t it social democracy that neutralized the resistance movements of the 20th century, while building up a state powerful enough to impose the current inequalities? Democracy has always been the guardian of capitalism, giving the greatest possible number of people reason to invest themselves in hierarchies and coercive institutions, equating freedom with property rights. If capitalism is doomed, we need something altogether different&mdash;the truth is, we always did.</p>
<p>Capitalism won&rsquo;t crumble overnight. Its rituals and values are so deeply ingrained in us that its demise could take generations, and it might give way to something even worse. If we want to have any influence over what comes next, we have to pose the right questions with the ways we fight and the narratives we propagate. Here we&rsquo;ll trace the trajectory of popular struggles against austerity and capitalism around the world across 2010 and 2011, identifying their limitations so as to push further next time.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/3b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/3a.jpg" width="500" height="500"/></a></p>
<h3>Pitfalls and Paradoxes: The Student Protests of March 4, 2010</h3>
<p>The economic crisis that entered the public consciousness in 2008 prompted governments to inflict massive cutbacks on public education. The student movement that began in December 2008 with the occupation of the New School in New York City&mdash;itself a private school&mdash;intensified with a series of protests and occupations throughout fall 2009, principally in California.<a class="footnote" href="javascript:void(0);" onclick="return overlib('See <em>Rolling Thunder</em> #9.', CAPTION, '[1]');" onmouseout="nd();">[1]</a> These culminated in nationwide demonstrations on <a href="http://www.crimethinc.com/texts/recentfeatures/march4.php">March 4, 2010</a>. The Bay Area was the epicenter of this day of action, with tens of thousands in the streets; but at this epicenter, the contradictions within the movement came into stark relief.</p>
<p>While anarchists had been at the forefront of the occupations, reformists took the lead in organizing for March 4, planning a standard march and rally. They also attempted to seize control of the narrative. A week before the day of action, a dance party at UC Berkeley turned into a small-scale riot as students took the streets, mingling with non-students and defending themselves against police attacks. There were only two arrests, but afterwards liberals and leftists alleged that outside agitators were attempting to hijack the movement&mdash;a story some had been repeating for months, which has become all the more familiar since.</p>
<p>As in <a href="http://www.crimethinc.com/texts/recentfeatures/whattoexpect.php#historical">the anti-war movement</a> seven years earlier, anarchists had largely limited themselves to escalating the <em>tactics</em> of the student movement. Most militant actions were organized informally, and there was neither an autonomous body for coordinating these nor a voice for them in the organizational structures of the larger movement. This opacity offered the element of surprise, but it ultimately enabled reformists to outflank radicals by dominating the public discourse and planning actions that were unfavorable for confrontation. Likewise, because anarchists weren&rsquo;t able to popularize a narrative identifying the student movement with the larger struggles of the disenfranchised, most people took it for granted that the point of the struggle was simply to get more funding for public education. Consequently, it was difficult to legitimize the participation of non-students except as passive &ldquo;allies,&rdquo; let alone make a case for a struggle <em>against</em> government.</p>
<p>On March 4, a march of several thousands departed from Berkeley towards Oakland. Student organizing groups jockeyed with black-clad militants for the lead. The march joined younger students and teachers in downtown Oakland for a rally at which the usual speakers took turns at the podium. A breakaway march had been planned to depart from the rally, but one speaker took the stage to discourage anyone from participating, emphasizing that it would be illegal and dangerous. The word on the street was that radicals had established some sort of back-room deal with public organizers that the latter reneged on. Most people left after the rally, but a couple hundred eventually regrouped around a sound system and set out, managing to block the freeway before being mass-arrested. A fifteen-year-old student fell from the freeway when the police closed in, suffering serious head injuries and tragically confirming the speaker&rsquo;s warning.</p>
<p>Afterwards, there were declarations of victory and hysterical recriminations, but the student movement had passed its peak. Without the initiative of the militant participants driving the movement, the reformist wing drifted into hopeless attempts to influence politicians; momentum collapsed. The same pattern played out elsewhere in the country.</p>
<p>Anarchists have to find a starting place from which to act in a society in which few even understand our goals. This creates paradoxes such as joining a struggle for education in a country in which education has always been tied to the state. Participating in the student movement, anarchists risked legitimizing social structures, roles, and privileges they would otherwise set out to undermine. The student movement of 2009-2010 might have gone further if it had been reframed as a part of a larger struggle involving all who were losing or had already lost their positions in the economy&mdash;not to mention those who never had any in the first place. In any case, it set the stage for <a href="http://occupyoakland.org/">Occupy Oakland</a> to do this.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/4b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/4a.jpg" width="500" height="333"/></a>
<em>Anarchists were &ldquo;occupying everything&rdquo; long before Occupy Wall Street <br />
was a gleam in <a href="http://en.wikipedia.org/wiki/Kalle_Lasn" target="_blank">Kalle Lasn</a>&rsquo;s eye.</em>
</p>
<h3>Reaching Limits: May Day, 2010</h3>
<p>On May Day 2010, small but fierce anarchist demonstrations and attacks on property took place in many cities around the United States, notably including Santa Cruz, California and Asheville, North Carolina. <a href="http://news.infoshop.org/article.php?story=20100916065614609" target="_blank">Eleven people</a> were arrested in Asheville, charged with conspiracy and other felonies and held on $65,000 bail.</p>
<p>The arrests sent shockwaves of controversy throughout anarchist circles. One editorial entitled <a href="http://news.infoshop.org/article.php?story=201006010725318" target="_blank">&ldquo;What I would do with $55,000&rdquo;</a> [sic] argued that it would be more strategic to leave the arrestees in prison and use the money to buy screen-printing equipment and pay the rent of social centers in Chicago. This is noxious indeed, but it showed how polarized the debate had become between partisans of infrastructure and confrontation, and how unfavorably insurrectionists had positioned themselves on the field of public discourse in advance of repression.</p>
<p>That question, raised in bad faith, still speaks to an important issue. What could anarchists do <em>offensively</em> with such an enormous sum of money? What would it mean to take the initiative, raising $65,000 to advance a confrontational program intentionally rather than reactively? Divorced from a strategy that incorporates repression as a necessary phase, following a blind mantra of <em>attack</em> is like taking the first vulnerable piece you see in a chess game: it can set you up for crushing defeats. This leaves anarchists always on the back foot.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/5b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/5a.jpg" width="500" height="332"/></a></p>
<p>Four days later, well over 100,000 people gathered in Athens, Greece to protest government cutbacks and tax increases mandated by the European Union and International Monetary Fund. Wave after wave attempted to storm the parliament in Syntagma square; this was arguably the closest Greece had come to insurrection since the riots of December 2008. It came to an end when three people were killed in a fire irresponsibly started by rioters in a bank still staffed by employees.</p>
<p>Many believe that this tragedy prevented a potentially revolutionary situation from unfolding. It also inverted the narrative that had framed resistance in Greece since December 2008, associating murder with protesters rather than police. It takes ten thousand people ten years to legitimize militant struggle, and a single fool an hour to discredit it.</p>
<p>The mood was bleak afterwards on both sides of the Atlantic. While anarchists in the US bickered about the Asheville 11, in Greece they debated about how anti-social tendencies had taken root and set the stage for the bank fire. Some still declared the worldwide actions at the beginning of May to be a success, but it&rsquo;s worth noting that few towns in the US hosted repeat events on May Day 2011.</p>
<p>When a strategy begins to produce diminishing or counterproductive returns, this is an opportunity to reevaluate and experiment. While the existing anarchist movement struggled to come to terms with the limits it had reached, new protagonists took the stage.<br />
</p>
<h3>Anarchy in the UK: <br />
The Student Movement, November-December 2010</h3>
<p>On November 10, 2010, the National Union of Students drew 52,000 people to London to protest an austerity bill that would raise the tuition cap from &pound;3290 to &pound;9000. As the main demonstration moved by Millbank Tower, a splinter group of hundreds, headed by no more than 30 black bloc anarchists, broke into the Tory Headquarters there. As they smashed windows, painted graffiti, and clashed with police, thousands of supporters gathered in the square outside, building a fire from their signs and placards. It took the police hours to regain control. Helicopter footage showed the occupiers lining the railing on the roof of Millbank, papers blowing out over the crowd far below while smoke rose from the fire.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/6b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/6a.jpg" width="500" height="578"/></a></p>
<p>While individual anarchists were among the first into the building, none of the organized anarchist groups in the UK turned out in great numbers. The photos of suspects circulated by the police and media didn&rsquo;t show the faces of longtime militants but those of the nation&rsquo;s youth. The participants referenced the unrest sweeping the globe&mdash;&ldquo;France, Greece, now here too&rdquo;&mdash;but this marked the entry of a new generation into confrontation with the state.</p>
<p>The UK had been comparatively quiet for years. Previous protest campaigns had largely been organized by full-time activists; consequently, an activist subculture had emerged. This subculture helped to foster radical activity and infrastructure, but it was disconnected from the experiences and concerns of most of those suffering from capitalism.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/7b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/7a.jpg" width="500" height="333"/></a></p>
<p>The attack on Millbank ignited <a href="http://www.crimethinc.com/blog/2011/01/26/the-uk-student-movement/">a wave of protests, walkouts, and other actions</a> involving more than 100,000 people over the next two months.<a class="footnote" href="javascript:void(0);" onclick="return overlib('This vindicates the call for anarchists to set off &ldquo;chain reactions of revolt&rdquo; that had appeared a few months earlier in our analysis, &ldquo;Fighting in the New Terrain.&rdquo;', CAPTION, '[2]');" onmouseout="nd();">[2]</a> Occupations occurred at schools throughout the country, serving as nerve centers to broaden and coordinate the movement. Several thousand young people converged in London again November 24 and 30; the police responded by surrounding and &ldquo;kettling&rdquo; demonstrators for hours. The movement peaked on December 9, with thousands participating in clashes in London while the British parliament passed the austerity package. Police kettled and viciously attacked protesters, sending one boy to the hospital in need of brain surgery; protesters defended themselves, smashed the windows of the Treasury and other buildings, and attacked a car bearing Prince Charles and the Duchess of Cornwall.</p>
<p>In contrast to the US student movement, the disenfranchised took a primary role in these protests, often to the chagrin of &ldquo;proper&rdquo; student organizers. In one video clip from December 9, masked hooligans asserted, &ldquo;We&rsquo;re from the slums of London&mdash;how do they expect us to pay &pound;9000 for uni fees?&rdquo; Politicians and corporate media endeavored to drive a wedge between the different demographics that comprised the movement, but this diversity was its primary strength.</p>
<p>Activity tapered off after the bill passed. As in Greece in December 2008, the end of the year served as the closing of parentheses around a period of increased momentum.</p>
<p>The movement in the UK came on the heels of strikes and labor unrest throughout Spain and France; it coincided with a comparable student movement in Italy, culminating similarly on December 14 with fires and rioting outside the Italian Parliament during a controversial vote. Things were heating up.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/8b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/8a.jpg" width="500" height="333"/></a></p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/9b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/9a.jpg" width="500" height="631"/></a></p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/10b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/10a.jpg" width="500" height="333"/></a></p>
<h3>New Fronts in Information Warfare: <br />
Wikileaks, Anonymous, Lulzsec</h3>
<p>While austerity protests drew in wider and wider swaths of the population, the same thing was taking place online. After <a href="http://wikileaks.org/" target="_blank">Wikileaks</a> released classified documents from the Afghanistan and Iraq occupations and US diplomatic cables, several corporations broke off relations with the group, cutting off its access to funds. In response, Anonymous&mdash;an internet meme serving as an umbrella for collective action&mdash;orchestrated distributed denial of service attacks on many of these companies, shutting down their websites and attracting international attention.</p>
<p>In the 20th century, the first wave of hackers had been motivated by curiosity and mischievousness; their successors pursued personal gain, working for criminal enterprises or security organizations&mdash;often in that order. Now, finally, it seemed that politicized hacking was coming into its own. Some of this attention may have been convenient for the US government, which was seeking to position itself for online crackdowns; but it also reflected the determination of online communities that existed by virtue of anonymity and free circulation of information to protect the necessary conditions of their existence.</p>
<p>While the culture of early Anonymous had been steeped in the adolescent humor and hostility of the message boards where it originated, by 2011 participants in this and similar projects frequently endorsed an anarchist agenda. For example, after <a href="http://boingboing.net/2011/06/23/breaking-lulzsec-lea.html" target="_blank">targeting the Arizona Department of Public Safety</a>, Lulzsec proclaimed, &ldquo;We&rsquo;re doing this not only because we are opposed to SB1070 and the racist Arizona police state, but because we want a world free from police, prisons and politicians altogether.&rdquo;</p>
<p>Information heists can reveal the shady underside of the authorities, discrediting them while dispelling the myth of their invulnerability. The cables released by Wikileaks describing President Ben Ali&rsquo;s pet tiger enjoying a luxurious diet while Tunisians starved stoked the flames of revolt in that country. But these attacks further a longer-term strategy, as well. Both 21st-century capitalism and the repressive apparatus that protects it depend on the circulation of information. Forcing corporations and governments to be cautious about how they share data cripples them.</p>
<p>&nbsp;</p>
<h5><strong>CNN</strong>: What&rsquo;s the end goal for you? What do you want to see happen as a result of Operation Payback?</h5>
<h5><strong>Anon</strong>: Personally? A utopian society. <br />
This is just a new way to fight . . .<br />
</h5>
<h3>The Insurrection Comes: <br />
&ldquo;Arab Spring,&rdquo; December 2010-March 2011</h3>
<p>No one was prepared for governments to begin toppling. The first to go was Tunisia. Demonstrations commenced after an impoverished street vendor set himself on fire in protest of his treatment by police; at first, these protests were marginal, but every attempt at repression fanned the flames until unions and even lawyers joined in. Turnouts only increased after Ben Ali fled the country on January 18.</p>
<p>The first massive demonstrations took place in Egypt a week later, organized by a coalition of predominantly youth groups. One of the most influential forums supporting these was a Facebook page called &ldquo;<a href="http://www.facebook.com/elshaheeed.co.uk?sk=info" target="_blank">We Are All Khaled Saeed</a>,&rdquo; named for a man murdered by police. The protests were violently repressed, and the government shut down internet and cell phone access throughout much of the country; but once again, this only spread and intensified the resistance. After clashes with the police left many police stations burnt to the ground along with the headquarters of the ruling party, demonstrators shifted towards strategic nonviolence rather than taking on the military directly. By early February, a great part of the country was participating in the revolt, despite hundreds of deaths and thousands of injuries.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/11b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/11a.jpg" width="500" height="313"/></a></p>
<p>President Mubarak repeatedly offered to grant protesters&rsquo; demands, but always a step too late; as momentum increased, people gained the confidence to demand more and more, until they would only be satisfied with his departure. He finally resigned on February 11. The following weeks saw similar uprisings in Bahrain, Syria, Yemen, and elsewhere around the Middle East, and an all-out civil war that ultimately drove Gaddafi from Libya.</p>
<p>Although North Africa might seem far away, in a globalized world we shouldn&rsquo;t be surprised by how familiar everything in this story is: unemployment and bitterness, actions organized by groups protesting police brutality, even college graduates working at coffee shops. There are no exotic overseas revolutions in the 21st century. Though these events dwarfed&nbsp;the preceding riots in Greece&nbsp;and&nbsp;the student movement in England, they sprang from the same source and assumed similar forms. The waves of unrest that had washed Europe in the preceding years helped set a precedent for what it looked like to revolt, which North Africans pushed further than Europeans had imagined possible.</p>
<p>We can learn a lot about revolt in the 21st century from studying these events. The upheaval began at the margins&mdash;Tunisia is a relatively minor nation, while Egypt is the most populated in the Middle East&mdash;and at the social periphery, among the unemployed, the young, and the poor. It spread to all social classes and metropolitan centers, going on to exert influence worldwide. In a fully networked world, instability at the fringe can threaten power at the center.</p>
<p>These uprisings continued the experimentation with new technologies and decentralized organization that characterized the&nbsp;anti-globalization movement, showing that anonymous networking could initiate full-scale leaderless rebellions. As information has become the lifeblood of capitalism,<a class="footnote" href="javascript:void(0);" onclick="return overlib('Today, high-speed global communication is essential for coordinating the flows of capital, commodities, and speculation; this is how capitalists outflanked the old workers&rsquo; movements, shifting centers of production swiftly around the world to force laborers to compete to offer the cheapest labor. But every advance in repression produces a symmetrical advance in resistance tactics.', CAPTION, '[3]');" onmouseout="nd();">[3]</a> rendering the internet the new global factory floor, these were its first workers&rsquo; councils&mdash;a new kind of collective intelligence enabling people to organize themselves directly without representation.</p>
<p>At the same time, if communications technology was essential to the uprising, it was because it <em>subverted</em> its conventional role in the West, bringing people together rather than enabling them to remain at a distance from one another. This is proven by the fact that the demonstrations only intensified when Mubarak shut down cell phone and internet service. The material infrastructure of the internet is still quite centralized; while it can be useful, it is a mistake to depend on it as long as it remains in capitalist hands.</p>
<p>Mubarak faced a no-win situation: if he left communications technologies running, they would be used against him, but taking them down provoked outrage and international solidarity. In the future, we can expect the authorities to suppress unrest by structuring and directing the flows of information rather than interrupting them. They already seem more adept at this in the US, where Facebook is not usually used to coordinate insurrections but as a space for atomized individuals to compete for social capital.</p>
<p>Although the North African upheavals involved labor unrest, they started outside the workplace and remained focused on public spaces like Cairo&rsquo;s Tahrir Square. The old labor movement was predicated on the way the production process gave workers common experiences, just as the subcultural strategies that followed it were based on the common references consumers shared. In the era of precarity, in which the common condition that unites us is that we are all at the mercy of an economy that offers us no permanent role, it makes sense for the factory occupations of 1968 to be replaced with the seizure of public space. Likewise, police are to the unemployed what bosses are to workers; in countries where young people suffer astronomical unemployment, it&rsquo;s not surprising that revolts begin with attacks on the police.</p>
<p>The drawback of starting from outside the workplace is that it can frame the object of the revolt in political rather than economic terms. While the revolts in North Africa were produced by economic conditions, they opposed themselves chiefly to the forms of government rather than the economic structures that produced these; in the end, they may have been limited by the absence of an alternate vision for human relations. Without this, people fell back on the traditional narratives of nationalism&mdash;as exemplified by Egyptian flags and the chant &ldquo;Muslim! Christian! We are all Egyptian!&rdquo;&mdash;and democracy. As often happens, the forms the rebellion assumed were far more radical than the demands it presented. As the Middle East continues to ferment and new traditions of resistance take root, we can hope that the vision implied by these forms will come into its own as an end as well as a means.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/12b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/12a.jpg" width="500" height="623"/></a></p>
<p>The peak of the so-called &ldquo;Arab Spring&rdquo; was followed by a period of chaos that continues up to today. The state desperately needs people to distrust and fear each other; without this, it lacks its chief justification for existence. Just as Mubarak&rsquo;s undercover police had posed as looters in order to justify a crackdown, outbreaks of ethnic violence have been convenient for those who wish to relegitimize state power. Yet Tahrir Square has been re-occupied by demonstrators again and again; the ousting of Mubarak and Ben Ali was clearly only the beginning of a long struggle.</p>
<p>Egypt received the second most military aid from the US in the world, after Israel&mdash;$1.3 billion a year. The tear gas canisters fired at demonstrators were inscribed &ldquo;Made in the USA.&rdquo; The oustings of Mubarak and later Gaddafi show that once things go far enough, military force is no longer a trump card; the military can hardly bomb its own cities. At the same time, to achieve more than a change of rulers, an insurrection has to spread into the ranks of the military and beyond national borders. It&rsquo;s unclear when we will cross this threshold, but nobody saw the Tunisian uprising coming, either.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/13b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/13a.jpg" width="500" height="332"/></a>
<strong>EGYPT WAS A RIOT</strong><br />
<em>Obama (recent supporter of Mubarak, <a href="http://www.youtube.com/watch?v=TyDLjLfE2Jc" target="_blank">February 11</a>): &ldquo;Egyptians have inspired us, and they've done so by putting the lie to the idea that justice is best gained by violence&hellip; For Egypt, it was the moral force of nonviolence that bent the arc of history toward justice once more . . . I&rsquo;m also confident that the same ingenuity and entrepreneurial spirit that the young people of Egypt have shown in recent days can be harnessed to create new opportunity: jobs, businesses.&rdquo;</em></p>
<h3>Occupying the Capitol, Not Attacking Capital:<br />
<a href="http://www.crimethinc.com/blog/2011/03/10/spread-the-chaos-from-capitol-to-capital/">Wisconsin, February-March 2011</a></h3>
<p>On the heels of the Egyptian example, anti-austerity protests gathered steam even in the US. Four days after Mubarak stepped down, a line of people mobilized by the Teaching Assistants Association waited to address the Wisconsin state legislature about proposed budget cuts and anti-union legislation. When the hearing was closed for the night, the queue became an impromptu occupation, as those who hadn&rsquo;t gotten to speak were reluctant to lose their places.</p>
<p>The Capitol building was occupied until March 3, becoming a rallying point for unprecedented demonstrations. Teachers called in sick to work en masse, shutting down schools; anarchists and fellow travelers occupied a university building in Milwaukee in an attempt to spread the unrest; rumors circulated about a general strike.</p>
<p>On March 9, while Senate Democrats were absent in protest, Wisconsin&rsquo;s Republican Senators passed a part of the proposed austerity package&mdash;a bill stripping public-sector unions of collective bargaining rights. In response, thousands returned to the capitol building, pushing past state patrolmen to reoccupy it in defiance of the&nbsp;court order&nbsp;that had concluded the previous occupation.</p>
<p>The centrality of the capitol building throughout the protests drove home prior to the Occupy movement how important it is for a movement to establish a relationship to physical place. Just as university occupations served as nerve centers during the&nbsp;December 2008 uprising in Greece, the capitol building offered a focal point for demonstrators to build momentum over a period of weeks and a site to converge in response to new developments. In a time of universal estrangement, when we can only congregate in spaces designed to make us shop or cheer for sports teams, common space itself has become radical and radicalizing.</p>
<p>This level of disruption was unusual for a quiet Midwestern state like Wisconsin. But once again, though the occupation assumed comparatively radical forms, it still limited itself to law-abiding democratic discourse. This created strange bedfellows for the protesters; for example, individual police officers expressed support for the occupation early on, though they later helped put a stop to it. This also paved the way for the Democratic Party to squander whatever momentum remained afterwards by channeling it into a doomed campaign to recall the governor.</p>
<p>However devious the Republicans&rsquo; machinations, they passed the bill by democratic process, the same way countless other bills are passed. Although the protesters saw themselves as partisans of democracy, in forcing their way back into the capitol on March 9 they were essentially asserting that their illegal occupation of the building was more legitimate than Senators doing what they were elected to do in it. Unfortunately, this was never articulated; people were prepared to break the law, but not to cease believing in it. It speaks volumes about the function of the Left that liberal organizers entered the capitol illegally on March 9 just to persuade everyone else to leave with them.</p>
<p>Between February 15 and March 3, the original occupation of the capitol had been undermined one compromise at a time. First the police politely asked people not to be in one room; they were being so nice about everything, and weren&rsquo;t they on the same side? Then they gently asked people to vacate another room, and longtime organizers supported this, and so on&mdash;until the former occupiers found themselves out on the pavement, dumbfounded. This same process took only one night to play out again on March 9.</p>
<p>This underlines an important lesson:&nbsp;<em>the first compromise might as well be the last.</em>&nbsp;Whenever we concede anything, we set a precedent that will be repeated again and again, emboldening those for whom it is more convenient if we don&rsquo;t stand up for ourselves. If police didn&rsquo;t arrest demonstrators in the capitol, it was not because they supported the occupation, nor because demonstrators had the right to be in the building, but because the demonstrators had mobilized enough social power to force the authorities to back down. Politeness and obedience could only detract from this leverage.</p>
<p>In popular struggles, one role anarchists can play is to be the ones who refuse to yield. We can also pass on our hard-won analyses to less experienced protesters&mdash;for example, emphasizing that however personable individual police officers might seem, they cannot be trusted insofar as they <em>are police.</em></p>
<p>To accomplish this, however,&nbsp;anarchists have to be vocal and in the thick of things, not looking on from the margins as they were in Wisconsin. Anarchists of a more insurrectionist bent gravitated to the occupation in Milwaukee, which failed to pick up steam, while anarchists in Madison largely focused on providing infrastructure.<a class="footnote" href="javascript:void(0);" onclick="return overlib('This is not the first time anarchists have contributed their organizational skills to an essentially liberal protest. At the 2004 Republican National Convention in New York City, about 100,000 people participated in demonstrations; this included thousands of anarchists, many of whom limited themselves to logistical roles. Afterwards, this was recognized as a tremendous missed opportunity&mdash;hence the efforts to take the lead in planning actions at the 2008 Republican National Convention in St. Paul, Minnesota. These conventions are covered in <em>Rolling Thunder</em> issues #1 and 7.', CAPTION, '[4]');" onmouseout="nd();">[4]</a> Offering resources can be a good way to connect with strangers; yet our task is not just to facilitate protests of any kind, but to ensure that they threaten the power structure.&nbsp;To this end, we have to seize the initiative to organize actions as well as infrastructure&mdash;engaging the general public in the process, not just other anarchists.&nbsp;Clashes with the state are bound to be more controversial than free meals and childcare, but this controversy has to play out if we are ever to get anywhere.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/14b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/14a.jpg" width="500" height="293"/></a>
<em>The occupied theater building in Milwaukee</em></p>
<p>A common complaint from the more combative participants in the Madison occupation was that leftist organizations had already determined the character of the protest. Anarchists were afraid to act, fearing that they would simply be marginalized if they challenged the dominant narrative. In fact, there&rsquo;s nothing to lose in such circumstances, when for all intents and purposes anarchists are <em>already marginalized.</em> The solutions promoted by the Left don&rsquo;t point beyond the horizon of capitalism; even when they aren&rsquo;t utterly na&iuml;ve, they serve to distract and neutralize those who desire real change. Where the field is split between left and right, we may as well disrupt this dichotomy by acting outside of it. Even if we fail, at least we broaden the terrain.</p>
<p>This brings up the larger question&mdash;what should be the <em>goal</em> of anti-austerity protests? In Wisconsin, most participants took it for granted that their goal was to stop the bill: in other words, to keep things the way they had been. This treats the financial crisis as if it were just an excuse dreamed up by greedy capitalists.</p>
<p>But from the capitalist perspective, austerity measures really are unavoidable; there&rsquo;s no other way to keep the system running. Elsewhere in the US, earnestly heartbroken Democrats were proposing&nbsp;similar measures&nbsp;for their own states&mdash;largely without opposition, thanks to the stupefying effect of the two-party system.</p>
<p>Capitalism is not a static condition but a dynamic process transforming the world. A protest can&rsquo;t freeze history. Even if one wave of cutbacks can be stopped, a thousand more assaults will follow. The state literally can&rsquo;t back down&mdash;the politicians have nowhere to go. This means that apparently realistic goals, such as blocking a particular budget or bill, are actually <em>less</em> realistic than attempting to change the entire system.</p>
<p>This was lost on many North American workers. Wisconsin teacher Peggy Kruse was&nbsp;quoted as saying, &ldquo;Most teachers are more than happy to take the 18% pay cut, to do anything that will help get the state back and running. We&rsquo;re most concerned about the loss of collective bargaining rights.&rdquo; In other words, we&rsquo;ll concede anything&mdash;just don&rsquo;t take away our right to concede! Let Bill Gates keep his $56 billion while we get pay cuts or pink slips, but don&rsquo;t touch the illusion that we&nbsp;choose&nbsp;this state of affairs.</p>
<p>Accepting defeat in advance correlates with a blind commitment to peaceful protest. Signs in Wisconsin read &ldquo;FIGHT LIKE AN EGYPTIAN,&rdquo; but Egyptian protesters&nbsp;burned down police stations. No amount of Obama doublespeak can render that <em>peaceful.</em></p>
<p>If we shouldn&rsquo;t evaluate anti-austerity protests according to whether they thwart new legislation or how many people they draw to rallies, their&nbsp;content becomes the important question.&nbsp;Do they create new relationships between people, new ways of relating to material goods? Do they demonstrate values that point beyond capitalism? Do they produce new momentum, new ways of fighting, new&nbsp;<em>unruliness?</em></p>
<p>The capitol building symbolized democracy, which is to say&nbsp;<em>collective participation in top-down control.</em>&nbsp;Occupying it implied that the people could be better stewards of democracy than their elected representatives. Insofar as workers behaved themselves even as their right to organize autonomously was stripped away, they proved this to be the case.</p>
<p>Like the student movement, the movement in Wisconsin stalled because it limited itself to opposing specific legislation affecting one demographic. Framed as a last-ditch effort to protect the privileges of state employees, it could only go so far; people of many walks of life got involved, but the narrative prevented them from taking the lead. Yet millions of workers without union jobs or state salaries were&nbsp;already&nbsp;suffering the same conditions the Republicans wanted to force on state employees. A movement involving all these different sectors of society as equal participants could have snowballed; it would also have been much more difficult to control. Spontaneous high school walkouts in February had hinted at this possibility, connecting the proposed cutbacks to the alienation of young people who had yet to be thrown at the mercy of the job market. Instead, the predominantly white union workers framed the protest as a matter of defending their own privileges, sidelining other demographics such as unemployed African-Americans in Milwaukee and thus dooming themselves to defeat.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/15a.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/15a.jpg" width="500" height="293"/></a>
<em>Get over it</em></p>
<h3>It Spreads: The <a href="http://www.crimethinc.com/texts/recentfeatures/barc.php">Plaza Occupation Movements</a>, May-June 2011</h3>
<h5>The time for indignation is over. Those who get indignant are already starting to bore us. Increasingly, they seem to us like the last guardians of a rotten system, a system without dignity, sustainability or credibility. We don&rsquo;t have to get indignant anymore, we have to revolt. The next time 300,000 of us take to the streets, let&rsquo;s not go back home at the end of the day. Let&rsquo;s go with our sleeping bags, knowing that on that night we won&rsquo;t sleep in our beds.&rdquo; </h5>
<h6 align="right">-Franco Berardi Bifo</h6>
<p>The spell of occupation extended beyond Wisconsin&mdash;along with the spell of democracy. Real Democracy Now (appropriately abbreviated DRY in Spanish), a new group professing to be outside all existing political parties and ideologies, organized protests against austerity measures and political corruption around Spain on May 15; afterwards, the idea spread by Twitter to camp out in plazas in imitation of the Tahrir Square encampment. Organized around assemblies based on &ldquo;direct democracy,&rdquo; these occupations swiftly drew thousands of participants in many cities around Spain. Communists, anarchists, and partisans of various national liberation movements mingled with people of other walks of life, many of whom had not previously been involved in protests or considered themselves politically active.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/16b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/16a.jpg" width="500" height="332"/></a></p>
<p>By the countrywide elections the following weekend, hundreds of thousands of people had visited or participated in the occupations. Nearly half of the population abstained from voting, with blank ballots doubling to 5%.</p>
<p>On May 27, police arrived at the occupation in Barcelona to &ldquo;clean up&rdquo; the plaza. Tens of thousands converged to oppose them. Organizers attempted to impose a code of nonviolence, as they had in every proposal in the assemblies, but as the police attacked clashes broke out all the same. After a long battle, the occupiers forced the police to withdraw; over one hundred people were injured, many with broken bones.</p>
<p>In some cities, the occupations had signed on the to DRY manifesto from the outset, becoming ideologically homogenous; these occupations did not expand as much or last as long. The occupations that remained sites of contention for a range of ideas and approaches were much more vibrant and enduring. Nonetheless, by mid-June the plazas had emptied throughout the country, though in some cities neighborhood assemblies took their place. Because they did not mount an offensive on the state and private ownership of capital, there was no endgame for the occupations: they were exciting experiments in convergence and self-organization, but offered no obvious road forward.</p>
<p>Like the UK student movement, the plaza occupation movement marked the entry of new demographics into conflict with the state&mdash;including many from the disenfranchised middle class. These newcomers accepted some of the premises of longtime radicals, such as autonomy from political parties; in this regard, they went much further than protesters in Wisconsin had. At the same time, they brought many of their dogmas with them, including pacifism. Likewise, the myth of a better, purer democracy remained alive and well in the plazas. The central assemblies addressed demands to the government and monopolized legitimacy, if not power, in the occupations.</p>
<p>In Greece, plaza occupations inspired by the ones in Spain began on May 25. These lasted longer than the Spanish occupations, drawing hundreds of thousands at the high points. They built up to a 48-hour general strike on June 28-29 coinciding with the Greek parliament narrowly voting to accept the new austerity measures decreed by the European Union. In Greece as in Spain, the new refugees from the middle class brought pacifism with them alongside various brands of nationalism. The pacifism threatened to divide the movement: as had occurred in the wake of the <a href="http://www.crimethinc.com/texts/recentfeatures/toronto2.php">Toronto G20 protests</a> and elsewhere, baseless conspiracy theories circulated that the &ldquo;hooded ones&rdquo; at the front of clashes with the police were actually somehow in league with the authorities. The nationalism was also ominous; although only a small minority in the occupations were out-and-out fascists, as the economic crisis worsens even mild nationalism may turn into xenophobia.</p>
<p>Despite these internal challenges, the general strike was marked by massive violent clashes with the police. For the first time since May 5, 2010, the insurgents who had risen up in December 2008&mdash;anarchists, anti-authoritarians, students, the underclass&mdash;were joined in the streets by the general public.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/17b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/17a.jpg" width="500" height="320"/></a></p>
<h3>Anarchy in the UK, Take Two: Riots and Reaction, August 2011</h3>
<p>A month later, Chile erupted in its wildest riots in years, with 874 people arrested in student protests against the privatized education system&mdash;the same day that Standard &amp; Poor&rsquo;s downgraded the United States credit rating. Immediately afterwards, riots broke out in the UK in response to the police murder of Mark Duggan. Far from subsiding, the unrest generated by the crisis was ricocheting back and forth across the globe.</p>
<p>The riots began on August 6 in London following protests in Duggan&rsquo;s native Tottenham and spread swiftly around the country, intensifying in other cities after police clamped down in the capitol. These were the opposite of the plaza occupations: a single subset of society escalating its private war on police and private property, without narrative, demands, or illusions, and thus coming directly into conflict with the rest of society as a whole. Participation occurred chiefly along class rather than racial lines, with many groups being effectively multi-ethnic.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/18b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/18a.jpg" width="500" height="348"/></a>
<em>Redistribution of power</em></p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/19b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/19a.jpg" width="500" height="347"/></a>
<em>Redistribution of wealth</em></p>
<p>Altogether the riots inflicted around&nbsp;&pound;200 million of damage, including widespread looting and arson. Once again, Twitter and Facebook were used to coordinate action on the ground, although the authorities took extensive advantage of this to arrest and prosecute participants&mdash;foreshadowing future clampdowns. Five more people lost their lives in the disorder.</p>
<p>The UK riots followed close on the heels of the unsuccessful anti-austerity protests, showing the consequences of denying a generation any prospects within capitalism. The subsequent push to cut off rioters&rsquo; families from social services underscores how the riots formalized the emergence of an excluded class that will only be controlled through unbridled violence. The appearance of vigilantes during the riots, including fascist groups like the English Defense League, indicates the breadth of forms that violence will take.</p>
<p>In this context, it&rsquo;s chilling how many people identified with the corporate media narrative demonizing the rioters, even turning out with brooms in a media stunt calculated to show that ordinary British people supported the continuation of law and order. If the British working class has any hope of defending itself against the next round of austerity measures and diminishing employment opportunities, this can only come from common cause between rioters and other elements of the exploited. The availability of the underclass as competition for employment is precisely what enables capitalists to keep wages and benefits down; in attempting to assert and defend their own privileges, obedient workers doom themselves to be the next on the chopping block. Of course, globally speaking, British workers have only recently begun to lose their comparative privileges, so perhaps it is not surprising that it is taking them some time to come to terms with their current condition.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/20b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/20a.jpg" width="500" height="359"/></a>
<em>Do-it-yourself class treachery</em></p>
<p>The absence of effective anarchist initiatives immediately following the riots was not promising; history appeared to be racing ahead of anarchists just when it was most important for them to intervene in it. Treating class as a kind of identity politics had not equipped the conservative majority of British anarchists for a world in which the most determinant struggles occur outside the workplace.<br />
</p>
<h3>The Shape of Occupations to Come</h3>
<p>In September 2011, protesters in North America finally hit upon a format that could spread, based on the models already tested elsewhere around the world. We&rsquo;ll discuss the lessons of the Occupy movement to date in a forthcoming analysis. Here, let it suffice to say that Occupy Wall Street caught on around the continent because it fulfilled conditions that could easily be deduced from earlier successes and failures worldwide. This suggests that studying the shortcomings of these precedents can also teach us how to improve on this success.</p>
<p>One obvious lesson is the importance of decision-making structures conducive to anarchist action. At no point during the buildup to the protests of March 4, 2010 or the occupations in Wisconsin did anarchists establish an autonomous public organizing body to play a role such as the&nbsp;RNC Welcoming Committee played at the <a href="http://www.crimethinc.com/texts/recentfeatures/rncdnc.php">2008 Republican National Convention</a> or the PGRP played at the <a href="http://www.crimethinc.com/texts/recentfeatures/g202.php">2009 G20 in Pittsburgh</a>. This was a strategic error that enabled liberal and authoritarian organizers to monopolize the public discourse around the protests and determine their character and conditions in advance. Without the leverage afforded by public organizing of our own, we can always&nbsp;expect to be hoodwinked and betrayed by those who don&rsquo;t share our opposition to hierarchical power.</p>
<p>The actions that go well for anarchists are likely to be the ones initiated by anarchists, or else in conjunction with others who respect anarchists&rsquo; goals and autonomy. In such cases, anarchists are more likely to succeed in determining the character of events, choosing a terrain conducive to confrontation. This may explain why occupations and apparently &ldquo;spontaneous&rdquo; actions have given more space and opportunity to decentralized forms of resistance than large-scale events such as the permitted marches of March 4, 2010. Authoritarian and lowest-common-denominator organizations can more easily dominate the latter, both by literally laying the groundwork of what is to happen and by monopolizing legitimacy in the public eye by presenting themselves as representing the movement. So long as anarchists remain on the margins of liberal and authoritarian organizing, organizing breakaway marches and the like, the lack of initiative and &ldquo;legitimacy&rdquo; in the public eye will always impose structural limits on our efforts.</p>
<p>We need public, participatory calls and organizing structures, both to offer points of entry to everyone who might want to fight alongside us and to make it impossible for authoritarians to stifle revolt by arranging the battlefield to be unfavorable for it. Public organizing can complement other less public approaches, but often it&rsquo;s necessary to render them possible in the first place. Not surprisingly, the cities in which anarchists succeeded in carrying out inspiring actions as part of the Occupy movement&mdash;Oakland, Seattle, Saint Louis&mdash;were the ones in which they either had considerable leverage within the general assemblies or maintained their own open anti-authoritarian caucuses.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/nightmares/21b.jpg" rel="lightbox[nightmares]"><img src="https://cloudfront.crimethinc.com/images/nightmares/21a.jpg" width="500" height="333"/></a></p>
<p>As&nbsp;capitalism renders more and more people precarious or redundant, it will be harder and harder to fight from recognized&nbsp;<em>positions of legitimacy</em>&nbsp;within the system such as &ldquo;workers&rdquo; or &ldquo;students.&rdquo; Last year&rsquo;s students fighting tuition hikes are this year&rsquo;s dropouts; last year&rsquo;s workers fighting job cuts are this year&rsquo;s unemployed. We have to legitimize fighting from&nbsp;<em>outside,</em>&nbsp;establishing a new narrative of struggle.</p>
<p>If we can accomplish this, we will neutralize the allegations of being &ldquo;outside agitators&rdquo; that are always raised against those who revolt. Better, we will transform every austerity conflict into an opportunity to connect with everyone else who has been thrown away by capitalism. Our goal should not be to protect the privileges of those who retain their jobs and enrollment, but to channel outrage about everything that capitalism has taken from all of us.</p>
<p>In addition to exacerbating the contradictions inherent in the financial crisis, we should undertake to make life in upheavals more pleasurable and robust than workaday life. Those who participate in wildcat strikes, blockades, and occupations should experience these as more exciting and fulfilling than their usual routines, to such an extent that it becomes possible to imagine life after capitalism. As many anarchists live in a permanent state of exclusion, making the best of it despite everything, we should be especially well-equipped to assist here.</p>
<p>Finally, we have to be tireless in our critique of democracy, as the alternative people in this society intuitively fall back on against the excesses of capitalism. The more unpopular this is, the more important it is that we do it. Private property and government are the two great sacred cows of our age&mdash;the ones for which our lives and the earth itself are being sacrificed&mdash;and challenging the ways they monopolize legitimacy is <em>one</em> project, not two. They are two heads of the same beast; they cannot be beaten separately.</p>
<p>&nbsp;</p>
<h5>&ldquo;It was a symbolic battle&mdash;or more precisely, a frighteningly real and bloody fight over a symbolic location; the fight itself was the message.&rdquo; </h5>
<h6 align="right">
&ndash;<a href="http://momentofinsurrection.wordpress.com/cyclones-of-struggle-from-occupation-to-intifada/" target="_blank">a participant</a> in the battle for the <br />
Egyptian Ministry of the Interior</h6>
<p>&nbsp;</p>
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1] See <em>Rolling Thunder</em> #9.</p>
<p>[2] This vindicates the call for anarchists to set off &ldquo;chain reactions of revolt&rdquo; that had appeared a few months earlier in our analysis, &ldquo;Fighting in the New Terrain.&rdquo;</p>
<p>[3] Today, high-speed global communication is essential for coordinating the flows of capital, commodities, and speculation; this is how capitalists outflanked the old workers&rsquo; movements, shifting centers of production swiftly around the world to force laborers to compete to offer the cheapest labor. But every advance in repression produces a symmetrical advance in resistance tactics.</p>
<p>[4] This is not the first time anarchists have contributed their organizational skills to an essentially liberal protest. At the 2004 Republican National Convention in New York City, about 100,000 people participated in demonstrations; this included thousands of anarchists, many of whom limited themselves to logistical roles. Afterwards, this was recognized as a tremendous missed opportunity&mdash;hence the efforts to take the lead in planning actions at the 2008 Republican National Convention in St. Paul, Minnesota. These conventions are covered in <em>Rolling Thunder</em> issues #1 and 7.</p>
</div>