<h6 align="right" style="margin-right: 0px"><a href="/tools/downloads/posters.html#prizes"><em>&raquo; Download the accompanying poster here. &raquo;</em></a></h6>
<h2><em>Fight capitalism and win</em></h2><h1>Millions of Dollars in Prizes!</h1>
<p align="center"><a href="http://thecloud.crimethinc.com/images/prizes/prizes_e.jpg" rel="lightbox[prizes]"><img src="http://thecloud.crimethinc.com/images/prizes/prizes_d.jpg" width="500" height="332"></a></p>
<p>   Over the past decade, government agencies around the US have paid out <a href="#2">millions and millions of dollars</a> in settlements resulting from federal and police violence against activists. And those are only the cases too flagrant to suppress&mdash;think how many more must go unreported! Far from an anomaly, illegal activity in the course of law enforcement is the norm; presumably it would be impossible to maintain law and order without it.</p>
<p>
The costs of these violations are figured into government budgets as foregone conclusions. For example, prior to the <a href="/texts/recentfeatures/rncdnc.php">2008 Republican National Convention</a>, the Republican National Committee <a href="http://www.commondreams.org/headline/2008/09/04" target="_blank">offered $10 million in advance</a> to cover lawsuits from police misconduct&mdash;acknowledging that, despite new laws passed specifically for the convention, the desired level of repression would require the authorities to break their own laws to the tune of millions of dollars.</p>
<p>
In all seriousness, you&rsquo;re not much more likely to win a million-dollar settlement than you are to get your hands on the prizes promised in corporate competitions&mdash;and being beaten by police is no more pleasant than being abused by the capitalist system in other ways. The point is that resistance doesn&rsquo;t always end in defeat, even when it results in repression and arrest. We should include the battle in the courts in our strategies, even if we don&rsquo;t believe in the legitimacy of the law any more than our rulers do. In cities that have seen a lot of recent demonstrations and lawsuits, police departments are often <a href="/blog/2007/10/25/notes-on-the-october-rebellion/" target="_blank">more hesitant</a> to beat and arrest protesters.</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/prizes/prizes2_b.jpg" rel="lightbox[prizes]"><img src="http://thecloud.crimethinc.com/images/prizes/prizes2_a.jpg" width="500" height="263"></a></p>
<a name="2" id="2"></a>
<p>
<strong>Some recent government settlements:</strong></p>
<p>
&bull; Following the <a href="/blog/2006/11/30/seattle-seven-years-later/">1999 protests</a> at the meeting of the World Trade Organization in Seattle, the city government paid <a href="http://www.komonews.com/news/local/6830252.html" target="_blank">$1.8 million</a> to resolve charges of brutality and wrongful arrest.</p>
<p>
&bull; The government of Los Angeles paid <a href="http://www.thefreelibrary.com/PROTESTERS%27+SETTLEMENT+IS+APPROVED+$1.2+MILLION+TO+BE...-a0116428999" target="_blank">over $5 million</a> as a result of 11 lawsuits stemming from police conduct during the 2000 Democratic National Convention.</p>
<p>
&bull; Years later, the Los Angeles City Council agreed to pay <a href="http://latimesblogs.latimes.com/lanow/2009/02/los-angeles-pay.html" target="_blank">$12.85 million</a> to demonstrators and bystanders attacked by police at a 2007 May Day rally.</p>
<p>
&bull; Police violence against anti-war protesters in April 2003 cost the government of Oakland, California <a href="http://query.nytimes.com/gst/fullpage.html?res=9B05E4DC1F31F933A15750C0A9609C8B63&amp;sec=&amp;spon=" target="_blank">over $2 million</a>.</p>
<p>
&bull; Meanwhile, activists won a settlement of <a href="http://ccrjustice.org/newsroom/press-releases/antiwar-activists-win-$2-million-settlement-new-york-city-major-victory-free" target="_blank">$2 million</a> for being illegally arrested the same month at anti-war protest in New York City.</p>
<p>
&bull; New York City has also paid <a href="http://www.lawyersandsettlements.com/settlements/03370/protesters.html" target="_blank">$231,000</a> and <a href="http://gothamist.com/2008/11/16/nyc_pays_55k_to_settle_another_2004.php" target="_blank">$55,000</a> to protesters arrested during the 2004 Republican National Convention, and <a href="http://www.nytimes.com/2002/02/08/nyregion/metro-briefing-new-york-manhattan-city-to-pay-protesters-469000.html" target="_blank">$469,000</a> to settle a lawsuit filed by people jailed after a protest of the murder of <a href="http://en.wikipedia.org/wiki/Amadou_Diallo" target="_blank">Amadou Diallo</a>, to name just a couple settlements.</p>
<p>
&bull; Washington, D.C. has witnessed a slew of successful suits by activists, including <a href="http://www.myfoxdc.com/dpp/news/local/dc-imf-protesters-settlement-112309" target="_blank">a $13.7 million settlement</a> following the 2000 IMF/World Bank protests and a <a href="http://www.lawyersandsettlements.com/settlements/06727/protester-abuse.html" target="_blank">$685,000</a> settlement for police violence during the 2001 inauguration. Protests against the World Bank and International Monetary Fund the following year resulted in various lawsuits, netting <a href="http://www.washingtonpost.com/wp-dyn/content/article/2009/12/15/AR2009121504345.html" target="_blank">$8.25 million</a>, <a href="http://www.lawyersandsettlements.com/settlements/08848/dc-protest-settlement.html" target="_blank">$1 million</a>, and <a href="http://www.lawyersandsettlements.com/settlements/07342/dc-protest-arrests.html" target="_blank">$200,000</a> for wrongful arrests. A 2002 detention of eight antiwar protesters also resulted in a settlement of <a href="http://www.washingtonpost.com/wp-dyn/content/article/2009/12/15/AR2009121504345.html" target="_blank">$450,000</a>.</p>
<p>
&bull; The particularly ugly police violence during the protests against the 2003 Free Trade Area of the Americas ministerial in Miami engendered lawsuits that concluded in a number of settlements, including separate payouts of <a href="http://www.commondreams.org/archive/2007/10/12/4508" target="_blank">$561,000</a>,
<a href="http://www.miaminewtimes.com/2007-10-04/news/ftaa-settlement-reached" target="_blank">$180,000</a>, and <a href="http://www.aclufl.org/news_events/?action=viewRelease&amp;emailAlertID=3574" target="_blank">$17,000</a>.</p>
<p>
&bull; Settlements result from ongoing campaigns as well as demonstrations. In 2002, a federal jury ruled that <a href="http://www.judibari.org/jury%27s_message.html" target="_blank">$4.4 million</a> should be awarded to <a href="http://en.wikipedia.org/wiki/Judi_Bari" target="_blank">Judi Bari</a> and Darryl Cherney for the violation of their rights by FBI and law enforcement agents. Likewise, environmentalist Josh Connole was awarded <a href="http://articles.latimes.com/2005/nov/15/local/me-connole15" target="_blank">a total of $120,000</a> for being arrested without probable cause.</p>
<h3>Testimonials</h3>
<p>
&ldquo;All the friends who were going to skip school with me flaked out at the last minute, so I wasn&rsquo;t with an affinity group when I was arrested. I had to call my dad. It could have been worse&mdash;he gave my jailers hell and was careful to keep copies of every piece of paper they made him sign. This came in handy three years later when I heard about the class action lawsuit for the mass arrest. I signed on, then waited&hellip; and waited&hellip; for a long time. And then we won! Of course, I donated some money to anarchist prisoners and legal support groups. I&rsquo;d been hearing good things about an upcoming anti-capitalist mobilization overseas, and with only two months to go I bought a plane ticket. I used the money to reinvest myself in the movement and came out committed to a life of struggle towards liberation.&rdquo;</p>
<p> <br />
&ldquo;When the police <a href="http://www.ainfos.ca/03/aug/ainfos00231.html" target="_blank">raided our bookstore</a>, we made over $60,000 in less than an hour. That sure is more than my college degree has made me! With the National Governors&rsquo; Convention coming to town, the authorities feared that we were up to something and preemptively stormed our collective space&mdash;only to discover that our most sinister plan was a puppet show. Truth be told, there was absolutely nothing we needed that kind of money for, but it was reassuring to know that the City of Indianapolis wasn't going to use it. So long as there is heart, revolutionary change doesn't need funding. That said, I simply can't wait for my house to be raided again&mdash;my son and I need a vacation!&rdquo;<br />
<br />
&ldquo;Thanks to the NYPD, I&rsquo;m a ten-thousandaire! At an anti-war demo in New York City, I was arrested while standing on the sidewalk with a bunch of people who were trying to get to a rally. &lsquo;Preemptive arrest&rsquo; is the strategy of choice for cops at big protests, the aim being to stop trouble before it starts. This results in a lot of people going to jail on minor charges based on flimsy or non-existent evidence, then being released after the action is over. After seven hours in jail, I was discharged with a ticket for disorderly conduct and told to show up in court a month later. I hired a lawyer, got the charge dismissed, and filed a lawsuit. A few years later my lawyer called and said I&rsquo;d been awarded $15,000 for my seven hours of trouble. It didn&rsquo;t cost me a dime and now I don&rsquo;t have to buy the store brand pasta!&rdquo;</p>
<p>&nbsp;</p>