<script language="JavaScript">
<!--
function win1() {
window.open("../texts/rncdoc0.html","Window1","menubar=no,innerWidth=560,toolbar=no,scrollbars=yes,status=no");
}
//-->
</script>
<h1>Going It Alone</h1>
<h2 align="right"> Anarchist Action at the Democratic <br />
and Republican National Conventions</h2>
<p align="center"><a href="/texts/images/rnc1b.jpg" rel="lightbox[rnc]" ><img src="/texts/images/rnc1.jpg" width="500" height="332"></a></p>
<p><em>(<a href="javascript:win1()" onMouseOver="self.status='Open In A Window'; return true;">Click here</a> for romantic introductory text)</em></p>
<p> For good or for ill, the protests at the 2008 Democratic and Republican National Conventions constituted the most significant nationwide effort anarchists have undertaken to organize militant action in the US in several years. Two weeks later, <a href="http://www.crimethinc.com/blog/2008/09/24/hundreds-of-billions-of-dollars/">the global economy collapsed</a>, followed shortly by anarchist-initiated rioting in <a href="http://www.crimethinc.com/blog/2008/12/20/greece-and-the-insurrections-to-come/">Greece</a> dwarfing anything in Denver or St. Paul. It&rsquo;s easy to feel that the DNC and RNC mobilizations were inconsequential by comparison. But if US anarchists are ever going to be capable of contributing to insurrections like the ones in <a href="http://en.wikipedia.org/wiki/2006_Oaxaca_protests" target="_blank">Oaxaca</a> and Greece, we either have to figure out how to improve on the models applied at the conventions, or else identify their shortcomings conclusively so as to adopt more effective approaches.</p>
<h3>Appraisal</h3>
<h5>    In short, the convention protests were not a stunning victory, but they set valuable precedents in coordination, strategy, and infrastructure. Perhaps the greatest danger is that, because they were not an unqualified success, they will have been forgotten by the time of the next mass mobilization.</h5>
<p>The convention protests had limited effect primarily because of low attendance, though anarchists made a much better showing than practically any other demographic and were better prepared than usual. They provide a classic example of a movement learning from its mistakes too late: anarchists finally regained the initiative in the antiwar movement just as that movement breathed its last. But if those who organize future mobilizations also learn these lessons, this could set the stage for more significant victories. Ultimately, the importance of the DNC and RNC mobilizations will be determined in the future, according to how they inform the next phase of radical organizing.</p>
<p> In terms of specifically anarchist participation, many aspects of the mobilizations were unprecedented. Nationwide preparations began well over a year in advance, and the majority of participants showed up in organized affinity groups. Anarchists took the initiative to determine and coordinate their own strategies and tactics, and made breakthroughs in establishing solidarity with other groups&mdash;as exemplified by the historic <a href="http://www.nornc.org/st-paul-principles/" target="_blank">St. Paul Principles</a>. They also debuted communications structures that had not previously been applied at mass mobilizations, which have since been cited by the US military <a href="http://www.fas.org/irp/eprint/mobile.pdf" target="_blank">[PDF, 6.9 MB]</a> and <a href="http://irevolution.wordpress.com/2008/12/18/greek-riots-facebook-twitter-and-sms/" target="_blank">utilized during the riots in Greece</a>. Just as the global <a href="http://www.indymedia.org" target="_blank">indymedia network</a> came out of the <a href="/blog/2006/11/30/seattle-seven-years-later/" target="_blank">Seattle WTO</a> demonstrations,<a class="footnote" href="javascript:void(0);" onclick="return overlib('Some critics pose a false dichotomy between building radical infrastructures and focusing on mass mobilizations; in fact, the latter often produce the former.', CAPTION, '[1]');" onmouseout="nd();">[1]</a> the DNC/RNC mobilizations produced the <a href="http://bashbacknews.wordpress.com/" target="_blank">Bash Back!</a> network<a class="footnote" href="javascript:void(0);" onclick="return overlib('Bash Back! came out of a Midwest anarchist consulta in November 2007, initiated by queer anarchists who felt that there hadn&rsquo;t been sufficient space for radical queer and trans participants at earlier demonstrations. Months after the conventions, Bash Back! groups were making headlines with provocative actions, and the network continued to spread across the US.', CAPTION, '[2]');" onmouseout="nd();">[2]</a> and plenty of other projects and momentum that continue to the time of this writing. Proportionate to the number of participants, the mobilizations were surprisingly successful.</p>
<p> The question, then, is whether they provide a model that can be expanded on. The conventions revealed the risks of initiating a mobilization so far in advance: by the time the event finally occurs, the context may have changed dramatically. Likewise, so much preparation can raise unrealistic expectations; it also invites serious repression and intelligence gathering from the authorities. One might ask whether the US anarchist movement can sustain such costs; on the other hand, one might also ask whether it can afford to remain a marginal participant in others&rsquo; campaigns, as it was throughout much of the past decade. This brings up the most fundamental question: was the explicitly anarchist character of the mobilization a fatally limiting factor, or a starting point towards building a bigger and more independent anarchist movement in the US?</p>
<p> Can we go it alone? Are we better off in the shadows? Or is there another way?
</p>
<h3>Prehistory: The Rise and Fall of the Anti-War Movement</h3>
<p>(This section is revised from a much larger analysis, <a href="/texts/recentfeatures/whattoexpect.php">&ldquo;What to Expect from the Conventions,&rdquo;</a> which appeared on this site in May 2008.)</p>
<p>The so-called &ldquo;anti-globalization movement,&rdquo; named by corporate media with a vested interest in obscuring the possibility of modern-day anticapitalist struggle, emerged as if from nowhere in the late 1990s. In fact, it was the convergence of a wide variety of smaller social currents ranging from indigenous liberation struggles to the do-it-yourself punk scene, all of which had been quietly developing over the preceding years. Perhaps the most surprising accomplishment of the movement was to revitalize street-level conflict, which many had deemed irrelevant in the postmodern era.</p>
<p> The US wing of this movement was not prepared for the sudden changes wrought by September 11, 2001; although the militant anti-IMF protest organized for that month became the first antiwar protest, anarchists swiftly lost the initiative to liberals and communists more familiar with reactive single-issue organizing. To the glee of authoritarians of every stripe, between 2001 and 2003 the antiwar movement replaced the anticapitalist movement in the public eye.</p>
<p> The antiwar movement of the following years failed to stop the war, but succeeded in taming protest itself. Considered as a whole, the worldwide demonstrations on <a href="http://en.wikipedia.org/wiki/February_15,_2003_anti-war_protest" target="_blank">February 15, 2003</a> comprised the most widely attended protest in human history&mdash;and yet they did nothing to hinder the Bush administration. One might say it was a triumph of co-optation that so much outrage and motivation was diverted into ineffectual rituals so soon after anticapitalists had demonstrated the power of direct action. To be fair, the effectiveness of the efforts of 1999-2001 did not become clear until years later when many were no longer paying attention. There were scattered efforts to apply direct action in antiwar efforts, such as the targeting of <a href="http://mfvov.com/blog/?p=505" target="_blank">recruitment centers</a> and <a href="http://en.wikipedia.org/wiki/Port_Militarization_Resistance" target="_blank">ports</a> engaged in military shipping, but these were too little too late. Imagine the effect if a mere tenth of the participants in the February 15 demonstrations had blockaded ports or smashed recruitment center windows!</p>
<p> Some have charged that the antiwar movement failed because it was not empowering for the working class or people of color. This is a half-truth: the antiwar movement failed because it was not empowering to anybody. The groups that dominated it did all they could to limit the tactics and strategies of participants to the lowest common denominator. Few will stick around in a movement that is not committed to or capable of accomplishing its professed objectives, and this is doubly true of people with limited resources who are all too familiar with being exploited for others&rsquo; gain. There were efforts to recruit laborers and people of color, but these rarely created mutually beneficial collaboration and dialogue. It could be charged that organizers sought to involve a wide range of demographics in order to present the movement as diverse, while still endeavoring to control its content and direction. Approaching the antiwar movement as an opportunity to create a mass under liberal leadership, rather than a means of fighting the war machine, actually undermined the possibility of it ever adding up to a durable, empowered mass.</p>
<p> By the middle of Bush&rsquo;s second term, public sentiment was acknowledged to be overwhelmingly against the war, and yet the antiwar movement had effectively collapsed. The tactic of mass mobilization, which liberals had hijacked from radicals, had accordingly been abandoned; protests still occurred, but none drew numbers worthy of the word &ldquo;mass.&rdquo;</p>
<p>    At the opening of 2008, liberal politics beyond the voting booth had been completely deflated by the failure of the antiwar movement. Liberal hopes were once again pinned on electoral politics, and the streets were as quiet as they had been in the mid-1990s when neoconservatives crowed that capitalism had triumphed as &ldquo;the end of history.&rdquo; This was the context in which anarchists prepared to go to Denver and St. Paul.<br />
</p>
<h3>Genesis</h3>
<p>The DNC/RNC mobilizations got started in a relative vacuum. In 2007, when organizers first decided to focus on them, few nationwide events were bringing people together for militant struggle or putting anarchism in the public eye. After the rise and fall of anti-globalization &ldquo;summit-hopping&rdquo; and the resulting backlash, reverting to the mass mobilization model was something of a failure of imagination. This goes double for those who had been saying for years that it was time to find something more effective, without ever presenting a concrete alternative that could fill the same role.</p>
<p> It&rsquo;s important to remember that when the conventions were first chosen as a target, it was not yet clear that the antiwar movement was on its last legs. The previous two election years had both included fierce protests at the Democratic and Republican National Conventions, with plenty of anarchist involvement but little serious advance organizing. Hundreds of thousands of protesters, including thousands of anarchists, had participated in the <a href="http://en.wikipedia.org/wiki/2004_Republican_National_Convention_protest_activity" target="_blank">2004 RNC</a> in New York, though there had been limited coordination or common strategy for anti-authoritarians. With this missed opportunity still fresh in people&rsquo;s minds, it was not unreasonable to expect the upcoming DNC and RNC might offer another chance in a similar context.</p>
<p> To this end, starting in a couple communities and spreading slowly across the country, small knots of anarchists began to discuss the conventions. In the host cities, these coalesced into the <a href="http://www.nornc.org/" target="_blank">RNC Welcoming Committee</a> and <a href="http://dncdisruption08.org" target="_blank">Unconventional Denver</a>; nationwide, a network of ad hoc collectives emerged under the moniker <a href="http://www.unconventionalaction.org" target="_blank">Unconventional Action</a>. From early on, most agreed that there should be a generalized strategy for direct action and an anarchist-organized infrastructure. Some also argued, drawing on examples from earlier mobilizations, that it was important for direct action to start on the first day of the conventions and coincide with other protests, rather than occurring at a separate time.</p>
<p><br />
</p>
<p align="right"><em>&ldquo;Overall, the RNC-WC&rsquo;s early formation, comprehensive membership drives, strategic partnerships, and flexibility will likely result in a more robust and balanced effort than in recent conventions. Consequently, security will likely be more difficult to maintain than in previous years.&quot;</em></p>
<p align="right"><em>&ndash;Department of Homeland Security Report <a href="http://rnc08report.org/engine/uploads/1/dhs-rnc-transport-infra-2008.pdf" target="_blank">[PDF, 359 KB]</a>, March 27, 2008</em>
</p>
<h3>Buildup</h3>
<p>For many, their first exposure to the organizing was a <a href="http://rnc08report.org/archive/403.shtml" target="_blank">humorous video short</a> from the RNC Welcoming Committee, depicting masked anarchists engaging in everyday activities throughout the Twin Cities and ending with the words &ldquo;We&rsquo;re getting ready.&rdquo; Later, humorless state and federal investigators referenced this video during interrogations and presented it at felony trials. When it appeared in August 2007, it showed radicals around the country that organizers in the Twin Cities were already focusing on the RNC and were resourceful and clever to boot.</p>
<p> Similarly, the first groups that appeared under the Unconventional Action banner didn&rsquo;t just put out a general call for organizing against the DNC and RNC, but went ahead and held consultas in their own communities. Once it was clear that some people were already preparing for the conventions, it was easier for others to do the same.</p>
<p> Taking a cue from the <a href="http://en.wikipedia.org/wiki/Dissent!_(network)" target="_blank">Dissent network</a> that had organized against the G8 summits in <a href="http://www.shutthemdown.org/Resources/Ch%202.pdf" target="_blank">England [PDF, 208 KB]</a> and <a href="http://news.infoshop.org/article.php?story=20070612082401642" target="_blank">Germany</a>, the WC organized a <a href="http://www.nornc.org/166" target="_blank">&ldquo;pRe-NC&rdquo; planning conference</a> exactly a year before the RNC. For many younger anarchists not yet entirely clear on the distinction between strategy and tactics, this was itself an educational experience; despite the resultant challenges, <a href="http://www.nornc.org/156/" target="_blank">a blockading strategy</a> emerged for the first day of the convention, relying on a diversity of tactics. Once this element was in place, the RNC mobilization gathered momentum steadily. Groups around the country signed on to the call to shut down the convention, and an Unconventional Action paper <a href="https://www.indybay.org/uploads/2007/12/12/paper_spreads.pdf" target="_blank">[PDF, 8.24 MB]</a> circulated advertising the strategies for both St. Paul and Denver. All this helped build confidence in the protests.</p>
<p> The DNC mobilization got off to a shakier start. Many Denver radicals were less enthusiastic about taking on the police state. <a href="http://www.recreate68.com/" target="_blank">Recreate 68</a>, a leftist umbrella group,<a class="footnote" href="javascript:void(0);" onclick="return overlib('As one cynic quipped, &ldquo;A lot of different things happened in 1968&mdash;not all of them good!&rdquo;', CAPTION, '[3]');" onmouseout="nd();">[3]</a> took the initiative to begin organizing, but it took longer for explicitly anarchist coordination to pick up steam. <a href="http://www.ainfos.ca/07/aug/ainfos00063.html" target="_blank">Early gatherings</a> in Denver drew fewer participants than those in St. Paul, and the goals of the mobilization seemed less clear. As the DNC drew nearer, <a href="http://www.denverpost.com/breakingnews/ci_9719912" target="_blank">a split occurred</a> in R68; meanwhile, Unconventional Denver gained momentum and local participants, and pulled together a week-long schedule <a href="http://www.unconventionalaction.org/downloads/Disrupt_the_DNC.pdf" target="_blank">[PDF, 789 KB]</a> of themed events. The people who organized in Denver took on disproportionately more work, with less support than in those in the Twin Cities; but in fighting this uphill battle, they enabled anarchists to frame the mobilizations as a rejection of representational politics itself, rather than just the Republican Party.</p>
<p> Both Unconventional Denver and the Welcoming Committee met regularly, establishing committees for logistical work and maintaining informative websites. Members of the WC undertook <a href="http://liam.gnn.tv/threads/28676/RNC_Welcoming_Committee_Comes_to_Your_Town?page=1" target="_blank">nationwide speaking tours</a> encouraging groups to coordinate their own participation, and maintained interest with a series of witty pranks and <a href="http://www.nornc.org/2008/03/14/rnc-welcoming-committee-orders-tasers-for-every-protestor/" target="_blank">press statements</a> along the lines of their initial video. Like many public organizing bodies, the WC was beset by painful internal and external ideological conflicts; despite this, they managed to lay the foundations for coordination among anarchists and coalition organizing with progressives.</p>
<p> In May, the WC hosted a <a href="http://www.mediamouse.org/news/2008/06/organizing-repo.php" target="_blank">second pRe-NC</a>, at which organizers from around the country attempted to flesh out the blockading strategy. The participants opted against dividing the city into zones according to level of risk, as had been done in <a href="http://en.wikipedia.org/wiki/Quebec_City_Summit_of_the_Americas" target="_blank">Quebec City</a> and <a href="http://en.wikipedia.org/wiki/27th_G8_summit" target="_blank">Genoa</a>, on the premise that organizers could not determine how the police would behave. Instead, it was agreed that the permitted rally and march would be kept free of direct action, as per the St. Paul Principles; meanwhile, the regions surrounding the convention center <a href=" http://www.unconventionalaction.org/downloads/st_paul_map.pdf" target="_blank">[map PDF, 197 KB]</a> were divided into <a href="http://www.nornc.org/sectors/" target="_blank">seven sectors</a>, so that different organizing groups could choose in advance where and with whom they would act. In the final months before the conventions, <a href="http://actioncamp08.wordpress.com/" target="_blank">direct action trainings</a> took place throughout the Midwest, while affinity groups from one coast to the other finalized their plans and organizers in the host cities rented convergence centers and <a href="http://minnesotaindependent.com/4315/grateful-young-revolutionary-anarchist-motherfuckers-seeking-rnc-accommodations" target="_blank">scrambled to coordinate logistics</a>.</p>
<p> Nothing ever goes as planned, but if you plan and work hard enough, something will happen. The stated goal of blockading the conventions was probably unrealistic, but anarchists had set the stage for a confrontation.<br />
</p>
<h3>The St. Paul Principles</h3>
<p>For years leading up to the conventions, mass mobilizations had been plagued by conflicts between advocates of direct action and other protesters; in some cases, pacifists and authoritarians had attacked militants or actively collaborated with the police against them. The RNC Welcoming Committee took steps to ensure that this would not happen in St. Paul. In February 2008, the Welcoming Committee and Unconventional Action Chicago joined a range of other groups, including the <a href="http://protestrnc2008.org/" target="_blank">Coalition to March on the RNC and Stop the War</a> and the <a href="http://www.antiwarcommittee.org" target="_blank">Anti-War Committee</a>, in drafting an agreement across ideological and tactical lines:</p>
<dl>
&bull; Our solidarity will be based on respect for a diversity of tactics and the plans of other groups.
</dl>
<dl>
&bull; The actions and tactics used will be organized to maintain a separation of time or space.<br /></dl>
<dl>
&bull; Any debates or criticisms will stay internal to the movement, avoiding any public or media denunciations of fellow activists and events.<br /></dl>
<dl>
&bull; We oppose any state repression of dissent, including surveillance, infiltration, disruption and violence. We agree not to assist law enforcement actions against activists and others.
</dl>
<p>This agreement helped to legitimize the anarchists in the eyes of other organizers&mdash;which in turn saved anarchists needless internal bickering over whether or not they were &ldquo;respecting the local community,&rdquo; a frequent stumbling block at mass mobilizations. Even after the RNC, organizers of many stripes respected the St. Paul principles, refusing to denounce or inform on militant activists.<br />
</p>
<p align="center"><a href="/texts/images/rnc2b.jpg" rel="lightbox[rnc]" ><img src="/texts/images/rnc2a.jpg" width="500" height="333"></a></p>
<h3>Attendance</h3>
<p>After all the promotion, where was everyone? The permitted march at the RNC was scarcely a tenth the size of the one in New York four years earlier; there may have been about as many hard-core militants as there had been at prior conventions, but nothing like the numbers imagined by those familiar with the high point of the anti-globalization era.</p>
<p> Several factors probably contributed to this. The conventions occurred away from the coasts, where the majority of radical communities were located. Some had hoped that the resurrected <a href="http://www.studentsforademocraticsociety.org/" target="_blank">Students for a Democratic Society</a> would organize a great deal of youth participation, but this did not occur on a national level. As anarchists had established their own social circles over the preceding years, their presence had decreased in subcultural milieus such as the punk scene, which may have resulted in lower attendance from those demographics. The high price of gasoline may have discouraged others.</p>
<p> Though some diehards showed up to play logistical roles, the generation of anarchists that had been instrumental in the mobilizations from Seattle to Quebec City largely stayed home. One might hypothesize that in this regard, the anarchist movement was still paying off bills from the anti-globalization days: many veterans of that era were still nursing their bitterness, or else tied down by new responsibilities, while many younger anarchists who never participated in a mass mobilization had been turned against them by the lingering backlash. In the buildup to the conventions, impressive new networks were established, but the failure to rebuild the old networks proved costly, as did the general lack of training and experience.</p>
<p> Meanwhile, the NGOs that had been so important in the anti-globalization movement were nowhere to be seen, and the liberal coalitions that had provided the bulk of the anti-war movement were drastically eroded. As mass mobilizations and traditional civil disobedience had produced diminishing returns, many NGOs had shifted away from them; now, without the older generation of anarchists involved, many connections with these groups had been lost.</p>
<p> It wasn&rsquo;t clear until months later just how dramatically the Obama campaign had affected the context, drawing people away from grassroots organizing and into voter registration and similar activities. <a href="http://www.leftturn.org/?q=node/1176" target="_blank">Certain self-described anarchists</a> who said they envied Obama&rsquo;s campaign for its success in mobilizing the masses failed to point out that it flourished to the same extent that our fair-weather allies disappeared. Reformist co-optation is a weapon against popular autonomy and self-determination no less than the tear gas of riot police. On the other hand, this made it all the more important that anarchists emphasize possibilities beyond the voting booth, and in this regard we could have done worse.</p>
<p> All this underscores the generosity of the longtime activists from outside our immediate milieu, such as <a href=" http://www.starhawk.org/activism/activism-writings/RNC2008_4.html" target="_blank">those from the Pagan Cluster</a>, who chose to bring their substantial skills to the mobilizations even as their compatriots stayed home.<br />
</p>
<h3>August 24-28: The Democratic National Convention</h3>
<p align="center"><a href="/texts/images/dnc1b.jpg" rel="lightbox[rnc]" ><img src="/texts/images/dnc1a.jpg" width="500" height="332"></a></p>
<p> People began to trickle into the convergence center in Denver in mid-August. Saturday night, August 23, was the first thickly attended spokescouncil; Unconventional Denver spokespeople appraised a full room of predominantly young anarchists of the various permitted and unpermitted events scheduled for the week, noting to applause that all UD events were unpermitted.</p>
<p> The liberal antiwar march the following day was unexpectedly small. An energetic anarchist-organized Reclaim the Streets march took off on its heels, however, crisscrossing downtown for hours and attracting a wide range of participants. Even after the march reached its destination, at which a standoff with police ensued, it spontaneously departed again; police eventually attempted to corral it between intersections, but the participants escaped through a parking deck. In retrospect, this was perhaps the only action of the entire DNC/RNC mobilization <a href="http://news.infoshop.org/article.php?story=20080824222427109" target="_blank">that was an uncomplicated success</a>. The organizers had correctly predicted that police would be hesitant to attack a mixed crowd the day before the convention, when <a href="http://www.codepink4peace.org/" target="_blank">Code Pink</a> and <a href="http://ivaw.org/" target="_blank">Iraq Veterans Against the War</a> were also in the streets; this helped to get the whole mobilization off on the right foot.</p>
<p> Back at the convergence center that evening, people regrouped to plan an action targeting party fundraisers the following night. In a typical example of how large meetings can get stymied in irrelevant deliberations, it didn&rsquo;t come out until well into the discussion that practically everyone involved also planned to participate in the black bloc called for 6 pm Monday. There had been no planning to speak of for the black bloc, and at that point it was too late.</p>
<p> R68 had reserved Civic Center Park downtown, which hosted ongoing musical performances and Food Not Bombs servings and generally served as a convergence area. This was also the starting point for the aforementioned black bloc, <a href="http://www.crimethinc.com/blog/2008/09/02/rt6-to-press-anecdote-from-denver/" target="_blank">the fate of which</a> is described in the introduction of Rolling Thunder #6. Suffice it to say the bloc didn&rsquo;t get far before being surrounded by police, resulting in approximately 100 arrests; more thorough preparation and strategizing might have produced better results, but at least the attempt produced a situation of social conflict&mdash;albeit at the expense of the other scheduled action, which never occurred. That evening, rebellious young people seemed much more desirous of conflict with the authorities than organized anarchists seemed prepared to facilitate it.</p>
<p> Tuesday saw anarchists scrambling to do jail support; arrestees&rsquo; court dates were all scheduled for September 2, an obvious attempt to paralyze those committed to both mobilizations. Wednesday, hundreds participated in an anticapitalist environmental march; meanwhile, at the convergence center, at which a police raid had been feared all week, warrantless police arrested people outside and used a bulldozer to destroy signs and banners in the parking lot. Later that day, Rage Against the Machine headlined a show that ended with anarchists supporting Iraq Veterans Against the War in an unpermitted march to the convention center. Further confrontations with the police did not occur, though perhaps this was for the best with the RNC around the corner.</p>
<p> Afterwards, <a href="http://news.infoshop.org/article.php?story=20080920110344447" target="_blank">one UD organizer</a> regretted that the mobilization did not produce common cause with other locals against the inequities of capitalism and white supremacy; in this regard, it may have been a missed opportunity to test new strategies for resistance in the Obama era. Despite fears, however, media coverage did not misrepresent anarchists as racists, and locals on the streets seemed to be sympathetic&mdash;an important point of reference for future efforts. Whatever its shortcomings, the mobilization in Denver succeeded in achieving some visibility and built up momentum for the RNC without inflicting unsustainable costs. As the week wound to a close, vehicles packed with anarchists set off for St. Paul.<br />
</p>
<span class="readinggallery"><a href="/texts/images/dnc2b.jpg" rel="lightbox[rnc]" >
<img src="/texts/images/dnc2a.jpg" width="156" height="104"></a>
<a href="/texts/images/dnc3b.jpg" rel="lightbox[rnc]">
<img src="/texts/images/dnc3a.jpg" width="156" height="104"></a>
<a href="/texts/images/dnc4b.jpg" rel="lightbox[rnc]"><img src="/texts/images/dnc4a.jpg" width="156" height="104"></a>
<a href="/texts/images/dnc5b.jpg" rel="lightbox[rnc]">
<img src="/texts/images/dnc5a.jpg" width="156" height="104" style="margin-bottom: 15px"></a>
<a href="/texts/images/dnc6b.jpg" rel="lightbox[rnc]">
<img src="/texts/images/dnc6a.jpg" width="156" height="104" style="margin-bottom: 15px"></a>
<a href="/texts/images/dnc7b.jpg" rel="lightbox[rnc]" ><img src="/texts/images/dnc7a.jpg" width="156" height="104" style="margin-bottom: 15px"></a></span>
<h3>Pre-Emptive Repression in the Twin Cities</h3>
<p>Like Denver, the Twin Cities had never seen a mobilization of this scale; it was a new challenge for anarchists and city officials alike. Although government repression increased to new levels in the months leading up to the RNC, there were precedents within recent memory hinting at what to expect. A decade earlier, the <a href="http://twincities.indymedia.org/2008/aug/ten-year-anniversary-minnehaha-free-state" target="_blank">Minnehaha Free State</a>&mdash;a 16-month anti-road occupation in Minneapolis&mdash;had been infiltrated, harassed, and raided multiple times by hundreds of officers,<a class="footnote" href="javascript:void(0);" onclick="return overlib('The Free State produced an entire generation of Twin Cities activists, some of whom later helped found the WC.', CAPTION, '[4]');" onmouseout="nd();">[4]</a> In July 2000, during <a href="http://www.earthfirstjournal.org/article.php?id=51" target="_blank">protests</a> against the International Society for Animal Genetics (ISAG),<a class="footnote" href="javascript:void(0);" onclick="return overlib('Comically, these were coordinated by the ISAG Welcoming Committee, a group promoting &ldquo;decentralized actions&rdquo; which foreshadowed the RNC WC by failing to engage with corporate media while police mobilized a massive campaign of repression.', CAPTION, '[5]');" onmouseout="nd();">[5]</a> over one hundred people were brutally mass-arrested, and organizers experienced violent house raids and snatch arrests. It should not have been a surprise when these tactics reoccurred eight years later.</p>
<p> After public outcry following the ISAG arrests, the Minneapolis City Council enacted new laws governing police treatment of protesters, but these were repealed in advance of the RNC. The cities of Minneapolis and St. Paul also passed <a href="http://minnesotaindependent.com/4586/rnc-protest-101-extra-credit-schools-churches-funerals-dont-need-permits" target="_blank">a host of new laws</a> regarding permits and protest, and broke out one that had never been used&mdash;the now-infamous <a href="https://www.revisor.leg.state.mn.us/statutes/?id=609.714&amp;year=2002" target="_blank">&quot;crimes committed in furtherance of terrorism&quot;</a>  provision of the Minnesota PATRIOT Act, which defines terrorism broadly enough to encompass civil disobedience.</p>
<p> In August 2007, the night before the pRe-NC began, police from several departments <a href="http://blogs.citypages.com/blotter/2007/08/mpls_police_adm.php" target="_blank">attacked the monthly Critical Mass bicycle ride</a> in downtown Minneapolis, beating and arresting 19 people and exclaiming &quot;See you next year!&quot; The arrestees were bailed out and the conference proceeded as scheduled, but this was a foreshadowing glimpse of the repression to come. Though two arrestees pled guilty to minor traffic violations, the others&rsquo; charges <a href="http://cmsupport.wordpress.com/2008/07/22/83107-critical-mass-legal-support-summary-and-rnc-update/" target="_blank">were later dropped</a>; as of this writing, one arrestee is taking the city government to trial after settlement negotiations failed.</p>
<p> Over the following year, the government sent multiple undercover police officers and federal informants to infiltrate the WC. The long buildup to the convention and the transparency of the WC enabled the state to gather tremendous quantities of intelligence. In the weeks before the RNC, police blatantly tailed and photographed organizers, staked out their houses, and attempted to question them. They also detained and harassed perceived anarchists, photographing them and searching and seizing their belongings and vehicles. Some of these photographs were later used to identify arrestees who would not give their names.</p>
<p> On Friday, August 29, the Ramsey County Sheriff's Department <a href="http://www.tcdailyplanet.net/article/2008/08/30/police-break-down-doors-night-time-raid-anarchist-meeting.html" target="_blank">raided the WC convergence space</a>. They detained several dozen people, including a five-year-old child,<a class="footnote" href="javascript:void(0);" onclick="return overlib('One detainee who attempted to sing to the child to keep him calm was gruffly instructed to &ldquo;Shut the fuck up&rdquo; by a gun-waving officer.', CAPTION, '[6]');" onmouseout="nd();">[6]</a> face down at gunpoint while they searched the building, taking everything from computers to children&rsquo;s artwork. The following morning, police <a href="http://rnc08report.org/archive/404.shtml" target="_blank">raided three houses</a>, arresting four organizers, handcuffing and questioning dozens more, and seizing a great deal more material. The seized items were used as props in a press conference at which Sheriff Bob Fletcher implied that they were dangerous weapons. Two other houses were raided in the course of the RNC: in one case, a federal informant <a href="http://rnc08report.org/archive/734.shtml" target="_blank">entrapped an unfortunate protester</a> into making Molotov cocktails; the other raid was conducted on a space occupied by videographers.</p>
<p> Throughout the following days, undercover snatch squads roamed in unmarked cars, kidnapping organizers wherever they could be found. One legal worker stepped into a courthouse to support an arrested friend, only to be detained and interrogated by Bob Fletcher himself. <a href="http://twincities.indymedia.org/2008/sep/suspicion-infiltrator-confirmed" target="_blank">Andrew Darst</a>, the federal informant who had spent months inside the WC as &ldquo;Panda,&rdquo; invited an organizer to meet him in a public place and identified him to a snatch squad by embracing him&mdash;unwittingly mimicking Judas, who identified Jesus to the Roman soldiers by kissing him.<a class="footnote" href="javascript:void(0);" onclick="return overlib('Imagine the conscience of a person whose chosen career echoes that of the most hated traitor in Christian history.', CAPTION, '[7]');" onmouseout="nd();">[7]</a></p>
<p> Taken as a whole, this was a higher level of repression than had occurred at a mass mobilization in the US in several years. Convergence center raids are not uncommon, the total number of arrests had been higher at the <a href="http://www.nyclu.org/node/1039" target="_blank">2004 RNC</a> in New York, and the bail of targeted arrestees was initially set higher at the <a href="http://www.thenation.com/doc/20031201/blanding" target="_blank">2000 RNC</a>  in Philadelphia; the house raids and snatch squads were more unusual, though precedented by ISAG. But the felony charges brought against the organizers who became known as the RNC 8&mdash;all of whom were indicted on &ldquo;conspiracy to commit riot in furtherance of terrorism,&rdquo; among other charges&mdash;were unlike anything since the <a href="http://en.wikipedia.org/wiki/Chicago_Seven" target="_blank">1968 conspiracy trial</a> following the DNC in Chicago.</p>
<p> None of this could derail the momentum of the organizing, however. The strategy for September 1 had been established far in advance, and scores of autonomous groups had already prepared. If anything, the raids and persecution made the public more sympathetic to the anarchists on the eve of the demonstrations.<a class="footnote" href="javascript:void(0);" onclick="return overlib('This has continued since the RNC demonstrations. Older Twin Cities progressives in particular have mobilized around the RNC 8 case.', CAPTION, '[8]');" onmouseout="nd();">[8]</a><br />
</p>
<h3>Final Countdown</h3>
<p> Despite the raids and arrests, sleep-deprived organizers eventually forced the city to <a href="http://www.nornc.org/2008/08/30/convergence-space-re-opens-moving-forward-with-organizing-for-sept-1/" target="_blank">reopen the convergence center</a>, and on Saturday night hundreds of anarchists from around the country gathered for a spokescouncil. As in Denver, the meeting ended in a tiresome circular discussion; but in this case, because the strategizing was already complete and even the start time of the blockading had been set at a less crowded spokescouncil the previous Wednesday, this focused harmlessly&mdash;if irrelevantly&mdash;on how the actions of September 1 would conclude.</p>
<p> Perhaps the most important thing that occurs at gatherings like this is not the centralized decision-making, but the experience of collective power and determination. There&rsquo;s nothing like the feeling of being in a space with hundreds of comrades who have come to risk everything in the struggle against oppression; it is utterly unlike daily life in the US. At the beginning of the meeting, as the spokespersons of dozens of affinity groups introduced themselves and stated their intentions, the atmosphere was electric. After all the repression of the preceding days, just being present was an act of courage and defiance. Comrades who hadn&rsquo;t seen each other for years, perhaps not since they had last fought side by side, embraced or nodded to one another in passing. Those moments of connection, and the indomitable will to resist that made them count, were themselves a sort of victory.</p>
<p> The following day, everything was suddenly up in the air again. As news came in that another hurricane was headed for New Orleans and rumors circulated that the RNC might be canceled, preparations ground to a halt all around the city, as all eyes focused on the convergence center at which another spokescouncil was taking place. After the Republicans announced that they would hold only <a href="http://www.cnn.com/2008/POLITICS/08/31/rnc.gustav/index.html" target="_blank">a shorter and less attended afternoon session</a>, the spokescouncil agreed that the blockades would go forward, picked a new time for them to occur, and split up so affinity groups could hastily reorganize their plans. Throughout the Twin Cities, police cars prowled and sirens wailed, while paranoid activists wondered whether they would even be able to get downtown the following morning.<br />
</p>
<p align="center"><a href="/texts/images/rnc3b.jpg" rel="lightbox[rnc]" ><img src="/texts/images/rnc3a.jpg" width="500" height="444"></a></p>
<h3>September 1: The Big Day</h3>
<p align="right">
<em>&ldquo;The initial law enforcement response downtown was primarily from individual Patrol Officers, who found themselves outnumbered and facing hundreds of anarchists. Because of radio communication problems, Mobile Field Force either did not respond or responded too late to assist the Patrol Officers.</em></p>
<p align="right"><em> Between approximately 12:30 p.m. and 3:00 p.m., the anarchists moved relatively freely through downtown Saint Paul. Loose items, including planters, refuse containers, newspaper boxes and traffic signs, became weapons of convenience for anarchists, who also used them to block streets. During their rampage, the anarchists broke windows on buildings and police cars, slashed tires on police cars and media vehicles, blocked streets and attacked individuals, including police officers, RNC delegates, and bystanders.<a class="footnote" href="javascript:void(0);" onclick="return overlib('This is presumably disinformation, though there are reports of a conflict between anarchists and pro-war demonstrators. Compared to police officers, anarchists are extremely principled about not attacking civilians.', CAPTION, '[9]');" onmouseout="nd();">[9]</a> They also attempted to prevent RNC delegates and delegate buses from entering the Xcel Energy Center. Throughout the day, the anarchist groups engaged police in a game of &lsquo;whack-a-mole,&rsquo; in which police were always chasing, but never controlling, the anarchists.</em></p>
<p align="right"><em> Shortly before 3:00 p.m., MFF units gathered south and east of the Landmark Center and began moving the anarchists out of downtown. This led to a large confrontation between anarchists and law enforcement along Kellogg. During these confrontations, MFF Officers used less-than-lethal weapons. Facing MFF pressure, the anarchist groups split at Kellogg and Robert, one group fleeing to the area of 9th and Temperance, where they were arrested or escaped. The other group fled to Shepard Road. The anarchists on Shepard Road were driven west to a park near Chestnut Road. At that location, the anarchists merged with a crowd of bystanders. The MFF units surrounded and detained the entire crowd.&rdquo;</em></p>
<p align="right"><em>    -<a href="http://rnc08report.org/archive/667.shtml" target="_blank">Report of the RNC Public Safety Planning and Implementation Review Commission</a></em><a href="http://rnc08report.org/archive/667.shtml" target="_blank"></a></p>
<p>At 11 a.m., the Coalition to March on the RNC and Stop the War rally kicked off at the capitol, while three miles away police prevented Macalester students from leaving to march to the rally site. Meanwhile, anarchists all over the city were getting into position and some of the first blockades were going up. By 12:30, the Funk the War march had left the rally area, encountering a confused police attempt to stop it, and the first hard blockade was in place on the I-94 off-ramp on the east side of St. Paul. At 1 p.m., the permitted march departed from the capitol; at the same time, there were major confrontations between police and the Funk the War march, the black bloc moving through northwest downtown, and the Bash Back! blockade. Protestors moved in and out of intersections evading the police; in the southwest and northeast, two new hard blockades were in place.</p>
<p> Between 1 and 2:30 p.m., a breakaway march departed from the Funk the War march, while the black bloc was joined by many from Bash Back! All over town, windows were smashed, squad car tires were slashed, and delegate buses were swarmed. Police responded with horse charges, pepper spray, tear gas, and rubber bullets. By 2:30, the permitted march had returned to the capitol and the Macalester student march was finally on its way. </p>
<p align="center"><a href="/texts/images/rnc4b.jpg" rel="lightbox[rnc]" ><img src="/texts/images/rnc4a.jpg" width="500" height="335"></a></p>
<p>Shortly before 3, the police dispersed the breakaway march, and hundreds of anarchists headed to the capitol to regroup, quieting the north part of St. Paul. Meanwhile, near the Xcel center on Kellogg, protestors were roving from intersection to intersection in increasingly large groups; many participants in earlier actions joined the Pagan Cluster and Funk the War there. </p>
<p> After calls for reinforcement went out over the comms system, the anarchists who had regrouped at the capitol began to march west around the perimeter fence in the second Anticapitalist Bloc of the day. Within the hour, the police utilized tear gas, pepper spray, concussion grenades, and marker rounds to clear the area around the Xcel center, pushing the Funk the War bloc east and bringing out the National Guard to hold the ground they had retaken. Around 4 p.m., police illegally raided the communications office; the arrestees were originally held on probable cause for felonies, but were released without having been charged. Meanwhile, the new Funk the War bloc dragged barricades into the street in the course of its retreat, then split up; some participants were mass-arrested in northeast downtown, while others traveled west on Shepard and still others safely dispersed.</p>
<p> Late that afternoon, over 200 people were corralled at the intersection of Shepard and Ontario, and most were mass-arrested. Most of the detainees were simply there to attend the &ldquo;Take Back Labor Day&rdquo; concert on Harriet Island.</p>
<p align="center"><a href="/texts/images/rnc5b.jpg" rel="lightbox[rnc]" ><img src="/texts/images/rnc5a.jpg" width="500" height="332"></a></p>
<p> In all, downtown St. Paul witnessed over ten hours of running confrontations. After the initial blockades and marches were broken up, protesters repeatedly found new convergence points such as the Funk the War sound system. That night, at a spokescouncil hastily convened on a college campus, a few dozen exhausted participants compared notes and discussed plans for the following days.</p><br />
<p><strong>Chronological Maps of Police and Protester Activity in St. Paul on September 1</strong></p>
<span class="readinggallery">
<a href="/texts/images/rnc_maps-1.gif" rel="lightbox[rnc]" >
<img src="/texts/images/rnc_maps-1a.gif" width="156" height="201" style="margin-bottom: 15px"></a>
<a href="/texts/images/rnc_maps-2.gif" rel="lightbox[rnc]" >
<img src="/texts/images/rnc_maps-2a.gif" width="156" height="201" style="margin-bottom: 15px"></a>
<a href="/texts/images/rnc_maps-3.gif" rel="lightbox[rnc]" ><img src="/texts/images/rnc_maps-3a.gif" width="156" height="218" style="margin-bottom: 15px"></a></span>
<p><em><a href="/texts/images/rnc_maps.pdf" target="_blank">Download Hi-Res PDF of the maps here [754 KB].</a></em></p>
<span class="readinggallery"><a href="/texts/images/rnc10b.jpg" rel="lightbox[rnc]" >
<img src="/texts/images/rnc10a.jpg" width="156" height="104"></a>
<a href="/texts/images/rnc11b.jpg" rel="lightbox[rnc]">
<img src="/texts/images/rnc11a.jpg" width="156" height="104"></a>
<a href="/texts/images/rnc9b.jpg" rel="lightbox[rnc]"><img src="/texts/images/rnc9a.jpg" width="156" height="104"></a>
<a href="/texts/images/rnc8b.jpg" rel="lightbox[rnc]">
<img src="/texts/images/rnc8a.jpg" width="156" height="104" style="margin-bottom: 15px"></a>
<a href="/texts/images/rnc7b.jpg" rel="lightbox[rnc]">
<img src="/texts/images/rnc7a.jpg" width="156" height="104" style="margin-bottom: 15px"></a>
<a href="/texts/images/rnc6b.jpg" rel="lightbox[rnc]" ><img src="/texts/images/rnc6a.jpg" width="156" height="104" style="margin-bottom: 15px"></a></span>
<h3>Communications</h3>
<p> The group that had formed to coordinate communications opted to use Twitter to distribute SMS messages to participants, as the <a href="http://www.appliedautonomy.com/txtmob.html" target="_blank">txt.mob</a> system used at the 2004 RNC had sometimes suffered significant delays.<a class="footnote" href="javascript:void(0);" onclick="return overlib('There were also security concerns, as txt.mob records had been subpoenaed in subsequent court cases.', CAPTION, '[10]');" onmouseout="nd();">[10]</a> The comms team established user groups around themes such as food and police activity, including one for each sector, so people could sign up to receive information only about subjects that concerned them. Scouts on the ground reported back to a communications hub at which reports were verified and sent out.</p>
<p> After the raid on the comms space, the Coldsnap Legal Collective&rsquo;s <a href="http://rnc08report.org/archive/336.shtml" target="_blank">Twitter</a> became the de facto comms system, as people called the jail support hotline to report unfolding events and legal workers passed these on to the public. On Friday, August 29, only 23 people were following Coldsnap Legal; a week later, over 1800 depended on it for news updates.</p>
<p> In some situations, the comms system enabled groups to evade police attacks and disperse safely. Others users complained that the flow of information was overwhelming and it was hard to make practical use of it on the streets, especially after the comms hub was raided and everyone was depending on Coldsnap&rsquo;s single feed.</p>
<p> Participants in the comms team have since published an <a href="http://comms.hackbloc.org/node/101" target="_blank">detailed analysis</a> of their efforts.</p>
<h3>September 2-4: Continued Confrontations</h3>
<p>As hoped, the events of September 1 set the stage for the rest of the week, emboldening protesters and causing police to behave irrationally. On Tuesday, just as the permitted Poor People&rsquo;s March was concluding, police shut down an attempted Rage Against the Machine concert nearby. The two crowds mingled; few avowed anarchists were present, but there was a rebellious atmosphere, as participants had presumably seen footage of the previous day&rsquo;s events. Police eventually <a href="http://rnc08report.org/archive/608.shtml" target="_blank">forced the crowd to disperse</a> by attacking with smoke bombs, tear gas grenades, and marker rounds. A similar scene played out the following night after the Rage Against the Machine show in Minneapolis; there was a fair bit of rebellious energy in the crowd, but no organized initiative to get things off the ground, and eventually the police attacked, divided, and dispersed the small march that occurred, <a href="http://rnc08report.org/archive/600.shtml" target="_blank">arresting 102</a>. Some have speculated as to what might have occurred at these events had anarchists been present with a plan; many anarchists were in jail or busy doing arrestee support, but others did not show up because they had been so focused on September 1 as to be totally unprepared for the rest of the week.<a class="footnote" href="javascript:void(0);" onclick="return overlib('While organizers in Denver risked spreading themselves too thin between different events, in St. Paul it could have been advantageous to plan more past September 1; on the other hand, there may simply not have been enough time and resources for this.', CAPTION, '[11]');" onmouseout="nd();">[11]</a></p>
<p> On the final day of the RNC, there was a march organized by the Anti-War Committee, a group open to civil disobedience tactics. Police blocked all the bridges downtown with snowplows. A reporter who had called anarchists &quot;hooligans&quot; three days earlier said, &quot;This city has never felt more like a police state.&quot; After police canceled the march permit, over a thousand protesters spent several hours attempting to make their way out of downtown. Once again, there were few avowed anarchists present, but the crowd was not exactly docile. As night fell, police began tear-gassing and pepper-spraying indiscriminately, eventually forcing approximately 350 people&mdash;including reporters and civilians&mdash;onto Marion Street bridge and <a href="http://minnesotaindependent.com/7564/riot-police-poised-at-capitol-following-arrests-march-begins" target="_blank">arresting them all</a>. This flagrantly illegal mass arrest was a public relations disaster for the city.<br />
</p>
<h3>Did the Strategy Work?</h3>
<p> The blockades failed to prevent delegates from reaching the convention. This may have been in part because of the last minute change in plans on the part of the RNC: it must have been easier to get half as many people into the convention center as originally planned. The small turnout from outside the anarchist camp was also a contributing factor: had thousands more protesters showed up, many would surely have reinforced the blockades.</p>
<p> Ineffective as they were at their stated purpose, the blockades created an unpredictable situation, stretching and distracting the police. By forcing the authorities to focus on protecting access to the RNC rather than controlling protesters, the blockading strategy opened space for other tactics which might otherwise have been impossible. Had there simply been a call for confrontational marches, the police might have been able to surround and neutralize them, as in Denver on August 25. This illustrates the strategic difference between what one calls for and what one actually hopes to do.</p>
<p> The strategy also offered a point of entry for everyone who wished to participate in direct action. It gave anarchists something to plan around, which helped them feel invested in the mobilization. Without this, it might have been difficult to get people to come to the RNC in organized affinity groups, ready to act.</p>
<p> There is a tension in mass action strategizing between concentrating forces for maximum strength and dispersing them for maximum surprise; if protesters are too concentrated, they can be trapped, while if they are spread too thin, they cannot support each other. The Seattle WTO blockades took place in a space of a few blocks; the blockades at the 2007 G8 in Germany were spread out over many miles. Though some protesters did spend hours wandering St. Paul looking for the action, by and large the blockading strategy resulted in an optimal distribution of forces.<br />
</p>
<p align="center"><a href="/texts/images/rnc12b.jpg" rel="lightbox[rnc]" ><img src="/texts/images/rnc12a.jpg" width="500" height="333"></a></p>
<h3>Behind Enemy Lines</h3>
<p align="right"><em>&ldquo;As told to this Commission, the St. Paul Police Department&rsquo;s approach to anarchist&rsquo;s [sic] efforts to block a street was: &lsquo;If we don&rsquo;t need a particular intersection, let them have it.&rsquo; The SPPD believed, through this approach, they could prevent encounters with anarchists from escalating, thereby limiting violence and the need for large numbers of arrests. One consequence of this strategy, however, was a heavy emphasis on mass crowd control<a class="footnote" href="javascript:void(0);" onclick="return overlib('Indeed, at least 600 of the 818 people arrested during the RNC were captured in mass arrests.', CAPTION, '[12]');" onmouseout="nd();">[12]</a> versus using extraction or targeted arrests when anarchists were conducting violent or unlawful activities.&rdquo;<br />
-<a href="http://rnc08report.org/archive/667.shtml" target="_blank">Report of the RNC Public Safety Planning and Implementation Review Commission</a></em></p>
<p> The police strategies at the 2004 RNC in New York and at the 2008 RNC in St. Paul were both typical of those police departments. The NYPD is one of the world&rsquo;s largest standing armies. It is accustomed to crowd control, and was still benefiting from post-9/11 patriotism in 2004&mdash;hence it was easy to line the streets with thousands of police and make targeted arrests rather than depending on chemical weapons. St. Paul, on the other hand, is a smaller city unused to large events. The liberal public was not excited about the RNC occurring there, so the government <a href="http://minnesota.publicradio.org/display/web/2008/08/28/downtown_makeover/?refid=0" target="_blank">hurried to reassure them</a> that there would be no riots, oppressive policing, or traffic disruptions, promising a surge in shopping and emphasizing the $50 million security budget provided by the Republican National Committee.</p>
<p> The Republican National Committee also hit on the innovation of <a href="http://www.commondreams.org/headline/2008/09/04" target="_blank">offering $10 million to cover any lawsuits from police misconduct</a>&mdash;acknowledging that, even with the repressive laws on the books, the desired level of repression would demand massive illegal activity from the forces of law and order. Thus, while the city was concerned about PR, the police had a free hand to break their own laws to the tune of $10 million.</p>
<p> In the months leading up to the RNC, a <a href="http://rnc08report.org/archive/437.shtml" target="_blank">conflict</a> played out between Ramsey County Sheriff Bob Fletcher, on whose shoulders rested the actual dirty work, and the St. Paul Police Department, which was struggling to maintain its image. While the SPPD had <a href="http://rnc08report.org/archive/361.shtml" target="_blank">promised a &ldquo;St. Paul model&rdquo;</a> in contrast to the notoriously brutal <a href="http://video.google.com/videoplay?docid=7557174318773212602" target="_blank">&ldquo;Miami model&rdquo;</a> from the <a href="http://www.crimethinc.com/texts/pastfeatures/miamiheat.php" target="_blank">2003 FTAA ministerial</a>, Fletcher let it be known that the police would be out to crack heads, <a href="http://www.startribune.com/politics/national/conventions/26894609.html?elr=KArksUUUU" target="_blank">predicting correctly</a> that there would be at least 800 arrests.</p>
<p> Yet despite millions of dollars and months of intensive training, the police were not prepared to control even a few hundred anarchists coordinated within a versatile framework. Most of the police had been positioned along the permitted march route; <a href="http://www.youtube.com/watch?v=gkZvtGCh5YA" target="_blank">dispatch tapes</a> reveal that between noon and 2 p.m. on September 1, a communications breakdown permitted anarchists to act freely throughout downtown. Fletcher later said, &quot;We had 15 officers responsible for the conduct of 500 anarchists. They were outnumbered 40 to one.&quot; This should dispel the myth of an invincible police state.</p>
<p> With the inflexibility typical of authoritarian institutions, once the police escalated to more repressive tactics, they found it impossible to de-escalate even when it was in their interest. Anarchists were not actively organized after September 1, but that first day was enough; after that, the police inflicted defeat after defeat upon themselves, needlessly attacking and radicalizing civilians.</p>
<p> If the RNC had occurred without direct action or police brutality, this would have signified that the resistance that flared up at the WTO protests had been definitively quashed during the Bush years, heralding a return to capitalist consensus. Instead, for the first time in years, militant confrontations set the tone for the protests and the police responded with indiscriminate violence&mdash;a major black eye for the government after all its assurances. Riot police filled the air with tear gas directly in front of delegate hotels and illegally arrested <a href="http://www.huffingtonpost.com/tom-dantoni/amy-goodman-violently-arr_b_123062.html" target="_blank">prominent journalists</a> and at least one Republican delegate.</p>
<p> The events of September 1 indicate that even against the assembled might of the state, a small organized group can escalate social conflict and produce a situation in which others join in. Comparing the RNC to the DNC, we can see that the authorities wouldn&rsquo;t have responded with such intense repression if anarchists hadn&rsquo;t done effective organizing.</p><br />
<h5>The Republican National Committee hit on the innovation of offering $10 million to cover any lawsuits from police misconduct&mdash;acknowledging that, even with the repressive laws on the books, the desired level of repression would demand massive illegal activity from the forces of law and order.<br />
</h5>
<p align="center"><a href="/texts/images/rnc13b.jpg" rel="lightbox[rnc]" ><img src="/texts/images/rnc13a.jpg" width="500" height="502"></a></p>
<h3>Losing Our Innocence</h3>
<p> Whatever victories occurred in St. Paul came at a great price, however. The few felony charges stemming from the RNC in 2000 had been a major shock to activists; in contrast, <a href="http://rnc08report.org/archive/413.shtml" target="_blank">159 people were arrested for supposed felonies</a> during the 2008 RNC. Though most of those charges <a href="http://rnc08report.org/archive/814.shtml" target="_blank">were dropped or lowered</a>, as of this writing 15 face pending felonies, several more have pled, and new charges <a href="http://rnc08report.org/archive/525.shtml" target="_blank">may still be filed</a>. Between 2000 and 2008, anti-anarchist repression had escalated dramatically, as FBI witch hunts sent <a href="http://www.crimethinc.com/texts/recentfeatures/greenscared.php" target="_blank">environmental activists</a> and animal liberationists to prison for up to decades. No convictions from mass mobilizations had resulted in multiple-year prison sentences in the US since the 1990s, but <a href="http://rnc08report.org/archive/844.shtml" target="_blank">Matthew DePalma</a>, an inexperienced youth entrapped into making Molotov cocktails by informant Andrew Darst, was sentenced to 42 months after pleading guilty. The other two defendants in federal cases, <a href="http://www.freethetexas2.com/" target="_blank">Bradley Crowder and David McCay</a>, currently await sentencing, and several other RNC defendants may do time as well.</p>
<p> The RNC 8 case is perhaps the first instance in which public organizers have been charged with terrorism simply for coordinating the logistics of a mass mobilization. In this regard, it echoes the <a href="http://www.shac7.com/case.htm" target="_blank">SHAC 7</a> case. It&rsquo;s interesting how the concept of terrorism has evolved over the past decade; after the September 11 attacks rocketed it into prominence, the meaning of the term could only expand. At first, terrorism was associated with Al Qaeda, an exotic, distant enemy almost all America could agree to hate. Then it expanded to include eco-terrorists and animal rights extremists&mdash;a demographic somewhat closer to home. By the time of the 2008 RNC, the sphere designated by the term seemed to be broadening at an unstoppable pace. As of this writing, the terrorism charges against the RNC 8 <a href="http://minnesota.publicradio.org/display/web/2009/04/09/rnc8_terrorism_charges_dropped/" target="_blank">have just been dropped</a>, signifying that the terrorism bubble has perhaps reached the limits of its expansion; meanwhile, felony conspiracy charges against the RNC 8 remain, and their trial promises to be a major event.<a class="footnote" href="javascript:void(0);" onclick="return overlib('It&rsquo;s noteworthy that the conspiracy charges against the RNC 8 were brought by Ramsey County, not the federal government. Although it seems strange that a liberal local government would be more eager to press terrorist conspiracy charges than the federal government under Bush, this appears to indicate that the RNC 8 case may not be an indication of federal tactics to come so much as the initiative of overzealous local authorities.', CAPTION, '[13]');" onmouseout="nd();">[13]</a></p>
<p> If the authorities create a new generation of activists inured to the threat of prison time and the accusation of terrorism, they may regret it. On the other hand, the anarchist movement in the US is small and has very limited resources; there are only so many expensive and exhausting trials it can afford. Only time&mdash;and the outcomes of the pending cases&mdash;will tell if the repression resulting from the RNC mobilization is sustainable.</p>
<p> Some have pointed to this repression and the case of the RNC 8 in particular as evidence that it is foolish to organize resistance publicly.<a class="footnote" href="javascript:void(0);" onclick="return overlib('Those who glorify clandestine action over participatory militant organizing should ask Daniel McGowan, who participated in several major Earth Liberation Front actions and went on to play a central role in organizing the 2004 RNC protests, which he found to be more effective. His address can be found at www.supportdaniel.org.', CAPTION, '[14]');" onmouseout="nd();">[14]</a> This is alarmist and misguided; the authorities would like nothing better than for anarchists to draw this conclusion and retreat into the shadows, losing track of one another and forfeiting the ability to coordinate their own large-scale initiatives. It&rsquo;s important not to be careless, but effective organizing against the government will always result in repression, whether or not people choose public roles. In this regard, it&rsquo;s noteworthy that one of the RNC 8 was not involved in the Welcoming Committee, but is being accused as an organizer nonetheless. The more public our efforts are, the more we can build up momentum and support, and the better equipped we will be to handle repression.</p>
<p> One example bears mentioning here. In the months leading up to the RNC, the <a href="http://www.organizepittsburgh.org/" target="_blank">Pittsburgh Organizing Group</a>, which first received national attention during preparations for the Miami FTAA protests in 2003, <a href="http://www.ainfos.ca/en/ainfos21074.html" target="_blank">publicly announced</a> that it would coordinate blockades in sector 1 of downtown St. Paul, going so far as to identify the intersection. This struck anarchists of a more clandestine bent as insane; some hypothesized that it must be a red herring to mislead the police. But come September 1, true to their word, Pittsburgh activists <a href="http://news.infoshop.org/article.php?story=20080901174615324" target="_blank">drove a car</a> into the middle of the intersection at 7th and Wall, disabling it and shutting down the intersection for some time; all their charges <a href="http://worcester.indymedia.org/node/46001" target="_blank">were subsequently dropped</a>. Let no one say it is impossible to organize resistance publicly.<br />
</p>
<h3>Learning from Infiltration</h3>
<p>Debates about public organizing aside, the WC&rsquo;s approach made it easy to infiltrate. Some infiltrators were more competent than others; nevertheless, their appearance and behavior differentiated them from others in the community, raising suspicions. Realizing this, the FBI <a href="http://www.citypages.com/2008-05-21/news/moles-wanted/" target="_blank">attempted to recruit</a> at least one individual to infiltrate &quot;vegan potlucks,&quot; convinced he would be trusted as he &quot;looked the part.&quot; By and large, infiltrators seemed uninterested in radical politics and visibly uncomfortable with the lifestyles of some anarchists, and displayed classic informant behavior such as asking inappropriate questions while accusing others of being agents. It is important not to decide who is trustworthy solely on appearances, but it's noteworthy that the infiltrators turned out to be the ones who looked like cops. The WC had identified most of the infiltrators in its midst long before they were outed, but did not expel them for fear of defaming innocent people. Good intentions are admirable, but we must also be able to protect ourselves&mdash;the WC might have saved themselves a lot of grief by doing so.</p>
<p> The paranoia that often passed as security culture in convention organizing offered limited protection. Vouching systems failed to keep out informants such as <a href="http://www.brandondarby.com/" target="_blank">Brandon Michael Darby</a>, and taking batteries out of cell phones&mdash;as Darby did to create trust while wearing a wire&mdash;did not prevent surveillance. Real security culture depends on deep-rooted social bonds and shared context, not to mention trusting one&rsquo;s intuition. Anarchists' greatest strengths lie in solidarity and community&mdash;we can find risk-free ways to cooperate with people who are new to us, and take risks only with those we know and trust intimately. People in the targeted communities have since expressed that they find it difficult to trust anyone; this is exactly what the authorities want.<br />
</p>
<h3>Media as a Weapon</h3>
<p>The RNC protests received nationwide coverage, but not as much as many had hoped. At this point, anarchists have to accept that the corporate media is not going to cover every broken window. The setbacks following September 11, 2001 showed how important it is to be able to maintain momentum without media attention. Anarchist organizing has to be aimed at achieving something more lasting than airtime on the evening news.</p>
<p> At the same time, it&rsquo;s important to see how media strategies affect police repression and public response. Before the RNC, the police <a href="http://minnesota.publicradio.org/display/web/2008/08/30/more_raids/#" target="_blank">used corporate media</a> to assure the public of their good intentions and smear anarchists as violent, waste-throwing invaders. This was essential to prepare the grounds for repression; police have been using these propaganda techniques since the Seattle WTO protests, when they learned to script a strategy beforehand lest the media accidentally focus on real issues.</p>
<p>Unfortunately, the WC&rsquo;s approach to the media played into the hands of the police. The WC experimented with various media strategy, ranging from complete non-engagement to pre-written statements and theatrical stunts. However, they did not fully engage with corporate media until <a href="http://twincities.indymedia.org/2008/sep/video-rnc-welcoming-committee-unmasked-press-conference-9408" target="_blank">after the raids</a>, when those who had not been arrested appeared unmasked at the newly re-opened convergence space and took questions under their real names. This initial reticence allowed the WC to retain its mystique, but it also permitted the police to gain the upper hand, leaving the WC constantly on the defensive.</p>
<p> The corporate media is corrupt and vapid, and cannot be trusted to represent radicals&mdash;or anyone&mdash;fairly. At the same time, it&rsquo;s important to see the media as the battlefield on which the police position themselves to attack. The WC did a brilliant job of using independent media to build excitement in the radical community; it is unfortunate that it did not also find ways to exploit the corporate media to outflank the police.<br />
</p>
<h3>Diversity of Tactics</h3>
<p align="right"><em>&ldquo;The very use of the word &lsquo;violence&rsquo; to describe the actions of protesters in the face of the police state we witnessed is ridiculous. Pepper spraying a girl repeatedly in the face after she attempted to hand a flower to a police officer is violence. A broken Macy's window is not. And even though some activists don't prefer property damage as a tactic, maintaining some amount of perspective is important. What is a broken window compared to a million Iraqis killed, or entire cities destroyed by the U.S. occupation forces? A whole lot of windows get broken when the U.S. drops bombs. Which is the bigger concern?&rdquo;</em></p>
<p align="right"><em>    -<a href="http://twincities.indymedia.org/2008/sep/anti-war-march-organizers-express-solidarity-and-respect-diverse-tactics" target="_blank">Katrina Plotz</a>,
member of the Anti-War Committee and<br />
the Coalition to March on the RNC and Stop the War</em></p>
<p>By September 3, one could hear all the discussions from 1999 beginning all over again. Is property destruction violence? Is it strategic? What tactics can build an effective movement for liberation? To some extent, it&rsquo;s good news when we have to start from scratch again about these issues&mdash;it means new people are involved in the discussion. Too much agreement on these questions is a sign of stagnation and insularity.</p>
<p> At the same time, intra-movement bickering provides the authorities valuable opportunities, so it is potentially historic that the St. Paul Principles served to prevent it. It remains to be seen whether this agreement was a precedent for future mobilizations or simply an anomaly produced by a dwindling antiwar movement. Would other protest groups have sought mutual respect with anarchists if there had been more influential allies available?</p>
<p> At the Seattle WTO protests, militant anarchists were a minority who exerted influence by acting outside the central organizing framework. In St. Paul, they were intimately involved in coordinating that central framework. Does this indicate that anarchism is shifting from the margins to become a significant force in political organizing? Or will the intensity of government repression in St. Paul discourage organizers from participating in future mobilizations based on diversity of tactics? Or, for that matter, did anarchists simply inherit the antiwar movement after everyone else had abandoned it?<br />
</p>
<h3>Party Like It&rsquo;s 1999</h3>
<p>After the MTV success of Nirvana and the explosion of &ldquo;grunge&rdquo; music, record labels sought for years to find the &ldquo;next Seattle.&rdquo; Radicals who grew up on footage of the riots outside the Seattle WTO summit have engaged in a similar pursuit throughout the past decade. The Seattle WTO protests have become a common point of reference for both protesters and police. For the former, they are a sort of creation myth, and a messiah some believe will come again; but you can never repeat the past, even if it inspires you to make new history.</p>
<p> Let&rsquo;s compare the RNC protests in St. Paul with the WTO protests, then, since it is practically impossible not to. A great deal of the organizing for Seattle was funded by NGOs, while the DNC and RNC mobilizations came entirely out of grassroots initiatives. There were only a few hundred utterly unprepared police in Seattle, while over the past decade events such as the RNC have come to be defended by literally military occupations; in that light, it is a miracle any direct action occurred in St. Paul at all. Some New York anarchists who had participated in the 2004 RNC reported that they had a much more fulfilling experience in St. Paul. If it were possible to compose an equation charting dollars spent on security and policing against numbers of protesters, minutes of airtime, and degrees of disruption, we might find that the 2008 RNC scored fairly well compared to the WTO protests.</p>
<p> Yet such an equation would tell us nothing about how effective the RNC mobilization was at actually bringing us closer to liberation. The critical difference between Seattle and St. Paul was that the WTO protests brought tens of thousands of people, including but not limited to anarchists, together in an unfamiliar and inspiring situation. The RNC mobilization was a much more limited affair. However successful our mobilizations are in themselves, they are useless if they do not ultimately enable us to generalize the struggle against hierarchy.<br />
</p>
<h3>Critical Assessment</h3>
<h5>    It remains to be seen how the precedents set at the RNC, during a comparatively quiet phase of social struggle, will influence events next time resistance becomes widespread.</h5>
<p> Viewed as a means of breaking a few windows or obtaining television airtime, any multi-year organizing effort is extremely inefficient. But the year and a half of preparation was valuable in itself as a means of building networks, visibility, and experience; the same goes for the legal support phase afterwards. Regardless of whether the RNC was successfully blockaded, the real significance of the mobilization lies in the way it raised the bar for what it means to organize as anarchists. If those who cut their teeth preparing for the convention continue to mobilize nationwide networks, organized into autonomous affinity groups within a larger strategic framework, it will have been worth the trouble. Often it is events like the RNC, or for that matter <a href="http://www.independent.co.uk/news/world/europe/tear-gas-fills-thessalonikis-riottorn-streets-as-running-battles-mark-end-of-eu-summit-541471.html" target="_blank">the protests against the EU summit in Greece</a> in 2003, that lay the groundwork for anarchist participation in more spontaneous and far-reaching uprisings such as the recent ones in <a href="http://news.infoshop.org/article.php?story=2009010801341349" target="_blank">Oakland</a> and Greece.</p>
<p> So intensive organizing is valuable in itself&mdash;but was the RNC the most sensible target? Probably not. As described, when it was first chosen, anarchists expected it to attract tens of thousands of protesters from other demographics. Once upon a time, the Republicans seemed invincible&mdash;by the time we finally built up the courage to take them on, they were so weakened that we could not build a long-term organizing strategy upon opposing them.<a class="footnote" href="javascript:void(0);" onclick="return overlib('See David Graeber&rsquo;s &ldquo;The Shock of Victory,&rdquo; available at www.infoshop.org.', CAPTION, '[15]');" onmouseout="nd();">[15]</a> Between the backlash against Bush, the hurricane, and the revelation that Palin&rsquo;s unwed teenage daughter was pregnant, the RNC would have been a disaster even without anarchist resistance.</p>
<p> Obama&rsquo;s election marked the definitive end of the context that generated the RNC protests. Now that the Bush years are over, anarchists should congratulate ourselves on having survived a difficult era with at least some vestiges of continuity and collective memory intact. The Obama era poses its own challenges; we have to find new ways to mobilize and reach out to potential comrades. We must lay down a root system that can sustain us well into the 21st century, so we can build on experiences such as the DNC and RNC mobilizations.<br />
</p>
<h3>Backlash</h3>
<p>As mentioned above, a few self-described anarchists had been horrified that others were mobilizing militant resistance to both political parties rather than trying to emulate the Obama campaign.</p>
<p> In November 2008, while many who had participated in the DNC and RNC mobilizations were busy coordinating legal support, these individuals resurfaced with a tortuous <a href="http://news.infoshop.org/article.php?story=20081121130038715" target="_blank">call</a> to attend Obama&rsquo;s inauguration in a spirit of &ldquo;presence rather than protest.&rdquo; The idea was to &ldquo;gather as a bloc, unmasked and with open arms, respecting the celebratory spirit of the day&rdquo; and &ldquo;illustrate the many moments when people on this continent and across the world aspired to better approximations of freedom.&rdquo; Perhaps because there was nothing else scheduled for the inauguration, a few respected organizing groups and a fair number of individuals signed on to the call, but its apparent rejection of militant opposition provoked vicious controversy. In the end, despite other calls, no other mobilizations came together for the inauguration, and scant few people participated in the &ldquo;Celebrate People&rsquo;s History &amp; Build Popular Power&rdquo; bloc.</p>
<p> It&rsquo;s hard not to interpret this call an as opportunist attempt to counteract whatever momentum towards militant organizing had come out of the convention protests. The originators of the call feared that if anarchists took a stand against Obama it would guarantee &ldquo;irrelevance,&rdquo; but the outcome showed that however limited the social base for confrontational direct action might be, the social base for a more conciliatory anarchism was practically nonexistent. Perhaps, in this era of reformism and co-optation, resistance will be militant or else will not be at all.</p>
<p> In the buildup to the DNC and RNC protests, anarchists had emphasized opposition to all politicians and parties, including Obama. The absence of any visible protest at the inauguration, despite the precedents from the two previous inaugurations and the desire to maintain momentum from the conventions, indicates that the militant wing of the anarchist movement had exhausted itself. Perhaps if organizers had included plans to protest at the inauguration in the mobilization against the conventions, emphasizing that this would occur whoever won the election, things might have played out differently. There are risks to picking targets far in advance, but also to not doing so.</p>
<p> This anecdote illustrates how militant victories, however modest, can provoke internal as well as external backlash. It also shows how reformist victories can divide and disable anarchist organizing. Although the inauguration may not have been the most strategic opportunity to manifest opposition, it is important not to forget how many other people have a stake in resisting the oppression they experience daily. Remember the diverse crowd that gathered in outrage in Denver, when the police mass-arrested the black bloc on August 25. Even with Obama on the ballot or in the White House, when the lines are drawn, people know where they stand in relation to authority.</p>
<p><br />
</p>
<h1>Appendix</h1>
<p><strong><a href="/texts/atoz/rnclegal.php" onMouseOver="self.status='Open In A Window'; return true;">We Are All Legal Workers: Legal Support at the RNC and After</a></strong><br />
</p>
<h2>Accounts</h2>
<p>We&rsquo;ve gone to some lengths to assemble and presume a variety of personal narratives from participants in the DNC and RNC protests:</p>
<p><strong>Democratic National Convention</strong><br />
<a href="/texts/atoz/rncdncdocs.php#doc2">Black Bloc at the DNC, August 25, 2008</a></p>
<p><strong>Two RNC Reports from the Iowa Campus Antiwar Network</strong><br />
<a href="/texts/atoz/rncdncdocs.php#doc3">Campus Antiwar Network Takes on the RNC</a><br />
<a href="/texts/atoz/rncdncdocs.php#doc4">Another Voice from Iowa CAN</a></p>
<p><strong>Three RNC Accounts from New Orleans Residents</strong><br />
<a href="/texts/atoz/rncdncdocs.php#doc5">Black Bloc, September 1</a><br />
<a href="/texts/atoz/rncdncdocs.php#doc6">Bringing the Storm to St. Paul</a><br />
<a href="/texts/atoz/rncdncdocs.php#doc7">Definitely Not Riot Porn: A NOLA Dispatch</a></p>
<p><strong>Additional RNC Accounts</strong><br />
<a href="/texts/atoz/rncdncdocs.php#doc8">Bullfighting in the Twin Cities: How to Avoid Mass Arrest</a><br />
<a href="/texts/atoz/rncdncdocs.php#doc9">A Love Letter To Keith</a><br />
<a href="/texts/atoz/rncdncdocs.php#doc10">Caught! </a><br />
<a href="/texts/atoz/rncdncdocs.php#doc11">Behind Bars </a><br />
<a href="/texts/atoz/rncdncdocs.php#doc12">Elsewhere in Town&hellip;</a></p>
<p><strong>After the Conventions</strong><br />
<a href="/texts/atoz/rncdncdocs.php#doc13">Brand Recognition </a><br />
<a href="/texts/atoz/rncdncdocs.php#doc14">The Beginning of Our Battles </a><br />
<a href="/texts/atoz/rncdncdocs.php#doc15">Afterwards </a></p>
<p><br />
</p>
<h2>Links to Further Reading</h2>
<h3>Accounts and Analyses</h3>
<p><a href="http://news.infoshop.org/article.php?story=20080916224828131" target="_blank">The Battle Of The River (account by &ldquo;Annie Nimmety&rdquo;)</a></p>
<p><a href="http://twincities.indymedia.org/2008/sep/organizing-resistance-retrospective-2008-republican-national-convention?t=1221977945" target="_blank">Organizing Resistance&mdash;A retrospective on the 2008 Republican National Convention</a></p>
<p><a href="http://news.infoshop.org/article.php?story=20080915164432610" target="_blank">The Ground Noise and the Static: A Chronicle of the Battle of Saint Paul, RNC 2008</a></p>
<p><a href="http://www.downtownexpress.com/de_280/shotbypolice.html" target="_blank">Shot by police, bashed by Palin (a journalist&rsquo;s account)</a></p>
<p><a href="http://www.minnesotaindependent.com/6740/day-one-diary-all-roads-lead-to-kellogg-boulevard" target="_blank">RNC Day One Diary: All roads lead to Kellogg Boulevard (with photos)</a></p>
<p><a href="http://antiauthoritarian.net/NLN/?p=484" target="_blank">Twin Study: Repression At The Republican National Convention</a><br />
</p>
<h3>Maps</h3>
<p><a href="http://news.infoshop.org/article.php?story=20080601222556916" target="_blank">Sector Map</a></p>
<p><a href="http://extras.twincities.com/pdfs/092508_rnc_map.pdf" target="_blank">Police map of September 1 events</a><br />
</p>
<h3>Video</h3>
<p><a href="http://twincities.indymedia.org/2008/oct/terrorizing-dissent-election-cut" target="_blank">Terrorizing Dissent documentary</a></p>
<p><a href="http://submedia.tv/stimulator/2008/10/06/ground-noise-and-static/" target="_blank">The Ground Noise and the Static documentary</a><br />
</p>
<h3>Archives</h3>
<p><a href="http://stpaul.gov/index.asp?NID=2901" target="_blank">Report of the RNC Public Safety Planning and Implementation Review Commission (government report with photos, videos, and documents)</a></p>
<p><a href="http://rnc08report.org/" target="_blank">RNC &rsquo;08 Report (well-nigh comprehensive citizen&rsquo;s archive of media reports, government documents, and other resources)</a></p>
<p><a href="http://www.infoshop.org/page/DNC-RNC2008BreakingNews" target="_blank">DNC/RNC 2008 News Archive at www.infoshop.org</a></p>
<p><a href="http://rnc08report.org/cgi-bin/engine/search.cgi?action=search&amp;page=1&amp;perpage=5000&amp;template=searchEngine/searchResults.html&amp;keywordSearchFields=source&amp;keyword=%27Twitter.com%27" target="_blank">Twitter feeds from Coldsnap Legal Collective and Comms Team</a><br />
</p>
<h3>Legal Support</h3>
<p><a href="http://rnc08arrestees.wordpress.com/" target="_blank">CRASS (Community RNC Arrestee Support Structure</a></p>
<p><a href="http://coldsnaplegal.wordpress.com/" target="_blank">Coldsnap Legal Collective</a></p>
<p><a href="http://rnc8.org" target="_blank">RNC 8 Support Site</a></p>
<p><a href="http://supportjessejames.wordpress.com" target="_blank">Support Site for felony defendant Jesse James Forrey</a></p>
<p><a href="http://helpmkethree.blogspot.com" target="_blank">Support Site for the &ldquo;Milwaukee Three&rdquo;: Karen Meissner, Christina Vana, and Dave Mahoney</a></p>
<p><a href="http://www.freethetexas2.com" target="_blank">Support Site for Federal Defendants David McCay and Bradley Crowder</a></p>
<p><a href="http://snitchwire.blogspot.com/" target="_blank">Snitchwire (informant tracking site)</a></p>
<p>&nbsp;</p>
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1] Some critics pose a false dichotomy between building radical infrastructures and focusing on mass mobilizations; in fact, the latter often produce the former.
</p>
<p>[2] Bash Back! came out of a Midwest anarchist consulta in November 2007, initiated by queer anarchists who felt that there hadn&rsquo;t been sufficient space for radical queer and trans participants at earlier demonstrations. Months after the conventions, Bash Back! groups were making headlines with provocative actions, and the network continued to spread across the US.</p>
<p>[3] As one cynic quipped, &ldquo;A lot of different things happened in 1968&mdash;not all of them good!&rdquo;
</p>
<p>[4] The Free State produced an entire generation of Twin Cities activists, some of whom later helped found the WC.</p>
<p>[5] Comically, these were coordinated by the ISAG Welcoming Committee, a group promoting &ldquo;decentralized actions&rdquo; which foreshadowed the RNC WC by failing to engage with corporate media while police mobilized a massive campaign of repression.</p>
<p>[6] One detainee who attempted to sing to the child to keep him calm was gruffly instructed to &ldquo;Shut the fuck up&rdquo; by a gun-waving officer.</p>
<p>[7] Imagine the conscience of a person whose chosen career echoes that of the most hated traitor in Christian history.</p>
<p>[8] This has continued since the RNC demonstrations. Older Twin Cities progressives in particular have mobilized around the RNC 8 case.
</p>
<p>[9] This is presumably disinformation, though there are reports of a conflict between anarchists and pro-war demonstrators. Compared to police officers, anarchists are extremely principled about not attacking civilians.</p>
<p>[10] There were also security concerns, as txt.mob records had been subpoenaed in subsequent court cases.
</p>
<p>[11] While organizers in Denver risked spreading themselves too thin between different events, in St. Paul it could have been advantageous to plan more past September 1; on the other hand, there may simply not have been enough time and resources for this.</p>
<p>[12] Indeed, at least 600 of the 818 people arrested during the RNC were captured in mass arrests.</p>
<p>[13] It&rsquo;s noteworthy that the conspiracy charges against the RNC 8 were brought by Ramsey County, not the federal government. Although it seems strange that a liberal local government would be more eager to press terrorist conspiracy charges than the federal government under Bush, this appears to indicate that the RNC 8 case may not be an indication of federal tactics to come so much as the initiative of overzealous local authorities.</p>
<p>[14] Those who glorify clandestine action over participatory militant organizing should ask Daniel McGowan, who participated in several major Earth Liberation Front actions and went on to play a central role in organizing the 2004 RNC protests, which he found to be more effective. His address can be found at www.supportdaniel.org.</p>
<p>[15] See David Graeber&rsquo;s &ldquo;The Shock of Victory,&rdquo; available at www.infoshop.org.
</p>
</div>