<p align="center"><a href="/texts/images/rnc14b.jpg" rel="lightbox[rnc]" ><img src="/texts/images/rnc14a.jpg" width="500" height="332"></a></p>
<h2>We Are All Legal Workers: <br />
Legal Support at the RNC and After</h2>
<h5>&ldquo;Coldsnap Legal&mdash;this line is not secure.&rdquo;</h5>
<p> Ever since the Seattle WTO protests, legal collectives have sought to counteract state repression by supporting participants in mass mobilizations. Even outside those contexts, legal workers can serve a valuable role wherever people face police harassment or arrest. Unfortunately, it&rsquo;s notoriously hard to recruit people for legal support; it isn&rsquo;t portrayed as sexy, it takes a lot of work, and many people wrongly fear that it requires special training.</p>
<p> The RNC legal effort started with a small group of determined people; most had no previous experience with legal work. Some had met at the poorly attended legal breakout session at the first pRe-NC, where they agreed that there was a need for more legal resources in the radical community and discussed organizing legal support structures for the RNC and beyond. The challenge of doing legal support for such a large mobilization was daunting; even the group&rsquo;s most experienced legal workers had never attempted anything near that scale. Ultimately, they pulled it off, with a lot of help from others who had done that work before.</p>
<p> In January 2008, they formed Coldsnap Legal Collective with the intention of setting up a jail support hotline, composing materials and trainings, and preparing legal support infrastructures for the convention. After speaking with legal workers from around the country, they also decided to organize a jail vigil and street team.</p>
<h3>We&rsquo;re Ready&mdash;Are We?</h3>
<p>Months before the RNC, Coldsnap began offering trainings locally and regionally, teaching people solidarity tactics, their legal rights, and how to interact with police. These evolved from dry, self-prepared lectures to participatory role-plays drawing on materials<a class="footnote" href="javascript:void(0);" onclick="return overlib('Many of these can be found at midnightspecial.net.', CAPTION, '[1]');" onmouseout="nd();">[1]</a> from more established legal collectives.</p>
<p> Coldsnap called the first national RNC legal support meeting to coincide with the second pRe-NC in May 2008. The more experienced national legal workers wanted Coldsnap to provide direction for the effort; to help, they offered support, resources, and access to pre-existing networks. They put on &ldquo;trainers&rsquo; trainings,&rdquo; established a database,<a class="footnote" href="javascript:void(0);" onclick="return overlib('The database began with affinity group support forms; it has enabled legal workers to track arrestees through the system, providing a record of the details of arrests, instances of police brutality, and other important information.', CAPTION, '[2]');" onmouseout="nd();">[2]</a> and arrived weeks in advance of the RNC to help set up the office and other structures. </p>
<p> One of the purposes of legal collectives is to bridge the gap between activists and the legal community, between whom there is often mutual distrust.&nbsp;Coldsnap&rsquo;s attempt to navigate these relationships produced mixed results. Lawyers regarded Coldsnap with suspicion on account of their unprofessional appearance and lack of law licenses; this did not stop them from making dire predictions about what would happen at the RNC, which were poorly received by many radicals when Coldsnap passed them on. Though the lawyers, legal workers, and activists all needed each other to be effective, communication was difficult and continued to be throughout the subsequent events.</p>
<p> Originally, Coldsnap intended to create a decentralized model of legal support, encouraging every affinity group to have its own legal support structure in place. They hoped that doing so would dismantle the perceived hierarchy of knowledge connected to legal work. This did not occur; most affinity groups did not make viable legal support plans for themselves, and Coldsnap ultimately did legal support for almost everyone. </p>
<h3>The Storm Hits</h3>
<p>Utilizing a web service that forwarded a single number to multiple phones, Coldsnap established a 24-hour hotline in spring of 2008, providing jail support for local events and encouraging everyone to memorize the number or write it on their bodies. For the convention, they set up shop in an office of NLG lawyers. The office included six phone lines connected to the hotline number and multiple computers sharing the central database. The hope was that occupying a legal office would protect against raids and subpoenas, due to attorney-client privilege issues.</p>
<p> The jail support hotline was connected to the office on August 29, hours before the convergence space was raided; from then on, people staffed the space 24 hours a day. Legal workers were busy that whole weekend dealing with house raids, detainments, and arrests, as well as making last-minute preparations for the convention. Coldsnap sent representatives to the weekend spokescouncils, giving updates, helping affinity groups get connected to the legal support structure, and forming a jail solidarity plan in which arrestees would give the name Jesse Sparkles rather than their real names and refuse to be separated on account of gender or severity of charge.</p>
<p>On September 1, the office was at maximum capacity. There were volunteers answering the phones and entering data, two information coordinators, one person handling media, and one person sending out reports via Twitter. Lawyers were constantly in conferences in the other room. The hotline received thousands of calls; information on police actions and arrests was verified and publicized, and arrestees spoke to caring people who listened to their stories, took down their information, and gave their loved ones updates and reassurance. A non-stop vigil outside the jail provided arrestees clean clothes, food, and hugs upon release. Legal observers were alerted of unfolding events and dispatched to the streets from a separate location; between missions, they dropped off reports at the office. The atmosphere was both exciting and exhausting&mdash;no one had slept, everything was happening at once, and not all the news was good. At times, tempers ran high. At one point on September 1, the lawyers became particularly irritated when an anarchist legal worker posted &ldquo;black bloc make total destroy everywhere!&rdquo; over the Coldsnap Twitter feed, fearing it might pose problems for future legal efforts.</p>
<p> Things did not improve from there. On the third day of the convention, a day still known to many legal workers as &ldquo;Black Wednesday,&rdquo; several things happened at once. The affidavits in the RNC 8 case were released to the press, with a number of Coldsnap members listed as members of the Welcoming Committee. Police came to the building housing the legal office, claiming to be responding to a hostage situation involving the videographers upstairs; then the landlord showed up, demanding an explanation and threatening eviction. The lawyers responded by banning everyone allegedly involved with the WC from the office and barring them from participating in RNC legal work, citing safety concerns. The blacklisted people, however, were the Coldsnap collective members responsible for bottomlining the office, which left out-of-town legal workers saddled with all the responsibility and confused arrestees calling a place where no one had any context for them. The fact that the banned legal workers were the ones most immediately connected to the anarchist community meant that the remaining legal effort lacked ties to that community&mdash;precisely the population most in need of support.</p>
<p> By the end of the week, the police had arrested 818 protesters, downtown St. Paul had become a full-on police state, and almost everyone was exhausted, in jail, or both. Not everything had gone as planned. The street team was a literal bust, as members were immediately singled out and targeted for arrest. The jail solidarity plan did not get the desired results: the police brutalized arrestees rather than meeting their demands, and the separated and demoralized Sparkles eventually gave their real names. In the office, processing the massive quantities of information that came in proved significantly more difficult than anticipated; volunteers struggled with the data entry backlog for months afterward. And although the banned Coldsnap members were eventually allowed to participate again, relations between legal workers and lawyers remained strained for some time.</p>
<h3>Aftermath</h3>
<p>The first meeting of RNC arrestees and supporters, two days after the end of the convention, evolved into CRASS (Community RNC Arrestee Support Structure), a spokescouncil of working groups dedicated to helping arrestees through the court process. CRASS provided a travel fund for arrestees,<a class="footnote" href="javascript:void(0);" onclick="return overlib('The travel fund, along with locals&rsquo; willingness to host out-of-town defendants, has helped people come back to fight their charges. This in turn helps with court solidarity, which can involve defendants coordinating and fighting their charges together, as well as people coming out in support.', CAPTION, '[3]');" onmouseout="nd();">[3]</a> helped them file civil suits, and called protests and press conferences to put pressure on city officials. Coldsnap got a new office and continued to staff the hotline and conduct trainings, but the majority of direct arrestee support came to be handled by CRASS. This was consistent with Coldsnap&rsquo;s original goal of arrestees handling their own support, although it occurred differently than first imagined.</p>
<p> CRASS devised strategies for court solidarity that achieved concrete victories.<a class="footnote" href="javascript:void(0);" onclick="return overlib('It also gave a community of militantly unemployed people a 9-5 weekday schedule.', CAPTION, '[4]');" onmouseout="nd();">[4]</a> These included packing courtrooms, standing up when defendants' names were called and wearing clothing expressing support; writing letters to judges regarding sentencing; and speaking on defendants' behalf as character witnesses. Courtwatch volunteers attended every single hearing, maintaining contact with arrestees and taking notes to update the database. Supporters organized call-in days, letter-writing campaigns, and other forms of pressure to drop charges, including crashing city officials&rsquo; events. Fighting charges largely led to prosecutors dropping them, if they weren&rsquo;t dismissed before trial. The first felony arrestee to be sentenced was given a stay of disposition rather than jail time, and the judge specifically cited the supporters packing the courtroom as one of the reasons; subsequent felony defendants were also given less jail time because of similarly visible support.</p>
<p> Other forms of legal work and support also achieved concrete results. In the immediate aftermath of the RNC, when police were visiting and threatening former WC members, legal workers called a community meeting to discuss the situation and brief the dozens of attendees on their rights; as a result, no one talked to the authorities, and the latter gave up their intimidation campaign shortly after. For many months, the Felony Working Group, an offshoot of CRASS, met weekly to share updates on cases and brainstorm ways to support those facing felony charges. Supporters produced propaganda, raised funds via secret caf&eacute;s,<a class="footnote" href="javascript:void(0);" onclick="return overlib('Secret Caf&eacute;s are a way to fundraise, socialize and build community; the idea is to turn an ordinary (or extraordinary!) space into a temporary restaurant with sliding-scale food and entertainment.', CAPTION, '[5]');" onmouseout="nd();">[5]</a> attended and transcribed each other&rsquo;s court dates, and offered each other emotional support.</p>
<p> Some of the felony defendants, such as the MK3 and the RNC 8, have their own support structures. Immediately after the RNC, the remains of the RNC WC coalesced into the Friends of the RNC 8; the Friends maintain a website and produce support material geared toward the radical community, as well as organizing events and coordinate national support and fundraising. In January 2009, the support structure of the RNC 8 expanded to include the RNC 8 Defense Committee, an umbrella group that works on political pressure campaigns with CRASS and other groups, including efforts to defeat the Minnesota PATRIOT Act.</p>
<p> Prosecutors continue to persecute RNC defendants. New felony cases are still being filed, and new charges have been added to existing cases in a dubiously legal attempt to coerce guilty pleas from the accused. The RNC 8 started out with one felony charge, which later got raised to four; they are facing two as of this writing, their terrorism charges having been dropped as a direct result of political pressure from their supporters. Another arrestee started out with two felony charges before the prosecutor increased the number to six and threatened to add six more. It is clear that this fight is far from over.</p>
<h3>Conclusions</h3>
<p>People in the Twin Cities are still dealing with the aftermath of the RNC. The networks and friendships created during the mobilization have helped mobilize important support for those facing felony charges; many of the accused have moved to the Twin Cities for the duration of their cases, bringing new energy with them. At the same time, lasting trauma and the fear and tedium of long court cases with potentially serious consequences have taken their toll on many people&rsquo;s mental health, especially through the bleak Minnesota winter. Constant meetings, court dates, and pending cases have sapped energy from the local radical community; they have also distracted organizers from their work, a situation that will only get worse if the latter end up in prison.</p>
<p>Police tactics are intended to maintain isolation, silence, and fear. Mutual aid and solidarity strengthen our communities and discourage repression. When people are familiar with the legal system and confident that they will be supported, they are less likely to be cowed by threats or fall for trickery. Many participants in the RNC protests expressed that the legal support available to them helped them feel more empowered to take action; others reported that knowing they were supported kept them from cooperating with the state. Cross-movement solidarity has also proved invaluable. For example, two members of the RNC 8 had been members of EWOK! (Earth Warriors Are Okay!), a group dedicated to supporting earth and animal liberation prisoners; consequently, the 8 received support and resources from those EWOK had supported.</p>
<p>We can no longer afford to leave legal work to the experts. This is more important than ever in light of the repressive response to the RNC protests. Whether or not we organize or participate in mass mobilizations, anarchists will continue to be charged with felonies; in addition to keeping the potential consequences of our actions in mind and mentally preparing ourselves for worst-case scenarios, we must plan and be equipped for legal support. In an age when anarchist organizing attracts federal attention and multi-million-dollar security budgets, all of us are at risk. The safety and security of our communities depend on our ability to respond and support one another.</p>
<p>Like it or not&mdash;these days, we are all legal workers.</p>
<p>&nbsp;</p>
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1] Many of these can be found at midnightspecial.net.
</p>
<p>[2] The database began with affinity group support forms; it has enabled legal workers to track arrestees through the system, providing a record of the details of arrests, instances of police brutality, and other important information.</p>
<p>[3] The travel fund, along with locals&rsquo; willingness to host out-of-town defendants, has helped people come back to fight their charges. This in turn helps with court solidarity, which can involve defendants coordinating and fighting their charges together, as well as people coming out in support.
</p>
<p>[4] It also gave a community of militantly unemployed people a 9-5 weekday schedule.</p>
<p>[5] Secret Caf&eacute;s are a way to fundraise, socialize and build community; the idea is to turn an ordinary (or extraordinary!) space into a temporary restaurant with sliding-scale food and entertainment.</p>
</div>
