<p align="center"><a href="http://thecloud.crimethinc.com/images/selfcare/1b.jpg" rel="lightbox[breakwith]"><img src="http://thecloud.crimethinc.com/images/selfcare/1a.jpg" width="500" height="495" title="For All We Care: Reconsidering Self-Care"/></a></p>
<p>In the 1980s, as she struggled with cancer, Audre Lorde asserted that caring for herself was <a href="http://www.lowendtheory.org/post/43457761324/on-audre-lordes-legacy-and-the-self-of-self-care">“an act of political warfare.”</a> Since then, self-care has become a popular buzzword in activist circles. The rhetoric of self-care has moved from specific to universal, from defiant to prescriptive. When we talk about self-care today, are we talking about the same thing Lorde was? It’s time to reexamine this concept.</p>
<p>But what could be wrong with <em>care?</em> And why, of all things, pick on <em>self-care?</em></p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/selfcare/2b.jpg" rel="lightbox[breakwith]"><img src="http://thecloud.crimethinc.com/images/selfcare/2a.jpg" width="500" height="374" /></a></p>
<p>For one thing, because it has become a sacred cow. It’s painful to hear people speak sanctimoniously about anything, but especially about the most important things. Pious unanimity implies a dark side: in the shadow of every church, a den of iniquity. It creates an <em>other,</em> drawing a line through as well as between us.</p>
<p><em>Self</em> and <em>care</em>—in that order—are universally acknowledged values in this society. Anyone who endorses self-care is on the side of the angels, as the saying goes—which is to say, against all the parts of us that don’t fit into the prevailing value system. If we wish to resist the dominant order, we have to play devils’ advocate, searching out what is excluded and denigrated.</p>
<p>Wherever a value is considered universal, we find the pressures of normativity: for example, the pressure to <em>perform</em> self-care for others’ sake, keeping up appearances. So much of what we do in this society is about maintaining the image that we’re successful, autonomous individuals, regardless of the reality. In this context, rhetoric about self-care can mask silencing and policing: <em>Deal with your problems yourself, please, so no one else has to.</em></p>
<p>Assuming that self-care is always good means taking for granted that <em>self</em> and <em>care</em> always have the same meaning. Here, we want to challenge monolithic and static understandings of selfhood and caring. Instead, we propose that different kinds of care produce different kinds of self, and that care is one of the battlefields on which social struggles play out.</p>
<h2>Don’t Tell Me to Calm Down</h2>
<p>Though advocates of self-care emphasize that it can look different for each person, the suggestions usually sound suspiciously similar. When you think of <a href="http://www.organizingupgrade.com/index.php/modules-menu/community-care/item/771-self-care-diy-a-how-to-just-for-you">stereotypical “self-care” activities,</a> what do you picture? Drinking herbal tea, watching a movie, taking a bubble bath, meditating, yoga? This selection suggests a very narrow idea of what self-care is: essentially, <em>calming yourself down.</em></p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/selfcare/3b.jpg" rel="lightbox[breakwith]"><img src="http://thecloud.crimethinc.com/images/selfcare/3a.jpg" width="500" height="654" /></a></p>
<p>All of these activities are designed to engage the <a href="http://en.wikipedia.org/wiki/Parasympathetic_nervous_system">parasympathetic nervous system</a>, which governs rest and recovery. But some forms of care require strenuous activity and adrenaline, the domain of the <a href="http://en.wikipedia.org/wiki/Sympathetic_nervous_system">sympathetic nervous system</a>. One way to prevent post-traumatic stress disorder, for example, is to allow the sympathetic nervous system enough freedom to release trauma from the body. When a person is having a panic attack, it rarely helps to try to make them calm down. The best way to handle a panic attack is to run.</p>
<p>So let’s start by discarding any normative understanding of what it means to care for ourselves. It might mean lighting candles, putting on a Nina Simone album, and rereading Randall Jarrell’s <em>The Animal Family.</em> It could also mean BDSM, intense performance art, mixed martial arts fighting, smashing bank windows, or calling out a person who abused you. It might even look like <em>really hard work</em> to other people—or ceasing to function altogether. This is not just a postmodern platitude (“different strokes for different folks”), but a question of what relationship we establish to our challenges and our anguish.</p>
<p>Caring for ourselves doesn’t mean pacifying ourselves. We should be suspicious of any understanding of self-care that identifies wellbeing with placidity or asks us to perform “health” for others. Can we imagine instead a form of care that would equip each of us to establish an intentional relationship to her dark side, enabling us to draw strength from the swirling chaos within? Treating ourselves gently might be an essential part of this, but we must not assume a dichotomy between healing and engaging with the challenges around and inside us. If care is only what happens when we step away from those struggles, we will be forever torn between an unsatisfactory withdrawal from conflict and its flipside, a workaholism that is never enough. Ideally, care would encompass and transcend both struggle and recovery, tearing down the boundaries that partition them.</p>
<p>This kind of care cannot be described in platitudes. It is not a convenient agenda item to add to the program of the average non-profit organization. It demands measures that will interrupt our current roles, bringing us into conflict with society at large and even some of the people who profess to be trying to change it.</p>
<br /><br />
<h5>
By your response to danger it is<br />
Easy to tell how you have lived<br />
And what has been done to you.<br />
You show whether you want to stay alive,<br />
Whether you think you deserve to,<br />
And whether you believe<br />
It’s any good to act.<br />
<br />
-Jenny Holzer</h5>
<br /><br />
<h2>Love Is a Battlefield</h2>
<p>If we want to identify what is worth preserving in self-care, we can start by scrutinizing care itself. To endorse care as a universal good is to miss the role care also plays in perpetuating the worst aspects of the status quo. There’s no such thing as care in its pure form—care abstracted from daily life in capitalism and the struggles against it. No, care is partisan—it is repressive or liberating. There are forms of care that reproduce the existing order and its logic, and other forms of care that enable us to fight it. We want our expressions of care to nurture liberation, not domination—to bring people together according to a different logic and values.</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/selfcare/4b.jpg" rel="lightbox[breakwith]"><img src="http://thecloud.crimethinc.com/images/selfcare/4a.jpg" width="500" height="252" /></a></p>
<p>From homemaking to professional housekeeping—not to mention nursing, hospitality, and phone sex—women and people of color are disproportionately responsible for the care that keeps this society functioning, yet have disproportionately little say in what that care fosters. Likewise, a tremendous amount of care goes into oiling the machinery that maintains hierarchy: families help police relax after work, sex workers help businessmen let off steam, secretaries take on the invisible labor that preserves executives’ marriages. </p>
<p>So the problem with self-care is not just the individualistic prefix. For some of us, focusing on self-care rather than caring for others would be a revolutionary proposition, albeit almost unimaginable—while the privileged can congratulate each other on their excellent self-care practices without recognizing how much of their sustenance they derive from others. When we conceive of self-care as an individual responsibility, we are less likely to see the political dimensions of care. </p>
<p>Some have called for a <em>caring strike</em>: a collective, public resistance to the ways capitalism has commandeered care. In their text <a href="http://zinelibrary.info/files/A%20Very%20Careful%20Strike.pdf">“A Very Careful Strike,”</a> Spanish militants Precarias a la Deriva explore the ways care has been commodified or rendered invisible, from customer service in the marketplace to emotional care in families. They challenge us to imagine ways care could be wrested away from maintaining our stratified society and instead lavished on fostering togetherness and revolt.</p>
<p>But such a project depends on those who are already most vulnerable in our society. It would take a tremendous amount of support for family members, sex workers, and secretaries to go on <em>care strike</em> without suffering appalling consequences.</p>
<p>So rather than promoting self-care, we might seek to <em>redirect and redefine</em> care. For some of us, this means recognizing how we benefit from imbalances in the current distribution of care, and shifting from forms of care that focus on ourselves alone to support structures that benefit all participants. Who&#8217;s working so you can rest? For others, it could mean taking better care of ourselves than we’ve been taught we have a right to—though it’s unrealistic to expect anyone to undertake this individually as a sort of consumer politics of the self. Rather than creating gated communities of care, let’s pursue forms of care that are expansive, that interrupt our isolation and threaten our hierarchies.</p>
<p>Self-care rhetoric has been appropriated in ways that can reinforce the entitlement of the privileged, but a critique of self-care must not be used as yet another weapon against those who are already discouraged from seeking care. In short: step up, step back.</p>
<br /><br />
<h5 style="padding-left: 10px">A struggle that doesn’t understand the importance of care is doomed to fail. The fiercest collective revolts are built on a foundation of nurture. But reclaiming care doesn’t just mean giving ourselves more care, as one more item after all the others on the to-do list. It means breaking the peace treaty with our rulers, withdrawing care from the processes that reproduce the society we live in and putting it to subversive and insurrectionary purposes.</h5>
<br /><br />
<h2>Beyond Self-Preservation</h2>
<blockquote>
<p>“‘Health’ is a cultural fact in the broadest sense of the word, a fact that is political, economic, and social as well, a fact that is tied to a certain state of individual and collective consciousness. Every era outlines a ‘normal’ profile of health.”
<em>–Michel Foucault</em></p>
</blockquote>
<p>The best way to sell people on a normative program is to frame it in terms of health. Who doesn’t want to be healthy?</p>
<p>But like “self” and “care,” health is not one thing. In itself, health is not intrinsically good—it’s simply the condition that enables a system to continue to function. You can speak about the health of an economy, or the health of an ecosystem: these often have an inverse relationship. This explains why some people describe capitalism as a cancer, while others accuse <a href="http://www.crimethinc.com/blog/2012/09/17/post-debate-debrief-video-and-libretto/">“black bloc anarchists”</a> of being the cancer. The two systems are lethal to each other; nourishing one means compromising the health of the other.</p>
<p>The repressive function of health norms is obvious enough in the professional field of mental health. Where <a href="http://www.crimethinc.com/books/contra/defs/drapetomania.html">drapetomania</a> and <a href="http://books.google.com/books?id=y3EFAAAAQAAJ&amp;pg=PA293&amp;lpg=PA293&amp;dq=anarchia+benjamin+rush&amp;source=bl&amp;ots=p1Gja9j40F&amp;sig=joYOcEpuS8-o9ujeD6AJLca4F_M&amp;hl=en&amp;sa=X&amp;ei=pO9dUbyZCImi8gTD0oDACw&amp;ved=0CEEQ6AEwAg#v=onepage&amp;q=anarchia%20benjamin%20rush&amp;f=false">anarchia</a> were once invoked to stigmatize runaway slaves and rebels, today’s clinicians diagnose oppositional defiance disorder. But the same thing goes on far from psychiatric institutions.</p>
<p>In a capitalist society, it should not be surprising that we tend to measure health in terms of productivity. Self-care and workaholism are two sides of the same coin: <em>preserve yourself so you can produce more.</em> This would explain why self-care rhetoric is so prevalent in <a href="http://www.incite-national.org/index.php?s=89">the non-profit sector</a>, where the pressure to compete for funding often compels organizers to mimic corporate behavior, even if they use different terminology.</p>
<p>If self-care is just a way to ease the impact of an ever-increasing demand for productivity, rather than a transformative rejection of that demand, it’s part of the problem, not the solution. For self-care to be <em>anti-capitalist,</em> it has to express a different conception of health.</p>
<p>This is especially complicated as our survival becomes ever more interlinked with the functioning of capitalism—a condition some have designated with the term <a href="http://en.wikipedia.org/wiki/Biopower"><em>biopower.</em></a> In this situation, the easiest way to preserve your health is to excel at capitalist competition, the same thing that is doing us so much harm. “There is no other pill to take, so swallow the one that made you ill.”</p>
<p>To escape this vicious circle, we have to shift from reproducing one “self” to producing another. This demands a notion of self-care that is transformative rather than conservative—that understands the self as dynamic rather than static. The point is not to stave off change, as in Western medicine, but to foster it; in the Tarot deck, Death represents metamorphosis.</p>
<p>From the standpoint of capitalism and reformism, anything that threatens our social roles is unhealthy. As long as we remain inside the former paradigm, it may be that only behaviors deemed <em>unhealthy</em> can point the way out. Breaking with the logic of the system that has kept us alive demands a certain reckless abandon.</p>
<p>This may illuminate the connection between apparently <a href="http://www.crimethinc.com/blog/2011/12/17/self-destruction/">self-destructive behavior</a> and rebellion, which goes back a long time before punk rock. The radical side of the Occupy Oakland assemblies, where all the smokers hung out, was known affectionately as the “black lung bloc”—the cancer of Occupy, indeed! The self-destructive energy that drives people to addiction and suicide can also enable them to take courageous risks to change the world. We can identify multiple currents within self-destructive behavior; some of them close down possibility, while others open it up. We need language with which to explore this, lest our language about self-care perpetuate a false binary between sickness and self-destructiveness on one hand and health and struggle on the other.</p>
<p>For when we speak of breaking with the logic of the system, we are not just talking about a courageous decision that presumably healthy subjects make in a vacuum. Even apart from “self-destructive” behavior, many of us already experience illness and disability that position us outside this society’s conception of health. This forces us to grapple with the question of the relationship between health and struggle.</p>
<p>When it comes to anti-capitalist struggle, do we associate health with productivity, too, implying that the ill cannot participate effectively? Instead, without asserting the ill as the revolutionary subject à la <a href="http://theicarusproject.net/">the Icarus Project</a>, we could look for ways of engaging with illness that pull us out of our capitalist conditioning, interrupting a way of being in which self-worth and social ties are premised on a lack of care for ourselves and each other. Rather than pathologizing illness and self-destructiveness as disorders to be cured for efficiency’s sake, we could reimagine self-care as a way of listening into them for new values and possibilities.</p>
<p>Think of Virginia Woolf, Frida Kahlo, Voltairine de Cleyre, and all the other women who drew on their private struggles with sickness, injury, and depression to craft public expressions of insubordinate care. How about Friedrich Nietzsche: was his poor health a mere obstacle, which he manfully overcame? Or was it inextricable from his insights and his struggles, an essential step on the path that led him away from received wisdom so he could discover something else? To understand his writing in the context of his life, we have to picture Nietzsche in a wheelchair charging a line of riot police, not flying through the air with an S on his chest.</p>
<p>Your human frailty is not a regrettable fault to be treated by proper self-care so you can get your nose back to the grindstone. Sickness, disability, and unproductivity are not anomalies to be weeded out; they are moments that occur in every life, offering a common ground on which we might come together. If we take these challenges seriously and make space to focus on them, they could point the way beyond the logic of capitalism to a way of living in which there is no dichotomy between care and liberation.</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/selfcare/5b.jpg" rel="lightbox[breakwith]"><img src="http://thecloud.crimethinc.com/images/selfcare/5a.jpg" width="500" height="331" /></a></p>
<h2>Further Reading</h2>
<p><a href="http://www.crimethinc.com/blog/2011/12/17/self-destruction/">Self-Destruction</a></p>
<p><a href="http://www.lowendtheory.org/post/43457761324/on-audre-lordes-legacy-and-the-self-of-self-care">“On Audre Lorde’s Legacy and the ‘Self’ of Self-Care”</a></p>
<p><a href="http://en.bookfi.org/book/1139807">“On Being Ill,”</a> Virginia Woolf</p>
<p><a href="http://anarchalibrary.blogspot.com/2012/02/ndrea-one-womans-fight-to-die-her-own.html"><em>N’Drea: One Woman’s Fight to Die Her Own Way</em></a></p>
