<h1>The SHAC Model:  A Critical Assessment</h1>
<p align="center"><img src="/texts/images/wolf_500.jpg" width="500" height="255"></p>
<h4>&ldquo;We were aware of the activists, but I don&rsquo;t think we understood exactly to what lengths they would go.&rdquo;<em> <br />
<div style="text-align: right !important">&ndash;Warren Stevens, on dropping a $33 million loan to<br />
Huntingdon Life Sciences despite having vowed never to do so,<br />
following rioting at his offices in Little Rock and vandalism of his property</div></em></h4>
<br /><h4>&ldquo;The number of activists isn&rsquo;t huge, but their impact has been incredible . . . There needs to be an understanding that this is a threat to all industries. <br />
The tactics could be extended to any other sectors of the economy.&rdquo;<em> <br />
<div style="text-align: right">&ndash;Brian Cass, managing director of HLS</div></em></h4>
<br />
<h4>&ldquo;Where all animal welfare and most animal rights groups insist on working within the legal boundaries of society, animal liberationists argue that the state is irrevocably corrupt and that legal approaches alone will never win justice for the animals.&rdquo;<em> <br />
<div style="text-align: right">&ndash;ALF Press Office</div></em></h4>
<p>&nbsp;</p>
<p>Over the past decade, <a href="http://en.wikipedia.org/wiki/Stop_Huntingdon_Animal_Cruelty" target="_blank">Stop Huntingdon Animal Cruelty&mdash;SHAC</a>&mdash;has waged an international direct action campaign against <a href="http://en.wikipedia.org/wiki/Huntingdon_Life_Sciences" target="_blank">Huntingdon Life Sciences</a>, Europe&rsquo;s largest contract animal testing corporation. By targeting investors and business partners of HLS, SHAC repeatedly brought HLS to the brink of collapse, and it took direct assistance from the British government and an international counter-campaign of severe legal repression to keep the corporation afloat.</p>
<p> In the wake of this campaign, there was talk of applying the SHAC model in other contexts, such as environmental defense and anti-war organizing. But what is the SHAC model, precisely? What are its strengths and limitations? Is it, in fact, an effective model? If so, for what?</p>
<h3>First, a Glossary of Terms</h3>
<p>Viewed from outside, the animal rights milieu can be confusing, even for other radicals. On one hand, the intense focus on this single issue can contribute to an insular mindset, if not outright myopia; on the other hand, there are countless animal liberation activists who see their efforts as part of a larger struggle against all forms of oppression. Those not familiar with the inner workings of the milieu often conflate the positions of opposing factions. At the risk of oversimplifying, it is possible to identify three distinct schools of thought:</p>
<p><strong>Animal Welfare</strong>&ndash;The idea that animals should be treated with mercy and compassion, especially when they are used for human benefit such as food production. For example, some animal welfare advocates lobby the government for more humane slaughter laws.</p>
<p><em>Example:</em> the <a href="http://www.hsus.org/" target="_blank">Humane Society of the United States (HSUS)</a></p>
<p><strong>Animal Rights</strong>&ndash;The idea that animals have their own interests and deserve legislation to protect them. Those who believe in animal rights often maintain vegan diets and oppose the use of animals for entertainment, experimentation, food, or clothing. While they may participate in protests or civil disobedience, they also generally believe in working within the system, through lobbying, marketing, outreach, and use of the corporate media.</p>
<p><em>Example:</em> <a href="http://www.peta.org" target="_blank">People for the Ethical Treatment of Animals (PETA)</a></p>
<p><strong>Animal Liberation</strong>&ndash;The idea that animals should not be domesticated or held in captivity. Since this is not possible within the logic of the current social and economic system, animal liberationists often tend towards anarchism, and may break laws in order to rescue animals or to preserve habitat.</p>
<p><em>Example:</em> <a href="http://www.animalliberationpressoffice.org/" target="_blank">the Animal Liberation Front (ALF)</a><a class="footnote" href="javascript:void(0);" onclick="return overlib('Unlike HSUS and PETA, the ALF is not technically an organization, but rather a banner taken up by autonomous cells which do not necessarily have any connection to each other.', CAPTION, '[1]');" onmouseout="nd();">[1]</a></p></p>
<p>Many groups focused on animal welfare and animal rights have criticized those who engage in direct action, arguing that such actions hurt the image of animal advocates and alienate potential sympathizers. It&rsquo;s also possible to interpret this criticism as motivated by the economic inducement of building up a wealthy membership base and the fear of running afoul of government repression. In addition to denouncing direct action, prohibiting their employees from interacting with those who countenance it, and pulling out of conferences including more militant speakers, organizations such as HSUS have gone so far as to laud the FBI for cracking down on animal liberation efforts. In 2008, <a href="http://www.greenisthenewred.com/blog/hsus-green-scare-donation/540/" target="_blank">HSUS ostentatiously offered a $2500 reward</a> to anyone providing information leading to the conviction of persons involved with an arson alleged by the FBI to be the work of animal rights activists.</p>
<h3>The SHAC Story: Overseas Beginnings</h3>
<p>The <a href="www.shac.net" target="_blank">SHAC campaign</a> originated in Britain, following a series of successful closures of laboratory animal breeders involving tactics from picketing to ALF raids and clashes with the police. Video footage shot covertly inside HLS in 1997 was aired on British television, showing staff shaking, punching, and shouting at beagles in an HLS lab. PETA stopped organizing protests against HLS after being threatened with legal action, and SHAC formed to take over the campaign in November 1999.</p>
<p> Huntingdon Life Sciences was a more formidable target than any individual animal breeder; the SHAC campaign constituted an escalation in animal rights activism in Britain. The idea was to focus specifically on the corporation&rsquo;s finances, utilizing the tactics that had closed small businesses to shut down an entire corporation. Activists set out to isolate HLS by harassing anyone involved with any corporation that did business with them. The role of SHAC as an organization was simply to distribute information about potential targets and report on actions as they occurred.</p>
<p> In January 2000, British activists publicized a list of the largest shareholders in HLS, including those who held shares through third parties for anonymity&mdash;one of which was Britain&rsquo;s Labour Party. Following two weeks of pitched demonstrations, many shareholders sold their holdings; finally, 32 million shares were placed on the London Stock Exchange for one penny each and HLS stocks crashed. In the ensuing chaos, the Royal Bank of Scotland wrote off an &pound;11.6 million loan in exchange for a payment of just &pound;1 in order to distance itself from the company, and the British government arranged for the state-owned Bank of England to give them an account because no other bank would do business with them. The company&rsquo;s share price, worth around &pound;300 in the 1990s, fell to &pound;1.75 in January 2001, stabilizing at 3 pence by mid-2001.</p>
<p> On December 21, 2000, HLS was dropped from the New York Stock Exchange; three months later, it lost its place on the main platform of the London Stock Exchange as well. HLS was only saved from bankruptcy when its largest remaining shareholder, the American investment bank Stephens, gave the company a $15 million loan. This chapter of the story closed with HLS moving its financial center to the United States to take advantage of US laws allowing greater anonymity for shareholders.<br />
</p>
<h3>In the USA</h3>
<p>Meanwhile, in the United States, the anti-fur campaigns that had characterized much of 1990s animal rights organizing had plateaued; the tactics of civil disobedience developed in those campaigns had reached a point of diminishing returns, and many activists were casting around for new targets and strategies. One faction of the animal rights movement, exemplified by groups like Vegan Outreach and DC Compassion Over Killing,<a class="footnote" href="javascript:void(0);" onclick="return overlib('According to reports, the main organizers of this group have since joined HSUS. This is an example of the subtle conflicts and power dynamics that play out in the animal rights movement: SHAC organizers complain that HSUS absorbs committed activists by giving them paying jobs and forbidding them to collaborate with more militant activists.', CAPTION, '[2]');" onmouseout="nd();">[2]</a> moved on to promoting veganism. More militant activists sought other points of departure. Some, like <a href="http://www.motherjones.com/politics/2006/01/americas-1-threat" target="_blank">Kevin Kjonaas</a>, who went on to become president of SHAC USA, had been in Britain and witnessed the apex of the British SHAC campaign, just as anti-globalization activists visiting Britain in the 1990s had brought back heady tales of <a href="http://en.wikipedia.org/wiki/Reclaim_the_Streets" target="_blank">Reclaim the Streets</a> actions.</p>
<p> The US SHAC campaign came out of conversations between animal rights activists in different parts of the country. While the vegan outreach campaign sought to appeal to the lowest common denominator in order to win over consumers, SHAC attracted militants who wanted to make the most efficient use of their individual efforts. Some reasoned that it was unlikely that the entire market base for animal products would be won over to veganism, especially insofar as people tend to be defensive about their lifestyle choices, but practically everyone could agree that punching puppies is inexcusable.</p>
<p> SHAC USA got started in January 2001, just as Stephens, Inc. saved HLS from bankruptcy. Stephens was based in Little Rock, Arkansas, so a number of activists moved there to organize. In April, <a href="http://www.directaction.info/library_hls.htm" target="_blank">14 beagles were liberated</a> from the new HLS lab in New Jersey; at the end of October, hundreds of people gathered in Little Rock for a weekend of demonstrations at Warren Stephens&rsquo; home and the offices of Stephens, Inc. By the following spring, Stephens had ditched HLS, breaking off a five-year contract after only one year.</p>
<p> Unrivaled by any campaign of comparable scale and effectiveness, SHAC took off quickly in the US. Thanks in part to superior funding,<a class="footnote" href="javascript:void(0);" onclick="return overlib('Unlike many social movements, the animal rights movement is supported by wealthy donors, and we can assume that some of them have contributed to SHAC.', CAPTION, '[3]');" onmouseout="nd();">[3]</a> the propaganda was colorful and exciting, as were promotional videos that juxtaposed heart-wrenching clips of animal cruelty with inspiring demonstration footage to a pulse-racing soundtrack of techno music. The campaign offered participants a wide range of options, including civil disobedience, office disruptions, property destruction, call-ins, pranks, tabling, and home demonstrations. In contrast to the heyday of anti-globalization summit-hopping, targets were available all around the country, limited only by activists&rsquo; imaginations and research. The intermediate goals of forcing specific investors and business partners to disconnect from HLS were often easily accomplished, providing immediate gratification to participants.</p>
<p> Whereas an individual might feel insignificant at an antiwar march of thousands, if she was one of a dozen people at a home demonstration that caused an investor to pull out, she could feel that she had personally accomplished something concrete. The SHAC campaign offered the kind of sustained low-intensity conflict through which people can become radicalized and develop a sense of collective power. Running in black blocs with friends, evading police after demonstrations, listening to inspirational speeches together, walking through offices yelling on bullhorns, reading other activists&rsquo; reports online, the feeling of being on the winning side of an effective liberation struggle&mdash;all these contributed to the seemingly unstoppable momentum of the SHAC campaign.</p>
<p align="center"><a href="/texts/images/megaphone_900.jpg" rel="lightbox"><img src="/texts/images/megaphone_500.jpg" width="500" height="333"></a></p>
<h3>Action</h3>
<h4>&ldquo;Carr Securities began marketing the Huntingdon Life Sciences stock. The next day, the Manhasset Bay Yacht Club, to which certain Carr executives reportedly belong, was vandalized by animal rights activists. The extremists sent a claim of responsibility to the SHAC website, and three days after the incident, Carr terminated its business relationship with HLS.&rdquo;<em> <br />
<div style="text-align: right">&ndash;<a href="http://epw.senate.gov/hearing_statements.cfm?id=247787" target="_blank">John Lewis</a>, Deputy Assistant Director <br />FBI Oversight on so-called &ldquo;Eco-terrorism&rdquo;</div></em></h4>
<p><br />
Direct action against those doing business with HLS has taken many forms, occasionally escalating to arson and violence. In February 2001, HLS managing director Brian Cass was hospitalized after being attacked with axe handles at his home. That July, the Pirates for Animal Liberation sank the yacht of a Bank of New York executive, and the bank soon severed ties with the lab. A year later, smoke bombs were set off at the offices of Marsh Corp. in Seattle, causing the evacuation of the high rise and their disassociation from HLS. In fall of 2003, incendiary devices were left at Chiron and Shaklee corporations for their contracting with HLS. In 2005, Vancouver-based brokerage Canaccord Capital announced that it had dropped a client, Phytopharm PLC, in response to the ALF firebombing of a car belonging to a Canaccord executive; Phytopharm had been doing business with HLS. All this took place against a backdrop of constant smaller-scale actions.</p>
<p> In December 2006, HLS was prevented from being listed on the New York Stock Exchange, an unprecedented development that resulted in a full page ad in the New York Times portraying a masked, apparently leather-jacketed caricature of an activist declaring &ldquo;I control Wall Street.&rdquo;<a class="footnote" href="javascript:void(0);" onclick="return overlib('This advertisement is all the more ironic in view of the role masked thugs in nations like Colombia continue to play in defending the interests of corporations who trade on Wall Street.', CAPTION, '[4]');" onmouseout="nd();">[4]</a> In 2007, eight companies dropped HLS, including their two biggest investors, AXA and Wachovia, following home demonstrations and ALF visits to executives&rsquo; houses. In 2008, incendiary devices were left under Staples trucks and Staples outlets were vandalized. About 250 companies altogether have dropped in the course of the campaign, including Citibank, the world&rsquo;s largest financial institution; HSBC, the world&rsquo;s largest bank; Marsh, the world&rsquo;s largest insurance broker; and Bank of America.</p>
<p align="center"><a href="/texts/images/nyse_900.jpg" rel="lightbox"><img src="/texts/images/nyse_500.jpg" width="500" height="809"></a></p>
<h3>Maintaining Momentum</h3>
<p>It&rsquo;s interesting to compare the arc of the SHAC campaign to that of the so-called anti-globalization movement. Both took off in Britain before catching on in the United States. SHAC was founded in England the same month as the historic WTO protests in Seattle; it got going in North America at the tail end of the anti-globalization surge, and maintained momentum after the US wing of the anti-globalization movement collapsed in the wake of the terrorist attacks of September 11, 2001.</p>
<p> How was the SHAC campaign able to maintain momentum while practically every other direct action-based campaign foundered or was co-opted by liberals? Can we derive lessons about how to weather crises from its example? </p>
<p> SHAC activists differed from participants in most other social movements in that they neither perceived themselves to need positive press coverage nor regarded negative press coverage as a bad thing. Their goal was to terrify corporations out of doing business with HLS, not to win converts to the animal rights movement. The more fearsome and crazy they appeared in the media, the easier it was to intimidate potential investors and business partners. Activists in other circles feared that the terrorism scare would make it easy for the government to isolate them by portraying them as dangerous extremists; for SHAC, the more dangerous and extreme they appeared, the better.</p>
<p> All this came back to haunt them in the end, when the most influential organizers went to trial and it was easy for the prosecution to frame them as representatives of a frankly terroristic underground. In this regard, the greatest strengths of the SHAC campaign&mdash;the relationship between public and covert organizing, the fearsome reputation&mdash;also proved to be its Achilles heel. The lesson seems to be that this approach can be effective on a small scale, so long as organizers do not provoke a confrontation with forces much stronger than themselves.</p>
<p> In addition to the matter of press coverage, it may be instructive to look at the way SHAC organizers framed the issues. SHAC spokespeople never backed down from emphasizing the necessity of direct action for animal liberation, even when the rest of the nation was fixated on Al Qaeda; the historic mobilization in Little Rock took place only a month and a half after the attacks on the World Trade Center and the Pentagon. Regardless of what happened in New York or Afghanistan, they emphasized that there were animals suffering at that very moment, who could be spared if people took a few concrete steps. Had organizers in other circles been able to maintain this kind of focus and urgency, history might have taken a different turn at the beginning of this decade.</p>
<p> It&rsquo;s possible, also, that with other forms of organizing at a lower ebb, SHAC picked up more participants than it would have if other direct action campaigns had maintained momentum. In contrast to the massive symbolic actions of the antiwar movement, the SHAC campaign was a hotbed of experimentation, in which new tactics were constantly being tested. For direct action enthusiasts concerned with making the most of their efforts&mdash;or simply bored with being treated as a number in a crowd estimate&mdash;it must have been seductive by comparison.</p>
<p> Whatever the cause, the SHAC campaign was able to maintain momentum until federal repression finally began to take its toll. Unlike many campaigns, which have faded due to attrition or cooptation, it took the full power of the state to check its advance.<br />
</p>
<h3>Repression</h3>
<p> All the accomplishments of the SHAC campaign came at a price. The more businesses dropped relations with HLS, the more attention the campaign attracted from law enforcement agencies and right wing think tanks. SHAC organizers in general were not an easily intimidated breed; it was common for participants in the campaign to joke about all the lawsuits and injunctions they had racked up and how little it mattered if they were sued as they had no money anyway.</p>
<p> The US and British governments ratcheted up repression steadily over the years, placing activists under surveillance, hitting them with lawsuits, blocking their fundraising efforts, intimidating organizations like PETA out of interacting with them, passing new laws against demonstrations in residential neighborhoods, and shutting down their websites. This culminated in the US with the trial of <a href="http://www.shac7.com" target="_blank">the so-called SHAC 7</a>: six organizers and the SHAC USA corporation itself.</p>
<p> On May 26, 2004, Lauren Gazzola, Jake Conroy, Josh Harper, Kevin Kjonaas, Andrew Stepanian, and Darius Fullmer were indicted on various federal charges for their alleged roles in the campaign. Teams of FBI agents in riot gear invaded their homes at dawn, threatening them and their pets with guns and handcuffing their relatives. The investigation leading up to the arrest was reportedly the FBI&rsquo;s largest investigation of 2003; court documents confirm that wiretap intercepts in the investigation outnumbered the intercepted communications of that year&rsquo;s second largest investigation 5 to 1.</p>
<p> The defendants were all charged with violating the <a href="http://www.greenisthenewred.com/blog/aepa/" target="_blank">Animal Enterprise Protection Act</a>, a controversial law intended to punish anyone who disrupts a corporation that profits from animal exploitation; some were also charged with interstate stalking and other offenses. The defendants were never charged with engaging personally in any threatening acts; the government based its case on the notion that they should be held responsible for all the illegal actions taken to further the SHAC campaign, regardless of their involvement. They were found guilty on March 2, 2006, sentenced to prison terms ranging from one to six years, and ordered to pay tremendous quantities of money to HLS.</p>
<p> The SHAC 7 trial was clearly intended to set a precedent for targeting public organizers of campaigns that include covert action; its repercussions were felt as far away as England. In 2005, the British government passed the &ldquo;Serious Organized Crime and Police Act&rdquo; specifically to protect animal research organizations. On May 1, 2007, after a series of raids involving 700 police officers in England, Holland, and Belgium, 32 people linked to SHAC were arrested, including Heather Nicholson and Greg and Natasha Avery, among the founders of SHAC in Britain. In January 2009, seven of them were sentenced to prison terms between four and eleven years.<br />
</p>
<h3>The Future of SHAC</h3>
<p> Despite all these setbacks, the SHAC campaign continues to this day, though it faces serious challenges in the United States. Some regional organizations are still active, and autonomous actions continue to occur, but there is no nationwide organizing body, no newsletter, no reliable website to publicize targets and action reports. Consequently, there is less strategic targeting, less outreach and networking, and a lack of national events. The upside is that it has become more difficult for companies to figure out who to subpoena or seek injunctions against&mdash;but that&rsquo;s a narrow silver lining.</p>
<p> This downturn can be attributed to government repression in general and the SHAC 7 trial specifically. Fear of legal repercussions has increased at the same time as key organizers have been taken out of action. With new local laws prohibiting residential picketing, and the Animal Enterprise Terrorism Act of 2006 making interstate tertiary targeting illegal, many tactics that once involved little risk are no longer feasible. Now that more public forms of organizing are being more aggressively punished, it seems possible that the next generation of animal liberation activists will focus more on clandestine tactics. One of the strongest features of the SHAC campaign was the combination of public and clandestine approaches, so this is not necessarily good news for the movement.</p>
<p> It&rsquo;s actually quite surprising that HLS is still in existence; half a decade ago, SHAC organizers must have been banking on already having won by this point. When Stephens, Inc. divested, their loans were all that kept HLS running; it was only the British government intervening again that enabled HLS to negotiate a refinancing and continue. Essentially, SHAC did win, only to have its victory stolen away. The same situation recurred when SHAC forced Marsh Inc. to break off ties, and HLS was faced with the prospect of operating without the insurance mandated by law. Again, the British government intervened, and HLS was given unprecedented coverage by the Department of Trade and Industry. Without this protection from the very pinnacle of power, HLS would be long gone&mdash;but that&rsquo;s precisely why governments exist: to protect corporations and preserve the smooth functioning of the capitalist economy. Perhaps it was na&iuml;ve to believe that the governments of Britain and the USA would permit even the fiercest animal liberation campaign to run an influential corporation out of business.</p>
<p> One can&rsquo;t fight like there&rsquo;s no tomorrow indefinitely, and the repeated return of HLS from the dead must have been maddening for long-term SHAC organizers who staked everything again and again on one final push. Participants disagree as to how significant a factor burnout has been, but it would be foolish to rule it out. The SHAC campaign has been oriented towards full-time activism from the beginning, the mindset being that, as HLS employees work full time, their opponents must work at least that hard. Newsletter articles such as the &ldquo;SHACtivist workout routine&rdquo; indicate a high-pressure approach that probably correlates with a high rate of burnout. In any case, as difficult as it may be to distinguish the effects of burnout from those of fear, many activists have indeed dropped out of SHAC without moving on to other campaigns.</p>
<p>SHAC is currently active in mainland Europe and Latin America, and unrelenting in Britain. The British SHAC campaign may offer a better model for how to handle federal repression; from this vantage point, it appears that British activists were prepared in advance for it, had people ready to take over for central organizers, and were more open to new people getting involved. But Britain is more densely populated than much of the United States and has a richer history of animal rights organizing, so it is unfair to compare the two campaigns too closely.</p>
<p> Will SHAC ultimately succeed in shutting down HLS? It&rsquo;s still possible, though it looks less likely than it did a few years ago. Some still feel that the most important thing is to close HLS at all costs, to win an historic victory that will inspire activists and terrify executives for decades to come. Others think that, whether or not HLS shuts down, SHAC has served its purpose, demonstrating the strengths and limitations of a new model for anticapitalist organizing.</p>
<h3>Hallmarks of the SHAC Model</h3>
<p>When people think of SHAC, they picture demonstrations at the homes of employees and investors; some anarchists mean nothing more than this when they refer to the &ldquo;SHAC model.&rdquo; But home demonstrations are merely incidental to the formula that has enabled SHAC to wreak such havoc upon HLS. To understand what made the campaign effective, we have to look at all its essential characteristics together.</p>
<p><strong>&bull; Secondary and tertiary targeting:</strong><a class="footnote" href="javascript:void(0);" onclick="return overlib('Secondary targeting means going after a person or entity who does business with the primary target of a campaign. Tertiary targeting means going after a person or entity who is connected to a secondary target.', CAPTION, '[5]');" onmouseout="nd();">[5]</a> The SHAC campaign set about depriving HLS of its support structure. Just as a living organism depends on an entire ecosystem for the resources and relationships it needs to survive, a corporation cannot function without investors and business partners. In this regard, more so than any standard boycott, property destruction, or publicity campaign, SHAC confronted HLS on the terms most threatening to a corporation. Starbucks could easily afford a thousand times the cost of the windows smashed by the black bloc during the Seattle WTO protests, but if no one would replace those windows&mdash;or the windows had been broken at the houses of investors, so no one would invest in the corporation&mdash;it would be another story. SHAC organizers made a point of learning the inner workings of the capitalist economy, so they could strike most strategically.</p>
<p> Secondary and tertiary targeting works because the targets do not have a vested interest in continuing their involvement with the primary target. There are other places they can take their business, and they have no reason not to do so. This is a vital aspect of the SHAC model. If a business is cornered, they&rsquo;ll fight to the death, and nothing will matter in the conflict except the pure force each party is able to bring to bear on the other; this is not generally to the advantage of activists, as corporations can bring in the police and government. This is why, apart from the axe handle incident, so few efforts in the SHAC campaign have been directed at HLS itself. Somewhere between the primary target and the associated corporations that provide its support structure, there appears to be a fulcrum where action is most effective. It might seem strange to go after tertiary targets that have no connection to the primary target themselves, but countless HLS customers have dropped relations after a client of theirs was embarrassed.</p>
<p>&bull; <strong>Complementary relationship between public and underground organizing:</strong> More than any other direct action campaign in recent history, the SHAC campaign achieved a perfect symbiosis of public organizing and underground action. To this end, the campaign was characterized by an extremely savvy use of technology and modern networking. The SHAC websites disseminated information about targets and provided a forum for action reports to raise morale and expectations, enabling anyone sympathetic to the goals of the campaign to play a part without drawing attention to themselves.</p>
<p><strong>&bull; Diversity of tactics:</strong> Rather than pitting exponents of different tactics against each other, SHAC integrated all possible tactics into one campaign, in which each approach complemented the others. This meant that participants could choose from a practically limitless array of options, which opened the campaign to a wide range of people and averted needless conflicts.</p>
<p><strong>&bull; Concrete targets, concrete motivations:</strong> The fact that there were specific animals suffering, whose lives could be saved by specific direct action, made the issues concrete and lent the campaign a sense of urgency that translated into a willingness on the part of participants to push themselves out of their comfort zones. Likewise, at every juncture in the SHAC campaign, there were intermediate goals that could easily be accomplished, so the monumental task of undermining an entire corporation never felt overwhelming.</p>
<p> This contrasts sharply with the way momentum in certain green anarchist circles died off after the turn of the century, when the goals and targets became too expansive and abstract. It had been easy for individuals to motivate themselves to defend specific trees and natural areas, but once the point for some participants was to &ldquo;destroy civilization&rdquo; and everything less was mere reformism, it was impossible to work out what constituted meaningful action.<br />
</p>
<h3>Advantages of the SHAC Model</h3>
<p> When the model pioneered by SHAC is applied correctly, its advantages are obvious. It hits corporations where they are most vulnerable: corporations do not do what they do because of ethical commitments or in order to obtain a certain public image, but in single-minded pursuit of profit, and the SHAC model focuses exclusively on making corporate wrongdoings unprofitable. In terms of building and maintaining a long-running direct action campaign, the SHAC model offers direction and motivation for participants, providing a framework for concrete rather than symbolic actions. The SHAC model sidesteps conflicts over tactics, offering the opportunity for activists of a range of abilities and comfort levels to work together. In establishing a wide array of targets, it gives activists the opportunity to pick the time, place, and character of their actions, rather than constantly reacting to their opponents. Above all, the SHAC model is efficient: SHAC USA has never had more than a few hundred active participants at any given time.</p>
<p> In contrast to most current organizing strategies, the SHAC model is an offensive approach. It offers a means of attacking and defeating established capitalist projects&mdash;of taking the initiative rather than simply responding to the advance of corporate power. SHAC did not set out to block the construction of a new animal testing facility or the passage of new legislation, but to defeat and destroy an animal testing corporation that had existed for decades.</p>
<p> The SHAC model demands and fosters a culture that not only celebrates direct action but constantly engages in it, encouraging participants to push their own limits. This contrasts sharply with certain so-called insurrectionist circles, in which anarchists talk a lot about rioting and resistance without engaging in day-to-day confrontations with the powers that be. Anti-globalization activists in Chicago sometimes asked SHAC organizers to lead chants at their protests, as the latter had a reputation for being boisterous and energetic: those who cut their teeth in the SHAC campaign, if they have not dropped out of direct action organizing entirely, are equipped to be effective in a wide range of contexts.</p>
<p> A subtler strength of the SHAC approach is that it draws on class tensions that are usually submerged in the United States. Activists from lower middle- and working-class backgrounds can find it gratifying to confront wealthy executives on their own turf. This also exposes single-issue activists to the interconnections of the ruling class. In visiting the houses of executives, one discovers that all the pharmaceutical and investment corporations are intertwined: they all own shares of each other&rsquo;s companies, sit on each other&rsquo;s boards, and live in identical suburban mansions in sprawling gated communities.</p>
<p> Finally, the SHAC model took advantage of opportunities offered by larger events and communities. Home demonstrations were often organized to take place after a conference or show; the ubiquity of potential targets meant there was always one close at hand. For several years running, SHAC demonstrations took place during the National Conference on Organized Resistance in Washington, DC, and they also occurred following anti-biotech protests in Philadelphia and Chicago. Though these sometimes provoked conflicts with other organizers, it only takes a couple dozen people to make an effective home demonstration, so it was always easy to pull one together.</p>
<p> SHAC itself tended to create and propagate a subculture of its own, complete with internal reference points and rituals. At conferences and major mobilizations activists compared notes about investors, local campaigns, and legal troubles. Sympathetic music scenes helped fund organizing and introduced new blood to the campaign. It would be difficult to imagine the SHAC campaign in the USA without the hardcore scene of the past two decades, which has consistently served as a social base for the militant animal rights movement. There are certainly drawbacks to identifying a campaign too closely with a specific youth-oriented subculture, but it is better to draw participants and momentum from at least one community than from none at all.<br />
</p>
<h3>Spurious Charges</h3>
<p> Some anarchists have thoughtlessly charged SHAC with reformism. This is absurd: SHAC&rsquo;s goal is not to change the way HLS conducts itself, but to shut it down. It is more precise to describe SHAC as an abolitionist campaign: not being able to bring about the end of animal exploitation in one fell blow, it seeks to accomplish the most ambitious but feasible step toward that end. Similarly, certain idle critics deride animal liberation efforts on the grounds that they are &ldquo;activism,&rdquo; with the implication that this is a bad thing in and of itself. Those who adopt this position should go ahead and acknowledge that they are unmoved by the oppression of their fellow living creatures and see no value in attempting to put an end to it&mdash;that is to say, they are hardly anarchists.<br />
</p>
<h3>Drawbacks and Limitations</h3>
<p>Spurious critiques aside, the SHAC model has some real limitations, which deserve examination.</p>
<p> First, there are certain prerequisites without which it will fail. For example, the SHAC model cannot succeed outside a setting in which direct action is regularly applied. All the strategic thinking in the world is worthless if no one is actually willing to act. In the militant animal rights milieu, the issues at stake are felt to be concrete and poignant enough that participants are motivated to take risks on a regular basis; without this motivation, the SHAC campaign would not have gotten off the ground. Likewise, the SHAC model is powerless against a target that does not depend on secondary and tertiary targets, or has an endless supply of them to choose from. Above all, the secondary and tertiary targets must have somewhere else to take their business&mdash;the SHAC model relies on the rest of the capitalist market to offer better options. In this regard, while it is not reformist, neither does it provide a strategy for taking on capitalism itself. </p>
<p> Secondly, as effective as they might be in purely economic terms, secondary and tertiary targeting locate the site of confrontation far from the cause for which the participants are fighting. Generally speaking, the more abstract the object of a campaign feels, the worse for morale. Much of the vitality of eco-defense struggles in the 1980s and &rsquo;90s came from the immediate, visceral connection forest defenders experienced with the land they were occupying; when environmental activism began shifting to more urban terrain a decade ago, it lost some of its impetus. It is perhaps specific to the SHAC campaign that participants have been able to maintain their outrage and audacity so far from the object of their concern; it is risky to assume this will always occur in other contexts.</p>
<p> Apart from these challenges, the SHAC model may be ineffective precisely because of its effectiveness. Is it realistic to set out to shut down powerful corporations, or will the government always intercede? It may be that in posing a threat to corporations in the economic terms they take most seriously, the SHAC model picks a fight it cannot win. Once the government is involved in a conflict, it takes more than a tight network of militants to win&mdash;it takes an entire large-scale social movement, and the SHAC approach alone cannot give rise to such a thing. In this regard, the SHAC model&rsquo;s greatest strength is also a fatal flaw.</p>
<p> Time will tell if HLS was too ambitious a target; the corporation might still collapse. Even so, it would probably be wise for the next ones who experiment with the model to set smaller goals, rather than even more ambitious ones, since the SHAC campaign itself has yet to succeed. Perhaps some unexplored middle ground awaits between shutting down individual fur stores and attempting to close Europe&rsquo;s largest animal testing corporation.</p>
<p> This is not to say that the SHAC model is useless if it does not result in the closure of the target. Sometimes it is worth fighting a losing battle so as to discourage an opponent from starting another battle; other times, even in losing one can gain valuable experience and allies. Ironically, the SHAC model may be more effective for recruiting people to direct action organizing than for its professed goal&mdash;precisely because, in bypassing recruitment to focus on other goals, it attracts participants who are serious and committed.</p>
<p> But if the point is to bring more people into direct action organizing rather than simply to shut down a single corporation, there are significant drawbacks to the SHAC model, too&mdash;for example, the high stress levels and likelihood of burnout. In this regard, it is not necessarily an advantage that the SHAC model teaches activists to think in the same terms as capitalist economists&mdash;efficiency, finances, chain of command&mdash;rather than prioritizing the social skills necessary to build long-term communities of resistance.</p>
<p> Likewise, in focusing on secondary and tertiary targeting, the SHAC model emphasizes and rewards an aggressive attitude that is less advantageous in other situations. What are the long-term psychological effects on organizers who spend half a decade or more screaming over a bullhorn at employees in their homes? What kind of people are drawn to a campaign that consists primarily of making other people miserable? It cannot go unsaid that some anarchists have reported frustrating interactions with SHAC organizers.</p>
<p> Considering the model from an anarchist perspective&mdash;to what extent does the SHAC approach tend to consolidate or undermine hierarchies? The secure organizing necessary for clandestine direct action can promote a cliquishness than intensifies as repression increases, thus preventing a campaign from drawing in new participation when it needs it most. Informal hierarchies plague organizing of all kinds; in the case of the SHAC campaign, those who do the research often have disproportionate influence over the direction of a campaign and end up making judgment calls with far-reaching effects.</p>
<p> It could be argued that the single-issue focus and goal-oriented nature of the SHAC campaign deprioritizes addressing forms of hierarchy other than the oppression of animals. It is no secret that some SHAC organizing groups have been wracked by conflicts over gender dynamics<a class="footnote" href="javascript:void(0);" onclick="return overlib('If there have not been corresponding conflicts regarding race and class, this may simply indicate that SHAC organizing has been predominantly white and middle class. Some have charged that the animal rights movement in the US attracts many from this demographic who are more comfortable protesting the oppression and exploitation of animals than addressing the power imbalances in their relationships with other human beings.', CAPTION, '[6]');" onmouseout="nd();">[6]</a> and some participants have not always been held accountable for their behavior. In a campaign that emphasizes victory above all else, this should not be surprising&mdash;if the most important thing is to win, it&rsquo;s easy to put off addressing internal conflicts, especially with the added stress of federal repression. Inevitably, the people who have bad experiences drop out of the campaign, taking with them the criticism others need to hear.</p>
<p> These questionable priorities have also manifested themselves in certain tasteless tactics. In one instance, a target who was struggling to escape alcoholism received a can of beer with a nasty note; in another, a woman&rsquo;s underwear was stolen and reportedly put up for sale. Utilizing the power imbalances of patriarchal society to target accomplices in the oppression of animals hardly sets an example of struggle against all forms of domination.</p>
<p> There are other ethical questions about secondary and tertiary targeting. Is it acceptable to risk frightening or injuring secretaries, children, and other uninvolved parties? What distinguishes anarchists from governments and other terrorists, if not the refusal to countenance collateral damage?</p>
<p> In essence, the SHAC model is a blueprint for a campaign of coercion, to be used in situations in which there is no other possible accountability process. This does not conflict with anarchist values&mdash;when an oppressor refuses to be accountable for his actions, it is necessary to compel him to stop, and this extends to those who aid and abet him as well. But targeting people who are not themselves involved in oppression muddies the waters. When an organizer publicizes a target, there is no telling what actions others will carry out. Perhaps the value of ending animal exploitation outweighs these risks and costs, but anarchists should not get too comfortable making such rationalizations.<br />
</p>
<h3>Other Applications of the SHAC Model</h3>
<p> There has been much talk of applying the SHAC model in other contexts, but few such efforts have produced anything comparable to the SHAC campaign. This bears some reflection. It&rsquo;s worth pointing out that some of the hype about the far-reaching applicability of the SHAC model has come straight from HLS, and so should be taken with a grain of salt. HLS is not interested in promoting effective new direct action methods, but rather in creating enough of a scare that other members of the ruling class will come to their assistance; it follows that even if they claim that SHAC tactics can be used effectively against any target, this is not necessarily the case. The same goes for <a href="http://www.stratfor.com/shac_convictions_martyrdom_effect" target="_blank">sensationalist analyses</a> by organizations such as Stratfor, whose primary goal seems to be terrorizing the public into feeling a need for their &ldquo;intelligence.&rdquo;</p>
<p>    It may be that, because the SHAC campaign maintained momentum while other forms of organizing dropped off, it has exerted a disproportionate influence upon the imaginations of current anarchists, to such an extent that many now tend to imitate the SHAC model in their organizing even when it is not strategically effective. Failures can be more instructive than successes; unfortunately, as they are more readily forgotten, they are often repeated over and over. For this reason, any consideration of the SHAC model should begin with the example of <a href="http://www.rootforce.org" target="_blank">Root Force</a>.</p>
<p> Root Force arose out of Earth First! circles a couple years ago with the intention of promoting a SHAC-style campaign targeting the infrastructure of global capitalism&mdash;an exponentially more ambitious goal than shutting down HLS. The organizers researched the corporations involved in pivotal infrastructural projects such as transcontinental highways and power plants. A website was set up to publicize this information and any actions that occurred; road shows toured the country to spread the word. It seemed that all the pieces were in place, and yet nothing happened.</p>
<p> Early in 2008, Root Force released a statement entitled &ldquo;<a href="http://www.rootforce.org/2008/02/10/a-revised-strategy/" target="_blank">A Revised Strategy</a>&rdquo; in which they acknowledged that their efforts had failed to produce an effective direct action campaign and described the difficulties of attempting to inspire action against infrastructural projects located so far away as to seem entirely abstract.</p>
<p> Root Force misunderstood how direct action campaigns take off. Action and inaction are both contagious. If some people are invested enough in a cause to risk their freedom for it, others may do the same; but as no one wishes to go out on a limb in isolation, a sound strategy alone is not sufficient to inspire actions.<a class="footnote" href="javascript:void(0);" onclick="return overlib('Compare this to the critique of calls for &ldquo;autonomous actions&rdquo; at mass mobilizations in &ldquo;Demonstrating Resistance,&rdquo; available in the recent features section of the reading library on this site.', CAPTION, '[7]');" onmouseout="nd();">[7]</a> Properly publicized, one serious direct action in the Root Force campaign would have been worth a hundred road shows.</p>
<p> The Root Force campaign had other flaws as well. If the goal was simply to give demonstrators something to do, the strategy was as good as any other; but if they hoped to block the construction of the highways and power plants most essential to the expansion of the capitalist market, they would have had to mobilize a lot more force than the SHAC campaign. If the targets they picked really were of critical importance to the powers that be, it follows that the government would have mobilized every resource to defend them. Overextension is the number one error of small-scale resistance movements: rather than setting attainable goals and building slowly on modest successes, organizers set themselves up for defeat by attempting to skip directly to the final showdown with global capitalism. We can fight and win ambitious battles, but to do so we have to assess our capabilities realistically.</p>
<p> Other SHAC-influenced approaches have been characterized by an emphasis on home demonstrations. For example, over the past few years, protesters against the IMF and World Bank have experimented with targeting executives and corporate sponsors. In 2006, while Paul Wolfowitz was president of the World Bank, there were a series of demonstrations at his girlfriend&rsquo;s home; eventually she moved. This does not seem to have impacted the IMF to the same extent as the worldwide upheavals associated with the anti-globalization movement. Sarcasm aside, there&rsquo;s little to be gained from harassing people like Wolfowitz: unlike the tertiary parties SHAC targeted, they are not simply going to take their business elsewhere.</p>
<p> Similarly, at the 2004 Republican National Convention, some organizers called for demonstrators to focus on harassing the delegates. The risk of this approach is that it can frame the conflict as a private grudge match between activists and authorities, rather than a social movement that is able to attract mass participation. Like Wolfowitz, Republican delegates are hardly going to retire because a few protesters shout at them&mdash;and even if some did, they would instantly be replaced. One proposal for the 2008 RNC protests involved activists targeting corporations that would be providing services to the convention. Targeting corporations providing services might have helped build momentum in the lead-up to the RNC, but it&rsquo;s unlikely that it could have succeeded in depriving an organization as powerful as the Republican Party of necessary resources. The same probably goes for proposals to target weapons contractors serving the US government&mdash;it might give demonstrators something exciting to do, but no one should underestimate what it would take to make a corporation like Boeing break off relations with the US military.</p>
<p> Some see the <a href="http://www.risingtidenorthamerica.org/wordpress/what-is-rising-tide/" target="_blank">Rising Tide</a> and <a href="http://ran.org/" target="_blank">Rainforest Action Network</a> campaigns against Bank of America as relatives of the SHAC campaign; these did use secondary targeting, although they were directly descended from environmental campaigns that preceded it. At the end of 2008, in a context of broader economic turmoil, Bank of America declared that they were pulling their financing from companies predominantly involved in mountain-top removal. However insincere this declaration may be, it at least indicates that the campaign forced BOA to take notice. Environmentalists in Indiana have had less success attempting to stop the construction of highway I-69 via a combination of home and office demonstrations and forest occupation tactics. In &ldquo;A Revised Strategy,&rdquo; Root Force cited I-69 as a pivotal infrastructural project; it will be interesting to see how the state responds if the struggle against I-69 ever becomes formidable.</p>
<p> All this is not to say that the SHAC model cannot be applied effectively, but simply to emphasize that activists must be intentional and strategic about where and how they attempt to do so. There are probably some situations in which the model could accomplish even more than it has for SHAC; without a doubt, there are other contexts in which it can actually be counterproductive.</p>
<p> To repeat, the SHAC campaign in the US has only involved a few hundred participants at any given time; a few thousand could possibly take on a bigger target. Even forcing the government to bail out a corporation, whether or not the target was successfully bankrupted, could still constitute an important victory. As of today, it remains to be seen where effective applications of the SHAC model will be found beyond the campaign that spawned it.
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1] Unlike HSUS and PETA, the ALF is not technically an organization, but rather a banner taken up by autonomous cells which do not necessarily have any connection to each other.
</p>
<p>[2] According to reports, the main organizers of this group have since joined HSUS. This is an example of the subtle conflicts and power dynamics that play out in the animal rights movement: SHAC organizers complain that HSUS absorbs committed activists by giving them paying jobs and forbidding them to collaborate with more militant activists.</p>
<p>[3] Unlike many social movements, the animal rights movement is supported by wealthy donors, and we can assume that some of them have contributed to SHAC.
</p>
<p>[4] This advertisement is all the more ironic in view of the role masked thugs in nations like Colombia continue to play in defending the interests of corporations who trade on Wall Street.</p>
<p>[5] Secondary targeting means going after a person or entity who does business with the primary target of a campaign. Tertiary targeting means going after a person or entity who is connected to a secondary target.</p>
<p>[6] If there have not been corresponding conflicts regarding race and class, this may simply indicate that SHAC organizing has been predominantly white and middle class. Some have charged that the animal rights movement in the US attracts many from this demographic who are more comfortable protesting the oppression and exploitation of animals than addressing the power imbalances in their relationships with other human beings.</p>
<p>[7] Compare this to the critique of calls for &ldquo;autonomous actions&rdquo; at mass mobilizations in &ldquo;Demonstrating Resistance,&rdquo; available in the recent features section of the reading library on this site.</p></div>