<p align="center"><a href="https://cloudfront.crimethinc.com/images/standing/1b.jpg" rel="lightbox[standing]"><img src="https://cloudfront.crimethinc.com/images/standing/1a.jpg" width="500" height="511" title="Standing on the Land to Stand Up Against Pipelines, A Report from the Unist&#8217;ot&#8217;en Camp"/></a></p>
<p>&nbsp;</p>
<h2>Introduction</h2>
<p>Across Turtle Island, a powerful resistance is rising. As corporations attempt to enter a new era of even dirtier fossil fuel production, indigenous communities are standing up to take direct action to protect Mother Earth. From Fort Chip to Beaver Lake, Red Lake to Lakota, communities are organizing. Some are pursuing legal challenges against violated treaties. Others are creating internet-driven mass movements such as <a href="http://idlenomore.ca/">Idle No More</a>. Others still are reclaiming their roots by going back to the land to assert traditional law. Among the latter are the Unist&#8217;ot&#8217;en, the People of the Headwater, whose lands encompass a wide swath of Northern British Columbia.</p>
<p>When companies like Enbridge and Apache announced plans to build a massive pipeline corridor through these lands, it provoked outrage from the Wet&#8217;suwet&#8217;en people whose traditional territory lies directly in its proposed path. Of the five Wet&#8217;suwet&#8217;en clans, the Unist&#8217;ot&#8217;en were the first to officially declare themselves opposed to ALL pipelines being proposed to cross their traditional territories. Now the Likhts’amisyu, Tsayu, and Git’dum’den clans have followed suit and momentum is growing. </p>
<p>This article tells the story from the perspective of the Unist&#8217;ot&#8217;en and their allies at the <a href="http://unistotencamp.com/">Unist&#8217;ot&#8217;en Camp</a> through the winter of 2012&#8211;3. It has been collectively produced by both indigenous and settler voices.</p>
<h2>Taking Care of the Land—Unist&#8217;ot&#8217;en Resistance to Pipelines and Other Projects</h2>
<h3>Background and Cultural Context</h3>
<p>Colonization has left a lingering impact on the 22,000 square kilometers of unceded Wet&#8217;suwet&#8217;en territories which stretch from the Bulkley Valley to Burns Lake. Weakened by a devastating series of contact-based illnesses, the Wet&#8217;suwet&#8217;en were displaced from their land over time as more and more settlers arrived in the area starting in the late 1800s. Decades of insidious assimilation policies served to reinforce colonial land-theft, including the establishment of the Moricetown reserve and the horrific residential school program that took many children from their homes and subjected them to physical abuse, sexual abuse, and Christian indoctrination. With the settlers came the logging and mining industries. Today, the forests have been decimated, a mono-cropped shadow of their former diversity. </p>
<p>Through all this, the sovereignty of Wet&#8217;suwet&#8217;en land was never surrendered, and to a large degree their culture remains intact. Today, many among the Wet&#8217;suwet&#8217;en still speak their language, fish and harvest berries as their ancestors did, and continue to maintain their traditional system of governance. But now the specter of a massive pipeline corridor has awoken a new urgency amongst the people. If the Wet&#8217;suwet&#8217;en do not rise to defend their lands now, the impact will be devastating, not only to them but for generations to come.</p>
<p>The Unist&#8217;ot&#8217;en are the original people distinct to the lands of the Wet&#8217;suwet&#8217;en. Over time, others have joined them and there are now five Clans who identify as Wet&#8217;suwet&#8217;en. Each clan has autonomous authority over its own traditional territory. Each territory has a hereditary chief who is responsible for its care. </p>
<h3>Sovereignty and Traditional Governance</h3>
<p>Hereditary Chiefs are chosen by the entire Clan Group; they prepare by learning about the features of the territory, how to conduct themselves on it, and the techniques and ceremonies that spiritually connect them to every aspect of their lands. In the past, medicine people selected chiefs while they were still in their mothers’ wombs. The current chief of the Unist&#8217;ot&#8217;en territory known as Talbits Kwa is Warner Williams, who was directed by his grandmother, the former chief, to protect the territory from development.</p>
<p>The decisions of the Clan are made in their Feast Hall, where all the members of the clan gather to share gifts with each other and manage their affairs. Here the Unist&#8217;ot&#8217;en practice a form of decision-making that resembles a consensus approach. They sit down and listen to each other, and together they come to decisions that reflect the unified position of the clan. The decisions made in the Feast Hall are the ultimate authority of the land—which is important to note in relation to the Band Council System of government.</p>
<p>The Band Council system is a governance structure created by the Canadian state through the <a href="http://en.wikipedia.org/wiki/Indian_Act">Indian Act</a>. The Unist&#8217;ot&#8217;en and grassroots Wet&#8217;suwet&#8217;en grudgingly accept that the Band Council has a limited authority, extending only to managing the affairs of the reserve it was created to represent. That authority in no way extends to traditional territory which remains governed by the Hereditary Chiefs. Therefore any deal claimed to have been reached by a pipeline company with a First Nation Band Council is not legitimate, unless it also has the consent of the Hereditary Chiefs and the Clan itself. </p>
<p>With respect to Unist&#8217;ot&#8217;en traditional territory, the Moricetown Band Council has acknowledged the authority of the hereditary chiefs and therefore refrained from signing any deals with pipeline companies. In other places such as Burns Lake, where the Band Council has been signing deals without even consulting the people, there has been growing protest. Representing an unbroken line of tradition that continued even through a period when the Feast system was made “illegal” by the state, the Wet&#8217;suwet&#8217;en regard their law as pre-dating and superseding the authority of the Canadian state. </p>
<h3>The Clan Decision to Reject All Pipelines</h3>
<p>When it came out that industry and government were hatching a plan for a massive pipeline corridor through their territory, the Unist&#8217;ot&#8217;en clan assembled to discuss the issue. They made the decision to reject all pipeline proposals. This uncompromising opposition to ALL pipelines through their territory is no surprise considering the historical reputation of the Unist&#8217;ot&#8217;en as a tough and hardy people with a fierce warrior tradition. The impact of the Unist&#8217;ot&#8217;en decision is considerable as their territories account for two thirds of the total Wet&#8217;suwet&#8217;en land base. </p>
<p>A major contributing factor to the decision of the Unist&#8217;ot&#8217;en was the influence of former chief Christine Holland, who directed her clan to protect the land and preserve it for future generations. The Unist&#8217;ot&#8217;en were also in a phase of reasserting their sovereignty in general; along with the other Wet&#8217;suwet&#8217;en clans, they had recently terminated unproductive treaty negotiations with Canada. In doing so, they choose to maintain their rights as a sovereign people that had never surrendered the title to their lands.</p>
<p>The Unist&#8217;ot&#8217;en knew that simply making the decision would not be enough to stop the pipelines. If they wanted to regain authority over their territory, they would have to get out on it. A clan cabin was constructed on the exact GPS coordinates of the proposed path of the Enbridge Northern Gateway and Pacific Trail Pipelines (then known as the Kitimat Summit Lake Loop or KSL). The site is situated in the Unist&#8217;ot&#8217;en territory known as Talbits Kwa, whose border follows the bank of the Wedzin Kwa (known colonially as the Morice River). A single-lane bridge is the only way in and out of the territory, and can only be accessed by a logging road running south from Houston, BC.</p>
<h3>The First Action Camp</h3>
<p>That summer the Unist&#8217;ot&#8217;en called for others to join them out on the territory for what would be their first annual Action Camp in July 2010. Among those who answered the call for solidarity were local allies from the other Wet&#8217;suwet&#8217;en clans, representatives from large environmental groups such as Greenpeace and the Sierra Club, and grassroots environmental activists and supporters of indigenous sovereignty. The camp organized a march through the nearby town of Smithers, where the Unist&#8217;ot&#8217;en served notice to the Ministries of Forest and Environment offices of their intention to manage their own affairs, announcing that any group or company which wished to access the territory would need to go through a Free Prior Informed Consent protocol with the members of the clan.</p>
<p>At the rally, hereditary chief Knedebeas asserted: “Our Unist’ot’en members will not sway under the threats and actions of industry and government. My grandmother Christine Holland gave us specific directions to protect our lands—that is exactly what we intend to do.”</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/standing/2b.jpg" rel="lightbox[standing]"><img src="https://cloudfront.crimethinc.com/images/standing/2a.jpg" width="500" height="375"/></a>
<em>Wet&#8217;suwet&#8217;en, Gitxsan, and Nat&#8217;ot&#8217;en supporters join solidarity action at chevron station in Smithers, BC</em></p>
<h3>Falling Out With The ENGOs and Transition to Grassroots Resistance</h3>
<p>The initial presence of environmental non-governmental organizations (ENGOs) at the first action camp was controversial. Some indigenous allies were wary based on the history of ENGOs aligning with grassroots efforts then sidelining them to sign deals with industry, such as what happened during the Great Bear Rainforest campaign; but the ENGOs had a lot of resources to help generate publicity for the Unist&#8217;ot&#8217;en resistance to the pipeline. </p>
<p>Unfortunately, the relationships deteriorated over the course of the camp. It became clear that some of the ENGOs were uncomfortable with certain positions of the Unist&#8217;ot&#8217;en. One person even inquired if the phrase “No <a href="http://en.wikipedia.org/wiki/Carbon_offset">Offsetting</a>” could be taken off one of the Unist&#8217;ot&#8217;en&#8217;s banners prior to the rally in Smithers. The Unist&#8217;ot&#8217;en regard offsetting as a dangerous false solution that allows polluters to continue their dirty practices by purchasing (often fictitious) offsets from another part of the world, but many ENGOs support offsetting—and possibly even hope to profit from it to fund their own activities</p>
<p>Further complicating the situation was the ENGOs reluctance to support the Unist&#8217;ot&#8217;en&#8217;s opposition to ALL pipelines. While the ENGOs were actively running campaigns against Enbridge Northern Gateway, they were ignoring that there was an entire corridor of pipelines planned. The ENGOs argued that opposing Northern Gateway was strategic, because there was more public support for opposing the oil pipelines than the gas ones. To the Unist&#8217;ot&#8217;en, stopping one pipeline meant nothing if you allowed all the others to pass through. In the end, many among the Unist&#8217;ot&#8217;en felt that the ENGOs were there to gain credibility as supporters of indigenous struggle, rather than to do actual work to benefit the territory.</p>
<h3>The Second Action Camp</h3>
<p>Based on the way things went with the first Action Camp, the Unist&#8217;ot&#8217;en decided to move forward with credible grassroots allies who supported their message and would stand by them in a crisis. As a result, <a href="http://stoptheflows.tumblr.com/">the second Action Camp</a>, held in August 2011, was invitation only, and the ENGOs were not invited. The ENGOs didn&#8217;t miss a beat, however, and simply shifted their support to Tribal Council bodies who were publicly advocating against Enbridge while quietly signing deals with Pacific Trails. </p>
<p>Smaller in scale and best understood as a transitional effort, the second camp saw the formation of solid relationships. Groups like <a href="http://noii-van.resist.ca/">No One is Illegal Vancouver</a>, <a href="http://forestaction.wikidot.com/">Victoria&#8217;s Forest Action Network</a>, and <a href="http://bcblackout.wordpress.com/">BC Blackout</a> emerged as the new allies of the Unist&#8217;ot&#8217;en, reflecting the new shift to community, grassroots, and autonomous support. The Unist&#8217;ot&#8217;en found that they shared many ideals with these groups—a stance encompassing opposition to ALL pipelines, respect for the sovereignty of the Unist&#8217;ot&#8217;en, and opposition to colonialism in general.</p>
<iframe width="500" height="281" src="//www.youtube-nocookie.com/embed/KyC4oUILmCk?rel=0" frameborder="0" allowfullscreen></iframe>
<h3>The First Blockade: The Unist&#8217;ot&#8217;en Take Action To Defend Their Land</h3>
<p>The fall of 2011 saw the first real test of the Unist&#8217;ot&#8217;en&#8217;s will to defend their territory against pipeline development. A phone call in the middle of the night alerted the Unist&#8217;ot&#8217;en that Pacific Trail Pipeline drillers were coming out to do work on the territory. Because, the Unist’ot’en were in mourning for a deceased Clan member in the community of Moricetown, the cabin was not being occupied full-time, and so the Unist&#8217;ot&#8217;en had to scramble into their trucks and race out to the territory from Moricetown. </p>
<p>The drillers were setting up to do work at Gosnell Creek, one of the most sensitive coho salmon spawning tributaries in their territory. The Unist&#8217;ot&#8217;en who had made the trip confronted the drillers and told them they were to cease work immediately and had five days to get all their equipment out or it would be confiscated. Later the next day the Unist&#8217;ot&#8217;en chiefs came out and issued the same command. The drillers complied and the incident was resolved peacefully.</p>
<p>In solidarity with the Unist&#8217;ot&#8217;en, BC Blackout organized an autonomous demonstration outside PTP co-owner Apache&#8217;s Vancouver office. BC Blackout brought a more militant message to the settler side of Unist&#8217;ot&#8217;en solidarity, expressing the viewpoint that “the struggle to protect the land is one with the struggle to free ourselves from wage slavery and the state.” Following the December solidarity action, allies in Vancouver and Victoria organized a series of fundraisers that enabled Victoria FAN to coordinate a caravan of supporters and supplies to the Third Action camp the following summer.</p>
<h3>The Third Action Camp</h3>
<p>In August 2012, allies of the Unist&#8217;ot&#8217;en once again gathered on the territory to express solidarity. Maintaining the grassroots tone established during the second camp, the third camp saw a considerable increase in attendance. Thanks to the caravan organized by Victoria&#8217;s Forest Action Network, there were many new and young faces from radical scenes in Vancouver and Victoria; for many of them, this was their first direct experience of indigenous culture.</p>
<p>A major objective of the camp was to further assert Unist&#8217;ot&#8217;en sovereignty over the territory, and a checkpoint was established at the bridge. Anyone wishing to cross into the lands of the Unist&#8217;ot&#8217;en would have to pass through a Free Prior Informed Consent protocol. The protocol was applied not only to camp attendees but to industrial activity as well.</p>
<p>Although it borrows language from the United Nations, the Unist&#8217;ot&#8217;en FPIC protocol reasserts a traditional practice. Before their culture was disrupted by colonization, any visitor or trader wishing to enter or do business on Unist&#8217;ot&#8217;en land would be greeted by representatives of that clan. They would have to answer questions as to who they were, where they were coming from, how long they wanted to stay, and how their presence would be beneficial to the territory.</p>
<p>When it was discovered that some of the loggers trying to pass through had been assigned cut-blocks that looked suspiciously like a pipeline right-of-way, they were denied entry and the road was closed. This created a stir in Houston, the nearby town where companies claimed they were losing thousands of dollars each day. For the first time, the executives of the logging companies were forced to come out to meet with the chiefs on the territory. After an open dialogue between the chiefs and the logging executives, it was agreed that the companies could come and collect the trees that had already been felled and logging could continue in other areas, but no new cutting was to occur for the right-of-way1. </p>
<p>Education about decolonization was also a major focus of the camp, especially for the new allies, because it is important to the Unist&#8217;ot&#8217;en that their allies have a solid understanding of who they are as a people and how the pipelines relate to the larger story of colonization. Decolonization work can be a painful process in its initial stages, especially as one strips away the fables that are told to justify the theft, murder, and displacement necessary to establish the Colonial State on indigenous land. </p>
<p>Yet by the end of the camp, a real sense of camaraderie had emerged. Alliances created during the second camp became cemented during the third. In the place of pacifist ENGOs, the Unist&#8217;ot&#8217;en now had loyal friends who understood the value of direct action and respected their warrior spirit. They also brought a spirit of working together to get things done—like stepping up to bottom-line the huge task of the kitchen. As the camp ended, almost everyone pledged to return the following year, or earlier if need arose.</p>
<h2>Permanent Occupation</h2>
<p>The winter of 2012 marked the beginning of full-time occupation of the camp by Unist&#8217;ot&#8217;en clan members. Based on the experience of the previous winter, the Unist&#8217;ot&#8217;en were wary that the pipeline companies would try to return and complete the work that had been thwarted previously, but with so much of their energy focused on organizing the Action Camp, there remained a mountain of work to prepare for winter out on the land.</p>
<p>The immediate challenge was to ready the main cabin for winter. The covered deck area served as an outdoor kitchen during the summer but needed to be enclosed and insulated for the winter. At the same time, the momentum generated by the Third Action Camp had created a series of opportunities to participate in larger events in the Lower Mainland. </p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/standing/3b.jpg" rel="lightbox[standing]"><img src="https://cloudfront.crimethinc.com/images/standing/3a.jpg" width="500" height="235"/></a>
<em>The unist&#8217;ot&#8217;en camp in all its winter glory</em></p>
<p>The solution emerged with the concept of front-line allies. It started with a few trusted settler allies from the Action Camp who stayed behind, initiating a daily relationship of direct support. The presence of these allies was critical in enabling the Unist&#8217;ot&#8217;en to move ahead with needed construction work while freeing up leaders to travel and raise further awareness for the Camp.</p>
<p>One of these events was the problematically-titled “Defend Our Coast” rally, a coalition effort bottom-lined by some of the biggest players in the Canadian environmental movement—including Greenpeace, Tzeporah Berman, and Sierra Club. Friction abounded over framing the coast as something that belonged to Canadian society the failure to consult local organizing and indigenous communities. The action also continued the recent NGO trend of tokenized civil disobedience. In the traditional use of the tactic, civil disobedience has been a direct action to break a law perceived to be unjust, often at great risk to the participants. The classic example from the Civil Rights era is Rosa Parks refusing to give up her bus seat to a white person. In the new incarnation being promoted by 350.org, Sierra Club, Greenpeace et al, civil disobedience has become the breaking of a random and often trivial law in order to assert a political viewpoint. In the case of Defend Our Coast, “civil disobedience” involved putting a wood stake into the lawn in front of the BC Provincial Legislature (technically illegal) in order to construct a symbolic “tanker” made of black fabric.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/standing/4b.jpg" rel="lightbox[standing]"><img src="https://cloudfront.crimethinc.com/images/standing/4a.jpg" width="500" height="375"/></a>
<em>Unist&#8217;ot&#8217;en allies holding ground at Defend Our Coast</em></p>
<p>Despite the problematic aspects of the rally, it was still a major event and a good opportunity to build awareness of the Unist’ot’en effort to defend their homelands from pipeline development. Ironically, inclusion of Unist’ot’en speakers was considered controversial due to the fact that their position encompasses an uncompromising rejection of all pipelines, which exposed the limited nature of the ENGO position focusing exclusively on Enbridge and Kinder Morgan. The reluctance of the NGO world to support grassroots indigenous resistance was indicated by their placing the Unist’ot’en at the very end of an overlong program of speakers. By contrast, Band Council chiefs, many known to be industry collaborators, spoke at the very beginning of the rally. </p>
<p>Nevertheless, the Unist’ot’en maintained a visible presence through the day with a large collection of banners. When the Unist&#8217;ot&#8217;en finally did get to speak, spokesperson Freda Huson shared her clan’s experience with some of the strongest words of the day: “Symbolic action will not save our land. Occupying and defending will save our land!”</p>
<p>After returning from the awareness efforts in the Lower Mainland and putting the finishing touches on the main cabin, it was time to settle in for winter. Snow was coming down by the bushel and nobody knew what to expect. It seemed possible that Pacific Trail Pipeline would try to take advantage of the harsh Wet&#8217;suwet&#8217;en winter conditions to push through at the time it would be most difficult to mobilize.</p>
<h3>Enter The Surveyors</h3>
<p>They came in November of 2012, almost a year after the Unist&#8217;ot&#8217;en had kicked them out. In a coincidence that borders on suspicious, surveyors for the Pacific Trails Pipeline snuck through with a truck when one of the Unist&#8217;ot&#8217;en leaders was departing camp for some solidarity work. Another truck was spotted doing work along the Forest Service Road in neighboring Git’dum’den territory. A watchful eye was cast at the bridge, and sure enough, later that evening, a truck was intercepted trying to enter the territory. They claimed to be searching for the other truck that had slipped by earlier that morning. These contractors were stopped and as they were being questioned, the other truck emerged trying to get out of the territory.</p>
<iframe width="500" height="281" src="//www.youtube-nocookie.com/embed/sXmFwj4YKsQ?rel=0" frameborder="0" allowfullscreen></iframe>
<p><br />Entering into Unist&#8217;ot&#8217;en land to do surveying work without the permission or consent of the Unist&#8217;ot&#8217;en is a serious offense by traditional law. For this violation, the contractors were issued an eagle feather, a traditional notice of trespass. By Unist&#8217;ot&#8217;en tradition, this warning is only issued once. Historically, a second violation was treated much more severely, even punishable by death. The next day the surveyors, who worked for a company called Can-Am Geomatics, were offered a chance to return to collect their equipment. They failed the FPIC protocol by refusing to share information with the Unist&#8217;ot&#8217;en. As a result they were sent back empty-handed. Later that day, a mission of camp members was sent out to confiscate the surveyor&#8217;s equipment. To this day, it remains safely kept by the Unist&#8217;ot&#8217;en should the company ever choose to negotiate its release.</p>
<p>Although the surveyors did not return to Unist&#8217;ot&#8217;en territory, they were once again discovered operating on Git’dum’den lands, for which they were also evicted, this time by a Git&#8217;dum&#8217;den Clan member, for the same reason of failing to obtain consent.</p>
<iframe width="500" height="375" src="//www.youtube-nocookie.com/embed/owHjAzqEa28?rel=0" frameborder="0" allowfullscreen></iframe>
<h3>Solidarity and Response</h3>
<p>After intercepting and evicting the pipeline surveyors, the Unist&#8217;ot&#8217;en called for their allies to rise up in support. The result was a day of action that saw solidarity rallies hosted in twenty cities across Turtle Island on November 27, 2012. The main purpose of the day was to deliver a message to the three companies that co-own Pacific Trail Pipelines as well as their investors. A letter was drafted and signed by Unist&#8217;ot&#8217;en spokesperson Freda Huson asserting the sovereignty of Unist&#8217;ot&#8217;en land and the denial of consent to the pipeline project. It explicitly stated that “any further unauthorized incursion into traditional Wet’suwet’en territory will be considered an act of colonialism, and an act of aggression against our sovereignty.” Although the Unist&#8217;ot&#8217;en had repeatedly informed PTP officials in meetings and via email that they were not welcome on the territory, the written letter was the first move in the direction of a strategy to target the investors as well as the companies themselves.</p>
<p>In so-called Canada, actions ranged across the entire country, stretching from St John&#8217;s, Newfoundland to Victoria, BC. Almost all the critical targets identified by the Unist&#8217;ot&#8217;en were visited by supporters over the course of that day. This included Apache&#8217;s Vancouver office and Calgary headquarters, all three offices of Encana institutional investor Jarislowsky Fraser Limited, and Royal Bank of Canada branches around the country. The national scope achieved by the action reflects the new reality that grassroots organizers lacking any sort of budget can nevertheless match institutional efforts by utilizing social networks and social media.</p>
<p>The day also saw support actions south of the border, including the offices of investors in New York and Texas. Activists from the <a href="http://www.tarsandsblockade.org/">Tar Sands Blockade</a> (TSB) helped to deliver the Unist&#8217;ot&#8217;en message directly to Apache&#8217;s headquarters in Houston, Texas. In the previous week, the Unist&#8217;ot&#8217;en had demonstrated their solidarity with TSB by creating a banner and issuing a statement in solidarity with their call for action. TSB replied at the Apache office and stated, “Real solidarity is about taking action. The Unist&#8217;ot&#8217;en Clan answered our call for solidarity actions last week and today we reciprocated.” The spirit of cooperation between the Tar Sands Blockade and the Unist&#8217;ot&#8217;en Camp builds unity between two critical fronts in the battle to contain pipeline expansion.</p>
<p>As it happened, Unist&#8217;ot&#8217;en spokesperson Freda Huson was in Trinidad to talk to activists who were working to oppose the development of <a href="http://ran.org/what-are-tar-sands">Tar Sands</a> in their own country. In an example of the type of solidarity that builds mutual aid, Unist&#8217;ot&#8217;en allies in Toronto visited the Trinidad embassy to deliver a message there, while activists in Trinidad visited the Canadian embassy to deliver the Unist&#8217;ot&#8217;en message.</p>
<p>In Montreal, protesters managed to get inside the JFL office to the utter bafflement of the staff, who claimed no knowledge of their investments disrespecting the rights of indigenous people. Within a month after the protest, Encana backed out of the project. PTP investor EOG also backed out a month after the day of actions, leaving ownership to Apache and new investor, Chevron Corp.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/standing/5b.jpg" rel="lightbox[standing]"><img src="https://cloudfront.crimethinc.com/images/standing/5a.jpg" width="500" height="332"/></a>
<em>Community members perform a war dance at a PTP meeting in Moricetown</em></p>
<h2>Cast Change and The Quiet Winter</h2>
<p>After the surveyor evictions and solidarity actions, things quieted down on the territory. There were no more signs of contractors, and no major response from the pipeline companies. This allowed the Unist&#8217;ot&#8217;en to focus on reviving traditional practices such as hunting and trapping. It has been years since they have lived full-time on their territory, and the re-establishment of the trap-lines is a source of pride for many in the community. The trap-lines are also strategic as they reinforce the Unist&#8217;ot&#8217;en claim to the land, demonstrating that they are utilizing it for traditional purposes. The resulting gifts from the forest were presented to the chiefs for the creation of traditional regalia.</p>
<p>Organizing and communications efforts continued to be a major task through the winter. Various articles were written and published by the Unist&#8217;ot&#8217;en and allies at the camp. The social media and web presence was re-structured and upgraded. Conferences were attended and further alliances made. The process of transitioning new allies into camp was initiated. And, of course, a lot of wood was chopped.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/standing/6b.jpg" rel="lightbox[standing]"><img src="https://cloudfront.crimethinc.com/images/standing/6a.jpg" width="500" height="375"/></a>
<em>Snowmobiles: the only way in or out of camp during the winter</em></p>
<p>With the emergence of Chevron as the new 50% owner of PTP, allies from <a href="http://risingtide.resist.ca/">Rising Tide Coast Salish</a> (based out of Vancouver) approached the Unist&#8217;ot&#8217;en about organizing a second day of action targeting Chevron and their investors. It was thought that since Chevron was new on the scene, they would benefit from a letter of warning from the Unist&#8217;ot&#8217;en as well. The day of action evolved into actions spread out over a couple days as investors were targeted on the Thursday prior to Easter Weekend, and rallies were held on Saturday, March 30. </p>
<p>Just outside of Vancouver, a mock circus occurred in front of Chevron&#8217;s Burnaby refinery. In Toronto, offices of Chevron investors were visited, with hilarious results, as office staff for Van Guard Group refused to accept the letter, and went so far as to push it back out from under their door as they locked it. The activists were told to stop trespassing, the irony of which was pointed out by a Rising Tide Toronto member who commented that was exactly what they were asking Van Guard to do: stop trespassing on Unist&#8217;ot&#8217;en land. A rally was also held in front of Chevron&#8217;s Canadian headquarters in Calgary, and allies from San Francisco visited their international headquarters in San Ramon with a giant banner.</p>
<p>As the snow thawed and spring approached, helicopter activity increased over the territory. Some of this was state surveillance—it is well known that the RCMP are keeping tabs on the camp—but some of it was industrial activity. In mid-April, a company was so bold as to use helicopters to drop water surveyors along the Wedzin Kwa and snatch them up before they could be intercepted by the Unist&#8217;ot&#8217;en Camp members who raced out to catch them. </p>
<p>So while things are quiet for now, they will likely not remain so for long.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/standing/7b.jpg" rel="lightbox[standing]"><img src="https://cloudfront.crimethinc.com/images/standing/7a.jpg" width="500" height="375"/></a>
<em>A helicopter taking off in a hurry to escape being chased down by Unist&#8217;ot&#8217;en camp members</em></p>
<h2>The Pipelines Targeting Unist&#8217;ot&#8217;en and Wet&#8217;suwe&#8217;ten Territories</h2>
<p>The following is a breakdown of all the current pipeline proposals affecting Unist&#8217;ot&#8217;en and Wet&#8217;suwet&#8217;en territories. As the fracking boom has glutted the domestic market with natural gas, prices have dropped. Therefore, companies are desperately looking to Asia for higher prices. In order to reach those markets, new pipeline infrastructure will be needed. Once Enbridge announced its intention to build the Northern Gateway pipeline, several other companies started making plans for pipelines that would follow the same right-of-way, thus creating the potential for a massive pipeline corridor. There currently exist ten potential pipeline projects, all in various stages of development. Some are simply speculative, while others are in active development.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/standing/8b.jpg" rel="lightbox[standing]"><img src="https://cloudfront.crimethinc.com/images/standing/8a.jpg" width="500" height="337"/></a>
<em>Enbridge, PTP, and Coastal GasLink proposed pipeline routes across Unist&#8217;ot&#8217;en territory</em></p>
<h3>Enbridge Northern Gateway</h3>
<p>Originally announced in 2005 and now undergoing a Joint Review Process, Enbridge&#8217;s Northern Gateway is a proposal for a dual-line 1,170 kilometer pipeline from Alberta to Kitimat, BC. The idea is to transport 525,000 barrels of Tar Sands bitumen west to the coast for export via supertankers to Asia. It would also bring highly corrosive toxic condensate east for use in diluting Tar Sands crude. A $5.5 billion project, the Northern Gateway would cross more than 800 streams and rivers, including sensitive salmon spawning areas in the upper Fraser, Skeena, and Kitimat watersheds.</p>
<p>Enbridge&#8217;s Northern Gateway is closely linked to the Canadian government&#8217;s plan to expand Tar Sands production. The extra capacity offered by the Northern Gateway alone would allow for 30% greater production over current levels. Other Tar Sands pipelines being proposed are the infamous Keystone XL and Enbridge&#8217;s proposed Line 9 reversal. Line 9 currently brings crude in to Sarnia from the United States, but Enbridge would like to use it to bring Tar Sands bitumen East. The <a href="http://www.tarsandsblockade.org/">Tar Sands</a> are the fastest growing source of greenhouse gas emissions in Canada and have had a devastating impact on the communities in the surrounding area.</p>
<p>Enbridge recently released plans for a modified route crossing the Wedzin Kwa (Morice River) a couple kilometers south of the existing Unist&#8217;ot&#8217;en Camp. This shows that industry is keeping close tabs on the camp and is well aware of Unist&#8217;ot&#8217;en resistance to the project. The new proposal changes nothing, as the new route still passes through territory under management of the Unist&#8217;ot&#8217;en. The Unist&#8217;ot&#8217;en were already planning to build pit houses in that area, so that more families could move back onto the territory.</p>
<h2>Pacific Trail Pipeline</h2>
<p>Announced shortly after Enbridge revealed its plans for the Northern Gateway, the Pacific Trail Pipeline (PTP) is a $1.23 billion project intended to link <a href="http://www.dangersoffracking.com/">fracking</a> operations in Northeastern BC with a proposed LNG processing plant in Kitimat (operating as Kitimat LNG). If completed, the pipeline would be able to transport 1 billion cubic feet of gas per day.</p>
<p>The PTP would follow almost exactly the same route as the Northern Gateway. Totaling 473 km in length, the pipeline would run from Summit Lake, just north of Prince George (where it would connect with the existing Spectra Energy pipeline), to Kitimat. Working under the radar of public awareness, Pacific Trails was the first and so far only pipeline project to obtain all its regulatory approvals. By the pipeline company&#8217;s original timeline, this project would already be operational. </p>
<p>Now owned by Apache and Chevron, the PTP is part of a trend towards integrated projects in which the parent company owns the reserves, the pipelines, and the processing facilities for whatever fossil fuel they are extracting. Often this ownership structure is disguised through the creation of various “limited partnerships.” In the case of this project, PTP is the corporate entity constructing the pipeline, and Kitimat LNG is the entity constructing the LNG processing plant and terminal. They are nothing more than empty shells to obscure the real players behind the scenes.</p>
<p>Although the general perception of natural gas pipelines is that they are safer than oil pipelines, when accidents do happen the results are explosive. Natural Gas pipelines don&#8217;t leak, they explode. An explosion at the Apache-operated LNG processing site on Various Island off of Western Australia <a href="http://www.watoday.com.au/wa-news/23m-varanus-explosion-compo-claim-settled-20091127-jw3p.html">took out 30% of that state&#8217;s domestic natural gas supply</a> for nearly six months. The investigation that followed found Apache&#8217;s safety culture to be “middle rank” and declared that there was enough <a href="http://www.slp.wa.gov.au/salesinfo/varanusinquiry.pdf">evidence</a> documenting the risk of corrosion that the accident “was not only foreseeable but to some extent foreseen.” </p>
<p>Of all the companies so far, Pacific Trail has been the most aggressive and blatant in their disregard of Unist&#8217;ot&#8217;en sovereignty. In 2011 they sent drillers (who were evicted), in 2012 they sent surveyors (who were also evicted), and now they are using helicopters to airlift water surveyors in and out of the territory. As PTP is the farthest along in its development, it will be the crucial test of the Unist&#8217;ot&#8217;en&#8217;s ability to protect their land from industrial development.</p>
<h2>Coastal GasLink</h2>
<p>A late arrival on the scene, Coastal GasLink is moving quickly through the regulatory process. A massive project whose initial capacity nearly doubles PTP, Coastal Gas Link has the potential to carry up to 5 billion cubic feet of fracked gas per day. Coastal Gas Link is owned by Shell Canada and a consortium of Asian energy companies. As with PTP, Coastal GasLink&#8217;s parent companies also own the proposed LNG plant linked with the project, known as LNG Canada.</p>
<p>The 650 km pipeline would cross 320 watercourses including the habitat of more than 100 at-risk species, such as white sturgeon, woodland caribou, and marbled murrelet. TransCanada documents outlining the pipeline project say it would cross four major drainages: the Peace, Fraser, Skeena and Kitimat rivers. More than 20 species of fish, including all five Pacific salmon species and steelhead, could be affected.
The LNG Canada project in Kitimat has been estimated at $12 billion, while the Coastal GasLink pipeline is estimated at $4 billion. The processing plant has already received a 25-year regulatory permit to export up to 24 million tons of LNG per year, and the environmental assessment for Coastal Gas link is currently underway.
Shell is already known in this region from the successful battle to prevent them from installing a coalbed methane project in the Sacred Headwaters of the Skeena, Nass, and Stikine rivers. Shell is also a major player in the Tar Sands and currently in conflict with the Athabasca Chipewyan First Nation over the expansion of its Jack Pine Mine in Alberta. In addition, the Unist&#8217;ot&#8217;en are well aware of the murder and devastation caused by Shell&#8217;s operations in the Niger Delta, where the equivalent of one Exxon Valdez oil spill has occurred each year for the past 50 years.</p>
<h2>Additional Pipelines</h2>
<p>Enbridge Northern Gateway, Pacific Trail, and Coastal GasLink represent the tip of the iceberg in terms of industry&#8217;s desire to expand pipeline infrastructure to fuel further expansion of Tar Sands and fracking operations in Canada. There are several more pipelines in various stages of development, many of which are waiting to see what happens with Pacific Trail.</p>
<p>In addition to the Kitimat plants, two massive LNG plants are being proposed for Prince Rupert. One is calling itself Pacific Northwest LNG and is co-owned by Petronas, Progress Energy, and Japex. Transcanada has been contracted to build the pipeline for an initial capacity of 2 billion cubic feet a day, but with the potential to expand that to 3.6 billion. The other unnamed project proposed by British Gas and Spectra is also huge, with a proposed pipeline capacity of almost 4.3 billion cubic feet a day. Although the current conceptual plans for the pipelines lie north of Wet&#8217;suwet&#8217;en territory, these projects are in the early stages of development and therefore any route is still possible. Even if the eventual paths of these pipelines fall outside the jurisdiction of the Wet&#8217;suwet&#8217;en, the Unist&#8217;ot&#8217;en intend to build relationships with the affected communities so that they can ensure that opposition in one area does not simply shift development into another. The ultimate goal is not just to stop pipelines from coming through Wet&#8217;suwet&#8217;en traditional territory, but to stop all of them.</p>
<p>There are also several pipeline projects hoping to pass through Wet&#8217;suwet&#8217;en Territory in hopes of reaching Asian markets. Some are older proposals such as Pembina Pipeline Expansion and Kinder Morgan Rearguard. Though somewhat dormant at the moment, the companies are actively monitoring how other projects fare against Wet’suwet’en resistance.</p>
<p>And the list of companies lining up with new projects continues to grow. At first dismissed as a fool&#8217;s dream, newspaper mogul David Black’s proposal for an oil refinery in Kitimat, called Kitimat Klean, has gained serious financial backing from European and Asian sources. Black&#8217;s project has stated that if Northern Gateway fails, they will construct their own pipeline to Kitimat. Two other companies investigating the possibility of further LNG plants on the Coast include Nexen—one of the biggest players in the Tar Sands and recently acquired by China National Offshore Oil Corporation—and Exxon—famous for the Valdez oil spill in Alaska and for funding climate change denial. Exxon recently acquired 545,000 hectares in the Montney shale field and 104,000 acres in the Duvernay shale in a 2.6 billion dollar deal adding to their existing holdings of 340,000 acres of shale gas properties in the Horn River basin. </p>
<p>Regardless of where these projects end up, they are a threat to the global eco-system. The Unist&#8217;ot&#8217;en and everyone who has a relationship to the Land understand that it is a holistic entity. When you take care of the land, it takes care of you. That is why the effort of the camp is not just to stop the pipelines, but to get back to the land itself. As part of this journey, the Unist&#8217;ot&#8217;en have come to see all the projects as linked, because they belong to the same colonial spirit that displaced them from their land in the first place. </p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/standing/9b.jpg" rel="lightbox[standing]"><img src="https://cloudfront.crimethinc.com/images/standing/9a.jpg" width="500" height="375"/></a>
<em>Defending the bridge after evicting PTP surveyors</em></p>
<h2>Responsibilities not Rights</h2>
<p>Responsibility differs from rights. The Unist&#8217;ot&#8217;en regard rights as the invention of statist bodies such as the United Nations and colonial entities such as Canada and the Band Office. They are premised on accepting the authority of the state-based system that creates them. By contrast, the Unist&#8217;ot&#8217;en regard responsibility as something that comes from the Creator through natural law. Natural law is the duty to learn about and follow the ways of Creation. In Wet&#8217;suwet&#8217;en culture, Bahni, or Warriors, have a responsibility to uphold Traditional and Natural law in the face of threat, infiltration, violence, and diminishment. </p>
<p>At Unist&#8217;ot&#8217;en Camp, traditional responsibilities are upheld as a means of reaffirming the sovereignty of Wet&#8217;suwet&#8217;en land. The Unist&#8217;ot&#8217;en knew that their territory could not be defended in boardrooms or by appealing to the colonial rulers of settler society. They had to go back to the source of their traditions and laws: the land. By occupying and defending their traditional territory, the Unist&#8217;ot&#8217;en are living and enacting traditional law. Their responsibility is guided by a power-with relationship to land, not a controlling power-over mechanism as utilized by colonial settler systems.</p>
<p>Traditional laws were asserted via protocols on these lands for thousands of years. The Wet’suwet’en presented themselves as such when traveling to neighboring peoples’ lands to conduct trade, build and maintain peace, assist allies in battle, and obtain resources. Knowledge bases were built over generations and expressed, at times, through a series of tactical and rigorous questions. Other times, planks were laid across canoes to provide a dance surface, and visiting nations would be required to dance their stories to demonstrate to the host nations that they were who they claimed to be—as the dance would have been known historically through trade relations. Identity was also proven through tattoo art on the chests of the male chiefs who often sat at the bow of the canoe.
Traditional Laws such as Free Prior Informed Consent are not lost or eroded. They have been dormant. The knowledge of conducting them is still active. They are not mere documents at the UN office waiting to be implemented by a state; they must be asserted by peoples who live off the land, connected to the spirit of the ancestors and upholding Natural Laws. Grassroots communities live and breathe these responsibilities, growing out of a particular place. </p>
<p>Industry and Government need to start learning about and respecting Traditional Law in their relation to Indigenous People. Traditionalists will not sit down at a board room or make decisions through colonial mechanisms. Recently, the Office of the Wet&#8217;suwet&#8217;en (OW) signed confidentiality and communications agreements with the Pacific Trails Pipeline company (co-owned by Chevron and Apache). By appearing to represent the traditional hereditary leadership, the OW has attempted to undermine the legitimacy of the Unist&#8217;ot&#8217;en hereditary chiefs who take direction directly from their people. The Unist&#8217;ot&#8217;en and Grassroots Wet&#8217;sewet&#8217;en have made their position clear: the hereditary chiefs are the final authority over traditional land. They will not participate in the tribal council&#8217;s attempts to re-ignite a failed treaty process and make deals with industry, nor will they make any decision without consulting the grassroots Indigenous people who are active on the land. </p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/standing/10b.jpg" rel="lightbox[standing]"><img src="https://cloudfront.crimethinc.com/images/standing/10a.jpg" width="500" height="750"/></a>
<em>&#8220;We are an impenetrable wall which is fortified by the same fighting spirits of our warrior ancestors who also refused to allow trespassers onto our sacred lands.&#8221; (photo by Adam Thomas)</em></p>
<h2>Building Relationships Out on the Land</h2>
<h3>The Unist&#8217;ot&#8217;en and Solidarity</h3>
<p>When the Unist&#8217;ot&#8217;en started out on their journey to oppose the pipelines, they knew they would be facing off with one of the most powerful industries in the world. These companies are responsible for large-scale destruction of the environment wherever they operate. They are implicated in the repression and murder of indigenous people around the world. They are primary agents in the creation of the greenhouse gas emissions driving the entire planet towards catastrophic climate change. Just as importantly, however, the Unist&#8217;ot&#8217;en knew that they were not alone in confronting them. </p>
<p>From the beginning, there has been a strong relationship between the Unist&#8217;ot&#8217;en and other indigenous communities fighting fossil fuel extraction. The Unist&#8217;ot&#8217;en sent representatives to the first Healing Walk in Fort McMurray organized by community activists from Fort Chipewyan. They have also visited and expressed their solidarity with people in the Peace River region living with the effects of fracking. The Unist&#8217;ot&#8217;en believe that stopping pipelines in their own territory means nothing unless it is an interim step toward stopping Tar Sands and fracking at their sources.</p>
<p>From the inception of the camp, local allies from Git&#8217;dum&#8217;den and Likhts’amisyu clans have been standing with the Unist&#8217;ot&#8217;en. That support is now spreading through the territory, and more chiefs from the different clans are speaking in favor of taking direct action to protect the land. A sad aspect of colonization is that the trauma inflicted by it has limited the capacity of the community to stand on the front-line. Many of the Elders are recovering from abuse suffered in residential schools; others are dealing with drug and alcohol issues, while many of the men who would be today&#8217;s warriors are caught up in colonized lifestyles.</p>
<p>Another sad effect of colonialism is that even among the Wet&#8217;suwet&#8217;en&#8217;s own people, some have become collaborators with their colonial overlords. A current example is a dispute between the people of Burns Lake and their Band Council. At issue is the fact that the elected chiefs have been making deals with the pipeline companies without consulting the community, and in direct opposition to the desire of the hereditary chiefs, whom the Wet&#8217;suwet&#8217;en people recognize as the rightful authority regarding their territories. When grassroots members of the band organized a protest, the Band Council called the RCMP to clear them out. </p>
<p>Based on this experience, the Unist&#8217;ot&#8217;en felt that if they were going to succeed in protecting their territory, they would have to work with settler allies as well as indigenous people.</p>
<h3>The Unist&#8217;ot&#8217;en and Front-line Allies</h3>
<p>The decision to take on settlers as allies was controversial. Some of the Unist&#8217;ot&#8217;en&#8217;s indigenous allies expressed discomfort at the presence of settlers at the action camps. This is understandable given the history of murder, theft, and repression that characterizes settler-indigenous relations. Past experiences with settlers from the mainstream environmental movement further complicated the picture. Although the Unist&#8217;ot&#8217;en listened to their allies who were critical of settler involvement at camp, the critics were not themselves able to commit to a full-time presence at the camp. Thus a pragmatic need remained for front-line allies from settler society.</p>
<p>A major and significant role of front-line allies at camp has been to help with the array of daily chores necessary to maintain a community in the bush. Felling trees and chopping wood, preparing food and cleaning dishes, collecting water, and making supply runs to town, settler allies have been an integral part of the camp. The extra presence at camp has also enabled Unist&#8217;ot&#8217;en leaders to mobilize for speaking events and key actions, as well as engage in important organizing work with the local community. </p>
<p>Allies have brought specific skills to the camp, too. Many have extensive experience in previous campaigns and direct actions, or web programming and media relations. These skills all helped in the organizing of the Unist&#8217;ot&#8217;en Days of Action.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/standing/11b.jpg" rel="lightbox[standing]"><img src="https://cloudfront.crimethinc.com/images/standing/11a.jpg" width="500" height="373"/></a>
<em>Nov 27, 2012: Unist&#8217;ot&#8217;en allies gather in front of Apache&#8217;s Vancouver office as part of Global Day of Action</em></p>
<h3>The Unist&#8217;ot&#8217;en and Anarchy</h3>
<p>The relationship between the Unist&#8217;ot&#8217;en and their settler allies extends beyond pragmatic necessity. As the traditionalists come to be a minority in their own society, this prepares the way for a natural affinity with resistance cultures that have long been the minority within settler society. As the attempt to work with ENGOs collapsed, the Unist&#8217;ot&#8217;en found that the same uncompromising stance driving away one set of allies drew in another.</p>
<p>From veteran tree-sitters and autonomous urban warriors to university students and independent journalists, a significant number of the new allies who rallied to the Unist&#8217;ot&#8217;en cause have been anarchists. Sometimes anarchist allies have clashed with other settler allies over the doctrine of non-violence. For example, controversy was stirred at the camp during a “hassle line” exercise, when an ally put forward a scenario for de-escalation which involved “a masked protester carrying a rock.” At this point, one of the core organizers of the camp stepped in to say that while the Unist&#8217;ot&#8217;en welcomed the support of those who wish to use exclusively peaceful tactics, they also embrace the way of the warrior.</p>
<p>Indeed, the Unist&#8217;ot&#8217;en have found that the non-indigenous allies whose political and philosophical views most closely align with their own have been anarchists. At the core of these shared principles is a rejection of the colonial nation state. This is an issue some allies struggle with. They want to support the Unist&#8217;ot&#8217;en from a shared desire to stop the pipelines, but their analysis does not extend to a complete rejection of the state. By contrast, anarchists are drawn to the Unist&#8217;ot&#8217;en cause for the very reason that their analysis includes a rejection of the state.</p>
<h3>The Benefit of Being out on the Land</h3>
<p>For all the good allies do for camp, the benefits of being out on the territory are nearly immeasurable. Even staying for just a few days can be a life-changing experience. As you gather water by the side of the river, listening to its steady whoosh and dipping your hand into its cool current, you cannot help but feel something stir within you. This is living water, the way it is supposed to be, clean and pure. From the knock-knock-knock of a woodpecker in the distance, the tracks of a Big or Little Brother along the riverbank, maybe even the sight of a little martin or ferret scurrying by, the forest around you is full of life. This too is as it should be. In the air itself, there is an energy as fresh as the tall pine which just exhaled it. Everything you could possibly need is here, if you have the knowledge and know what you are looking for. This is the way all of Turtle Island used to be, before invader culture landed here carrying colonization along with it.</p>
<p>These realizations strengthen the spirit and aid in decolonization, even as they induce grief for what has been lost. As more indigenous communities rise up to assert their sovereignty, decolonization must become more than a game of identity politics. It means figuring out how indigenous and settler allies can live and work side by side pursuing a shared vision. A lot has been lost, but a lot is left to protect as well. Being on the land, free from the distractions of the city, is an awakening moment, allowing one to rise above imprinted colonial identities to begin approaching life as a harmonized human being.</p>
<p>The relationships built at the Camp are the backbone of the solidarity network. There&#8217;s a difference between being ideologically aligned with a struggle and having a genuine relationship with the people behind it. It is this relationship of care that will draw people back to the Camp in a time of crisis. It is this relationship of care that drives the ongoing support efforts which, though less glamorous than high-profile actions, are nevertheless the lifeblood of the camp in its current transition toward a self-sustaining community.</p>
<h3>Building Bridges from Resistance to Community</h3>
<p>The long-term goal of the camp is not just to stop the pipelines, but to be back out living on their traditional land as Unist&#8217;ot&#8217;en. In one sense, the Unist&#8217;ot&#8217;en regard time spent defending the territory as time lost that could have been spent engaging in traditional activities. That is why, even with all the organizing work to be done, one of the main priorities for the Unist&#8217;ot&#8217;en over the winter was to reestablish their traplines.</p>
<p>During the spring 2013 camp, May 6 to 24, the Unist&#8217;ot&#8217;en took further steps to build infrastructure on the land in the form of traditional pithouses for Unist&#8217;ot&#8217;en families. To complement the pithouses, food-growing areas were established using permaculture methods. For the garden work, settler allies played a significant collaborative role. Some examples of new techniques the Unist&#8217;ot&#8217;en incorporated into their camp include rocket stoves, clay ovens, humanure compost, and no-till gardening.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/standing/12b.jpg" rel="lightbox[standing]"><img src="https://cloudfront.crimethinc.com/images/standing/12a.jpg" width="500" height="375"/></a>
<em>Traditional pithouse under construction as part of the unist&#8217;ot&#8217;en clan&#8217;s spring camp</em></p>
<p>Another example of creative collaboration between the Unist&#8217;ot&#8217;en and their allies is the Unist&#8217;ot&#8217;en Camp Urban Junk Technology project, which seeks to develop renewable energy from scrap materials. Some of the ideas being explored are constructing wind generators from microwave ovens, converting junk car alternators into permanent magnet alternators for micro-hydro, or using old washing machines to generate power with water. The process is open-ended and decentralized, so that allies can work together wherever they are and develop solutions with whatever they are able to scavenge, then share it with the rest of the group so the ideas can be applied at the camp.</p>
<h3>The Need for a Network of Front-line Allies</h3>
<p>As the Unist&#8217;ot&#8217;en Camp continues to entrench itself on the territory, it will need continued support from a network of dedicated allies from both settler and indigenous backgrounds. So far, industry has not made a strong attempt to push through, but that will not last indefinitely. Furthermore, the objectives of the Unist&#8217;ot&#8217;en Camp cannot be achieved in isolation, as pushing the pipelines north or south of their territory does nothing to stop the overall expansion of toxic industrial projects.</p>
<p>Hope for ultimate victory rests in indigenous communities joining together to re-assert authority over their traditional lands. The idea is powerful because it offers a direct solution to both the potential environmental impact of these projects and the theft of land embodied by colonialism. Such a movement would have a clear mandate and a basis for mutual support.</p>
<p>As a wider resistance emerges to reassert indigenous authority, it will be crucial for each community to define what relationship it is willing to develop with radical allies from settler society. That said, the experience of the Unist’ot’en Camp suggests that the most effective role settler allies can play is in channeling support from urban areas to the front lines. Indigenous people have the will and determination to take back their land and will fight if necessary to protect it. The scale of support needed exceeds the capacity of current solidarity networks. If the Unist&#8217;ot&#8217;en Camp becomes a model of resistance for other communities to follow, these struggles will need to be linked into a wider network of front-line resistance communities and urban-based supporters. </p>
<p>Coordinating a strategy to meet the needs of all communities will be a tremendous challenge. Bringing together these two elements into a network would require a shift in focus to expanding and reinforcing front-line struggle in general, rather than promoting one specific cause at the potential expense of another. At the moment, many solidarity activists in urban areas are already trying to support multiple communities, but without any coordination, their capacity for support is limited. A general network could help with coordination and focus on increasing overall capacity.</p>
<p>Elements of this potential network of front-line allies could include providing ongoing solidarity at the front-lines, material support through fundraising and donation drives, creating a rapid response mechanism for emergency mobilizations, raising general awareness, and coordinating solidarity actions. With the Canadian government currently pursuing billions of dollars in resource projects over the next decade, it will take an integrated network of resistance to combat it.</p>
<h3>Creating a Community Corridor</h3>
<p>As other communities take up the Unist&#8217;ot&#8217;en model of resistance and an integrated network evolves to support them, it will be possible to create a general strategy around united campaigns. Conversations between front-line community members and allies at the camp have produced the idea of the Community Corridor: a proposal to map out sites of resistance, sites of solidarity, and means of transferring resources between them. </p>
<p>Take the Unist&#8217;ot&#8217;en Camp as an example. If this proposed network of allies had a mobilization contingency plan in place and it was discovered that PTP was making an aggressive move against the camp, an emergency call for support could go out. If pipeline companies knew that the community they were threatening was connected to a dedicated network of support, they might deem the project too costly to pursue. The more comprehensive the network, the fewer places any company would be able to operate without encountering it.</p>
<p>As victories were achieved in one community, new tactics and tools could be disseminated through the network to other communities. Communities that win their objectives could then focus attention on supporting other groups. For example, if the Wet&#8217;suwe&#8217;ten were able to drive off all the pipeline proposals for Kitimat definitively, they could shift their efforts to supporting resistance against the remaining pipelines destined for Prince Rupert. Once the pipeline projects were shut down, more energy could be focused directly on the fracking fields and Tar Sands themselves.</p>
<h2>Conclusion</h2>
<p>The Unist&#8217;ot&#8217;en Camp is direct resistance to colonization through the assertion of responsibility to protect traditional territory that was never ceded to the Canadian State. The direct nature of the camp strips down the problems being faced to their essential elements. If the problem of colonization is the theft of indigenous land through displacement, then the solution is to reclaim it. If the problem with industrial civilization is that its projects are destroying the planet, then the solution is to stop them. If the problem is that a pipeline company wants to come through your traditional territory, the solution is to occupy it. Indigenous peoples such as the Unist&#8217;ot&#8217;en are in a unique position to do all these things at the same time.</p>
<p>If your objective is to stop the destruction of the environment, is the best way to do that through the colonial system that created the mess in the first place? Or by aligning yourself with the people who were wronged by it?</p>
<p>In the months to come, the Unist&#8217;ot&#8217;en will stand against the government, its police forces, and industry, all of which conspire to steal the wealth of indigenous land. The relationship between the Unist&#8217;ot&#8217;en and their allies will continue to grow. Through their collaboration, a model of resistance is emerging that is inspiring further communities to take action. </p>
<p>As companies madly rush to exploit all the remaining fossil fuels before the economy sinks under the waves of crisis produced by global warming, efforts like those of the Unist&#8217;ot&#8217;en are beacons for those who still believe in resistance. They hope that you will join them, or join others near you, in fighting for the same cause. It is not a matter of justice, but of survival—for all of us.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/standing/13b.jpg" rel="lightbox[standing]"><img src="https://cloudfront.crimethinc.com/images/standing/13a.jpg" width="500" height="375"/></a>
<em>The powerful Wedzin Kwah as seen from camp</em></p>
<h2>How to Get Involved</h2>
<p><strong>Email:</strong> unistotencamp@riseup.net<br />
<strong>Web:</strong> <a href="http://unistotencamp.com">unistotencamp.com</a><br />
<strong>Facebook:</strong> <a href="http://www.facebook.com/unistoten">facebook.com/unistoten</a><br />
<strong>Twitter:</strong> <a href="https://twitter.com/UnistotenCamp">https://twitter.com/UnistotenCamp</a><br />
<strong>YouTube:</strong> <a href="http://www.youtube.com/user/UnistotenCamp">http://www.youtube.com/user/UnistotenCamp</a></p>
<p><strong>Support the Camp:</strong> <a href="http://unistotencamp.wordpress.com/donate-to-camp/">http://unistotencamp.wordpress.com/donate-to-camp/</a></p>
<p><strong>Solidarity organizing list:</strong> <a href="https://lists.riseup.net/www/subrequest/unistotencampsolidarity">https://lists.riseup.net/www/subrequest/unistotencampsolidarity</a></p>