<p align="center"><a href="http://thecloud.crimethinc.com/images/terrain/bannerb.jpg" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/terrain/bannera.jpg" alt="Fighting in a New Terrain: What's Changed Since the 20th Century" width="500" height="335"></a></p>
<h3><em>Overture:</em> The More Things Change&hellip;</h3>
<p>Once, the basic building block of patriarchy was the nuclear family, and calling for its abolition was a radical demand. Now families are increasingly fragmented&mdash;yet has this fundamentally expanded women&rsquo;s power or children&rsquo;s autonomy?</p>
<p>Once, the mainstream media consisted of only a few television and radio channels. These have not only multiplied into infinity but are being supplanted by forms of media such as Facebook, Youtube, and Twitter. But has this done away with passive consumption? And how much more control over these formats do users really have, structurally speaking?</p>
<p>Once, movies represented the epitome of a society based on spectatorship; today, video games let us star in our own shoot-'em-up epics, and the video game industry does as much business as Hollywood. In an audience watching a movie, everyone is alone; the most you can do is boo if the storyline outrages you. In the new video games, on the other hand, you can interact with virtual versions of other players in real time. But is this greater freedom? Is it more togetherness?</p>
<p>Once, one could speak of a social and cultural mainstream, and subculture itself seemed subversive. Now &ldquo;diversity&rdquo; is at a premium for our rulers, and subculture is an essential motor of consumer society: the more identities, the more markets.</p>
<p>Once, people grew up in the same community as their parents and grandparents, and travel could be considered a destabilizing force interrupting static social and cultural configurations. Today life is characterized by constant movement as people struggle to keep up with the demands of the market; in place of repressive configurations, we have permanent transience, universal atomization.</p>
<p>Once, laborers stayed at one workplace for years or decades, developing the social ties and common reference points that made old-fashioned unions possible. Today, employment is increasingly temporary and precarious, as more and more workers shift from factories and unions to service industry and compulsory flexibility.</p>
<p>Once, wage labor was a distinct sphere of life, and it was easy to recognize and rebel against the ways our productive potential was exploited. Now every aspect of existence is becoming &ldquo;work,&rdquo; in the sense of activity that produces value in the capitalist economy: glancing at one&rsquo;s email account, one increases the capital of those who sell advertisements. In place of distinct specialized roles in the capitalist economy, we increasingly see flexible, collective production of capital, much of which goes unpaid.</p>
<p>Once,  the world was full of dictatorships in which power was clearly wielded from above and could be contested as such. Now these are giving way to democracies that seem to include more people in the political process, thus legitimizing the repressive powers of the state.</p>
<p>Once, the essential unit of state power was the nation, and nations competed among themselves to assert their individual interests. In the era of capitalist globalization, the interests of state power transcend national boundaries, and the dominant mode of conflict is not war but policing. This is occasionally employed against rogue nations, but continuously implemented against people.</p>
<p>Once, one could draw lines, however arbitrary, between the so-called First World and Third World. Today the First World and the Third World coexist in every metropolis, and white supremacy is administered in the United States by an African-American president.</p>
<p>&nbsp;</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/terrain/comic1b.gif" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/terrain/comic1a.gif" width="500" height="349"></a></p>
<p><br />
</p>
<h1>Fighting in the New Terrain</h1>
<h5>At the turn of the century, we could only<br />
imagine anarchism as a desertion from<br />
an all-powerful social order.</h5>
<p>Ten years ago, as starry-eyed young maniacs, we published <a href="http://www.crimethinc.com/books/days.html" target="_blank"><em>Days of War, Nights of Love</em></a>, unexpectedly one of the best-selling anarchist books of the following decade.<a class="footnote" href="javascript:void(0);" onclick="return overlib('At the time, we had no idea the book would reach anyone at all. A fierce argument took place shortly before it went to print over whether to print 1000 or 1500 copies, which concluded with one CrimethInc. agent declaring that he would pay for the extra 500 copies himself and give them away. Instead, we went through fourteen printings over the next ten years; as of this writing, well over 55,000 print copies are in circulation, not counting the various translations.', CAPTION, '[1]');" onmouseout="nd();">[1]</a> Although controversial at the time, in retrospect it was fairly representative of what many anarchists were calling for: immediacy, decentralization, do-it-yourself resistance to capitalism. We added some more provocative elements: anonymity, <a href="/texts/atoz/practical.php">plagiarism</a>, crime, hedonism, the refusal of work, <a href="/texts/days/deadhand.php">the delegitimization of history</a> in favor of myth, the idea that revolutionary struggle could be a romantic adventure.</p>
<p>Our approach was shaped by a specific historical context. The Soviet bloc had recently collapsed and the impending political, economic, and ecological crises had yet to come into view; capitalist triumphalism was at its peak. We focused on undermining middle class values because they seemed to define<em> everyone&rsquo;s</em> aspirations; we presented anarchist struggle as an individual project because it was difficult to imagine anything else. As the anti-globalization movement gathered momentum in the US and gave way to the anti-war movement, we came to conceptualize struggle more collectively, though still as originating from a personal decision to oppose a firmly rooted status quo.</p>
<p>Today, much of what we proclaimed has become pass&eacute;. As capitalism has shifted into a state of perpetual crisis and technological innovations have penetrated deeper into every aspect of life, instability, decentralization, and anonymity have come to characterize our society without bringing the world of our dreams any closer.</p>
<p>Radicals often think they are out in a wasteland, disconnected from society, when in fact they are its cutting edge&mdash;though not necessarily moving towards the goals they espouse. As we later argued in <a href="/rt"><em>Rolling Thunder</em> #5</a>, resistance is the motor of history: it drives social, political, and technological developments, forcing the prevailing order to innovate constantly in order to outflank or absorb opposition. Thus we can contribute to tremendous transformations without ever achieving our object.</p>
<p>This is not to credit radicals with the agency to determine world events, so much as to assert that we often find ourselves unconsciously on their cusp. Measured against the infinities of history, all agency is infinitesimal&mdash;but the very notion of political theory presumes that it is still possible to utilize this agency meaningfully.</p>
<p>When we strategize for individual campaigns, we have to take care not to make demands that can be defused by partial reforms, lest our oppressors neutralize us by simply granting them. Some examples of easily co-opted radical programs are so obvious that it is practically vulgar to point them out: bicycle fetishism, <a href="/texts/atoz/climate.php#2">&ldquo;sustainable&rdquo; technology</a>, &ldquo;buying local&rdquo; and other forms of ethical consumerism, volunteer work that mitigates the suffering caused by global capitalism without challenging its roots.</p>
<p>But this phenomenon can also occur on a structural level. We should look at the ways we have called for broad social change that could take place without shaking the foundations of capitalism and hierarchy&mdash;so that next time our efforts can <em>take us all the way.</em></p>
<h5>Today it must become a line of flight<br />
out of a collapsing world.<br />
</h5>
<h3>Not Working&mdash;Did It Work?</h3>
<p>The defining provocation of our early years was to take literally the Situationists&rsquo; dictum <em>NEVER WORK</em>. A few of us decided to test out on our own skin whether this was actually possible. This bit of bravado showed all the genius of untutored youth, and all the perils. Though countless <a href="http://www.zpub.com/notes/black-work.html" target="_blank">others</a> had trodden this road before, for us it was as if we were the first primates to be shot into space. In any case, we were <em>doing</em> something, taking the dream of revolution seriously as a project one might initiate in one&rsquo;s own life <em>immediately</em>, with&mdash;as we used to say&mdash;an aristocratic disdain for consequences.</p>
<p>It&rsquo;s tempting to brush this off as mere performance art. Yet we have to understand it as an early attempt to answer the question that still faces would-be revolutionaries in the US and Western Europe: <em>What could interrupt our obedience?</em> Contemporary <a href="/texts/recentfeatures/insurrection.php">insurrectionists</a> are attempting to ask this same question now, though the answers many of them offer are equally limited. By themselves, neither voluntary unemployment nor gratuitous vandalism seem to be capable of jerking society into a revolutionary situation.<a class="footnote" href="javascript:void(0);" onclick="return overlib('To be fair, the insurrectionist mantra of<em> attack</em> is more up to date than our boycott of wage labor. The latter presumed that the economy requires our participation; the former accepts that it does not, and focuses on interrupting it by other means.', CAPTION, '[2]');" onmouseout="nd();">[2]</a> Despite everything, we stand by our initial hunch that it will take a <em>new way of living</em> to bring about such a situation; it&rsquo;s not just a matter of putting in enough hours at the same old tasks. The essential fabric of our society&mdash;the curtain that stands between us and another world&mdash;is above all the <em>good behavior</em> of exploited and excluded alike.</p>
<p>Within a decade, history rendered our experiment obsolete, perversely granting our demand for an unemployable class. US unemployment rates, alleged to be at <a href="http://www.bls.gov/cps/prev_yrs.htm" target="_blank">4%</a> in the year 2000, <a href="http://www.bls.gov/opub/ils/pdf/opbils82.pdf" target="_blank">had climbed to 10%</a> by the end of 2009&mdash;only counting people known to be actively looking for work. The excess of consumer society once offered dropouts a certain margin of error; the economic crisis eroded this and gave a decidedly involuntary flavor to joblessness.</p>
<p>It turns out capitalism has no more use for us than we have for it. This doesn&rsquo;t just go for anarchist dropouts, but for millions of workers in the US. Despite the economic crisis, <a href="http://marketplace.publicradio.org/display/web/2010/07/28/pm-rise-in-profits-more-hiring-not-exactly/" target="_blank">major corporations are currently reporting enormous earnings</a>&mdash;but instead of using this income to hire more employees, they&rsquo;re investing in foreign markets, purchasing new technology to reduce their need for employees, and paying out dividends to stockholders. What&rsquo;s good for General Motors is not good for the country after all;<a class="footnote" href="javascript:void(0);" onclick="return overlib('This is even more sticking in light of the fact that General Motors is now predominantly owned by the US government.', CAPTION, '[3]');" onmouseout="nd();">[3]</a> the most profitable companies in the US right now are shifting both production and consumption to &ldquo;developing markets&rdquo; overseas.</p>
<p>In this context, dropout culture looks a bit like a voluntary <a href="http://en.wikipedia.org/wiki/Austerity" target="_blank">austerity</a> program; it&rsquo;s convenient for the wealthy if we reject consumer materialism, since there&rsquo;s not enough to go around anyway. In the late 20th century, when the majority of people identified with their jobs, refusing to pursue employment as self-realization expressed a rejection of capitalist values. Now erratic employment and identification with one&rsquo;s leisure activities rather than one&rsquo;s career path have been normalized as an economic position rather than a political one.</p>
<p>Capitalism is also incorporating our assertion that people should act according to their consciences instead of for a wage. In an economy full of opportunities to sell one&rsquo;s labor, it makes sense to emphasize the importance of other motivations for activity; in a precarious economy, being willing to work for free has different implications. The state increasingly relies on the same do-it-yourself ethic that once animated the punk underground to offset the deleterious effects of capitalism. It is cheaper to let environmentalists volunteer to clean up the <a href="http://www.fox10tv.com/dpp/news/gulf_oil_spill/wala-oil-spill-volunteer-opps-lr" target="_blank">BP oil spill</a> than to pay employees to do this, for example. The same goes for <a href="http://www.foodnotbombs.net/" target="_blank">Food Not Bombs</a> if it is treated as a charity program rather than a way of establishing subversive flows of resources and camaraderie.</p>
<p>Today the challenge is not to persuade people to refuse to sell their labor, but to demonstrate how a redundant class can survive and resist. Unemployment we have in abundance&mdash;we need to interrupt the processes that produce poverty.</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/terrain/comic2b.gif" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/terrain/comic2a.gif" width="500" height="257"></a></p>
<h3>New Technologies, Outmoded Strategies</h3>
<p>In the second half of the 20th century, radicals based themselves in subcultural enclaves from which to launch assaults on mainstream society. The call for confrontational unemployment presumed a context of existing countercultural spaces in which people could invest themselves in <em>something else.</em></p>
<p>The cultural landscape is different today; subculture itself seems to function differently. Thanks to new communications technology, it develops and spreads much faster, and is replaced just as quickly. Punk rock, for example, is no longer a secret society into which high school students are initiated by classmates&rsquo; mix tapes. It is still generated by the participants, but now as a consumer market mediated via impersonal venues such as message boards and downloading. It&rsquo;s no surprise if people are less personally invested in it: as easily as they discovered it, they can move on to something else. In a world composed of<em> information</em>, subculture no longer appears to be <em>outside</em> society, indicating a possible line of escape, but rather one of many zones within it, a mere matter of taste.</p>
<p>Meanwhile, the internet has transformed anonymity from the province of criminals and anarchists into a feature of everyday communication. Yet unexpectedly, it also fixes political identities and positions in place according to a new logic. The landscape of political discourse is mapped in advance by URLs; it&rsquo;s difficult to produce a mythology of collective power and transformation when every statement is already located in a known constellation. A poster on a wall could have been put up by anyone; it seems to indicate a general sentiment, even if it only represents one person&rsquo;s ideas. A statement on a website, on the other hand, appears in a world permanently segregated into ideological ghettos. The myth of CrimethInc. as a decentralized underground anyone could participate in inspired a great deal of activity until the topography of the internet slowly concentrated attention on a single webpage.</p>
<p>Thus the internet has simultaneously fulfilled and rendered obsolete the potential we saw in subculture and anonymity. One could say the same of our advocacy of plagiarism; a decade ago we thought we were taking an extreme position against authorship and intellectual property when in fact we were barely ahead of the curve. The weeks we spent combing libraries for images to reuse foreshadowed a world in which practically everyone does the same thing with Google Image Search for their blogs. Conventional notions of authorship are being superseded by new forms of production, such as <a href="http://en.wikipedia.org/wiki/Crowdsourcing" target="_blank">crowdsourcing</a>, that point to a possible future in which free volunteer labor will be a major part of the economy&mdash;as a <em>part</em> of capitalism rather than an opposition to it.</p>
<p><p align="center"><a href="http://thecloud.crimethinc.com/images/terrain/comic3b.gif" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/terrain/comic3a.gif" width="500" height="608"></a></p></p>
<p>Here we arrive at one of the most pernicious ways our wishes have been granted in form rather than content. Free distribution, once thought to demonstrate a radical alternative to capitalist models, is now taken for granted in a society in which the means of material production are still held hostage by capitalists.<a class="footnote" href="javascript:void(0);" onclick="return overlib('In the mid-1990s, the most radical do-it-yourself bands fantasized about being able to give away their records as a political statement; now every band practically <em>has to</em> give away their music just to get started. While it appears at first glance that music is being decommodified, in fact musicians are being compelled to provide free labor that reinforces consumer dependence on new commodities such as computers and smartphones. Benefit records used to be able to raise significant quantities of money for political prisoners and other causes outside the logic of the exchange economy; today this is much more difficult. Thus free distribution can serve to concentrate capital in the hands of capitalists, undercutting the resistance strategies of the previous generation.', CAPTION, '[4]');" onmouseout="nd();">[4]</a> Electronic formats lend themselves to free distribution of information; this forces those who produce material formats such as newspapers to give them away, too, or go out of business&mdash;to be replaced by bloggers happy to work for free. Meanwhile, food, housing, and other necessities&mdash;not to mention the hardware required to access electronic formats&mdash;are as expensive as ever. This situation offers a certain amount of access to the dispossessed while benefiting those who already control vast resources; it is perfect for an era of high unemployment in which it will be necessary to placate the jobless <em>and make use of them</em>. It implies a future in which a wealthy elite will use free labor from a vast body of <a href="http://en.wikipedia.org/wiki/Precarious_work" target="_blank">precarious</a> and unemployed workers to maintain its power and their dependence.</p>
<p>This is all the more gruesome in that this free labor will be absolutely voluntary, and will appear to benefit the general public rather than the elite.</p>
<h5>&nbsp;</h5>
<h5>  Perhaps the central contradiction of our age is that the new technologies and social forms horizontalize production and distribution of information, yet make us more dependent on corporate products.<br />
</h5>
<h3>Decentralizing Hierarchy: Participation as Subjugation</h3>
<p>At the close of the 1990s, anarchists championed participation, decentralization, and individual agency. Building on our experiences in the do-it-yourself underground, we helped popularize the <a href="http://en.wikipedia.org/wiki/Viral_Change" target="_blank">viral model</a>, in which a format developed in one context could be reproduced worldwide. Exemplified by programs like Food Not Bombs and tactics such as the Black Bloc, this helped spread a particular anti-authoritarian culture from New York to New Zealand.</p>
<p>At the time, we were responding both to the limitations of the previous century&rsquo;s political and technological models and to emerging opportunities to transcend them. This put us near the forefront of innovations that reshaped capitalist society. For example, <a href="http://en.wikipedia.org/wiki/TXTMob" target="_blank">TXTmob</a>, the SMS text messaging program developed by <a href="http://www.appliedautonomy.com/" target="_blank">the Institute for Applied Autonomy</a> for protests at <a href="/texts/atoz/demonstrating.php">the Democratic and Republican National Conventions</a>, <a href="http://www.140characters.com/2009/01/30/how-twitter-was-born/" target="_blank">served as a model</a> for <a href="http://en.wikipedia.org/wiki/Twitter" target="_blank">Twitter</a>. Similarly, one can interpret the networks of the international do-it-yourself underground, formalized in guidebooks like <em>Book Your Own Fucking Life</em>, as forerunners of Myspace and Facebook. Meanwhile, the viral model is now best known for <a href="http://en.wikipedia.org/wiki/Viral_marketing" target="_blank">viral marketing</a>.</p>
<p>So consumer culture has caught up to us, integrating our escape attempt into the maintenance of the spectacle we rejected and offering everyone else the opportunity to &ldquo;escape&rdquo; as well. Bored by unidirectional network television programming, the modern consumer can do her own programming, albeit still at a physical and emotional distance from her fellow viewers. Our longings for more agency and participation have been granted, but inside a framework still fundamentally determined by capitalism. The demand that everyone become a subject rather than an object has been realized: now we are the subjects administering our own alienation, fulfilling the Situationist dictum that the spectacle is not just the world of appearances but rather the social system in which human beings only interact as their prescribed roles.<a class="footnote" href="javascript:void(0);" onclick="return overlib('&ldquo;The spectacle is not a collection of images; it is a social relation between people that is mediated by images.&rdquo;<br />&ndash;Guy Debord,<em> Society of the Spectacle</em>', CAPTION, '[5]');" onmouseout="nd();">[5]</a></p>
<p>Even fascists are trying to get in on decentralization and autonomy. In Europe, <a href="http://en.wikipedia.org/wiki/Autonomous_nationalists" target="_blank">&ldquo;Autonomous Nationalists&rdquo;</a> have appropriated radical aesthetics and formats, utilizing anticapitalist rhetoric and black bloc tactics. This is not simply a matter of our enemies attempting to disguise themselves as us, though it certainly muddies the waters: it also indicates an <em>ideological split</em> in fascist circles as the younger generation attempts to update its organizational models for the 21st century. Fascists in the US and elsewhere are engaged in the same project under the paradoxical banner of <a href="http://www.publiceye.org/magazine/v23n4/rebranding_fascism.html" target="_blank">&ldquo;National Anarchism&rdquo;</a>; if they succeed in persuading the general public that anarchism is a form of fascism, our prospects will be bleak indeed.</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/terrain/photo1b.jpg" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/terrain/photo1a.jpg" width="500" height="334" style="margin-bottom: 2px"></a><em><br />
&ldquo;Autonomous Nationalists&rdquo; (Somebody please put these morons out of our misery!)</em><br />
</p>
<p>What does it mean if fascists, the foremost proponents of hierarchy, can employ the decentralized structures we pioneered? The <a href="/blog/2009/09/08/from-the-archives-critique-of-state-socialism/">20th century</a> taught us the consequences of using hierarchical means to pursue supposedly non-hierarchical ends. The 21st century may show us how supposedly non-hierarchical means can produce hierarchical ends.</p>
<p>Extrapolating from these developments and others, we might hypothesize that we are moving towards a situation in which the foundation of hierarchical society will not be permanent centralization of power, but the standardization of certain disempowering <em>forms</em> of socializing, decision-making, and values. These appear to spread spontaneously, though in fact they only appear desirable because of what is <em>absent</em> in the social context imposed on us.</p>
<p>But&mdash;decentralized hierarchies? This sounds like a Zen koan. Hierarchy is the concentration of power in the hands of a few. How can it be decentralized?</p>
<p>To make sense of this, let&rsquo;s go back to Foucault&rsquo;s conception of the <a href="http://cartome.org/foucault.htm" target="_blank">panopticon</a>. Jeremy Bentham designed the panopticon as a model to make prisons and workplaces more efficient; it is a circular building in which all the rooms open inward on a courtyard, so as to be viewed from a central observation tower. The inmates cannot see what goes on in the tower, but they know they may be under observation from it at any given moment, so they eventually internalize this surveillance and control. In a word, power <em>sees</em> without looking, while the observed look without seeing.</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/terrain/photo2b.jpg" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/terrain/photo2a.jpg" width="500" height="335" style="margin-bottom: 2px"></a><em><br />
Panopticon</em><br />
</p>
<p>In the panopticon, power is already based in the <em>periphery</em> rather than the center, in that control is chiefly maintained by the inmates themselves.<a class="footnote" href="javascript:void(0);" onclick="return overlib('The inmate of the panopticon &ldquo;assumes responsibility for the constraints of power; he makes them play spontaneously upon himself; he inscribes in himself the power relation in which he simultaneously plays both roles; he becomes the principle of his own subjection.&rdquo;<br />&ndash;Michel Foucault, <em>Discipline and Punish</em>', CAPTION, '[6]');" onmouseout="nd();">[6]</a> Workers compete to be capitalists rather than establishing common cause as a class; fascists enforce oppressive relationships autonomously, without state oversight. Domination is not imposed from above but is a function of <em>participation itself.</em></p>
<p>Simply to participate in society, we must accept the mediation of structures determined by forces outside our control. For example, our friendships increasingly pass through Facebook, cellular phones, and other technologies that map our activities and relationships for corporations as well as government intelligence; these formats also shape the content of the friendships themselves. The same goes for our economic activities: in place of simple poverty we have loans and credit ratings&mdash;we are not a class without property, but a class driven by debt. And once again, all this appears voluntary, or even as &ldquo;progress.&rdquo;</p>
<p>What does it look like to resist in this context? Everything seemed so much easier in 1917 when proletarians worldwide dreamed of storming the Winter Palace. Two generations later, the equivalent seemed to be taking over the headquarters of network television; this fantasy reappeared in a <a href="http://en.wikipedia.org/wiki/V_for_Vendetta_(film)" target="_blank">Hollywood action movie</a> as recently as 2005. Now, it&rsquo;s increasingly obvious that global capitalism has no center, no heart through which to drive a stake.</p>
<p>In fact, this development is a boon to anarchists, in that it closes the way to top-down forms of struggle. There are no shortcuts now, and no justifications for taking them&mdash;there will be no more &ldquo;provisional&rdquo; dictatorships. The authoritarian revolutions of the 20th century are behind us for good; if revolt is to break out, anarchist practices will have to spread.</p>
<p>Some have argued that in the absence of a center, when the aforementioned<em> virus</em> is much more dangerous than the frontal assault, the task is not so much to pick the correct target as to popularize a <em>new way of fighting</em>. If this has not yet occurred, maybe it is simply because anarchists have yet to develop an approach that strikes others as <em>practical</em>. When we demonstrate concrete solutions to the problems posed by the capitalist disaster, perhaps these will catch on.</p>
<p>But this is tricky. Such solutions have to resonate beyond any particular subculture in an era in which every innovation instantly generates and is contained by subculture. They must somehow refuse <em>and interrupt</em> the forms of participation essential to the maintenance of order, both the ones predicated on integration and the ones predicated on marginality. They have to provide for people&rsquo;s immediate needs while giving rise to insurgent desires leading <em>elsewhere</em>. And if we advance solutions that turn out not to address the root causes of our problems&mdash;as we did a decade ago&mdash;we will only <em>inoculate</em> the ruling order against this generation&rsquo;s resistance.</p>
<p>When it comes to contagious solutions, perhaps the <a href="/blog/2008/12/25/how-to-organize-an-insurrection/">Greek riots of 2008</a> during which all the banks were burned were less significant than the day-to-day practices in Greece of occupying buildings, <a href="http://www.youtube.com/watch?v=QoKyYKgaHZA" target="_blank">seizing and redistributing food</a>, and gathering publicly outside the logic of commerce. Or perhaps the riots were equally significant: not just as a material attack on the enemy but as a festival affirming a radically different way of being.<br />
</p>
<h3>Destabilization of Society: Double or Nothing</h3>
<p>In the 1990s, capitalism appeared eminently stable, if not unassailable. Anarchists fantasized about riots, catastrophes, and industrial collapse precisely because these seemed impossible&mdash;and because, in their absence, it appeared that they could only be a good thing.</p>
<p>All that changed starting in September 2001. A decade later, crises and catastrophes are all too familiar. The notion that the world is coming to an end is practically banal; who hasn&rsquo;t read a report about global warming and shrugged? The capitalist empire is obviously overextended and few still believe it is going to last forever. For now, however, it seems to be able to utilize these catastrophes to consolidate control, passing on the costs to the oppressed.<a class="footnote" href="javascript:void(0);" onclick="return overlib('Let us not forget that from 1945 to 1989 capitalism thrived by exploiting another ongoing catastrophe, the Cold War, in which a series of conflicts and crises threatened to end in nuclear Armageddon. Instability and the specter of the end of the world can be very useful to our rulers. We can imagine a future in which the repressive measures necessary to maintain industrial capitalism are justified on ecological grounds the same way that a generation ago the repressive measures  necessary to maintain the democracy of the market were justified as protecting freedom.', CAPTION, '[7]');" onmouseout="nd();">[7]</a></p>
<p>As globalization intensifies the <a href="http://finance.yahoo.com/tech-ticker/the-u.s.-middle-class-is-being-wiped-out-heres-the-stats-to-prove-it-520657.html?tickers=^DJI,^GSPC,SPY,MCD,WMT,XRT,DIA" target="_blank">distance between classes</a>, some of the disparities between nations seem to be leveling out. Social support structures in Europe and the US are being dismantled just as economic growth shifts to China and India; National Guardsmen who served in Iraq are being deployed in the US to maintain order during <a href="/blog/2009/09/30/state-repression-at-the-g20-protests/">summit protests</a> and natural disasters. This is consistent with the general trend away from static, spatialized hierarchies towards dynamic, decentralized means of maintaining inequalities. In this new context, 20th century notions about privilege and identity are increasingly simplistic.</p>
<p>Our enemies to the Right have already mobilized their reaction to the era of globalization and decentralization. We can see this from the Tea Party in the US to nationalist movements throughout Europe and religious fundamentalism worldwide. While Western Europe has agglomerated into the European Union, Eastern Europe has been Balkanized into dozens of nation-states teeming with fascists eager to capitalize on popular discontent. Religious fundamentalism is a comparatively recent phenomenon in the Middle East, having taken hold in the wake of failed secular &ldquo;national liberation&rdquo; movements as an exaggerated reaction to Western cultural imperialism. If we permit proponents of hierarchy to monopolize opposition to the prevailing order, anarchists will simply disappear from the stage of history.</p>
<p>Others are already disappearing from this stage. As the middle class erodes in Europe,<a class="footnote" href="javascript:void(0);" onclick="return overlib('Contrary to its mythology, the Left exists to defend the interests of the middle class, not the poor. The welfare programs of social democracy were established to appease the oppressed instead of granting them an equal say in society. Likewise, &ldquo;sustainable&rdquo; capitalism&mdash;tellingly, the latest cause to reinvigorate the Left&mdash;is more about sustaining capitalism than sustaining life on earth.', CAPTION, '[8]');" onmouseout="nd();">[8]</a> traditional Left parties are dying out with it, and far Right parties are taking all the ground they lose.</p>
<p>If the Left continues to recede into extinction, anarchism will be the only game left in town for radicals.<a class="footnote" href="javascript:void(0);" onclick="return overlib('Of course, if anarchists become more effective, we will probably see Leftist organizing revive, in part as a means of co-opting resistance.', CAPTION, '[9]');" onmouseout="nd();">[9]</a> This will open a space in which we can make our case to all who have lost faith in political parties. But are we prepared to fight it out with global capitalism on our own, without allies? Escalating conflict is a gamble: as soon as we attract the attention of the state, we have to play double or nothing, attempting to mobilize enough popular support to outflank the inevitable counterattack. Every <a href="http://www.crimethinc.com/texts/recentfeatures/toronto.php" target="_blank">riot</a> has to be followed by an even broader outreach campaign, not a retreat into the shadows&mdash;a tall order in the face of backlash and repression.</p>
<p>Perhaps it would be better if history were moving slowly enough that we had time to build up a massive popular movement. Unfortunately we may not have a choice in the matter. Ready or not, the instability we wished for is here; we will either change the world or perish with it.</p>
<p>So it is high time to dispense with strategies founded on the stasis of the status quo. At the same time, crisis keeps one locked in a perpetual present, reacting to constant stimuli rather than acting strategically. At our current capacity, we can do little to mitigate the effects of capitalist catastrophes. Our job is rather to set off <em>chain reactions of revolt</em>; we should evaluate everything we undertake in this light.</p>
<p>In this context, it is more important than ever not to see <em>ourselves</em> as the protagonists of insurrection. The currently existing social body of anarchists in the US is numerous enough to <em>catalyze</em> social upheavals, but not nearly numerous enough to carry them out. As a comrade from <a href="http://voidnetwork.blogspot.com/" target="_blank">Void Network</a> never tires of emphasizing, &ldquo;We don&rsquo;t make the insurrection. We do some organizing; <em>everyone</em> makes the insurrection.&rdquo;</p>
<p>This will demand a lot from each of us. Ten thousand anarchists willing to go to the same lengths as <a href="http://www.anarchist-studies.org/node/429" target="_blank">Enric Duran</a>, the patron saint of debt defaulters, could constitute a real force, seizing resources with which to establish alternative infrastructures and setting a public example of disobedience that could spread far and wide.<a class="footnote" href="javascript:void(0);" onclick="return overlib('Now that God is dead, perhaps we can disbelieve <em>debt</em> out of existence&mdash;or even <em>money</em>, if enough of us treat it as a fiction.', CAPTION, '[10]');" onmouseout="nd();">[10]</a> <em>That</em> would bring <a href="http://news.infoshop.org/article.php?story=20060610134717980" target="_blank">&ldquo;dropping out&rdquo;</a> up to date for the new era. It&rsquo;s terrifying to imagine going to such lengths&mdash;but in a collapsing world, terror waits ahead whether we choose it or not.</p>
<p>Everyone who has participated in a black bloc knows it&rsquo;s safest in the front. <em>Double or nothing.</em></p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/terrain/photo3b.gif" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/terrain/photo3a.gif" width="500" height="295" style="margin-bottom: 2px"></a><em><br />
Fight back&mdash;social peace is neither</em></p>
<p align="center"><br />
</p>
<h3>Conclusion: Forbidden Pleasures</h3>
<p>But enough about strategy. There was one demand in<em> Days of War, Nights of Love</em> that could not be realized in any form under capitalism: the idea that unmediated life could become intense and joyous. We expressed this in our conception of resistance as a romantic adventure capable of fulfilling all the desires produced but never consummated by consumer society. Despite all the tribulation and heartbreak of the past decade, this challenge still lingers like hope at the bottom of Pandora&rsquo;s box.</p>
<p>We still stand by this demand. We don&rsquo;t resist simply out of duty or habit or thirst for vengeance, but because we want to <em>live fully</em>, to make the most of our limitless potential. We are anarchist revolutionaries because it seems there is no way to find out what that means without at least a little fighting.</p>
<p>As many hardships as it may entail, our struggle is a pursuit of joy&mdash;to be more precise, it is a way of generating new forms of joy. If we lose sight of this, no one else will join us, nor should they.<em> Enjoying ourselves</em> is not simply something we must do to be strategic, to win recruits; it is an infallible indication of whether or not we have anything to offer.</p>
<p>As austerity becomes the watchword of our rulers, the pleasures available on the market will be increasingly ersatz. The turn to virtual reality is practically an admission that real life is not&mdash;cannot be&mdash;fulfilling. We should prove otherwise, discovering <em>forbidden pleasures</em> that point the way to another world.</p>
<p>Ironically, ten years ago this one sensible demand was the most controversial aspect of our program. Nothing makes people more defensive than the suggestion that they can and should enjoy themselves: this triggers all their shame at their failures to do so, all their resentment towards those they feel must be monopolizing pleasure, and a great deal of lingering Puritanism besides.</p>
<p>In<em> <a href="http://www.prickly-paradigm.com/paradigm14.pdf" target="_blank">Fragments of an Anarchist Anthropology</a></em><a href="http://www.prickly-paradigm.com/paradigm14.pdf" target="_blank"> [pdf]</a>, David Graeber speculates that</p>
<h6>if one wishes to inspire ethnic hatred, the easiest way to do so is to concentrate on the bizarre, perverse ways in which the other group is assumed to pursue pleasure. If one wishes to emphasize commonality, the easiest way is to point out that they also feel pain.</h6>
<p>This formula is tragically familiar to anyone who has witnessed radicals caricaturing each other. Declaring that you have experienced heavenly pleasure&mdash;especially in something that actually violates the regime of control, such as shoplifting or fighting police&mdash;is an invitation for others to heap scorn upon you. And perhaps this formula also explains why anarchists can come together when the state murders <a href="http://en.wikipedia.org/wiki/Brad_Will" target="_blank">Brad Will</a> or <a href="http://en.wikipedia.org/wiki/Alexandros_Grigoropoulos" target="_blank">Alexis Grigoropoulos</a> but cannot set aside our differences to fight equally fiercely<em> for the living.</em></p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/terrain/photo4b.jpg" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/terrain/photo4a.jpg" width="500" height="435"></a></p>
<p>Death mobilizes us, catalyzes us. The reminder of our own mortality liberates us, enabling us to act without fear&mdash;for nothing is more terrifying than the possibility that we <em>could</em> live out our dreams, that something is truly at stake in our lives. If only we knew that the world were ending, we would finally be able to risk everything&mdash;not just because we would have nothing to lose, but because <em>we would no longer have anything to win.</em></p>
<p>But if we want to be anarchists, we are going to have to embrace the possibility that our dreams <em>can</em> come true&mdash;and fight accordingly. We are going to have to choose life over death for once, pleasure over pain. We are going to have to <em>begin.</em></p>
<p>&nbsp;</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/terrain/photo5b.gif" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/terrain/photo5a.gif" width="500" height="622"></a></p>
<p align="right">&nbsp;</p>
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1] At the time, we had no idea the book would reach anyone at all. A fierce argument took place shortly before it went to print over whether to print 1000 or 1500 copies, which concluded with one CrimethInc. agent declaring that he would pay for the extra 500 copies himself and give them away. Instead, we went through fourteen printings over the next ten years; as of this writing, well over 55,000 print copies are in circulation, not counting the various translations.</p>
<p>[2] To be fair, the insurrectionist mantra of<em> attack</em> is more up to date than our boycott of wage labor. The latter presumed that the economy requires our participation; the former accepts that it does not, and focuses on interrupting it by other means.</p>
<p>[3] This is even more sticking in light of the fact that General Motors is now predominantly owned by the US government</p>
<p>[4] In the mid-1990s, the most radical do-it-yourself bands fantasized about being able to give away their records as a political statement; now every band practically <em>has to</em> give away their music just to get started. While it appears at first glance that music is being decommodified, in fact musicians are being compelled to provide free labor that reinforces consumer dependence on new commodities such as computers and smartphones. Benefit records used to be able to raise significant quantities of money for political prisoners and other causes outside the logic of the exchange economy; today this is much more difficult. Thus free distribution can serve to concentrate capital in the hands of capitalists, undercutting the resistance strategies of the previous generation.</p>
<p>[5] &ldquo;The spectacle is not a collection of images; it is a social relation between people that is mediated by images.&rdquo; –Guy Debord,<em> Society of the Spectacle</em></p>
<p>[6] The inmate of the panopticon &ldquo;assumes responsibility for the constraints of power; he makes them play spontaneously upon himself; he inscribes in himself the power relation in which he simultaneously plays both roles; he becomes the principle of his own subjection.&rdquo; –Michel Foucault, <em>Discipline and Punish</em></p>
<p>[7] Let us not forget that from 1945 to 1989 capitalism thrived by exploiting another ongoing catastrophe, the Cold War, in which a series of conflicts and crises threatened to end in nuclear Armageddon. Instability and the specter of the end of the world can be very useful to our rulers. We can imagine a future in which the repressive measures necessary to maintain industrial capitalism are justified on ecological grounds the same way that a generation ago the repressive measures  necessary to maintain the democracy of the market were justified as protecting freedom.</p>
<p>[8] Contrary to its mythology, the Left exists to defend the interests of the middle class, not the poor. The welfare programs of social democracy were established to appease the oppressed instead of granting them an equal say in society. Likewise, &ldquo;sustainable&rdquo; capitalism&mdash;tellingly, the latest cause to reinvigorate the Left&mdash;is more about sustaining capitalism than sustaining life on earth.</p>
<p>[9] Of course, if anarchists become more effective, we will probably see Leftist organizing revive, in part as a means of co-opting resistance.</p>
<p>[10] Now that God is dead, perhaps we can disbelieve <em>debt</em> out of existence&mdash;or even <em>money</em>, if enough of us treat it as a fiction.</p>
</div>