<h1 style="margin-bottom: 0px">Toronto G20: Eyewitness Report</h1>
<h3>Or, <a href="http://www.crimethinc.com/blog/2010/02/15/riot-2010/">Riot 2010</a> Part Deux</h3>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/toronto2/1b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/toronto2/1a.jpg" width="500" height="333"></a></p>
<p><a href="http://www.crimethinc.com/texts/recentfeatures/toronto.php" target="_blank">Our last update</a> offered an overview of what happened in Toronto during the <a href="http://www.youtube.com/watch?v=eqdzUEv_gdw&amp;feature=related" target="_blank">anarchist actions against the G20</a> June 25-27. We&rsquo;ve received the following blow-by-blow report from on the ground there, offering context and analysis from inside the <a href="http://www.youtube.com/watch?v=2kcrEL-HHtA&amp;feature=related" target="_blank">riots</a> that shook Canada&rsquo;s largest city. Anarchists have fully emerged in North America as a force to be reckoned with following the events in Toronto, and it is important to understand how this came about. The black bloc has become <a href="http://www.thestar.com/news/gta/torontog20summit/article/829559--the-violent-protesters-who-never-were" target="_blank">a household name</a> throughout the region, and we must use this exposure to our advantage by maintaining our visibility even in the face of repression. We must also look critically at the events of the weekend in order to make strategic advances toward our goal of completely dismantling the domination and hierarchy of the present world.  </p>
<h3>Lead-up</h3>
<p>The June G20 meeting was announced for Toronto in December of 2009. While anarchists were already preparing for the G8 in Huntsville, the announcement that a major summit would be held in the downtown core of Canada&rsquo;s largest city created a stir among anarchists, and generated significant momentum for counter-summit actions to take place in Toronto. To our knowledge, anarchists participated in three basic models of organizing against the G20. We will briefly outline these to offer context to those seeking to understand the successes and failures of the Toronto protests. </p>
<p> Some anarchists were involved in the <a href="http://g20.torontomobilize.org/" target="_blank">Toronto Community Mobilization Network (TCMN)</a>, which was not an anarchist group and did not organize actions but sought only to provide infrastructure and coordination for the convergence in Toronto. Many anarchists, especially those based in Toronto, chose to put their efforts into this group rather than organize along explicitly anarchist lines. <a href="http://guerrillaunderground.ning.com/profiles/blogs/callout-for-the-toronto-g20" target="_blank">Southern Ontario Anarchist Resistance (SOAR)</a> was born of the desire for an explicitly anarchist group to organize an action framework against the summit, creating a semi-public format that many anarchists and allies could plug into. They issued calls to action fairly early on and while they saw fierce divisions over tactics and strategy in the immediate lead-up to the G20, they maintained the public call for <a href="http://anarchistnews.org/?q=node/10935" target="_blank">three explicitly anarchist actions during the weekend</a>. Other anarchists organized informally through established networks of friends sharing affinity and agreements on tactics, and they made <a href="http://fireworksforprisons.wordpress.com/" target="_blank">a public call for a demonstration against prisons</a> on Sunday June 26, the last day of the G20 summit. Also significant is that many different groups in Montreal organized massive support for the convergence against the G20; this included <a href="http://www.clac2010.net/" target="_blank">a reforming of CLAC</a>, which had originally existed to oppose the Summit of the Americas in Quebec City in 2001.</p>
<p> There were other groups organizing against the G20, with which anarchists interacted in various ways. <a href="http://www.nooneisillegal.org/" target="_blank">No One Is Illegal</a>, a cross-Canada network working to end deportations and regularize non-status migrants, held a march and participated in much of the street action. The<a href="http://www.ocap.ca/" target="_blank"> Ontario Coalition Against Poverty (OCAP)</a> also organized for the summit, focusing on a march it called for Friday. The Canadian Labour Congress, a mainstream union coalition, organized the largest permitted march on Saturday. Various other protests occurred in the week leading up to the summit, including <a href="http://g20.torontomobilize.org/schedule" target="_blank">a queer action on Tuesday, a day of protest for climate justice on Wednesday, and a march in solidarity with Indigenous sovereignty on Thursday.</a></p>
<p> This is only a general overview of the different approaches anarchists took in Toronto, but perhaps it will help others understand how the Toronto actions compare to other convergences against global capitalism.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/toronto2/2b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/toronto2/2a.jpg" width="500" height="611"></a></p>
<h3>Friday June 25 : Quiet Before The Storm</h3>
<p>The day before the G20 leaders arrived, No One Is Illegal and OCAP organized an <a href="http://25june.wordpress.com/" target="_blank">unpermitted march</a>. </p>
<p> A number of anarchists had come prepared to march in full <a href="/texts/pastfeatures/blocs.php" >black bloc</a> but without the intention of starting conflict with the police or damaging property. The intention was to show solidarity with the struggles of migrants and other marginalized groups and to get a feel for acting collectively with those prepared to use black bloc tactics in the days to come. The bloc was initially small, around 30-40 people, but swelled to perhaps double that during the march.</p>
<p> The bloc was supported by many in the crowd; some supporters chased away journalists as people were changing clothes at the beginning. The bloc walked beside a contingent from No One Is Illegal<a class="footnote" href="javascript:void(0);" onclick="return overlib('No One Is Illegal is a broad network of people with different approaches to their respective struggles, in addition to the specific groups who maintain the websites and hold meetings.', CAPTION, '[1]');" onmouseout="nd();">[1]</a> for the duration of the march, a connection that would continue to bear fruit the following day. The other intention of this bloc was to communicate with others in the march about why anarchists choose to use black bloc tactics; while this was only partially realized, many good conversations took place. In any case, the bloc succeeded in establishing an anarchist presence at the G20 from the outset and making an initial show of strength. The march petered out around University Avenue and Dundas Street, as some went to set up a tent city in Allan Gardens and others rushed to the spokescouncil to discuss plans for the next day&rsquo;s action.<br />
</p>
<h3>Saturday Afternoon: Unexpected Anarchy</h3>
<p>The rally called for early Saturday afternoon by the Canadian Labour Congress (CLC) was expected to be the largest protest of the G20. SOAR had called for a &ldquo;Get Off The Fence&rdquo; action, vaguely promoted as a sort of break-away march that would attempt to get to the fence surrounding the site of the summit. Many plans for coordinating actions on Saturday were presented and scrapped during heated debate at the Friday night spokescouncil. The meeting ended with a consensus on having no plan, which was met with cheers and applause. The banners and flyers that were to promote and lead this break-away march never materialized, perhaps due <a href="http://toronto.mediacoop.ca/story/house-raids-warrants-and-arrests/3823" target="_blank">to early morning raids on the houses of organizers.</a></p>
<p> <iframe width="500" height="450" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps/ms?ie=UTF8&amp;hl=en&amp;oe=UTF8&amp;msa=0&amp;msid=103335406819895550235.000489f7628ab377781da&amp;source=embed&amp;ll=43.654553,-79.387422&amp;spn=0.013972,0.025706&amp;output=embed"></iframe><br /><a href="http://maps.google.com/maps/ms?ie=UTF8&amp;hl=en&amp;oe=UTF8&amp;msa=0&amp;msid=103335406819895550235.000489f7628ab377781da&amp;source=embed&amp;ll=43.654553,-79.387422&amp;spn=0.013972,0.025706" style="color:#0000FF;text-align:center" target="_blank">Corporate media map of events on Saturday, June 26</a>      </p>
<p>As anarchists arrived in Queen&rsquo;s Park and coalesced into a bloc of perhaps 100-150, they learned that a section of radical unionists and a contingent with No One Is Illegal flags also wished to break off from the main march and head south towards the fence. At this point things looked pretty bleak. Anarchists with street experience worried about the small size of the bloc and its relative disorganization&mdash;there were no scouts or comms teams to speak of and not many flags or banners. Meanwhile, up to 20,000 security personnel were arrayed against the protesters.</p>
<p> Many concerns had been voiced by anarchists in the months leading up to the G20 that a march on Saturday toward the fence was a &ldquo;suicide mission&rdquo; and completely unstrategic. In fact, many trustworthy comrades whose presence would have bolstered the bloc chose to not even come to this march for fear of being in jail and missing the anarchist-organized anti-prison demonstration the next day. It had also been suggested that the CLC would be antagonistic towards anarchists and would use union marshals to force them to the back of the march, thus making it impossible for anarchists to draw support from the crowd with which to break away in any direction.</p>
<p> As the march got moving, however, the bloc was able to enter roughly the middle of the larger group without conflict. The idea circulated that when other contingents who wanted to head south tried to do so, the bloc would join them and see what happened.</p>
<p> After marching down University Avenue and then west on Queen Street, <a href="http://nooneisillegal-montreal.blogspot.com/2010/06/g20-capitalism-is-attacked-in-streets.html" target="_blank">a section of the protest headed by No One Is Illegal flags</a> turned at John Street and dashed south. At this point, the black bloc was behind and somewhat isolated from this group, but did eventually move to support them. The surging crowd made some distance down John Street but was quickly stopped short by lines of riot cops. Of particular interest here is that while anarchists debated for hours about how to avoid putting regular protestors and those with uncertain citizenship status at risk with confrontational tactics, it was actually a group of mostly people of color, migrants, and their allies who were the first to charge the police. Perhaps in the future, anarchists can stop trying to &ldquo;look after&rdquo; those they believe have less privilege than themselves and instead establish stronger bonds of material solidarity with those clearly willing to fight the systems of state control.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/toronto2/3b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/toronto2/3a.jpg" width="500" height="333"></a></p>
<p>After it became clear that this line of riot cops was reinforced heavily, the crowd returned to Queen Street and continued to march west to Spadina Street. During this time the bloc merged with another group of anarchists who had been moving separately in the march, and its numbers swelled to around 200. The march came to Spadina Street and another charge south was attempted, this time with the No One Is Illegal contingent and sections of the black bloc rushing together. After another standoff, from which many returned with bleeding cuts from police batons, the crowd lingered at the corner of Queen and Spadina. It was from this intersection that the CLC labor march route turned north to march back to Queen&rsquo;s Park and the designated &ldquo;free speech&rdquo; protest pen. Many from the march had stayed behind to see if anything else was going to happen. </p>
<p> There was much debate about which direction to go&mdash;both within the black bloc and between the bloc and other groups. Some thought another charge should be made to the police line, while others thought the bloc should keep marching further west. At various points black bloc participants argued with others from No One Is Illegal about whether the point of the march was to try to go to the fence or to go wherever necessary in order to remain active on the streets of Toronto. At a critical moment many in the black bloc were chanting &ldquo;West on Queen! West on Queen!&rdquo; in an attempt to steer the demo away from the convention center hosting the G20 and towards a trendy shopping district. </p>
<p> Yet after hurried conversations and some heated debate, the decision was made to double back and proceed east along Queen Street. The bloc was convinced to head in the general direction of the convention center and the financial district, though many felt this would prove to be a tactical mistake. Supporters outside of the black bloc had information from scouts and runners that the way east was clear of riot police, and after initial hesitation the bloc listened to their advice. This was perhaps the defining decision, determining all that followed.</p>
<p> Since the rest of the permitted march had continued north past Spadina and Queen, the way remained open behind the crowd: surprisingly, the cops had not moved in to block the street off yet, likely concerned primarily with fortifying their positions on every street going south. The crowd that had lingered began to move in that direction, and the black bloc finally became somewhat cohesive and made a run to the front of this group. The bloc was then able to tighten up and it seemed the numbers had swelled again to 200-300, with anywhere from 400-800 other protestors also marching east. At this point the bloc came upon a single police cruiser, which was caught unaware in the middle of the bloc after it doubled back quickly to the east. There was a single officer inside, and the windows of the car were smashed and the hood was stamped on while the officer looked out in horror. This attack was met with cheers and screams of encouragement from the bloc and the rest of the crowd, boosting morale and letting the bloc know that militant tactics against police would be supported by the crowd.</p><p align="center"><a href="https://cloudfront.crimethinc.com/images/toronto2/4b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/toronto2/4a.jpg" width="500" height="337"></a></p>
<p>By this time the bloc had traveled many blocks from the rest of the labor march; anyone not comfortable with confrontational street tactics had had a reasonable amount of time to return north. The quick run to the east which was not met by any police resistance allowed for a good degree of distance between the black bloc and the &ldquo;green&rdquo; or family-friendly protest. </p>
<p> As the bloc continued down Queen Street, the windows of many stores and buildings were smashed, including the Nike store, Starbucks, and the Gap. The windows of a government building housing an immigration office were also destroyed, as was a CTV<a class="footnote" href="javascript:void(0);" onclick="return overlib('Canadian corporate news media.', CAPTION, '[2]');" onmouseout="nd();">[2]</a> van. The march was trying to move quickly at this point, surprised that the way east was clear of riot police.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/toronto2/5b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/toronto2/5a.jpg" width="500" height="281"></a></p>
<p>As the crowd arrived at Bay Street&mdash;the central artery of Toronto&rsquo;s financial district, which could be considered the Canadian equivalent of Wall Street&mdash;antagonisms flared again between the black bloc, the No One Is Illegal contingent, and others. The suggestion was again made to go south; many in the bloc were convinced that this would mean marching into an area where the police would be able to surround us easily. At one point a physical altercation almost erupted between individuals from two groups and it was looking ugly. Ultimately, as the crowd filled the intersection of Queen and Bay, the bloc listened to those who wanted to go south and moved in that direction. While the black bloc could be criticized for focusing on its own self-interest at first, the anarchists involved in this action eventually made efforts to hear out the desires of the other groups assembled. After tensions eased everyone marched south down Bay Street together.</p>
<p> The huge windows of bank headquarters were smashed with hammers and rocks, to the cheers of the crowd, and the bloc ran forward again overwhelming a cop car stationed at the intersection of Bay and King. The bloc surged past this car after smashing its windows and continued south for about half a block. The security perimeter was visible about a block and a half away, and those in front waited for the rest of the bloc to catch up and talked hurriedly of plans for some sort of attack on the fence. Unfortunately, no one had really expected to get this close to the fence and it didn&rsquo;t seem as though anything could be done to breech the perimeter with what was available on hand.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/toronto2/6b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/toronto2/6a.jpg" width="500" height="363"></a></p>
<p>As the bloc gathered many screamed to push further south. The sounds of breaking glass filled the air from every direction. Lines of riot cops ran in from both sides of Bay Street at Wellington Street and Front Street, and the bloc moved back towards King. The now iconic torching of the police car took place at some point during this back and forth, and it actually seemed to scare police off for a good few minutes. All the anarchists we subsequently spoke with about this situation reported that they had never before witnessed such a significant force of police acting as fearful as they did at this moment.</p>
<p> Of course, this didn&rsquo;t last long, and the bloc became boxed in on Bay Street as it attempted to retreat north. Somehow, at just the right moment, people charged the north-east corner of the intersection of Bay and King. Perhaps because one of their cruisers was burning behind them and hundreds of dangerous anarchists were hurtling towards them screaming, the line of riot cops actually retreated, stumbling backwards, and let the crowd through. The march was able to stay cohesive and continue east along King street without being split apart; to the best of our knowledge, not a single arrest had been made at that point.</p>
<p> The bloc moved quickly but did not seem to leave any section behind, and was able to make it east to Yonge Street where it turned north. We continued up Yonge with the cops behind us scrambling to catch up. The targeted destruction of property continued as many more banks and corporate chains were attacked. Other targets included a leather store (the vegan bloc was suspected), a jewelry shop (an unsuccessful attempt at looting), and an American Apparel; a Bell Mobility store and a Footlocker were looted, with cell phones and new running shoes flying into the crowd. The number of banks and corporate chains with their windows smashed at this point became <a href="http://watch.ctv.ca/news/latest/g20-aftermath/" target="_blank">too numerous to keep track of</a>. The devastation went so far that some later claimed that it was the largest example of property destruction ever carried out by anarchists in North America.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/toronto2/7b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/toronto2/7a.jpg" width="500" height="335"></a></p>
<p>As the march continued north up Yonge many people began to disperse, even though riot cops were still nowhere to be found. A significant number of people managed to march all the way back to Queen&rsquo;s Park and converge with the remnants of the labor rally. The energy and excitement bursting from anarchists who made their getaways was of course to be short-lived. The extreme retaliation of the security apparatus would soon be felt everywhere in the city.</p>
<h3>Saturday Night : Generalized Revolt &amp; Repression</h3>
<p>The mainstream news media reported at various times between four and eight police cruisers on fire around the Toronto downtown core. It seems that police cars were hastily abandoned as officers scrambled to other parts of the city, and the march left many smashed vehicles in its wake. These were then lit on fire either by lingering anarchists or random hooligans who saw an opportunity to destroy police cars with no officers in sight to enforce law and order.<a href="http://rabble.ca/blogs/bloggers/judes/2010/06/toronto-burning-or-it" target="_blank"> While conspiracy-theory leftists suggest</a> the that the police purposefully left cars for anarchists to attack in order to justify later repression, this theory has been <a href="http://toronto.mediacoop.ca/blog/oshipeya/3966" target="_blank">thoroughly debunked by others</a> whose sentiments we share.</p>
<p> The crowd remaining at Queen&rsquo;s Park merged with others milling around this area and eventually was forcibly dispersed and mass-arrested by police, provoking minor confrontation. During this time, as anarchists prepared for a late-night dance party called for by SOAR, the destruction and burning of one of the police cruisers was broadcast live on local news with a frantic anchor saying, &ldquo;I don&rsquo;t understand where the police are and how they could let this happen!&rdquo; Against the idea that the police permitted this to happen and always retain complete control in our society, we would argue that they were stretched thin across the city and were focused on dispersing and arresting any crowds they perceived to be linked to the black bloc. It took them a few more hours to clear Queen Street, which they eventually did.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/toronto2/8b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/toronto2/8a.jpg" width="500" height="337"></a></p>
<p>As the night progressed, many crowds spontaneously formed and were attacked viciously by police; snatch squads started to round up anyone who &ldquo;looked like an anarchist or a protester.&rdquo; The planned Reclaim the Streets dance party was cancelled due to its organizers all being detained. Unconfirmed reports were passed around of another group marching on the fence, and hundreds of arrests were made late into the night and early morning hours. At this point, coordination among anarchists severely broke down, and the lack of a comms team or anything resembling a unified twitter update feed meant that most were spread out and isolated throughout the city unsure of what was going on and unable to amass in significant numbers to accomplish more during this volatile situation. While at most summits in recent memory it was considered a victory to smash up shopping districts and then disappear, Toronto seemed to present a situation in which generalized street fighting and securing of areas of the city with barricades could have been possible if anarchists had come prepared and had been in better communication with each other and the crowds of supportive protestors and hooligans. The events of Saturday night show that sometimes anarchists&rsquo; efforts are only limited by the participants&rsquo; inability to imagine that they will succeed.</p>
<h3>Sunday : The Party&rsquo;s Over</h3>
<p>Anarchists had announced a noise demonstration outside a prison for the following Sunday at 5 pm. As mentioned above, some even chose not to attend the Saturday march because they wanted the Sunday demonstration to be the strongest show of anarchist activity during the G20, believing that it offered a more concrete opportunity to use the momentum of the G20 to make a material advance in the long-term struggle against prisons in southern Ontario.</p>
<p> Sunday morning, 70 arrests were made at a university campus providing mass housing to protestors mostly from Quebec. The police held a press conference claiming that the black bloc were terrorists and that they had caught most of the troublemakers. Seized alleged weapons were displayed for the media; police <a href="http://www.theglobeandmail.com/news/national/toronto/they-came-to-attack-our-city-blair/article1622761/" target="_blank">lied through their teeth, claiming to have found</a> a cross-bow and a chainsaw among the seized items, but later conceded that the cross-bow and other items had come from an innocent <a href="http://en.wikipedia.org/wiki/Larp" target="_blank">LARPer </a>coincidently rounded up that weekend.</p>
<p> By mid-afternoon, a jail solidarity march had been mass-arrested and tear gas blasts had been fired into the crowd. The police were now prepared to forcefully disperse any crowd with the most brutal measures needed, in order to send a message to the anarchists in Toronto that there would be no way to come together and carry out more militant actions.</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/toronto2/9b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/toronto2/9a.jpg" width="500" height="333"></a></p>
<p> Despite this climate, many still attempted to gather for the anarchist march against prisons at 5 pm. Many who tried were snatched up in the surrounding neighborhood, as squads of police in vans roamed the area. These cops jumped out and surrounded anyone with a backpack or side bag, detaining everyone who had black clothing with them or who attempted to flee. This succeeded in preventing anyone from amassing at the proposed meeting point, and it seemed to those scouting the neighborhood that at least a few affinity groups had been completely rounded up while most others saw one or two people from their groups detained. The police thus effectively canceled this demonstration. </p>
<p> At this point, people were being released from the detention centre and <a href="http://toronto.mediacoop.ca/story/conditions-g20-dentention-centre-are-illegal-immoral-and-dangerous/3918" target="_blank">giving horrifying accounts</a> of what took place within. A group of seemingly random passersby standing on the corner of Queen and Spadina were kettled in and held in the rain for hours before being carted off to the detention center. A<a href="http://www.thestar.com/news/gta/torontog20summit/article/830747--joint-lawsuit-planned-for-g20-arrestees" target="_blank"> reliable accoun</a>t places the total of arrests for the weekend at 1090. Anarchists and other supporters gathered outside the detention center on Monday to await the release of their friends and comrades, some of whom unfortunately remained in jail.<br />
</p>
<h3>Post-Convergence: Legal Fallout and Debriefing</h3>
<p>In the aftermath of the G20, it has come to light that police have been running an investigation for over a year to crack down on the anarchist movement in southern Ontario. Two informants have been discovered that succeeded in infiltrating anarchist communities. More specific and detailed information about these individuals will be appear online shortly. </p>
<p> Of those arrested at the G20, 263 were charged with criminal offences, and the severity of these charges is still being determined. A publication ban on information about those charged after the G20 has made it difficult to get a concrete sense of the situation thus far. At least 17 people from southern Ontario still being held on conspiracy-related charges, all of whom are longtime community organizers who will need massive support in the coming months.</p>
<p> These assaults on the anarchist milieu in Toronto have created a tense and difficult situation for those who live here. This repression has also offered an opportunity for people to forge closer ties as they come together to support those remaining in prison and facing more serious charges. It has yet to be seen what the outcome of this backlash will be and what toll it will eventually take on the anarchist community here, but those being targeted as organizers need local and international support, so stay tuned for more information.</p>
<p> It is important to keep perspective on this repression without missing the chance to analyze how anarchists pulled off such a massive attack in the face of a billion-dollar security budget and almost 20,000 security personnel. The march on Saturday was able to carry out so much property destruction because of the relationships between anarchists and others on the street, and because it acted at the same time as a massive protest that clogged up almost every artery in the downtown core.</p>
<p> That is not to say that anarchists must only act in coordination with other groups. <a href="http://www.crimethinc.com/blog/2010/02/15/riot-2010/" target="_blank">Earlier this year</a> in Vancouver, it was shown anarchists that can be effective when acting autonomously from other larger groups. Strategic wisdom can be gleamed, however, from the fact that every planned anarchist event after Saturday&rsquo;s large march failed to materialize.<a class="footnote" href="javascript:void(0);" onclick="return overlib('On the ground in Toronto there was considerable frustration that there was no public, well-promoted comms team or anything like the twitter feeds that had been used extensively in Pittsburgh and at the RNC. This caused those who had come to Toronto for the protests great difficulty communicating with or even finding each other.', CAPTION, '[3]');" onmouseout="nd();">[3]</a> When conflict escalates to a high level, the police can usually seize the upper hand once anarchists have separated, preventing them from reconverging unless they find some way of doing so with the element of surprise. The Saturday SOAR action may have succeeded only because it chose the correct time to act: not after the tone of the G20 had already been set, but starting off strong and putting pressure on the police when they already had their hands full. Also, in contrast to similar actions in the US in recent memory, the black bloc in Toronto also succeeded as a result of listening to its allies on the streets.</p>
<p> While informal organizing outside of the TCMN and SOAR did not have its desired effect, the ability of informants to penetrate these circles was also limited. There are fundamental drawbacks to organizing in a fashion that intentionally excludes the general public, but there are benefits as well. In the future perhaps anarchists who want to organize in this way can more carefully consider how to maximize their efforts no matter what happens at the initial outbreak of conflict, and be ready to capitalize on this conflict and push it further rather than waiting to carry out a predetermined plan. Having no plan at all can work better than sticking to a terrible plan, but the trick is to make our plans flexible enough to be effective no matter how the variables change.</p>
<p> After an entire financial district has been wrecked by the black bloc, after police cruisers have blazed mere blocks from the razor-wire security fence, after cell phones and running shoes have been stolen from the windows of corporate outlets, the time has come to ask ourselves: what next? We cannot be content with these small victories, however spectacular and inspiring they are. This weekend sent a clear message to our enemies that they cannot host a G20 summit without anarchists smashing the symbols of capitalism at every corner. Downtown Toronto came to a standstill Saturday, the subway system was shut down, and even the most na&iuml;ve liberals uttered the words &ldquo;police state.&rdquo;  We must begin to ask the difficult questions, <a href="http://anarchistnews.org/?q=node/11635" target="_blank">as some have begun</a>, about how these situations can escalate towards our goals of abolishing hierarchy and domination more generally. We must look to towards the next convergence of anarchist forces not as a theater where the same routine can be played out again, but where we can press onwards with the momentum created in Toronto to intensify these ruptures and open up a space to realize the anarchist desire for freedom in all of its possible forms.
</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/toronto2/10b.jpg" rel="lightbox[g20]"><img src="https://cloudfront.crimethinc.com/images/toronto2/10a.jpg" width="500" height="354"></a></p>
<h3>Further Reading: <br />
How Could Anarchists Outmaneuver the Cops?</h3>
<p><a href="http://toronto.mediacoop.ca/blog/oshipeya/4012" target="_blank">Debunking Myths and Conspiracy Theories about Anarchist Violence in Toronto</a></p>
<p><a href="http://www.youtube.com/watch?v=gLopuQUgsWM" target="_blank">Submedia Footage and Commentary</a></p>
<p>&nbsp;</p>
<div id="footnoteprint">
<br />
<br />
<p>[1] No One Is Illegal is a broad network of people with different approaches to their respective struggles, in addition to the specific groups who maintain the websites and hold meetings.</p>
<p>[2] Canadian corporate news media.</p>
<p>[3] On the ground in Toronto there was considerable frustration that there was no public, well-promoted comms team or anything like the twitter feeds that had been used extensively in Pittsburgh and at the RNC. This caused those who had come to Toronto for the protests great difficulty communicating with or even finding each other.</p>
</div>