<h1>G20:  Shut Doors = Broken Windows</h1>
<p align="center"><a href="http://thecloud.crimethinc.com/images/toronto/1b.jpg" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/toronto/1a.jpg" width="500" height="354"></a></p>
<h5 style="margin-bottom: 5px">&ldquo;Anarchists essentially outsmarted the extensive security plan by taking advantage of vulnerable parts of the city while police officers were focused on the large demonstration and the summit perimeter.&rdquo;</h5>
<h6 align="right">
&ndash;<a href="http://www.google.com/hostednews/ap/article/ALeqM5jDF_205MqoAsFPFodDEdtYmQBUJAD9GKISS80" target="_blank">AP News Report</a></h6>
<p>On June 26, 2010, thousands of anarchists and other protesters gathered outside the <a href="http://2010.mediacoop.ca/" target="_blank">G20 summit in Toronto</a>, facing off against <a href="http://www.google.com/hostednews/ap/article/ALeqM5jDF_205MqoAsFPFodDEdtYmQBUJAD9GKISS80" target="_blank">more than 19,000 security officials with a budget of nearly one billion dollars</a>. The <a href="http://www.youtube.com/watch?v=iDEfOJT6HZQ" target="_blank">riots</a> that followed have provoked outrage from public officials and commentators in the corporate media.
We salute the courage of those who put themselves at tremendous risk to shatter the illusion of social consensus and reveal the depth of outrage against the G20 leaders and the capitalist system they defend. If you put your freedom on the line in Toronto&mdash;<em>thank you</em>.</p>
<p>&nbsp;</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/toronto/2b.jpg" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/toronto/2a.jpg" width="500" height="333" style="margin-bottom: 2px"></a><em><br />
Apocalyptic vistas</em></p>
<h3>Shut Doors . . .</h3>
<p>As anarchists, we do not simply oppose specific policies of the G20&mdash;though the program <a href="http://vancouver.mediacoop.ca/story/g-20-nations-race-bottom-will-continue/3899" target="_blank">drafted at the Toronto summit</a> looks dire indeed&mdash;but also its basic structure. Be it G7, G8, G20, or G1000, any structure that empowers heads of state to decide the fates of millions is fundamentally exclusive and coercive. We oppose the G20 summits because we believe that only horizontal initiatives can solve the problems facing us today.</p>
<p>Financial crisis, ecological catastrophe, and repression of dissent are the necessary consequences of capitalist economics and hierarchical political systems that concentrate power in the hands of the most ruthless few. When all are forced to compete for resources and power at any cost rather than being free to develop ways of life based on sharing and peaceful coexistence, neither oil spills nor wars based on false pretexts should surprise us.</p>
<p> <p align="center"><a href="http://thecloud.crimethinc.com/images/toronto/4b.jpg" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/toronto/4a.jpg" width="500" height="333" style="margin-bottom: 2px"></a><em><br />
Too late for reformism</em></p>
<p>The kind of world our rulers are trying to build was reflected in the security apparatus set up to protect the summit from the populace that has to deal with its consequences. A part of downtown Toronto was fenced off, with <a href="http://www.thestar.com/news/gta/torontog20summit/article/828896--first-secret-law-arrestee-plans-charter-challenge?bn=1" target="_blank">&ldquo;secret laws&rdquo;</a> giving police additional powers in the area. The <a href="http://toronto.mediacoop.ca/story/house-raids-warrants-and-arrests/3823" target="_blank">preemptive raids</a> directed at protest organizers were not an anomaly&mdash;similar raids took place before the <a href="http://www.crimethinc.com/texts/atoz/rncdnc.php" >Republican National Convention</a> in 2008, for example. In making <a href="http://www.edmontonsun.com/news/g20/2010/06/28/14542396.html" target="_blank">over 900 arrests</a> of largely law-abiding citizens over the course of the weekend, security personnel were not overreacting but utilizing the criminal justice system for its implicit purpose: the containment of possible threats to the status quo.</p>
<p>If this is <a href="http://www.google.com/hostednews/ap/article/ALeqM5jDF_205MqoAsFPFodDEdtYmQBUJAD9GKISS80" target="_blank">the first time police have used tear gas in Toronto</a>, it only shows how tight their control has been over Toronto&rsquo;s poor and dispossessed until now. Likewise, the petulant reactions of politicians and corporate media reveal that, for once, protests went beyond anything they could co-opt into their own agendas.</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/toronto/3b.jpg" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/toronto/3a.jpg" width="500" height="752" style="margin-bottom: 2px" title="Photo by Foo, www.iwasaround.com"></a><em><br />
Proper use of corporate media</em>  
<p><br />
</p>
<h5 style="margin-bottom: 5px">&ldquo;Traditionally, crowds gathered to defend <br />
the community against outsiders who might <br />
otherwise impose their interests.&rdquo;</h5>
<h6 align="right">
&ndash;Al Sandine,<em> The Taming of the American Crowd</em></h6>
<h3 style="padding-top: 10px">. . . Broken Windows</h3>
<p>Although initial reports implied smaller numbers, Toronto police chief Bill Blair eventually acknowledged that <a href="http://www.google.com/hostednews/ap/article/ALeqM5jDF_205MqoAsFPFodDEdtYmQBUJAD9GKISS80" target="_blank">&ldquo;as many as a thousand people&rdquo;</a>
participated in militant actions on Saturday&mdash;what Premier Dalton McGuinty called <a href="http://www.theglobeandmail.com/news/world/g8-g20/toronto/police-demonstrators-gather-for-huge-g20-protest/article1619460/" target="_blank">&ldquo;mindless destruction and violence.&rdquo;</a></p>
<p>This kind of rhetoric is always the first response to a group stepping forcefully outside the permitted discourse; later, of course, there come <a href="http://www.crimethinc.com/blog/2008/09/19/fun-with-battle-in-seattle/" >movie adaptations</a> and overtures to &ldquo;be part of the process.&rdquo; It&rsquo;s important not to panic at moments like this when our enemies hope to scare us out of sticking to our guns. By standing proudly by militant action, we can help to legitimize structural opposition to capitalism; if we act ashamed or conciliatory, we enable our enemies to determine what counts as acceptable. Ironically, the only way to cease appearing &ldquo;extremist&rdquo; to the general public is to affirm the necessity of militant action until it is eventually normalized as a valid option.</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/toronto/5b.jpg" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/toronto/5a.jpg" width="500" height="346" style="margin-bottom: 2px"></a><em><br />
Doing your banking during the G20 summit</em></p>
<p>It is the politicians and police who should be ashamed. It is particularly cowardly for those who have never faced police violence to insult young people who are willing to stand up to a billion dollars worth of security personnel; it is particularly mindless for men whose privileges <em>just so happen</em> to rest on a complete acceptance of the values of the prevailing order to defame individuals who have the integrity to question those values. If anything qualifies as &ldquo;mindless destruction and violence,&rdquo; it is the unquestioning obedience of the police who attack noncombatants whenever ordered.</p>
<p>We are shocked by the hypocrisy of those who benefit from hundreds of years of colonization, genocide, and exploitation but prefer to focus on a few broken windows. We abhor the duplicity of police who can cite &ldquo;public safety&rdquo; as a pretext for <a href="http://toronto.mediacoop.ca/story/readers-stories-2-house-raid/3915" target="_blank">any outrage</a>, including gross violations of the laws they supposedly exist to enforce, while callously and indiscriminately attacking the public. We deplore the deceitfulness of media outlets that miss no opportunity to slander anarchists: for example, implying that <a href="http://en.wikipedia.org/wiki/Death_of_Ian_Tomlinson" target="_blank">the police murder of Ian Tomlinson at the 2009 G20 summit in London</a> was a result of the demonstrations there and not the senseless, unprovoked atrocity that it was. <p align="center"><a href="http://thecloud.crimethinc.com/images/toronto/6b.jpg" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/toronto/6a.jpg" width="500" height="763" style="margin-bottom: 2px"></a><em><br />
&ldquo;If you want a vision of the future, imagine a boot stamping on a human face&rdquo; &ndash;George Orwell</em></p></p>
<p>On the other hand, we are deeply inspired by our comrades in Toronto. It is astonishing that anarchists managed to achieve so much despite the forces arrayed against them. Although we fear a serious wave of repression is on the way, the events of June 26 did a lot to dispel the illusion that our rulers are invincible.</p>
<p>This is not to say we should stop at summit rioting. If it is possible for anarchists outnumbered twenty to one to trash a shopping district and set a few police cars on fire, think how much <em>more</em> possible&mdash;and more important&mdash;it is to fight on the terrain of our everyday lives. Anti-summit rioting is a powerful symbolic gesture of refusal, signifying a willingness to go <em>all the way</em>&mdash;but it will be in vain unless we actually succeed in passing beyond gestures into material transformation. Pundits and politicos should count themselves lucky when anarchists limit themselves to <em>symbolic</em> gestures, rather than setting about the serious business of overthrowing capitalism once and for all.</p> <p align="center"><a href="http://thecloud.crimethinc.com/images/toronto/7b.jpg" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/toronto/7a.jpg" width="500" height="587" style="margin-bottom: 2px" title="Photo by Foo, www.iwasaround.com"></a><em><br />
Break on through to the other side</em>  </p>
<p>As economic and ecological conditions continue to worsen, social conflict will also intensify; one day the challenge will not be to provoke riots but to accomplish anything besides them. If anarchists do not establish ourselves as the foremost opponents of the ruling order, fascists and fundamentalists surely will. In view of this, it may be important that we distinguish ourselves in summit protests. Yet in the long run we will win or lose according to whether we are able to utilize these opportunities to make our case to others, and to seize spaces and resources with which to demonstrate our alternative.</p>
<p>May sirens mingle in the air with the crisp scent of smoke. May projectiles rain down upon the spectacles of consumer culture. May we seize every chance to strike our oppressors and inspire our friends, neighbors, and coworkers to do the same. Now the question is how we can seize back our own communities and creative potential with the same fierceness we saw in Toronto.</p>
<p align="center"><a href="http://thecloud.crimethinc.com/images/explode/explode_b.gif" rel="lightbox[g20]"><img src="http://thecloud.crimethinc.com/images/explode/explode_a.gif" width="500" height="659" style="margin-bottom: 2px"></a><em><br />
<a href="http://thecloud.crimethinc.com/images/explode/explode.pdf"> Click here for PDF [29k]</a></em>  </p>
<h3>Further Reading</h3>
<p><a href="http://2010.mediacoop.ca/" target="_blank"><strong>G20 Alternative Media Center</strong></a></p>
<p><strong><a href="http://g20.torontomobilize.org/" target="_blank">Toronto Community Mobilization Network</a></strong></p>
<p><strong><a href="http://www.theglobeandmail.com/news/world/g8-g20/news/how-the-g20-clashes-unfolded/article1619983/" target="_blank">Corporate Media Map of Events</a></strong><a href="http://www.theglobeandmail.com/news/world/g8-g20/news/how-the-g20-clashes-unfolded/article1619983/" target="_blank"></a></p>
<p align="center" style="line-height: 15px; margin-bottom: 25px">&nbsp;</p>
<p>&nbsp;</p>