<h1>Under the Big Tent</h1>
<h5>Discussion Questions following the <br />
2007 CrimethInc. Convergence in Athens, Ohio</h5>
<a href="/texts/images/athens1big.jpg" rel="lightbox[athens]"><img src="/texts/images/athens1small.jpg" alt="Street Parade" width="500" height="225" /></a><p>Over three hundred people participated in this summer&rsquo;s CrimethInc. convergence, perhaps one and a half times the attendance of last year&rsquo;s. The two and a half days set aside for workshops were not enough to accommodate all the workshops participants hoped to present, even with four sessions a day and five running at a time. In a matter of days, an overgrown tangle of wilderness that had been abandoned for twenty-odd years became a fully-functioning campsite capable of hosting workshops, cooking, a full-time arts and crafts center, and a walk-in &rsquo;zine library and prisoner support station even in the midst of intense rainstorms. Everyone had access to camping space, three healthy meals a day, comprehensive health care, nonstop educational and entertainment activities, and great quantities of free literature without any registration fees or mandatory work. And&mdash;to offer a single inspiring anecdote&mdash;people who attended a workshop on breaking out of police holds successfully used this skill to escape arrest during the celebratory parade at the climax of the convergence.</p>
<p> Clearly, people are interested in the anarchist alternative; clearly, the CrimethInc. convergence has become a successful model of what one anarchist pundit unambitiously dubbed the Temporary Autonomous Zone.</p>
<p> When something reaches a certain level of success, it&rsquo;s no longer necessary or helpful to cheerlead for it. To get anywhere, we must begin from the premise that this summer&rsquo;s convergence was a failure, albeit a failure that could be improved upon. What could be more defeatist than to regard any anarchist project as a success with no potential for improvement, when the anarchist struggle has so far to go in North America?</p>
<p> In that spirit, we present the following discussion questions, focusing primarily on the most problematic and controversial aspects of the convergence. Those who wish to read more about the basic format of the convergence should consult<a href="http://crimethinc.com/blog/2006/08/11/we-live-to-tread-on-kings/" target="_blank"> the report from the one last summer</a>.</p>
<h3>Mass</h3>
<p>In <em>Crowds and Power</em>, Elias Canetti argues that the most essential characteristic of the crowd is that it always wants to grow. Immediately before the convergence, I attended a family reunion; as each carload of relatives arrived, people commented approvingly on how many more were coming and how big the family was. Anarchists and other evangelists rationalize their desire for mass as a matter of necessity in the struggle to change the world, but growth for its own sake offers no guarantee of improved effectiveness or increased freedom. At the first CrimethInc. convergence, in 2002, there were few enough people present that a majority of the participants got to know each other over the course of the week; in Athens, it was easy for anyone to remain anonymous in the mass. The greater the number of people in a space, the fewer new bonds tend to be forged.</p>
<p> At the same time, one can hardly say there are enough spaces in North America in which even modest numbers of people can come together to discuss and experiment with anarchist models. If people are turning out to the CrimethInc. convergence in greater and greater numbers, does this mean that the convergence must take on the role of being one of the primary nationwide anarchist gatherings?<a class="footnote" href="javascript:void(0);" onclick="return overlib('Arguably, as events such as this year&rsquo;s National Conference on Organized Resistance were somewhat less well organized and attended than before, the convergence is already playing this role de facto. Reports indicate that there were more people at the convergence than there were at the Earth First! rendezvous, or at the SDS national convention which ran contemporaneously. One might argue that CrimethInc., which began over a decade ago as a minority reaction to prevailing anarchist currents, has now become itself a central current. Perhaps this is an inevitable process&mdash;but should CrimethInc. projects be redirected to function better as part of the &ldquo;mainstream&rdquo; of anarchist activity? Or will this only crush out the last precious drops of the spontaneity that made them powerful in the first place?', CAPTION, '[1]');" onmouseout="nd();">[1]</a> How do we maintain an atmosphere of intimacy and informal participation while adjusting to fill this role? How do we create a space that suits everyone, when people are arriving with an increasingly diverse range of experiences, expectations, and needs?</p>
<p>On the other hand, what if it proves impossible for the convergence to serve its current function as attendance increases? If that is the case, should we discourage people from attending? Should we hold convergences in more remote locations, or convergences focused on specific topics, or multiple simultaneous regional convergences?</p>
<h3>Ethnicity and Age</h3>
<p>There were a lot of people at the convergence, coming from a modest array of subcultures, and among these people one could find a range of class backgrounds and relationships to gender. But the participants were overwhelmingly white. Last summer, anarchist people of color were actually disproportionately represented in organizational roles&mdash;but this doesn&rsquo;t seem to have resulted in more general attendance by people of color.</p>
<p> Is the CrimethInc. project more relevant to people coming from a predominantly white cultural context? If future convergences attract predominantly white folks, can they still contribute to momentum towards multi-ethnic resistance and solidarity&mdash;and if so, how? If future convergences attract predominantly white folks, can they be comfortable spaces for folks of color and fulfilling spaces for others? Should those involved in CrimethInc. projects defer to the analysis and approach of existing anti-oppression groups such as the <a href="http://www.collectiveliberation.org" target="_blank">Catalyst Project</a>, or develop their own?</p>
<p>The other significant absence of diversity was in age, and this was all the more glaring an issue in that many participants in earlier convergences were nowhere to be seen. Are young people really more prone to revolutionary commitments than older people? What does it take for a person to maintain involvement in radical projects across decades? What can others do to support and encourage this? How many older people are committed to revolutionary struggle but choose not to attend convergences? How can what happens at the convergence be connected to them and their efforts?</p>
<h3>Specialization</h3>
<p>The earliest CrimethInc. convergences were characterized by extremely informal infrastructures: at any time, anyone might find himself or herself digging a fire pit or performing for everyone. This summer, owing to the great numbers of people involved, the infrastructure was much more rigidly organized: one committee scheduled workshops, another maintained security shifts, yet another especially disciplined group organized the kitchen&mdash;which was far and away the most impressive mobile free food kitchen I&rsquo;d seen since the Miami FTAA protests of 2003. At earlier convergences, each person <a href="http://www.crimethinc.com/tools/downloads/posters.html#wash" target="_blank">washed his or her own dish</a>; at this one, a crack team headed up by one determined individual who never left the kitchen area washed everyone&rsquo;s dishes. There was a quartermaster keeping up with all the tools and supplies, a conflict mediation team, a person responsible for maintaining the free literature area. Looking around at the campsite, it was easy to imagine that we could reorganize society along anarchist lines&mdash;but perhaps not as easy for first-time participants to imagine that they could organize something similar themselves.<br />
The organizing model for this convergence was based on <em>bottomlining</em>&mdash;an individual or team volunteered to handle each task, swearing to take care of it come hell or high water. This model enables organizers with control issues to stop worrying about aspects of the organizing other than the ones they choose to take on&mdash;but does it also undermine the participatory environment that was so integral to the charm of the first CrimethInc. convergences?</p>
<p>One night, after a performance of a selection from Howard Zinn&rsquo;s <em>Emma</em>, a fire dancing troupe put on an impressive show. The play had been cast and practiced during the convergence, and had all the urgency and winsome awkwardness of a brand new project, but the fire dancers were clearly experienced in their field. Someone who had been involved in the organizing of the first convergence pointed out that, while everyone at that convergence took a turn in the spotlight, in this case we were basically a bunch of spectators watching a small team of professionals. How do we decentralize attention, or at least access and feelings of entitlement to attention? Would we benefit from more structure, or less?</p>
<p>At the debrief discussion at the end of the convergence, some organizers expressed concern about how much of the infrastructural work had been done by a small proportion of the participants. On the other hand, these &ldquo;insiders&rdquo; totally dominated this phase of the discussion! How can organizational work be more widely distributed, along with personal initiative itself?</p>
<h3>The Festival as Clich&eacute; . . . and as Nightmare</h3>
<p>To what extent do the people who are free to drop everything for a week to go camp out halfway across the country represent the demographics that actually read and make use of CrimethInc. material? Everyone who is invested in CrimethInc. projects knows others who are similarly invested but would never come to a convergence. To what extent does the current format of the convergence bring out people who like camping and workshops more than people who are committed to CrimethInc. projects? How can CrimethInc. agents who are unwilling or unable to attend the annual convergence undertake other experiments that fill similar roles?</p>
<p> Are there other possible formats for the convergence? If it took place in an urban setting, for example, would the ubiquity of capitalist consumer culture inevitably undermine the possibility of an atmosphere of autonomy?</p>
<p> As it has attracted more participants and solidified into a set format, the CrimethInc. convergence has taken on pronounced similarities to other events. Like the National Conference on Organized Resistance, it features two full days of workshops; like the Earth First! rendezvous, it involves camping out in a rustic setting; like any rock festival or youth culture event, the premise is that people of a minority persuasion who are used to being diffused throughout society spend a short, intense period of time together. Anything that falls into a recognizable category inevitably absorbs the inertia associated with existing examples of that category, and the convergence is no exception.</p>
<p>To gauge the dangers posed by that inertia, let&rsquo;s examine the subcultural festival as a phenomenon. These festivals are characterized by the artificial and temporary establishment of a community comprised of people of a single demographic. In some instances they are regarded&mdash;unconsciously or self-consciously&mdash;as models for an alternate society, an absurd pretension considering their homogeneity. It can be an intensely demoralizing experience for a bunch of isolated rebels who are used to defining themselves by their differences from others to spend a lot of time together. Without the others against whom they have contrasted themselves, they may feel their personal rebellions have lost their special meaning&mdash;and if the artificial society they comprise bears any similarities to the larger society they oppose, that undermines the dearly held faith that &ldquo;if only there were more of us&rdquo; things would be better.</p>
<p>One might argue that the prevalence of the subcultural festival at this juncture in history is simply a manifestation of the destruction of spatially-based long-term communities. When people arrive at the Rainbow Gathering, one of the longest-running and most widely attended subcultural gatherings, they are greeted with the words &ldquo;Welcome home&rdquo;&mdash;an ironic greeting, given that they are, spatially speaking, anywhere but home. Might one compare all these white people tromping from cities and suburbs into the last fragile forests in search of &ldquo;home&rdquo; to the white people who gentrify neighborhoods, or the white people who brought the scourge of Western civilization to North America as refugees from Europe? How are we to make any space into <em>home,</em> anyway, if we are perpetually gallivanting from one temporary community to another? Like any epidemic, alienation proliferates by means of its victims&rsquo; attempts to escape it. Are subcultural festivals, gatherings, and convergences simply another form of this destructive flight that wrecks exactly that which it seeks?</p>
<p>Granted that the preceding two paragraphs outline a vision of hell&mdash;how can the CrimethInc. convergence resist the tendency for any event or social group to revert to default setting as soon as it becomes a known quantity? How can we overcome the inertia brought to the convergence by participants familiar with and inured to the limitations of other such gatherings? What role, if any, could it serve in building longer term connections and investments? Do we have any right staging such events in feral countryside, or would it be more responsible to hold convergences in the spaces we already inhabit on a daily basis?</p>
<h3>Subculture</h3>
<p>I&rsquo;ve never been to a Rainbow Gathering. My only context for the Rainbow phenomenon comes from my experience hitchhiking&mdash;Jesus sometimes sends his followers to give me rides, but when it comes to looking after hitchhikers the Rainbow Gathering seems to be a far more powerful and attentive patron saint. Countless drivers have referred to the Rainbow Gathering upon picking me up; as far as I can tell, it seems to be a space that promotes mutual aid and sharing, and as far as that goes I&rsquo;m all for it.</p>
<p>But I have to say I was surprised when people started showing up at CrimethInc. convergences for whom the Rainbow Gathering was their closest point of reference. As I understand it, the Rainbow Gathering is more associated with pacifism, New Age spirituality, and drug use than with the all-out war on capitalism and hierarchy called for in most CrimethInc. literature.</p>
<p>Are there more common threads than I realized connecting CrimethInc. and the whole Rainbow thing? Or are these people showing up at the convergence because it seems to have a similar format to the Rainbow Gathering? If the CrimethInc. convergence were to become just another stop on the Rainbow circuit, would that be a positive thing&mdash;exposing more people to revolutionary anarchism&mdash;or would it just dilute the atmosphere? Are there disturbances in the Rainbow ecosystem that are driving people from those circles to our convergence?</p>
<p>According to one participant in the convergence, Earth First! has already been through this same experience with their yearly rendezvous, with the result that their rendezvous is now always scheduled to coincide with the Rainbow National Gathering. That doesn&rsquo;t seem promising. Does it make a difference that the convergence is a sober space, while the rendezvous is similar to the Rainbow Gathering in that it often hosts a lot of substance use?</p>
<p>But this specific line of questioning indicates a broader horizon of questions. As a broader range of people get involved in anarchist spaces, they will inevitably bring with them their own subcultural activities and reference points&mdash;whether those be drum circles, moshing, or bowling. Is it mere bigotry that punk subcultural norms go unquestioned, for example, regardless of the political implications of those norms, on account of punk having long been associated with anarchism&mdash;while others are regarded with suspicion?</p>
<h3>Sobriety and Gift Economics</h3>
<p>If anything decisively distinguishes the CrimethInc. convergence from the Earth First! rendezvous and the Rainbow Gathering alike, it is that it is an explicitly sober space. In a culture that promotes intoxication among radicals as well as everyone else, this is an achievement, though at every convergence the same discussions have to take place all over again to maintain this. Most inspiring of all were the participants who acknowledged having left the site of last year&rsquo;s convergence to drink, but made a point this year of emphasizing the value of the convergence being a sober space to others who wished to drink.</p>
<p>After the unpermitted march at the end of the convergence, the police used false positives from drug-sniffing dogs to justify searching people&rsquo;s vehicles. When it came out that the pigs found no illegal substances in those searches, somebody shouted out &ldquo;The policy works!&rdquo; Why is sobriety not more widely practiced as an aspect of revolutionary strategy? How do we create sober environments in which no one feels uncomfortable about or judged for their personal relation to substance use? If CrimethInc. is not itself a movement, but rather a subversion of movements, would organizing a sober Rainbow Gathering itself qualify as subversive activity?</p>
<p>Likewise, if anything distinguishes the CrimethInc. convergence from the various anarchist book fairs, the National Conference on Organized Resistance, and events like the US Social Forum, it is that there is no registration fee and no buying or selling. It is a powerful thing to demonstrate that we can provide for the needs of hundreds of people across several days by means of volunteer labor and individual donations. Besides intoxication and exchange economics, are there are other aspects of contemporary society we might try doing without?</p>
<h3>Relating to Other Radical Organizations</h3>
<p>This year&rsquo;s convergence took place at the same time as the national convention of the new Students for a Democratic Society and the Feral Visions gathering. The latter was on the West coast, but many committed anarchists had to choose between attending the convergence and the SDS convention, which took place in nearby Detroit. The dates of both events were announced shortly after we announced the date of this year&rsquo;s convergence&mdash;to our great frustration, as we had already spent weeks contacting organizers around the country, including some from SDS, inquiring about their schedules for the summer. It&rsquo;s possible that, had the two events not overlapped, more serious student organizers would have been in Athens.</p>
<p>A statement was read at the SDS convention from participants in the CrimethInc. convergence, encouraging more conscientious coordination between the two groups. It reportedly met a warm reception; in addition, a collection of hundreds of dollars was taken up at the convention when it was reported that police had made arrests at the parade concluding the convergence.</p>
<p>How can CrimethInc. and more rigidly structured groups like SDS work together in the future? What would it look like to collaborate with such groups to organize a convergence that brought together participants from several different strains of radical thought and organizing? Could that be a worthwhile experiment?</p>
<h3>Prisoner Support</h3>
<p>Last summer there was a prisoner support table offering resources about current political prisoners and defendants and materials for writing letters to them; some dozens of letters were written and mailed off. This summer&rsquo;s convergence featured a similar prisoner support station, but dramatically fewer letters were written. Does this reflect simple ergonomic shortcomings on the part of this year&rsquo;s support station&mdash;the absence of a table and chairs for writing, for example&mdash;or a more ominous deprioritization of prisoner support on the part of participants? </p>
<h3>Workshops</h3>
<p><a href="http://www.infoshop.org/inews/article.php?story=2007crimethinc-conv-ohio&amp;query=crimethinc.%2Bconvergence" target="_blank">Approximately fifty workshops, discussions, and presentations</a>  took place in the course of this year&rsquo;s convergence, not including caucuses and plant walks. One of the hallmarks of the CrimethInc. convergence model is that everyone who attends is encouraged to present a workshop, on the grounds that people learn more from presenting workshops than they possibly could from watching others&rsquo; workshops.</p>
<p>Perhaps not surprisingly, many of the workshops were not as interactive as they could have been&mdash;there was a lot of one person talking at length. It needs to be said that a workshop presenter is responsible for giving those who attend a workshop the most entertaining, engaging experience possible: if you choose to speak at people for an hour, it had better be a powerful performance! There was some talk afterwards of setting higher standards for the workshops. How can this be accomplished without discouraging inexperienced presenters from offering workshops? And how can we further challenge the standard, often boring format of workshops, which the convergence has inherited unquestioned from more orthodox activist conferences?</p>
<p>By far the most controversial aspect of this year&rsquo;s convergence was the workshop entitled &ldquo;2012.&rdquo; Presumably, this workshop was scheduled with the expectation that it was not simply an introduction to wingnut millenarianism, but it proved to be exactly that. Not only that, but due to its taking place in the big army tent during the last block of workshops, it ran on for several hours through dinner and into the evening, becoming a clearinghouse for wingnut ideas of all stripes.</p>
<p>The tent was packed for the workshop, though it later came out that many people had circulated in and out of it in the course of its duration, most more out of curiosity than credence. The unfortunate effect, however, was that the spectacle of a packed house listening to cosmic conspiracy theory at a supposedly clearheaded radical convergence demoralized people. The effect was similar to what might have happened if the <a href="http://en.wikipedia.org/wiki/The_Jerry_Springer_Show" target="_blank">Jerry Springer show</a>  was playing on the campsite with a crowd gathered around it: whether or not they approved or believed in it, their attention alone legitimized it and seemed to reflect on the convergence itself. If we would not have had television on the campsite, if we would not have invited the Church of Scientology to seek converts, why was there space for wingnut millenarians? Should there be a policy delineating what kinds of workshops are encouraged and discouraged? What about suggested &ldquo;tracks,&rdquo; directed themes for workshops and discussions? Or is that too controlling?</p>
<p>But the more important question is&mdash;why did the 2012 workshop attract so much attention in the first place? Was it the result of having a wider range of people at the convergence this year, that some of them are actually prone to believing such nonsense? Are some anarchists in fact eager to believe the world is going to end soon (or reach peak oil or a &ldquo;point of singularity&rdquo; or whatever) so they won&rsquo;t have to figure out how to liberate themselves? Was it simply the Jerry Springer effect&mdash;people can&rsquo;t help but flock to something ridiculous, even if there are more meaningful options close at hand? The schedule was packed all day every day with demanding activities&mdash;did people need something light to break up all that seriousness? Were the workshop presenters simply more compelling speakers than other workshop presenters? Did the workshop fill a role of being whimsical, entertaining, or romantic in a way that no other workshop did? Should we have been more conscientious about making sure something worthwhile would fill that role?</p>
<h3>Making Concrete Plans for the Future</h3>
<p>There were several efforts to make concrete plans for future projects and mobilizations, but few of these bore tangible fruit; it seems difficult to achieve concrete results and commitments in open workshop settings. On the other hand, plenty of agreements and decisions came out of informal conversations during the convergence. Are formal structures simply less efficient, or is this more the result of the predispositions of those who would attend a CrimethInc. convergence in the first place? If informal discussions are bound to be the setting of all the important decisions, how do we prioritize and facilitate them?</p>
<h3>And Hidden Somewhere Behind All This, A Publishing Collective</h3>
<p>Of all the workshops, performances, and discussions at the convergence, it is striking how little focus there was on CrimethInc. projects per se. On one hand, this avoids creating a &ldquo;star system&rdquo; centering attention on those already engaged in those projects, but on the other hand it contributes to the impression that the convergence is a merely social space, reinforcing the separation between the informal networks that produce projects and the social circles that consume them. At worst, this suggests a dynamic in which CrimethInc. is invisibly directed by a few people without the input of the vast majority of those who identify with it. On the other hand, efforts at earlier convergences to organize CrimethInc. projects did not bear fruit. What would it take for the convergence be a space in which wider participation in CrimethInc. propaganda projects could develop?</p>
<h3>Ambitious Hedonism, Or Going Through the Motions?</h3>
<p>At the end of the event, someone asked organizers who had been involved in several convergences what they would have done for the convergence had it simply been a matter of what most interested them personally. Their answers were all very different from what they had actually done. What would have happened if these experienced participants had tailored their efforts to their own personal tastes rather than to the presumed necessities of organizing a successful anarchist event? Are these participants unable to concentrate more on subjects and experiments that interest them because others are not stepping forward to handle the basic responsibilities of setting up infrastructure, or because of their own inability to trust others to do that?<br />
What would it look like to have a convergence that was designed to fulfill the specific wildest dreams of the individuals involved? Can we even imagine such a thing? If we can&rsquo;t, can we hope to make a revolution centered around the fulfillment of desire?</p>
<h3>POSTSCRIPT: The Adventure of Our Lives</h3>
<p> In August 2003, after participating in the CrimethInc. convergence described in &ldquo;<a href="/texts/pastfeatures/underhelicopters.php">Under the Helicopters</a>,&rdquo; my barnstorming group made one more tour stop&mdash;in Athens, Ohio. By that time, following an unplanned parade-turned-riot and subsequent media feeding frenzy, there was an APB out and police officers were waiting for us everywhere we went.</p>
<p>Our final evening of performances and workshops went smoothly enough until the conclusion. We&rsquo;d been ending each event by teaching people <a href="http://www.resurrectdead.com/crimethinc_article_checked_2.htm" target="_blank">how to make the asphalt tile mosaics</a>  described in <em><a href="http://www.crimethinc.com/books/rfd.html">Recipes for Disaster</a></em>, then affixing one in a street as a token of our passing. We debated briefly as to whether we should attempt this act of unorthodox vandalism under the watchful eyes of the police, and finally concluded&mdash;as we always do&mdash;that we had to go for it and let the consequences sort themselves out. A slapstick scene ensued such as one might see in a European comedy: imagine us running around the campus pursued by police and audience members, attempting to elude the former and put down our tile mosaic in front of the latter. In the end, we succeeded in deploying the mosaic, but were followed by police to the house we&rsquo;d intended to stay at and had to escape through the back alley to sleep somewhere else.</p>
<p>Months later, unbeknownst to us and against all odds, the mosaic remained in the parking lot&mdash;somehow the police never bothered to have it removed. Long before we ever met, the person who is now my lover and partner walked past a colorful heart set into the asphalt on her way to class every day, wondering how it came to be there.</p>
<p>Fast-forward nearly four years, to the end of July 2007. The tile mosaics our barnstorming tour put down have been paved over and the passionate friendships that bound our group together have cooled. All of us are now involved in new projects and friendships&mdash;for example, I&rsquo;m back in Athens, in an unpermitted parade at the conclusion of the sixth CrimethInc. convergence, surrounded by hundreds of costumed maniacs. Some of them are spinning fire; others are beating improvised percussion instruments, including one enormous drum pushed on a shopping cart; still others have just dislodged an enormous road blockade reading &ldquo;ROAD CLOSED&rdquo; from a construction site and are carrying it to the front. Among the whirling dancers and masked faces, through the haze of enthusiasm and good cheer, I can make out a couple people who were with me here four years earlier. We&rsquo;ve covered a lot of ground in that time.</p>
<p> My partner calls me over to a spot in the road. There, set in the asphalt, as fresh and bright as the day we put it there, is a colorful tile heart.</p>
<p>When experiments like these work, they connect us to spaces and to each other in a magical way, giving our lives back the narrative meaning that capitalism drains from everything. They may not immediately overthrow the government or abolish private ownership of capital, but they give us the networks, experience, and sense of our own power necessary for tilting at such monstrous windmills. Separated from our ongoing struggle for liberation they are senseless, but they aren&rsquo;t only useful as incremental steps towards liberation&mdash;they also <em>are</em> that liberation, as we recapture our lives, moment by moment, from routine and obedience.</p>
<h3>Missing Appendix</h3>
<p>Dear reader, <a href="/blog/2007/09/16/2007-convergence-coverage/">this blog post</a> is where your answers to these questions could be, along with your account from the convergence if you were there. Feel free to fill in the blanks. Thus far,<a href="http://crimethinc.com/blog/2007/07/30/convergence-coverage-appetizer/"> other than all the news reporting </a> from the parade at the end, these two accounts are all we&rsquo;ve been able to turn up: <br />
<a href="http://moxie0.livejournal.com" target="_blank">http://moxie0.livejournal.com</a><br />
<a href="http://crimethinc.net/board/topic/58" target="_blank">http://crimethinc.net/board/topic/58</a></p>
<span class="readinggallery"><a href="/texts/images/athens2big.jpg" rel="lightbox[athens]">
<img src="/texts/images/athens2small.jpg" width="156" height="100" style="margin-bottom: 15px"></a>
<a href="/texts/images/athens3big.jpg" rel="lightbox[athens]">
<img src="/texts/images/athens3small.jpg" width="156" height="100" style="margin-bottom: 15px"></a></span>  
<div id="footnoteprint">
<br />
<br />
<br />
<p><strong>[1]</strong>Arguably, as events such as this year&rsquo;s National Conference on Organized Resistance were somewhat less well organized and attended than before, the convergence is already playing this role de facto. Reports indicate that there were more people at the convergence than there were at the Earth First! rendezvous, or at the SDS national convention which ran contemporaneously. One might argue that CrimethInc., which began over a decade ago as a minority reaction to prevailing anarchist currents, has now become itself a central current. Perhaps this is an inevitable process&mdash;but should CrimethInc. projects be redirected to function better as part of the &ldquo;mainstream&rdquo; of anarchist activity? Or will this only crush out the last precious drops of the spontaneity that made them powerful in the first place? </p></div>