<h1>Undermining Oppression</h1>
<p>Ask an urban bird what a polluted sky is. You&rsquo;ll get no answer. Even if birds could tell their tale so you could understand it, they would likely have no explanation for the pollutants they breathe and fly through every moment of their lives. Polluted air simply is. Birds take it for granted.</p>
<p> The first step in combating oppression is learning to recognize it. Many people in North America seem to think racism, for example, is a thing of the past, banished now by affirmative action programs and Black History month. Radicals often have a stronger awareness of how prevalent racism still is, and may even develop an analysis of how it is only one manifestation of systematic white supremacy, but many go no further than this. To undermine and ultimately abolish oppression, it is necessary to take the step of confronting and undoing it in ourselves and others.</p>
<p> There are almost as many kinds of oppression as there are facets of our complex identities; some strains are based on visible traits like race or sex, others are not. Fortunately, there are also tools that can be used for identifying, resisting, and dismantling all of them.</p>
<p> Throughout this recipe, we focus on white supremacy so as to offer concrete examples, though it is not necessarily more widespread or pernicious than patriarchy or any other form of oppression. Oppression and privilege intertwine in extremely complex ways; racism, classism, heterosexism, ageism, and others overlap and extend into all spheres of our lives. Traditional single-issue activism focuses on contesting one manifestation of these at a time: fighting the prison-industrial complex, opposing corporate exploitation of low-wage workers, challenging specific foreign policies. Such activism can benefit greatly from a holistic understanding of oppression and how it operates&mdash;in these examples, how state repression, capitalism, and imperialism all rest on oppression and privilege. Whatever one&rsquo;s chosen focus, it is important to be aware of diverse forms of oppression and to challenge them on every level.</p>
<h3>Anger, Silence, and Guilt</h3>
<p>Working against both institutional and personal manifestations of oppression can be emotionally intense and challenging. In the course of learning to recognize and struggle against oppression, one is likely to encounter and experience deep resentment, regret, and heartache.</p>
<p> Many people have been deeply hurt and angered in the course of their experiences of oppression, and these feelings of hurt and anger can be hard for others to hear. Even when the ways they choose to express these feelings seem unproductive or antagonizing to those who have not shared their experience, it is important that they be supported in doing so&mdash;otherwise, how are people to learn from one another and gain perspective on themselves? If rage and pain are hard to hear about, imagine how much harder they are to live with and give voice to!</p>
<p> Likewise, fighting racism and white supremacy isn&rsquo;t a matter of simply learning not to say the wrong thing. At worst, would-be radicals can approach these issues in a self-serving manner, focusing on how to avoid being accused of racism and privilege instead of concentrating on actually combating them. If we are to effect real change in our society, we will do better to deal with everything openly, however clumsily, than to keep silent in fear of ourselves and each other.</p>
<p> Those who set out to contest their own privileges will inevitably struggle with feelings of guilt. Such feelings can be powerful resources; they can also paralyze and incapacitate. Guilt can motivate one to act in accordance with one&rsquo;s conscience, fostering self-awareness and courage; it can also trap one in a closed circle of self-recrimination. When those with privilege make their own guilt the focus of their thinking about oppression, it can be a way of re-centralizing their own experiences, turning away from the experiences of those who bear the brunt of injustices and from the question of what can be done.</p>
<p> When dealing with guilt, begin by analyzing what it is that makes you feel guilty, and move swiftly on to the matter of what concrete steps you can take to redress the situation. Focus on this, rather than on shame and self-flagellation. However complicit you may be in oppressive systems, however much more you may benefit from the status quo than others do, you too are deserving, you too are unique, you too suffer, just like everyone else&mdash;that is never in question. The question is what you can do to stop being complicit, to stop benefiting at others&rsquo; expense.</p>
<h3>Understanding What Oppression Is</h3>
<p>Oppression is a network of forces and barriers that are not accidental or occasional and hence avoidable, but systematically related in such a way as to catch one between and among them, restricting or penalizing motion in any direction. The experience of being oppressed is similar to the experience of being caged&mdash;all avenues, in every direction, are blocked.</p>
<p> Imagine a birdcage. If you look very closely at just one wire of the cage, you cannot see the other wires. You could examine that wire, up and down the length of it, and be unable to see why a bird would not just fly around it any time it desired to. There is no physical property of any one wire, nothing that the closest scrutiny could discover, that would reveal how a bird could be inhibited or harmed by it. It is only when you step back to view the whole cage that you can see why the bird does not go anywhere. Then it becomes obvious that the bird is surrounded by a network of systematically related barriers, no one of which would be the least hindrance to its flight, but which, in conjunction, are as confining as the solid walls of a dungeon.</p>
<p> Oppression can indeed be hard to see and recognize: one can study the elements of an oppressive structure with great care without seeing the structure as a whole, and hence without recognizing that one is looking at a cage.</p>
<p> With this understanding of oppression, one can distinguish between the terms oppression and domination. Domination occurs when an individual or group coerces, controls, or intimidates others. Domination is noxious in all its forms, but not all domination is oppression. Domination is being blocked by a single wire of a birdcage. For example, when the one white boy at an all-black school is taunted and even physically assaulted, these are acts of domination, not oppression. Some would call this reverse racism, but that expression is misleading: it suggests that the boy is experiencing the same thing the black students are by growing up in a white-dominated society, which is not the case. Oppression is not merely individual instances of domination, prejudice, or ignorance; it is the systematic privileging of one group over another. It is not possible for a more privileged group to be oppressed by a less privileged group: therefore reverse racism is a contradiction in terms.</p>
<p> In some ways, terms like racism and sexism are also misleading: they fail to bring to light the fact that in every instance of oppression, there is a privileged group as well as a targeted one. In using such language, we can overlook the role we play in these systems of oppression. Racism sounds like a mere matter of prejudice and ignorance, but the problem is deeper than this: it is the centrality of whiteness in our culture, which is better described by a term such as white supremacy. Modern white supremacy is a long-standing, institutionally perpetuated system of exploitation and oppression of continents, nations, and peoples of color. White people and nations tyrannize others in order to maintain and defend a system of wealth, power, and privilege. By using language that indicates this, we can identify clearly where privilege resides and what is actually at stake.</p>
<h3>Identity</h3>
<p>Western culture relies upon binary logic to classify things and people. From childhood, we learn oppositions like day/night, good/bad, boy/girl, and understand each word to have meaning only in relation to its opposite. Good means the complete absence of bad things, boy means the complete absence of girl things: boys are taught to be boys in large part by being discouraged from all behaviors deemed girlish. As we grow, we learn the many dualisms that frame the ways we see ourselves: feminine/masculine, homosexual/heterosexual, immigrant/native, children/adults, elderly/youthful, transgender/gender normative, color/white.</p>
<p> These dualisms contribute to a conception of the world that is oversimplified, even outright false. Not one of us embodies the extremes they define. All the same, we attempt to fit into the rigid boxes these words outline, so we can find words to describe who we are and live up to the words that describe what is worth being. In the process, we construct our individual identities, our sense of self, the defining of which then creates another binary: the I/other dichotomy. In rigidly defining who we are, we cast everything else as not like us, as other.</p>
<p> Just as each of us has an individual I, our society has a cultural I. The cultural I purports to represent the most prevalent social experience, even though the perspective it presents is actually that of a small minority, if of anyone at all. The cultural I is white, male, able-bodied, heterosexual, and every other characteristic defined as &ldquo;normal,&rdquo; and is coded into our society through a variety of visual and linguistic cues: the faces we see overwhelmingly in mass media, the implicit meanings in words like history and mankind. The cultural I can be recognized in what is not said, but assumed: philosophy means western philosophy, history means US history. The assumptions that some people don&rsquo;t have accents, that only non-white communities are ethnic groups, these are both evidence of the cultural I at work; the same goes for the habit of referring to non-whites, women, and other demographics as &ldquo;minorities,&rdquo; despite the obvious fact that they comprise the majority of the population. The halves of the binaries which are normalized in this way come to be taken for granted as standard&mdash;even if, like the blonde actresses in Mexican soap operas, they are extremely uncommon&mdash;and we only specify aspects of people&rsquo;s identities when they deviate from the norm.</p>
<h3>Privilege</h3>
<p>
Whether they wish it or not, members of dominant social groups possess unfair advantages over members of less privileged groups. Privilege depends on the existence of hierarchy: an imbalance of power extending throughout society, providing some demographics with more resources, leverage, and comfort than others. The workings of hierarchy are justified by supremacist thinking, such as the idea that some groups are harder working, better equipped, or more deserving than others; they also are obscured by the obliviousness that comes of identifying with the cultural I. Privilege can be practically invisible to those who have it; it is often painfully obvious to those who do not.</p>
<p> Social dynamics are never so simple that people can be divided easily into oppressors and oppressed, however. Any individual may partake of privilege in one situation, and suffer its absence in another. It makes more sense to focus on the ways some benefit and others suffer in regard to specific criteria, with an eye to following how these shift in different contexts. A group of people who all identify as women of color may be composed of different religions, genders, class backgrounds, native tongues, ethnicities, sexual orientations, and conditions of mental health and experience subtle power imbalances within their ranks accordingly. Similarly, it is a mistake to think of different forms of oppression as existing in a hierarchy of grievousness, or to argue that some manifestations of oppression are mere subsets of others; to do so trivializes the unique experiences of human beings, which cannot be measured or reduced to abstractions.</p>
<p>Many privileged people think of themselves as self-sufficient, assuming that they live in a meritocracy and that all that they have in life is the result of their own hard work or that of their families. In doing so, they overlook the institutional and cultural advantages from which they benefit. To take stock of what advantages you might have in terms of racial privileges, consider how many of these statements reflect your experience:</p>
<dl>
&bull; I can, if I wish, arrange to be in the company of people of my race most of the time.<br />
&bull; I can turn on the television or open to the front page of the paper and see people of my race widely represented.<br />
&bull; I can be sure that my children will be given curricular materials in school that testify to the existence of their race and to the history and accomplishments of others of their racial background.<br />
&bull; I can go into a music shop and expect to find music made by others of my race, into a supermarket and find the staple foods that fit with my cultural traditions, into a hairdresser&rsquo;s shop and find someone who can work with my hair.<br />
&bull; Whether I use checks, credit cards, or cash, I can count on my skin color not to work against the appearance of financial reliability.<br />
&bull; I can swear, dress in second-hand clothes, or not answer letters without having people attribute these choices to the bad morals, poverty, or illiteracy of my race.<br />
&bull; I can do well in a challenging situation without being called a credit to my race.<br />
&bull; I am never asked to speak for all the people of my racial group.<br />
&bull; I can criticize the US government and talk about how much I fear its policies and behavior without being immediately seen as a cultural outsider.<br />
&bull; I can be pretty sure that if I ask to talk to the &ldquo;person in charge&rdquo; I will be facing a person of my race.<br />
&bull; If my day, week, or year is going badly, I need not wonder of each negative episode or situation whether it has racial overtones.
</dl>
<p> For more perspective, go over this list again, replacing &ldquo;race&rdquo; with ethnicity, sex, gender, age, shape, and so on. Of course, no two white people experience white privilege in exactly the same way, just as not every man feels safer walking alone at night than every woman. Some people have made life decisions that result in them not experiencing many of the daily privileges enjoyed by others of their demographic: a taxi driver may be as likely to refuse to pick up a white man with facial tattoos as a black man without them. But privilege, on a deeper level, is not easily shaken off. The white man, in an extreme, can have his tattoos removed, while the black man knows that the challenges he faces in a racist society are inescapable. A woman from a middle class family may choose a life of poverty and even homelessness, but the fact that she is connected to people who might be able to help her in an emergency makes her experience very different from that of a homeless person of a poor background. Similarly, the advantages that come from having been raised in a privileged setting remain throughout one&rsquo;s life, whatever else happens. Those of privileged backgrounds who choose a path of exile upon which they experience alienation and persecution can draw on these experiences to imagine what life is like for those who never had their advantages in the first place.</p>
<p> Rather than denying the privileges one possesses or imagining one could somehow wash one&rsquo;s hands of them and thus of complicity in oppression, it makes more sense to use one&rsquo;s privileges, whatever they may be, to undermine privilege in general. One way to do so is to find ways to put these at the disposal of others who can benefit from them. If nothing else, one should always attempt to stay aware of the unfair advantages one has, and to take these into account in interactions with others; but simply learning to recognize and decry one&rsquo;s privileges while still cashing in on them does not constitute an effective struggle against oppression.</p>
<h3>Reclaiming Identity: Identity Politics</h3>
<p>A classic step in self-empowerment has been to reclaim the boxes we&rsquo;re forced into, reinterpreting them as politicized identities. By linking up with others like us, we find validation of our experiences and perspectives, and companions with whom to struggle against the forces that oppress us and others.</p>
<p> The matter of identity is indeed complex. A person&rsquo;s identity is not a set of fixed essences, but a fluid intersection of social, political, and psychological processes. Yet though the constructed identities foisted upon us by this society may not reflect what we consider to be our true selves, we must engage with them in order to subvert them. Whether or not we want it to be the case, our experiences are shaped by the ways we are perceived, and it can be useful to organize with those who share our experiences.</p>
<p> For instance, even in gatherings of radicals or others thought to be conscious about racism and white supremacy, people of color can feel alienated, for example when there is a great disparity in numbers between those who have white privilege in common and those who do not. In such situations, one option is to call for a &ldquo;caucus&rdquo; or establish a &ldquo;safer space&rdquo; wherein people of color invite others who identify similarly to gather and interact in an exclusive space, or at least taking a break from the potentially taxing experience of being in a minority that must deal with uneven power dynamics. The purpose of this is not to exclude those who do not identify as people of color. It is, rather, a way for those who can feel alienated, marginalized, or victimized in environments in which the tone is set by more privileged groups to come together, support one another, and organize as they desire. It can be a relief to take some time off from the challenges of interacting with others who do not share one&rsquo;s frame of reference for oppression, and from feeling the pressure of others&rsquo; observation and expectations. Ultimately, it is in the best interest of everyone in a group that all individuals within it feel comfortable and empowered.</p>
<p> Caucuses and safer spaces need not be limited to people of color, of course: all who feel they might benefit from this format can employ it. They need not happen only at short-term gatherings of radicals, either: it can make sense to have weekly caucuses in a community, or monthly ones within a collective, or to call for one in the midst of an organizing effort. Women-only houses can offer round-the-clock safer space, youth-only radio stations can provide opportunities for individuals to develop their unique voices, queer-only magazines and action groups can carry out long-term campaigns. In this way, the identities that mark targeted groups for oppression can be turned into sites for organizing resistance to it.</p>
<h3>Self-Empowerment</h3>
<p> Covering the surface of this society is a complex network of minute rules and norms through which the most original minds and energetic characters can barely penetrate. People&rsquo;s wills are not shattered, but softened, bent, and guided. We are seldom forced to act, but are constantly restrained from acting. Such repression does not destroy, but rather prevents existence; it does not tyrannize, but instead compresses, stifles, and stupefies, so that each individual grows up into a dutiful lamb that needs no shepherding to stay within the fence-line. This is not political repression, which necessitates secret police and prison camps, but cultural repression, in which people police and imprison themselves.</p>
<p> It is too simplistic to imagine individual social controllers in the upper echelons of power as the source of all oppression. White supremacy, for example, is not just the clubs of white policemen, nor the country clubs of white executives. White power is not just the power of white people; it is a system of dynamics extending throughout every level of a society, present in every interaction and within every individual. This is why there can be white privilege even in nations where&mdash;according to conventional North American standards&mdash;no one is, technically speaking, white. Likewise, there is no external enemy we can march against to overthrow patriarchy; we are within enemy territory, and the enemy is within us. At the same time as we fight against external manifestations of oppression, we must also struggle against those we have internalized, putting an end to our own oppressive actions and empowering ourselves to cast off the shackles we have received.</p>
<p> Learning to take criticism constructively&mdash;even when it&rsquo;s hard to feel that it is intended constructively&mdash;is an important part of this. If one is too defensive to receive perspective on one&rsquo;s own attitudes and conduct, one will miss out on countless opportunities to better oneself. At the same time, one must learn to recognize the voice of the oppressor in one&rsquo;s own head, telling one what one can and cannot do, what one deserves and does not deserve. An encouraging, inspiring circle of peers can help to counteract this internalized oppression.</p>
<h3>Being an Ally</h3>
<p>To be allies to others in the struggle against racism&mdash;to name one example of oppression&mdash;is to recognize that racism exists within us without resigning ourselves to that fact, and to engage in real resistance that goes beyond the confession of our personal complicity. It is to accept that we who have internalized racial dominance will never fully understand the plight of those who suffer the injustices of white supremacy more than we do, and yet to do all we can to learn from their experiences. It is to take an active role in fighting against racist institutions, without compromising the autonomy of those who have even more at stake in this struggle than we do.</p>
<p> People sometimes assume that the means for learning about racism are in scarce supply. This is an absurd, perhaps even subtly racist assumption, as it ignores the abundance of experience around us. To gain an understanding of the workings of white supremacy, one need not attend endless workshops or become involved in an obscure subculture; indeed, there are reasons to be suspicious of anti-racist organizing in which white experts take the lead in educating and organizing. There are no experts on oppression&mdash;or rather, all who experience oppression are experts. Even if you have been so privileged as not to have experienced it yourself, there are people all around you who know firsthand what it is to bear the brunt of racist injustice and inequality. You simply must learn to listen to them, and to conduct yourself such that they will be willing to share their experiences with you.</p>
<p> At the same time, no person more targeted by the racist system than you are owes it to you to take the time to educate you about racism. They have enough to deal with already, without you feeling entitled to make assumptions about or demands of them. Many people of color are exhausted from being asked to speak for all members of their race throughout their lives, or for that matter for all members of all non-white races. Whenever people less privileged than you are willing to take the time to share their perspectives, they are giving a generous gift, one greater than anyone could possibly ask of them and not to be taken for granted. In the meantime, whenever you need to learn about racism and white supremacy and don&rsquo;t know who to approach, you can always consult the vast bodies of literature, film, music, and history made by those of less privileged backgrounds than your own. Aspiring anti-racists of all races, accustomed to listening to popular white views on nearly everything, would benefit from taking in knowledge of all sorts from multiple sources. As programmed as we all have been by this racist society, we owe it to ourselves and each other to begin learning the rest of our history and culture.</p>
<p> Educating oneself is a critical starting place, but this is not sufficient to make one a good ally: one must make use of this education in practice. Learning the ways that privileged groups dominate others, one must then take steps to cease all such activities. This can be as simple as a man learning not to interrupt women in conversation, or as complex as a household of white tenants joining in a struggle against the gentrification of their predominantly black neighborhood.</p>
<p> To be an ally, one ultimately must provide concrete support to those on the front lines of the struggle against oppression. In doing so, a person from a privileged background should be careful not to attempt to assume control, as he or she has been conditioned to feel entitled to do, but rather endeavor to provide support to others according to their express wishes. Above all, would-be allies must stay sensitive, both to the needs of others and to the tragedies in the world around them, and put their outrage at the disposal of those who suffer these tragedies.</p>
<h3>Group Dynamics</h3>
<p>Oppression is not an individual problem, but a social phenomenon; accordingly, while individuals can work on deconstructing it within themselves and supporting others who are struggling against it, the most important work against oppressive dynamics takes place in social groups.</p>
<p> Hierarchical power dynamics are common even in affinity groups, collectives, and other groups that aspire to radical activity. Many communities include aggressive or dominating individuals who, in speaking or acting, hinder others from doing so. They offer their opinions on every topic, take over the organizing of every project, seize every opportunity to speak on behalf of others. Such dominating individuals may believe that they are doing the majority of the work because no one else would do it if they did not; but it can also be the case that they are creating an environment in which others become unwilling to fight for space in which to act. Taken by itself, this behavior is only domination; but when one factors in the privileges many domineering individuals abuse and perpetuate, it can be recognized as yet another manifestation of oppression.</p>
<p> Individuals must develop the self-awareness to resist dominating social situations and prevent others from dominating them. There are tools groups can use collectively to this end, as well. Simple matters, such as how accessible gathering times and locations are to different demographics and whether childcare is available, can determine who is and is not able to participate in specific projects and social circles. In meetings, a group can give speaking priority to those who have been speaking less, or to those who are more directly affected by the issue in question. Discussions can be set up in a format that encourages the equal participation of different groups: for example, women and men can alternate speaking, so there will be equal proportions of male and female voices heard. No structure can be counted on to be better than the people who make use of it&mdash;there&rsquo;s no substitute for self-awareness and sensitivity&mdash;but such conventions can be a stepping stone to more naturally egalitarian dynamics.</p>
<p> Another format useful for resolving conflicts or giving a group perspective on its inner dynamics is sometimes called a &ldquo;fishbowl.&rdquo; This exercise is like safer spaces and caucuses in that a space and time is set aside for one demographic within the group to speak, but in this case the rest of the group is present, listening to but not participating in the discussion. This can be a tremendously instructive opportunity for those with privilege to learn about others&rsquo; experiences, and for those who experience challenges in working with privileged individuals to address them; at the same time, this practice must be applied with care, as it can make people feel singled out.</p>
<p> No one appreciates feeling used or put on display because of the color of their skin or any other such characteristic. This is sometimes called tokenization, and it is a blunder many commit in attempts to make their communities more welcoming to &ldquo;others.&rdquo; Recruiting people of color, women, or other less privileged demographics to prove one&rsquo;s dedication to anti-oppression work, or asking them to speak as &ldquo;the minority&rdquo; in meetings or conversations, can itself be oppressive behavior.</p>
<h3>Nurturing Relationships</h3>
<p>Developing relationships with those who experience less privilege is no guarantee that we will deal openly and consistently with race or any other such issue. Too often, people claim to understand the experiences of another group because of a high degree of exposure to them: &ldquo;But my best friend is black!&rdquo; &ldquo;But my stepfather wasn&rsquo;t born here!&rdquo; A white person&rsquo;s relationship with a person of color can never be a proof or a credential of anti-racist consciousness.</p>
<p> All the same, working to dismantle the institutional, cultural, and personal barriers that keep us alienated from one another is a fundamental part of undermining white supremacy and other forms of oppression. We may have to accept that there will always be more barriers to remove, but in removing those we are able to we learn and grow in revolutionary ways. Meaningful relationships that transcend boundaries and constructs can offer a taste of the world oppression otherwise denies us. Building friendships and alliances with people whose experience of oppression is different from our own is much more than a strategy for working towards specific political ends; it is also a way to live life more fully and do our part to make it possible for others do the same.</p>
<p>&nbsp;</p>
</div>