<p align="center"><a href="http://cloudfront.crimethinc.com/images/violence/1b.jpg" rel="lightbox[violence]"><img src="http://cloudfront.crimethinc.com/images/violence/1a.jpg" width="500" height="333"/></a></p>
<h1>The Illegitimacy of Violence,  the Violence of Legitimacy</h1>
<p>What is violence? Who gets to define it? Does it have a place in the pursuit of liberation? These age-old questions have returned to the fore during the Occupy movement. But this discussion never takes place on a level playing field; while some delegitimize violence, the language of legitimacy itself paves the way for the authorities to employ it.</p>
<p>&nbsp;</p>
<h5>&ldquo;Though lines of police on horses, and with dogs, charged the main street outside the police station to push rioters back, there were significant pockets of violence which they could not reach.&rdquo;<br />
</h5>
<h4 align="right">&ndash;<a href="http://thelede.blogs.nytimes.com/2011/08/06/shops-and-cars-burn-in-anti-police-riot-in-london/" target="_blank">The New York Times</a>,
on the UK riots of August 2011</h4>
<p>&nbsp;</p>
<p>During the 2001 FTAA summit in Quebec City, one newspaper famously reported that <a href="http://www.trabal.org/texts/stvio_socmovestud.pdf" target="_blank">violence erupted when protesters began throwing tear gas canisters back at the lines of riot police.</a> When the authorities are perceived to have a monopoly on the legitimate use of force, &ldquo;violence&rdquo; is often used to denote <em>illegitimate use of force</em>&mdash;anything that interrupts or escapes their control. This makes the term something of a <a href="http://en.wikipedia.org/wiki/Floating_signifier" target="_blank">floating signifier</a>, since it is also understood to mean &ldquo;harm or threat that violates consent.&rdquo;</p>
<p>This is further complicated by the ways our society is based on and permeated by <em>harm or threat that violates consent.</em> In this sense, isn&rsquo;t it violent to live on colonized territory, destroying ecosystems through our daily consumption and benefitting from economic relations that are forced on others at gunpoint? Isn&rsquo;t it violent for armed guards to keep food and land, once a commons shared by all, from those who need them? Is it more violent to resist the police who evict people from their homes, or to stand aside while people are made homeless? Is it more violent to throw tear gas canisters back at police, or to denounce those who throw them back as &ldquo;violent,&rdquo; giving police a free hand to do worse?</p>
<p>In this state of affairs, there is no such thing as <em>nonviolence</em>&mdash;the closest we can hope to come is to negate the <em>harm or threat</em> posed by the proponents of top-down violence. And when so many people are invested in the privileges this violence affords them, it&rsquo;s na&iuml;ve to think that we could defend ourselves and others among the dispossessed without violating the wishes of at least a few bankers and landlords. So instead of asking whether an action is violent, we might do better to ask simply: <em>does it counteract power disparities, or reinforce them?</em></p>
<p>This is the fundamental anarchist question. We can ask it in every situation; every further question about values, tactics, and strategy proceeds from it. When the question can be framed thus, why would anyone want to drag the debate back to the dichotomy of violence and nonviolence?</p>
<p>The discourse of violence and nonviolence is attractive above all because it offers an easy way to claim the higher moral ground. This makes it seductive both for criticizing the state and for competing against other activists for influence. But in a hierarchical society, gaining the <em>higher ground</em> often reinforces hierarchy itself.</p>
<p>Legitimacy is one of the currencies that are unequally distributed in our society, through which its disparities are maintained. Defining people or actions as violent is a way of excluding them from legitimate discourse, of silencing and shutting out. This parallels and reinforces other forms of marginalization: a wealthy white person can act &ldquo;nonviolently&rdquo; in ways that would be seen as violent were a poor person of color to do the same thing. In an unequal society, the defining of &ldquo;violence&rdquo; is no more neutral than any other tool.</p>
<p>Defining people or actions as violent also has immediate consequences: it justifies the use of force against them. This has been an essential step in practically every campaign targeting communities of color, protest movements, and others on the wrong side of capitalism. If you&rsquo;ve attended enough mobilizations, you know that it&rsquo;s often possible to anticipate exactly how much violence the police will use against a demonstration by the way the story is presented on the news the night before. In this regard, pundits and even rival organizers can participate in <em>policing</em> alongside the police, determining who is a legitimate target by the way they frame the narrative.</p>
<p>On the one-year anniversary of the Egyptian uprising, the military lifted the Emergency Laws&mdash;<a href="http://www.egyptindependent.com/node/617036" target="_blank">&ldquo;except in thug-related cases.&rdquo;</a> The popular upheaval of 2011 had forced the authorities to legitimize previously unacceptable forms of resistance, with Obama characterizing as <a href="http://www.youtube.com/watch?v=TyDLjLfE2Jc" target="_blank">&ldquo;nonviolent&rdquo;</a> an uprising in which thousands had <a href="http://occupywallst.org/article/solidarity-statement-cairo/" target="_blank">fought police and burned down police stations</a>. In order to re-legitimize the legal apparatus of the dictatorship, it was necessary to create a new distinction between violent &ldquo;thugs&rdquo; and the rest of the population. Yet the substance of this distinction was never spelled out; in practice, &ldquo;thug&rdquo; is simply the word for a person targeted by the Emergency Laws. From the perspective of the authorities, ideally <em>the infliction of violence itself</em> would suffice to brand its victims as violent&mdash;i.e., as legitimate targets.<a class="footnote" href="javascript:void(0);" onclick="return overlib('Witness how police officers routinely charge arrestees with whatever violence they have inflicted upon them.', CAPTION, '[1]');" onmouseout="nd();">[1]</a></p>
<p>So when a broad enough part of the population engages in resistance, the authorities have to redefine it as nonviolent, even if it would previously have been considered violent. Otherwise, the dichotomy between violence and legitimacy might erode&mdash;and without that dichotomy, it would be much harder to justify the use of force against those who threaten the status quo. By the same token, the more ground we cede in what we permit the authorities to define as violent, the more they will sweep into that category, and the greater risk all of us will face. One consequence of the past several decades of self-described nonviolent civil disobedience is that some people regard merely raising one&rsquo;s voice as violent; this makes it possible to portray those who take even the most tentative steps to protect themselves against police violence as violent thugs.</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/violence/2b.jpg" rel="lightbox[violence]"><img src="http://cloudfront.crimethinc.com/images/violence/2a.jpg" width="500" height="357"/></a></p>
<h5>&ldquo;The individuals who linked arms and actively resisted, that in itself is an act of violence&hellip; linking arms in a human chain when ordered to step aside is not a nonviolent protest.&rdquo;</h5>
<h4 align="right">  -UC police captain Margo Bennett, <br />
quoted in <a href="http://www.sfgate.com/cgi-bin/article.cgi?f=/c/a/2011/11/10/MNH21LTC4D.DTL#ixzz1dQT8J9cb" target="_blank">The San Francisco Chronicle</a>, <br />
justifying the use of force against students <br />
at the University of California at Berkeley</h4>
<p><br />
</p>
<h2><strong>The Master&rsquo;s Tools: Delegitimization, Misrepresentation, and Division</strong></h2>
<p>Violent repression is only one side of the two-pronged strategy by which social movements are suppressed. For this repression to succeed, movements must be divided into <em>legitimate</em> and <em>illegitimate,</em> and the former convinced to disown the latter&mdash;usually in return for privileges or concessions. We can see this process up close in the efforts of professional journalists like Chris Hedges and Rebecca Solnit to demonize rivals in the Occupy movement.</p>
<p>In last year&rsquo;s <a href="http://www.commondreams.org/view/2011/11/14-8" target="_blank">Throwing Out the Master&rsquo;s Tools and Building a Better House: Thoughts on the Importance of Nonviolence in the Occupy Revolution</a>,&rdquo; Rebecca Solnit mixed together moral and strategic arguments against &ldquo;violence,&rdquo; hedging her bets with a sort of US exceptionalism: Zapatistas can carry guns and Egyptian rebels set buildings on fire, but let no one so much as burn a trash can in the US. At base, her argument was that only &ldquo;people power&rdquo; can achieve revolutionary social change&mdash;and that &ldquo;people power&rdquo; is necessarily nonviolent.</p>
<p>Solnit should know that the defining of violence isn&rsquo;t neutral: in her article &ldquo;The Myth of Seattle Violence,&rdquo; she recounted her unsuccessful struggle to get the <em>New York Times</em> to stop representing the demonstrations against the 1999 WTO summit in Seattle as &ldquo;violent.&rdquo; In consistently emphasizing <em>violence</em> as her central category, Solnit is reinforcing the effectiveness of one of the tools that will inevitably be used against protesters&mdash;including her&mdash;whenever it serves the interests of the powerful.</p>
<p>Solnit reserves particular ire for those who endorse diversity of tactics as a way to preclude the aforementioned dividing of movements. Several paragraphs of &ldquo;Throwing Out the Master&rsquo;s Tools&rdquo; were devoted to denouncing the CrimethInc. <a href="http://www.crimethinc.com/blog/2011/10/07/dear-occupiers-a-letter-from-anarchists/">&ldquo;Dear Occupiers&rdquo;</a> pamphlet: Solnit proclaimed it &ldquo;a screed in justification of violence,&rdquo; &ldquo;empty machismo peppered with insults,&rdquo; and stooped to ad hominem attacks on authors about whom she admittedly knew nothing.<a class="footnote" href="javascript:void(0);" onclick="return overlib('For what it&rsquo;s worth, though Solnit alleges that we &ldquo;don&rsquo;t seem prepared to act,&rdquo; the authors of &ldquo;Dear Occupiers&rdquo; and this text are all lifelong participants in social movements, most of whom live well below the poverty line far from liberal Meccas like her San Francisco. This subject strikes very close to home for us: several of us have faced trumped up rioting charges&mdash;one for acting as a public liaison during an anti-gentrification demonstration, another for being tackled by police during a street parade&mdash;and many of us have dear friends in prison. We choose to write anonymously in part because, not being professional journalists, we can&rsquo;t count on employers not to discriminate against us for our political beliefs, and also because these beliefs attract more hostile attention from the authorities than those of Solnit or Hedges, but above all because we don&rsquo;t seek to found careers or personal fame on our efforts to change the world.', CAPTION, '[2]');" onmouseout="nd();">[2]</a></p>
<p>As anyone can <a href="http://cloudfront.crimethinc.com/images/occupy/dearoccupiers.pdf">readily ascertain</a>, the majority of &ldquo;Dear Occupiers&rdquo; simply reviews the systemic problems with capitalism; the advocacy of diversity of tactics is limited to a couple subdued paragraphs. Why would an award-winning author represent this as a pro-violence screed?</p>
<p>Perhaps for the same reason that she joins the authorities in delegitimizing violence even when this equips them to delegitimize her own efforts: Solnit&rsquo;s leverage in social movements and her privileges in capitalist society are both staked on the distinction between legitimate and illegitimate. If social movements ever cease to be managed from the top down&mdash;if they stop <em>policing themselves</em>&mdash;the Hedges and Solnits of the world will be out of a job literally as well as figuratively. That would explain why they perceive their worst enemies to be those who soberly advise against dividing movements into legitimate and illegitimate factions.</p>
<p>It&rsquo;s hard to imagine Solnit would have represented &ldquo;Dear Occupiers&rdquo; the way she did if she expected her audience to read it. Given her readership, this is a fairly safe bet&mdash;Solnit is often published in the corporate media, while CrimethInc. literature is distributed only through grass-roots networks; in any case, she didn&rsquo;t include a link. Chris Hedges took similar liberties in his notorious &ldquo;<a href="http://www.truthdig.com/report/item/the_cancer_of_occupy_20120206/" target="_blank">The Cancer in Occupy</a>,&rdquo; a litany of outrageous generalizations about &ldquo;black bloc anarchists.&rdquo; It seems that both authors&rsquo; ultimate goal is <a href="http://www.crimethinc.com/blog/2012/02/20/black-bloc-confidential/">silencing</a>: <em>Why would you want to hear what those people have to say? They&rsquo;re violent thugs.</em></p>
<p>The title of Solnit&rsquo;s article is a reference to Audre Lorde&rsquo;s influential text, &ldquo;<a href="http://lists.econ.utah.edu/pipermail/margins-to-centre/2006-March/000794.html" target="_blank">The Master&rsquo;s Tools Will Never Dismantle the Master&rsquo;s House</a>.&rdquo; Lorde&rsquo;s text was not an endorsement of nonviolence; even Derrick Jensen, whom Hedges quotes approvingly, has <a href="http://www.endgamethebook.org/Excerpts/25%20-%20Pacifism%20I.html" target="_blank">debunked such misuse of this quotation</a>. Here, let it suffice to repeat that the most powerful of the master&rsquo;s tools is not violence, but delegitimization and division&mdash;as Lorde emphasized in her text. To defend our movements against these, Lorde exhorted us:</p>
<h6>&ldquo;Difference must be not merely tolerated, but seen as a fund of necessary polarities between which our creativity can spark&hellip; Only within that interdependency of different strengths, acknowledged and equal, can the power to seek new ways of being in the world generate, as well as the courage and sustenance to act where there are no charters.&rdquo;</h6>
<p>If we are to survive, that means:</p>
<h6>&ldquo;&hellip;learning how to stand alone, unpopular and sometimes reviled, and how to make common cause with those others identified as outside the structures in order to define and seek a world in which we can all flourish&hellip; learning how to take our differences and make them strengths. For the master's tools will never dismantle the master's house.&rdquo;</h6>
<p>It is particularly shameless that Solnit would quote Lorde&rsquo;s argument against silencing out of context in order to delegitimize and divide. But perhaps we should not be surprised when successful professionals sell out anonymous poor people: they have to defend their class interests, or else risk joining us. For the mechanisms that raise people to positions of influence within activist hierarchies and liberal media are not neutral, either; they reward docility, often coded as &ldquo;nonviolence,&rdquo; rendering invisible those whose efforts actually threaten capitalism and hierarchy.<br />
</p>
<h2><strong>The Lure of Legitimacy</strong></h2>
<p>When we want to be taken seriously, it&rsquo;s tempting to claim legitimacy any way we can. But if we don&rsquo;t want to reinforce the hierarchies of our society, we should be careful not to validate forms of legitimacy that perpetuate them.</p>
<p>It is easy to recognize how this works in some situations: when we evaluate people on the basis of their academic credentials, for example, this prioritizes abstract knowledge over lived experience, centralizing those who can get a fair shot in academia and marginalizing everyone else. In other cases, this occurs more subtly. We emphasize our status as community organizers, implying that those who lack the time or resources for such pursuits are less entitled to speak. We claim credibility as longtime locals, implicitly delegitimizing all who are not&mdash;including immigrants who have been forced to move to our neighborhoods because their communities have been wrecked by processes originating in ours. We justify our struggles on the basis of our roles within capitalist society&mdash;as students, workers, taxpayers, citizens&mdash;not realizing how much harder this can make it for the unemployed, homeless, and excluded to justify theirs.</p>
<p>We&rsquo;re often surprised by the resulting blowback. Politicians discredit our comrades with the very vocabulary we popularized: &ldquo;Those aren&rsquo;t activists, they&rsquo;re homeless people pretending to be activists.&rdquo; &ldquo;We&rsquo;re not targeting communities of color, we&rsquo;re protecting them from criminal activity.&rdquo; Yet we prepared the way for this ourselves by affirming language that makes legitimacy conditional.</p>
<p>When we emphasize that our movements are and must be nonviolent, we&rsquo;re doing the same thing. This creates an <a href="http://en.wikipedia.org/wiki/Other" target="_blank">Other</a> that is outside the protection of whatever legitimacy we win for ourselves&mdash;that is, in short, a legitimate target for violence. Anyone who pulls their comrades free from the police rather than waiting passively to be arrested&mdash;anyone who makes shields to protect themselves from rubber bullets rather than abandoning the streets to the police&mdash;anyone who is charged with assault on an officer for being assaulted by one: all these unfortunates are thrown to the wolves as the <em>violent</em> ones, the bad apples. Those who must wear masks even in legal actions because of their precarious employment or immigration status are denounced as <em>cancer,</em> betrayed in return for a few crumbs of legitimacy from the powers that be. We Good Citizens can afford to be perfectly transparent; we would never commit a crime or harbor a potential criminal in our midst.</p>
<p>And the <a href="http://en.wikipedia.org/wiki/Other" target="_blank">Othering</a> of violence smooths the way for <em>the violence of Othering</em>. The ones who bear the worst consequences of this are not the middle class brats pilloried in internet flame wars, but the same people on the wrong side of every other dividing line in capitalism: the poor, the marginalized, those who have no credentials, no institutions to stand up for them, no incentive to play the political games that are slanted in favor of the authorities and perhaps also a few jet-setting activists.</p>
<p>Simply delegitimizing violence can&rsquo;t put an end to it. The disparities of this society couldn&rsquo;t be maintained without it, and the desperate will always respond by acting out, especially when they sense that they&rsquo;ve been abandoned to their fate. But this kind of delegitimization <em>can</em> create a gulf between the angry and the morally upright, the &ldquo;irrational&rdquo; and the rational, the <em>violent</em> and the <em>social.</em> We saw the consequences of this in the UK riots of August 2011, when many of the disenfranchised, despairing of bettering themselves through any legitimate means, hazarded a private war against property, the police, and the rest of society. Some of them had attempted to participate in previous <a href="http://www.crimethinc.com/blog/2011/01/26/the-uk-student-movement/">popular movements</a>, only to be stigmatized as hooligans; not surprisingly, their rebellion took an antisocial turn, resulting in five deaths and further alienating them from other sectors of the population.</p>
<p>The responsibility for this tragedy rests not only on the rebels themselves, nor on those who imposed the injustices from which they suffered, but also upon the activists who stigmatized them rather than joining in creating a movement that could channel their anger. If there is no connection between those who intend to transform society and those who suffer most within it, no common cause between the hopeful and the enraged, then when the latter rebel, the former will disown them, and the latter will be crushed along with all hope of real change. No effort to do away with hierarchy can succeed while excluding the disenfranchised, the Others.</p>
<p>What should be our basis for legitimacy, then, if not our commitment to legality, nonviolence, or any other standard that hangs our potential comrades out to dry? How do we explain what we&rsquo;re doing and why we&rsquo;re entitled to do it? We have to mint and circulate a currency of legitimacy that is not controlled by our rulers, that doesn&rsquo;t create Others.</p>
<p>As anarchists, we hold that our desires and well-being and those of our fellow creatures are the only meaningful basis for action. Rather than classifying actions as violent or nonviolent, we focus on whether they extend or curtail freedom. Rather than insisting that we are nonviolent, we emphasize the necessity of interrupting the violence inherent in top-down rule. This might be inconvenient for those accustomed to seeking dialogue with the powerful, but it is unavoidable for everyone who truly wishes to abolish their power.<br />
</p>
<h2><strong>Conclusion: Back to Strategy</strong></h2>
<p>But how <em>do</em> we interrupt the violence of top-down rule? The partisans of nonviolence frame their argument in strategic as well as moral terms: violence alienates the masses, preventing us from building the &ldquo;people power&rdquo; we need to triumph.</p>
<p>There is a kernel of truth at the heart of this. If violence is understood as <em>illegitimate use of force,</em> their argument can be summarized as a tautology: <em>delegitimized action is unpopular.</em></p>
<p>Indeed, those who take the legitimacy of capitalist society for granted are liable to see anyone who takes material steps to counteract its disparities as violent. The challenge facing us, then, is to legitimize concrete forms of resistance: not on the grounds that they are nonviolent, but on the grounds that they are liberating, that they fulfill real needs and desires.</p>
<p>This is not an easy matter. Even when we passionately believe in what we are doing, if it is not widely recognized as legitimate we tend to sputter when asked to explain ourselves. If only we could stay within the bounds prescribed for us within this system while we go about overthrowing it! The Occupy movement was characterized by attempts to do just that&mdash;citizens insisting on their right to occupy public parks on the basis of obscure legal loopholes, making tortuous justifications no more convincing to onlookers than to the authorities. People want to redress the injustices around them, but in a highly regulated and controlled society, there&rsquo;s so little they feel entitled to <em>do.</em></p>
<p>Solnit may be right that the emphasis on nonviolence was essential to the initial success of Occupy Wall Street: people want some assurance that they&rsquo;re not going to have to leave their comfort zones, and that what they&rsquo;re doing will make sense to everyone else. But it often happens that the preconditions for a movement become limitations that it must transcend: Occupy Oakland remained vibrant after other occupations died down <em>because</em> it embraced a diversity of tactics, not <em>despite</em> this. Likewise, if we really want to transform our society, we can&rsquo;t remain forever within the narrow boundaries of what the authorities deem legitimate: we have to extend the range of what people feel entitled to do.<br />
</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/violence/3b.jpg" rel="lightbox[violence]"><img src="http://cloudfront.crimethinc.com/images/violence/3a.jpg" width="500" height="333"/></a></p>
<h5>All the media coverage in the world won&rsquo;t help us if we fail to create a situation in which people feel entitled to defend themselves and each other.<br />
</h5>
<p>Legitimizing resistance, expanding what is acceptable, is not going to be popular at first&mdash;it never is, precisely because of the tautology set forth above. It takes consistent effort to shift the discourse: calmly facing outrage and recriminations, humbly emphasizing our own criteria for what is legitimate.</p>
<p>Whether we think this challenge is worthwhile depends on our long-term goals. As David Graeber <a href="http://theanarchistlibrary.org/HTML/David_Graeber__The_Shock_of_Victory.html" target="_blank">has pointed out</a>, conflicts over goals often masquerade as moral and strategic differences. Making nonviolence the central tenet of our movement makes good sense if our long-term goal is not to challenge the fundamental structure of our society, but to build a mass movement that can wield legitimacy as defined by the powerful&mdash;and that is prepared to <em>police</em> itself accordingly. But if we really want to transform our society, we have to transform the discourse of legitimacy, not just position ourselves well within it as it currently exists. If we focus only on the latter, we will find that terrain slipping constantly from beneath our feet, and that many of those with whom we need to find common cause can never share it with us.</p>
<p>It&rsquo;s important to have strategic debates: shifting away from the discourse of nonviolence doesn&rsquo;t mean we have to endorse every single broken window as <em>a good idea.</em>. But it only obstructs these debates when dogmatists insist that all who do not share their goals and assumptions&mdash;not to say their class interests!&mdash;have no strategic sense. It&rsquo;s also not strategic to focus on delegitimizing each other&rsquo;s efforts rather than coordinating to act together where we overlap. That&rsquo;s the point of affirming a diversity of tactics: to build a movement that has space for all of us, yet leaves no space for domination and silencing&mdash;a &ldquo;people power&rdquo; that can both expand and intensify.<br />
</p>
<h3><strong>Further Reading</strong></h3>
<p><a href="http://woborders.wordpress.com/2012/02/13/debating-tactics-remember-to-ask-what-works/" target="_blank"><strong>Debating Tactics: Remember to Ask, &ldquo;What Works?&rdquo;</strong></a></p>
<p><strong><a href="http://phdoctopus.com/2012/02/13/historicizing-violence-thoughts-on-the-hedgesgraeber-debate/" target="_blank">Historicizing &ldquo;Violence&rdquo;: Thoughts on the Hedges/Graeber&nbsp;Debate</a></strong><a href="http://phdoctopus.com/2012/02/13/historicizing-violence-thoughts-on-the-hedgesgraeber-debate/" target="_blank"></a><br />
</p>
<h5>&nbsp;</h5>
<h5>&ldquo;Those who said that the Egyptian revolution was peaceful did not see the horrors that police visited upon us, nor did they see the resistance and even force that revolutionaries used against the police to defend their tentative occupations and spaces: by the government's own admission, 99 police stations were put to the torch, thousands of police cars were destroyed, and all of the ruling party's offices around Egypt were burned down. Barricades were erected, officers were beaten back and pelted with rocks even as they fired tear gas and live ammunition on us . . . if the state had given up immediately we would have been overjoyed, but as they sought to abuse us, beat us, kill us, we knew that there was no other option than to fight back.&rdquo;</h5>
<h4 align="right">&ndash; <a href="http://occupywallst.org/article/solidarity-statement-cairo/" target="_blank">Solidarity statement from Cairo</a> to Occupy Wall Street, October 24, 2011</h4>
<!--<p align="right">&nbsp;</p>
<p align="center"><a href="http://cloudfront.crimethinc.com/images/violence/4b.jpg" rel="lightbox[violence]"><img src="http://cloudfront.crimethinc.com/images/violence/4a.jpg" width="500" height="375"/></a><em>
Windshield of a police cruiser in St. Louis on March 15, 2012 <br />
after police <a href="http://stlouis.cbslocal.com/2012/03/16/two-occupiers-injured-in-confrontation-with-st-louis-police/" target="_blank">brutally evicted a park occupation</a></em></p>-->
<p>&nbsp;</p>
<p>&nbsp;</p>
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1] Witness how police officers routinely charge arrestees with whatever violence they have inflicted upon them.</p>
<p>[2] For what it&rsquo;s worth, though Solnit alleges that we &ldquo;don&rsquo;t seem prepared to act,&rdquo; the authors of &ldquo;Dear Occupiers&rdquo; and this text are all lifelong participants in social movements, most of whom live well below the poverty line far from liberal Meccas like her San Francisco. This subject strikes very close to home for us: several of us have faced trumped up rioting charges&mdash;one for acting as a public liaison during an anti-gentrification demonstration, another for being tackled by police during a street parade&mdash;and many of us have dear friends in prison. We choose to write anonymously in part because, not being professional journalists, we can&rsquo;t count on employers not to discriminate against us for our political beliefs, and also because these beliefs attract more hostile attention from the authorities than those of Solnit or Hedges, but above all because we don&rsquo;t seek to found careers or personal fame on our efforts to change the world.</p>
</div>