<h1>What to Expect<br />from the Conventions</h1>
<h5>An Analysis of the Strategic Opportunities and Challenges Presented by the 2008 Democratic and Republican National Conventions</h5>
<h6><em>Prepared as a contribution to</em> <a href="http://www.inthemiddleofawhirlwind.info" target="_blank">In the Middle of a Whirlwind: 2008 Convention Protests, Movement and Movements</a>, <em>a project coordinated by <a href="http://www.warmachines.info" target="_blank">Team Colors</a> and published by</em> <a href="http://www.joaap.org" target="_blank">The Journal of Aesthetics and Protest</a></h6> 
<h3>The Short Answer</h3>
<p>If you plan to attend the demonstrations at the <a href="http://dncdisruption08.org/" target="_blank">Democratic</a> or <a href="http://nornc.org/" target="_blank">Republican</a>  National Conventions, you should already know what you intend to accomplish there and how you will go about it. If, for example, you intend to <a href="http://www.unconventionalaction.org/strategies/strategies.html" target="_blank">blockade a street</a>, you should already be in a committed affinity group, have picked out a location, and be hammering out the details. Things never go as planned, but preparation helps get things off on the right foot. If you haven&rsquo;t done any of this yet, there&rsquo;s still time, but get a move on&mdash;one thing that has been proven not to work at mass mobilizations is for everyone to show up hoping everyone else has done the work. 	</p><p>Doubtless, there will be some&mdash;perhaps ten, perhaps ten thousand&mdash;for whom the conventions are a life-changing experience, and others for whom they will be non-events. We get out of life what we put in. But one has to prioritize&mdash;so how important are these conventions, anyway? </p>
<h3>The Long Answer</h3>
<p>To answer this question, let us:</p>
<p>&bull; <a href="#return">reappraise the effectiveness of mass mobilizations in general</a><br />
&bull; <a href="#historical">consider the current context</a><br />
&bull; <a href="#or">scrutinize the motivations and infrastructures of both the organizers and the authorities</a><br />
&bull; <a href="#strategy">and examine the specific strategies that have been proposed for the protests.</a></p>
<p><strong>Advisory:</strong> The pernicious thing about analyses like this one is that, in framing human activity on the stage of world history rather than in terms of personal decisions and experiences, they present life through the wrong end of the telescope. Reading too many texts like this can convey the impression that the desires and actions of any given individual are insignificant in the grand scheme of things. In fact, we experience the world as individuals, not as a grand totality&mdash;each human being is literally the center of his or her world, and our treatises should start from this premise rather than obscuring it. There is no &ldquo;world history&rdquo; except for the sum total of all our individual lives. It can be useful to examine social and historical phenomena in hopes of making our efforts at resistance and liberation more strategic, but the center of gravity should always be your life.</p>
<p>&nbsp;</p>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/convention/convention1b.jpg" rel="lightbox[convention]"><img src="https://cloudfront.crimethinc.com/images/convention/convention1a.jpg" width="500" height="621"></a></p>
<a name="return" id="return"></a><h3>Return to Summit Demonstrations?</h3>
<p>As chronicled in our earlier report, <a href="http://crimethinc.com/texts/recentfeatures/demonstrating.php" target="_blank"><em>Demonstrating Resistance</em></a>, since the turn of the century the North American anarchist movement has gone through a turbulent love affair with mass actions, passing from heady infatuation to messy breakups, attempted reconciliations, and finally <a href="http://www.crimethinc.com/blog/2006/11/30/seattle-seven-years-later/" target="_blank">wistful nostalgia</a>. At first, following the WTO protests of 1999, mass mobilizations were taken for granted by many as<em> the</em> way to take on capitalism. Later, as bills came due in the form of legal troubles, burnout, and diminishing returns on previously effective tactics, it became popular to describe the mass action model as obsolete.<a class="footnote" href="javascript:void(0);" onclick="return overlib('We cannot consider this disenchantment outside the context of the antiwar movement, of course, which is examined in the following section.', CAPTION, '[1]');" onmouseout="nd();">[1]</a> Some of those who participated most enthusiastically in the heyday of summit-hopping subsequently brushed it off as a dead end. We must take their criticisms seriously, even if we factor in the disillusionment that typically comes with age and the tendency people have to condemn an approach in universal terms simply because they no longer wish to participate in it themselves. 	</p>
<p>Two of the most common adjectives critics use to describe mass mobilizations are <em>reactive</em> and <em>symbolic</em>. One can hardly argue with the former description. The tentative efforts that have been made to duplicate the mass mobilization model on a proactive basis, such as the 2002 <a href="http://www.infoshop.org/inews/article.php?story=02/11/20/2543557&amp;query=barricada%2Bboston" target="_blank">Fiesta del Pueblo in Boston</a> and the &ldquo;Fix Shit Up&rdquo; campaign in Georgia preceding the 2004 G8 summit, have not been promising; it seems that, at least for now, it is much easier to mobilize a great number of people against something than for something. Constantly responding to events organized by our enemies keeps us from taking the initiative and distracts us from manifesting examples of the world we wish to live in. But this does not mean there is no such thing as a good time to react, only that we must be judicious in picking when to do so. </p>
<p>The charge that mass mobilizations are symbolic is more complicated. What does it mean for something to be symbolic? The togetherness, visibility, and conflict with the forces of law and order that many of us have experienced at demonstrations were real enough. A militant march calling for the abolition of capitalism cannot immediately achieve its object, of course, but that doesn&rsquo;t mean it is <em>merely</em> symbolic&mdash;if it contributes to the development of a current of resistance, then it is as effective at its stated purpose as a grocery distribution might be. David Graeber has <a href="http://www.infoshop.org/inews/article.php?story=2007graeber-victory" target="_blank">argued persuasively</a>  that the upswing of anticapitalist mass mobilizations around the turn of the century was instrumental in bringing about major defeats for the WTO, FTAA, IMF, and World Bank. Certainly, the liberal antiwar marches organized since then have done nothing to halt the Iraq war, but this simply suggests that <em>some </em>mass mobilizations are merely symbolic while others are not. </p>
<p>One might argue that trade summits and political conventions are essentially media events&mdash;that they are themselves symbolic. According to this logic, even the most confrontational demonstrations only pit one spectacle against another, thus remaining within the field of political discourse rather than mounting a real attack on the root system of capitalism. This begs the question of what comprises the essential infrastructure of the capitalist system: is it only the labor of workers in factories, or does it also include the legitimacy people accord governments and laws, the illusion of the absence of dissent, the hypnosis of empty streets? Not to suggest that it is <em>more</em> important to confront capitalism on the level of rhetoric and representation than at the sites of production; but the Seattle WTO protests showed that the former approach can complement the latter in times of low revolutionary consciousness. 	</p>
<p>Anarchists with a taste for confrontation and property destruction have suggested that large-scale demonstrations have become so heavily policed since 9/11 that it is impossible to get away with anything. Whether or not this is true, one cannot evaluate the importance of this contention without establishing what the point of confrontation and property destruction is in the first place. </p>
<p>Clearly, anarchists cannot smash capitalism one window at a time; <a href="http://crimethinc.com/texts/recentfeatures/demonstrating.php" target="_blank">as has been pointed out before</a>, natural disasters regularly do tens of thousands of times more financial damage to corporations than anarchists ever have without bringing the downfall of capitalism any closer. The trashing of corporate shop fronts during the Seattle WTO protests contributed to the surge of anarchism in the US because it was a visible&mdash;even symbolic&mdash;statement, not because of the financial losses inflicted on Nike and Starbucks. The effectiveness of such actions cannot be measured in purely military or economic terms; they are powerful because they are visible and inspiring to others, expressing a dissident value system with a simple gesture that can be easily imitated.<a class="footnote" href="javascript:void(0);" onclick="return overlib('At the same time, they draw this power from directly attacking manifestations of the capitalist system, which they could not do if they were <em>merely</em> symbolic; thus these actions depend on a precarious combination of symbolic and concrete.', CAPTION, '[2]');" onmouseout="nd();">[2]</a> This contrasts sharply with the clandestine cell approach associated with the Earth Liberation Front, which maximizes material and financial damage while tending to isolate the confrontation from a broader social context. </p>
<p>Aspiring window-smashers who marched in frustration down streets lined with police have long fantasized about how much easier it would be to smash those windows without a public call to action tipping off the authorities. Yet it does not appear that most of those who withdrew from the mass action model in search of more effective approaches have found them. Despite calls for more clandestine action in the wake of the decline of mass mobilizations, autonomous direct action is hardly at a high point in the US right now. One of the essential characteristics of mass mobilizations is that the urgency and companionship enable participants to pass beyond their everyday limits; for a short time, they collectively produce and experience a different reality, and act accordingly. Without this feedback loop, it is much more difficult for many people to cross the threshold into serious action. 	</p>
<p>So is it more effective for one person to smash twenty windows on an empty street, or for twenty people to smash one window with the eyes of the world upon them? For that matter&mdash;is it safer to smash windows alone, or during a mass mobilization when lawyers are prepared to spring into action and police may be hard pressed to prove that they grabbed the <em>right</em> black-masked hoodlum? Is an example more infectious when it takes place in a typical suburban setting, or in a glamorous moment of collective activity? There may not be simple answers to these questions, but this indicates that those who desire contagious conflict with the state cannot simply brush off the value of mass mobilizations. 	</p>
<p>We cannot discuss the matter of visibility without addressing the role of the media. Mass mobilization is a risky strategy indeed if its effectiveness hinges on attention from corporate media; indeed, one of the great lessons of 9/11 was that a movement that depends on media coverage for its morale can be dispelled in a single day. Yet mass mobilizations lend themselves well to decentralized media; because so many witness them together, they are often documented by a multiplicity of voices in a way that smaller-scale actions rarely are. At best, this independent coverage can force the corporate media to pick up stories and stick closely to the facts, for fear of being upstaged or delegitimized by their underground competition. </p>
<p>Some critics feel that anarchists should focus on building up infrastructure, and that mass mobilizations simply distract from this. This poses a dichotomy that is contradicted by recent history. The <a href="www.indymedia.org" target="_blank">indymedia network</a>, arguably one of the most successful anti-authoritarian infrastructures in the world, came to be as a direct result of the WTO protests in Seattle. Likewise, though efforts to coordinate nationwide networks in the US for their own sake have all fizzled, consultas and chapters of <a href="http://www.unconventionalaction.org" target="_blank">Unconventional Action</a> have appeared all across the US over the past several months. By providing a massive challenge and a common goal, a successful mass mobilization can enable anarchists to make qualitative as well as quantitative advances in experience, connections, and capabilities. </p>
<p>So the most primitive&mdash;though not necessarily wrong-headed&mdash;argument for anarchists to invest themselves in demonstrating against the Democratic and Republican National Conventions is that it&rsquo;s been half a decade since the last major anarchist-organized mobilization. It&rsquo;s good to have them every once in a while so we can maintain visibility outside areas in which we have a lot of local activity. Summit-hopping is draining, but the occasional major action can be reinvigorating. </p>
<p>All this is not to say that we can count on a mass mobilization to inaugurate a new era of social struggle simply because this has occurred in the past. Let us now consider whether this summer is the most opportune juncture at which to hazard this experiment.</p>
<a name="historical" id="historical"></a><h3>The Historical Context</h3>
<h5>Some have charged that the antiwar movement<br />
failed because it was not empowering for<br />
the working class or people of color.<br />
This is a half-truth: the antiwar movement failed because it was not empowering for <em>anybody</em>.</h5>
<p>The so-called &ldquo;anti-globalization movement,&rdquo; named by corporate media with a vested interest in obscuring the possibility of modern-day anticapitalist struggle, emerged as if from nowhere in the late 1990s. In fact, it was the convergence of a wide variety of smaller social currents ranging from indigenous liberation struggles to the do-it-yourself punk scene, all of which had been quietly developing over the preceding years. Perhaps the most surprising accomplishment of the movement was to reintroduce and revitalize street-level conflict, which many had deemed irrelevant in the postmodern era. 	</p>
<p>The North American wing of this movement was not prepared for the sudden changes wrought by September 11, 2001; although the militant anti-IMF protest organized for that month became the first antiwar protest, anarchists lost the initiative to liberals and communists who were more familiar with single-issue antiwar organizing. To the glee of authoritarians of every stripe, the antiwar movement replaced the anticapitalist movement in the public eye between 2001 and 2003. 	</p>
<p>The antiwar movement of the following years was a colossal failure&mdash;perhaps the most colossal failure in the history of antiwar movements. Taken together, the demonstrations that took place worldwide on February 15, 2003 comprised the most widely attended protest in human history&mdash;and yet they did absolutely nothing to hinder the Bush administration. One might say it was a triumph of co-optation that so much outrage and motivation was diverted into ineffectual rituals, so soon after anticapitalists had demonstrated the power of direct action. To be fair, the effectiveness of the demonstrations of 1999-2001 did not become clear until years later when many were no longer paying attention. Also, there were scattered efforts to apply direct action in antiwar efforts, such as the targeting of recruitment centers and ports engaged in military shipping; these were simply too little too late. Imagine the effect if a mere tenth of the participants in the February 15 demonstrations had smashed recruiting center windows or blockaded ports! </p>
<p>Some have charged that the antiwar movement failed because it was not empowering for the working class or people of color. This is a half-truth: the antiwar movement failed because it was not empowering to <em>anybody</em>. The groups that dominated antiwar organizing did all they could to limit the tactics and strategies of participants to the lowest common denominator. Few will stick around in a movement that is not committed to or capable of accomplishing its professed objectives, and this is doubly true of people with limited resources who are all too familiar with being exploited for others&rsquo; gain. There were efforts to recruit working class people and people of color, but these rarely created mutually beneficial collaboration and dialogue. It could be charged that organizers sought to involve a wide range of demographics in order to present the movement as diverse, while still endeavoring to control its content and direction. Approaching the antiwar movement as an opportunity to create a mass under liberal leadership, rather than a chance to actually fight the war machine, actually undermined the possibility of it ever adding up to a durable, empowered mass. </p>
<p>By the middle of Bush&rsquo;s second term, public sentiment was acknowledged to be overwhelmingly against the war, and yet the antiwar movement had effectively collapsed. The tactic of mass mobilization, which liberals had hijacked from radicals, had accordingly been abandoned; protests still occurred, but none drew numbers worthy of the word &ldquo;mass.&rdquo; </p>
<h5>Now the antiwar movement has ceded the territory it took in 2002, and it&rsquo;s up to us to fill this vacuum.</h5>
<p>Today, liberal politics beyond the voting booth has been completely deflated by the failure of the antiwar movement. Liberal hopes are once again pinned on electoral politics, and the streets are as quiet as they were in the mid-1990s when neoconservatives were crowing that capitalism had triumphed as &ldquo;the end of history&rdquo; and the obsolescence of mass mobilizations was taken for granted by anarchists. This is to say: the liberal antiwar movement has ceded the territory it took in 2002, and if anarchists could fill this vacuum we might become major players once again. </p>
<p>Especially if a Democrat is elected to be the next President&mdash;but either way, really&mdash;anarchists now find ourselves in an explicitly oppositional position that brings out the differences between us and liberals as well as conservatives. If we are bold enough to take advantage of this&mdash;by practicing effective direct action rather than staging spectacles and recruiting drives, for example&mdash;we may be able to seize the initiative once again. Not being subsumed in a predominantly liberal opposition enables us to take the initiative to mobilize a real opposition beyond the dead ends of electoral politics and merely perfunctory protest. Many of those who participated sincerely in the antiwar movement must recognize its limitations; indeed, there seems to be some interest in the anarchist anti-RNC organizing among older antiwar activists in the Midwest. If we can demonstrate an effective alternative, we may earn new allies. </p>
<p>The political machine, having lost a lot of popular faith during the Bush years, is now attempting to recapture public attention through a gripping new electoral spectacle. We&rsquo;re to believe the fate of the world hangs in the balance, even as media focus on &ldquo;superdelegates&rdquo; and voting districts betray just how little influence any of us really have. Anarchists are the ones best equipped to counter this, and we should not miss the opportunity. We may not persuade everyone to become anarchists in 2008, but if we re-enter the public eye as the ones who saw it coming, when the inevitable disillusionment sets in following the election our model for contesting power outside the voting booth will be visible as an attractive alternative.</p>
<p>Electoral politics dominates the imaginations of people in the United States to an unparalleled degree. Whenever the question of social change arises, one is always pointed to the ballot box: <em>if you don&rsquo;t vote, you can&rsquo;t complain</em>, which is to say, <em>vote and shut up</em>. One might argue that there is no more strategic target for direct action than the conventions, which represent the total hegemony of the two-party system. Even opposition to the excesses of capitalism can still be re-absorbed into electoral politics&mdash;one of the major issues at the WTO protests was that the WTO could supersede the &ldquo;democratic process&rdquo; of participating nations. Only a direct attack on the electoral spectacle itself could reframe the terms of public discussion to foreground more effective approaches to self-determination. Powerful actions at the conventions could set a new tone for the coming years, setting a precedent for people using their own strength and energizing smaller-scale direct action organizing throughout the US.<a class="footnote" href="javascript:void(0);" onclick="return overlib('It goes without saying that without sustained local organizing towards long-range goals, we can&rsquo;t expect the convention protests to achieve anything at all, however dramatic they might be.', CAPTION, '[3]');" onmouseout="nd();">[3]</a></p>
<p>Right now we can still draw on the outrage arising from the Iraq war to mobilize people. After this election, it will be a moot point, part of history. If we play our cards right at this historical juncture, we can draw on the frustration of those who feel betrayed not only by Bush but also by the Democrats who acted as his accomplices and by the liberal antiwar movement that channeled dissent into a powerless dead end. The same goes for immigration and global warming&mdash;the Democrats are attempting to frame themselves as the ones who will save the world from climate change, and we owe it to everyone to call bullshit on this.</p>
<p>But are anarchists in the US prepared to organize an effective mass mobilization at this point? The new generation, who grew up on stories of the Seattle WTO protests, has never participated in anything comparable, however eager some are to do so. Likewise, though some survivors from the last generation have gone long enough without a major mobilization that they are interested in attempting another one, there is still a lot of inertia and hesitation. Many who have been disappointed before do not want to put all their eggs in this basket. So, having considered the reasons why the conventions might present a strategic target, let us turn to the drawbacks of focusing on them.</p>
<h3>Drawbacks to Focusing on the Conventions</h3>
<p>Dubious radicals who don&rsquo;t want anarchists to organize against the conventions have trotted forth the usual clich&eacute;s. One has even suggested that rather than targeting them with direct action we should be learning from Obama, whose campaign has supposedly ignited the hope of a nation.<a class="footnote" href="javascript:void(0);" onclick="return overlib('Our take on this, conversely, is that politicians like Obama are elevated to the national spotlight in times of increasing dissent and discontent, so that grassroots outrage is channeled back into institutional cooptation. That&rsquo;s <em>our power</em> they flaunt at us. Like everything else, it looks sexier on the other side of the television screen&mdash;but rather than coveting it there, we should focus on continuing to build it, not to mention resist their efforts to hijack it.', CAPTION, '[4]');" onmouseout="nd();">[4]</a> It&rsquo;s safe to say that if you&rsquo;re jealous of a politician&rsquo;s ability to hypnotize people into renewed faith in representative democracy but shrug off a nationwide grass-roots anarchist mobilization, you need to check your priorities as an anarchist. Remember, after the <a href="http://www.infoshop.org/page/J18" target="_blank">Global Day of Action on June 18</a>, 1999 that foreshadowed the WTO protests, there were anarchists who insisted that mass mobilizations had reached their peak and it was time to focus elsewhere. Someone is always bound to think the time isn&rsquo;t right. 	</p>
<p>Whether or not they are grounded in reality, these misgivings themselves constitute a drawback to focusing on the conventions, for a mass mobilization cannot succeed without widespread faith in its potential. It would not even be worth discussing the matter further if there were not hundreds&mdash;hopefully thousands&mdash;of other anarchists who are willing to take the chance. 	</p>
<p>Aside from the predictable criticisms, there are more substantive drawbacks to choosing the conventions as the site for a grudge match with hierarchical power. Successful mass actions can only be outgrowths from already thriving relationships and social currents; they offer the opportunity to measure our capacities, but it is unrealistic to expect them to produce powerful movements out of thin air. In this regard, it&rsquo;s not promising that these mobilizations come after years without much direct action organizing, when few anarchists have had the opportunity to develop their skills or networks. A summer of direct action training camps cannot make up for this; highly publicized calls for buildup actions might have done the trick, but the conventions are only a couple months away as of this writing. 	</p>
<p>There is something paradoxical about organizing a mass mobilization as an advertisement for direct action. Generally, whatever approach one adopts sets a precedent for more of the same; interrupting the electoral spectacle is not the same as creating empowering contexts for self-determination. As the party conventions only occur once every four years, successful demonstrations this summer have little risk of setting off another wave of summit-hopping; but it remains to be seen to what extent the somewhat abstract goal of &ldquo;breaking the spell of electoral politics&rdquo; can actually motivate people to put their bodies on the line. 	</p>
<p>On a related note, anarchists appear to have put more energy into strategizing the nuts and bolts aspects of the convention protests than into presenting a case for militant action there to the public at large. No plan that depends on mass participation can succeed if it is not persuasively put forward to great numbers of people. In this regard, it is fortunate that the first <a href="http://www.unconventionalaction.org/news/2007/12/13/the-unconventional-action-newspaper-is-out-at-last/" target="_blank">Unconventional Action paper</a> has been succeeded by a <a href="http://news.infoshop.org/article.php?story=20080514190337742" target="_blank">second paper focusing on a critique of electoral politics</a>. 	</p>
<p>It has been charged that mass mobilizations deplete a lot of energy that could otherwise be invested in more sustaining, sustainable ventures. This is especially true in the US, where direct action in general rarely provides the participants with resources besides <a href="http://www.infoshop.org/inews/article.php?story=20060610134717980&amp;mode=print" target="_blank">visibility and morale</a>. Though this may be an opportune juncture for a mass mobilization, it would be better if that mobilization did something to secure new resources for further direct action-based organizing. There have been <a href="http://crimethinc.com/texts/recentfeatures/reallyreally.php" target="_blank">examples of this</a> on the local scale in recent years; overseas, the riots in Denmark over the eviction of the social center Ungdomshuset provide a model for a nationwide mobilization aimed at securing space in which to nurture resistance movements. In the United States, however, no version of this approach has appeared on the national scale. </p>
<p>Were we facing a choice between a national mobilization aimed at securing immediate resources and the more visibility-oriented approach of the convention protests, it might be that the former would make more sense. But the fact is that no such possibilities are on the table at this point. Those who feel the time is right to return to the streets must make the best of the RNC/DNC protests; the more who do so, the more likely they are to turn out well. At worst, the conventions will be a sort of Groundhog Day at which anarchists will see their shadow and hide out for four more years.</p>
<a name="or" id="or"></a><h3>RNC or DNC?</h3>
<p> 	Ideally, the convention protests would be framed as a single mobilization, to emphasize the total rejection of party politics and so-called representation. This would make clear that our protests have nothing to do with the platforms of the individual candidates. If anything, insofar as the Democrats are expected to win the coming elections, it would probably be most strategic to focus on Denver, however thorny it might be working out how to demonstrate against an African-American or female presidential candidate. </p>
<p>Unfortunately, in the course of the past year, major differences have emerged between the local organizing in Denver and St. Paul. It now appears that, as in 2004, the demonstrations at the RNC will be several orders of magnitude larger than those at the DNC. Like it or not, we must take this into account. 	</p>
<p>In Denver, which will host the Democratic National Convention at the end of August, anarchist organizing has taken place in the shadow of <a href="http://www.recreate68.org" target="_blank">Recreate 68</a>, a coalition of liberal and radical groups. This has manifested itself most recently with the cancellation of one of <a href="www.dncdisruption08.org" target="_blank">Unconventional Denver&rsquo;s</a> two primary days of action, despite two nationwide consultas and months of planning, at the request of an immigrant and Chicano rights coalition. The anarchist community in Denver has appeared at times to be approaching the convention protests as a local rather than national event; the handful of organizers who have taken the DNC on as a serious project are overextended by all accounts. 	</p>
<p>In the Twin Cities, on the other hand, anarchists are involved explicitly in every level of the organizing in a way we haven&rsquo;t seen since the successful <a href="http://www.infoshop.org/octo/ftaa.html" target="_blank">FTAA protests in Quebec of April 2001</a>. The <a href="http://www.nornc.org" target="_blank">RNC Welcoming Committee</a>, an explicitly anti-authoritarian organizing group, has for well over a year already, and has established relationships of mutual respect and collaboration with broader antiwar organizations throughout the region&mdash;an achievement that has eluded other anarchist organizers for years. We may not be blessed with an organizing group as creative and diligent as the Welcoming Committee any time soon&mdash;all the more reason for anarchists to take advantage of their groundwork. </p>
<p>The surge in anarchist traveling culture that coincided with the publication of <a href="http://www.crimethinc.com/books/evasion.html" target="_blank"><em>Evasion</em></a> is long past; nowadays most anarchists can only be away from their communities for limited periods of time, so they have to choose carefully which national events to attend. Most will probably choose the RNC over the DNC, deeming Denver a tragic but unavoidable missed opportunity.</p>
<p> This does not mean there is no potential for demonstrations at the DNC. Even a small but exciting action in Denver could serve the important purpose of heightening expectations and morale for St. Paul. Hopefully at least a moderate number of highly motivated anarchists from the surrounding region will converge in Denver with a plan for making something memorable occur. </p>
<p>Failing all else, being the main news at the RNC will frame us as the true opponents of the unpopular Republicans and thus distinguish us from the Democratic Party. Democrats will not be happy about a major confrontation in St. Paul, for fear that it could distract attention from their electoral efforts and portray opponents of Republican policies as streetfighting militants. Besides, if the Democrats do win the election, we can always deal with them at the inauguration.</p>
<h3>On the Other Side of the Barricades</h3>
<p> 	While anarchists are organizing for the conventions, what&rsquo;s going on in boardrooms and at police trainings? What strategies can we expect the authorities to apply at the conventions, and what factors may tie their hands? 	</p>
<p>Both Minneapolis and St. Paul have liberal governments that need to come across as supportive of law-abiding protesters; in this regard, healthy relations between anarchists and other antiwar organizers constitute a real challenge for them. Officials have emphasized that the police will be civil&mdash;not starting in riot gear; that there will be no &ldquo;free speech zones&rdquo;&mdash;demonstrators will be allowed &ldquo;within sight and sound&rdquo; of the Excel Center hosting the RNC; and that the police strategy will not resemble the brutal &ldquo;<a href="http://en.wikipedia.org/wiki/Miami_model" target="_blank">Miami model</a>&rdquo; applied at the 2003 FTAA protests, but rather will establish a new &ldquo;St. Paul model.&rdquo; It&rsquo;s also worth pointing out that St. Paul will be fielding about 3000 police, compared to the tens of thousands on duty in New York City during the 2004 RNC. 	</p>
<p>The climate has definitely shifted over the past four years. Following the 2003 FTAA protests, the brutal tactics used by Miami police chief John Timoney&mdash;who had been police commissioner in Philadelphia during the 2000 RNC&mdash;fell out of favor. Shortly before the 2004 RNC, the &ldquo;Timoney three,&rdquo; three protesters who had been badly beaten by Timoney and then charged with multiple felonies at the preceding RNC, were declared innocent. The policing at the 2004 RNC in New York was extremely intimidating, but comparatively restrained&mdash;presumably it would not have served the interests of those in power for major confrontations to erupt there. Since then the tide has flowed back to the left in the United States, and the authorities must be preparing for new management. In Washington, DC, the police who were so quick to make mass arrests at events like the 2002 IMF protests have subsequently had to restrain themselves after a series of successful lawsuits; at the antiwar protests last March 19, they were so hesitant to make arrests that many concluded they were only targeting those who committed felonies. 	</p>
<p>All this could change overnight if the powers that be saw a significant threat to their ascendancy; but it suggests that compelling the police to use force at the conventions this summer would be a coup, in that it would frame them as aggressors in a time when they are trying to dispel that image. Rumor has it that the St. Paul police are consulting European police forces for tips on how to control crowds via containment rather than brute force. We should strategize accordingly. 	</p>
<p>Going into the 2004 RNC protests, many feared that the police would be as brutal as they had been at the FTAA protests the preceding year; coming out of them, some felt that the police had set out to avoid such gratuitous use of force, and that it would have been a victory rather than a defeat to compel them to beat and tear gas people in downtown New York City during such a highly televised event. It may be that we don&rsquo;t need to succeed in actually shutting down the convention in St. Paul this summer to deal a blow to our enemies and seize the attention of the world; we need only provoke a serious confrontation with the police.</p>
<a name="strategy" id="strategy"></a><h3>The Strategy</h3>
<p align="center"><a href="https://cloudfront.crimethinc.com/images/convention/convention2b.jpg" rel="lightbox[convention]"><img src="https://cloudfront.crimethinc.com/images/convention/convention2a.jpg" width="500" height="369"></a></p>
<p> Some felt that the 2004 RNC protests were unsuccessful because there was no clear, unified anarchist strategy; anarchists participated by the thousands, but by and large only swelled the numbers at liberal events or got arrested in symbolic gestures. <a href="http://www.unconventionalaction.org" target="_blank">The Unconventional Action</a> network appears to have begun as a reaction to this, in order to formulate a coherent strategy for this summer&rsquo;s convention protests. Unconventional Action groups, along with the RNC Welcoming Committee and anarchist organizers in Denver, have fallen back on the consulta model previously used in the buildup to the 2003 FTAA protests in order to give a semblance of participatory transparency to the process of establishing a strategy. It must be said that this model is at its most effective and appropriate when it is utilized by longstanding groups with shared experience and accountability, rather than new ad hoc groups and atomized individuals with little real accountability or coherence. 	</p>
<p>As the strategy for the DNC protests is being reworked as this is written, it&rsquo;s not possible to say much about it for certain. For now, our analysis must focus on the RNC protests, for good or for ill. 	</p>
<p>So, following a full year of regional and national strategy consultas, the RNC strategy that has been consensed upon by groups nationwide is&hellip; shutting it down via blockading. This may strike those who remember the summit protests of the turn of the century as a failure of imagination; since the fluke of the 1999 WTO protests, no blockading strategy has succeeded in shutting down a meeting or convention, though this has been attempted countless times from Gleneagles to Australia. 	</p>
<p>So why blockading? First, it gives protesters something concrete to do. Perhaps it would have been better if some other proposal had taken hold, offering some new experiment; but at least people are talking about collective direct action again. Even if the blockading is not entirely successful, the experience of attempting to achieve a concrete goal rather than simply participate in symbolically making a statement will shape the organizing for this and future events. A successful organizing campaign towards blockading could promote an orientation towards proactive direct action among demonstrators for years to come, regardless of the success of the actual blockading at the RNC. </p>
<p>Similarly, protests will only have a chance of seriously disrupting the RNC if they are able to involve a great number of people coming from a wide variety of perspectives, abilities, and comfort levels. Blockading is an extremely versatile tactic; in fact it is not one tactic at all, but a category including a wide selection of tactics ranging from nonviolent civil disobedience to all-out streetfighting. Despite the apparent stalemate of the post-WTO years, no comparably broad and participatory approach for coordinating direct action has appeared. 	</p>
<p>Combined with the outlying locations of most hotels, <a href="http://www.rncwelcomingcommittee.org/wp-content/uploads/2008/02/stp_map6_location_web.jpg" target="_blank">the geography of downtown St. Paul </a> is potentially conducive to successful blockading. Considering the tremendous number of delegates who must be able to reach the convention center and the comparatively small number of police that will be in St. Paul, it seems that blockading could actually succeed if enough people participate. If this is an approach that could work in St. Paul but not in another city, it&rsquo;s important that we not miss this opportunity. There is a significant difference between attempting to prevent eight people in helicopters from reaching a convention center, as demonstrators attempted at the 2005 and 2007 G8 summits, and stopping tens of thousands of delegates and assorted hangers-on traveling by bus or car. In this case, it should only be necessary to stop a fraction of them to prevent the convention from moving forward. </p>
<p>Like the emphasis on strategy, it is possible that the blockading approach has reappeared in reaction to anarchist strategies at the 2004 RNC, some of which focused on harassing the delegates themselves. Blockading indicates that the important target is the political machine itself, not the individuals who make it up; conversely, attacking the delegates frames the protest as a private conflict between specialized individuals&mdash;protesters and politicians&mdash;rather than a conflict between people and institutions. Belligerent protesters are hardly going to change the minds of the delegates, and even if they could, those delegates would only be replaced with others more loyal to the party officials and their corporate masters. Targeting the delegates has sometimes been framed as an application of the &ldquo;<a href="http://en.wikipedia.org/wiki/Stop_Huntingdon_Animal_Cruelty" target="_blank">SHAC model</a>&rdquo; from the animal liberation movement, in which individuals who do business with animal abusers are targeted personally. This is a thoughtless error, for the SHAC model presupposes that those targeted can take their business elsewhere, whereas the essence of the US political machine is that there is only one route to power. </p>
<p>To return to blockading&mdash;entirely apart from its effectiveness at shutting out delegates, successfully shutting down even a part of downtown St. Paul would be experienced by the participants as a hugely empowering event. It&rsquo;s possible, if the blockades are successful, that police will attack them in some places while ignoring other zones&mdash;that was the approach they utilized at last summer&rsquo;s G8 protests in Germany. During the brainstorming phase of the strategy discussions of the past year, one running theme was the establishment of autonomous zones; creating such a zone in direct confrontation with the authorities would be significantly more inspiring than simply creating an autonomous zone somewhere else with their implicit permission. </p>
<p>Speaking of autonomous zones, blockading can open up space for other tactics that are otherwise much more difficult to utilize; property destruction and street parties are two obvious examples. In this regard, whether or not they serve any other purpose, successful blockades enable participants to apply a diversity of tactics. </p>
<p>Finally, if serious blockading is to be an option, it must be organized months in advance, whereas other approaches can be put together with less warning. It might turn out that blockading is not the most effective strategy for the RNC protests, and the participants must shift direction at the last minute; but for it even to be a possibility in St. Paul this coming September, it is necessary that organizers be preparing for it right now. Only time will tell whether it proves to be an effective approach, or for that matter whether this summer&rsquo;s convention protests will be effective at all; but this is also up to us.</p>
<h3>What Constitutes Victory?</h3>
<p> As suggested above, it may not be necessary to successfully shut down the DNC and RNC to achieve the goals of this summer&rsquo;s protests; it may suffice to make a valiant, sincere effort. None of the major mobilizations of 2000, such as the IMF/World Bank protests in Washington, DC and the RNC in Philadelphia, succeeded in shutting down their targets. At the time, this was regarded with mixed feelings, but if a mobilization of comparable scale were to take place this year, it would be a massive achievement, proof that the anarchist movement in North America has neither dissipated nor given up on confronting hierarchical power in the streets. The point is not to bring back the obsession with summit hopping that characterized the anarchist movement eight years ago, but to demonstrate that we can utilize that approach when it is strategic, as a complement to our ongoing efforts in other contexts. History is opening a window to us right now, should we desire to take advantage of it. </p>
<p>See you, once again, in the streets.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h3>Additional References</h3>
<p> <a href="http://www.infoshop.org/inews/article.php?story=20070613014901381&amp;query=unconditional%2Bfaction" target="_blank">Unconditional Faction</a> &ndash; A hilarious satire regarding why <em>not</em> to target the conventions</p>
<p> <a href="http://www.infoshop.org/inews/article.php?story=20080407201602210&amp;query=blockading%2BRNC%2BWelcoming%2Bcommittee" target="_blank">Why Blockading</a> &ndash; A text from the RNCWC regarding the reasoning behind the blockading strategy</p>
<p><a href="http://libcom.org/library/ending-war-inventing-movement-mayday-1971" target="_blank">Ending a War: Inventing a Movement: Mayday 1971</a> &ndash; A historical reference point for what happened <em>last time</em> a mass mobilization focused on decentralized blockading near the end of an antiwar movement&mdash;or <a href="http://www.zinelibrary.net/maydaylakauffman.pdf" target="_blank">download the PDF</a> </p>
<div id="footnoteprint">
<br />
<br />
<br />
<p>[1] We cannot consider this disenchantment outside the context of the antiwar movement, of course, which is examined in the following section.
</p>
<p>[2] At the same time, they draw this power from directly attacking manifestations of the capitalist system, which they could not do if they were <em>merely</em> symbolic; thus these actions depend on a precarious combination of symbolic and concrete.</p>
<p>[3]  It goes without saying that without sustained local organizing towards long-range goals, we can&rsquo;t expect the convention protests to achieve anything at all, however dramatic they might be.</p>
<p>[4]  Our take on this, conversely, is that politicians like Obama are elevated to the national spotlight in times of increasing dissent and discontent, so that grassroots outrage is channeled back into institutional cooptation. That&rsquo;s <em>our power</em> they flaunt at us. Like everything else, it looks sexier on the other side of the television screen&mdash;but rather than coveting it there, we should focus on continuing to build it, not to mention resist their efforts to hijack it.</p>
</div>