* Creating a TCE language translation
** Prerequisites
*** Data Gathering
    1. determine the 2-letter language code for the language you are adding
       * https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
    2. decide on the new url (=crimethinc.com/tce/foobar=)
       * we go with the name of the language *in that language*. For example, Spanish is =crimethinc.com/tce/espanol/=
    3. determine if the language is written left-to-right or right-to-left (=ltr= or =rtl=)
       * Wikipedia is a good way to figure this out
*** Software needed
    You will need a few tools mostly for processing the PDF and creating the image assets.
**** Image processing
     - GIMP, Photoshop, or really any program that can crop images
     - Imagemagick: for creating the various sized versions of the images)
     - pdfimages: for pulling image assets out of the PDF
**** Text processing 
     - pdftotext: for pulling the text out of the PDF
** Getting up and running
   You can run the =to_change_everything= generator to get some of the basic wiring set up:
   #+BEGIN_SRC sh
     rails generate to_change_everything LANG_CODE URL [LANG_DIRECTION] [options]
   #+END_SRC
   This generator will:
     - create a language-specific css file
     - add url to =to_change_everything_controller=
     - add a translation yaml

   After running the generator run the server (*you will need to restart the server if it was already running*) and try navigating to your new page.
** Slotting in the text
   1. Obtain the pdf version of the language
   2. Run this command in the terminal to extract the text:
      #+BEGIN_SRC sh
        pdftotext the-pdf-file.pdf the-pdf-file.txt
      #+END_SRC
   3. Using the pdf as a guide, put the corresponding text in the corresponding section of the new yaml file
      * wrap every paragraph in html =<p></p>= tags
      * include any internal html tags needed (e.g. =<em>=)
      * every line should be a single line (yes, some will be very long)
** prepare the images
   woof
** customize the CSS
   ¡GLHF!
** polish
   There are certain things that vary language-to-language. We will just try to work through them on the PR, but some examples are:
*** pdf has a custom font 
    You can usually determine what font the PDF is using via this terminal command:
    #+BEGIN_SRC sh
      strings the-tce.pdf | grep FontName
    #+END_SRC
