name: Pull Request Labeler

on:
  - pull_request

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Labeler
        uses: actions/labeler@v4.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
