on: [push]

name: Tests, System

jobs:
  run:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB_NAME: crimethinc_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        # needed because the postgres container does not provide a healthcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_DB_NAME: crimethinc_test
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres

    steps:
      - name: Install system libraries
        run: sudo apt-get update && sudo apt-get install -y -qq --no-install-recommends libpq-dev libvips-dev

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Set up Ruby
        uses: ruby/setup-ruby@master
        with:
          bundler-cache: true

      - name: Configure database
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: bundle exec rails db:create

      - name: Run tests
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: bundle exec rspec spec/system
